### ISSUE TITLE
Just upgraded to 3.4.0 and getting segfault

### ISSUE THREAD

**Issue by eterry1388** [e2guardian/e2guardian#103]
/var/log/syslog shows this when I go to a website:

`Jan 29 11:32:40 vpn-1 kernel: [  433.852571] e2guardian[2099]: segfault at 48b17d0 ip 000000000043649f sp 00007fff9069bc00 error 4 in e2guardian[400000+bc000]`

If the site is TRUSTED or DENIED there is no exception and the page is returned back to the client.  Otherwise this segfault happens and the client gets no data back.

**Comment by fredbcode** [comment]
Which OS ? With or without SSLMITM ?

**Comment by fredbcode** [comment]
Which OS ?

**Comment by eterry1388** [comment]
Without SSLMITM on Ubuntu 14.04

**Comment by fredbcode** [comment]
your compilation options ?

**Comment by eterry1388** [comment]
I had 3.2.0 installed with the `.deb` file.  I then downloaded the 3.4.0 `.deb` file and used `dpkg -i` to install it.  I didn't compile anything.

**Comment by fredbcode** [comment]
Maybe I made a mistake with 3.4.0 but I had only tested with Debian wheezy and Jessie
Please can try to build a binary ?

With this packages:

Build-Depends: base-files, base-passwd, bash, coreutils, dash, debianutils, diffutils, dpkg, e2fsprogs, findutils, grep, gzip, hostname, ncurses-base, ncurses-bin, perl-base, sed, login, sysvinit-utils, sysvinit, tar, bsdutils, mount, util-linux, libc6-dev , libc-dev, gcc , g++ , make, dpkg-dev , autotools-dev, debhelper , dh-autoreconf, dpatch , libclamav-dev , libpcre3-dev, zlib1g-dev, pkg-config, libssl-dev

And this commands

Eg:
./autogen.sh && ./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--enable-locallists=yes' && make

You should create a binary with a maxchildren value of 1024
After just copy the binary src/e2guardian in /usr/sbin

Thanks

**Comment by fredbcode** [comment]
Hi 
Can you make a try with this binary ? http://www.megafileupload.com/agqK/e2guardian

**Comment by fredbcode** [comment]
Can you make a try with this package https://github.com/e2guardian/e2guardian/releases/download/untagged-d4525540d6740f3bfd79/e2guardian_3.4.0.1_wheezy-jessie_amd64.deb

**Comment by fredbcode** [comment]
Sorry wrong link http://www.megafileupload.com/65cp/e2guardian_3.4.0.1_wheezy-jessie_amd64.deb

**Comment by mortim3r** [comment]
Ce paquet semble fonctionner. J'ai supprimé l'ancien avec un dpkg -P, puis installé le nouveau.
Couplé avec un squid 3.4.8, avec des configuration de base : pas de ssl, pas de blacklist ...
Je testerai avec de la conf un peu plus évoluée dans les prochains jours.
Très beau travail que vous faites, merci.

**Comment by fredbcode** [comment]
Ok, for english reader: it works, I will release 3.4.0.1 soon

**Comment by fredbcode** [comment]
Fixed 3.4.0.1
