### ISSUE TITLE
e2guardian -g failed and stop e2guardian

### ISSUE THREAD

**Issue by tachtler** [e2guardian/e2guardian#104]
Hi,

Still on Version 3.3.2, after using following command, e2guardian will stop working:
`# e2guardian -g`

See messages from systemctl status e2guardian.service:

e2guardian[26973]: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
e2guardian[26973]: Reconfiguring E2guardian: done
e2guardian[26973]: Reconfiguring E2guardian: gentle reload starting
e2guardian[26973]: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
e2guardian[26973]: Reconfiguring E2guardian: done
e2guardian[26973]: Reconfiguring E2guardian: gentle reload starting
e2guardian[26973]: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
systemd[1]: e2guardian.service: main process exited, code=killed, status=11/SEGV
systemd[1]: Unit e2guardian.service entered failed state.
systemd[1]: e2guardian.service failed.

When I do the following commands, e2guardian will start and will be stable working:
`# systemctl start e2guardian.service`
OR
`# systemctl restart e2guardian.service`
The file **/etc/e2guardian/e2guardianf1.conf** seems to be correct, because e2guardian will start!

Maybe I can sent more configuration files, if it is necessary?

Please can you help.

Klaus.

**Comment by fredbcode** [comment]
> Hi,
>
> Still on Version 332, after using following command, e2guardian will 
> stop working:
>

You mean 3.2.0 ?

> ||
>
> The file */etc/e2guardian/e2guardianf1conf* seems to be correct, 
> because e2guardian will start!
>

And start/stop works ?

**Comment by tachtler** [comment]
Hi,

yes start/stop/restart still works.

Klaus.

Am 30. Januar 2016 18:51:41 MEZ, schrieb Fredb <notifications@github.com>:
>
>> Hi,
>>
>> Still on Version 332, after using following command, e2guardian will 
>> stop working:
>>
>
>You mean 3.2.0 ?
>
>> ||
>>
>> The file */etc/e2guardian/e2guardianf1conf* seems to be correct, 
>> because e2guardian will start!
>>
>
>And start/stop works ?
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/104#issuecomment-177260522

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

--

------------------------------------------
e-Mail  : klaus@tachtler.net
Homepage: http://www.tachtler.net
DokuWiki: http://www.dokuwiki.tachtler.net
------------------------------------------

**Comment by tachtler** [comment]
Hi,

today, my colleague make a new rpm package to version 3.4.0 and I installed the package now.

**BUT:** Same issue with the versions before!

With
`# e2guardian -g`
the e2guardian try's 3 times to opening filter group config: `/etc/e2guardian/e2guardianf1.conf` and after 3 errors, the main process stop working.

When I do `systemctl stop e2guardian.service`, `systemctl start e2guardian.service` or `systemctl restart e2guardian.service`, everything works fine, as expected.

Klaus.

**Comment by fredbcode** [comment]
Unfortunately I can't reproduce here with Debian Jessie 64 bits

more /run/systemd/generator.late/e2guardian.service 
# Automatically generated by systemd-sysv-generator

[Unit]
SourcePath=/etc/init.d/e2guardian
Description=LSB: e2guardian configuration
Before=runlevel2.target runlevel3.target runlevel4.target runlevel5.target shutdown.target
After=remote-fs.target network-online.target systemd-journald-dev-log.socket
Wants=network-online.target
Conflicts=shutdown.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=no
SysVStartPriority=17
PIDFile=/var/run/e2guardian.pid
ExecStart=/etc/init.d/e2guardian start
ExecStop=/etc/init.d/e2guardian stop

root@test:/tmp# e2guardian -g
root@test:/tmp# systemctl status e2guardian
● e2guardian.service - LSB: e2guardian configuration
   Loaded: loaded (/etc/init.d/e2guardian)
   Active: active (running) since lun. 2016-02-01 00:00:38 CET; 10h ago
  Process: 19138 ExecStop=/etc/init.d/e2guardian stop (code=exited, status=0/SUCCESS)
  Process: 19241 ExecStart=/etc/init.d/e2guardian start (code=exited, status=0/SUCCESS)
 Main PID: 19328 (e2guardian)
   CGroup: /system.slice/e2guardian.service
           ├─ 4344 /usr/sbin/e2guardian
           ├─ 4345 /usr/sbin/e2guardian
           ├─ 4346 /usr/sbin/e2guardian
           ├─ 4347 /usr/sbin/e2guardian
           ├─ 4348 /usr/sbin/e2guardian
           ├─ 4349 /usr/sbin/e2guardian
           ├─ 4350 /usr/sbin/e2guardian
           ├─ 4351 /usr/sbin/e2guardian
           ├─ 4352 /usr/sbin/e2guardian
           ├─ 4353 /usr/sbin/e2guardian
           ├─ 4354 /usr/sbin/e2guardian
           ├─ 4355 /usr/sbin/e2guardian
           ├─ 4356 /usr/sbin/e2guardian
           ├─ 4357 /usr/sbin/e2guardian
           ├─ 4358 /usr/sbin/e2guardian
           ├─ 4359 /usr/sbin/e2guardian
           ├─ 4360 /usr/sbin/e2guardian
           ├─ 4361 /usr/sbin/e2guardian
           ├─ 4362 /usr/sbin/e2guardian
           ├─ 4363 /usr/sbin/e2guardian
           ├─ 4370 /usr/sbin/e2guardian
           ├─ 4371 /usr/sbin/e2guardian
           ├─ 4372 /usr/sbin/e2guardian
           ├─ 4373 /usr/sbin/e2guardian
           ├─ 4374 /usr/sbin/e2guardian
           ├─ 4375 /usr/sbin/e2guardian
           ├─ 4376 /usr/sbin/e2guardian
           ├─ 4377 /usr/sbin/e2guardian
           ├─ 4378 /usr/sbin/e2guardian
           ├─ 4379 /usr/sbin/e2guardian
           ├─ 4380 /usr/sbin/e2guardian
           ├─ 4381 /usr/sbin/e2guardian
           ├─ 4382 /usr/sbin/e2guardian
           ├─ 4383 /usr/sbin/e2guardian
           ├─ 4384 /usr/sbin/e2guardian
           ├─ 4385 /usr/sbin/e2guardian
           ├─ 4386 /usr/sbin/e2guardian
           ├─ 4387 /usr/sbin/e2guardian
           ├─ 4388 /usr/sbin/e2guardian
           ├─ 4389 /usr/sbin/e2guardian
           ├─ 4393 /usr/sbin/e2guardian
           ├─ 4394 /usr/sbin/e2guardian
           ├─ 4395 /usr/sbin/e2guardian
           ├─ 4396 /usr/sbin/e2guardian
           ├─ 4397 /usr/sbin/e2guardian
           ├─ 4398 /usr/sbin/e2guardian
           ├─ 4399 /usr/sbin/e2guardian
           ├─ 4400 /usr/sbin/e2guardian
           ├─ 4401 /usr/sbin/e2guardian
           ├─ 4402 /usr/sbin/e2guardian
           ├─ 4403 /usr/sbin/e2guardian
           ├─ 4404 /usr/sbin/e2guardian
           ├─ 4405 /usr/sbin/e2guardian
           ├─ 4406 /usr/sbin/e2guardian
           ├─ 4407 /usr/sbin/e2guardian
           ├─ 4408 /usr/sbin/e2guardian
           ├─ 4409 /usr/sbin/e2guardian
           ├─ 4410 /usr/sbin/e2guardian
           ├─ 4411 /usr/sbin/e2guardian
           ├─ 4412 /usr/sbin/e2guardian
           ├─ 4415 /usr/sbin/e2guardian
           ├─ 4416 /usr/sbin/e2guardian
           ├─ 4417 /usr/sbin/e2guardian
           ├─ 4418 /usr/sbin/e2guardian
           ├─ 4512 /usr/sbin/e2guardian
           ├─ 4513 /usr/sbin/e2guardian
           ├─ 4514 /usr/sbin/e2guardian
           ├─ 4515 /usr/sbin/e2guardian
           ├─ 4516 /usr/sbin/e2guardian
           ├─ 4517 /usr/sbin/e2guardian
           ├─ 4518 /usr/sbin/e2guardian
           ├─ 4519 /usr/sbin/e2guardian
           ├─ 4520 /usr/sbin/e2guardian
           ├─ 4521 /usr/sbin/e2guardian
           ├─ 4522 /usr/sbin/e2guardian
           ├─ 4523 /usr/sbin/e2guardian
           ├─ 4524 /usr/sbin/e2guardian
           ├─ 4525 /usr/sbin/e2guardian
           ├─ 4526 /usr/sbin/e2guardian
           ├─ 4527 /usr/sbin/e2guardian
           ├─ 4528 /usr/sbin/e2guardian
           ├─ 4529 /usr/sbin/e2guardian
           ├─ 4530 /usr/sbin/e2guardian
           ├─ 4531 /usr/sbin/e2guardian
           ├─19328 /usr/sbin/e2guardian
           └─19329 /usr/sbin/e2guardian

févr. 01 00:00:38 test e2guardian[19241]: Starting e2guardian: e2guardian.
févr. 01 00:00:40 test e2guardian[19328]: Started sucessfully.
févr. 01 00:00:40 test e2guardian[19328]: Monitorhelper called: /etc/e2guardian/scripts/monitor_helper start
févr. 01 10:09:06 test e2guardian[19328]: Reconfiguring E2guardian: gentle reload starting
févr. 01 10:09:36 test e2guardian[19328]: Reconfiguring E2guardian: gentle reload completed
févr. 01 10:12:25 test e2guardian[19328]: Reconfiguring E2guardian: gentle reload starting

Can you share your files ?

**Comment by tachtler** [comment]
Hi Fred,

yes I can share my files... which one?

Klaus.

[e2guardian.conf.txt](https://github.com/e2guardian/e2guardian/files/111982/e2guardian.conf.txt)
[e2guardianf1.conf.txt](https://github.com/e2guardian/e2guardian/files/111983/e2guardianf1.conf.txt)

**Comment by fredbcode** [comment]
All please, /etc/e2guardian and your list (blacklist/whitelist)

**Comment by tachtler** [comment]
Hi,

can I sent you the config files, I wouldn't post it here on github?

Klaus.

**Comment by fredbcode** [comment]
You can take my PM numsys - no_spam - @ - no_spam - free.fr

**Comment by fredbcode** [comment]
Okay I made a test, no problem here with two differences (except that I'm using debian)
No clamav, no SSLMITM

Can you try without clamav and without SSLMITM (all SSLMITM lines commented) ?

**Comment by philipianpearce** [comment]
This is a well-known issue with dansg/e2g.

It is because e2g starts as root and then once all files are read in changes uid to the e2guardian user.
So all the configuration and list file paths must be readable by the user e2guardian runs as.
The most secure way to do this is to have the files owned by the e2guardian user, with permissions of 600 and directories in path 750 as you do not normally want ordinary users reading the files.

If they are not you will get this error.  It will start OK, because it is able to read files while uid is root, but -g will fail as e2g once it has dropped suid no longer has permission to read the files.

**Comment by tachtler** [comment]
Hi Phillip,

The file system rights are:
```
# ll -d /etc/e2guardian
drwxr-xr-x 6 root root 4096 Feb 11 14:10 /etc/e2guardian
```
and the file permissions are:
```
# ls -l e2guardian*.conf
-rw-r--r-- 1 root root 27923 Feb  1 09:15 e2guardian.conf
-rw-r--r-- 1 root root 19496 Feb  1 09:16 e2guardianf1.conf
-rw-r--r-- 1 root root 19406 Jul 21  2015 e2guardianf2.conf
-rw-r--r-- 1 root root 19749 Feb  6 07:04 e2guardianf3.conf
-rw-r--r-- 1 root root 19582 Jul 21  2015 e2guardianf4.conf
-rw-r--r-- 1 root root 19570 Jul 21  2015 e2guardianf5.conf
-rw-r--r-- 1 root root 19570 Jul 21  2015 e2guardianf6.conf
```
So the user e2guardian must be able to read the files, or I'm wrong?

Thank you!

**Comment by fredbcode** [comment]
> ls -l e2guardian*.conf

There is nothing else ?

ls -l /etc/e2guardian/

And about your lists ?

**Comment by tachtler** [comment]
Hi Fred,

of course there are some more files: I typed ls -l /etc/e2guardian/e2guardian*.conf
The whole list are:
```
# ls -l /etc/e2guardian
total 204
drwxr-xr-x 2 root root   122 Feb  1 09:09 authplugins
drwxr-xr-x 2 root root   116 Feb  1 09:09 contentscanners
drwxr-xr-x 2 root root    61 Feb  1 09:09 downloadmanagers
-rw-r--r-- 1 root root 27923 Feb  1 09:15 e2guardian.conf
-rw-r--r-- 1 root root 26947 Jan 29 13:33 e2guardian.conf.orig
-rw-r--r-- 1 root root 19496 Feb  1 09:16 e2guardianf1.conf
-rw-r--r-- 1 root root 19269 Jan 29 13:33 e2guardianf1.conf.orig
-rw-r--r-- 1 root root 19406 Jul 21  2015 e2guardianf2.conf
-rw-r--r-- 1 root root 19749 Feb  6 07:04 e2guardianf3.conf
-rw-r--r-- 1 root root 19582 Jul 21  2015 e2guardianf4.conf
-rw-r--r-- 1 root root 19570 Jul 21  2015 e2guardianf5.conf
-rw-r--r-- 1 root root 19570 Jul 21  2015 e2guardianf6.conf
drwxr-xr-x 8 root root  4096 Feb  1 09:09 lists
```

Klaus.

**Comment by fredbcode** [comment]
And no problem in lists or others ?

**Comment by tachtler** [comment]
Hi Fred,

I found my problem! - The /etc/e2guardian/lists/blacklist/* - files had the permission 750 - now I changed my update-script to set the file permission to 755 and now it works!
`
# e2guardian -g`
and
```
# systemctl status e2guardian.service
● e2guardian.service - E2guardian Web filtering
   Loaded: loaded (/usr/lib/systemd/system/e2guardian.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-03-23 15:52:45 CET; 1min 1s ago
  Process: 18686 ExecStart=/usr/sbin/e2guardian (code=exited, status=0/SUCCESS)
 Main PID: 18703 (e2guardian)
   CGroup: /system.slice/e2guardian.service
           ├─18703 /usr/sbin/e2guardian
           ├─18705 /usr/sbin/e2guardian
           ├─18707 /usr/sbin/e2guardian
           ├─18832 /usr/sbin/e2guardian
           ├─18833 /usr/sbin/e2guardian
           ├─18834 /usr/sbin/e2guardian
           └─18835 /usr/sbin/e2guardian

Mar 23 15:52:41 server50.tachtler.net systemd[1]: Starting E2guardian Web filtering...
Mar 23 15:52:45 server50.tachtler.net systemd[1]: Started E2guardian Web filtering.
Mar 23 15:52:47 server50.tachtler.net e2guardian[18703]: Started sucessfully.
Mar 23 15:53:26 server50.tachtler.net e2guardian[18703]: Reconfiguring E2guardian: gentle reload starting
```

Thank you - it was my fault - tahnk you for the great help and your patience!

Klaus.

**Comment by fredbcode** [comment]
No problem
