### ISSUE TITLE
bannedphraselist not working in 3.4.0.1

### ISSUE THREAD

**Issue by aerturk** [e2guardian/e2guardian#109]
Hello,

With a default squid 3.5 and e2guardian 3.4.0.1 setup bannedphraselist is not working. Just installed with default options, and add a few words to bannedphraselist file; but I can still browse web pages with words in bannedphraselist file (over HTTP).

I only modified bannedphraselist file to be sure but cannot make it work.

Thank you.

**Comment by fredbcode** [comment]
Can you make a test with 3.4.0 branch ?
I totally removed weightedphrasemode by default

**Comment by aerturk** [comment]
Hello,

I downloaded e2guardian-master on this page.
configure --prefix=/usr/local/e2
make & make install
chmod & chown /usr/local/e2/var/ for nobody user
edit nano /usr/local/e2/etc/e2guardian/lists/bannedphraselist and add a few words like:
<QWERTY>
< QWERTY >
<qwerty>  
< qwerty >
then search for qwerty and browse to a few found sites without HTTPS.

I can browse, it does not block. There is no denied/banned lines in logs.

Squid is 3.5, default install on centos no config change.

**Comment by fredbcode** [comment]
No the master but v3.4

**Comment by aerturk** [comment]
Hello,

Sorry don't use git before. I changed to branch v3.4; download it as zip file; then configure, make etc all steps as in the previous message. But again, I can browse sites with banned words.

Do you need additional information about setup?

**Comment by fredbcode** [comment]
You can switch to another branch with checkout
git checkout v3.4
git pull
./autogen.sh ...

The zip file still from the master branch

**Comment by fredbcode** [comment]
OK I pushed to master, please try the zip file now

**Comment by aerturk** [comment]
Hello,

Unfortunately, it does not work.

I checkout by using Linux git command line, make and try. Then download zip file again make & make install. But still it does not work.
/usr/local/e2/sbin/e2guardian -v command gives.
e2guardian 3.4.0.2

I followed same steps for latest dansguardian-2.12.0.3. It works as expected. Added just "qwerty" for test, and all sites with word "qwerty" blocked.

However, I need e2guardian for SSL MITM features.

**Comment by fredbcode** [comment]
Ok I think I forgot something, sorry I can't made tests now
Can you (re)-try, just download the zip file

**Comment by aerturk** [comment]
No, it does not work.

**Comment by fredbcode** [comment]
Which value are you using for naughtynesslimit ?

**Comment by aerturk** [comment]
It is default value. aughtynesslimit = 50

I only modify bannedphraselist file after make&make install (to add a few words).

**Comment by fredbcode** [comment]
Ok can you make a try now
Please be sure that macontentfiltersize > 0

**Comment by aerturk** [comment]
maxcontentfiltersize = 256

I run git pull then make, but still does not work.

**Comment by fredbcode** [comment]
Weird, it works here now 

Bannedphraselist -> <vrrpd>

2016.2.12 14:50:41 10.x.x.x http://numsys.eu *DENIED* Phrase interdite : vrrpd GET 33133 0  3 403 text/html  groupe3 Mozilla/5.0 (Windows NT 6.1; rv:44.0) Gecko/20100101 Firefox/44.0  

Perhaps, you should upgrade maxcontentfiltersize value (I'm using 2000) ?

**Comment by aerturk** [comment]
Hello,
I think I found the problem.

By default weightedphrasemode line is disabled in e2guardianf1.conf file; and in comments it written that it is 1 by default. BUT it is not 1 actually. Because when I uncommented "weightedphrasemode = 1" line, it works as expected.

By the way, another question, I need to test MITM with transparent proxy. MITM is good in exclusive transparent mode; do you test it in transparent proxy mode. Does it work?

Thank you.

**Comment by fredbcode** [comment]
Ok good, I will discuss with Phillip about "weightedphrasemode = 1" and 
we will release a new version soon
Sorry but SSLMITM is only with implicit mode

**Comment by Mariollo14** [comment]
I had the same issue and tried to uncomment the weightedphrasemode = 1, but filtering still isnt working. I'm using the 3.4.0.1 version however, could it be the problem?

However just to let you know, as I already mentioned on the google group, there's a similar issue:

I'm not able to filther the regular expressions inside the body of an html page. I edited the file 'contentregexplist'  adding the following line:
"Stefano"->"Mario"

am I missing something?

I didnt tested the same functionality on URLs, headers and so on yet,
but I believe I should be able to do the substitution in the same way.

**Comment by fredbcode** [comment]
Actually only the master's branch is good
3.4.0.2

**Comment by Mariollo14** [comment]
Actually I'm trying to install the master branch following the instructions here:
https://github.com/e2guardian/e2guardian/blob/360949dee4e3e6a49ac79ff527ad88672a844543/INSTALL
(the debian installation part)
but it keeps giving me the same error:

./configure: line 6848: PKG_PROG_PKG_CONFIG: command not found
checking for PCRE support... yes
./configure: line 6875: syntax error near unexpected token `PCRE,libpcre'
./configure: line 6875: `PKG_CHECK_MODULES(PCRE,libpcre >= 6.0)'

if you have any suggestion it would be woderful

thank you

**Comment by fredbcode** [comment]
Which debian version ? Do you have libpcre-dev ?
Did you follow ?

./autogen.sh
./configure --options ...
make

**Comment by Mariollo14** [comment]
1)debian 8.3.0 (amd64)
2)3) this is what I made:
To install PCRE, type thy following command:

su
apt-get update
apt-get install libpcre3 libpcre3-dev

./autogen.sh && ./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--enable-locallists=yes' '--enable-orig-ip=yes' '--enable-avastd=yes' '--enable-kavd=yes' '--enable-commandline=yes' '--enable-fancydm=yes' '--enable-totalblocklist=yes' '--enable-rxredirects=yes' '--enable-addheader=yes' '--enable-sslextralists=yes' '--enable-searchwords=yes' '--enable-dnsauth=yes' && make

same problem:
./configure: line 6848: PKG_PROG_PKG_CONFIG: command not found
checking for PCRE support... yes
./configure: line 6875: syntax error near unexpected token `PCRE,libpcre'
./configure: line 6875: `PKG_CHECK_MODULES(PCRE,libpcre >= 6.0)'

**Comment by Mariollo14** [comment]
I'm sorry for all these questions, but I'm actually configuring e2guardian for an european project carried on by my university (Politecnico of Turin) for bringing security to the edge of the network.

https://www.secured-fp7.eu/

so as a first step I need to know all the ways you can configure the content filther and how (then I'll have to write a middleware to translate high level commands to the desired configuration)

**Comment by fredbcode** [comment]
Do you have pkg-config ?

dpkg -l pkg-config

**Comment by Mariollo14** [comment]
Voluto=U (non noto)/I (installato)/R (rimosso)/P (rimosso totale)/H (in attesa)
| Stato=Non/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(nessuno)/R (reinstallazione richiesta) (Stato,Err: maiuscolo=grave)
||/ Nome           Versione     Architettura Descrizione
+++-==============-============-============-=================================
un  pkg-config     <nessuna>    <nessuna>    (nessuna descrizione disponibile)

**Comment by fredbcode** [comment]
Should be fixed now, with 3.4.0.2
