### ISSUE TITLE
Changelog Upgrade

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#11]
Would be very useful to have a list of files that were changed when program is updated, so that its easy to backup the lists directory and the dansguardian.conf and dansguardianf1.conf files and restore them after upgrading to a new version.

If there was a file listing what files were updated in the updated version, then it would be very easy to see what files in the lists directory have changed so that program updates are not overwritten when restoring the lists directory.  Its convenient to backup and restore the lists directory and dansguardian.conf config files as the settings in these files are specifc to the network installed.  Thank you

**Comment by spikedrba** [comment]
@Dalacor can you please provide a use case? I'm not clear what problem you're encountering. You can always do a git diff to see which files were changed from version to version, but maybe that's not what you're asking. thanks.

**Comment by Dalacor** [comment]
If I can do a git diff to see which files have changed from version to version then that solves my problem.

To give you an example - I might change a number of settings in the e2guardian.conf and e2guardianf1.conf and say the bannedextensionlist files.  So what I normally do when updating E2guardian is to backup the E2guardian folder, then remove E2guardian and then install the new E2guardian.  After that I would copy the lists files and e2guardian.conf files back.

However, there might be changes in the E2guardian.conf files or in say the say the bannedextensionlist file and I wanted a way to see whether any files had any changes between old and new version so I didn't effectively end up overwriting the changes in the new bannedextensionlist file when I restored the file with all my changes in it as I don't want the default settings.

**Comment by spikedrba** [comment]
it seems to me there's two different problems here, but maybe I'm still not understanding, thank you for your patience:

1) config files changes in e2g
2) your own config changes

for 1), you can do a git diff between revisions, no problem

for 2), that's not really something e2g can or even should do. my recommendation is to handle your own changes in another file and include that. this is what I do so that I never have problems with my config being overwritten (other than the main one). So example the lists files include overrides/somelist and that's where I put my changes. If e2g updates the list files, all I have to do is to re-add that include and I'm done.

thanks,

Spike

**Comment by Dalacor** [comment]
To put it very simply, what I am trying to achieve is when installing a new version of E2guardian, what is the best and simplest way to apply my own config changes without having to open 20 files and add the entries again!

What I have been doing is keeping a copy of all the files that I have changed and when I put  a new version of E2guardian on a system, I just copy across the files that I have changed from my computer onto the new system.  The drawback of this system is that if there are new changes in the files as a result of a newer version of E2guardian, then those new changes are lost when I apply my config files.

Your method is one way of doing it.  What I have been doing is doing a visual file compare of new e2g file and my custom config file and syncing it up that way.

Hence my original request that if the changelog indicated exactly which files have changed - I would only have to look at those files that have changed and copy across my changes to the newever version of the e2guardian config file.  So I am not interested in the actual changes in e2guardian, more preventing overwritting new changes in newer versions when applying my config changes.

**Comment by spikedrba** [comment]
@Dalacor then you can do a git diff between version you have and version you are installing of the config dir. That will tell you if and what changed, like git diff tag1 tag2 -- some/file/name , where the filename is the list name. This is how it's normally handled as a "Changelog" is for feature changes etc, not to list which files where changed, that's definitely a git diff job.

Also your problem has to do with how you install e2guardian. For example on debian/ubuntu (and I suspect on any other packaging system), the package manager handles this, but noticing that a file already exists and providing a diff if there are indeed differences (and prompting you for what to do).
