### ISSUE TITLE
bannedsitelist not working in 3.4.0.1

### ISSUE THREAD

**Issue by marcuskong** [e2guardian/e2guardian#114]
I migrated to 3.4.0.1 from 3.1.2 with the same configurations and list files . But it doesn't filter any http pages . I banned every web sites except the sites in greysitelist . So far I have no idea what happened , there is no more segment fault . Please help to point out what the problem .
Now I downgrade it . My Linux OS is CentOS 6.7 .

**Comment by fredbcode** [comment]
Yes there is a problem but the stable master's branch is good now
But I prefer discuss some points with Philip before releasing

**Comment by marcuskong** [comment]
I tried transparent mode was fail of 3.4.0.2 .

**Comment by fredbcode** [comment]
Should be fixed now, with 3.4.0.3
