### ISSUE TITLE
weightedphrasemode

### ISSUE THREAD

**Issue by nerijus** [e2guardian/e2guardian#115]
Does not work in 3.4.0.1. Earlier e2guardian.conf had weightedphrasemode = 2, now e2guardian.conf does not have weightedphrasemode at all, e2guardianf1.conf has it commented out. It should either be uncommented by default, or mentioned in release notes.

**Comment by Mariollo14** [comment]
I think it is the same issue discussed in #109 bannedphraselist not working in 3.4.0.1

take a look. I'm waiting for the 3.4.0.2 version as well.

**Comment by fredbcode** [comment]
Should be fixed now, with 3.4.0.2
