### ISSUE TITLE
3.4.0.1 displays page incorrectly

### ISSUE THREAD

**Issue by nerijus** [e2guardian/e2guardian#116]
3.2.0 displays OK, or if I add the site to exceptionsitelist in 3.4.0.1.
The URL is http://osp.stat.gov.lt/statistiniu-rodikliu-analize1
I am attaching screenshots:
without proxy:
![without proxy](https://cloud.githubusercontent.com/assets/591932/13353203/604011a8-dc9b-11e5-8a3d-023a6a21557c.jpg)
with proxy:
![with proxy](https://cloud.githubusercontent.com/assets/591932/13353205/64ba6882-dc9b-11e5-9893-2729c2eee195.jpg)

**Comment by fredbcode** [comment]
Do you have something in log files ?

**Comment by nerijus** [comment]
Yes, I see
```http://osp.stat.gov.lt/statistiniu-rodikliu-analize;jsessionid=C490
2B545FD3170302E342B6EA09F2C1?p_p_id=analysisportlet_WAR_analysisportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode
=view&p_p_cacheability=cacheLevelPage&p_p_col_id=column-1&p_p_col_count=2&_analysisportlet_WAR_analysisportlet_ja
vax.faces.resource=theme.css&_analysisportlet_WAR_analysisportlet_ln=primefaces-aristo *DENIED* Draudžiamas URL r
egexp: (big|cyber|hard|huge|mega|small|soft|super|tiny|bare|naked|nude|anal|oral|topp?les|sex|phone)+.*(anal|babe
|bharath|boob|breast|busen|busty|clit|cum|cunt|dick|fetish|fuck|girl|hooter|lez|lust|naked|nude|oral|orgy|penis|p
orn|porno|pupper|pussy|rotten|sex|shit|smutpump|teen|tit|topp?les|xxx)s? GET 0 0 Banned Regular Expression URLs 1
 403 -     - -
```

Strange that it works with 3.2.0 and the same config.

**Comment by Alexander237** [comment]
you need to add osp\.stat\.gov\.lt to exeptionregexpurllist or comment relevant line in bannedregexpurllist. This issue related to configuration, but not to the e2g

**Comment by nerijus** [comment]
Adding to exception works of course. The problem is, that the same config works with 3.2.0 without adding to exception.

**Comment by fredbcode** [comment]
In this case, the problem was with 3.2.0 
All seem correct here
