### ISSUE TITLE
e2guardian ipv6

### ISSUE THREAD

**Issue by lours974** [e2guardian/e2guardian#117]
With this patch :

> https://sourceforge.net/p/dansguardian/feature-requests/13/
> http://saschahlusiak.de/linux/dansguardian-ipv6.diff

I have got a working dansguardian ipv6 after rebuild.

```
netstat =>
tcp6 0 0 :::8080 :::* LISTEN 0 116145021  15068/dansguardian

```
Can you integrate these patch or is it done already
e2guardian_3.4.0.1_wheezy-jessie_amd64.deb does not listen ipv6

Thk

**Comment by fredbcode** [comment]
> With this patch :
>
>     https://sourceforge.net/p/dansguardian/feature-requests/13/
>     http://saschahlusiak.de/linux/dansguardian-ipv6.diff
>
> I have got a working dansguardian ipv6 after rebuild.
>
> |netstat => tcp6 0 0 :::8080 :::* LISTEN 0 116145021 15068/dansguardian |
>
> Can you integrate these patch or is it done already
> e2guardian_3.4.0.1_wheezy-jessie_amd64.deb does not listen ipv6
>
> Thk
>
> —
>


Working without any changes ? odd

**Comment by fredbcode** [comment]
Doh ! dansguardian of course ...
Not yet adapted to e2, sorry no


Sent from my ASUS

-------- Message d'origine --------
De :lours974 <notifications@github.com>
Envoyé :Sat, 05 Mar 2016 17:05:21 +0100
À :e2guardian/e2guardian <e2guardian@noreply.github.com>
Sujet :[e2guardian] e2guardian ipv6 (#117)

**Comment by fredbcode** [comment]
Duplicate with #34
