### ISSUE TITLE
BYPASS not working with sslmitm = on

### ISSUE THREAD

**Issue by neradpeter** [e2guardian/e2guardian#118]
When i do ssl filtering, bypassing ban is not working. My configuration is default:

> bypass = 300
> bypasskey = ''

Im using the same single html template for ssl and non ssl filtering with continue button:

`<a class="btn btn-lg btn-success" href="-BYPASS-" role="button">Continue</a></p>`

**Comment by neradpeter** [comment]
No one has the same problem ?

**Comment by fredbcode** [comment]
I went quickly through the code and I think it can't yes,
Can you just make a try with Firefox and sslaccessdeniedaddress = 'http://alocalwebsite/mybannedpage.htm'
Put this value in your group file e2guardianfx.conf and tell me if you see a banned page (with and without SSL banned domains) ?

Sorry I can't test right now I'm not using SSLMITM

**Comment by fredbcode** [comment]
Related to bug #135

**Comment by fredbcode** [comment]
Fixed in 3.5.0
