### ISSUE TITLE
BaseSocket readFromSocket incorrect error path

### ISSUE THREAD

**Issue by prlw1** [e2guardian/e2guardian#119]
There are three recv() calls in BaseSocket.cpp which each has a different way of dealing with EINTR. Maybe a wrapper function is in order?

Code inspection suggests that there is an issue with the recv() call in readFromSocket:

   471      while (true) {
   472          rc = recv(sck, buff, cnt, flags);
   473          if (rc < 0) {
   474              if (errno == EINTR && (honour_reloadconfig ? !reloadconfig : true)) {
   475                  continue;
   476              }
   477          }
   478  
   479          break;
   480      }
   481  
   482      return rc + tocopy;

Consider what happens if recv() returns EAGAIN. On my system it happens to be 35. The loop will break, and we return tocopy+35 ?!

**Comment by fredbcode** [comment]
Yes, seems right 
And on Linux EAGAIN and EWOULDBLOCK share the same value

**Comment by prlw1** [comment]
Just to be clear: you agree that there is a bug - the number of bytes received should have nothing to do with the value of an error code.

**Comment by prlw1** [comment]
I should rephrase that: recv() fails, rc = -1, you now return tocopy - 1.

**Comment by fredbcode** [comment]
Fixed in 3.5.0
