### ISSUE TITLE
Scan skin content of picture

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#12]
Feature request!

Would it be possible to implement into e2Guardian a feature where it can scan the pictures on the page and block the picture if there is a high percentage of skin tone on the page.

e2guardian only focus on weightlisting text content and not the pictures.  The pic rating only works if the website developer includes the picture rating in a certain category.

Sometimes one can come across websites where there is nudity displayed but its not being blocked because there is no text that is being filtered out so the picture gets displayed.  Thank you

**Comment by fifthsegment** [comment]
Connecting squid with a Python ICAP server that implements nude.py could be used for scanning nudity in pictures.

**Comment by Dalacor** [comment]
I will look into this if I ever find the time.  Thanks

**Comment by philipianpearce** [comment]
Stale
