### ISSUE TITLE
SSLMITM Works fine everywhere I tried except for the site : Flashgot.net

### ISSUE THREAD

**Issue by fifthsegment** [e2guardian/e2guardian#121]
I have E2G (v.3.4.0.3) installed on an OpenWRT router (15.05) with ssl mitm on. It works pretty well on all major domains that I tried; google,facebook,ycombinator,medium,flickr. However whenever I visit the site https://www.flashgot.net/ I get a "Certificate supplied by server was not valid" error. Could anyone try this on their E2G setup and let me know if they get the error too on this specific domain?

**Comment by neradpeter** [comment]
What about this ?:
```
#SSL certificate checking
# Check that ssl certificates for servers on https connections are valid   
# and signed by a ca in the configured path
sslcertcheck = on
```
https://www.flashgot.net/ has not valid certificate at this time :-D

**Comment by fifthsegment** [comment]
Tried this with both `sslcertcheck` ON and OFF but get the same error :(

Btw, isn't flashgot's certificate valid? http://i.imgur.com/u51G7IS.jpg

**Comment by neradpeter** [comment]
Im using latest firefox ... i have not istalled ca root certificate for this site in firefox certification store.. SEC_ERROR_UNKNOWN_ISSUER

What about your certificate store on OpenWRT router ?

Sorry for my english

You can add this site as exception site to your configs..

**Comment by neradpeter** [comment]
Using sslyze tool gives me this output:
> Certificate - Trust:
      Hostname Validation:               OK - Subject Alternative Name matches flashgot.net
      Mozilla NSS CA Store (02/2016):    FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Microsoft CA Store (02/2016):      FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Apple CA Store (OS X 10.11.3):     FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Java 6 CA Store (Update 65):       FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Google CA Store (02/2016):         FAILED - Certificate is NOT Trusted: unable to get local issuer certificate
      Weak Signature:                    OK - No SHA1-signed certificate in the chain
      Certificate Chain Received:        ['maone.net', 'COMODO RSA Domain Validation Secure Server CA', 'COMODO RSA Certification Authority']
      Certificate Chain Order:           FAILED - Certificate chain out of order!

I have no latest updates for certification stores from providers :-D

**Comment by nerijus** [comment]
https://community.letsencrypt.org/t/which-browsers-and-operating-systems-support-lets-encrypt/4394

@neradpeter , which OS do you use?

**Comment by nerijus** [comment]
Just tried https://www.flashgot.net/ on latest FF and Fedora 23, and yes, it does complain about invalid certificate (although my own older letsencrypt certificates work fine). So it seems there is a problem with letsencrypt and FF. Chrome works fine.

**Comment by nerijus** [comment]
Found it - https://community.letsencrypt.org/t/certificates-issued-by-lets-encrypt-authority-x3-not-valid-in-mozilla/13320/11

**Comment by fifthsegment** [comment]
hmmm... my own website https://www.abdullahirfan.com is powered by a LetsEncrypt certificate, but it works fine on Firefox. Wierd...

**Comment by neradpeter** [comment]
What about cert store on openwrt router ? Have you ca autority for maone.net ?  Comodo certificates probably are in store but maone.net is problem (look at certificate chain)

**Comment by nerijus** [comment]
@fifthsegment, no, not weird, as there is a new regression with letsencrypt and FF.

**Comment by fifthsegment** [comment]
@nerijus Oh! okay.


@neradpeter maone.net opens fine via e2g. 


I found some more problems in the logs: https://180.87.4.131/ https://81.19.104.48/ . Seems like E2G is unable to open any IP over https.

**Comment by fredbcode** [comment]
Same without E2, the problem still present I can close ?
