### ISSUE TITLE
Bypass Variables missing?

### ISSUE THREAD

**Issue by 83GTIGuy** [e2guardian/e2guardian#122]
I used a script with v 3.2. series that seems to have stopped working in the 3.4 series.  The best I can tell is that the Bypass variables are not all being sent.  The short list is IP, Reason, categories, deniedurl.  The only one I see now is deniedurl.  This is running in non sslmitm mode.

Cheers

**Comment by fredbcode** [comment]
Weird, works good here at least for IP, Reason, categories, deniedurl and username
But not tested with Bypass

**Comment by 83GTIGuy** [comment]
You are correct it does work.  Turns out my issue was the accessdeniedaddress was still in the e2guardian.conf vs e2guardianf1.conf.  The 3.4 series changes in the configuration files and being more strict was the issue.

**Comment by fredbcode** [comment]
Fine
