### ISSUE TITLE
How to verify false positive PUA, with integrated Clamd

### ISSUE THREAD

**Issue by 83GTIGuy** [e2guardian/e2guardian#124]
Running latest versions of e2guarian and clamd on my proxy server.  When I test our the clamd setup on the ecar test file it identifies the file properly..  After a few days of use all is good except visiting pandora.com
clamd .logsays /tmp/tfWfPyPC: PUA.Win.Trojan.Xored-1 FOUND  .  How do I verify this is a real issue? And if its not a real issue identify whats going wrong with the setup?
deletedownloadedtempfiles = off is set so I could test the file on another system, but I don't see any files left in /tmp/.
If I submit the url to be scanned by other online site scanners they don't pick up anything.
e2guardian.log says:  http://www.pandora.com *INFECTED* * *DENIED* Virus or bad content detected. PUA.Win.Trojan.Xored-1 GET 263456 0 Content scanning 1 403 text/html     - -
But that doesn't indicate if its the index.html, or some associated javascript file.

Cheers
  Derek

**Comment by philipianpearce** [comment]
Not really a e2g issue.

Suggest you try the clamd web site/forums to identify what the log message means

Regards
Philip
