### ISSUE TITLE
PICS not working

### ISSUE THREAD

**Issue by msali** [e2guardian/e2guardian#125]
I enabled PICS filtering, but it doesn't work. Even setting 0 to all in the pics file, nothing is filtered.

**Comment by philipianpearce** [comment]
PICS is now obsolete. It was a W3C draft for self categorizing sites by the author and was popular when Dan originally wrote DansGuardian. It has not worked for many years as only a very few, very old sites embed the PICS codes in their pages. 

See https://en.wikipedia.org/wiki/Platform_for_Internet_Content_Selection for more information. 

PICS support will be removed from the next major version of e2guardian. 

Regards 

Philip 

----- Original Message -----
