### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by ZomboBrain** [e2guardian/e2guardian#126]
`2016.5.2 17:55:58 - 192.168.42.56 https://www.tipico.com:443 *VERWEIGERT* Das vom Server ausgelieferte Zertifikat ist ungültig: unable to get local issuer certificate CONNECT 0 0 SSL SEITE 1 200 -     - -`
Can somebody tell me what this error means and how to fix it?
Thanks a lot!

EDIT: I forget some details
Debian 8 x64 on VMware
Squid as Proxy
e2guardian 3.4.0.3

sslmitm = on & mitmcheckcert = on => Error above. 
sslmitm = on & mitmcheckcert = off => No Error. But I don't want this. 
Chrome and IE11 say the website is fine.

**Comment by fredbcode** [comment]
Did you check the files rights ?

**Comment by philipianpearce** [comment]
Have you looked at the following, which contains some help on this? 

https://github.com/e2guardian/e2guardian/blob/v3.4/notes/certificate_errors 

Regards 

Philip 

----- Original Message -----

**Comment by ZomboBrain** [comment]
There is a know error in Debian 8, a root CA is missing, so some websites are not secure on debian. We put the site in the execution ssl list.
