### ISSUE TITLE
Updating exceptionvirusmimetypelist to allow bypass more streaming types

### ISSUE THREAD

**Issue by 83GTIGuy** [e2guardian/e2guardian#131]
The following site has a nice updated list of streaming mimetypes that should be added to exceptionvirusmimetypelist so more types work out of the box.  https://www.sophos.com/support/knowledgebase/115656.aspx

With clamav plugin enabled netflix via roku box isn't working, but does via browser.  Any configuration advice?  

Also pandora via roku box isn't loading station list.
Any configuration advice?

Cheers

**Comment by fredbcode** [comment]
Please open a discussion here https://groups.google.com/forum/#!forum/e2guardian
I guess this is not really a bug
