### ISSUE TITLE
Migration from Dansguardian

### ISSUE THREAD

**Issue by papoteur-mga** [e2guardian/e2guardian#132]
Hello,
I ask the question for the Mageia team, who plan to migrate from dansguardian to e2guardian.
I saw it was a script for such a migration, which was deleted then. 
My questions are: 
1/ Is it possible to keep the old configuration from dansguardian and to use it for e2guardian? If not directly, what should be do for that? 
2/ We have drakguard which is a graphical tool to configure it. Is it enough to replace the destination path and name containing dansguardian with e2guardian?

**Comment by fredbcode** [comment]
Hi,

I'm sorry but no, now there are too many differences between E2 and DG.
There is also now a big change, no rule anymore in "master" file it's 
dedicated to engine specifications
