### ISSUE TITLE
The problem to enable  Auth plugins

### ISSUE THREAD

**Issue by diegogodoi89** [e2guardian/e2guardian#133]
Hello, I have a big problem to activate the Auth plugins when I descomento these lines simply the service is not up and also does not generate any error log, when I comment again back to work any tips?

#authplugin = '/etc/e2guardian/authplugins/proxy-basic.conf'
#authplugin = '/etc/e2guardian/authplugins/proxy-digest.conf'

**Comment by fredbcode** [comment]
Which version ? OS and compilation options ?

**Comment by diegogodoi89** [comment]
Debian 8;

Version;
e2guardian 3.4.0.3
![error](https://cloud.githubusercontent.com/assets/12152524/16873704/456e5fb8-4a6b-11e6-9884-be835692b1f1.png)
![error](https://cloud.githubusercontent.com/assets/12152524/16873708/4b9c90a8-4a6b-11e6-9e5d-1727682ede8a.png)




Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--with-filedescriptors=8192' '--enable-sslmitm=yes'

**Comment by fredbcode** [comment]
Nothing in syslog ?
Please try e2guardian -N

**Comment by fredbcode** [comment]
No news ?
