### ISSUE TITLE
nocheckcertsitelist (build cruft) in git

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#137]
Hi,

my name is Mike Gabriel and, together with a colleague, I prepare an upload of e2guardian to Debian, targetting Debian 9 (aka stretch).

I will send in various issue reports on e2guardian while packaging this software. Most of them will be formal, relate to the build workflow, etc.

Herer comes the first minor issue:  nocheckcertsitelist gets generated at build time from nocheckcertsitelist.in (in configs/lists/). I'd consider nocheckcertsitelist as build cruft and suggest removing it from Git.

Greets,
Mike

**Comment by fredbcode** [comment]
Hi Mike and thank you for your help
Sorry I have no time now to check each change

Please can you provide a global patch with all your changes for develops branch ? I already merged #140 and #144

Thanks

Fred

**Comment by fredbcode** [comment]
nocheckcertsitelist.in is useless, removed in dev

**Comment by sunweaver** [comment]
Thanks!
