### ISSUE TITLE
 source is missing: data/blockedflash.swf

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#139]
In the e2guardian source code you ship one (only one, yeah!!!) binary file without providing its source code: data/blockedflash.swf.

For Debian packaging, I need to rebuild everything that is binary-like, also the .swf file shipped with e2guardian. Is it possible to add the underlying source code in the e2guardian code tree? Alternatively, can you describe to where you obtained that blockedflash.swf and how it can be re-created?

Thanks,
Mike

**Comment by sunweaver** [comment]
P: e2guardian source: source-contains-prebuilt-flash-object data/blockedflash.swf
N: 
N:    The source tarball contains a prebuilt file in the Shockwave Flash (SWF)
N:    or Flash Video (FLV) format. These are often included by mistake when
N:    developers generate a tarball without cleaning the source directory
N:    first. An exception is simple video files, which are their own source.
N:    
N:    If there is no sign this was intended, consider reporting it as an
N:    upstream bug.
N:    
N:    If the Flash file is not meant to be modified directly, please make sure
N:    the package includes the source for the file and that the packaging
N:    rebuilds it.
N:    
N:    Severity: pedantic, Certainty: possible
N:    
N:    Check: cruft, Type: source

Or would you say that blockedflash.swf falls under the category "An exception is simple video files, which are their own source."??? (I am not at all an expert on that dying Flash technology...).

**Comment by fredbcode** [comment]
Unfortunately we don't have the source code, this is an old part of DG

**Comment by fredbcode** [comment]
Ok new file + source pushed to develop

**Comment by sunweaver** [comment]
On  Di 11 Okt 2016 12:39:57 CEST, Fredb wrote:

> Ok new file + source pushed to develop

Very cool. The Debian FTP masters accepted the .swf file without  
source, but it is even better to have the source code at end (and  
rebuild it at package build time).

Thanks!
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Short question: I just checked the guardian.fla file. It looks like a binary blob, too. With what tool did you create that .fla file and how do you make the .swf from it? (Sorry, I am not an expert on Flash and neither very familiar with non-free software).

**Comment by fredbcode** [comment]
Not an expert too ... This animation was created by another person 
I think this is made with Trillix

**Comment by sunweaver** [comment]
On  Di 11 Okt 2016 14:38:06 CEST, Fredb wrote:

> Not an expert too ... This animation was created by another person
> I think this is made with Trillix

It would be good to have a little README that explains how it can be rebuilt.

Thanks!
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fredbcode** [comment]
Hum, this program is closed source I think we just should remove this part when flash will die (soon I hope :) )
