### ISSUE TITLE
too many LICENSE files...

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#141]
In the e2guardian source code, I found three full copies of the GPL-2 license.

DGnotes/LICENSE
COPYING
LICENSE

May I propose removing DGnotes/LICENSE and LICENSE completely ? 

About DGnotes/LICENSE: I recommend a paragraph in README.md that explains that DG was licensed under GPL-2+ and e2guardian continues that. Shipping a duplicate  version of the full GPL-2 text as historic documentation is not required.

Greets
Mike

**Comment by fredbcode** [comment]
ok done (dev)

**Comment by fredbcode** [comment]
Fixed in 3.5.0
