### ISSUE TITLE
drop automake build cruft from source tree

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#142]
The following files are auto-created by autoconf/automake and need not to be in an upstream source tree:

- depcomp
- install-sh
- missing

IMHO, these files can be safely removed. Please consider doing so. Thanks.

**Comment by fredbcode** [comment]
Ok in dev branch

**Comment by sunweaver** [comment]
Fixed by d36ec39e824b52b5b084207c7cc2ba4f17baaad4. Thus, closing.
