### ISSUE TITLE
copyright information in e2guardian.8 man page outdated 

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#143]
Please review the e2guardian.8 man page as found in current upstream code. To my opinion, the information provided there is outdated and only refers to the DG copyright situation. Please improve. Thanks!!!

**Comment by fredbcode** [comment]
https://github.com/e2guardian/e2guardian/blob/master/doc/e2guardian.8 seems right to me ?

**Comment by sunweaver** [comment]
Hi,

On  Di 11 Okt 2016 12:43:00 CEST, Fredb wrote:

> https://github.com/e2guardian/e2guardian/blob/master/doc/e2guardian.8 seems  
> right to me ?

hmmm... you are right. I thought that I saw a man page with the old  
DansGuardian copyright holders in it. Sorry for the noise.

Only thing, in the header line, you should put June 2015 (or Oct 2016)  
rather than "Juin 2015".

Sorry for the noise,
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fredbcode** [comment]
Ok fixed on dev branch
