### ISSUE TITLE
E2guardian is running out of MaxChildren process

### ISSUE THREAD

**Issue by ThePutzy** [e2guardian/e2guardian#147]
Hello,

we have the Problem that we becomes this Message "E2guardian is running out of MaxChildren process: 179 maxchildren: 180".

I've tested many values (180, 380, 500, 1000 and more).
I've tested with the other children values too.

But we have every time this problem.
How can we fix it? It will stops the complete e2guardian.

Our Env Ubuntu xenial - 128GB RAM:
`ulimit -n: 65536`
`#define __FD_SETSIZE 1024`

**Comment by fredbcode** [comment]
How many process ? How many simultaneous users ?

ps -edf | grep e2guardian | wc -l

> I've tested many values (180, 380, 500, 1000 and more).

Maybe it's normal, I'm using 8000 maxchildren here**

**Comment by ThePutzy** [comment]
`# ps -edf | grep e2guardian | wc -l`
returns: `182`

Actually we have 10 devices running through our squid and e2g.

**Comment by fredbcode** [comment]
With maxchildren=180 ?
Perhaps there is something slow in your network (ISP ? Proxy ?) that's just mean there are many opened connections.

Can I see the result of ?
grep -v '#' /etc/e2guardian/e2guardian.conf

Can you increase the value beyond 1024 ? ( need a special compilation option https://github.com/e2guardian/e2guardian/blob/master/INSTALL )

**Comment by ThePutzy** [comment]
Yes with 180 as maxchildren.

here's my conf:
`languagedir = '/usr/local/share/e2guardian/languages'
language = 'german'
loglevel = 0
logexceptionhits = 0
logfileformat = 1
loglocation = '/var/log/e2guardian/access.log'
dstatlocation = '/var/log/e2guardian/dstats.log'
filterip =
filterports = 8080
proxyip = 127.0.0.1
proxyport = 3128
proxytimeout = 20
proxyexchange = 20
pcontimeout = 55
usecustombannedimage = on
custombannedimagefile = '/usr/local/share/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/usr/local/share/e2guardian/blockedflash.swf'
filtergroups = 1
filtergroupslist = '/etc/e2guardian/lists/filtergroupslist'
bannediplist = '/etc/e2guardian/lists/bannediplist'
exceptioniplist = '/etc/e2guardian/lists/exceptioniplist'
showweightedfound = off
urlcachenumber = 1000
urlcacheage = 900
scancleancache = on
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
prefercachedlists = off
maxcontentfiltersize = 256
maxcontentramcachescansize = 2000
maxcontentfilecachescansize = 20000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
downloadmanager = '/etc/e2guardian/downloadmanagers/fancy.conf'
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
contentscannertimeout = 60
contentscanexceptions = off
recheckreplacedurls = off
forwardedfor = on
usexforwardedfor = on
logconnectionhandlingerrors = on
logsslerrors = off
logchildprocesshandling = off
maxchildren = 180
minchildren = 20
minsparechildren = 16
preforkchildren = 10
maxsparechildren = 32
maxagechildren = 500
maxips = 0
ipcfilename = '/tmp/.e2guardianipc'
urlipcfilename = '/tmp/.e2guardianurlipc'
ipipcfilename = '/tmp/.e2guardianipipc'
pidfilename = '/var/run/e2guardian.pid'
nodaemon = off
nologger = off
logadblocks = off
loguseragent = off
softrestart = off
mailer = '/usr/sbin/sendmail -t'`


typesizes.h:
`#define __FD_SETSIZE            65536`

posix_types.h:
`#define __FD_SETSIZE    65536`

`ulimit -n: 65536`

Built with:
`e2guardian 3.4.0.3
'--sysconfdir=/etc' '--localstatedir=/var' '--with-proxyuser=proxy' '--with-proxygroup=proxy' '--enable-sslmitm' '--enable-icap' '--enable-ntlm' '--enable-dnsauth' '--enable-email' '--enable-clamd' '--with-filedescriptors=65536' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes'`

**Comment by fredbcode** [comment]
Ok can you make a try with

initialtrickledelay = 40
proxytimeout = 60
proxyexchange = 30
pcontimeout = 15
trickledelay = 20
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf' -> remove downloadmanager = '/etc/e2guardian/downloadmanagers/fancy.conf'
maxchildren = 6000 
minchildren = 64
minsparechildren = 15 
preforkchildren = 20
maxsparechildren = 80
maxagechildren = 5000

**Comment by ThePutzy** [comment]
I've deleted the complete e2guardian and installed the .deb from releases.

`Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--with-filedescriptors=8192' '--enable-sslmitm=yes'`

I've wrote down your settings at our config.
Now: `ps -edf | grep e2guardian | wc -l` returns 6003

dmesg returns:
`[180523.537246] e2guardian[28951]: segfault at 0 ip 00007f27dbead3a8 sp 00007ffc4a0f5130 error 4 in libstdc++.so.6.0.21[7f27dbddd000+172000]`

the last line from /var/log/e2guardian/dstats.log
`1475756837      5727    5631    96      0       1280    765     168451  561`

Performance is ok too.
Currently we have 8 devices on this e2guardian.

**Comment by fredbcode** [comment]
> I've deleted the complete e2guardian and installed the .deb from releases. 

> Now: ps -edf | grep e2guardian | wc -l returns 6003 

Big problem, e2 creates process without any limit 

> [180523.537246] e2guardian[28951]: segfault at 0 ip 00007f27dbead3a8 sp 00007ffc4a0f5130 error 4 in libstdc++.so.6.0.21[7f27dbddd000+172000] 

I guess the debian package is not fully compatible 

Do you have more indications in syslog ? cache.log ? etc

**Comment by ThePutzy** [comment]
No nothing, no more indications.

**Comment by fredbcode** [comment]
Ok step by step

Can you make a try with only one device

1 - The number of process increase beyond maxchildren after a while ? (6003)
2 - There is a segault ?
3 - No problem (slow connection, ifconfig with crc errors, etc)

Also, I guess you should use a compiled version, just switch your binary /usr/sbin/e2guardian 
Do you have an ulimit value in /etc/init.d/e2guardian ?

**Comment by ThePutzy** [comment]
It's running since 6 days without a problem.

**Comment by fredbcode** [comment]
How ?, there is something changed ?

**Comment by ThePutzy** [comment]
No, nothing. i'm confused. we have many devices running (round about 20).
No Problem, no error messages.

**Comment by fredbcode** [comment]
Ok thanks

**Comment by ThePutzy** [comment]
Thank you for your perfectly support :+1: :smile:
