### ISSUE TITLE
AIA extension in generated certs for MITM

### ISSUE THREAD

**Issue by varejjka** [e2guardian/e2guardian#148]
Hello
I am using e2guardian in production and everything works fine. 
But there is no AIA (Authority Information Access) extension added in generated certificates for MITM.
For this reason cert chain in generated certificate is incomplete and browsers are not trust that certificate.
I can't use imported in browser CA because there are many users with mobile phones (not under my management)  in my network.
My org has its own PKI service and i want to use it.
Any help? 
Thanks.

**Comment by fredbcode** [comment]
This is not really a bug, please open a discussion here https://groups.google.com/forum/#!forum/e2guardian
