### ISSUE TITLE
Weighted phrases

### ISSUE THREAD

**Issue by matjon** [e2guardian/e2guardian#15]
Hello,
e2g does not treat punctuation marks (, . etc) the same as spaces when parsing weighted phrase lists. Therefore
< sex ><200>
will not match "sex.".

Because of that, most of the weighted phrases in e2g do not enforce end of word at the end or beginning of the phrase. That can lead to overblocking when a phrase appears in the middle of another unrelated word (possibly in a different lang).

Impact of this is probably not big, may be bigger in some combination of languages.

**Comment by fredbcode** [comment]
Fixed 3.2.0
