### ISSUE TITLE
Protect stupid admin (myself) against e2guardian running out of children processes

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#151]
I just had an issue where I updated filterports to 3128 and left proxyport on 3128, as well.

This is of course a no-op setup, but what I see is e2guardian dumping thrillions of messages to syslog:

```
Oct 11 19:32:23 filter e2guardian[16710]: E2guardian is running out of MaxChildren process: 179 maxchildren: 180
Oct 11 19:32:23 filter e2guardian[16710]: E2guardian is running out of MaxChildren process: 179 maxchildren: 180
Oct 11 19:32:23 filter e2guardian[16710]: E2guardian is running out of MaxChildren process: 179 maxchildren: 180^C
```

Suggestion: build in some protection against such a config flaw into the config parser and let the e2guardian service fail at startup.

**Comment by fredbcode** [comment]
Are you sure ?
Here:
service e2guardian restart
[....] Restarting e2guardian: e2guardianError binding server socket: [8080 0.0.0.0 0] (Adresse déjà utilisée)
Error binding server socket (is something else running on the filter port and ip?
Exiting with error
 failed!

(Adresse déjà utilisée) mean Address already in use

**Comment by fredbcode** [comment]
FI: maxchildren: 180 is a very low value
