### ISSUE TITLE
Clamav is blocking everything

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#152]
I just now solve this problem.
ClamAV 0.99.2/22396/Thu Oct 20 06:57:49 2016.
First of all it was kinda complicated to connect e2guardian to clamav. It's crashing everytime, when I'm uncomenting contentscanner line with clamav in e2guardian.conf. Problem is - there is no clamd.sock anymore. You need to add in /etc/e2guardian/contentscanners/clamdscan.conf file this:
clamdudsfile = '/var/run/clamav/clamd.ctl'

After that e2guardian will start, but with no access to the internet. In access.log there will be this:

https://mail.yandex.ru/u2709/api/models.jsx?_m=get_user_activity *SCANNED* *DENIED* /tmp/tfTSzDuy: Access denied. ERROR POST 171 0 Content scanning 2 403 application/json  All   - - application/x-www-form-urlencoded,,401,0,,0;

If you try to change pathprefix line in /etc/e2guardian/contentscanners/clamdscan.conf then you will receive this:

https://mail.yandex.ru/u2709/api/models.jsx?_m=get_user_activity *SCANNED* *DENIED* : lstat() failed: No such file or directory. ERROR POST 171 0 Content scanning 2 403 application/json  All   - - application/x-www-form-urlencoded,,401,0,,0;

Commenting pathprefix line and init that comand will solve the problem:

usermod -a -G e2guardian clamav
/etc/init.d/e2guadian restart && /etc/init.d/clamav-daemon restart

Sorry for my English. If I did something wrong, please tell me. Or add it to description of content scaners. 
Everything works ok now. Eicar.org is blocked by AV.

**Comment by fredbcode** [comment]
ok good, maybe you may push this to the group list ?
https://groups.google.com/forum/#!forum/e2guardian
