### ISSUE TITLE
Can't write to socket: Broken pipe Error writing url ipc. (Ignorable)

### ISSUE THREAD

**Issue by dezechristophe** [e2guardian/e2guardian#153]
hi,
e2guardian has "freeze" with those messages : 

2016-11-09T09:20:40.113401+01:00 serveur e2guardian0[11816]: Error writing url ipc. (Ignorable)
2016-11-09T09:20:40.113524+01:00 serveur e2guardian0[11816]: Can't write to socket: Broken pipe
2016-11-09T09:20:40.113590+01:00 serveur e2guardian0[11816]: Error writing url ipc. (Ignorable)
2016-11-09T09:20:40.113718+01:00 serveur e2guardian0[11816]: Can't write to socket: Broken pipe
2016-11-09T09:20:40.113835+01:00 serveur e2guardian0[11816]: Error writing url ipc. (Ignorable)
2016-11-09T09:20:40.114058+01:00 serveur e2guardian0[11816]: Can't write to socket: Broken pipe
2016-11-09T09:21:10.977329+01:00 serveur e2guardian0[11814]: Unable to fork() any more.
2016-11-09T09:24:04.898608+01:00 serveur e2guardian0[11814]: message repeated 52 times: [ Unable to fork() any more.]
2016-11-09T09:24:23.203122+01:00 serveur e2guardian0[11814]: Exiting due to high failure count.
2016-11-09T09:24:23.275492+01:00 serveur e2guardian0[11814]: Main parent process exiting.
2016-11-09T09:24:23.275511+01:00 serveur e2guardian0[11814]: Exiting with error

e2guardian process were still visible  on pstree output but not traffic wer accepted
What can cause that ?

I've restarted service and all went OK

e2guardian -v
e2guardian 3.2.0

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--with-filedescriptors=8192' '--enable-sslmitm=yes'

maxchildren = 4000
minchildren = 128
minsparechildren = 8
preforkchildren = 128
maxsparechildren = 256
maxagechildren = 1000

**Comment by dezechristophe** [comment]
does a "bad" crontab like this one can be the cause ?
00 */3 * * * /bin/sync;/bin/echo "3" > /proc/sys/vm/drop_caches;/bin/sync

**Comment by fredbcode** [comment]
I don't think but why are you using this ?

drop_caches
Writing to this will cause the kernel to drop clean caches, dentries and
inodes from memory, causing that memory to become free.

Do you have something before this lines ? Maybe something not directly related to E2guardian 
Daemon.log ? kern.log ?

2016-11-09T09:20:40.113401+01:00 serveur e2guardian0[11816]: Error writing url ipc. (Ignorable)
2016-11-09T09:20:40.113524+01:00 serveur e2guardian0[11816]: Can't write to socket: Broken pipe

**Comment by dezechristophe** [comment]
thanks
 
I've found this in /var/log/rsyslog/local/kernel/kernel.err.log

[kernel.zip](https://github.com/e2guardian/e2guardian/files/589730/kernel.zip)
[kernel.zip](https://github.com/e2guardian/e2guardian/files/589731/kernel.zip)



2016-11-14T14:28:29.625295+01:00 dans-0442765s.proxy-filtrant.in.ac-nantes.fr kernel: [128888.868482] Out of memory: Kill process 86301 (e2guardian) score 6 or sacrifice child
2016-11-14T14:28:29.625296+01:00 dans-0442765s.proxy-filtrant.in.ac-nantes.fr kernel: [128888.868485] Killed process 86301 (e2guardian) total-vm:221380kB, anon-rss:44720kB, file-rss:0kB
2016-11-14T14:29:04.168417+01:00 dans-0442765s.proxy-filtrant.in.ac-nantes.fr kernel: [128923.188398] Out of memory: Kill process 86373 (e2guardian) score 6 or sacrifice child
2016-11-14T14:29:04.168417+01:00 dans-0442765s.proxy-filtrant.in.ac-nantes.fr kernel: [128923.188400] Killed process 86373 (e2guardian) total-vm:221380kB, anon-rss:40772kB, file-rss:0kB

strange to be tou of memory
root@dans-0442765s:~# free -m
             total       used       free     shared    buffers     cached
Mem:         24096       3577      20518          0         41        242
-/+ tampons/cache:       3292      20803
Partition d'échange:       1951        135       1816

**Comment by dezechristophe** [comment]
[kernel.info.log.zip](https://github.com/e2guardian/e2guardian/files/589750/kernel.info.log.zip)

more infos

**Comment by fredbcode** [comment]
Your system was out of memory, a moment not pemanently.
My advice : you should watch your memory usage every hour and perhaps tune swap with swappiness.

It seems that there is no bug here, the kernel kills some process in this case, this is an usual behavior 



Le 14 novembre 2016 16:48:18 GMT+01:00, dezechristophe <notifications@github.com> a écrit :
>thanks
> 
>I've found this in /var/log/rsyslog/local/kernel/kernel.err.log
>
>[kernel.zip](https://github.com/e2guardian/e2guardian/files/589730/kernel.zip)
>[kernel.zip](https://github.com/e2guardian/e2guardian/files/589731/kernel.zip)
>
>
>
>2016-11-14T14:28:29.625295+01:00
>dans-0442765s.proxy-filtrant.in.ac-nantes.fr kernel: [128888.868482]
>Out of memory: Kill process 86301 (e2guardian) score 6 or sacrifice
>child
>2016-11-14T14:28:29.625296+01:00
>dans-0442765s.proxy-filtrant.in.ac-nantes.fr kernel: [128888.868485]
>Killed process 86301 (e2guardian) total-vm:221380kB, anon-rss:44720kB,
>file-rss:0kB
>2016-11-14T14:29:04.168417+01:00
>dans-0442765s.proxy-filtrant.in.ac-nantes.fr kernel: [128923.188398]
>Out of memory: Kill process 86373 (e2guardian) score 6 or sacrifice
>child
>2016-11-14T14:29:04.168417+01:00
>dans-0442765s.proxy-filtrant.in.ac-nantes.fr kernel: [128923.188400]
>Killed process 86373 (e2guardian) total-vm:221380kB, anon-rss:40772kB,
>file-rss:0kB
>
>strange to be tou of memory
>root@dans-0442765s:~# free -m
>           total       used       free     shared    buffers     cached
>Mem:         24096       3577      20518          0         41       
>242
>-/+ tampons/cache:       3292      20803
>Partition d'échange:       1951        135       1816
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/153#issuecomment-260372143

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
Debian ? Ubuntu ?

J'ai vu Nantes dans les logs, vous utilisez peut-être Éole ?
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by dezechristophe** [comment]
excatement ! ;)
eole 2.5.2
Ubuntu 14.04  LTS

**Comment by dezechristophe** [comment]
avec 20 Go de RAM , je pensais que 4000 children passerait , mais j'ai l'impression que mon calcul doit etre mauvais! ?

**Comment by fredbcode** [comment]
Pas forcément, il y a peut-être juste eu une surcharge un moment, ça arrive.

Tu fais partie de l'équipe d'Eole ?

Le 14 novembre 2016 19:31:35 GMT+01:00, dezechristophe <notifications@github.com> a écrit :
>avec 20 Go de RAM , je pensais que 4000 children passerait , mais j'ai
>l'impression que mon calcul doit etre mauvais! ?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/153#issuecomment-260419932

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by dezechristophe** [comment]
non , même si j'ai participé à quelques projets.
Je gêre l'assistance niveau 3 sur les pare-feux de l'academie de Nantes

Sinon pour mon problème est que e2guardian fini par s'arreter

**Comment by dezechristophe** [comment]
c'est etrange qu'il y ait des processus si gros ?

**Comment by fredbcode** [comment]
Relance tu parfois squid et e2guardian ? Je veux dire un restart complet

**Comment by fredbcode** [comment]
Oups j'oubliais tu fais de l'analyse AV et si oui comment ? Squid + clamav ?

**Comment by dezechristophe** [comment]
en fait calculer le nombre de possible de processus en fonction de la taille de la RAM n'est pas trivial.
j'ai l'impression que plus il y  a de process, plus ils sont gros ?
ex : 
600 process =  1800Mo de RAM = 3Mo/processus
1500 process = 7 Go de RAM = 4,6Mo/processus
2700 process = 16 Go de RAM = 6Mo par process

**Comment by dezechristophe** [comment]
non pas d'AV

**Comment by fredbcode** [comment]
Non ce n'est pas simple ça dépend aussi de ta base de blacklists
Ici avec 3600 process qui tournent je consomme environ 5 Mo par process , sur une machine avec seulement 67 process c'est quasi idem.

J’utilise la commande suivante 
ps aux --sort=rss |grep e2

Mais ça dépend beaucoup de tes règles 

En tout cas si tu utilises au moins 4000 process et si squid bouffe pas mal de ram (dépend aussi de ta conf) je pense que 20 go risque d’être juste, il faudra peut-être envisager de doubler/tripler ta machine ou d’augmenter ta RAM, doubler la machine aurait aussi comme avantage d'ajouter du faillover.

Un petit restart quotidien de squid et e2guardian pourrait aider aussi, par exemple dans une crontab à minuit ou bien lors du logrotate  

Je parle de RAM VSZ en vérité la consommation est plus légère disons 1,5 MO

RSS is the Resident Set Size and is used to show how much memory is allocated to that process and is in RAM. It does not include memory that is swapped out. It does include memory from shared libraries as long as the pages from those libraries are actually in memory. It does include all stack and heap memory.

VSZ is the Virtual Memory Size. It includes all memory that the process can access, including memory that is swapped out and memory that is from shared libraries

**Comment by dezechristophe** [comment]
ok pour info squid est sur une autre machine
j'utilise les blacklist de toulouse, fournit par EOLE.
je vais baisser à 3300 pour voir
pour info
[ps.log.zip](https://github.com/e2guardian/e2guardian/files/591555/ps.log.zip)

**Comment by fredbcode** [comment]
Ok je clôture le ticket ce soir, si besoin d'en discuter ouvre plutôt une discussion ici 
https://groups.google.com/forum/#!forum/e2guardian
