### ISSUE TITLE
Reload is not sufficient after changing filter of an ipgroup

### ISSUE THREAD

**Issue by baby-gnu** [e2guardian/e2guardian#158]
Hello,

When changing the `filter` of an `ipgroups`, we must restart e2guardian for the change to be effective.

According to the documentation `e2guardian -g` should be sufficient.

Step to reproduce:

1. set a filter `blockall` to block everything
2. set an `ipgroups` using the `blockall` filter
3. reload e2guardian `e2guardian -g`
4. try to surf on a website from a host within the defined `ipgroups` → it must fail
5. set a new filter `allowall` to allow everything
6. change the `ipgroups` filter to `allowall`
7. reload e2guardian `e2guardian -g`
8. try to surf on a website from a host within the defined `ipgroups` → it should works

In our tests we find that we needed to restart e2guardian instead of the `e2guardian -g`.

Regards.

e2guardian version is 3.2.0

**Comment by fredbcode** [comment]
Yes there is some know bugs with gentle restart, however gentle restart does not kill current connections a full application can take some time  
Only filter group config is re-read aka "filtergroupslist"

http://contentfilter.futuragts.com/wiki/doku.php?id=command_line_usage&DokuWiki=wdievqxsxe

FYI a restart stop anything except a large file download

**Comment by fredbcode** [comment]
I can close ?

**Comment by baby-gnu** [comment]
For us, yes.
