### ISSUE TITLE
Too many temp files for download...

### ISSUE THREAD

**Issue by tachtler** [e2guardian/e2guardian#159]
Hi,

If've seen lots of files generated by e2guardien, **I think using the option `filecachedir = '/tmp'`**, there will be lot's of files generated like the follwoing list:

```
-r--r----- 1 e2guardian e2guardian 11786957 Dec 17 07:33 tfTmNTS2
-r--r----- 1 e2guardian e2guardian 11786957 Dec 17 07:39 tfU4w0Pu
-r--r----- 1 e2guardian e2guardian 11786957 Dec 14 06:38 tfuN2Tr3
-r--r----- 1 e2guardian e2guardian 11786957 Dec 14 17:43 tfw3yq6N
-r--r----- 1 e2guardian e2guardian 11786957 Dec 14 09:10 tfwDdVRu
-r--r----- 1 e2guardian e2guardian 11786957 Dec 14 17:35 tfWPosOK
-r--r----- 1 e2guardian e2guardian 11786957 Dec 13 19:08 tfXt8Hyk
-r--r----- 1 e2guardian e2guardian 11786957 Dec 16 18:54 tfxUirjl
-r--r----- 1 e2guardian e2guardian 11786957 Dec 17 07:32 tfYewPKl
-r--r----- 1 e2guardian e2guardian 11786957 Dec 17 07:34 tfYqkPlh
-r--r----- 1 e2guardian e2guardian   405886 Dec 18 16:51 tfzKtdhu
-r--r----- 1 e2guardian e2guardian 11786957 Dec 14 06:43 tfZMG2EP
```
**All files start with tf** ...

How can this problem be solved?

Did I make a configuration mistake?

Thank you for your help!
Klaus Tachtler.

**Comment by fredbcode** [comment]
Which AV, clamav ? If yes, there was a know problem upgrade corrected it

**Comment by tachtler** [comment]
Hi,

yes you're right, I use ClamAV under CentOS-7.2 - but I use the package from EPEL-Repo... Can you give me some more information, how can I solve this?

Thank you!
Klaus.

**Comment by fredbcode** [comment]
Sorry I don't known (I'm not using clamav and centos) 
Which version version are you using ? Maybe there is some update for Centos ?

At worst you make a little script, like this

service e2guardian stop
rm -Rf /tmp/tf* -> I think you should use an another directory to avoid problem 
service e2guardian start

In crontat at midnight

**Comment by tachtler** [comment]
Hi,

thank you, I will make the latest CentOS update from 7.2 to 7.3 - maybe the problem will be solved with that?

Thank you for your answer!
Klaus.

**Comment by fredbcode** [comment]
Feel free to reopen if not

**Comment by tachtler** [comment]
Hi,

I will keep an eye on it, will update and than I will see. First thing I did, I increase the memory for scanning object to 51200 and this prevent till now the creation of the files too.

Thank you for your support!
Klaus.

**Comment by tachtler** [comment]
Hi Frédéric,

thank you for your tip with clamav, but there will be a patch starting with version 0.99.3 and the actual stable are 0.99.2. So I have to wait for that version. 

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Frédéric,

I had contact with Robert and he was so nice to make an update for ClamAV. The update is still in prgress, but I hope I can test it in the next few days. I will report, if the problem with the closed/not deleted temp files will be gone!

`* Sun Nov 26 2017 Robert Scheck <robert@fedoraproject.org> - 0.99.2-13 - Backported upstream patch to unbreak e2guardian vs. temp files`

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Frédéric,

**Extract from the e-mail to Robert: [https://bodhi.fedoraproject.org/updates/clamav-0.99.2-13.el7](url)**

> Hi Robert,
> 
> thank you, thank you, thank you for updating the package and integrating the patch, IT WORKS for me!
> 
> Here some LOG lines from /var/log/clamd.log under CentOS-7.4 (clamav-server):
> 
> ```
> Nov 30 10:44:27 vml70050 clamd[1565]: /tmp/tfuxXwf8: Eicar-Test-Signature FOUND
> Nov 30 10:44:54 vml70050 clamd[1565]: /tmp/tfmOLFsu: Eicar-Test-Signature FOUND
> Nov 30 10:45:26 vml70050 clamd[1565]: /tmp/tf0Ne071: Eicar-Test-Signature FOUND
> Nov 30 10:45:33 vml70050 clamd[1565]: /tmp/tfBhAssR: Eicar-Test-Signature FOUND
> Nov 30 10:45:38 vml70050 clamd[1565]: /tmp/tfx8lHKR: Eicar-Test-Signature FOUND
> ```
> AND
> 
> ```
> # ls -la /tmp/tf*
> ls: cannot access /tmp/tf*: No such file or directory
> ```
> 
> Seems to work!
> 
> Thank you
> Klaus.

**Comment by fredbcode** [comment]
So great

**Comment by tachtler** [comment]
Hi 

after testing a while, there will be still an issue - I open a new bug report at ClamAV Bugzilla:

https://bugzilla.clamav.net/show_bug.cgi?id=11984

Sorry, but the problems still occur after and after.

Thank you
Klaus.

**Comment by tachtler** [comment]
Hi Frédéric,

can you take a look into this bug report of ClamAV?
https://bugzilla.clamav.net/show_bug.cgi?id=11984

Maybe the problem occurs not in ClamAV? 
Maybe e2guardian creates the file and some circumstance will prevent the deletion of the file, when e2guardian and ClamAV work together?

Thank you!
Klaus.

**Comment by fredbcode** [comment]
Duplicate bug report

**Comment by fredbcode** [comment]
Duplicate
