### ISSUE TITLE
Missing authplugins from E2 3.4.0.3 deb package

### ISSUE THREAD

**Issue by cnighswonger** [e2guardian/e2guardian#160]
I am working on moving a content filter server currently running DG over to E2. 

I installed e2guardian from the deb package available [here.](https://github.com/e2guardian/e2guardian/releases/download/v3.4.0.3/e2guardian_3.4.0.3_wheezy-jessie_amd64.deb)

While porting our current DG config over to E2, I notice the omission of the five authplugins originally included in the DG code. They are missing from the e2guardian/lists/authplugins subdir while the feature is still available in the e2guardian.conf file. These plugins are included in the [repo.](https://github.com/e2guardian/e2guardian/tree/master/configs/authplugins)

This seems to be a bug with the deb package.

**Comment by fredbcode** [comment]
I think that there is nothing missing in code, maybe I just forgot some configs files in my latest package.
You can find the files on github, I will take a look soon
Can you try to completly remove e2 and reinstall ?

Le 7 janvier 2017 04:58:01 GMT+01:00, Chris Nighswonger <notifications@github.com> a écrit :
>I am working on moving a content filter server currently running DG
>over to E2. 
>I installed e2guardian from the deb package available here:
>
>
>There are a number of "housekeeping" issues evident which appear to be
>"left over" from the fork of DG by Frederic. One which appears to
>affect things is the omission of the five authplugins originally
>included in the DG code. They are missing from the
>e2guardian/lists/authplugins subdir while the feature is still
>available in the e2guardian.conf file.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/160

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by cnighswonger** [comment]
The config files are definitely missing from the current deb package. I just put them there manually. This machine is in production, so I cannot remove/reinstall at the moment. It will be June before I can take it down again.

Otherwise things seem to be ok. Porting over the old DG config and lists was pretty straightforward.

My reference to "housekeeping" issue comes from finding references to DG in various configuration files of E2.

I have used DG for 17 years. Dan and Phillip are great fellows and had a really good product. I'm glad to see someone has chosen to continue the good work.

Chris

**Comment by fredbcode** [comment]
I checked the files are in e2guardian_3.4.0.3_wheezy-jessie_amd64.deb 
Which version are you using ?

**Comment by cnighswonger** [comment]
e2guardian_3.4.0.3_wheezy-jessie_amd64.deb

And I see that dpkg -c does show the files in the list... very weird indeed. They did not install when I did dpkg -i. Not sure what happened there at all, but sorry for any false alarm!

**Comment by fredbcode** [comment]
No problem, I will make a test to be sure ...

**Comment by fredbcode** [comment]
I confirm no problen with fresh installation
