### ISSUE TITLE
Multiple filters per users

### ISSUE THREAD

**Issue by fcruzcoelho** [e2guardian/e2guardian#161]
Good afternoon,

I'm trying to perform a multiple filter setup for the same users, in different groups.

GROUP = Basic filter2 (blocks facebook)
GROUP = social filter3 allow to some users

It is possible to bypass filter2 for facebook only

Joao = filter2
Joao = filter3

It would be possible?

Thank you

**Comment by fredbcode** [comment]
No only the first will be applied

Le 10 janvier 2017 19:33:08 GMT+01:00, fcruzcoelho <notifications@github.com> a écrit :
>Good afternoon,
>
>I'm trying to perform a multiple filter setup for the same users, in
>different groups.
>
>Joao = filter2
>Joao = filter3
>
>It would be possible?
>
>Thank you
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/161

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fcruzcoelho** [comment]
Thank you
