### ISSUE TITLE
Missing Dependency Check

### ISSUE THREAD

**Issue by cnighswonger** [e2guardian/e2guardian#162]
OS: CentOS 7.2.1511
e2guardian: master

configure.ac appears to be missing a check for openssl development libraries. I configured with the following options and received no errors:

`./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--with-filedescriptors=8192' '--enable-sslmitm=yes'`

but running `make` resulted in the following sorts of errors which installing openssl-devel corrected:

`Socket.hpp:15:25: fatal error: openssl/ssl.h: No such file or directory
 #include "openssl/ssl.h"
                         ^
compilation terminated.
In file included from FDTunnel.hpp:14:0,
                 from FDTunnel.cpp:28:
Socket.hpp:15:25: fatal error: openssl/ssl.h: No such file or directory
 #include "openssl/ssl.h"
                         ^
compilation terminated.
In file included from DataBuffer.hpp:10:0,
                 from DownloadManager.hpp:14,
                 from OptionContainer.hpp:10,
                 from ConnectionHandler.hpp:11,
                 from ConnectionHandler.cpp:8:
Socket.hpp:15:25: fatal error: openssl/ssl.h: No such file or directory
 #include "openssl/ssl.h"
`

Chris

**Comment by fredbcode** [comment]
Ok thanks, fixed in dev branch
