### ISSUE TITLE
Auth plugin returned error code: -3  

### ISSUE THREAD

**Issue by fcruzcoelho** [e2guardian/e2guardian#164]
Good Morning,

After performing the configuration of e2guardian with the NTLM plugin for user authentication by multiple groups in some cases I receive the message below.

NTLM - Invalid message of length 33, message was: NTLMSSP
Auth plugin returned error code: -3

And some users report that they need to re-authenticate.

Has anyone ever had this problem? Would you help me?

Thank you

**Comment by fredbcode** [comment]
Can you provide more explanations about your configuration ? Did you see bug #130 ?

**Comment by fcruzcoelho** [comment]
Good Morning,

I use ntlm_auth with other services to perform authentication with my active directory, below.

1. kerberos
2. samba
3. winbind

Line used for the proxy (squid) to perform authentication of users of the active directory, below.

Auth_param ntlm program / usr / bin / ntlm_auth --helper-protocol = squid-2.5-ntlmssp --domain = DOMAIN
Auth_param ntlm children 200 startup = 0 idle = 1
Auth_param ntlm keep_alive on

But I did believe that I found the problem, that it was permission in the following winbind files / directories.

Follow command for permission.
    - chgrp squid / var / run / samba / winbindd || Return 1
    - chgrp squid / var / lib / samba / winbindd_privileged || Return 1

After this change the same stopped requesting users / password.

I'm still monitoring.

Thank you for your help.

**Comment by fredbcode** [comment]
Ok do you have problem with https ? some sites like https://www.cmb.fr https://www.youtube.com

**Comment by fcruzcoelho** [comment]
No, apparently normal https access, I just noticed that it does not appear in the logs access, but it can be by the type of log that I configured it is (2 - CSV-format)

And the pages that are blocked https, does not show the block page but it's because I did not configure the certificates to perform this filter.

Thank you

**Comment by fredbcode** [comment]
Which version are you using ?

**Comment by fcruzcoelho** [comment]
Good Morning,

I am using the versions below.
Because? is there any problem?

squid:  3.5.23
e2guardian: 3.4.0.3

Thank you

**Comment by fredbcode** [comment]
Yes I do not understand you must see bug #130 
Please, can you try this

Put a user in filter group 2 

# cat common/filtergroupslist
user=filter2

filter1 = default (where youtube.com is blacklisted)
filter2 = (where youtube.com is allowed/not blacklisted)

Actually there is a bug youtube is blocked

**Comment by fcruzcoelho** [comment]
fredbcode,

I did the tests requested, normal access.
In my environment there are two groups.

Web_lib_avigated = filter2
Web_lib_basico_new = filter5

fabiocoelho-sao=filter2 accesses youtube.com
xteste=filter5 access denied at youtube.com.

The accesses for youtube coming out of filter = 2 are carried out successfully, this is both http/https.

But the hits for youtube coming out of filter = 5 are blocked successfully, so much for http/https.

Follow Print.
![snapshot84](https://cloud.githubusercontent.com/assets/13903548/22110451/e624d5ac-de42-11e6-9248-d3c2d6df13e5.png)
![snapshot85](https://cloud.githubusercontent.com/assets/13903548/22110450/e62311c2-de42-11e6-860b-e22be8f7cd2a.png)

To do some locks I am using the blacklist (shallalist) the locks are successfully done but in my default page the access denied does not show the category, I have already moved the listcategories option but it does not appear.

Could you help me with this problem here or open another issue.

Follow Print:
![snapshot83](https://cloud.githubusercontent.com/assets/13903548/22110656/a148148e-de43-11e6-9a8d-866d5f183d37.png)

Thank you

**Comment by fredbcode** [comment]
Can you make a try with logexceptionhits = 2 and loglevel = 1 
NTLM works with IE for you ?

**Comment by fcruzcoelho** [comment]
Tests performed successfully as requested.

NTLM works normal with IE.

Could you help me with the issue of categories with blacklist (shallalist) as above print.

Thank you

**Comment by fredbcode** [comment]
Yes, please make a try with logexceptionhits = 2 and loglevel = 1
And add a groupname value in each e2guadianfx.conf

After that report the result

**Comment by fcruzcoelho** [comment]
Following, results.

Even though the category does not show on the block page, do you know what it can be?

Follow Print:
![snapshot86](https://cloud.githubusercontent.com/assets/13903548/22145445/87c5de1a-dee8-11e6-9d41-176f52628c9f.png)
![snapshot87](https://cloud.githubusercontent.com/assets/13903548/22145444/87c512f0-dee8-11e6-9b4a-09836927b87c.png)
![snapshot88](https://cloud.githubusercontent.com/assets/13903548/22145446/87c87bc0-dee8-11e6-8000-30f84b773975.png)

Thank you

**Comment by fredbcode** [comment]
Do you have a category in the file with this domain ? 

Try first at first line: 
#listecategory:"blabla"

And restart e2guardian

You must be sure that xvideosporno.blog.br is ONLY on this file

**Comment by fcruzcoelho** [comment]
Yes I have, I did one more test with only one domain that I'm sure is in the porn category.

Follow Print:
![snapshot89](https://cloud.githubusercontent.com/assets/13903548/22146105/b67dff24-deea-11e6-8a20-061c551e5039.png)
![snapshot90](https://cloud.githubusercontent.com/assets/13903548/22146104/b67dcbd0-deea-11e6-96f6-7c42a6be8f79.png)
![snapshot91](https://cloud.githubusercontent.com/assets/13903548/22146106/b67fca70-deea-11e6-8a3b-7b469d36984c.png)

Even so, it does not show the category that this domain belongs to,

Does it need to do any more configuration ?.

Thank you

**Comment by fredbcode** [comment]
Do you have put this ?
#listecategory:"blabla"
in porn/domains

**Comment by fredbcode** [comment]
Same in /domains/url

**Comment by fcruzcoelho** [comment]
I do not understand, it's to insert #listecategory: "bla bla" into:
/ Blacklists / e2guardian / BL / porn / domains
/ Blacklists / e2guardian / BL / porn / urls
Would not it be within / etc / e2guardian / lists / bannedsitelist?

On the line

# List categorization
#listcategory: "porn"

Thank you

**Comment by fredbcode** [comment]
It's just for testing
Just check if there is listcategory:"whateveryouwant" in domain and urls

**Comment by fcruzcoelho** [comment]
Excuse me but I can not understand,

I insert listcategory: "whateveryouwant" into.

/ Blacklists / e2guardian / BL / porn / domains
/ Blacklists / e2guardian / BL / porn / urls

Even so he did not show.

![snapshot93](https://cloud.githubusercontent.com/assets/13903548/22147064/22b1a238-deee-11e6-9828-d015243117d1.png)

Thank you

**Comment by fredbcode** [comment]
must be a comment #

**Comment by fredbcode** [comment]
#listcategory:"whateveryouwant"

**Comment by fcruzcoelho** [comment]
Yes I put it with and without the #, it still did not work.
Do you use it that way?
Could you show me a print?

Thank you

**Comment by fredbcode** [comment]
#listcategory:"liste_noire"
no-ip.org

2017.1.20 7:28:23 fred 10.92.48.183 http://no-ip.org *DENIED* Site interdit : no-ip.org GET 0 0 liste_noire 3 403 -  groupe3 Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0  - - 

I'm not using a page right now, but still you must see something like this in your log

**Comment by fredbcode** [comment]
You block with squid maybe ?

**Comment by fcruzcoelho** [comment]
Yes,
"2017.1.20 9:14:22","fabiocoelho-sao","172.16.75.157","http://www.sambaporno.com","*DENIED* Blocked site: sambaporno.com","GET","0","0","","2","403","-","","web_lib_avancado","","","-","-",""
"2017.1.20 9:14:22","fabiocoelho-sao","172.16.75.157","http://www.sambaporno.com/style.css","*DENIED* Blocked site: sambaporno.com","GET","0","0","","2","403","-","","web_lib_avancado","","","-","-",""

Not Squid is just for caching.

Tks

**Comment by fcruzcoelho** [comment]
I did these steps too, but it does not work.

http://contentfilter.futuragts.com/wiki/doku.php?id=downloadable_blacklists

tks

**Comment by fredbcode** [comment]
Ok great so the category is right, the webpage should show this value

**Comment by fcruzcoelho** [comment]
Okay, but it's not showing to me :)

How your logfileformat?

Mine is like this

Logfileformat = 2

Thank you

**Comment by fredbcode** [comment]
Hum sorry answer to fast ...
Can you make grep -r sambaporno.com in all your lists ?

**Comment by fredbcode** [comment]
Not related but "Auth_param ntlm keep_alive on" breaks IE here 
Ubuntu 16.04 win 10 and edge

**Comment by fcruzcoelho** [comment]
Yes, 

root@btu-squid01:~#  grep -r sambaporno.com /blacklists/e2guardian/BL/*
/blacklists/e2guardian/BL/porn/domains:sambaporno.com
root@btu-squid01:~#

**Comment by fredbcode** [comment]
Ok like this I don't known, I must investigate 
Can you try with a unusual website something like azertyuiop.com
#listcategory:"liste_noire"
azertyuiop.com

e2guardian is restarted not reloaded ?

**Comment by fcruzcoelho** [comment]
Yes, e2guardian restarts

logfileformat=5

Yours is the same?

Tks

**Comment by fredbcode** [comment]
logfileformat = 1 

Please try this
"Can you try with a unusual website something like azertyuiop.com
#listcategory:"liste_noire"
azertyuiop.com"

**Comment by fredbcode** [comment]
Just add azertyuiop.com in you file

**Comment by fcruzcoelho** [comment]
Fred,

Thanks for the patience and help, now it worked out, I do not know why the other time did not roll.

Reset the config including the
#listcategory: "porn" in the file below.
/ Blacklists / e2guardian / BL / porn / domains

I rebooted e2guardian and it showed the category.
![snapshot94](https://cloud.githubusercontent.com/assets/13903548/22148715/d7e2ce40-def6-11e6-8133-167be0c9c317.png)
![snapshot95](https://cloud.githubusercontent.com/assets/13903548/22148716/d7e459e0-def6-11e6-8eb6-aee951386cd2.png)


Thank you

**Comment by fredbcode** [comment]
Ok great 

Just for helping (another bug)
Can you take a look at this

In squid.conf "Auth_param ntlm keep_alive on" breaks IE here
Ubuntu 16.04 win 10 and edge

Same for you ? Win10 and edge ?

**Comment by fcruzcoelho** [comment]
Mine is with
Auth_param ntlm keep_alive on

And I have not encountered any problems with IE / edge so far.

My environment is in cluster with CentOS7 already I use the same one to more than 3 years. But now I'm migrating SquidGuard to e2guardian and so far doing very well.

What break is happening in yours?

Thank you

**Comment by fredbcode** [comment]
No identification at all, and with "Auth_param ntlm keep_alive off" no problem 
But it works with firefox in both case

**Comment by fcruzcoelho** [comment]
Got it,
But here we no longer use IE, because it is incompatible with several web applications, but the tests we did with it did not present any problem, so far.

As I reported I used squid with NTLM authentication for over 3 years, and we never had any problems in the navigation part with IE.

Need I do some more analysis?

Thank you

**Comment by fredbcode** [comment]
No thanks again,
I close
