### ISSUE TITLE
Youtube adds killing videos

### ISSUE THREAD

**Issue by winewood** [e2guardian/e2guardian#174]
Running at current branch: develop
The good: MITM is working for every site. It scans, blocks, and does it's job. Google redirection is great, and reddit scanning and blocking is perfect!

The Bad: https://www.youtube.com is blackscreening with error every 2nd video with pauses each commercial many times to black window with unrecoverable error.

Dec 26 19:19:09 ubuntu-minimal e2guardian[8743]: ssl_read failed
Dec 26 19:19:09 ubuntu-minimal e2guardian[8743]: error:140780E5:SSL routines:ssl23_read:ssl handshake failure
Dec 26 19:19:12 ubuntu-minimal e2guardian[9218]: ssl_write failed
Dec 26 19:19:12 ubuntu-minimal e2guardian[9222]: ssl_write failed <-- appear each youtube ad.

I am not sure how MITM is still working with these errors. Cert's are being generated, no site is blocked due to them. Youtube is getting wrecked with annoyances, and is almost unusable. Firefox, Chrome, it doesn't matter. Added youtube to nocheckcrtlist and exceptionlist, but these SSL errors apparently originate from the numerous ads outside the youtube domain, and will only impact service during ad insertion. Is there a work around for an HTTPS site like youtube that requests add content via SSL? The videos rely on ads in order to play in many cases.

**Comment by fredbcode** [comment]
Please can you make a try with an exclusion for .googlevideo.com ?
As far I can tell the video are played from domains outside youtube.com
I denied ADS (but I'm not using SSLMITM to be honest) without any problem with youtube

https://r15---sn-4gxx-25gee.googlevideo.com/videoplayback?upn=i91DlMm_IB0&lmt=1449602798393333&expire=1486859035&mime=audio%2Fwebm&ipbits=0&initcwndbps=741250&pl=15&signature=A912939136150B2AB8C57F339803879148F58291.3038CEE218EDF5F31A7106D32206EE9167294082&key=yt6&nh=EAE&ip=88.174.120.52&itag=251&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ei=u1afWJWvJMT-cNzjuvgF&requiressl=yes&keepalive=yes&source=youtube&clen=17545645&mt=1486837404&mv=m&ms=au&gir=yes&mm=31&mn=sn-4gxx-25gee&id=o-APsvGzuTVHPX636WRsPxGu1aktdxEBaNDW0m53-j7QeI&dur=1110.401&alr=yes&ratebypass=yes&cpn=98vH-rDGvDTNcYOd&c=WEB&cver=2.20170209&range=783532-1088895&rn=54&rbuf=39605

GET /videoplayback?upn=i91DlMm_IB0&lmt=1449602798393333&expire=1486859035&mime=audio%2Fwebm&ipbits=0&initcwndbps=741250&pl=15&signature=A912939136150B2AB8C57F339803879148F58291.3038CEE218EDF5F31A7106D32206EE9167294082&key=yt6&nh=EAE&ip=88.174.120.52&itag=251&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ei=u1afWJWvJMT-cNzjuvgF&requiressl=yes&keepalive=yes&source=youtube&clen=17545645&mt=1486837404&mv=m&ms=au&gir=yes&mm=31&mn=sn-4gxx-25gee&id=o-APsvGzuTVHPX636WRsPxGu1aktdxEBaNDW0m53-j7QeI&dur=1110.401&alr=yes&ratebypass=yes&cpn=98vH-rDGvDTNcYOd&c=WEB&cver=2.20170209&range=783532-1088895&rn=54&rbuf=39605 HTTP/1.1
Host: r15---sn-4gxx-25gee.googlevideo.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://www.youtube.com/watch?v=nWpWOvr9itw
Origin: https://www.youtube.com
DNT: 1
Connection: keep-alive

HTTP/1.1 200 OK
Last-Modified: Tue, 08 Dec 2015 19:26:38 GMT
Content-Type: audio/webm
Date: Sat, 11 Feb 2017 18:24:08 GMT
Expires: Sat, 11 Feb 2017 18:24:08 GMT
Cache-Control: private, max-age=21287
Accept-Ranges: bytes
Content-Length: 305364
Connection: keep-alive
Alt-Svc: quic=":443"; ma=2592000
Access-Control-Allow-Origin: https://www.youtube.com
access-control-allow-credentials: true
timing-allow-origin: https://www.youtube.com
access-control-expose-headers: Client-Protocol, Content-Length, Content-Type, X-Bandwidth-Est, X-Bandwidth-Est2, X-Bandwidth-Est-Comp, X-Bandwidth-Avg, X-Head-Time-Sec, X-Sequence-Num, X-Segment-Lmt, X-Walltime-Ms
X-Content-Type-Options: nosniff
Server: gvs 1.0

**Comment by fredbcode** [comment]
As you can see the referrer is youtube.com but the parts of the videos are in many subdomains like https://r15---sn-4gxx-25gee.googlevideo.com

**Comment by winewood** [comment]
Thank you for posting this.   I will add this to my exception list.  Since I have re-direct on to safe, it is ok to allow only google safe search on, instead of page inspection.   
I am using man-in-the-middle and will test.  It would always play the video initially, but only when the ads hit does it hit the black screens.

The MITM is the money with this product imho.   I am seeing another error, but I want to test it further prior to submission.  Will tell you in a few days on the status of this problem with that fix implemented.

**Comment by fredbcode** [comment]
It's better now ?

**Comment by winewood** [comment]
YES, it is better now.   Thank you for the follow up.
