### ISSUE TITLE
e2guardian[22495]: E2guardian is running out of MaxChildren process: 379 maxchildren: 380

### ISSUE THREAD

**Issue by mviniciusleal** [e2guardian/e2guardian#175]
Hi, im getting this error "E2guardian is running out of MaxChildren". I've tried both 3.4.0.3 and 3.5.0.
I tried to increase:
maxsparechildren
maxagechildren
maxchildren

I had set maxchildren  to 1000 but the problem either occurs.
Its possible to see what access is using the process (Something like mod_status, to map get online state of each slot and map with acess)?

Following my config:
languagedir = '/opt/e2guardian-3.4.0.3/share/e2guardian/languages'
language = 'ptbrazilian'
loglevel = 2
logexceptionhits = 2
logfileformat = 3
dstatlocation = '/opt/e2guardian-3.4.0.3/var/log/e2guardian/dstats.log'
filterip = 192.168.131.254
filterip = 192.168.133.254
filterports = 8080
filterports = 8080
proxyip = 127.0.0.1
proxyport = 3128
proxytimeout = 20
proxyexchange = 20
pcontimeout = 55
usecustombannedimage = on
custombannedimagefile = '/opt/e2guardian-3.4.0.3/share/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/opt/e2guardian-3.4.0.3/share/e2guardian/blockedflash.swf'
filtergroups = 3
filtergroupslist = '/opt/e2guardian-3.4.0.3/etc/e2guardian/lists/filtergroupslist'
bannediplist = '/opt/e2guardian-3.4.0.3/etc/e2guardian/lists/bannediplist'
exceptioniplist = '/opt/e2guardian-3.4.0.3/etc/e2guardian/lists/exceptioniplist'
showweightedfound = on
urlcachenumber = 1000
urlcacheage = 900
scancleancache = on
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
prefercachedlists = off
maxcontentfiltersize = 256
maxcontentramcachescansize = 2000
maxcontentfilecachescansize = 20000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
downloadmanager = '/opt/e2guardian-3.4.0.3/etc/e2guardian/downloadmanagers/fancy.conf'
downloadmanager = '/opt/e2guardian-3.4.0.3/etc/e2guardian/downloadmanagers/default.conf'
contentscannertimeout = 60
contentscanexceptions = off
authplugin = '/opt/e2guardian-3.4.0.3/etc/e2guardian/authplugins/ip.conf'
mapauthtoports = off
recheckreplacedurls = off
forwardedfor = off
usexforwardedfor = off
logconnectionhandlingerrors = on
logsslerrors = off
logchildprocesshandling = off
maxchildren = 380
minchildren = 64
minsparechildren = 16
preforkchildren = 20
maxsparechildren = 64
maxagechildren = 10000
maxips = 0
ipcfilename = '/tmp/.e2guardianipc'
urlipcfilename = '/tmp/.e2guardianurlipc'
ipipcfilename = '/tmp/.e2guardianipipc'
nodaemon = off
nologger = off
logadblocks = off
loguseragent = off
softrestart = off
ssl_mitm = off

**Comment by fredbcode** [comment]
I guess there is no bug here, please use the mailling list
I guess you should increase your maxchildren value beyond 1024 

Do you have something else un syslog ?

----- mviniciusleal <notifications@github.com> a écrit :

**Comment by fredbcode** [comment]
Please post your questions, comments, ideas and feedback, here https://groups.google.com/forum/#!forum/e2guardian
