### ISSUE TITLE
NTLM auth problem

### ISSUE THREAD

**Issue by neradpeter** [e2guardian/e2guardian#177]
Sorry,  please close it

**Comment by fredbcode** [comment]
Why "close it" please can you explain ? I have another user with this problem, I think you can help

**Comment by neradpeter** [comment]
Ok... so

I have problem with auth, every time a got only this in log:

> NTLM - step 2 was not part of an auth handshake! (HTTP/1.1 200 OK#015)
> Auth plugin returned error code: -1

the html status messages was various

I had to setup x_forwarded_for directives on booth sides (squid, e2guardian) and auth is ok.

Relatively ok :-D

Now i have problem with:

> E2guardian is running out of MaxChildren process: 179 maxchildren: 180

and sometimes 

> NTLM - Invalid message of length
> Auth plugin returned error code: -3

and sometime with NTLM error code: -1 

but i hope the error "out of" is base problem... and to solve it I need more free time


I need to compile latest e2guardian on old system Fedora 17 :-)

**Comment by fredbcode** [comment]
Ok thanks

**Comment by fredbcode** [comment]
Related with #178 ?

**Comment by fredbcode** [comment]
Fixed un 3.5.1
