### ISSUE TITLE
No compiled package for PfSense?

### ISSUE THREAD

**Issue by forid786** [e2guardian/e2guardian#179]
Hey E2Guardian Users,

Anyone been able to create a package for PfSense for the latest version? I'm pretty new to this so trying to get it up and running with PfSense.

I guess it requires BSD for compilation too...

**Comment by forid786** [comment]
Can anyone compile this on BSD?

**Comment by fredbcode** [comment]
As the problem is not related with E2 I will close this ticket, but you can try to open a discussion here:
https://groups.google.com/forum/#!forum/e2guardian
