### ISSUE TITLE
killall for logrotation causes service interruption

### ISSUE THREAD

**Issue by spikedrba** [e2guardian/e2guardian#180]
Dear all,

I've just finished migrating to a new install of e2g, great stuff, thanks for all the work this community put into it.

One thing I noticed, which isn't really great for us, is that by default e2g ships with a logrotation script that kills e2g (see data/scripts/e2guardian.in). Could this be avoided? I understand that whatever daemon needs to let go of the FD it's writing to so that it can log to the new file, but is there a reason why a SIGHUP or similar won't do? restarting the whole shebang, especially with a lot of processes like in our case, is quite a pain.

thanks,

Spike

**Comment by fredbcode** [comment]
You can try e2guardian -r but not tested by me 

> especially with a lot of processes like in our case, is quite a pain.

?  I'm using 5000 process here, and I restart e2guardian twice by day 
Users should be not disconnected ? Only large download must be impacted 

A logrotate at midnight is a problem for your users ?

**Comment by spikedrba** [comment]
thank @fredbcode , I tried -r, but it didn't work at least for the settings I was working with at the time, I had to issue a restart to see things changing. Maybe there's cases where -r works tho, not sure, haven't tested too closely.

Yeah I'm moving the logrotate to a different time/midnight, but I wanted to check if there was a way around it. Regarding users not disconnected, if a e2g process is parsing a request and you killit how is the user not going to be disconnected? Or does the stop wait for a process to have completed serving a request before killing it? in which case I guess I have no problem even tho it seems there's potentially a window where you're not able to serve requests.

Out of curiosity how long does it take with those many processes to restart? on a pretty modern server on my end it takes almost 30 secs with 300 processes...

thanks,

Spike

**Comment by fredbcode** [comment]
Right now 2750 process 
3 seconds, just a little freeze for users, the sessions to the websites still opened

**Comment by spikedrba** [comment]
ok thanks, guess will have to figure out why it takes so much longer on mine. mind to share specs of your box?

**Comment by fredbcode** [comment]
Yes 
reportinglevel = 3 
loglevel = 1 
logexceptionhits = 2
logfileformat = 1
proxyfailureloginterval = 100
filtergroups = 5 
showweightedfound = off
weightedphrasemode = 0
urlcachenumber = 0
urlcacheage = 0
phrasefiltermode = 1
preservecase = 1
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = on
reverseclientiplookups = off
logclienthostnames = off
createlistcachefiles = on
maxuploadsize = -1
maxcontentfiltersize = 0 
usernameidmethodproxyauth = on
maxcontentramcachescansize = 0
maxcontentfilecachescansize = 0
deletedownloadedtempfiles = off
initialtrickledelay = 40
proxytimeout = 60
proxyexchange = 30
pcontimeout = 15
trickledelay = 20
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
authplugin = '/etc/e2guardian/authplugins/proxy-digest.conf'
authplugin = '/etc/e2guardian/authplugins/proxy-basic.conf'
recheckreplacedurls = off
forwardedfor = on
usexforwardedfor = off
logconnectionhandlingerrors = on
logchildprocesshandling = off
maxchildren = 6000 
minchildren = 64
minsparechildren = 15 
preforkchildren = 20
maxsparechildren = 80
maxagechildren = 10000 
maxips = 0  
softrestart = on

**Comment by spikedrba** [comment]
thanks, what kind of machine are you running this on? I'm using a E5-2650 DP Xeon SM X9DRW with 128GB ram and SSD drives. This should be blazing fast given the load, but I just tested again and it took 3 seconds to stop e2g and then **8 seconds** to get it back up. At the time of the test I had 320 processes going, so a fraction of yours.

This is my config (relevant process part only):
urlcachenumber = 1000
urlcacheage = 1800
scancleancache = on
phrasefiltermode = 1
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
prefercachedlists = off
maxcontentfiltersize = 1024
maxcontentramcachescansize = 2048
maxcontentfilecachescansize = 20000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
contentscannertimeout = 60
contentscanexceptions = off
recheckreplacedurls = off
forwardedfor = off
usexforwardedfor = off
logconnectionhandlingerrors = on
maxchildren = 1000
minchildren = 20
minsparechildren = 10
preforkchildren = 10
maxsparechildren = 25
maxagechildren = 2000

**Comment by fredbcode** [comment]
> 8 seconds to get it back up

Can you make a try with e2guardian -N ?
You mean 8 seconds to start, not to reach 320 processes I guess ?

Are you using an AV  ? If yes, can you disabled it ?

**Comment by spikedrba** [comment]
I will try with -N, I need to set up another test bench to also try the dev branch per other bug.

8 Seconds to start the minchildren, ie 20.

not using any AV

**Comment by fredbcode** [comment]
Maybe you are using a very huge blacklist ? About mine the total size is 4,2 MB, more or less 150 000 domains

**Comment by spikedrba** [comment]
ah, very good point, I installed the latest blacklist from http://urlblacklist.com/ as linked in DG and that's 106MB... 4.5M domains... guess I'll need to look at its usefulness and do some trimming. Do you have recommendations on building a blacklist? how do you manage yours?

**Comment by fredbcode** [comment]
it depends of your needs
The best and more secure solution is the white list
A big white list and all others domains banned 
You allow only the domains needed and in the banned page the users can open a ticket

**Comment by spikedrba** [comment]
fair enough, I don't think whitelists are an option anymore except for rare cases because websites have become crazy complex. In any case, I guess we're talking about something else now and to my original report the answer seems to be now and without a large blacklist restarts are actually not that much of an issue. Also based on docs the -r[eload] works to reload filtering groups, but not the main config file, which is why it didn't work for me in the paste.
