### ISSUE TITLE
e2guardian systemd service does not support reload

### ISSUE THREAD

**Issue by spikedrba** [e2guardian/e2guardian#182]
Hi,

I'd like to use the reload functionality that e2g provides (like in dansguardian you can do e2guardian -r) which is specifically designed to reload lists definition. Even on my system where normally a restart takes 11 seconds, a reload takes 1 second, making it highly desirable for frequent list changes.

The command works just fine, but the systemd definition is lacking support for it. To add it a oneliner is needed:

ExecReload=/usr/sbin/e2guardian -r

I've attached a patch in case it helps. I've tested it on my system and it works fine. If you try it out remember to issue a systemd daemon-reload to get systemd to check and reload the new unit file.

[systemd-e2g-reload.txt](https://github.com/e2guardian/e2guardian/files/819031/systemd-e2g-reload.txt)

**Comment by fredbcode** [comment]
Ok thanks
