### ISSUE TITLE
Invalid Certificate

### ISSUE THREAD

**Issue by fcruzcoelho** [e2guardian/e2guardian#184]
Sirs, good afternoon.
I am facing a problem accessing a website below:
http://www2.sefaz.ce.gov.br/sitram-internet/masterDetailNotaFiscal.do?method=prepareSearch

After entering the key to make the query of the note fical with the key below.
42170284229889000173550020007937861008172282
After inserting the key for query it returns an invalid certificate error, even adding in the browser I can not give continuity in the process because it does not show the screen of capicha.

Follow Print:
![snapshot116](https://cloud.githubusercontent.com/assets/13903548/23715217/a70ed24e-040a-11e7-8536-7e076b6d434a.png)

This access is done without the e2guardin in front, with only the squid configured in the browser the same works normally.

My version of e2guardian is
E2guardian 3.4.0.3

Could you help me with this problem?

Thank you

**Comment by neradpeter** [comment]
Do you have enabled certificate validation in config ?


Dňa 8. marca 2017 18:25:38 používateľ fcruzcoelho 
<notifications@github.com> napísal:

**Comment by fcruzcoelho** [comment]
Good afternoon
What configuration would be in e2guardianfN.conf?
Ssl cert check = off
Ssl mitm = off
Mitmcheckcert = on

I've all changed to on / off and nothing.

Is there somewhere else to do this setup?

Thank you

**Comment by fcruzcoelho** [comment]
Good afternoon

I tried putting the site in nocheckcertsitelist but it does not work, could you help me.

Thank you

**Comment by fcruzcoelho** [comment]
Good afternoon
Could you tell me if someone has had this problem in E2G or if the version 3.5.0 is the same?
Thank you

**Comment by Kenny690** [comment]
Have you tried to put it in exceptionsitelist? If this will not work, you can try to make an exception in your proxy.

**Comment by fcruzcoelho** [comment]
Good Morning,
I made the configuration with the "exceptionsitelist" but still the same checks whether the connection is secure or not, validating the invalid certificate.

What configuration in my proxy can I have since the same is just as cache!

Is the configuration for verifying the e2guardin certificate not working? Or is it with a bug?

Thank you

**Comment by neradpeter** [comment]
I have the same problem... look at google group


Dňa 13. marca 2017 15:17:18 používateľ fcruzcoelho 
<notifications@github.com> napísal:

**Comment by fcruzcoelho** [comment]
Sorted out,

I added the gov.br domain to "exceptionsitelist" and "nocheckcertsitelist"

Apparently the problem disappeared


Thank you

**Comment by fcruzcoelho** [comment]
I'm closing the issue.

Thank you
