### ISSUE TITLE
Cant get work version 3.5.1

### ISSUE THREAD

**Issue by neradp** [e2guardian/e2guardian#189]
Hi i complile e2guardian from source..

every request to e2guardian gives me : segfault at 3554810 ip 00000000004768d3 sp 00007fff1c794790 error 4 in e2guardian[400000+bc000]

e2guardian not working

Im using fedora 17

im config with ./configure '--enable-clamd=yes' '--with-proxyuser=dansguardian' '--with-proxygroup=dansguardian' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--with-filedescriptors=8192' '--enable-sslmitm=yes'

config files same from 3.5.0 just copiing compiled executable file

version 3.5.0 is ok

**Comment by neradp** [comment]
/usr/local/sbin/e2guardian(_ZN16FOptionContainer9inURLListER6Stringjbbb+0x36e) [0x490cee]
/usr/local/sbin/e2guardian(_ZN16FOptionContainer16testBlanketBlockEjbb+0x1c3) [0x489713]

**Comment by fredbcode** [comment]
Sorry I don't known Fedora, can you try like this 

make distclean
./autogen.sh
./configure '--enable-clamd=yes' '--with-proxyuser=dansguardian' '--with-proxygroup=dansguardian' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--enable-pcre=yes' '--with-filedescriptors=1024' '--enable-sslmitm=yes'
make

**Comment by fredbcode** [comment]
Are you using "groupemode = 0" ?

**Comment by fredbcode** [comment]
Some news, FI V4.1 is out
