### ISSUE TITLE
[V4.0.1] e2guardian segfault at restart

### ISSUE THREAD

**Issue by fredbcode** [e2guardian/e2guardian#192]
Mar 15 11:52:48 proxytest systemd[1]: Started LSB: e2guardian configuration.
Mar 15 11:52:48 proxytest e2guardian[16090]: Started sucessfully.
Mar 15 11:52:53 proxytest e2guardian[16090]: 54485 No header recd from client - errno: 0
Mar 15 11:56:48 proxytest e2guardian[16090]: 54558 No header recd from client - errno: 0
Mar 15 11:56:48 proxytest e2guardian[16090]: 54561 No header recd from client - errno: 0
Mar 15 11:56:48 proxytest e2guardian[16090]: 54559 No header recd from client - errno: 0
Mar 15 12:40:48 proxytest e2guardian[16090]: 54956 No header recd from client - errno: 104
Mar 15 12:48:23 proxytest e2guardian[16090]: 55206 No header recd from client - errno: 0
Mar 15 13:02:48 proxytest systemd[1]: Stopping LSB: e2guardian configuration...
Mar 15 13:02:48 proxytest e2guardian[16090]: sigtimedwait() signal 15 recd:
Mar 15 13:02:48 proxytest e2guardian[16090]: stopping connections
Mar 15 13:02:48 proxytest kernel: [1992307.638106] e2guardian[16090]: segfault at 0 ip 00007fa473a935e4 sp 00007fffad2fa340 error 4 in libc-2.19.so[7fa473a2a000+1a1000]
Mar 15 13:02:48 proxytest e2guardian[16090]: connections stopped
Mar 15 13:02:48 proxytest e2guardian[16090]: sending null socket to http_workers to stop them
Mar 15 13:02:48 proxytest systemd[1]: e2guardian.service: main process exited, code=killed, status=11/SEGV
Mar 15 13:02:48 proxytest e2guardian[19418]: Stopping e2guardian: e2guardian.
Mar 15 13:02:48 proxytest systemd[1]: Unit e2guardian.service entered failed state.
Mar 15 13:02:48 proxytest systemd[1]: Starting LSB: e2guardian configuration...
Mar 15 13:02:49 proxytest e2guardian[19424]: Starting e2guardian: e2guardian.
Mar 15 13:02:49 proxytest systemd[1]: Failed to read PID from file /var/run/e2guardian.pid: Invalid argument
Mar 15 13:02:49 proxytest systemd[1]: Started LSB: e2guardian configuration.
Mar 15 13:02:49 proxytest e2guardian[19429]: Started sucessfully.
Mar 15 13:02:55 proxytest e2guardian[19429]: 55939 No header recd from client - errno: 0

**Comment by philipianpearce** [comment]
Please recompile with -g -O0 to turn off optimization.
Turn on core dumping.
Replicate fault .
Then examine core dump with gdb to get back trace.

I will also have another look at the close-down part of the code as it does not close tidily as yet.

**Comment by fredbcode** [comment]
Thanks, I will test asap, next week I guess.

Not related but FI it seems that my recent change about redirect code (30x) fix a problem with SSLMITM (look at #176)

Le 16 mars 2017 15:29:10 GMT+01:00, Philip Pearce <notifications@github.com> a écrit :
>Please recompile with -g -O0 to turn off optimization.
>Turn on core dumping.
>Replicate fault .
>Then examine core dump with gdb to get back trace.
>
>I will also have another look at the close-down part of the code as it
>does not close tidily as yet. 
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/192#issuecomment-287074664

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
ok now
