### ISSUE TITLE
[V4.0.1] bannedregexpurllist is broken

### ISSUE THREAD

**Issue by fredbcode** [e2guardian/e2guardian#193]
InBannedRegExpURLList always returns -1

**Comment by fredbcode** [comment]
bannedregexheader works well, this is the same part of code in Connectionhandler.cpp

inBannedRegExpURLList = KO
inBannedRegExpHeaderList = OK

>             if ((j = (*ldl->fg[filtergroup]).inBannedRegExpURLList(temp, lastcategory)) >= 0) {
>                 (*checkme).isItNaughty = true;
>                 (*checkme).whatIsNaughtyLog = o.language_list.getTranslation(503);
>                 (*checkme).message_no = 503;
>                 // Banned Regular Expression URL:
>                 (*checkme).whatIsNaughtyLog += (*ldl->fg[filtergroup]).banned_regexpurl_list_source[j].toCharArray();
>                 (*checkme).whatIsNaughty = o.language_list.getTranslation(504);
>                 // Banned Regular Expression URL found.
>                 (*checkme).whatIsNaughtyCategories = (*o.lm.l[(*ldl->fg[filtergroup]).banned_regexpurl_list_ref[j]]).category.toCharArray();
>                 return;
>             }
>             if ((j = ldl->fg[filtergroup]->inBannedRegExpHeaderList(header->header, lastcategory)) >= 0) {
>                 checkme->isItNaughty = true;
>                 checkme->whatIsNaughtyLog = o.language_list.getTranslation(508);
>                 checkme->message_no = 508;
>                 checkme->whatIsNaughtyLog += ldl->fg[filtergroup]->banned_regexpheader_list_source[j].toCharArray();
>                 checkme->whatIsNaughty = o.language_list.getTranslation(509);
>                 checkme->whatIsNaughtyCategories = o.lm.l[ldl->fg[filtergroup]->banned_regexpheader_list_ref[j]]->category.toCharArray();
>                 return;
>             }

**Comment by philipianpearce** [comment]
Have altered code for BannedRegExpURLLIst to match inBannedRegExpHeaderList.

However both worked OK for me before change.

**Comment by fredbcode** [comment]
Ok now
