### ISSUE TITLE
[V4.0.1] warning message (compilation)

### ISSUE THREAD

**Issue by fredbcode** [e2guardian/e2guardian#194]
Socket.cpp:37:2: warning: #warning "X509_V_FLAG_TRUSTED_FIRST not available, chain creation will be unreliable" [-Wcpp]
 #warning "X509_V_FLAG_TRUSTED_FIRST not available, chain creation will be unreliable"

**Comment by philipianpearce** [comment]
If you get this warning you need a more up-to-date openssl.

Warning amended to say this.
