### ISSUE TITLE
Hosts blocking HTTP / 1.0 requests

### ISSUE THREAD

**Issue by marsat** [e2guardian/e2guardian#196]
sorry but translate.google.fr this [issues](https://github.com/marsat/CTparental/issues/35)

Some hosting blocks HTTP / 1.0 requests, which results in a browser that molines for several minutes 
to finally respond:

> The connection has been reset
> 
>      The connection to the server was reset while the page was loaded.
> 
>      The site may be temporarily unavailable or overloaded. Try again later;
>      If you can not navigate to any site, check your computer's network connection;
>      If your computer or network is protected by a firewall or proxy, make sure
>      Firefox is allowed to access the Web.

To solve this problem I am only finding a one-way method that modifies the binary e2guardian so that it produces only HTTP / 1.1 stamping frames
Patcher as am
`sudo /bin/sed -i "s?HTTP/1.0?HTTP/1.1?g" /usr/sbin/e2guardian`
`sudo service e2guardian restart`
The handling is to redo in case of re-installation or update e2guardian.

A modification of e2guardian source code to use HTTP / 1.1 would be a good idea I think.
Thank you again for your support for this very useful project.

**Comment by fredbcode** [comment]
Vous avez un exemple concret ? E2guardian ne fait que transmettre les requêtes, cela m'étonne.
J'ai des dizaines de milliers d'utilisateur et je n'ai jamais eu de cas remonté.

Je ne suis pas convaincu que modifier les requêtes soit pertinent vous allez rencontrer d'autres types de bugs


----- marsat <notifications@github.com> a écrit :

**Comment by marsat** [comment]
oui touts les sites en air.defense.gouv.fr exemple: http://www.eetaa722.air.defense.gouv.fr

**Comment by fredbcode** [comment]
Ok merci, je vais tester demain sur ma plateforme je te tiens au courant



----- marsat <notifications@github.com> a écrit :

**Comment by fredbcode** [comment]
Fonctionne ici sans probléme avec 
E2guardian 3.5.1 et 4.0.2 + Squid 3.5.23

**Comment by marsat** [comment]
ok , effectivement je n'est pas la dernière version  , mais e2guardian 3.4.0.3-1 + privoxy 3.0.26-3 version des dépôts Debian sid.
j'attendrais donc avec impatience les future version dans les dépôts debian. 

bref le problème semble résolut dans les futures version. 
je clôture donc.

encore merci pour la réactivité et le temps passé.

**Comment by fredbcode** [comment]
Marsat il y a un paquet tout pret sinon pour Jessie 64bits
Pour sid en official tu risques d'attendre longtemps .. 
En tout cas dans la prochaine debian c'est la 3.4.0.3 de prévue

Toutefois avec la 3.4.0.3 je n'ai pas le bug non plus

**Comment by marsat** [comment]
je vais maître a jour ma Debian et voir sa, mais si sa fonctionne chez toi c'est que j'ai une couille sur mon OS ou ma conf  ou que c'est le couplage avec privoxy qui provoque cela ? au pire je tenterai une compilation pour debian sid . encore merci.
