### ISSUE TITLE
[V4.0.2] Could not write to logging process

### ISSUE THREAD

**Issue by fredbcode** [e2guardian/e2guardian#197]
This messages appears sometimes 

Mar 22 14:02:36 proxytest e2guardian[6847]: Could not write to logging process:
Mar 22 14:02:36 proxytest e2guardian[6847]: Could not write to logging process:

**Comment by philipianpearce** [comment]
Fix pushed to v4.0 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
Faster than light :)

**Comment by fredbcode** [comment]
Ok, I planned a test Monday on production, with complex rules, 6 groups, Auth Basic + Digest, and more or less 5000 maxchildren running  

Fred

----- Mail original -----
