### ISSUE TITLE
Can't install 4.0.2

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#198]
Something really strange is happening.
#uname -a
Linux Osiris 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux

I'm trying to install 4.0.2, but can't get it working.
If I install it from deb file (dpkg -i ...) i'm getting this:
```
root@Osiris:~# dpkg -i e2guardian_4.0.2_jessie_ubuntu16.04_amd64.deb
Выбор ранее не выбранного пакета e2guardian.
(Чтение базы данных … на данный момент установлено 89162 файла и каталога.)
Подготовка к распаковке e2guardian_4.0.2_jessie_ubuntu16.04_amd64.deb …
Распаковывается e2guardian (4.0.2) …
Настраивается пакет e2guardian (4.0.2) …
grep: /etc/e2guardian/e2guardian.conf: Нет такого файла или каталога
grep: /etc/e2guardian/e2guardian.conf: Нет такого файла или каталога
grep: /etc/e2guardian/e2guardian.conf: Нет такого файла или каталога

Job for e2guardian.service failed because the control process exited with error code.
See "systemctl status e2guardian.service" and "journalctl -xe" for details.
invoke-rc.d: initscript e2guardian, action "restart" failed.
● e2guardian.service - E2guardian Web filtering
   Loaded: loaded (/etc/systemd/system/e2guardian.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2017-04-01 09:44:25 +05; 5ms ago
  Process: 4613 ExecStart=/usr/sbin/e2guardian (code=exited, status=1/FAILURE)

апр 01 09:44:25 Osiris systemd[1]: Starting E2guardian Web filtering...
апр 01 09:44:25 Osiris e2guardian[4613]: Error opening /etc/e2guardian/e2guardian.conf
апр 01 09:44:25 Osiris systemd[1]: e2guardian.service: Control process exited, code=exited status=1
апр 01 09:44:25 Osiris systemd[1]: Failed to start E2guardian Web filtering.
апр 01 09:44:25 Osiris systemd[1]: e2guardian.service: Unit entered failed state.
апр 01 09:44:25 Osiris systemd[1]: e2guardian.service: Failed with result 'exit-code'.
WARNING: Starting e2guardian failed. Please check your configuration.
Synchronizing state of e2guardian.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable e2guardian
Job for e2guardian.service failed because the control process exited with error code.
See "systemctl status e2guardian.service" and "journalctl -xe" for details.
WARNING: Starting e2guardian failed. Please check your configuration.
Обрабатываются триггеры для systemd (232-19) …
```
And in /etc/e2guardian I don't have e2guardian.conf and e2guardianf1.conf. If I'll try to get them from my backup - he will be moan about fancy downloader conf file (that it doesn't exist). And etc...
But if I will fully replace /etc/e2guardian with my backup I will get the same result as if I will do a clean install from the source code:

```
root@Osiris:~/e2guardian-4.0# e2guardian
Error reading file : Нет такого файла или каталога
Error opening sslsiteregexplist
Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
Error in reading filter group files
Error reading filter group conf file(s).
Error parsing the e2guardian.conf file or other e2guardian configuration files
```

But the thing is... 

```
root@Osiris:~/e2guardian-4.0# grep -r "sslsiteregexplist" /etc/e2guardian/
root@Osiris:~/e2guardian-4.0#
```

There's no mention in config files about sslsiteregexplist and there IS sslsiteregexplist file in /etc/e2guardian/lists. And I don't know what files he's trying to read.

I have tried v.4.0, v4develop and a deb file from v4.0beta2.

**Comment by Kenny690** [comment]
Oh... my... gosh... I found the solution. I NEED to write down in e2guardianf1.conf this:

`sslsiteregexplist = '/etc/e2guardian/lists/sslsiteregexplist'`

Anyway, why did you remove that from configs if e2guardian need that?

**Comment by fredbcode** [comment]
Which debian, I will confirm Monday but as far as I know the package 
worked well

||
>
> There's no mention in config files about sslsiteregexplist and there 
> IS sslsiteregexplist file in /etc/e2guardian/lists. And I don't what 
> files he's trying to read.
>

Yes this file is needed, I will check if I forgot something in package

**Comment by Kenny690** [comment]
I have Debian Stretch. Thank you.

**Comment by fredbcode** [comment]
Oh, not yet tested with stretch

Le 1 avril 2017 12:08:39 GMT+02:00, Kenny690 <notifications@github.com> a écrit :
>I have Debian Stretch. Thank you. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/198#issuecomment-290910647

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Kenny690** [comment]
So I'll be first? :D
I had only one sigsegv after ~an hour of installation. Already 4 hours passed - no errors.

**Comment by fredbcode** [comment]
I pushed a new package, please make a try 
Thanks

**Comment by fredbcode** [comment]
It works well ?

**Comment by Kenny690** [comment]
It installed well. No errors

**Comment by Kenny690** [comment]
There's no sslsiteregexplist definition in e2guardiand1.conf.

**Comment by fredbcode** [comment]
Yes sorry fixed now

**Comment by Kenny690** [comment]
Seems like everything's work now.

**Comment by fredbcode** [comment]
ok great

**Comment by fredbcode** [comment]
Duplicate with #199
