### ISSUE TITLE
segfault on 3.5.1 running on Centos 7.3

### ISSUE THREAD

**Issue by RaNd250** [e2guardian/e2guardian#201]
After I issue e2guardian -g i receive 
` kernel: e2guardian[8063]: segfault at 34b2198 ip 00007effb7effc56 sp 00007fff698b9a88 error 4 in libc-2.17.so[7effb7db5000+1b6000]
` every 10-20" but the process is still running and serving.
If i restart the process with -Q no issus at all.
Running without SSL/MIMT.

`e2guardian 3.5.1

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--with-filedescriptors=16384 --enable-dnsauth=yes' '--enable-static-zlib=yes' '--enable-orig-ip=yes'
`

Any ideas ?

**Comment by fredbcode** [comment]
Are you using "groupmode=" in your config file ?

**Comment by RaNd250** [comment]
No, i didn't find this option, so i assumed it is not used, as I used to work with  dansguardian defore.

**Comment by fredbcode** [comment]
Can you make a try with v4.0 (from github branch not zip) ?
This version is almost done and contains many bugfixes

**Comment by RaNd250** [comment]
Which branch ? 4 or 4 develop ?

**Comment by fredbcode** [comment]
v4.0 yes --with-filedescriptors is useless now

**Comment by RaNd250** [comment]
Thanks!
No errors anymore!

Still waiting feedback from users to see how it perfoms, since dansguardian needed 4 nodes to get
the perfomance we needed.

**Comment by fredbcode** [comment]
v4.1 is out now

**Comment by RaNd250** [comment]
4.0 crashes often with segfault on Centos 7.
Installing 4.1.2 to see if the issues are resolved.
