### ISSUE TITLE
openSUSE 42.2 compatibility

### ISSUE THREAD

**Issue by jpeter01** [e2guardian/e2guardian#205]
Could you please add compatibility for openSUSE 42.2 in v4.x ?

I compiled v3.5.1, and it missed some shared objects, I created sym-links for them:

ln -s /usr/lib64/libcrypto.so.37.0.0 /usr/lib64/libcrypto.so.10
ln -s /usr/lib64/libssl.so.38.0.0 /usr/lib64/libssl.so.10
ln -s /usr/lib64/libpcreposix.so.0 /usr/lib64/libpcreposix.so.3
ln -s /usr/lib64/libpcre.so.1 /usr/lib64/libpcre.so.3

After it v3.5.1 was running, and doing the redirecting well. I compiled v4.1, and it gives the following error message at start up:
e2guardian: /lib64/libcrypto.so.1.0.0: no version information available (required by e2guardian)
e2guardian: /lib64/libssl.so.1.0.0: no version information available (required by e2guardian)
e2guardian: symbol lookup error: e2guardian: undefined symbol: pcreposix_regcomp

The installed packages with the shared objects are the following:

linux:~ # rpm -qf /usr/lib64/libcrypto.so.37.0.0 
libcrypto37-2.3.4-3.1.x86_64
linux:~ # rpm -qf /usr/lib64/libssl.so.38.0.0 
libssl38-2.3.4-3.1.x86_64
linux:~ # rpm -qf /usr/lib64/libpcreposix.so.0
libpcreposix0-8.39-6.1.x86_64
linux:~ # rpm -qf /usr/lib64/libpcre.so.1
libpcre1-8.39-6.1.x86_64

**Comment by fredbcode** [comment]
Very weird, I guess you are not compile on openSUSE 42.2, why ?

**Comment by jpeter01** [comment]
I compiled it on openSUSE 42.2. Do you need the output of configure, or make?

**Comment by fredbcode** [comment]
I don't known SUSE
But this 
ln -s /usr/lib64/libcrypto.so.37.0.0 /usr/lib64/libcrypto.so.10
ln -s /usr/lib64/libssl.so.38.0.0 /usr/lib64/libssl.so.10
ln -s /usr/lib64/libpcreposix.so.0 /usr/lib64/libpcreposix.so.3
ln -s /usr/lib64/libpcre.so.1 /usr/lib64/libpcre.so.3

It's really strange, that mean the libraries found in compilation are not the same where/when e2 runs

**Comment by jpeter01** [comment]
Yes they aren't. And in the repositories aren't any packages, which are providing the same versions of libraries, that's why I used sym-linking.

**Comment by fredbcode** [comment]
But there is something strange how e2 can find the libraries in compilation ?
Are you using exactly the same machine ?

**Comment by jpeter01** [comment]
Yes, I am using the same machine. And at compilation e2 gave no errors.

**Comment by jpeter01** [comment]
Sorry I was misleading you. I tried more versions on the machine, and that one was from the Debian package. I used it because the compiled version did not find the config files.

Thank you for your help!
