### ISSUE TITLE
v4.0: Failure of large body download when Content-Length header missing

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#206]
A few sites such as yandex.ru appear to be sending a large body without sending Content-Length header.   Since I posted this have discovered that they are sending Content-Length header, but are delaying the send, resulting in a header time-out.   

This worked OK in v3 but in v4.0 is hanging, so that browser gets a header (with gzip header) but no body.    Browser gives ERR_CONTENT_DECODING_FAILED as it cannot decode empty body.

Giving a longer header time-out appears to fix this issue.

Seen in issue #200

**Comment by philipianpearce** [comment]
Bug title is wrong - sites are sending Content-Length, but are delaying send.

**Comment by fredbcode** [comment]
You mean proxyechange value ? I'm using 60 seconds 
So if I understand this website sends a partial header, "wait" a moment, and finally push the end ?
Very weird

**Comment by philipianpearce** [comment]
In v4 I had a 100ms timeout for header lines after the first as expected them all at same time.
Now changed to use proxyexchangetimeout as per v3.

There is still an issue with this site with image search thumbnails (well that is part of the problem, thumbnails are very big!!) not displaying.  I am looking at that now as a separate bug.
