### ISSUE TITLE
v4.0  - Large thumbnails fail to completely download on some sites (yandex.ru)

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#207]
Discovered when fixing bug #206.

Only seems to affect large images when in MITM mode.   May also affect http sites, but sites with issue all seem to be https.

Issue not seen in Google or Bing which use proper thumbnails.

**Comment by fredbcode** [comment]
In this case it's more pcontimeout or trickledelay ?

**Comment by fredbcode** [comment]
There is some hardcoded value in DayaBuffer.cpp  and few other

**Comment by philipianpearce** [comment]
Problem seems to be in FDtunnel - it is sometimes not returning - I'm looking at that now. 

This bug is really odd - does not seem to affect other search sites. 

DataBuffer is working OK now - I was looking at it in some detail as part of bug #206 

Regards 

Philip 

----- Original Message -----
