### ISSUE TITLE
E2guardian doesn't start after reboot

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#208]
Found some news. I have read the syslog after reboot. That's what I have:
```
# cat /etc/syslog | grep e2guardian
Apr 14 10:14:49 osiris e2guardian[16184]: sigtimedwait() signal 15 recd:
Apr 14 10:14:49 osiris e2guardian[16184]: Stopping
Apr 14 10:14:49 osiris e2guardian[16184]: sending null socket to http_workers to stop them
Apr 14 10:15:50 osiris systemd[1]: [/usr/share/e2guardian/scripts/e2guardian.service:4] Unknown lvalue 'TimeoutStartSec' in section 'Unit'
Apr 14 10:15:50 osiris systemd[1]: [/usr/share/e2guardian/scripts/e2guardian.service:4] Unknown lvalue 'TimeoutStartSec' in section 'Unit'
Apr 14 10:16:00 osiris e2guardian[599]: httpworkers option in e2guardian.conf has a value too high.
Apr 14 10:16:00 osiris ifup[437]:  httpworkers option in e2guardian.conf has a value too high for current file id limit (1024)
Apr 14 10:16:00 osiris systemd[1]: [/usr/share/e2guardian/scripts/e2guardian.service:4] Unknown lvalue 'TimeoutStartSec' in section 'Unit'
Apr 14 10:16:06 osiris kernel: [   26.138809] cgroup: fork rejected by pids controller in /system.slice/e2guardian.service
```

I have default e2guardian.service from the yesterday's last pull of v4.0.

**Comment by Kenny690** [comment]
The strange thing is that e2guardian thinks that I have filedescriptors limit at 1024, but:

```
root@Osiris:~# cat /proc/sys/fs/file-max
806512
root@Osiris:~# ulimit -Hn
16384
root@Osiris:~# ulimit -Sn
16384
```

Or it's not what I think about?

**Comment by fredbcode** [comment]
There are some confusions here
e2guardian.service is not a script but a config file

[/usr/share/e2guardian/scripts/e2guardian.service:4] Unknown lvalue 'TimeoutStartSec' in section 'Unit'

Why do you have a service file here ? What process launch it like a script ?

"option in e2guardian.conf has a value too high for current file id limit (1024)"

Means that your e2.guardian.service is not applied correctly, because LimitNOFILE=65535 push this limit

/etc/systemd/system/e2guardian.service
[Unit]
Description=E2guardian Web filtering
After=network.target

[Service]
LimitNOFILE=65535
Type=forking
IgnoreSIGPIPE=no
GuessMainPID=no
ExecStart=/usr/sbin/e2guardian
ExecReload=/usr/sbin/e2guardian -r

**Comment by Kenny690** [comment]
If you remember, I tried this config. I'm starting to thing that the problem is 
"httpworkers option in e2guardian.conf has a value too high."
Only after I get it to 800 from 5000 it started without any problems. But what is confusing:
(on httpworkers=5000, new script) I'm rebooting the system, e2guardian doesn't start on startup, but when I'm launching it manually - there's no errors and it starts fine.
(on httpworkers=800, old script) It's starts on reboot and it can use service e2guardian start|stop|restart. 
I'll try to test it better.

**Comment by fredbcode** [comment]
Yes but at first you must find what is "/usr/share/e2guardian/scripts/e2guardian.service" which process launch this ? Why this path ?

**Comment by Kenny690** [comment]
Oh, sorry, didn't explain. 
It's:
ln -s /usr/share/e2guardian/scripts/e2guardian.service /etc/systemd/system/e2guardian.service

I used this:

https://raw.githubusercontent.com/e2guardian/e2guardian/master/INSTALL

ADDITIONAL SCRIPTS section.

**Comment by fredbcode** [comment]
Yes Kenny it's what I mean :)
It's no a script at all, it's a config file 


systemd is very different to systemv-init

**Comment by fredbcode** [comment]
Kenny save your configuration and remove completely e2guardian (apt-get remove e2guardian --purge)
Download my package and try

**Comment by Kenny690** [comment]
Got error on installation.
Failed to restart e2guardian.service: Unit e2guardian.service not found.
invoke-rc.d: initscript e2guardian, action "restart" failed.
Unit e2guardian.service could not be found.
WARNING: Starting e2guardian failed. Please check your configuration.
Synchronizing state of e2guardian.service with SysV service script with /lib/sys                                                                                                                                                             temd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable e2guardian
Failed to enable unit: File e2guardian.service: No such file or directory
dpkg: ошибка при обработке пакета e2guardian (--install):
 подпроцесс установлен сценарий post-installation возвратил код ошибки 1

**Comment by fredbcode** [comment]
I don't understand I'm trying right now with Strech and it works well

**Comment by fredbcode** [comment]
Can you copy and paste, step by step ? remove, install, etc

**Comment by Kenny690** [comment]
OMG, I still had a symbolic link in /etc/systemd/system/. After I removed that - everything installs.
Still has the problem with reboot.
syslog:

Apr 14 12:51:27 osiris systemd[1]: Reloading.
Apr 14 12:51:27 osiris systemd[1]: [/etc/systemd/system/e2guardian.service:4] Unknown lvalue 'TimeoutStartSec' in section 'Unit'
Apr 14 12:51:27 osiris systemd[1]: apt-daily.timer: Adding 9h 54min 5.273909s random time.
Apr 14 12:51:27 osiris systemd[1]: Reloading.
Apr 14 12:51:27 osiris systemd[1]: [/etc/systemd/system/e2guardian.service:4] Unknown lvalue 'TimeoutStartSec' in section 'Unit'
```
Apr 14 12:51:27 osiris systemd[1]: apt-daily.timer: Adding 7h 20min 38.657263s random time.
Apr 14 12:51:43 osiris systemd[1]: Started E2guardian Web filtering.
Apr 14 12:51:43 osiris systemd[1]: Reached target Multi-User System.
Apr 14 12:51:43 osiris systemd[1]: Reached target Graphical Interface.
Apr 14 12:51:43 osiris systemd[1]: Starting Update UTMP about System Runlevel Changes...
Apr 14 12:51:43 osiris systemd[1]: Started Update UTMP about System Runlevel Changes.
Apr 14 12:51:43 osiris systemd[1]: Startup finished in 3.538s (kernel) + 23.587s (userspace) = 27.126s.
Apr 14 12:51:44 osiris kernel: [   27.209881] cgroup: fork rejected by pids controller in /system.slice/e2guardian.service
```

**Comment by fredbcode** [comment]
Can you post /etc/systemd/system/e2guardian.service ?

**Comment by Kenny690** [comment]
```
[Unit]
Description=E2guardian Web filtering
After=network.target
TimeoutStartSec=20s

[Service]
LimitNOFILE=65535
Type=forking
IgnoreSIGPIPE=no
GuessMainPID=no
ExecStart=/usr/sbin/e2guardian
ExecReload=/usr/sbin/e2guardian -r

[Install]
WantedBy=multi-user.target
```

**Comment by fredbcode** [comment]
Hum related to the documentation 

Try to move TimeoutStartSec=20s to Service

**Comment by fredbcode** [comment]
It works ? I mean systemd issue ?

**Comment by Kenny690** [comment]
Seems like there is no problem with systemd, but with e2guardian itself or with my system. 
It works when I'm setting httpworkers = 800, but when I set it to 5000 I'm getting this:
`Apr 14 16:27:30 osiris kernel: [ 7483.764591] cgroup: fork rejected by pids controller in /system.slice/e2guardian.service`

**Comment by fredbcode** [comment]
No message like : [/etc/systemd/system/e2guardian.service:4] Unknown lvalue 'TimeoutStartSec' in section 'Unit'

**Comment by fredbcode** [comment]
It's just a warning cgroup: fork rejected by pids controller in /system.slice/e2guardian.service

**Comment by Kenny690** [comment]
Yes, this message has disappear after I moved it from unit to service section.

**Comment by fredbcode** [comment]
Ok so I close this ticket, thanks for your help
