### ISSUE TITLE
e2guardian - updated blacklists from URLBlacklist.com doesnt start

### ISSUE THREAD

**Issue by 1nfrag** [e2guardian/e2guardian#209]
In the past with Dansguardian I used to update our blacklists from URLblacklist.com
I've since moved to e2guardian and been very happy with the progress being made. Thanks guys!

I updated to version 4.02 recently and I've been trying to get it to start using the bigblacklist from URLblacklist. However it doesnt start. It seems to time out. I dont know where to look for any errors but I'm happy to do so if you can point me in the right direction. As soon as I switch back to the default blacklists the service will start fine.

I'm running Debian if that helps. :)

**Comment by Kenny690** [comment]
Can you share with us your e2guardian.conf and e2guardianf1.conf?

**Comment by fredbcode** [comment]
Maybe you have not enough CPU power ? Can you make a "top" when you start e2guardian

**Comment by fredbcode** [comment]
FYI 4.1 is out now ! You can download a debian package if needed: https://github.com/e2guardian/e2guardian/releases

**Comment by 1nfrag** [comment]
Using top it basically maxes out 1 cpu core I believe so I'm guessing its not multi-threaded. Its running on a decent server in a virtual machine so I cant see why the CPU would be too slow.

**Comment by 1nfrag** [comment]
e2guardian.conf: https://pastebin.com/0xbuGSG6
e2guardianf1.conf: https://pastebin.com/EqzM1Vyi

**Comment by fredbcode** [comment]
Yes it is type H to see the threads 
Do you have something in syslog

**Comment by Kenny690** [comment]
Is that OK, that he doesn't has maxcontentfilecachescansize?

**Comment by 1nfrag** [comment]
top - 16:33:13 up  5:34,  2 users,  load average: 0.15, 0.19, 0.17
Threads: 115 total,   2 running, 113 sleeping,   0 stopped,   0 zombie
%Cpu(s): 24.9 us,  0.1 sy,  0.0 ni, 75.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   4003064 total,  1598852 used,  2404212 free,    30768 buffers
KiB Swap:  4191228 total,        0 used,  4191228 free.  1301936 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
32703 root      20   0  170444 117936   5320 R 99.9  2.9   0:09.95 e2guardian
   23 root      20   0       0      0      0 S  1.3  0.0   1:24.88 ksoftirqd/3
    3 root      20   0       0      0      0 S  0.7  0.0   2:04.49 ksoftirqd/0
   13 root      20   0       0      0      0 S  0.7  0.0   2:15.94 ksoftirqd/1
22631 root      20   0       0      0      0 S  0.7  0.0   0:00.30 kworker/3:1
    7 root      20   0       0      0      0 S  0.3  0.0   2:00.32 rcu_sched
11173 root      20   0   32680  11944   2436 R  0.3  0.3   0:15.99 top

**Comment by 1nfrag** [comment]
I cant find anything relevant in the logs other than   e2guardian starting and failing to start
It seems more that it times out in the starting effort than that an error occurs.

Perhaps you feel like downloading the list and trying on your machine? :)

**Comment by 1nfrag** [comment]
Does nobody else update their blacklists?

**Comment by 1nfrag** [comment]
e2guardian.service start operation timed out. Terminating.

**Comment by fredbcode** [comment]
Can try this 
Change /etc/systemd/system/e2guardian.service with 

[Unit]
Description=E2guardian Web filtering
After=network.target

[Service]
TimeoutStartSec=20s
LimitNOFILE=65535
Type=forking
IgnoreSIGPIPE=no
GuessMainPID=no
ExecStart=/usr/sbin/e2guardian
ExecReload=/usr/sbin/e2guardian -r

[Install]
WantedBy=multi-user.target

After type systemctl daemon-reload
and
service e2guardian restart

**Comment by 1nfrag** [comment]
OK tried that but no change that I can see

**Comment by 1nfrag** [comment]
I've tried just using the domains file for the adult category from the new lists... that started.
Then I tried just the urls file from the adult category from the new lists... it wont start. It times out.

**Comment by fredbcode** [comment]
Try to upgrade TimeoutStartSec=20s (don't forget systemctl daemon-reload)

**Comment by fredbcode** [comment]
Maybe TimeoutStartSec=60s

How many domains and urls ?

**Comment by 1nfrag** [comment]
There must be heaps in the adult/urls list...pages upon pages.
I've updated the service to wait 60s now and it works as long as I dont use adult/urls from the new blacklist file.
It might be the file is to big or something is wrong with it. 
For now I just wont use that file and modify my update script to exclude it.
Thanks very much for your time and help!

**Comment by fredbcode** [comment]
Ok I will close for now, feel free to reopen if needed

**Comment by surjitiit** [comment]
Thanks very much for your time and help!
