### ISSUE TITLE
[ V.3.5.1] unable to compile latest bug fix provided in issue 195.

### ISSUE THREAD

**Issue by winewood** [e2guardian/e2guardian#214]
https://github.com/e2guardian/e2guardian/issues/195

In this fix, the solution was enabled for 4, 4.1 etc.    The solution is not working for 3.5.1  (the only version that currently works on my platform)   When testing the fix provided in download link, I am unable to compile using any version of openssl.

The error from the make is as follows:

g++ -DHAVE_CONFIG_H -I. -I..
 -D__CONFFILE='"/etc/e2guardian/e2guardian.conf"'
-D__LOGLOCATION='"/var/log/e2guardian/"' -D__PIDDIR='"/var/run"'
-D__PROXYUSER='"e2guardian"' -D__PROXYGROUP='"e2guardian"'
-D__CONFDIR='"/etc/e2guardian"'  -D_FORTIFY_SOURCE=2   -g -O2
-fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
-DFD_SETSIZE=65535 -MT e2guardian-CertificateAuthority.o -MD -MP -MF
.deps/e2guardian-CertificateAuthority.Tpo -c -o
e2guardian-CertificateAuthority.o `test -f 'CertificateAuthority.cpp' ||
echo './'`CertificateAuthority.cpp
CertificateAuthority.cpp: In member function 'bool
CertificateAuthority::getSerial(const char*, ca_serial*)':
CertificateAuthority.cpp:127:16: error: aggregate 'EVP_MD_CTX mdctx' has
incomplete type and cannot be defined
     EVP_MD_CTX mdctx;
                ^
CertificateAuthority.cpp:146:30: error: 'EVP_MD_CTX_cleanup' was not
declared in this scope
     EVP_MD_CTX_cleanup(&mdctx);
                              ^
CertificateAuthority.cpp: In member function 'EVP_PKEY*
CertificateAuthority::getServerPkey()':
CertificateAuthority.cpp:461:29: error: invalid use of incomplete type
'EVP_PKEY {aka struct evp_pkey_st}'
     CRYPTO_add(&_certPrivKey->references, 1, CRYPTO_LOCK_EVP_PKEY);
                             ^
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/pem.h:14,
                 from CertificateAuthority.cpp:21:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of
'EVP_PKEY {aka struct evp_pkey_st}'
 typedef struct evp_pkey_st EVP_PKEY;
                ^
CertificateAuthority.cpp:461:46: error: 'CRYPTO_LOCK_EVP_PKEY' was not
declared in this scope
     CRYPTO_add(&_certPrivKey->references, 1, CRYPTO_LOCK_EVP_PKEY);
                                              ^
CertificateAuthority.cpp:461:66: error: 'CRYPTO_add' was not declared in
this scope
     CRYPTO_add(&_certPrivKey->references, 1, CRYPTO_LOCK_EVP_PKEY);
                                                                  ^
Makefile:1121: recipe for target 'e2guardian-CertificateAuthority.o' failed
make[2]: *** [e2guardian-CertificateAuthority.o] Error 1
make[2]: Leaving directory '/usr/local/share/e2guardian_stable/src'
Makefile:393: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/share/e2guardian_stable'
Makefile:334: recipe for target 'all' failed
make: *** [all] Error 2

I have used 3 different versions of openssl in an attempt to make around it, but the error appears to be in the code.  Can this please be investigated?

**Comment by Kenny690** [comment]
Did you install libssl1.0-dev?

17 апр. 2017 г. 8:17 пользователь "Wade Young" <notifications@github.com>
написал:

**Comment by winewood** [comment]
You are correct Kenny690.   I had to re-install many packages after changing one earlier.  The package change after re-installing another version of opensll must have changed my pre-requisites for the build.  Thank you!
