### ISSUE TITLE
Latest version of Chrome browser rejects generated certificate

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#216]
This is due to Google implementing a non-standards based policy in Chrome.

Adjustment to certificate generation made in latest v4.1 branch which adds fields required by Chrome.     Note:  You must clear your generated certificates cache on systems for the new policy to have an effect.  Do this safely with script such as:-

if cd path_to_generated_cert_directory
then
   rm  -fr *
fi

**Comment by philipianpearce** [comment]
Fix ported to v3.5 branch.
 Note: You must clear your generated certificates cache on systems for the new policy to have an effect. Do this safely with script such as:-

if cd path_to_generated_cert_directory
then
rm -fr *
fi

**Comment by sunweaver** [comment]
Hi!

For Debian stretch, which will be released with e2guardian 3.4.0.3, it would be good to have a fix for this issue backported to the 3.4 branch.

Is that possible from the upstream devs? It would be highly appreciated. With a upstream sanctioned patch, I could update e2guardian in Debian stretch and make people happy when using Google Chrome and Chromium against an e2guardian on a stretch server.

Hope someone raises his/her finger for this...

Mike

**Comment by fredbcode** [comment]
Ok, I will, I hope next week

**Comment by sunweaver** [comment]
Hi Fred,

On  Di 23 Mai 2017 08:41:57 CEST, Fredb wrote:

> Ok, I will, I hope next week

Awesome! Thanks!

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fredbcode** [comment]
at least if that is possible ...

**Comment by philipianpearce** [comment]
I think I have already fixed this in v3.5 branch - just needs testing and if OK releasing. 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
Yes Philip, but 3.4.0.3 has been selected to be in Debian stretch (so also in Ubuntu)

**Comment by fredbcode** [comment]
Ok pushed, thanks Philip
