### ISSUE TITLE
localbannedsitelist cannot override exceptionsitelist when https request (3.5.1)

### ISSUE THREAD

**Issue by VasiliyF** [e2guardian/e2guardian#218]
I have some sites in exceptionsitelist and *ip *ips blanket exceptions. When I add some site (http) from exceptionsitelist to localbannedsitelist, site is blocking. But if this site is https - no blocking.
*ip *ips blanket block in localbannedsitelist  works the same way.
SSLMITM is on.

**Comment by philipianpearce** [comment]
Fixed in v4.1 branch
