### ISSUE TITLE
Ad blocking fails on some sites expecting javascript responses - causing slow response

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#219]

**Comment by fredbcode** [comment]
Related with #94 ?

**Comment by philipianpearce** [comment]
Not related to #94. This needs a re-think of how blocks are delivered to browser and the order of processing so quite a major change (not for v4.1!). 
----- Original Message -----

**Comment by fredbcode** [comment]
Did you made a test with a correctly formatted (but empty) js in return ?
There is something like that for flash

**Comment by fredbcode** [comment]
How the browser knows that an object is a JS, it's not by mime types ?

Le 2 mai 2017 18:05:49 GMT+02:00, Philip Pearce <notifications@github.com> a écrit :
>Not related to #94. This needs a re-think of how blocks are delivered
>to browser and the order of processing so quite a major change (not for
>v4.1!). 
>----- Original Message -----
>
>> From: "Fredb" <notifications@github.com>
>> To: "e2guardian/e2guardian" <e2guardian@noreply.github.com>
>> Cc: "Philip Pearce" <philip.pearce@e2bn.org>, "Author"
>> <author@noreply.github.com>
>> Sent: Tuesday, 2 May, 2017 4:00:15 PM
>> Subject: Re: [e2guardian/e2guardian] Ad blocking fails on some sites
>> expecting javascript responses - causing slow response (#219)
>
>> Related with #94 ?
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub , or mute the thread
>> .
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/219#issuecomment-298681029

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
Fixed ?
