### ISSUE TITLE
[4.1/SSLMITM] Unexpected 407 requests

### ISSUE THREAD

**Issue by fredbcode** [e2guardian/e2guardian#220]
With mail.ru I can see a lot of 407 requests from squid, it's like e2guardian try to convert some HTTPS requests to HTTP

Basic identification:

Squid:
10.x.x.x - - [03/May/2017:09:41:09 +0200] "GET http://rs.mail.ru/d1698795.gif?&rnd=4919224&test_id=214 HTTP/1.0" 407 489 936 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
10.x.x.x - - [03/May/2017:09:41:09 +0200] "GET http://rs.mail.ru/d729402.gif?&rnd=364614286&test_id=214 HTTP/1.0" 407 489 937 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
10.x.x.x - - [03/May/2017:09:41:09 +0200] "GET http://rs.mail.ru/d1169362.gif?&rnd=819626730&test_id=214 HTTP/1.0" 407 489 938 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
10.x.x.x - - [03/May/2017:09:41:09 +0200] "GET http://rs.mail.ru/d1265489.gif?&rnd=876723593&test_id=214 HTTP/1.0" 407 489 938 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
10.x.x.x - - [03/May/2017:09:41:09 +0200] "GET http://rs.mail.ru/d12403154.gif?&rnd=625342457&test_id=214 HTTP/1.0" 407 489 939 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
10.x.x.x - - [03/May/2017:09:41:10 +0200] "GET http://rs.mail.ru/d21895644.gif?&rnd=822480369&test_id=214 HTTP/1.0" 407 489 939 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
10.x.x.x - - [03/May/2017:09:41:10 +0200] "GET http://rs.mail.ru/d523187.gif?&rnd=29294148&test_id=214 HTTP/1.0" 407 489 936 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
 
As you can see squid block because there is no user/password and worst this website should be in HTTPS 

I think I also saw some unexpected 407 in e2guardian not relayed to squid (I'm not sure I will confirm)

Certainly related with #213 (at least for slowdown)

**Comment by philipianpearce** [comment]
@fredb 

Are you seeing any syslog errors at the same time, and any ssl errors? 


Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
No nothing

**Comment by fredbcode** [comment]
10.x.x.x - - [03/May/2017:11:33:37 +0200] "POST http://www.google-analytics.com/collect HTTP/1.0" 407 489 1232 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
10.x.x.x.x - - [03/May/2017:12:01:02 +0200] "GET http://www.google-analytics.com/r/collect?v=1&_v=j53&a=458224078&t=pageview&_s=1&dl=http%3A%2F%2Fwww.universfreebox.com%2F&ul=fr&de=windows-1252&dt=Univers%20Freebox%20%3A%20Toute%20l%27actualit%C3%A9%20de%20Free%20et%20sa%20Freebox%2C%20Free%20Mobile%2C%20Freebox%20TV%2C%20FTTH%2C%20des%20t%C3%A9l%C3%A9coms%20et%20bien%20plus%20encore...&sd=24-bit&sr=1344x840&vp=1327x684&je=0&fl=25.0%20r0&_u=IAEAAEABI~&jid=205694565&gjid=1787568188&cid=742164939.1393327778&tid=UA-89680-1&_gid=571936861.1493805878&_r=1&z=904724660 HTTP/1.0" 407 489 1043 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"

I also have this with another websites, it's like e2guardian/browser try to make the decipher request directly

**Comment by fredbcode** [comment]
>  try to make the decipher request directly 
Perfect trace here:

E2guardian:
2017.5.3 **12:40:46** fbourgeois 10.x.x.x **https**://www.ecranlarge.com/films/critique/986324-tunnel-critique-enterree - GET 0 0 - 1 407 - - negociate_identification - - - - -
2017.5.3 **12:40:48** fbourgeois 10.x.x.x **https**://www.ecranlarge.com/films/critique/986324-tunnel-critique-enterree - GET 0 0 - 1 407 - - negociate_identification - - - - -

E2guardian:
10.x.x.x - - [03/May/2017:**12:40:46** +0200] "GET **http:**//www.ecranlarge.com/films/critique/986324-tunnel-critique-enterree HTTP/1.0" 407 489 1114 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"
10.x.x.x - - [03/May/2017:**12:40:48** +0200] "GET **http:**//www.ecranlarge.com/films/critique/986324-tunnel-critique-enterree HTTP/1.0" 407 489 1114 TCP_DENIED:HIER_NONE "Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0"

Of the requests before are OK user value + HTTPS

**Comment by philipianpearce** [comment]
Something really wrong here:- 

With a logged https full url you are in MITM tunnel. The auth should be all done in html (at the CONNECT) stage. You should never have a 407 inside a mitm tunnel. I'll have a look. 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
And more weird why my request become HTTP in squid

**Comment by fredbcode** [comment]
It's why I said, it's like e2guardian decipher and does unexpected requests and the result is a normal 407

**Comment by philipianpearce** [comment]
I understand what you are seeing - but I cannot replicate (the http requests to squid) on my systems without pass-through auth on. 

You have amended the code so that when 407 returned is now exception. Exceptions do not go mitm. Could you do a debug trace? Just on a failing url? 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
Fixes now + 407 requests logged without group on e2
