### ISSUE TITLE
[v4.1] clamav/commandlinescan are broken 

### ISSUE THREAD

**Issue by fredbcode** [e2guardian/e2guardian#224]

**Comment by fredbcode** [comment]
Fix tested with SSLMITM and this test page http://securite-informatique.info/virus/eicar/

exceptionvirusurllist = '/etc/e2guardian/lists/contentscanners/exceptionvirusurllist'
progname = '/usr/bin/clamdscan'
cleancodes = 0
virusregexp = : ([ -/a-zA-Z0-9.]+) FOUND
submatch = 1
defaultresult = infected

**Comment by Anthony-76** [comment]
I will try this day and come back to give you a feedback

**Comment by Anthony-76** [comment]
The problem of segfault with clamav scanner still  present.

It's seem appear (with my tests) when I navigate on lot of webpages https and then I go to https://secure.eicar.org/eicar_com.zip .

**Comment by fredbcode** [comment]
I only worked on commandlinescan, it works here with config above

**Comment by Anthony-76** [comment]
If I use your config file for commandlinescan.conf I have the following error:

Error reading file : Aucun fichier ou dossier de ce type
Error opening exceptionvirusmimetypelist
Content scanner plugin init returned error value: -1
Error loading CS plugins
Error parsing the e2guardian.conf file or other e2guardian configuration files

To avoid this error, the following files are empty

'/etc/e2guardian/lists/contentscanners/exceptionvirusmimetypelist'
'/etc/e2guardian/lists/contentscanners/exceptionvirusextensionlist'
'/etc/e2guardian/lists/contentscanners/exceptionvirussitelist'

Then I make new tests and the segfault appear again

**Comment by fredbcode** [comment]
Sorry I'm unable to reproduce 
clamdscan works manually ? The process can be execute par e2guardian user ? 
The files above are with the good rights ?

**Comment by Anthony-76** [comment]
clamdscan works fine in command line

e2guardian user is "clamav"

Theses files have the good rights

**Comment by fredbcode** [comment]
For the record:

About clamdscan 
There is a problem here in getLine https://github.com/e2guardian/e2guardian/blob/v4.1/src/contentscanners/clamdscan.cpp#L147

Seems write was good but not read 
rc = stripedsocks.getLine(buff, 4096, o.content_scanner_timeout) returns is 0 but the data is empty 

If there is no return the plugin validate as good, I think there is a security problem here 

No problem manually with socat 

socat - UNIX-CONNECT:/var/run/clamav/clamd.ctl 
SCAN /tmp/tfBZtBMJ
/tmp/tfBZtBMJ: OK

**Comment by fredbcode** [comment]
@Anthony-76 Can you allow a temporary access to your machine ? (contact me by mail if you can)

**Comment by Anthony-76** [comment]
fredbcode, are you avalaible the next monday, the morning to have an access on my Machine?

**Comment by fredbcode** [comment]
Yes ok

Le 19 mai 2017 17:24:17 GMT+02:00, Anthony-76 <notifications@github.com> a écrit :
>fredbcode, are you avalaible the next monday, the morning to have an
>access on my Machine?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/224#issuecomment-302733184

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
Fixed
