### ISSUE TITLE
segfault in libstdc++.so.6.0.20

### ISSUE THREAD

**Issue by xenadmin** [e2guardian/e2guardian#225]
Hello,
we use Debian 8 Jessie x64. We installed the deb package of e2guardian 4.1 from the releases.
We use Squid Cache: Version 3.4.8

e2guardian Port 2323
squid Port 2324
Alle test are performed through Internet Explorer 11

We migrate a customer from DansGuardian to e2guardian. He asked us to to use his old template.html. As soon as I use that file, i get the following error a few seconds after I restart the service:

`May 23 16:12:01 proxy kernel: [943007.854768] e2guardian[26414]: segfault at 0 ip 00007f2c79d8b2d9 sp 00007f2c714e0d20 error 4 in libstdc++.so.6.0.20[7f2c79ccb000+ec000]`

The template:
```
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>Company GmbH - Zugriff Verweigert</title>
    <style>
        <!-- html, body { font-family: Arial,Helvetica,sans-serif; font-size: 75%; line-height: 1.5; margin: 0; padding: 0; background: #333 url("http://10.21.30.118/dg/bg-master.jpg") repeat-x fixed left top; } -->
        #holder { width: 960px; margin:5px auto 0 auto; background-color: #ecedee; border-left: 2px solid #51c053; border-right: 2px solid #51c053; color: #000; }
        <!-- #header { background: url(http://10.21.30.118/dg/start.jpg); height:293px; padding:7px 50px 0 50px; text-align:right; } -->
        #content { padding:10px 20px; font-size:133.33%; }
    </style>
</head>
<body>
    <div id="holder">
        <div id="header">
            <span>Benutzer: -USER- | IP: -IP- | Gruppe: -FILTERGROUP- | Host: -HOST-</span>

        </div>
        <div id="content">

            <div style="border:1px solid #444; background:#0517e6; color:#fff; padding:10px 50px;">
                <h2>Der Zugriff auf die Seite</h2>
                <h3 style="color:red;">-URL-</h3>
                <h2>wurde mit folgender Begruendung verweigert:</h2>
                <h3 style="color:red;">-REASONGIVEN-</h3>
                                <p>-CATEGORIES-</p>
                <p>-REASONLOGGED-</p>
            </div>
            <br /><br />
            <div style="border:1px solid #444; background:#fff; padding:10px;">
                Sie sehen diese Fehlermeldung, weil die von Ihnen gewuenschte Seite unangebrachte Inhalte aufweist oder als solche gekennzeichnet ist.
                Bei Fragen oder Beschwerden wenden Sie sich bitte an Ihren Netzwerkadministrator.

            </div>

        </div>
    </div>
</body>
</html>
```

The default template works without problems. 
Any idea?

**Comment by fredbcode** [comment]
I guess it's related with bug #217
Now retryfix shows the wrong line, maybe a bad line break

**Comment by xenadmin** [comment]
Ok, this is labeled as fixed, what must I do to resolve this issue? I think I missed something.

**Comment by fredbcode** [comment]
> We installed the deb package of e2guardian 4.1

Can you make a try with "retryfix" ? 
Or use an editor like vi to remove space and blanck

**Comment by fredbcode** [comment]
> We installed the deb package of e2guardian 4.1

Can you make a try with "retryfix" ? 
Or use an editor like vi to remove space and blanck

**Comment by xenadmin** [comment]
I'm so sorry, but I have absolutely no idea what you mean with "retryfix". Is that a program or parameter?

I removed all the blank lines with nano, but still no difference.

**Comment by fredbcode** [comment]
I mean the retryfix branch from github, the fix is here

**Comment by xenadmin** [comment]
aaaahhhh I see.
Is there a deb file available or do i have to compile from source?

**Comment by fredbcode** [comment]
Sorry actually no deb, we will release soon but many users contact me about bugs with AV scanning so I need take a look

**Comment by xenadmin** [comment]
I will talk to my colleague if he can help me compiling. 

I also have problems with clamav, should I open a new issue for that topic? Main problem is, that as soon as I enable clamav integration everything gets real slow.

**Comment by fredbcode** [comment]
About clamav put your comment here https://github.com/e2guardian/e2guardian/issues/224
Please post your configuration

----- Mail original -----

**Comment by xenadmin** [comment]
I was able to solve the problem on my own. e2guardian 4.1 doesn't like the customers DansGuardian Template at all. But a colleague of me converted the template, so that the pictures are embedded in the file. Now it works. I attach both files for your reference.

**Comment by xenadmin** [comment]
https://sfs.login-online.de/f/e21574ffc2/

**Comment by fredbcode** [comment]
Ok
