### ISSUE TITLE
Segmentation fault with -HOST- placeholder

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#229]
end log request ----------------------------------------
from header url:http://vitrines.globo.com/vitrine/vitrine.min.js Line: 1331 Function: getUrl
Displaying TEMPLATE
-HOST- placeholder encountered but hostname currently unknown; lookup forced.
Segmentation fault

**Comment by fredbcode** [comment]
Do you have some informations in syslog ? Do you have a way to reproduce ?

**Comment by fredbcode** [comment]
In HTMTemplate.cpp

Line 164 can try to remove the DNS request 

And put just for testing host = "test";

if (host == NULL) {
host = "test";
}

line = (host ? .....

Something like that ...

**Comment by marcelloc** [comment]
The site on debug is on my blacklist. That was the way I could reproduce the error.

**Comment by fredbcode** [comment]
Ok If you find a little time try the change above, it's just to know if there an issue with a wrong DNS resolution

**Comment by fredbcode** [comment]
I pushed some fixes from Philip, can you make a try ?

**Comment by marcelloc** [comment]
still crashing with -HOST- on denied page

**Comment by fredbcode** [comment]
E2guardian can make a DNS request ?

**Comment by fredbcode** [comment]
You can make a retry ?

**Comment by fredbcode** [comment]
Still present ?

**Comment by fredbcode** [comment]
However, if you are still experiencing this issue, please feel free to reopen it

**Comment by marcelloc** [comment]
Found the bug. I'm pushing a fix to it right now.

**Comment by marcelloc** [comment]
the ip has a name. The size of if (names->size() > 0) is 2
but *host = names->front(); or line = *host; segfault the daemon.

I was researching and found that gethostbyaddr was replaced by getnameinfo but the sintax changes a bit. Still trying to test with new function to see if result changes on BSD

**Comment by marcelloc** [comment]
I Could fix it changing the login, can you check if it does no breaks anything?
