### ISSUE TITLE
sslcertcheck seems to be ignored with MITM

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#230]
While using MITM, sites with bad certificate are always blocked with:

Certificate supplied by server was not valid  SSL SITE

**Comment by fredbcode** [comment]
Are you using mitmcheckcert ?

# Enable MITM site certificate checking
# ignored if  sslmitm is off
# default (recommended) is 'on'
mitmcheckcert = on

**Comment by marcelloc** [comment]
maybe my mistake. I'll check

**Comment by marcelloc** [comment]
Sorry. My mistake I was configuring just sslcertcheck. MITM is working fine with checkcert
but when I tried the oposite(no MITM and sslcertcheck=on) what kind of error should user receive? 
I'm getting browser add exception alert instead of a ssl error. Is this the normal behavior?

**Comment by fredbcode** [comment]
yes this option is only used by SSLMITM
So with MITM disabled you have the usual behaviour (depend of browser)

**Comment by marcelloc** [comment]
Ok. Thanks.
