### ISSUE TITLE
daemon aborts with more then 4000 httpd workers in BSD

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#231]
Compiling ,*[a-z|A-Z].*
...with PCRE
 in handle connection
 waiting connection on http_worker_Q 0x8136de400
,*[a-z|A-Z].*
...with PCRE
 in handle connection
 waiting connection on http_worker_Q 0x8136dec00
Compiling ,*[a-z|A-Z].*
...with PCRE
 in handle connection
 waiting connection on http_worker_Q 0x8136dcc00
Abort

**Comment by fredbcode** [comment]
Be carreful you are using debug compilation, please retry with a "normal" version

**Comment by marcelloc** [comment]
This was the first try. I've enabled debug to see what was going wrong

**Comment by fredbcode** [comment]
Some news ?

**Comment by marcelloc** [comment]
Same result with latest code.

**Comment by fredbcode** [comment]
Hum I Wonder you reach a system limit, which result of ?

 sysctl kern.threads.max_threads_per_proc


----- Marcello Coutinho <notifications@github.com> a écrit :

**Comment by marcelloc** [comment]
kern.threads.max_threads_per_proc: 4096
