### ISSUE TITLE
back button circumvents filter

### ISSUE THREAD

**Issue by spikedrba** [e2guardian/e2guardian#235]
Both I and someone else posted to the ML one month apart reporting this so I've decided to open an issue.

Repro:
- run a google search for banner keyword
- get the expected banned page
- hit the back button
- see the result page

Looking at the logs the urls are slightly different which I'm guessing is why the difference in results, altho it's strange because the differences are minimal and the second url being shorter I'd actually expected the relevant of the banned keyword to be even higher, but maybe something else is at play.

Here's the urls:

<pre>
2017.6.17 12:09:49 - x.x.x.x https://www.google.com/search?site=&source=hp&q=BAD+WORDS&gs_l=hp.3...1989.1989.0.3050.1.1.0.0.0.0.66.66.1.1.0....0...1.1.64.hp..0.0.0.hqNTLzmSYUQ&bav=on.2,or.&fp=1&biw=621&bih=323&dpr=1&tch=1&ech=1&psi=eX5FWfHsNcH8jwPwlJqQBg.1497726586744.3
2017.6.17 12:10:06 - x.x.x.x https://www.google.com/gen_204?atyp=i&ct=**backbutton**&cad=&tt=navigation&ei=eX5FWfHsNcH8jwPwlJqQBg&zx=1497726606875 - GET 0 0 - 1 204 - - no_mame_group - - - - -
2017.6.17 12:10:07 - x.x.x.x https://www.google.com/search?q=BAD+WORDS&bav=on.2,or.&cad=b&fp=1&biw=621&bih=323&dpr=1&tch=1&ech=1&psi=eX5FWfHsNcH8jwPwlJqQBg.1497726606877.3 - GET 20638 0 - 1 200 application/json - no_mame_group - - - - -
</pre>

links to ML posts:
* https://groups.google.com/forum/#!topic/e2guardian/JefUJc5lcTI
* https://groups.google.com/forum/#!topic/e2guardian/6TzTI91y20g

I'm testing with the retryfix branch.

**Comment by spikedrba** [comment]
forgot to add this to the ticket, but like I said on the group, if I add a lot more bad keywords the problem does not present itself, strengthening the hypothesis that somehow the difference in text is enough to trigger the DENIED in one case and not the other.

**Comment by fredbcode** [comment]
Here a message from Philip 

>  Hi Fred,
> 
> I do not have the problem here at all.
> 
> Looking at the email trail it seems that initially the block is via urlregexp - we only use this in very rare cases as it is very unreliable and tends to cause overblocking.    The two URLs are slightly different and so the pattern matches on one url and does not on the second.
> 
> Search term blocking will only work if the correct regexps are in searchregexplist which extracts the search terms from the url.
> 
> The following entries work here for Google:-
> 
> "^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*\?q=([^&]*)\&.*"->"\1"
> "^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*/.*\&q=([^&]*).*"->"\1"
> "^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*\?q=([^&]*)"->"\1"
> "^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*/.*\&q=([^&]*)"->"\1"
> 
> This has two extra lines which cope with the case where the search string is at the end of the url

**Comment by philipianpearce** [comment]
The email system seems to have stripped the '*' from the lines. 

Please substitute an asterisk ("*") for the capital 'A' in the following: 

"^ http:// [0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]A\?q=([^&]A)\&.A"->"\1" 
"^ http:// [0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]A/.A\&q=([^&]A).A"->"\1" 
"^ http:// [0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]A\?q=([^&]A)"->"\1" 
"^ http:// [0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]A/.A\&q=([^&]A)"->"\1" 

Regards 

Philip 

----- Original Message -----

**Comment by spikedrba** [comment]
thanks @fredbcode and @philipianpearce based on your comment however, it seems that I shouldn't be using this to begin with? I'm referring to "the block is via urlregexp - we only use this in very rare cases as it is very unreliable and tends to cause overblocking". Is the recommendation to disable it then?

Like I said in the email thread, what actually puzzled me was that the page was not blocked by the weighted phrase list, given the many occurrences of the same bad term in the results. Any idea why that'd happen? Can you reproduce it at all if you search for that bad keyword ([here](https://github.com/e2guardian/e2guardian/blob/master/configs/lists/phraselists/pornography/weighted#L402) it is again).

thanks,

Spike

**Comment by forid786** [comment]
Not sure if this is related, but this seems closely related to an issue I've been having, although only on Yandex.

When you go to Yandex and search "porn" in the search for example. It isn't blocked, however, if you refresh the page it picks it up. It should be picked up straight away, there's no point showing bad links and pictures, then it disappearing after a refresh.
