### ISSUE TITLE
--with-filedescriptors removed on V4 ?

### ISSUE THREAD

**Issue by tgalloy** [e2guardian/e2guardian#243]
When installing the V3.5 for testing, I used --with-filedescriptors to up the maximum childrens to 8192, but on V4, this parameter does not exist ? Is it a bug, or have you removed it and up de default process count e2guardian can handle ?

**Comment by fredbcode** [comment]
Yes it's removed, now e2guardian is based on new slightly more efficient model, which is based on threads instead of independent processes.

Now the max value is 20 000, but many resources are needed in this case. 
On large site you might want to try 5000 

Changes about FD_SETSIZE are not longer needed

**Comment by tgalloy** [comment]
I have an other issue (I will make a new issue if you want). Our proxy are running on CentOS 6.9 (2 VM) and 7.3 (2 physical servers), and when compiling V4, I get an error about libiconv. I have a command 'iconv', but there is no packet named libiconv. I can disable the auth plugins, but I want to know, maybe we will need it in the future :|

**Comment by fredbcode** [comment]
FYI 4.1.1 is in the starting blocks

**Comment by fredbcode** [comment]
Yes different issue, I don't know centos but libiconv seems exist ?

https://centos.pkgs.org/7/forensics-x86_64/libiconv-devel-1.14-3.el7.x86_64.rpm.html
https://centos.pkgs.org/7/forensics-x86_64/libiconv-1.14-3.el7.x86_64.rpm.html

**Comment by tgalloy** [comment]
Thank you, I see those links after commenting. This repo isn't installed by default on CentOS, I will install it and try it on the test server. Thank you for your quick response time :)
