### ISSUE TITLE
Categories not showing for blacklists

### ISSUE THREAD

**Issue by forid786** [e2guardian/e2guardian#244]
When a site is banned via a blacklist, such as shallalist, the category isn't shown. For example, if you've blocked betting sites on your network, and you try visiting it via E2Guardian. The block page only says "siteblocked" not the category or why it was blocked.

Here's an example : http://prntscr.com/fn3hgk

Hope it can be sorted out, I'm using pfSense (BSD) x64.

**Comment by fredbcode** [comment]
Are you sure that there is a "tag" ?

# List categorisation
#listcategory: "Banned Sites"

Be carreful "#" is needed !

**Comment by marcelloc** [comment]
I do a cleanup on resulting files on pfSense. I'll update the code to be sure it's not being removed.

Is there any other options? I saw #listcategory: #noconvert #ENDLIST #time:

**Comment by fredbcode** [comment]
No more than http://contentfilter.futuragts.com/wiki/doku.php?id=delivering_block_messages#cgi_program_parameters

Le 24 juin 2017 07:11:48 GMT+02:00, Marcello Coutinho <notifications@github.com> a écrit :
>I do a cleanup on resulting files on pfSense. I'll update the code to
>be sure it's not being removed.
>
>Is there any other options? I saw #listcategory: #noconvert #ENDLIST
>#time:
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/244#issuecomment-310814860

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
closed due to lack of response - feel free to reopen if necessary

**Comment by marcelloc** [comment]
Each blacklist file needs the listcategory definition inside it. Editing all .include show the category on deny page.

**Comment by forid786** [comment]
@marcelloc Can we not add listcategory definition in an automated manner? Because ShallaList should already have the blacklisted URL's in separate categories. 

I want to deploy E2Guardian for a Charity based educational organisation, and categories need to be listed for blocked URL's, for obvious reasons such as troubleshooting over blocking and getting the filter tuned right.

**Comment by marcelloc** [comment]
I`ve answered it on pfSense forum too. I'll include it on the package. 

https://forum.pfsense.org/index.php?topic=128116.msg732712#msg732712

**Comment by Dalacor** [comment]
I have searched Google high and low to get a clear answer on this issue.

Do you have to go into /blacklists/porn and then edit the domain file and put in #listcategory: "Porn" and basically do that for every domain, url and expressions file for every single category.

If so, how do you get these files to retain the #listcategory setting if you update the blacklists daily.

Is there no way to inlclude the blacklist in the bannedsitelist file and to specify the #listcategory in the bannedsitelist file as well. This would be a better solution.

What I have got is two lines in the bannedsitelist pointing to two files bigblacklist and squidblacklist to separate the blacklists. The only way that I can get the category to show is to edit the actual domain blacklist file in each category. But these files are updated daily!

**Comment by fredbcode** [comment]
Hi, you can just put #listcategory tag in your blacklist file (I mean the file called by e2) and in this file just add an include to your "real" blacklist

**Comment by Dalacor** [comment]
Yes I can do that. But I don't want just 
#listcategory: "Banned Sites" for all the blacklist files.

What I am trying to do is if the website is blacklisted by porn or social networks blacklist then the category shows as porn or social networks or whatever blacklist category it is. Currently it just shows as Banned Sites (as I have the listcategory as Banned Sites) on the old system and blank on the new system unless I put the Listcategory in each domain file in the blacklists.

I can't work out how to list all the categories in the blacklist file.

**Comment by forid786** [comment]
@Dalacor on the pfSense GUI for E2 Guardian on the black list tab it allows you to set it up exactly as you would like it. So if its a porn site that's blocked it'll actually list the category on the block page.

I think there maybe some script in the background to do the list category though but will probably need to check the code to confirm how it works for sure.

**Comment by Dalacor** [comment]
Does pfsense edit the bannedsitelist file for each categories or does the program edit the actual domain file within the blacklist. the impression that I got is that the PFsense developer modified the program to make it edit the actual domain file in each category.

**Comment by forid786** [comment]
Yeah I think you're probably right, but it does it pretty quick. At least for my black list. But checking the code is the only way to be certain!

**Comment by Dalacor** [comment]
So basically I just need to find a way to make Slackware update the blacklist files and include the categories or ask Squidblacklist to include the listcategories as part of the subscription.

Thanks @forid786
