### ISSUE TITLE
Access denied page not shown when trying to open "bad" https site 

### ISSUE THREAD

**Issue by VasiliyF** [e2guardian/e2guardian#247]
v4.1.1. Access denied page not shown when trying to open "bad" https site and sslmitm=off. Instead Firefox show "The proxy server is refusing connections", in access.log appropriate string present ("https://vk.com:443","*DENIED* Blocked site: vk.com"....)

**Comment by Kenny690** [comment]
Это потому что e2 выводит страницу блокировки по протоколу http, а браузер видит, что ты пытаешься обратиться к https. Поэтому прокси и не принимает соединение.

**Comment by Kenny690** [comment]
Включи sslmitm и он будет подставлять страницу блокировки по протоколу https. И всё будет работать.

**Comment by VasiliyF** [comment]
Мне нужно блокировать https сайты без sslmitm для определённой группы.

**Comment by fredbcode** [comment]
Not a bug, without SSLMITM e2guardian can't switch the page by another. 
However there is a trick with firefox only (see ssllaccessdenyaddress)

**Comment by Kenny690** [comment]
Тогда оставляй всё как есть. Сайты блокируются же. Да и sslmitm можно включить только для одной группы, не затрагивая остальные. Для этого, в e2guardianf1.conf ставишь sslmitm=on, а в f2 ставишь sslmitm=off. По-другому, насколько я знаю, нельзя, ибо трафик по 443 порту шифруется, а e2 не знает как его расшифровать без sslmitm.
