### ISSUE TITLE
ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by infrafast** [e2guardian/e2guardian#267]
Hello, 

e2guardian works fine when filtering http but when filtering https, I systematically get 

ERR_TUNNEL_CONNECTION_FAILED

logfile indicate

2017.7.31 19:31:22 - 192.168.0.28 https://www.youtube.com:443 *DENIED* Blocked site: youtube.com CONNECT 0 0 Banned Sites 1 403 - - no_mame_group - - - - -

The configuration I have is squid (port 3131) + e2guardian-4.1.2 (port 8082)

I am not sure if this is a bug as I can't imagine e2guardian not filtering https and being the only one having this issue ? 

Thanks,

Thomas

**Comment by fredbcode** [comment]
Which version ? It works with sslmitm=off ?

**Comment by forid786** [comment]
Perhaps there's some keywords on YouTube that E2 Guardian blocked. I had that issue with the Japanese phrase list, which was really alpha.

**Comment by fredbcode** [comment]
Did you have follow the documentation ? There is an AC on your browser ?

**Comment by infrafast** [comment]
Hello, thks for your replies. e2guardian is v4.1.2, 
I didn't touch the sslmitm zhich is off as defaut in e2guardianf1.conf
@forid: I will double check but in fact, its with all https site, I used youtube as an example
I checked the dansguardian and e2guadrian wiki doc but can't find anything related to that issue (I don't have AC on my browser). 
Regarding 443 forward, my service provider box forward this to my synology (equally as 80) which act as a reverse proxy for outside and transparent proxy for inside. No issue with 80 however. I'll try to deactivate the reverse proxy and tell you.

**Comment by infrafast** [comment]
in addition to my previous post/feedback; I made the following:
- deactivate the reverse proxy (forward 443 from my box to nginx), same issue
- when I type in a non existing site (like: https://www.123456azertyuiop.fr/)
    get in chrome: ERR_TUNNEL_CONNECTION_FAILED (site is unreachable)
   nothing captured on e2guardian
- when I type in an existing https filtrered site (let's say youtube as described in initiql post),
   get in chrome: ERR_TUNNEL_CONNECTION_FAILED (site is unreachable)
   banned site captured in e2guardian logfile
More info on my config:
- service provider: free, (revolution freebox) 
- both e2guardian and proxy (squid) running on synology NAS (dsm version 6) 
any clue?

**Comment by fredbcode** [comment]
You are using transparent proxy ?

Le 1 août 2017 12:09:01 GMT+03:00, infrafast <notifications@github.com> a écrit :
>in addition to my previous post/feedback; I made the following:
>- deactivate the reverse proxy (forward 443 from my box to nginx), same
>issue
>- when I type in a non existing site (like:
>https://www.123456azertyuiop.fr/)
>    get in chrome: ERR_TUNNEL_CONNECTION_FAILED (site is unreachable)
>   nothing captured on e2guardian
>- when I type in an existing https filtrered site (let's say youtube as
>described in initiql post),
>   get in chrome: ERR_TUNNEL_CONNECTION_FAILED (site is unreachable)
>   banned site captured in e2guardian logfile
>More info on my config:
>- service provider: free, (revolution freebox) 
>- both e2guardian and proxy (squid) running on synology NAS (dsm
>version 6) 
>any clue?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/267#issuecomment-319314122

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by infrafast** [comment]
Transparent proxy is not  a parameter I have access to in my synology interface; but here is what I did: 

my internet box act as a router (not in bridge mode I can't make it as bridge)
my synology act as a proxy / dhcp / firewall

since my clients could bypass the synology to connect internet thru the box directly:
- I block all traffic in my box thru parental control and only let my synology go thru (192.168.0.100). 
- my dhcp (synology) distribute wpdat on port 81 (http://192.168.0.100:81/wpad.dat) and define himself as the gateway for the client 

content of the wpad:
function FindProxyForURL(url, host) { if (isInNet(host, "192.168.0.0", "255.255.255.0")) { return "DIRECT"; } else { return "PROXY 192.168.0.100:8082" ; } }

why port 81 ? : the port 80 and 443 are blocked to avoid my client connecting to internet directly and force them to go thru the proxy (e2guardian on 8082 which talk to squid on 3131) 

I admit the setup is a little bit un-conventionnal but it's the only way I found to control and force traffic thru the synology having the box in router mode...

I tried to let all open (443 and 80) but have the same behaviour, it's really only 443 which cause issue

**Comment by fredbcode** [comment]
Can you make a try without e2 only with squid running on 8082 ?

Le 1 août 2017 12:34:40 GMT+03:00, infrafast <notifications@github.com> a écrit :
>Transparent proxy is not  a parameter I have access to in my synology
>interface; but here is what I did: 
>
>my internet box act as a router (not in bridge mode I can't make it as
>bridge)
>my synology act as a proxy / dhcp / firewall
>
>since my clients could bypass the synology to connect internet thru the
>box directly:
>- I block all traffic in my box thru parental control and only let my
>synology go thru (192.168.0.100). 
>- my dhcp (synology) distribute wpdat on port 81
>(http://192.168.0.100:81/wpad.dat) and define himself as the gateway
>for the client 
>
>content of the wpad:
>function FindProxyForURL(url, host) { if (isInNet(host, "192.168.0.0",
>"255.255.255.0")) { return "DIRECT"; } else { return "PROXY
>192.168.0.100:8082" ; } }
>
>why port 81 ? : the port 80 and 443 are blocked to avoid my client
>connecting to internet directly and force them to go thru the proxy
>(e2guardian on 8082 which talk to squid on 3131) 
>
>I admit the setup is a little bit un-conventionnal but it's the only
>way I found to control and force traffic thru the synology having the
>box in router mode...
>
>I tried to let all open (443 and 80) but have the same behaviour, it's
>really only 443 which cause issue
>
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/267#issuecomment-319320450

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by infrafast** [comment]
good idea. Indeed I have to look in squid side as when I bypass e2 and connect direclty to squid on 8082 I have the same result: http filtrered well with the squid "access forbidden page" and https filtered but with the  ERR_TUNNEL_CONNECTION_FAILED.

Thanks for your good support and having routed me to the right path. I will investigate on syno forum now and post my solution if any here if it may help others!

**Comment by fredbcode** [comment]
No problem thanks for your return

Le 1 août 2017 16:22:28 GMT+03:00, infrafast <notifications@github.com> a écrit :
>good idea. Indeed I have to look in squid side as when I bypass e2 and
>connect direclty to squid on 8082 I have the same result: http
>filtrered well with the squid "access forbidden page" and https
>filtered but with the  ERR_TUNNEL_CONNECTION_FAILED.
>
>Thanks for your good support and having routed me to the right path. I
>will investigate on syno forum now and post my solution if any here if
>it may help others!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/267#issuecomment-319368147

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by forid786** [comment]
I believe it could be related to redirecting HTTPS traffic. I tried using a NAT redirection to redirect port 443 (HTTPS) traffic to E2 Guardian, via my pfsense firewall/router and that caused the same problem you are having. However, just as you describe, http (port 80) traffic worked fine as normal.
