### ISSUE TITLE
Build failure against OpenSLL >= 1.1

### ISSUE THREAD

**Issue by david-geiger** [e2guardian/e2guardian#268]
Hi,

I tried to build latest 4.1.2 release on Mageia Cauldron but the build fails against OpenSLL >= 1.1, see the build log:

> CertificateAuthority.cpp: In member function 'bool CertificateAuthority::getSerial(const char*, ca_serial*)':
CertificateAuthority.cpp:133:16: error: aggregate 'EVP_MD_CTX mdctx' has incomplete type and cannot be defined
     EVP_MD_CTX mdctx;
                ^
CertificateAuthority.cpp:150:30: error: 'EVP_MD_CTX_cleanup' was not declared in this scope
     EVP_MD_CTX_cleanup(&mdctx);
                              ^
CertificateAuthority.cpp: In member function 'EVP_PKEY* CertificateAuthority::getServerPkey()':
CertificateAuthority.cpp:471:29: error: invalid use of incomplete type 'EVP_PKEY {aka struct evp_pkey_st}'
     CRYPTO_add(&_certPrivKey->references, 1, CRYPTO_LOCK_EVP_PKEY);
                             ^
In file included from /usr/include/openssl/crypto.h:31:0,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/pem.h:14,
                 from CertificateAuthority.cpp:21:
/usr/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'EVP_PKEY {aka struct evp_pkey_st}'
 typedef struct evp_pkey_st EVP_PKEY;
                ^
CertificateAuthority.cpp:471:46: error: 'CRYPTO_LOCK_EVP_PKEY' was not declared in this scope
     CRYPTO_add(&_certPrivKey->references, 1, CRYPTO_LOCK_EVP_PKEY);
                                              ^
CertificateAuthority.cpp:471:66: error: 'CRYPTO_add' was not declared in this scope
     CRYPTO_add(&_certPrivKey->references, 1, CRYPTO_LOCK_EVP_PKEY);
                                                                  ^
Makefile:1127: recipe for target 'e2guardian-CertificateAuthority.o' failed
make[2]: *** [e2guardian-CertificateAuthority.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/e2guardian-4.1.2/src'
make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/iurt/rpmbuild/BUILD/e2guardian-4.1.2/src'

[build_log_e2guardian.txt](https://github.com/e2guardian/e2guardian/files/1199497/build_log_e2guardian.txt)

**Comment by fredbcode** [comment]
I guess there is some missing library like libopenssl-dev

**Comment by david-geiger** [comment]
Nop it is installed: "lib64openssl-devel-1.1.0f-1.mga7" and "lib64openssl1.1-1.1.0f-1.mga7"

**Comment by fredbcode** [comment]
libssl1.x-dev is needed

**Comment by fredbcode** [comment]
Perhaps the name is just libopenssl-devel on your system ? You must find the package with this files 
https://packages.debian.org/fr/jessie/amd64/libssl-dev/filelist

**Comment by david-geiger** [comment]
Yes on Mageia the name is just libopenssl-devel and the files are:

/usr/include/multiarch-x86_64-linux/openssl/opensslconf.h
/usr/include/openssl/aes.h
/usr/include/openssl/asn1.h
/usr/include/openssl/asn1_mac.h
/usr/include/openssl/asn1t.h
/usr/include/openssl/async.h
/usr/include/openssl/bio.h
/usr/include/openssl/blowfish.h
/usr/include/openssl/bn.h
/usr/include/openssl/buffer.h
/usr/include/openssl/camellia.h
/usr/include/openssl/cast.h
/usr/include/openssl/cmac.h
/usr/include/openssl/cms.h
/usr/include/openssl/comp.h
/usr/include/openssl/conf.h
/usr/include/openssl/conf_api.h
/usr/include/openssl/crypto.h
/usr/include/openssl/ct.h
/usr/include/openssl/des.h
/usr/include/openssl/dh.h
/usr/include/openssl/dsa.h
/usr/include/openssl/dtls1.h
/usr/include/openssl/e_os2.h
/usr/include/openssl/ebcdic.h
/usr/include/openssl/ec.h
/usr/include/openssl/ecdh.h
/usr/include/openssl/ecdsa.h
/usr/include/openssl/engine.h
/usr/include/openssl/err.h
/usr/include/openssl/evp.h
/usr/include/openssl/hmac.h
/usr/include/openssl/idea.h
/usr/include/openssl/kdf.h
/usr/include/openssl/lhash.h
/usr/include/openssl/md2.h
/usr/include/openssl/md4.h
/usr/include/openssl/md5.h
/usr/include/openssl/mdc2.h
/usr/include/openssl/modes.h
/usr/include/openssl/obj_mac.h
/usr/include/openssl/objects.h
/usr/include/openssl/ocsp.h
/usr/include/openssl/opensslconf.h
/usr/include/openssl/opensslv.h
/usr/include/openssl/ossl_typ.h
/usr/include/openssl/pem.h
/usr/include/openssl/pem2.h
/usr/include/openssl/pkcs12.h
/usr/include/openssl/pkcs7.h
/usr/include/openssl/rand.h
/usr/include/openssl/rc2.h
/usr/include/openssl/rc4.h
/usr/include/openssl/rc5.h
/usr/include/openssl/ripemd.h
/usr/include/openssl/rsa.h
/usr/include/openssl/safestack.h
/usr/include/openssl/seed.h
/usr/include/openssl/sha.h
/usr/include/openssl/srp.h
/usr/include/openssl/srtp.h
/usr/include/openssl/ssl.h
/usr/include/openssl/ssl2.h
/usr/include/openssl/ssl3.h
/usr/include/openssl/stack.h
/usr/include/openssl/symhacks.h
/usr/include/openssl/tls1.h
/usr/include/openssl/ts.h
/usr/include/openssl/txt_db.h
/usr/include/openssl/ui.h
/usr/include/openssl/whrlpool.h
/usr/include/openssl/x509.h
/usr/include/openssl/x509_vfy.h
/usr/include/openssl/x509v3.h
/usr/lib64/libcrypto.so
/usr/lib64/libssl.so
/usr/lib64/pkgconfig/libcrypto.pc
/usr/lib64/pkgconfig/libssl.pc
/usr/lib64/pkgconfig/openssl.pc

**Comment by fredbcode** [comment]
And the issue still here ?

**Comment by david-geiger** [comment]
Yes it doesn't build with openssl 1.1.0f but with older 1.0.2l it build fine.

**Comment by fredbcode** [comment]
Ok after investigation there are some major changes in openssl 1.1.x and e2guardian can't works directyl with.
We should do something like:
https://github.com/x42/liboauth/issues/9

This bug is related with #269

**Comment by philipianpearce** [comment]
I will look at this later in v5 development.   If not too complicated, we may be able to back-port to v4.

**Comment by david-geiger** [comment]
Any news ?

**Comment by fredbcode** [comment]
We are working on it, I'm testing some code from Philip right now

**Comment by fredbcode** [comment]
E2guardian 4.1.5 [develop's branch] works now with libssl1.0 and libssl1.1

Build with:
'--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'

I will release soon, next month

V5 still in development for now

**Comment by fredbcode** [comment]
E2guardian 4.1.5 is released

**Comment by david-geiger** [comment]
Thank you very much!

Build fine now on Mageia Cauldron against openssl >= 1.1

**Comment by chujiangke** [comment]
> 
> libssl1.x-dev is needed

thinks men

**Comment by chujiangke** [comment]
apt-get install libssl1.0-dev
