### ISSUE TITLE
Provide DEB packages of the 4.x releases for Debian 9 Stretch

### ISSUE THREAD

**Issue by xenadmin** [e2guardian/e2guardian#269]
It would be nice if you could provide ready to use DEB packages for x64 Debian 9 Stretch under:
https://github.com/e2guardian/e2guardian/releases
The Version released with Debian 9 Stretch is 3.5.x

Thank you.

**Comment by fredbcode** [comment]
Did you try the package with Debian 9 ?

Le 8 août 2017 16:16:38 GMT+02:00, Marco Hofmann <notifications@github.com> a écrit :
>It would be nice if you could provide ready to use DEB packages for x64
>Debian 9 Stretch under:
>https://github.com/e2guardian/e2guardian/releases
>The Version released with Debian 9 Stretch is 3.5.x
>
>Thank you. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/269

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by xenadmin** [comment]
Yes I tried "E2guardian first v4 Stable Release - version 4.1.0" if I recall correctly. It couldn't resolve its dependencies. But I can't remember the exact message. 
Should I reproduce it to provide you with an error message?

**Comment by fredbcode** [comment]
Yes


You can also try this

dpkg -i package.deb

And right after

apt-get -f install


Use the latest 4.1.2

**Comment by xenadmin** [comment]
That were exactly the steps I tried on Stretch with 4.1.0 ;-)
I do a test with a VM.

**Comment by xenadmin** [comment]
```
root@stretch:~# dpkg -i e2guardian_4.1.2_jessie_ubuntu16.04_amd64.deb
Vormals nicht ausgewähltes Paket e2guardian wird gewählt.
(Lese Datenbank ... 28327 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von e2guardian_4.1.2_jessie_ubuntu16.04_amd64.deb ...
Entpacken von e2guardian (4.1.2) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von e2guardian:
 e2guardian hängt ab von libevent-pthreads-2.0-5; aber:
  Paket libevent-pthreads-2.0-5 ist nicht installiert.
 e2guardian hängt ab von libtommath0; aber:
  Paket libtommath0 ist nicht installiert.
 e2guardian hängt ab von libssl1.0.0 (>= 1.0.0); aber:
  Paket libssl1.0.0 ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes e2guardian (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für systemd (232-25+deb9u1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 e2guardian

root@stretch:~# apt-get -f install
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Abhängigkeiten werden korrigiert ... Fertig
Die folgenden Pakete werden ENTFERNT:
  e2guardian
0 aktualisiert, 0 neu installiert, 1 zu entfernen und 0 nicht aktualisiert.
1 nicht vollständig installiert oder entfernt.
Nach dieser Operation werden 14,2 MB Plattenplatz freigegeben.
Möchten Sie fortfahren? [J/n]
(Lese Datenbank ... 28655 Dateien und Verzeichnisse sind derzeit installiert.)
Entfernen von e2guardian (4.1.2) ...
```
I know it's german, I didn't think about that when I installed the vm.

He misses: 
libevent-pthreads-2.0-5
libtommath0
libssl1.0.0 (>= 1.0.0)

apt-get -f install removes e2guardian

**Comment by fredbcode** [comment]
Try to install the libraries manually before
Apt-get install libevent-pthreads libsll libtommath 
Without the number version or with * 

Le 9 août 2017 13:32:58 GMT+02:00, Marco Hofmann <notifications@github.com> a écrit :
>```
>root@stretch:~# dpkg -i e2guardian_4.1.2_jessie_ubuntu16.04_amd64.deb
>Vormals nicht ausgewähltes Paket e2guardian wird gewählt.
>(Lese Datenbank ... 28327 Dateien und Verzeichnisse sind derzeit
>installiert.)
>Vorbereitung zum Entpacken von
>e2guardian_4.1.2_jessie_ubuntu16.04_amd64.deb ...
>Entpacken von e2guardian (4.1.2) ...
>dpkg: Abhängigkeitsprobleme verhindern Konfiguration von e2guardian:
> e2guardian hängt ab von libevent-pthreads-2.0-5; aber:
>  Paket libevent-pthreads-2.0-5 ist nicht installiert.
> e2guardian hängt ab von libtommath0; aber:
>  Paket libtommath0 ist nicht installiert.
> e2guardian hängt ab von libssl1.0.0 (>= 1.0.0); aber:
>  Paket libssl1.0.0 ist nicht installiert.
>
>dpkg: Fehler beim Bearbeiten des Paketes e2guardian (--install):
> Abhängigkeitsprobleme - verbleibt unkonfiguriert
>Trigger für systemd (232-25+deb9u1) werden verarbeitet ...
>Fehler traten auf beim Bearbeiten von:
> e2guardian
>
>root@stretch:~# apt-get -f install
>Paketlisten werden gelesen... Fertig
>Abhängigkeitsbaum wird aufgebaut.
>Statusinformationen werden eingelesen.... Fertig
>Abhängigkeiten werden korrigiert ... Fertig
>Die folgenden Pakete werden ENTFERNT:
>  e2guardian
>0 aktualisiert, 0 neu installiert, 1 zu entfernen und 0 nicht
>aktualisiert.
>1 nicht vollständig installiert oder entfernt.
>Nach dieser Operation werden 14,2 MB Plattenplatz freigegeben.
>Möchten Sie fortfahren? [J/n]
>(Lese Datenbank ... 28655 Dateien und Verzeichnisse sind derzeit
>installiert.)
>Entfernen von e2guardian (4.1.2) ...
>```
>I know it's german, I didn't think about that when I installed the vm.
>
>He misses: 
>libevent-pthreads-2.0-5
>libtommath0
>libssl1.0.0 (>= 1.0.0)
>
>apt-get -f install removes e2guardian
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/269#issuecomment-321229476

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by xenadmin** [comment]
´´´
root@stretch:~# apt install libevent-pthreads libsll libtommath
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket libevent-pthreads kann nicht gefunden werden.
E: Paket libsll kann nicht gefunden werden.
E: Paket libtommath kann nicht gefunden werden.
´´´
All three packages could not be found. I now remember the issue. That was the problem I had with 4.1.0.
After that I stopped trying an switched back to Debian 8. But today Debian 8 is old-stable and we need a path to Stretch.

**Comment by fredbcode** [comment]
Yes I will

I guess the versions are different can you try an apt-cache search libevent-pth*

And make the same for the others

Le 9 août 2017 13:56:48 GMT+02:00, Marco Hofmann <notifications@github.com> a écrit :
>´´´
>root@stretch:~# apt install libevent-pthreads libsll libtommath
>Paketlisten werden gelesen... Fertig
>Abhängigkeitsbaum wird aufgebaut.
>Statusinformationen werden eingelesen.... Fertig
>E: Paket libevent-pthreads kann nicht gefunden werden.
>E: Paket libsll kann nicht gefunden werden.
>E: Paket libtommath kann nicht gefunden werden.
>´´´
>All three packages could not be found. I now remember the issue. That
>was the problem I had with 4.1.0.
>After that I stopped trying an switched back to Debian 8. But today
>Debian 8 is old-stable and we need a path to Stretch. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/269#issuecomment-321234191

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by xenadmin** [comment]
```
root@stretch:~# apt search libevent-pth*
Sortierung... Fertig
Volltextsuche... Fertig
libevent-pthreads-2.0-5/stable 2.0.21-stable-3 amd64
  Asynchronous event notification library (pthreads)

root@stretch:~# apt search libssl*
Sortierung... Fertig
Volltextsuche... Fertig
...
libssl1.0.2/stable,now 1.0.2l-2 amd64  [installiert]
  Werkzeugsatz für das Secure Socket Layer (SSL) - Laufzeitbibliotheken

libssl1.1/stable,now 1.1.0f-3 amd64  [installiert]
  Werkzeugsatz für das Secure Socket Layer (SSL) - Laufzeitbibliotheken
...

root@stretch:~# apt search libtommath*
Sortierung... Fertig
Volltextsuche... Fertig
libtfm1/stable 0.13-4 amd64
  Fast multiple-precision integer library [runtime]

libtommath-dev/stable 1.0-4 amd64
  Integer-Bibliothek mit erhöhter Genauigkeit [Entwicklungsdateien]

libtommath-docs/stable 1.0-4 all
  multiple-precision integer library [documentation]

libtommath1/stable 1.0-4 amd64
  multiple-precision integer library [runtime]
```

I would guess the third one is the problem? What else do you need?

**Comment by xenadmin** [comment]
Doesn't work. Why should it? Installing the dependencies first with apt wouldn't make any difference? Anyway, here are the results:
```
apt list --installed
Auflistung... Fertig
...
libevent-pthreads-2.0-5/stable,now 2.0.21-stable-3 amd64  [installiert]
libssl1.0.2/stable,now 1.0.2l-2 amd64  [installiert]
libssl1.1/stable,now 1.1.0f-3 amd64  [installiert]
libtommath1/stable,now 1.0-4 amd64  [installiert]
...

root@stretch:~# dpkg -i e2guardian_4.1.2_jessie_ubuntu16.04_amd64.deb
Vormals nicht ausgewähltes Paket e2guardian wird gewählt.
(Lese Datenbank ... 28629 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von e2guardian_4.1.2_jessie_ubuntu16.04_amd64.deb ...
Entpacken von e2guardian (4.1.2) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von e2guardian:
 e2guardian hängt ab von libtommath0; aber:
  Paket libtommath0 ist nicht installiert.
 e2guardian hängt ab von libssl1.0.0 (>= 1.0.0); aber:
  Paket libssl1.0.0 ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes e2guardian (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für systemd (232-25+deb9u1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 e2guardian
```
He doesn't like that libssl1.**0.0** isn't avaible and libtommath**0**

**Comment by fredbcode** [comment]
Try this dpkg -i --force-all e2package.deb

Le 9 août 2017 17:31:23 GMT+02:00, Marco Hofmann <notifications@github.com> a écrit :
>Doesn't work. Why should it? Installing the dependencies first with apt
>wouldn't make any difference? Anyway, here are the results:
>```
>apt list --installed
>Auflistung... Fertig
>...
>libevent-pthreads-2.0-5/stable,now 2.0.21-stable-3 amd64  [installiert]
>libssl1.0.2/stable,now 1.0.2l-2 amd64  [installiert]
>libssl1.1/stable,now 1.1.0f-3 amd64  [installiert]
>libtommath1/stable,now 1.0-4 amd64  [installiert]
>...
>
>root@stretch:~# dpkg -i e2guardian_4.1.2_jessie_ubuntu16.04_amd64.deb
>Vormals nicht ausgewähltes Paket e2guardian wird gewählt.
>(Lese Datenbank ... 28629 Dateien und Verzeichnisse sind derzeit
>installiert.)
>Vorbereitung zum Entpacken von
>e2guardian_4.1.2_jessie_ubuntu16.04_amd64.deb ...
>Entpacken von e2guardian (4.1.2) ...
>dpkg: Abhängigkeitsprobleme verhindern Konfiguration von e2guardian:
> e2guardian hängt ab von libtommath0; aber:
>  Paket libtommath0 ist nicht installiert.
> e2guardian hängt ab von libssl1.0.0 (>= 1.0.0); aber:
>  Paket libssl1.0.0 ist nicht installiert.
>
>dpkg: Fehler beim Bearbeiten des Paketes e2guardian (--install):
> Abhängigkeitsprobleme - verbleibt unkonfiguriert
>Trigger für systemd (232-25+deb9u1) werden verarbeitet ...
>Fehler traten auf beim Bearbeiten von:
> e2guardian
>```
>He doesn't like that libssl1.**0.0** isn't avaible and libtommath**0**
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/269#issuecomment-321291576

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by risturiz** [comment]
Hi, Debian 9.1 too:

> /usr/sbin/e2guardian: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

With "dpkg -i --force-all" install but dont run because libssl

**Comment by fredbcode** [comment]
Ok I will made a specific package

Le 10 août 2017 23:44:46 GMT+02:00, Rafael Isturiz <notifications@github.com> a écrit :
>Hi, Debian 9.1 too:
>
>> /usr/sbin/e2guardian: error while loading shared libraries:
>libssl.so.1.0.0: cannot open shared object file: No such file or
>directory
>
>With "dpkg -i --force-all" install but dont run because libssl
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/269#issuecomment-321681944

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by xenadmin** [comment]
@fredbcode Du you still need the "dpkg -i --force-all e2package.deb" test from me? Or any other test?

**Comment by fredbcode** [comment]
No not needed, thanks

**Comment by fredbcode** [comment]
Ok I pushed a package compiled for libssl1.0.2
https://github.com/e2guardian/e2guardian/releases
It should works

**Comment by risturiz** [comment]
Hi, thanks a lot for the package... Install only complains about "Package libtommath0 is not installed." For the record, Debian 9.1 have:

> Package: libtommath1
> Source: libtommath
> Version: 1.0-4

But e2guardian is running now

**Comment by xenadmin** [comment]
I can confirm the same problem with libtommath0.

**Comment by fredbcode** [comment]
Ok fixed now

**Comment by xenadmin** [comment]
Installing via 
dpkg -i package.deb && apt-get -f install
Seems to work now. We now would have to try it on a real machine.
