### ISSUE TITLE
greysitelist hits not logged

### ISSUE THREAD

**Issue by spikedrba** [e2guardian/e2guardian#274]
Hi,

I've just began using grey lists, which according to [this](http://contentfilter.futuragts.com/wiki/doku.php?id=grey...list_or_exception...list&DokuWiki=wdievqxsxe):

> The webpages listed in the grey… files (greysitelist and greyurllist in 2.10) skip site (domain/host), path, and regular expression checks, but still do the “content” check.
> 
> If you want to see a webpage -unless it contains objectionable content such as proscribed phrases- list it in these files.

After adding yahoo.com to my greylist however, I noticed the hits are no longer logged. Is this expected? it seems like e2g should log all requests no matter what.

thanks,

Spike

**Comment by fredbcode** [comment]
It depends, which loglevel and exception log ?

**Comment by fredbcode** [comment]
From develop
<code>
# Logging Settings
#
# 0 = none  1 = just denied  2 = all text based  3 = all requests
loglevel = 1

# Log Exception Hits
# Log if an exception (user, ip, URL, phrase) is matched and so
# the page gets let through.  Can be useful for diagnosing
# why a site gets through the filter.
# 0 = never log exceptions
# 1 = log exceptions, but do not explicitly mark them as such
# 2 = always log & mark exceptions (default)
# 3 = always log & mark exceptions and hidden requests (like identifications)
logexceptionhits = 2
</code>

**Comment by spikedrba** [comment]
I should have pointed out, I'm doing loglevel=2 and logexceptionhits=2 so I'd expect them to be logged. am I wrong?

**Comment by fredbcode** [comment]
Yes, can you make a try with develop ?

**Comment by spikedrba** [comment]
I think this was a problem of my end, I'm trying to do too many things at once altho I still feel there's something strange going on I can't point my finger at. In any case, if I try to repro on a test instance with just my client I can't, the logs show up correctly. I've noticed that logs on a busy-ish systems with syslogs=true can be delayed for quite a few seconds, which I wouldn't think to be normal give the abundant free cpu and ram (and the disks are SSDs).

**as a wish list item, it would be good if grey list urls were marked as such, just like you have TRUSTED and DENIED, something to make it obvious that the url has been scanned, otherwise it's hard to tell if that's happening or not to begin with.**

thanks,

Spike
