### ISSUE TITLE
E2Guardian redirecting site to loopback? 

### ISSUE THREAD

**Issue by forid786** [e2guardian/e2guardian#275]
Trying to visit www.watchshop.com and I keep getting redirected to loopback (127.0.0.1). Initially I thought it was DNS related, checked everything and it's fine. I bypassed E2Guardian by setting squid as the proxy locally and the website loaded just fine.

When trying to access the site via E2Guardian on the real time logs I can see that it's giving a 301 response. I've even tried adding the site to E2Guardian's exclusion list but no joy. Can this please be looked into, not sure what's special about this site but it's causing E2Guardian to become confused somehow.

Here's some screenshots : https://image.prntscr.com/image/zXi1I0XvRqmtDnHpH2YuMw.png
https://image.prntscr.com/image/8aqll15EQ0uXw-d_K3LDSg.png

**Comment by forid786** [comment]
```

[2.3.4-RELEASE][root@pfSense.kortex]/root: e2guardian -v
e2guardian 4.1.3

Built with:  '--localstatedir=/var' '--with-logdir=/var/log' '--with-piddir=/var/run' '--with-zlib=/usr' '--enable-fancydm' '--disable-clamd' '--enable-commandline' '--enable-dnsauth' '--disable-email' '--disable-icap' '--disable-kavd' '--enable-ntlm' '--enable-sslmitm' '--enable-trickledm' '--prefix=/usr/local' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd10.3' 'build_alias=amd64-portbld-freebsd10.3' 'CXX=c++' 'CXXFLAGS=-O2 -pipe  -I/usr/local/include -D__SSLMITM -D__SSLCERT -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing  -DLIBICONV_PLUG -std=c++1y' 'LDFLAGS= -lssl -lcrypto -fstack-protector' 'LIBS=' 'CPPFLAGS=-I/usr/local/include -DLIBICONV_PLUG' 'CC=cc' 'CFLAGS=-O2 -pipe  -I/usr/local/include -D__SSLMITM -D__SSLCERT -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing' 'CPP=cpp' 'PKG_CONFIG=pkgconf'
[2.3.4-RELEASE][root@pfSense.kortex]/root:

```

**Comment by fredbcode** [comment]
Can you post your logs ? Squid + E2Guardian because we need more 
informations

Can you make a capture with wireshark? or with some plugins like Live 
HTTP Headers (for firefox)
I like to see the complete 301 response


<https://addons.mozilla.org/en-US/firefox/addon/live-http-headers/?src=search>

**Comment by spikedrba** [comment]
@forid786  was that happening on 4.1.2? that's what I'm using and I can't repro.

**Comment by fredbcode** [comment]
Works here

**Comment by forid786** [comment]
@spikedrba Haven't tried it on 4.1.2, will try to see what HTTP headers shows when I'm home.

Been really busy, sorry for the late response @fredbcode

**Comment by forid786** [comment]
Here's the Live HTTP Headers output @fredbcode 

`https://www.google.com/complete/search?client=firefox&q=wa

GET /complete/search?client=firefox&q=wa HTTP/1.1
Host: www.google.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: */*
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

HTTP/2.0 200 OK
date: Thu, 07 Sep 2017 20:19:15 GMT
pragma: no-cache
expires: -1
cache-control: no-cache, must-revalidate
content-type: text/javascript; charset=UTF-8
strict-transport-security: max-age=86400
content-disposition: attachment; filename="f.txt"
content-encoding: br
server: gws
content-length: 90
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
alt-svc: quic=":443"; ma=2592000; v="39,38,37,35"
X-Firefox-Spdy: h2
----------------------------------------------------------
http://www.watchshop.com/

GET / HTTP/1.1
Host: www.watchshop.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: PHPSESSID=sq6gl16mgp26usub7cs42rmjv7
Connection: keep-alive
Upgrade-Insecure-Requests: 1

HTTP/1.1 301 Moved Permanently
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Thu, 07 Sep 2017 20:19:16 GMT
Expires: -1
Last-Modified: Thu, 07 Sep 2017 20:19:16 GMT
Location: http://127.0.0.1
Pragma: no-cache
Server: Apache
Vary: Accept-Encoding
X-Frame-Options: sameorigin
Content-Length: 26
X-Cache: MISS from KorTeX_Smart_Filter
X-Cache-Lookup: MISS from KorTeX_Smart_Filter:3128
Via: 1.1 KorTeX_Smart_Filter (squid/3.5.26)
Connection: keep-alive
----------------------------------------------------------
`

**Comment by fredbcode** [comment]
Do you have some logs from e2guardian and Squid ?

**Comment by fredbcode** [comment]
Please share your squid.conf file

**Comment by fredbcode** [comment]
Closing this for now, please feel free to reopen if any updates

**Comment by forid786** [comment]
Sorry about the wait, life gets in the way... I've still got interest in this don't worry.

Here's my Squid.conf : https://ybin.me/p/0c5570e438e8212f#u+v+WA6uSOZ8Vwtosyy1UskYbngUmA4lWuHKF//FG0g=

The issue is still occurring...
