### ISSUE TITLE
handle excessive headers more gracefully and give better clues in the logs

### ISSUE THREAD

**Issue by spikedrba** [e2guardian/e2guardian#276]
Hi,

I just got bitten by the maxheaders limit being exceeded and my connections being killed with not much of an explanation.

I think it would be advisable to:
1) clearly report this in the logs, it took a long time to figure out this was the issue. Since e2g knows it should log it and say that maxheaders was exceeded and the connection killed
2) users get an unfriendly "502 Gateway timeout error" . It would be great if it was possible to give back a nicer error message, maybe using some customer template like for the block.

thanks,

Spike

**Comment by fredbcode** [comment]
Ok done 4.1.3 and v5
