### ISSUE TITLE
Exception whist reading ClamD socket: Can't read from socket: select() on input: timeout

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#277]
Hi,

When Clamav reload the virus definition database, E2guardian display on the screen this message:

Exception whist reading ClamD socket: Can't read from socket: select() on input: timeout

Is it possible or maybe there is an option in E2guardian to avoid this "problem"?

Fo example, is it possible to add a new option in E2guardian to display the webpage even if Clamav reload his database instead of display the timeout error message?

Thanks
Anthony

**Comment by fredbcode** [comment]
Do you have the skills to test the develop branch ? If yes I can take a look

**Comment by Anthony-76** [comment]
I will install de develop branch the next week.

Then, I will contact you to make tests.

**Comment by fredbcode** [comment]
Ok please wait the "go" before

**Comment by fredbcode** [comment]
@Anthony-76 Please, can you post the syslog returns when this "issue" occur 
I mean with your actual version

**Comment by Anthony-76** [comment]
Hi fredbcode,

Below, the syslog:

Sep 12 09:52:01 test e2guardian[9137]: Error connecting to ClamD socket
Sep 12 09:52:01 test e2guardian[9137]: Unknown return code from content scanner: -1
Sep 12 09:52:01 test e2guardian[9137]: Error connecting to ClamD socket
Sep 12 09:52:01 test e2guardian[9137]: Unknown return code from content scanner: -1

I use E2guardian 4.1.2.
Do you want that i test with the develop branch?

**Comment by fredbcode** [comment]
Not yet, I will add a new option this week, I'll keep you in touch

**Comment by Anthony-76** [comment]
Ok,

**Comment by fredbcode** [comment]
Ok I pushed a fix 
Please make a try with this new option in your group file:

https://github.com/e2guardian/e2guardian/blob/develop/configs/e2guardianf1.conf.in#L292

Please, try with on and off and report here the syslog messages

Thanks for your help

**Comment by Anthony-76** [comment]
ok,

I will try this today,

I will give you a feedback.

Thanks

**Comment by Anthony-76** [comment]
the syslog with disablecontentscanerror = on



Sep 12 11:14:01 sysun snmpd[10651]: error on subcontainer 'ia_addr' insert (-1)
Sep 12 11:14:02 sysun e2guardian[7662]: Error connecting to ClamD socket
Sep 12 11:14:02 sysun e2guardian[7662]: Unknown return code from content scanner: -1
Sep 12 11:14:02 sysun e2guardian[7662]: disablecontentscanerror is on : bypass actived USER: 172.16.100.2 URL: http://www.eicar.org/download/eicar.com.txt
Sep 12 11:14:07 sysun e2guardian[7662]: 49319 No header recd from client at 172.16.100.2 - errno: 0


The sylog with disablecontentscanerror = off

Sep 12 11:15:17 sysun e2guardian[8245]: Error connecting to ClamD socket
Sep 12 11:15:17 sysun e2guardian[8245]: Unknown return code from content scanner: -1
Sep 12 11:15:17 sysun e2guardian[8245]: Error connecting to ClamD socket
Sep 12 11:15:17 sysun e2guardian[8245]: Unknown return code from content scanner: -1


It seems good for me

**Comment by fredbcode** [comment]
Ok great, fixed
