### ISSUE TITLE
HTTP 301

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#278]
Hi,

When I tried to go to the http://www.travail.gouv.fr  website, I have an error 301

This is my log:
2017.10.3 9:43:19 - 192.168.100.137 http://www.travail.gouv.fr - GET 0 0 - 1 301 - -

So, If i add gouv.fr in whitelist, I can visit this webpage.

Maybe it's the same issue than #275 

If you want, I can make tests and debugs

Best regards
Anthony

**Comment by fredbcode** [comment]
Which version ?

Works here

**Comment by Anthony-76** [comment]
I use 4.1.2 release

**Comment by fredbcode** [comment]
http://www.travail.gouv.fr is redirected to
http://travail-emploi.gouv.fr/ (code 301)

Without problem 

Do you see a request to http://www.travail.gouv.fr ?

**Comment by Anthony-76** [comment]
So, When I tried to go to visit the http://www.travail.gouv.fr , I have only the "GET 0 0 - 1 301 - -" in my log.

I'm not redirected on http://travail-emploi.gouv.fr/  with my browser.
It's work if I put ".gouv.fr" in whitelist

**Comment by fredbcode** [comment]
What rules are you using ?

It's not at all the same domain, so "travail-emploi" must be also allowed  

What happen when you try http://travail-emploi.gouv.fr directly ?

**Comment by fredbcode** [comment]
This is from Squid ? 2017.10.3 9:43:19 - 192.168.100.137 http://www.travail.gouv.fr - GET 0 0 - 1 301 - -
If yes, do you have logs from E2 ?

**Comment by Anthony-76** [comment]
The log that I posted come from E2

**Comment by Anthony-76** [comment]
Here the log from squid:

**Comment by Anthony-76** [comment]
Ok,

I make a new test:


The redirect to  http://travail-emploi.gouv.fr appear about 15 seconds after to go to http://www.travail.gouv.fr/.


With the High load on system, E2 can't inspect all webpages in "real time" . This is add more time to redirect and the browser dispaly me a timeout....

**Comment by fredbcode** [comment]
Can you make a wireshark trace betwen the browser and e2 ? You log the denied requests ?
What happen when you try http://travail-emploi.gouv.fr directly in your browser ?

**Comment by fredbcode** [comment]
Ok can you make a "top" and post the result here

**Comment by Anthony-76** [comment]
the http://travail-emploi.gouv.fr access works fine.

Just for information, by unlucky, in the same time Clamav crashed.
This is why in add the website in withlist, it had worked....

sorry to open this ticket.

I close it
Best regards
