### ISSUE TITLE
Broken link in Wiki page

### ISSUE THREAD

**Issue by Atavic** [e2guardian/e2guardian#287]
First link on Wiki page [Using your new shiny content filter](https://github.com/e2guardian/e2guardian/wiki/Installation-on-Ubuntu-or-Debian#using-your-new-shiny-content-filter) seems broken, the working one is:
https://support.mozilla.org/en-US/kb/advanced-panel-settings-in-firefox

**Comment by spikedrba** [comment]
thank you for the report @Atavic , I fixed the wiki using the correct link you provided (to be precise I linked the specific proxy settings page linked off of the one you mentioned). thanks.
