### ISSUE TITLE
4.1.3 / Probrem with htmltemplate parameters

### ISSUE THREAD

**Issue by men-chris** [e2guardian/e2guardian#289]
Since the installation of version 4.1.3, the "htmltemplate" parameter no longer works correctly:

```
Oct 24 17:35:04 pp-proxy e2guardian [9816]: error reading HTML template file.
Oct 24 17:35:04 pp-proxy e2guardian [9816]: Error reading HTML Template file: /usr/share/e2guardian/languages/ukenglish/men.html
Oct 24 17:35:04 pp-proxy e2guardian [9816]: Error opening the filter group config: /etc/e2guardian/e2guardianf1.conf
Oct 24 17:35:04 pp-proxy e2guardian [9816] Error!
Oct 24 17:35:04 pp-proxy e2guardian [9816]: Reconfiguring E2guardian: gentle reload failed
```

The file are here: /etc/e2guardian/languages/french/men.html

And in the "e2guardian.conf" there are:

```
languagedir = '/ usr / share / e2guardian / languages'
language = 'french'
```

It's a bug?

**Comment by fredbcode** [comment]
Hum did you see that /usr/share/e2guardian/languages/ukenglish/men.html  - ukenglish ? -

languagedir = '/ usr / share / e2guardian / languages'

There are spaces, wrong copy/past or not ?


----- Mail original -----

**Comment by men-chris** [comment]
There are no space, it's just a wrong copy :)

In "e2guardian.conf" there are : 

```
languagedir = '/usr/share/e2guardian/languages'
language = 'french'
```

And e2guardian search the custom file in : 

`/usr/share/e2guardian/languages/ukenglish/men.html`

In previous versions it was good.

On server : 
```
# ll /usr/share/e2guardian/languages/ukenglish
total 68
-rwxr-xr-x 1 root root  6293 juil. 18 17:00 fancydmtemplate.html
-rw-r--r-- 1 root root  3946 juil. 18 17:00 messages
-rw-r--r-- 1 root root  3680 juil. 18 17:00 messages.alt
-rwxr-xr-x 1 root root 50027 juil. 18 17:00 template.html
```

**Comment by fredbcode** [comment]
Do you have a french directory ? /usr/share/e2guardian/languages/french ?

**Comment by men-chris** [comment]
Yes, with my custom page : 

```
# ll /usr/share/e2guardian/languages/french
total 136
-rw-r--r-- 1 e2guardian e2guardian 58740 oct.  25 10:22 dm_men.html
-rwxr-xr-x 1 e2guardian e2guardian  6605 juil. 18 17:00 fancydmtemplate.html
-rw-r--r-- 1 e2guardian e2guardian 55149 oct.  25 10:22 men.html
-rwxr-xr-x 1 e2guardian e2guardian  6310 juil. 18 17:00 messages
-rwxr-xr-x 1 e2guardian e2guardian  2628 juil. 18 17:00 template.html
```

**Comment by fredbcode** [comment]
it works here 

# The language file is used no matter what setting however.
languagedir = '/etc/e2guardian/languages'
# language to use from languagedir.
language = 'french'

It's like "language = 'french'" is not read at all, maybe you have this value twice ?
Can you try: 
grep "language" /etc/e2guardian/*

**Comment by men-chris** [comment]
Ok, I found the problem : 

in e2guardian.conf I change :  

`#languagedir = '/usr/share/e2guardian/languages'`

by 

`languagedir = '/etc/e2guardian/languages/'`

And copy my custom files here.

This is the value of version 3.5

Thank for your help !
