### ISSUE TITLE
4.1.3 / Problem when using Fancy download manager

### ISSUE THREAD

**Issue by men-chris** [e2guardian/e2guardian#290]
Since switching to version 4, I'm having problems with Fancy download manager : 

When I download a large file (630 MB), Fancy downloads the file, analyzes it but when you click on the link for download it locally, the system downloads the file again for analysis ...

In addition, the temporary files on the server are not deleted, while the configuration requires it : 

```
# ll /tmp
total 1325076
-r--r----- 1 e2guardian e2guardian 678428672 oct.  25 11:56 tfCx93dC
-r--r----- 1 e2guardian e2guardian 678428672 oct.  25 11:58 tfTtp01G
```

This are no problem with smaller files (64 MB for example).

To test, I use this site for download different files : http://test-debit.free.fr/

My configuration are : 

**e2guardian.conf :** 
```
maxcontentfilecachescansize = 2048000
downloadmanager = '/etc/e2guardian/downloadmanagers/fancy.conf'
filecachedir = '/tmp'
```

**fancy.conf :** 
```
plugname = 'fancy'
useragentregexp = 'mozilla'
maxdownloadsize = 2048000
```

Is there a problem with my configuration or a bug?

**Comment by fredbcode** [comment]
Can you make a try with default downloadmanager ?
https://github.com/e2guardian/e2guardian/blob/master/configs/e2guardian.conf.in#L414

**Comment by fredbcode** [comment]
Yes, this is an old part of dansguardian.
If I can I will take a look, probably this part should be removed ...

Le 25 octobre 2017 17:10:20 GMT+02:00, men-chris <notifications@github.com> a écrit :
>Yes without Fancy, with default downloadmanager only : 
>
>```
>#downloadmanager = '/etc/e2guardian/downloadmanagers/fancy.conf'
># downloadmanager = '/etc/e2guardian/downloadmanagers/trickle.conf'
>downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
>
>```
>The download file test (http://test-debit.free.fr/image.iso for
>exemple) work ! Download complete, and delete automatically the
>temporary file.
>
>so the problem comes from Fancy?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/290#issuecomment-339362953

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by men-chris** [comment]
Great, thank you !
