### ISSUE TITLE
Certificate supplied by server was not valid: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ILoveMuffins** [e2guardian/e2guardian#295]
Hi folks,

I'm trying to run e2guardian, I installed it on Debian with dpkg. Some ssl sites like stackoverflow working correctly, but other like google.com do not, because of this error. e2guardian version 4.1.3. Tested with Firefox 52.4.0
I think I need help with this

**Comment by philipianpearce** [comment]
See notes/certificate_errors for help on this.

The github issues is for bugs, not for general help.

If you need further help, please post to the community e2guardian group e2guardian@googlegroups.com
