### ISSUE TITLE
Custom page for https forbidden site

### ISSUE THREAD

**Issue by men-chris** [e2guardian/e2guardian#297]
I have a question about the custom page when accessing a forbidden site in https

In e2guardianfX.conf : 

`sslaccessdeniedaddress = 'https://myserver.mydomain.fr/acces-refuse.html'`

but it only works with Firefox.

Is there a setting to make this behavior functional with IE, Chrome, or Edge?

I have e2guardian 4.1.3 version.

Thank you !

**Comment by fredbcode** [comment]
Yes by default it's only for Firefox, there is an option for all browsers but a SSL error is generated.

If you need further help, please post to the community e2guardian group e2guardian@googlegroups.com

Github must be used for bug reports only

Le 31 octobre 2017 12:12:25 GMT+01:00, men-chris <notifications@github.com> a écrit :
>I have a question about the custom page when accessing a forbidden site
>in https
>
>In e2guardianfX.conf : 
>
>`sslaccessdeniedaddress =
>'https://myserver.mydomain.fr/acces-refuse.html'`
>
>but it only works with Firefox.
>
>Is there a setting to make this behavior functional with IE, Chrome, or
>Edge?
>
>Thank you !
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/297

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by men-chris** [comment]
Ok sorry !
