### ISSUE TITLE
exceptionsitelist cannot override localbannedsitelist  when http request and ** Blanket Block

### ISSUE THREAD

**Issue by VasiliyF** [e2guardian/e2guardian#299]
I have some sites in exceptionsitelist and ** blanket exceptions in localbannedsitelist. When I try access https-site (those in  exceptionsitelist) - access granted, but when the same http-site - access denied ('Walled Garden is on...' message) .
localexceptionsitelist is empty, SSLMITM is on.

**Comment by fredbcode** [comment]
Still present, which version ?

**Comment by philipianpearce** [comment]
Closed as no response for some months.  Also, blanket block function has changed in V5.
