### ISSUE TITLE
build with prefix=/usr/local breaks man page install

### ISSUE THREAD

**Issue by cweimann** [e2guardian/e2guardian#30]
I think the problem is the $(transform) step which prepends /usr/local.  When prefix is set to /usr/local this is not needed. 

I fixed this in both doc/Makefile.in and src/Makefile.in in order to successfully install.

# ./configure --program-prefix=/usr/local 
# make
[snip]
# make install
Making install in doc
test -z "/usr/local/share/doc/e2guardian" || /usr/home/andmore/develop/e2guardian/install-sh -d "/usr/local/share/doc/e2guardian"
 /usr/bin/install -c -m 644 'AuthPlugins' '/usr/local/share/doc/e2guardian/AuthPlugins'
 /usr/bin/install -c -m 644 'ContentScanners' '/usr/local/share/doc/e2guardian/ContentScanners'
 /usr/bin/install -c -m 644 'DownloadManagers' '/usr/local/share/doc/e2guardian/DownloadManagers'
 /usr/bin/install -c -m 644 'FAQ' '/usr/local/share/doc/e2guardian/FAQ'
 /usr/bin/install -c -m 644 'FAQ.html' '/usr/local/share/doc/e2guardian/FAQ.html'
 /usr/bin/install -c -m 644 'Plugins' '/usr/local/share/doc/e2guardian/Plugins'
test -z "/usr/local/man/man8" || /usr/home/andmore/develop/e2guardian/install-sh -d "/usr/local/man/man8"
 /usr/bin/install -c -m 644 './e2guardian.8' '/usr/local/man/man8//usr/locale2guardian.8'
install: /usr/local/man/man8//usr/locale2guardian.8: No such file or directory
*** Error code 71

Stop in /usr/home/andmore/develop/e2guardian/doc.
*** Error code 1

Stop in /usr/home/andmore/develop/e2guardian/doc.
*** Error code 1

Stop in /usr/home/andmore/develop/e2guardian.

**Comment by fredbcode** [comment]
Fixed (dev branch)

**Comment by fredbcode** [comment]
Fixed 3.2.0
