### ISSUE TITLE
Need to restrict log file permissions

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#300]
e2guardian logs are generally sensitive information.  Permissions need to be restricted - currently they are world readable.

**Comment by fredbcode** [comment]
You mean with the debian package ?

----- Orion Poplawski <notifications@github.com> a écrit :

**Comment by opoplawski** [comment]
This is with an rpm that I've built.

**Comment by fredbcode** [comment]
So maybe I misunderstand, but the issue is with this package ? Or there is something wrong with our make script ?
As far I can remember there is nothing specific in code, this is an implementation problem, no ?

**Comment by opoplawski** [comment]
There should be an option in the code to specify the permissions of the log files when they are created.  Although it can be mitigated by using UMask in the systemd service file like:
```
[Unit]
Description=E2guardian Web filtering
After=network.target

[Service]
LimitNOFILE=65535
Type=simple
IgnoreSIGPIPE=no
ExecStart=/usr/sbin/e2guardian -N
ExecReload=/usr/sbin/e2guardian -r
Restart=always
UMask=027

[Install]
WantedBy=multi-user.target
```

**Comment by fredbcode** [comment]
Ok I will add this value in systemd, but I prefer let the choice for admin ...

**Comment by fredbcode** [comment]
Done in v4.4.1 need check in v5 before close

**Comment by fredbcode** [comment]
ok done
