### ISSUE TITLE
Feature Request: greyregexpurllist missing

### ISSUE THREAD

**Issue by michaelbaecker** [e2guardian/e2guardian#301]
Hello,

We want to implement a whitelist only proxy server. But one feature is missing for our environment.

We have to implement a method that requires a regexp urllist in the greylisting. 

That feature, as far as we know, was in dansguardian, but seems to be missing in e2guardian

Thanks for reading

Michael

**Comment by fredbcode** [comment]
You mean banned regex ?

If yes there is bannedregexwithblanketblock

**Comment by michaelbaecker** [comment]
Let me try to explain, what we are doing:
- We block all IP base URLs
# bannedsitelist
**
**s
*ip
*ips

- We greylist some URLs, which contain IPs for "android connectivity check" 
# greyurllist
172.217.22.195/generate_204
...
- We redirect every generate_204 request to a local webserver to generate the 204 response code:
# urlregexplist
"(^http://.*/generate_204$)"->"http://ourwebserver/generate_204.php"

Then the tablets think, that they are connected to the internet. But they only have access to our whitelisted sites.

Our problem is from time to time there occur new URLs for the generate_204 request and there is nearly no documentation on this feature.

When we use the feature exceptionregexpurllist, then the urlregexplist isn't processed. 

If there are any other suggestions, you are welcome!

Michael

**Comment by fredbcode** [comment]
Yes I see, it worked before ?
