### ISSUE TITLE
Client IP address is missing with squid format logs

### ISSUE THREAD

**Issue by men-chris** [e2guardian/e2guardian#302]
When the log format is enabled to use the squid format in e2guardian.conf:

loglevel = 3
logexceptionhits = 3
logfileformat = 3

The IP address of the client machine is not present in the logs:

1510757523.530     53 - TCP_MISS/200 471 POST http://ocsp.digicert.com usertest DEFAULT_PARENT/127.0.0.1 application/ocsp-response
1510757523.534     54 - TCP_MISS/200 471 POST http://ocsp.digicert.com usertest DEFAULT_PARENT/127.0.0.1 application/ocsp-response
1510757584.067  60907 - TCP_MISS/200 3264 CONNECT https://incoming.telemetry.mozilla.org:443 usertest DEFAULT_PARENT/127.0.0.1 -
1510757584.067  60909 - TCP_MISS/200 3264 CONNECT https://incoming.telemetry.mozilla.org:443 usertest DEFAULT_PARENT/127.0.0.1 -

Still, if I enable the dansguardian mode:

logfileformat = 4 (tab delimited)

The IP address is visible:

2017.11.15 11:55:37 usertest 172.X.X.X https://versioncheck-bg.addons.mozilla.org:443 - CONNECT 4799 0 - 1 200 - - preprod - - - - -
2017.11.15 11:55:38 usertest 172.X.X.X https://aus5.mozilla.org:443 - CONNECT 3468 0 - 1 200 - - preprod - - - - -
2017.11.15 11:56:32 usertest 172.X.X.X https://services.addons.mozilla.org:443 - CONNECT 7354 0 - 1 200 - - preprod - - - - -
2017.11.15 11:56:36 usertest 172.X.X.X http://ocsp.digicert.com *SCANNED* - POST 471 0 - 1 200 application/ocsp-response - preprod - - - - application/ocsp-request,,83,0,,0;

Is this a bug?

**Comment by fredbcode** [comment]
Fixed on develop: 

1511791931.019  49962 10.1.1.1 - TCP_MISS/200 4041 CONNECT https://db5sch101101228.wns.windows.com:443 johndoe DEFAULT_PARENT/127.0.0.1 -

**Comment by fredbcode** [comment]
Fixed on 4.1.4, must check on V5 before close

**Comment by fredbcode** [comment]
ok done
