### ISSUE TITLE
URL with no scan result

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#303]
Hello,

I found something strange in my e2guardian access.log, maybe it's not a problem but I don't know how to interpret it :

sometimes there is some URL with no scan result, so I don't know if the request had been blocked or accepted by e2guardian. Here's some example of similar requests, some with scan results (SCANNED), and other without :

2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-s11_2x.jpg *SCANNED* - GET 39678 0 - 1 200 image/jpeg -  - - - - -
**2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-ttl_s12_2x.png - GET 5573 0 - 1 200 image/png -  - - - - -
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-ttl_s14_2x.png - GET 2447 0 - 1 200 image/png -  - - - - -
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-ttl_s13_2x.png - GET 9480 0 - 1 200 image/png -  - - - - -
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/s.gif - GET 43 0 - 1 200 image/gif -  - - - - -
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-ttl_s2_2x.png - GET 5221 0 - 1 200 image/png -  - - - - -**
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-s21_2x.jpg *SCANNED* - GET 17123 0 - 1 200 image/jpeg -  - - - - -
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-s24_2x.jpg *SCANNED* - GET 15373 0 - 1 200 image/jpeg -  - - - - -
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-s22_2x.jpg *SCANNED* - GET 46824 0 - 1 200 image/jpeg -  - - - - -
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-s23_2x.jpg *SCANNED* - GET 41828 0 - 1 200 image/jpeg -  - - - - -
**2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-ttl_s3_2x.png - GET 6056 0 - 1 200 image/png -  - - - - -
2017.11.16 14:08:58 - 172.16.X.X http://images.apple.com/cbx/eu/17/11/4675/v1/fr/i/m-ttl_s25_2x.png - GET 5218 0 - 1 200 image/png -  - - - - -**

Do you know how to interpret these URL requests ?

Regards,

Anthony

**Comment by fredbcode** [comment]
Maybe I'm wrong, but it's always the same type of files 
Do you have one png files scanned ? If not I guess there is an exclusion somewhere in your rules 

----- Mail original -----

**Comment by Anthony-76** [comment]
Oh yes you're right !
image/png and image/gif where by default included in the extensionmimetypelist and extensionlist !

Thanks !

Anthony
