### ISSUE TITLE
User do not uses right filter group (/etc/e2guardian/lists/authplugins/ipgroups)

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#304]
Hi,

I have the following /etc/e2guardian/lists/authplugins/ipgroups file

192.168.23.1-192.168.23.254=filter1
192.168.24.1-192.168.24.25=filter2
10.2.35.1-10.2.35.254=filter3
10.2.34.1-10.2.34.254=filter4
192.168.102.1-192.168.102.254=filter5
172.16.21.1-172.16.21.250=filter6
172.16.20.1-172.16.20.254=filter7
172.16.22.1-172.16.22.254=filter8
172.16.23.1-172.16.23.254=filter9
169.254.4.20-169.254.4.20=filter10
172.16.24.1-172.16.24.254=filter11
10.64.147.1-10.64.147.254=filter12

I made differents whitelists/blacklists by filter.

On each filter, I put windowsupdate.com in blacklist.

Then I delete a windowsupdate entrie in blacklist of filter11 file, computers in 172.16.24.1-172.16.24.254 ip range can't download from windowsupdate.com

It works only if I put windowsupdate.com in lists_filter1/exceptionsitelist file

It seems that all ip range of all filter works with filter1 only.

Why?
Is it a mistake of my part ?(In release 3.5, I have no error)

Best regards
Anthony

**Comment by fredbcode** [comment]
> It works only if I put windowsupdate.com in
> lists_filter1/exceptionsitelist file

group 1 is the default group, when a user is not know -> group1

So if I understand right your issue, IP plug-in doesn't authenticate your users ?

**Comment by Anthony-76** [comment]
Right, IP plugin seems put all users in filter1.

**Comment by fredbcode** [comment]
Quickly tested here, works

1) I put my address to ipgroups as filter 3
2) I enabled IP authentication as first method in e2guardian.conf

I'm denied/allowed like a filter 3 user

  
 



----- Mail original -----

**Comment by Anthony-76** [comment]
Ok, I will make new tests

**Comment by Anthony-76** [comment]
oh..... I make a mistake......

The authplugin = '/etc/e2guardian/authplugins/ip.conf line was commented in e2guardian.conf.

Sorry for my mistake.

Best regards
Anthony
