### ISSUE TITLE
HTTPS Filtering without using MITM (Based on Server Name)

### ISSUE THREAD

**Issue by drop2kumar** [e2guardian/e2guardian#305]
Hi, 

Can I filter HTTPS page without using MITM? 
Though we can not see complete URL, we can see Server Name while establishing TLS connection. 
Privoxy claims they can do it. But I am using E2Guardian and want to know how to make it work?

Thanks in advance.

Kumar M.

**Comment by fredbcode** [comment]
Please do not use the issue tracker for asking questions, use the group
