### ISSUE TITLE
v5develop: sslsiteregexplist

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#307]
SSL regex list not working

Contents of sslsiteregexplist:
"(^https://www.youtube.com)"->"https://restrict.youtube.com"
"(^https://m.youtube.com)"->"https://restrict.youtube.com"
"(^https://youtubei.googleapis.com)"->"https://restrict.youtube.com"
"(^https://youtube.googleapis.com)"->"https://restrict.youtube.com"
"(^https://www.youtube-nocookie.com)"->"https://restrict.youtube.com"

Debug:
...
/etc/e2guardian/lists/sslsiteregexplist
Compiling ^.*\:[0-9]+\/.*
...with PCRE 
Compiling (^https://www.youtube.com)
...with PCRE 
Compiling (^https://m.youtube.com)
...with PCRE 
Compiling (^https://youtubei.googleapis.com)
...with PCRE 
Compiling (^https://youtube.googleapis.com)
...with PCRE 
Compiling (^https://www.youtube-nocookie.com)
...with PCRE 
...
inRegExpURLList: https://www.youtube.com
inRegExpURLList (processed): www.youtube.com
SB state sitein target www.youtube.com target2 www.youtube.com state_result 0 list_check 1 isSearch 0

(full debug log attached)
[1.txt](https://github.com/e2guardian/e2guardian/files/1516798/1.txt)

Also sslsiteregexplist is missing from Makefile.am in the configs/list directory.  And bannedsitelist.in as well as bannedsitelist exist in the same directory.

**Comment by fredbcode** [comment]
Which version ?

**Comment by fredbcode** [comment]
I think you are speaking about v5develop, please add a tag like [v5develop] or be more explicit in your description.

**Comment by philipianpearce** [comment]
Fixed in latest v5develop.    Note that you will need to compile new binary and use the revised common.story to enable correct working.
