### ISSUE TITLE
v5develop: icap ssl

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#309]
What is the correct configuration for icap to handle ssl configuration.

Using squid with the following -
http_port 3130  ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB cert=/home/xxx/Root-ca.crt key=/home/xxx/Root-ca.key

e2guardian -
enablessl = on
sslmitm = off
sslcertcheck = off

curl -k -x https://127.0.0.1:3130 -L https://www.google.com gives a malformed url 400 error.

icap is setup properly, as I can do curl -k -x https://127.0.0.1:3128 -L http://www.asdf.com without issue.

Attached is log showing the malformed header response
[log.txt](https://github.com/e2guardian/e2guardian/files/1529387/log.txt)

**Comment by fredbcode** [comment]
Maybe I missed something but google still cipher in your trace, so I guess there is something wrong with Squid.
With SSLBump e2guardian must only see HTTP requests

Here, I'm testing ICAP with HTTP and HTTPS requests (No SSLBump) and it works well
Can you try with SSLBump disabled for beginning 

Are you using the latest push from Phillip ?

**Comment by philipianpearce** [comment]
Looking at trace it seems that squid has bumped SSL and is sending a ICAP request with a HTTP non-standard request of GET https://www.google.com HTTP/1.1

I have attempted to fix http 400 error return. 
Please re-test with latest v5develop.

**Comment by fredbcode** [comment]
@PhilCode4U Please check asap, thanks

**Comment by PhilCode4U** [comment]
Hi,
I tried and i have no problem, it works.
try with enablessl = off in e2guardian and with the latest v5develop
I think it's the problem

**Comment by fredbcode** [comment]
Philip before we close, I'm seeing something wrong
With a denied page (website) we have a blank page, the redirection is broken
Same issue with template.html 

Of course I'm speaking with Squid SSLBump

**Comment by philipianpearce** [comment]
Fred/Phil,

Can you send me a e2g debug trace for the blank page, redirection broken problem?
