### ISSUE TITLE
v5develop: Naughtyfilter.hpp compile error

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#310]
I've been compiling v5develop for a while and always had to modifiy NaughtFilter.hpp to uncomment #include "HTTPHeader.hpp" in NaughtyFilter.hpp.  NaughtFilter.hpp uses HTTPHeader (as we as deque) which are defined by HTTPHeader.hpp.  See compilation error below.

x86_64-openwrt-linux-musl-g++ -DHAVE_CONFIG_H -I. -I..  -D__CONFFILE='"/etc/e2guardian/e2guardian.conf"' -D__LOGLOCATION='"/var/log/e2guardian/"' -D__PIDDIR='"/tmp/e2guardian/"' -D__PROXYUSER='"nobody"' -D__PROXYGROUP='"nogroup"' -D__CONFDIR='"/etc/e2guardian"'  -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/usr/include -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/include/fortify -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/toolchain-x86_64_gcc-5.4.0_musl/include  -I/home/dbrody/bamboo-data/xml-data/build-dir/CON-LEDE-JOB1/staging_dir/target-x86_64_musl/usr/include  --std=c++11  -DFD_SETSIZE=65535 -MT contentscanners/e2guardian-clamdscan.o -MD -MP -MF contentscanners/.deps/e2guardian-clamdscan.Tpo -c -o contentscanners/e2guardian-clamdscan.o `test -f 'contentscanners/clamdscan.cpp' || echo './'`contentscanners/clamdscan.cpp
In file included from contentscanners/../ContentScanner.hpp:11:0,
                 from contentscanners/clamdscan.cpp:14:
contentscanners/../NaughtyFilter.hpp:48:10: error: 'deque' in namespace 'std' does not name a template type
     std::deque<String> embededURLs;
          ^
contentscanners/../NaughtyFilter.hpp:49:10: error: 'deque' in namespace 'std' does not name a template type
     std::deque<url_rec> reversedURLs;
          ^
contentscanners/../NaughtyFilter.hpp:51:5: error: 'HTTPHeader' does not name a type
     HTTPHeader* request_header;
     ^
contentscanners/../NaughtyFilter.hpp:52:5: error: 'HTTPHeader' does not name a type
     HTTPHeader* response_header;
     ^
contentscanners/../NaughtyFilter.hpp:56:5: error: 'RegExp' does not name a type
     RegExp ch_isiphost;
     ^
contentscanners/../NaughtyFilter.hpp:57:5: error: 'RegResult' does not name a type
     RegResult Rch_isiphost;
     ^
contentscanners/../NaughtyFilter.hpp:62:10: error: 'deque' in namespace 'std' does not name a template type
     std::deque<url_rec> deep_urls;
          ^
contentscanners/../NaughtyFilter.hpp:154:30: error: expected ')' before '&' token
     NaughtyFilter(HTTPHeader &request, HTTPHeader &response);

**Comment by philipianpearce** [comment]
OK, thanks for the info.
Corrected in latest v5develop.
