### ISSUE TITLE
SSL cert check

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#311]
In a non-e2guardian environment, a browser when visiting a site with an invalid SSL cert (expired, ca signed, etc) will alert the user and give an option to continue.

In a e2guardian SSL MITM environment, we have the option to sslcertcheck = on which checks whether the ca is signed.  If it is not (not sure if it does anything else other than checking the ca), it halts.  Is there a way to allow give the user the ability to proceed instead of just halting.  Maybe perhaps with squid?  With sslcertcheck=off and the e2guardian root ca installed, this gives the user a false sense that the original cert is valid.

**Comment by philipianpearce** [comment]
Note that sslcertcheck flag is not a MITM flag. It only affects SSL sites which are NOT MITM where certs as passed through to the user browser 'as is'. So ' With sslcertcheck=off and the e2guardian root ca installed, this gives the user a false sense that the original cert is valid.' is not the case. With sslcertcheck=off and mitm off the cert is passed through to the users browser for check in the normal way, whether or not the e2g root ca is installed. 

When a site is MITM the sslcheckcert setting is ignored. In MITM you use mitmcheckcert which by default is 'on' and is recommended to be always 'on'. 

The e2guardian MITM model is designed specifically to move the decision on whether to allow a 'bad' cert through away from the user to the e2g administrator who is able to put 'self-signed' etc, sites which they want to allow access into the nocheckcertsitelist. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
Below is the segement of e2guardianf1.conf.  It specifies mitmcheckcert=off, but v5develop appears to be checking nocheckcertsitelist as it gives the following error on https://zimbio.com - "Server%27s SSL certificate does not match domain name".  Also %27 should be ' but isn't in the message.

------

#NOTE to enable SSL MITM or CERT checking                                          
# enablessl must be defined as 'yes' in e2guardian.conf                     
                                                                            
#SSL certificate checking                                                   
# Check that ssl certificates for servers on https connections are valid     
# and signed by a ca in the configured path                                 
sslcertcheck = off                                                          
                                                                                 
#SSL man in the middle                                                      
# Forge ssl certificates for all non-exception sites, decrypt the data then re encrypt it
# using a different private key. Used to filter ssl sites                                
sslmitm = on                                                                             
                                                                                         
#Limit SSL MITM to sites in greysslsitelist(s)                                           
# ignored if  sslmitm is off                                                             
# SSL sites not matching greysslsitelist will be treat as if sslmitm is off.             
# The following option is replaced by storyboard logic                                   
#onlymitmsslgrey = off                                                                   
                                                                                         
# Enable MITM site certificate checking                                                  
# ignored if  sslmitm is off                                                             
# default (recommended) is 'on'                                                          
mitmcheckcert = off                                                                      
                                                                                         
#Do not check ssl certificates for sites listed                             
# Can be used to allow sites with self-signed or invalid certificates       
# or to reduced CPU load by not checking certs on heavily used sites (e.g. Google, Bing)
# Use with caution!                                                                     
# Ignored if mitmcheckcert is 'off'                                                     
#nocheckcertsitelist = '/etc/e2guardian/lists/nocheckcertsitelist'                      
sitelist = 'name=nocheckcert,path=/etc/e2guardian/lists/nocheckcertsitelist'

**Comment by philipianpearce** [comment]
mitmcheckcert=off was not being actioned in v5. I have pushed fix for this to v5develop. 

I will look at the issue of hex encoding in messages separately - this may be related to outstanding bug #204. 

dbrody2004 - Many thanks for your input. 

Regards 

Philip 

----- Original Message -----
