### ISSUE TITLE
v5develop: Compile errors on FreeBSD 11.1

### ISSUE THREAD

**Issue by robotman3000** [e2guardian/e2guardian#316]
When compiling on FreeBSD (for use in pfSense), I get the following error:

ConnectionHandler.cpp:376:26: error: use of undeclared identifier 'EAI_NODATA'
                    case EAI_NODATA:
                         ^
ConnectionHandler.cpp:2200:24: error: cast from pointer to smaller type 'char' loses information
                p[j] = (char)NULL;
                       ^~~~~~~~~~

I then went into the source of  ConnectionHandler.cpp and commented out the bad case statement
and replaced the `p[j] = (char)NULL;` with `p[j] = 0;`. This fixed these problems, however there were more errors:

CertificateAuthority.cpp:45:18: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
        while (e = ERR_get_error()) {
               ~~^~~~~~~~~~~~~~~~~
CertificateAuthority.cpp:45:18: note: place parentheses around the assignment to silence this warning
        while (e = ERR_get_error()) {
                 ^
               (                  )
CertificateAuthority.cpp:45:18: note: use '==' to turn this assignment into an equality comparison
        while (e = ERR_get_error()) {
                 ^
                 ==
CertificateAuthority.cpp:136:16: error: variable has incomplete type 'EVP_MD_CTX' (aka 'evp_md_ctx_st')
    EVP_MD_CTX mdctx;
               ^
/usr/local/include/openssl/ossl_typ.h:92:16: note: forward declaration of 'evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
CertificateAuthority.cpp:474:29: error: member access into incomplete type 'EVP_PKEY' (aka 'evp_pkey_st')
    CRYPTO_add(&_certPrivKey->references, 1, CRYPTO_LOCK_EVP_PKEY);
                            ^
/usr/local/include/openssl/ossl_typ.h:93:16: note: forward declaration of 'evp_pkey_st'
typedef struct evp_pkey_st EVP_PKEY;
               ^
CertificateAuthority.cpp:474:46: error: use of undeclared identifier 'CRYPTO_LOCK_EVP_PKEY'
    CRYPTO_add(&_certPrivKey->references, 1, CRYPTO_LOCK_EVP_PKEY);

I don't know if any of the errors in the second set are caused by missing libraries, but I wouldn't expect that since the configure script ran fine. Let me know if you need more information to debug this.

**Comment by philipianpearce** [comment]
@robotman3000 

What version of OpenSSL are you using? 

Regards 

Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
Yes, a number of macros in OpenSSL v1.1 are removed and/or have changed function. 

Regards 

Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
I am using gcc v5.4.0. 


Try p[j] = '\0'; 


I will also change to this in v5develop as this is more correct than using (char)NULL 


Regards 

Philip 

----- Original Message -----

**Comment by robotman3000** [comment]
Ok that will be great, thanks.

**Comment by robotman3000** [comment]
What are you planning to do with the compile error about `EAI_NODATA`? It appears it was deprecated and removed in freebsd a long time ago, about 2003. Take a look at [this link](https://lists.freebsd.org/pipermail/freebsd-ports/2003-October/005757.html) and [this one](https://github.com/eventlet/eventlet/issues/393).

**Comment by philipianpearce** [comment]
Thanks - Fixed in latest v5develop. Still current in linux so I have added #ifdef EAI_NODATA round the code. 

Regards 

Philip 

----- Original Message -----

**Comment by robotman3000** [comment]
I'm closing this issue because the compile errors I was experiencing have been fixed.

**Comment by robotman3000** [comment]
Thanks for the help
