### ISSUE TITLE
v5develop: Segmentation fault on FreeBSD from client request 

### ISSUE THREAD

**Issue by robotman3000** [e2guardian/e2guardian#318]
Every time a client connects e2guardian exits with signal 11. I have tried with and without sslmitm and using HTTP and HTTPS. Same result. I am using commit 6fd87372db088e01ffcf1e336a797f808f05bcd7 which as of writing is the latest one. If it's useful these are the configure parameters I am using:
`./configure --localstatedir=/var --enable-static zlib=yes --enable-pcre=yes --enable-segv-backtrace --enable-clamd=yes --enable-avastd=no --enable-icap=yes --enable-kavd=no --enable-commandline=yes --enable-fancydm=yes --enable-trickledm=yes --enable-ntlm=no --enable-sslmitm=yes --enable-dnsauth=no --enable-email=yes`.

**Comment by robotman3000** [comment]
Later when I have time I will have to try running v5develop on linux to see if the issue is also present there.

**Comment by robotman3000** [comment]
@philipianpearce How do I use the segv backtrace feature?

**Comment by philipianpearce** [comment]
The segv backtrace compile option is depreciated in v4 and v5 - as it does not function in the multi-threaded environment. I will remove it as a configure option. 

To get a back trace you have to enable core dumps and then use a debugger (gdb) to get the backtrace. Also, compile with -g3 -O0 in CPPFLAGS - this will give source code line numbers in the back trace. 

Regards 

Philip 

----- Original Message -----

**Comment by robotman3000** [comment]
After resetting the configs I ceased to get the segfault on a clients connection. Please note that I did the reset about a month ago but only just now am reporting the change. My thought is that it was somehow caused by problems with the list files or with their declaration in the filtergroup. Should the issue be left open in case the problem recurs or would be better to create a new issue?

**Comment by robotman3000** [comment]
@philipianpearce  I have stumbled upon the segv issue again.
I enabled just one auth plugin, the ip auth, and I got these segmentation faults. This also occurred on linux
[log3.txt](https://github.com/e2guardian/e2guardian/files/1666679/log3.txt)
[log2.txt](https://github.com/e2guardian/e2guardian/files/1666680/log2.txt)
[log1.txt](https://github.com/e2guardian/e2guardian/files/1666681/log1.txt)
Log 1 is HTTP Transperent
Log 2 is HTTPS Transperent
Log 3 is HTTP Explicit

**Comment by philipianpearce** [comment]
@robotman3000   There was a bug in both the ip and port auth plug-ins which was returning a group = -1 when no match found.    Fixed in latest v5.0 branch.  Many thanks for the debug logs, very helpful.  

If you are happy with the fix, please close this issue.

Regards Philip

**Comment by robotman3000** [comment]
I have tested and the issue appears to be fixed, Thanks
