### ISSUE TITLE
Kerberos authentication

### ISSUE THREAD

**Issue by men-chris** [e2guardian/e2guardian#321]
Is it planned to support Kerberos authentication in a future release?

Currently, Squid handles Kerberos authentication, but e2guardian does not know how to retrieve the person's identity from the logs.

**Comment by philipianpearce** [comment]
It is not something that I intend to write in the near to middle future as at Protex we use dnsauth and a separate authentication system to do kerberos (and other authentication methods).

However, it would be great if someone in the community would write a native e2g auth plug-in to do this!
 
I do not think that it would be too difficult to write, it's just that I have list of other features that have a higher priority.  And it would also be great to have a number of auth plug-ins that would make e2g more flexible and stand-alone.  For example, native basic auth etc. 

If anyone wants to write a plug-in then I would be happy to help by reviewing your code and including it in a future e2g release.

**Comment by fredbcode** [comment]
Hi Philip, write a plug-in for kerberos is really more complex than NTLM or DIGEST, BASIC
Kerberos identification is a real problem because the user name is heavily encrypted.
Previously, I fixed some bugs in NTLM/Digest and I also had a look at kerberos and I saw that it works very differently than NTLM    

I guess that ICAP is the only near way (thanks again for your great works !), perhaps made e2guardian as a full proxy with is own identification system could be a way, but it's not an easy solution -> AD integration, Ldap requests, cache, etc ...

http://contentfilter.futuragts.com/wiki/doku.php?id=user_identification_to_ad#ntlm_or_kerberos

**Comment by philipianpearce** [comment]
Hi Fred, 

What you say is true in the old, traditional way dg/e2g has worked with always an upstream cache and with authentication provided by squid as e2g cannot 'sniff' the user-name on the line. This is the viewpoint that contentfutures was working from. But in v5 this no longer the case! You no longer have to use upstream squid for these things. 

There is no reason at all why a native e2g plug-in should not be developed using samba (in the same way that squid does). All the complexity can be handled by samba modules and ldap integration is also very straight forward. At Protex we already do this for our own authentication system so I know it is possible! 

There is no need to implement caching in e2g as caching is becoming increasing irrelevant as more and more sites go https. If cacheing is needed then there is still the straight squid (or other proxies) available as an option, but using this would not prevent a native e2g auth from working. 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
Ok, I see thank you

Yes maybe we should rewrite identification and remove this part from proxy


>
>
> There is no need to implement caching in e2g as caching is becoming 
> increasing irrelevant as more and more sites go https. If cacheing is 
> needed then there is still the straight squid (or other proxies) 
> available as an option, but using this would not prevent a native e2g 
> auth from working.

About this specific point I disagree, with SSLBump caching still very 
efficient, even with something like youtube you can add a Squid URL 
rewriter plugin like https://cachevideos.com/
But yes native e2g auth seems a good way to do

@men-chris <https://github.com/men-chris> still in a near future ICAP 
seems to me a good solution, I'm testing right now and it's very fast 
and flexible Identification name is sends by a proxy ICAP (I mean Squid, 
but also Bluecoat or whatever)

**Comment by fredbcode** [comment]
Fixed by ICAP support
