### ISSUE TITLE
v5develop:bannedextensionlist

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#323]
I added .txt to the bannedextensionlist, but it appears as if it is ignored.  I made sure exceptionextensionlist was empty.  Attached you can the output of e2guardian that shows the download of the .txt file from http://www.sample-videos.com/download-sample-text-file.php.

[1.log](https://github.com/e2guardian/e2guardian/files/1573008/1.log)

**Comment by philipianpearce** [comment]
Identified as bug - extension and mime lists being read but not being checked.  Storyboard issue.

**Comment by dbrody2004** [comment]
Still can't get this work properly.  I've attached the log.  The file download is http://www.sample-videos.com/text/Sample-text-file-10kb.txt.  Below are the headers from it.  I put ".txt" in the bannedextensionlist.  From the commit, I see that it is checking the header fields disposition for extension and contenttype for mime.  You can see that the request to get the sample file doesn't have disposition so this file is not blocked.


curl -v http://www.sample-videos.com/text/Sample-text-file-10kb.txt
*   Trying 45.249.110.23...
* TCP_NODELAY set
* Connected to www.sample-videos.com (45.249.110.23) port 80 (#0)
> GET /text/Sample-text-file-10kb.txt HTTP/1.1
> Host: www.sample-videos.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 03 Jan 2018 20:58:06 GMT
< Server: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
< Last-Modified: Tue, 15 Nov 2016 19:46:58 GMT
< ETag: "3412f9-2526-5415c382719f8"
< Accept-Ranges: bytes
< Content-Length: 9510
< Content-Type: text/plain
< 
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus condimentum sagittis lacus, laoreet luctus ligula laoreet ut. Vestibulum ullamcorper accumsan velit vel vehicula. Proin tempor lacus arcu. Nunc at elit condimentum, semper nisi et, condimentum mi. In venenatis blandit nibh at sollicitudin. Vestibulum dapibus mauris at orci maximus pellentesque. Nullam id elementum ipsum. Suspendisse cursus lobortis viverra. Proin et erat at mauris tincidunt porttitor vitae ac dui.
.
.
.

[1.txt](https://github.com/e2guardian/e2guardian/files/1601670/1.txt)

**Comment by philipianpearce** [comment]
As far as I am aware dg/e2g has always just checked the disposition for file extensions, as in most cases the url extension is not relevant e.g a url ending in .php, .asp .cgi (or nothing) can generate a .exe .txt etc. file download. 

If you have a use for blocking url based on extension, then I will look at the storyboard logic to do this. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
Well it works though a lot responses don't contain disposition, so I wrote a script that also cross references the extension to mime type and then adds that to the bannedmimelist.
