### ISSUE TITLE
v5develop: onlymitmsslgrey implementation

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#325]
In the configuration files it states onlymitmsslgrey has been replaced.  How do we implement this feature through storyboard?  Basically we just want sslmitm off for any sites on in the greyssllist.

#Limit SSL MITM to sites in greysslsitelist(s)
# ignored if  sslmitm is off
# SSL sites not matching greysslsitelist will be treat as if sslmitm is off.
# The following option is replaced by storyboard logic
#onlymitmsslgrey = off  - ignored in V5

**Comment by philipianpearce** [comment]
If you want mitm off for a list of sites then put these sites in the exceptionsitelist.   Exception sites are never mitm.

I will update the documentation to indicate the storyboard where this setting can be made and also comments in the file showing how to make this setting.

**Comment by dbrody2004** [comment]
Actually I wanted mitm off for all sites except those we put in a list.  Is that possible?

**Comment by philipianpearce** [comment]
Yes, it is possible.  That is what was called onlymitmsslgrey in v4 did.   I will put up revised documentation on how to do this in a few days.  I am on vacation currently.

**Comment by dbrody2004** [comment]
Thanks.  Have you had time to put something together?

**Comment by philipianpearce** [comment]
I expect to get this done by the end of the week. 

Regards 

Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
There is now notes in examplef1.story.in on how to do this.

**Comment by dbrody2004** [comment]
Thanks, works good. 

I'm trying to understand how greylist checking is done without mitm.  Is E2guardian looking at SNI since that is not encrypted?   Does it make two connections - one to obtain the certificate (using E2Guardian private/public key pair) and then if okay, makes another connection passing the client public key through.
