### ISSUE TITLE
v5develop:blank page returned

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#326]
Setup -

e2guaridan<->Squid.  Squid listens on 3128.  e2guardian is setup as transparent proxy.

Going directly to squid - 
curl -x http://192.168.4.2:3128 "https://www.alibaba.com/trade/search?fsb=y&IndexArea=product_en&CatId=&SearchText=test" returns a valid webpage

Going through e2guardian returns a blank page -
curl "https://www.alibaba.com/trade/search?fsb=y&IndexArea=product_en&CatId=&SearchText=test"

Log file is attached.
[1.log](https://github.com/e2guardian/e2guardian/files/1577089/1.log)

**Comment by philipianpearce** [comment]
I am unable to replicate with current v5develop.

**Comment by dbrody2004** [comment]
I've ran some logs here.  First is the e2guardian log, the second is the tcpdump between e2guardian and squid (port 3128).  The third is the pcap file.  You can see from the e2guardian log -

hw58:  -Not scanning zero-length body
hw58: Sending 0 bytes from RAM (0 in buffer; 0 already sent)

The tcdump shows data between squid and e2guardian.

The squid log shows this.  In particular - Read.cc(144) HandleRead: FD 12, size 16384, retval -1, errno 104 which is a connection reset by peer (e2guardian).  Squid is trying to send 16384 bytes but connection gets reset.  This is verified by the 1.pcap file showing that the connection is reset by e2guardian (port 54934 -> port 3128 (squid))

2017/12/22 22:59:56.564| 5,5| Read.cc(58) comm_read_base: comm_read, queueing read for local=127.0.0.1:3128 remote=127.0.0.1:55826 FD 12 flags=1; asynCall 0x1242b20*1
2017/12/22 22:59:56.564| 5,5| ModEpoll.cc(116) SetSelect: FD 12, type=1, handler=1, client_data=0x7fa186bf4678, timeout=0
2017/12/22 22:59:56.564| 45,9| cbdata.cc(426) cbdataInternalUnlock: 0x124a048=7
2017/12/22 22:59:56.564| 5,5| AsyncCallQueue.cc(57) fireNext: leaving TunnelBlindCopyWriteHandler(local=192.168.2.69:37902 remote=198.11.132.23:443 FD 13 flags=1, data=0x124a048, size=31, buf=0x124a170)
2017/12/22 22:59:56.564| 45,9| cbdata.cc(426) cbdataInternalUnlock: 0x124a048=6
2017/12/22 22:59:56.564| 1,9| EventLoop.cc(41) checkEngine: Engine 0x7fff26b03868 is idle.
2017/12/22 22:59:56.564| 1,9| EventLoop.cc(41) checkEngine: Engine 0x7fff26b03870 is idle.
2017/12/22 22:59:56.564| 5,8| ModEpoll.cc(267) DoSelect: got FD 13 events=4 monitoring=1d F->read_handler=1 F->write_handler=0
2017/12/22 22:59:56.564| 5,8| ModEpoll.cc(296) DoSelect: no write handler for FD 13
2017/12/22 22:59:56.564| 5,5| ModEpoll.cc(116) SetSelect: FD 13, type=2, handler=0, client_data=0, timeout=0
2017/12/22 22:59:56.564| 5,8| ModEpoll.cc(267) DoSelect: got FD 12 events=19 monitoring=19 F->read_handler=1 F->write_handler=0
2017/12/22 22:59:56.564| 5,8| ModEpoll.cc(273) DoSelect: Calling read handler on FD 12
2017/12/22 22:59:56.564| 5,3| Read.cc(144) HandleRead: FD 12, size 16384, retval -1, errno 104
2017/12/22 22:59:56.564| 5,3| Read.cc(154) HandleRead: comm_read_try: scheduling Comm::COMM_ERROR
2017/12/22 22:59:56.564| 5,3| IoCallback.cc(116) finish: called for local=127.0.0.1:3128 remote=127.0.0.1:55826 FD 12 flags=1 (-1, 104)

[e2guardian.log](https://github.com/e2guardian/e2guardian/files/1583658/e2guardian.log)
[tcpdump.log](https://github.com/e2guardian/e2guardian/files/1583659/tcpdump.log)
<img width="1166" alt="screen shot 2017-12-22 at 3 11 56 pm" src="https://user-images.githubusercontent.com/4682241/34314641-7a0c99c6-e72a-11e7-9997-0816cc8e809e.png">

**Comment by fredbcode** [comment]
Can you please make a trace with wireshark format

Something like
tcpdump -i eth0 -Xvvnns0 -w /tmp/dump.cap**

**Comment by dbrody2004** [comment]
I have run three files -
dump_e2guardian.pcap - capture of output of e2guardian
dump_squid.pcap - capture of squid<->e2guardian
dump_noe2guardian.pcap - capture bypassing e2guardian

URL -  http://192.168.4.2:3128 "https://www.alibaba.com/trade/search?fsb=y&IndexArea=product_en&CatId=&SearchText=test"

Links:
https://www.dropbox.com/s/kwg0e3ix4t7riih/dump_e2guardian.pcap?dl=0
https://www.dropbox.com/s/dxf9a2xdi09rp0w/dump_squid.pcap?dl=0
https://www.dropbox.com/s/fxu2klntzd6g4dt/dump_no_e2guardian.pcap?dl=0

**Comment by dbrody2004** [comment]
So doing some debugging on this.  Below are the headers for the request.  There is no content-length specified.  In downloadmanagers/default.cpp, dminstance::in this causes geteverything=true and blocksize=32768.  When dminstance::in calls rc = sock->readChunk(block,newsize,d->timeout);, the download length is 65213, but only 32768 are available and the call returns with -1.

How can this be fixed?

Headers -
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Establish HTTP proxy tunnel to www.alibaba.com:443
> CONNECT www.alibaba.com:443 HTTP/1.1
> Host: www.alibaba.com:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: www.alibaba.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=www.alibaba.com
* 	 start date: Sat, 06 Dec 2014 13:35:51 GMT
* 	 expire date: Thu, 05 Dec 2024 13:35:51 GMT
* 	 issuer: C=US,ST=CA,L=San Jose,O=VXE Networks,CN=marco
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /trade/search?fsb=y&IndexArea=product_en&CatId=&SearchText=test HTTP/1.1
> Host: www.alibaba.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sun, 24 Dec 2017 23:59:16 GMT
< Content-Type: text/html;charset=UTF-8
< Transfer-Encoding: chunked
< Connection: close
< Vary: Accept-Encoding
< Set-Cookie: ali_apache_id=73.92.100.68.1514159956269.450593.4; path=/; domain=.alibaba.com; expires=Wed, 30-Nov-2084 01:01:01 GMT
< Vary: Accept-Encoding
< Server: Apache-Coyote/1.1
< P3P: CP="CAO PSA OUR"
< Set-Cookie: JSESSIONID=AE2D727A0E390B3AB13B53E3C77C39F3; Path=/; HttpOnly
< Set-Cookie: ali_apache_track=; Domain=.alibaba.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
< Set-Cookie: ali_apache_tracktmp=; Domain=.alibaba.com; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/
< Resin-Trace: ali_resin_trace=mlr_pc_org_prod_key=bts2|industry_id=100009293|sn_cat_type=1|qrw_kw=test|p4pid=f0e83da9-c801-4c2e-b326-c4e43a105e40|s_abtest=01_M_R|se_pn=1|isAtmOnline=0|is_broadquery=0|beaconId=02cc5ac4bdb546cfae2d141eb1e92de8|sq_type=a|forecast_post_cate=153710:0:154.0^100003004:0:94.0^100003003:1:5.0|is_f0_test=1|kw_type=0|is_chinasuppliers=0|isGalleryList=0|pvmi=2870a5dd589143249e8af5b2270f2fbf|carry_flag=product|sek=test|semi=0|is_onsite_check=0|magellan_waterfall=new_version|magellan_attr_mab=attr_desc_mab|is_gs_filt=0|proxy_ip=0|se_rst=2572522|magellan_personalize_group=new_version|ser=1001|bran_ab_test=0|is_waterfall=1|set=3|magellan_query_distinct=new_version|pageId=4e257a1b3b2d4e9ab6f75906efe7a6bf|sek_sepd=test|is_av_filt=0|magellan_js_bucket=old_version|magellan_common_expriment=new_version|is_merge_supplier=0|is_as_filt=0|is_escrow_filt=0|magellan_itwoi_qrw=i2i_new_version|magellan_personalize_rotation=new_version|magellan_rfqinsert=new_version
< Set-Cookie: xman_us_f=x_l=0; Domain=.alibaba.com; Expires=Sat, 12-Jan-2086 03:13:23 GMT; Path=/
< Set-Cookie: acs_usuc_t=acs_rt=02cc5ac4bdb546cfae2d141eb1e92de8; Domain=.alibaba.com; Path=/
< Set-Cookie: xman_t=vQOcoxbV0acOKyy8jqnr9RTv0sj4aqsKixQsbKN57n/L8ASsUq6UqMw5st2tIncX; Domain=.alibaba.com; Path=/; HttpOnly
< Set-Cookie: xman_f=HzwTBt0hczfcyQ9CHNu9QN1VwZQGb05pqCD9jllye8vwZGB4WLJD2LAscjHHS5/7gge4dcuV0dNDMSY/PcP2j5oN8M3U/83Z1JGiizxLPB/Q2Sdta7lqbA==; Domain=.alibaba.com; Expires=Sat, 12-Jan-2086 03:13:23 GMT; Path=/; HttpOnly
< Content-Language: en-US
< Strict-Transport-Security: max-age=31536000
< 
* Closing connection 0
root@marcoe2squiddesktop:/home/dbrody/e2guardian_v5_2# curl -v -k -x http://127.0.0.1:8080 -L "https://www.alibaba.com/trade/search?fsb=y&IndexArea=product_en&CatId=&SearchText=test"
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* Establish HTTP proxy tunnel to www.alibaba.com:443
> CONNECT www.alibaba.com:443 HTTP/1.1
> Host: www.alibaba.com:443
> User-Agent: curl/7.47.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied OK to CONNECT request
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: www.alibaba.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=www.alibaba.com
* 	 start date: Sat, 06 Dec 2014 13:35:51 GMT
* 	 expire date: Thu, 05 Dec 2024 13:35:51 GMT
* 	 issuer: C=US,ST=CA,L=San Jose,O=VXE Networks,CN=marco
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /trade/search?fsb=y&IndexArea=product_en&CatId=&SearchText=test HTTP/1.1
> Host: www.alibaba.com
> User-Agent: curl/7.47.0
> Accept: */*
>

**Comment by philipianpearce** [comment]
Yes, this agrees with what the e2g trace shows. I will look at redesigning logic in readChunk to allow for very large chunks, or rather to cut large chunks into smaller ones. Although there is no upper limit on chunk size in the http standard it does suggest they are kept short to reduce delays. 

Oddly I have not been able to replicate this issue, so the large chunks may have something to do with the squid set-up ? 

Could you try without squid (proxyip = ) and see if the issue is still there? We would then be able to see if it is target host making a large chunk or squid? (Chunking is hop-by-hop). 

I will change the function to cope with larger chunks anyway, but it would good to know why you are getting such large chunks. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
I disabled squid by setting proxyip= as well as stopping the squid service and same result (blank page).  Not sure why you can't replicate it.  I've compiled inside openwrt as well as in ubuntu to see if there was something else going on, but same results on both.

**Comment by philipianpearce** [comment]
Should now be fixed. Please test.

**Comment by dbrody2004** [comment]
Appears to be working

**Comment by philipianpearce** [comment]
Thanks, I will close the ticket 

Regards 

Philip 

----- Original Message -----
