### ISSUE TITLE
v5develop: bannedsiteiplist

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#332]
Can't get bannedsiteiplist to work.   

------------------------
Contents of bannedsiteiplist -

64.90.40.65
-----------------------

Debug output -
...
ipsitelist deque is size 1
reading %sname=banned,messageno=500,path=/etc/e2guardian/lists/bannedsiteiplist
Looking for banned type 3 in listmeta
Not Found banned type 3 in listmeta
name = banned m_no=500log_m_no=500 path=/etc/e2guardian/lists/bannedsiteiplist
pushing back for new list
/etc/e2guardian/lists/bannedsiteiplist
Compiling ^.*\:[0-9]+\/.*
...with PCRE 
Compiling ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$
...with PCRE 
Compiling ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$
...with PCRE 
Compiling ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$
...with PCRE 
Compiling ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}$
...with PCRE 
Compiling ^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}-\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$
...with PCRE 
Converting to lowercase
iplist deque is size 0
sitelist deque is size 11
....

hw1:  in  handle connection
hw1:  waiting connection on http_worker_Q 
hw1:  popped connection from http_worker_Q
hw1:  -got peer connection
hw1: 10.0.19.130
hw1: Start of request header:in
hw1: header:in before getLine - timeout:55000 Line: 1921 Function: in
hw1: firstime: header:in after getLine  Line: 1925 Function: in
hw1: header:size =  4
hw1: first line =  GET / HTTP/1.1
hw1: CheckHeader: HTTP/1.1 detected Line: 989 Function: checkheader
hw1: zero contentlength on request due to not POST/PUT 
hw1: CheckHeader flags before normalisation: AP=1 PPC=0 1.1=1 connectionclose=1 CL=0 Line: 1048 Function: checkheader
hw1: CheckHeader flags after normalisation: AP=0 WP=0 Line: 1069 Function: checkheader
hw1: CheckHeader: Adding our own Proxy-Connection: Close Line: 1087 Function: checkheader
hw1: from header url:http://64.90.40.65/ Line: 1219 Function: getUrl
hw1: isProxyRequest is 0
hw1: Compiling ,*[a-z|A-Z].*
hw1: ...with PCRE 
hw1: from header url:http://64.90.40.65 Line: 1219 Function: getUrl
hw1: decoding url Line: 1503 Function: decode
hw1: 30853Start URL http://64.90.40.65is_ssl=0ismitm=0
hw1: Checking for IP obfuscation in 64.90.40.65 Line: 760 Function: malformedURL
hw1: isProxyRequest is 0 only_ip_auth is 1
hw1:  -Not got persistent credentials for this connection - querying auth plugins
hw1:  -No auth plugins loaded; using defaults & feigning persistency
hw1:  -username: -
hw1:  -filtergroup: 0
hw1:  -About to check for bypass...
hw1: Found cookie: Line: 1293 Function: getCookie
hw1: No bypass cookie Line: 1321 Function: isBypassCookie
hw1:  -Finished bypass checks.
hw1: After StoryB checkrequest isexception 0 gomitm 0 mess_no 0
hw1:   got past line 727 rfo 
hw1: request headerout:GET http://64.90.40.65/ HTTP/1.1
hw1: request headerout:GET http://64.90.40.65/ HTTP/1.1
hw1: headertoclient:GET http://64.90.40.65/ HTTP/1.1
hw1: timeout:55000 Line: 1771 Function: out
hw1: Header written - pstdata_len:0 Line: 1836 Function: out
hw1: Returning from header:out  Line: 1859 Function: out
hw1: Start of response header:in
hw1: header:in before getLine - timeout:61000 Line: 1921 Function: in
hw1: firstime: header:in after getLine  Line: 1925 Function: in
hw1: header:size =  12
hw1: first line =  HTTP/1.1 200 OK
hw1: tp =Content-Length: 772
hw1: tp =772 Contentlen.int =772
hw1: CheckHeader: HTTP/1.1 detected Line: 989 Function: checkheader
hw1: CheckHeader: P-C says close Line: 1025 Function: checkheader
hw1: CheckHeader flags before normalisation: AP=0 PPC=1 1.1=1 connectionclose=1 CL=1 Line: 1048 Function: checkheader
hw1: CheckHeader flags after normalisation: AP=0 WP=0 Line: 1069 Function: checkheader
hw1: isProxyRequest is 0
hw1:  -persistPeer: 0
hw1: After StoryB checkresponse0 mess_no 0
hw1:  -Content scanners interested in response data: 1 Line: 1084 Function: handleConnection
hw1: mime type: text/html Line: 216 Function: isContentType
hw1:  -Filtering with expectation of a possible csmessage Line: 2794 Function: check_content
hw1: 
hw1:  -about to get body from proxy
hw1: Got to final download manager so defaulting to always match.
hw1: Inside default download manager plugin  icap=0
hw1: tranencodeing is 
hw1: bytes remaining is 772
hw1: blocksize: 32768
hw1: newsize: 772
hw1: Leaving default download manager plugin
hw1:  -got body
hw1:  -Running scanMemory
hw1: About to writeMemoryTempFile /tmp/tfBlhQMS size: 772
hw1: clamdscan command:SCAN /tmp/tfBlhQMS
hw1: Got from clamdscan: /tmp/tfBlhQMS: OK
hw1: clamdscan - he say yes (clean)
hw1:  -AV scan 0 returned: 0
hw1:  -finished running AV
hw1: mime type: text/html Line: 216 Function: isContentType
hw1:  -Start content filtering: hw1: Preserve case: 0
hw1: Raw content needed
hw1: Not preserving case of raw content
hw1: "Smart" filtering is enabled
hw1: Checking smart content
hw1: Map start
hw1: Map end
hw1: WEIGHTING: 0
hw1: NAUGHTINESS: 0
hw1: Checking raw content
hw1: Found this phrase:  control 
hw1: Found this phrase: control
hw1: Found this phrase: load
hw1: Found this phrase: web
hw1: Found this phrase: cure
hw1: Found this phrase: new
hw1: Found this phrase: age
hw1: Found this phrase: age
hw1: Found this phrase: age
hw1: Map start
hw1: Map:  control  1
hw1: Map: age 3
hw1: Map: control 1
hw1: Map: cure 1
hw1: Map: load 1
hw1: Map: new 1
hw1: Map: web 1
hw1: Map end
hw1: WEIGHTING: 10
hw1: NAUGHTINESS: 10
hw1:  -Done content filtering: hw1: mime type: text/html Line: 216 Function: isContentType
hw1: Starting content reg exp replace
hw1:  Returning from content checking
hw1: End content check isitNaughty is  0
hw1: response headerout:HTTP/1.1 200 OK
hw1: response headerout:HTTP/1.1 200 OK
hw1: headertoclient:HTTP/1.1 200 OK
hw1: timeout:61000 Line: 1771 Function: out
hw1: Header written - pstdata_len:0 Line: 1836 Function: out
hw1: Returning from header:out  Line: 1859 Function: out
hw1: Sending 772 bytes from RAM (772 in buffer; 0 already sent)
hw1: Sent 772 bytes from RAM (772
hw1:  -Forwarding body to client : Upfailure is 0
hw1:  -Attempting graceful connection close Line: 1171 Function: handleConnection
hw1: handle_peer returned: 0
hw1:  in  handle connection
hw1:  waiting connection on http_worker_Q

**Comment by philipianpearce** [comment]
ipsitelist now working correctly - note that unlike other lists the item matched is not returned.  This is an outstanding 'feature' of all iplists which will be fixed in a future release.
