### ISSUE TITLE
v5develop: bannedsitelist

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#334]
I noticed this awhile ago -

Our bannesitelist has a bunch of .include statements in it.  One of the .include statements referred to an invalid filename.  e2guardian did not error out on loading but just stop processing the file.  I don't know if this pertains to all lists or just that one.

**Comment by philipianpearce** [comment]
In v5, list file read error is reported on stderr when not demonised and in syslog once running. 

Currently, (unlike v4 which aborted when mandatory lists failed to load) v5 does not abort on failure of lists loading. This is deliberate as these files can change whilst e2g is running and if a file path error is introduced to a file and then a '-r' or '-q' actioned if aborted would give a abrupt failure of service. Also, v5 does not have an inbuilt concept of 'mandatory lists' 

In a future version there will be an option to 'require' individual list files to be read in ok. With this a failure will cause an abort on start-up, but on reloads will result in e2g to continue running with the previously loaded version of lists. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
So v5 doesn't require a restart if a list is modified?  How about if a config file is modified (xxx.conf or xxxf1.conf)?

**Comment by philipianpearce** [comment]
No, just a e2guardian -g. (also with v4)

If e2guardian.conf is modified then a full restart(i.e a complete 'stop' followed by 'start') is required.  
However the lists and storyboard defined in e2guardian.conf are re-read (if changed) on an e2guardian -g.
If an e2guardianfn.conf is modified a restart is not required just an e2guardian -g.
See comments at start of the example *.conf files.

**Comment by dbrody2004** [comment]
I tried the -g option.  I had e2guardian running in a separate thread fine.  I issue e2guardian -g (also tried -c along with it) and it gives the following error on the first thread.  /etc/e2guardian/preauth.story does exist and is loaded fine on the first startup.

signal:10
master: busychildren:0 worker Q size:0
master: gentle reload activated
master: iplist deque is size 0
master: sitelist deque is size 0
master: ipsitelist deque is size 0
master: urllist deque is size 0
master: Reading storyboard file /etc/e2guardian/preauth.story
Error opening Storyboard file (does it exist?): /etc/e2guardian/preauth.story
master: Storyboard not loaded OK
master: busychildren:0 worker Q size:0
master: busychildren:0 worker Q size:0
master: busychildren:0 worker Q size:0

**Comment by philipianpearce** [comment]
Check the file permissions. All config files and lists must be readable by the e2guardian user/group. 

When starting e2guardian runs as root so can read anything, but then setuid and group to e2guardian user when running, so when re-reading config/lists is as just a user. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
Got it.  I found that ListContainer->ifsreadItemList, the code should be -

 if (is_iplist)
            addToIPList(temp);
        else
            addToItemList(temp.toCharArray(), temp.length()); // add to unsorted list

As it stands in ifsreadItemList, if the list is an IP list, it doesn't get added to the iplist list.

**Comment by philipianpearce** [comment]
Are you sure you are looking at the latest code? IP lists work correctly here! 

The logic you describe is already in the code! 

if (temp.length() > 0) { 
mem_used += temp.length() + 1; 
if (is_iplist) 
addToIPList(temp); 
else { 
if (mem_used > data_memory) 
increaseMemoryBy(2048); 
addToItemList(temp.toCharArray(), temp.length()); // add to unsorted list 
} 
} 

Regards 

Philip 

----- Original Message -----
