### ISSUE TITLE
v5develop: Missing and incorrect configs

### ISSUE THREAD

**Issue by robotman3000** [e2guardian/e2guardian#336]
Hi, I have been working on pfSense to get v5 running and at various points in the process (make install or running e2g) I get errors about missing list files. Here are the issues I know of currently:

Makefile issues:
`bannedsitelistwithbypass - Missing; make install fails`
`bannedurllistwithbypass - Missing; make install fails`
`preauth.story - Forgotten`

Runtime Issues:
`examplef1.story - Line 1 Incorrect (.Include</home/dg/etc/config_i1/common.story> should be .Include</usr/local/etc/e2guardian/common.story>)`

**Comment by robotman3000** [comment]
I believe there are more but I don't remember which lists are affected.

**Comment by robotman3000** [comment]
Ok, so now as of the latest commit (1fcf069) everything except the 2 banned lists seem to be fixed. The files are present with the .in extension but it doesn't seem like they are getting processed

**Comment by marcelloc** [comment]
I'm still getting this issues with current v5develop branch

bannedsitelistwithbypass

the .in file exists but the resulting config file is not being created by make process.

**Comment by fredbcode** [comment]
Yes sorry, I missed something, should be better now

**Comment by marcelloc** [comment]
Thanks Fred!

**Comment by marcelloc** [comment]
this issue can be closed

**Comment by fredbcode** [comment]
Ok, thank you for your help
