### ISSUE TITLE
v5develop: Illegal Instruction error on FreeBSD

### ISSUE THREAD

**Issue by robotman3000** [e2guardian/e2guardian#337]
HTTP connections appear to work fine but HTTPS causes e2guardian to crash with an illegal instruction error. The crash occurs right after one or more "Going MITM ...." lines are printed. So far I have only seen it happen after 1 or 3 lines. Let me know what other debugging information you need, Thanks.

**Comment by robotman3000** [comment]
Here, I have some logging that may be useful. Let me clarify that HTTPS connections, both transparent and non-transparent cause the illegal instruction.
[log4.txt](https://github.com/e2guardian/e2guardian/files/1666652/log4.txt)
[log3.txt](https://github.com/e2guardian/e2guardian/files/1666653/log3.txt)
[log2.txt](https://github.com/e2guardian/e2guardian/files/1666654/log2.txt)
[log1.txt](https://github.com/e2guardian/e2guardian/files/1666655/log1.txt)

**Comment by robotman3000** [comment]
In all cases I was testing with curl

**Comment by robotman3000** [comment]
Things have changed now. Only https causes the Illegal Instruction. One note: I have transparent https enabled. Here are "updated" (new) debug logs. These were made using commit 1fcf069 on pfSense
[e2guardian-configs.tar.gz](https://github.com/e2guardian/e2guardian/files/1729903/e2guardian-configs.tar.gz)
[https-example.com.log](https://github.com/e2guardian/e2guardian/files/1729904/https-example.com.log)
[https-github.com.log](https://github.com/e2guardian/e2guardian/files/1729905/https-github.com.log)

I hope this helps.

**Comment by marcelloc** [comment]
still happening with current code

Going MITM ....
Going MITM ....
Going MITM ....
Going MITM ....
hw251: End content check isitNaughty is  0
hw254: tranencodeing is chunked
hw254: bytes remaining is -1
hw254: End content check isitNaughty is  0
Illegal instruction

**Comment by marcelloc** [comment]
with debug enabled...

hw245: looking for cert /usr/local/etc/e2guardian/ssl/generatedcerts/CE/8B/20/D6313DBF342A0C9E9E3A37686A
hw245: Certificate found
hw245:  -Going SSL on the peer connection
hw245:  nf 0 upfail 1
hw245:  -SSL Interception failed  nf 0 upfail 1
hw245:  -Building raw log data string... hw245:  -...built
hw245:  -reporting level is 3
hw245: mime type: - Line: 216 Function: isContentType
hw245: mimes result : false Line: 243 Function: isContentType
hw245: Displaying TEMPLATE
log: received a log request0

0
0
0
https://www.facebook.com

CONNECT
-
172.17.26.7
443
0
0
0
0
0
0
0
200
0
-
1520561039
453543




202
0

hw245:  -Shutting down ssl to proxy
hw245:  -Shutting down ssl to client
29 2018.3.8 23:04:04 - 172.17.26.7 https://www.facebook.com:443 - CONNECT 0 0 - 1 200 - - Default - - - - -
Illegal instruction

**Comment by marcelloc** [comment]
with gdb

Thread 257 received signal SIGILL, Illegal instruction.
[Switching to LWP 101816 of process 16563]
0x000000000043f5cd in ConnectionHandler::goMITM(NaughtyFilter&, Socket&, Socket&, bool&, bool&, bool&, String&, stat_rec*&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool) ()

**Comment by marcelloc** [comment]
This issues is fixed on 5.0.1 too
