### ISSUE TITLE
Monitoring of httpworkers usage

### ISSUE THREAD

**Issue by xenadmin** [e2guardian/e2guardian#342]
Hello,

we have several customers on e2guardian 4.x by now. Is there a way to get Information about the utilization for the httpworkers? Right now we are guessing, which isn't a great way to design. I would like to add the utilization into our Zabbix monitoring. 

Thanks for your help and great work.

**Comment by philipianpearce** [comment]
Define dstatlocation in e2guardian.conf 

See notes/dstat_format. 

----- Original Message -----

**Comment by xenadmin** [comment]
Thank you, I totally missed that. Based on that information I wrote a Template for our Zabbix Monitoring:
https://github.com/xenadmin/zabbix-templates/tree/master/zabbix-e2guardian
