### ISSUE TITLE
e2guardian on CentOS 6

### ISSUE THREAD

**Issue by gjahchan** [e2guardian/e2guardian#343]
I have successfully configured v5.0 of eguardian with g++ v4.4.7, but it will not compile even without the c++1y CXXGLAG:

$ g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I had to remove c++1y from CXXFLAGS for compilation to work. But I am still facing an issue:

<snip>
make[2]: Entering directory `/tmp/e2guardian-5.0/src'
g++ -DHAVE_CONFIG_H -I. -I..  -D__CONFFILE='"/etc/e2guardian/e2guardian.conf"' -D__LOGLOCATION='"/var/log/e2guardian/"' -D__PIDDIR='"/var/run"' -D__PROXYUSER='"clamav"' -D__PROXYGROUP='"e2guardian"' -D__CONFDIR='"/etc/e2guardian"'  -D_FORTIFY_SOURCE=2   -DFD_SETSIZE=65535 -MT e2guardian-String.o -MD -MP -MF .deps/e2guardian-String.Tpo -c -o e2guardian-String.o `test -f 'String.cpp' || echo './'`String.cpp
String.cpp:27: error: ‘thread_local’ does not name a type
String.cpp: In member function ‘String String::sort_search()’:
String.cpp:562: error: ‘unique_ptr’ is not a member of ‘std’
String.cpp:562: error: expected primary-expression before ‘char’
String.cpp:562: error: expected ‘;’ before ‘char’
String.cpp:563: error: ‘temp’ was not declared in this scope
----------------------------------------------
I compiled from source and installed latest gcc (7.3.0), e2guard-5.0 does not like it either:

$ g++ --version
g++ (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
--------------------------------------------
Configuration does not work anymore: snippet from config.log
...
configure:2718: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
...
I get similar output when I run: g++ -V
--------------------------------------------
If I configure with gcc 4.4.7, compilation with gcc-7.3 still fails:

Making all in src
make[2]: Entering directory `/tmp/e2guardian-5.0/src'
g++ -DHAVE_CONFIG_H -I. -I..  -D__CONFFILE='"/etc/e2guardian/e2guardian.conf"' -D__LOGLOCATION='"/var/log/e2guardian/"' -D__PIDDIR='"/var/run"' -D__PROXYUSER='"clamav"' -D__PROXYGROUP='"e2guardian"' -D__CONFDIR='"/etc/e2guardian"'  -D_FORTIFY_SOURCE=2   --std=c++1y  -DFD_SETSIZE=65535 -MT e2guardian-String.o -MD -MP -MF .deps/e2guardian-String.Tpo -c -o e2guardian-String.o `test -f 'String.cpp' || echo './'`String.cpp
g++: error trying to exec 'cc1plus': execvp: No such file or directory
make[2]: *** [e2guardian-String.o] Error 1
make[2]: Leaving directory `/tmp/e2guardian-5.0/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/e2guardian-5.0'
make: *** [all] Error 2

**Comment by philipianpearce** [comment]
gcc v4.4.7 does not fully support c++11, you need v5.4 or later - see notes/NEWIN_v5 

Our reference build is on gcc v5.4, so I would suggest that you use the latest in the v5 tree v5.5. 

A lot of old features where removed in gcc v6 and v7 and if looks like the configure script uses some of these. We will look at this at a later point, but currently for stability we are sticking to gcc v5 as a reference platform. I will add a note to the INSTALL/NEWIN files to that effect. 

Regards 

Philip 

----- Original Message -----
