### ISSUE TITLE
[Libssl 1.1] Unexpected error from sigtimedwait() 4 Interruption during system call

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#344]
I have just packaged e2guardian 4.1.4 for Debian unstable (I am the e2guardian maintainer in Debian).

We are currently performing functionality tests on a stretch-backport system. The build works well, but at runtime things fail:

```
Feb  7 16:26:43 filter e2guardian[23719]: Unexpected error from sigtimedwait() 4 Unterbrechung während des Betriebssystemaufrufs
Feb  7 16:26:44 filter e2guardian[23719]: Unexpected error from sigtimedwait() 4 Unterbrechung während des Betriebssystemaufrufs
```

```
#  strace -f e2guardian -N -c /etc/e2guardian/e2guardian.conf
[...]
[pid 25378] futex(0x5559c74e89cc, FUTEX_WAIT_PRIVATE, 197, NULLstrace: Process 25377 attached
 <unfinished ...>
[pid 25377] set_robust_list(0x7f41d80659e0, 24) = 0
[pid 25377] futex(0x5559c74e89cc, FUTEX_WAIT_PRIVATE, 198, NULLstrace: Process 25376 attached
 <unfinished ...>
[pid 25376] set_robust_list(0x7f41d88669e0, 24) = 0
[pid 25376] futex(0x5559c74e89cc, FUTEX_WAIT_PRIVATE, 199, NULLstrace: Process 25375 attached
 <unfinished ...>
[pid 25375] set_robust_list(0x7f41d90679e0, 24) = 0
[pid 25375] futex(0x5559c74e89cc, FUTEX_WAIT_PRIVATE, 200, NULLstrace: Process 25374 attached
 <unfinished ...>
[pid 25374] set_robust_list(0x7f41daa6c9e0, 24) = 0
[pid 25374] open("/var/log/e2guardian/access.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 4
[pid 25374] lseek(4, 0, SEEK_END)       = 0
[pid 25374] futex(0x5559c74e866c, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
[pid 25373] <... rt_sigtimedwait resumed> ) = -1 EAGAIN (Resource temporarily unavailable)
[pid 25373] rt_sigtimedwait([HUP USR1 PIPE TERM], NULL, {tv_sec=5, tv_nsec=0}, 8) = -1 EAGAIN (Resource temporarily unavailable)
[pid 25373] rt_sigtimedwait([HUP USR1 PIPE TERM], NULL, {tv_sec=5, tv_nsec=0}, 8) = -1 EAGAIN (Resource temporarily unavailable)
[pid 25373] rt_sigtimedwait([HUP USR1 PIPE TERM], NULL, {tv_sec=5, tv_nsec=0}, 8
```

It seems the application is stuck in the sig handler procedure and not getting to handle any request.

The funny thing is that I see a bound filter port (for me, this is 3128):

```
e2guardia 25373  e2guardian    3u  IPv4 170640      0t0  TCP filter.intern:3218 (LISTEN)
```

But when I nmap that <ip>:<port> pair, I get a socket closed result:

```
root@filter:/var/log/e2guardian# nmap -p 3128 filter.intern

Starting Nmap 7.40 ( https://nmap.org ) at 2018-02-07 16:38 CET
Nmap scan report for filter (10.0.2.6)
Host is up (0.000032s latency).
rDNS record for 10.0.2.6: filter.intern
PORT     STATE  SERVICE
3128/tcp closed squid-http

Nmap done: 1 IP address (1 host up) scanned in 0.26 seconds
```

Note, that we switch ports

filterip = 10.0.2.6
filterports = 3128

proxyip = 127.0.0.1
proxyports = 8080

The underlying Squid3 works ok.

Any idea what is happening here? The packaging recipe for Debian is here:
https://anonscm.debian.org/cgit/debian-edu/pkg-team/e2guardian.git/

Simply clone a copy of the repo's master branch. Run "debian/rules/get-orig-source" and then "debuild -uc -us" on a Debian stretch system to reproduce my setup.

Thanks,
Mike

**Comment by sunweaver** [comment]
Here is the debian/rules file, showing how I configured the build:
https://anonscm.debian.org/cgit/debian-edu/pkg-team/e2guardian.git/tree/debian/rules?id=68552c2fced87f2fe3f79a5f5026d21ad91f40a3

**Comment by fredbcode** [comment]
Hello

Can you try this package?

https://github.com/e2guardian/e2guardian/releases/tag/v4.1.4

Do you have libpthread (and dev version) installed ?

**Comment by sunweaver** [comment]
Hi,

On Wednesday, February 7, 2018, Fredb wrote:
> Hello
> 
> Can you try this package?
> 
> https://github.com/e2guardian/e2guardian/releases/tag/v4.1.4

I can try that later. More interesting is the debian/ folder that you used for building the package. Esp. the build dependencies used.
 
> Do you have libpthread (and dev version) installed ?

Which package exactly???

Mike

-- 
Sent from my Fairphone 2 (running Sailfish OS)

**Comment by fredbcode** [comment]
ii  libpth20:amd64                        2.0.7-20+b2                                 amd64        GNU Portable Threads
ii  libpthread-stubs0-dev:amd64           0.3-4                                       amd64        pthread stubs not provided by native libc, development files
ii  libevent-pthreads-2.0-5:amd64         2.0.21-stable-3                             amd64        Asynchronous event notification library (pthreads)


Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CFLAGS=-g -O2 -g -Wall -O2' 'LDFLAGS=' 'CPPFLAGS=' 'CXXFLAGS=-g -O2 -g -Wall -O2'


more e2guardian_4.1.4_strech/control/control 
Package: e2guardian 
Version: 4.1.4
Architecture: amd64
Maintainer: frederic Bourgeois <numsys@free.fr>
Installed-Size: 13900
Depends: adduser, libevent-pthreads-2.0-5, perl, libbz2-1.0, libc6 (>= 2.4), libgcc1 (>= 1:4.1.1), libpcre3 (>= 8.10), libstdc++6 (>= 4.6), libtommath1, zlib1g (>= 1:1.1.4), libssl1.0.2 (>= 1.0.1)
Suggests: squid, clamav (>= 0.80), clamav-freshclam
Section: web

**Comment by sunweaver** [comment]
On  Do 08 Feb 2018 15:21:53 CET, Fredb wrote:

> ii  libpth20:amd64                        2.0.7-20+b2                 
>                  amd64        GNU Portable Threads
> ii  libpthread-stubs0-dev:amd64           0.3-4                       
>                  amd64        pthread stubs not provided by native  
> libc, development files
> ii  libevent-pthreads-2.0-5:amd64         2.0.21-stable-3             
>                  amd64        Asynchronous event notification  
> library (pthreads)

Ok. I have added libpthread-stubs0-dev as build dependency, let's see  
what comes of it.

> Built with:  '--prefix=/usr' '--enable-clamd=yes'  
> '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian'  
> '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes'  
> '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes'  
> '--enable-trickledm=yes' '--mandir=${prefix}/share/man'  
> '--infodir=${prefix}/share/info' '--enable-pcre=yes'  
> '--enable-sslmitm=yes' 'CFLAGS=-g -O2 -g -Wall -O2' 'LDFLAGS='  
> 'CPPFLAGS=' 'CXXFLAGS=-g -O2 -g -Wall -O2'

Ok...

> more e2guardian_4.1.4_strech/control/control
> Package: e2guardian
> Version: 4.1.4
> Architecture: amd64
> Maintainer: frederic Bourgeois <numsys@free.fr>
> Installed-Size: 13900
> Depends: adduser, libevent-pthreads-2.0-5, perl, libbz2-1.0, libc6  
> (>= 2.4), libgcc1 (>= 1:4.1.1), libpcre3 (>= 8.10), libstdc++6 (>=  
> 4.6), libtommath1, zlib1g (>= 1:1.1.4), libssl1.0.2 (>= 1.0.1)
> Suggests: squid, clamav (>= 0.80), clamav-freshclam
> Section: web

Oh wow... you still require libssl 1.0.x. For Debian unstable, you  
need to port to libssl 1.1.

I will build without ssl support until you have ported your code to ssl 1.1.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
Hi,

On  Mi 07 Feb 2018 18:28:38 CET, Fredb wrote:

> Hello
>
> Can you try this package?
>
> https://github.com/e2guardian/e2guardian/releases/tag/v4.1.4
>
> Do you have libpthread (and dev version) installed ?

The .deb you provide somehow seems to work. How do you create it?

Also, as long as e2guardian lacks libssl 1.1 support, it makes no  
sense to replace the currently available version (3.4.0.2) in Debian.

Please support libssl 1.1. Thanks!

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by sunweaver** [comment]
HI once more,

On  Do 08 Feb 2018 15:21:53 CET, Fredb wrote:

> Depends: adduser, libevent-pthreads-2.0-5, perl, libbz2-1.0, libc6  
> (>= 2.4), libgcc1 (>= 1:4.1.1), libpcre3 (>= 8.10), libstdc++6 (>=  
> 4.6), libtommath1, zlib1g (>= 1:1.1.4), libssl1.0.2 (>= 1.0.1)
> Suggests: squid, clamav (>= 0.80), clamav-freshclam
> Section: web

in fact, building against the still available libssl1.0-dev is  
impossible as of today, as some of the other build dependencies  
already pull in libssl 1.1 and libssl1.1-dev and libssl1.0-dev  
conflict with each other in Debian unstable right now.

So, there really is a need to get libssl 1.1 supported.

Thanks!
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fredbcode** [comment]
> 
> The .deb you provide somehow seems to work. How do you create it?

Manually ...
Compiled with libssl1.0 -> Still supported by debian in Strech

> 
> Also, as long as e2guardian lacks libssl 1.1 support, it makes no
> sense to replace the currently available version (3.4.0.2) in Debian.
> 
> Please support libssl 1.1. Thanks!

Yes

**Comment by sunweaver** [comment]
Hi,

On  Do 08 Feb 2018 17:29:44 CET, Fredb wrote:

>>
>> The .deb you provide somehow seems to work. How do you create it?
>
> Manually ...
> Compiled with libssl1.0 -> Still supported by debian in Strech

But could missing libssl support (I simply omit libssl-dev from  
Build-Depends) result in a hanging and non-functional e2guardian?

>>
>> Also, as long as e2guardian lacks libssl 1.1 support, it makes no
>> sense to replace the currently available version (3.4.0.2) in Debian.
>>
>> Please support libssl 1.1. Thanks!
>
> Yes

Thanks a lot for looking into that!

Mike

-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fredbcode** [comment]
Do you have schedule to fix a version ? This year (I hope) V5 will be released this is a very important version with many new featuress (ICAP, storyboard, etc)

**Comment by sunweaver** [comment]
Hi,

On  Fr 09 Feb 2018 08:31:31 CET, Fredb wrote:

> Do you have schedule to fix a version ? This year (I hope) V5 will  
> be released this is a very important version with many new featuress  
> (ICAP, storyboard, etc)

The very next milestone is Ubuntu LTS 18.04. The upload gate via  
Debian unstable closes March 1st 2018.

The next milestone then is Debian buster (aka Debian 10). There is at  
least time until the end of this year, before any sort of freeze will  
come up.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fredbcode** [comment]
Ok, so I think 4.1.5 for 18.04 should be interesting but 4.x still with libssl1.0, I will release at the end of the next week if needed 

5.x for Debian 10, it's a major release with a lot of changes (ICAP storyborad, transparent proxy, etc)

> But could missing libssl support (I simply omit libssl-dev from Build-Depends) result in a hanging and non-functional e2guardian?

Yes I guess 

FYI my compilation option for the next package:

'--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -frecord-gcc-switches -g3 -O0'

**Comment by sunweaver** [comment]
Hi,

On  Fr 16 Feb 2018 12:37:08 CET, Fredb wrote:

> Ok, so I think 4.1.5 for 18.04 should be interesting but 4.x still  
> with libssl1.0, I will release at the end of the next week if needed

Sorry, I can't get a libssl1.0 based application into Debian unstable  
anymore (without protest).

> 5.x for Debian 10, it's a major release with a lot of changes (ICAP  
> storyborad, transparent proxy, etc)

Let's focus on that then.

>> But could missing libssl support (I simply omit libssl-dev from  
>> Build-Depends) result in a hanging and non-functional e2guardian?
>
> Yes I guess

Ok. So no point in packaging e2guardian with lacking SSL MitM support.

> FYI my compilation option for the next package:
>
> '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian'  
> '--with-proxygroup=e2guardian' '--sysconfdir=/etc'  
> '--localstatedir=/var' '--enable-icap=yes'  
> '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes'  
> '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info'  
> '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2  
> -frecord-gcc-switches -g3 -O0'

Ok. But again. No upload, until I have libssl1.1 support.

Sorry + Thanks!
Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fredbcode** [comment]
E2guardian 4.1.5 is released now

**Comment by sunweaver** [comment]
On  Mo 21 Mai 2018 09:36:53 CEST, Fredb wrote:

> E2guardian 4.1.5 is released now

Great! Looking into Debian packaging and testing now...

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by fredbcode** [comment]
FYI: V5 will be released in two weeks, the changes are massive
