### ISSUE TITLE
v5: THTTPS connection handler caught an exception: basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#345]
This error comes up THTTPS connection handler caught an exception: basic_string::_M_construct null not valid Line: 3159 Function: handleTHTTPSConnection with a particular device we attached to e2guardian.  Attached is the logfile.  Do you know what might be happening?

[1.txt](https://github.com/e2guardian/e2guardian/files/1709815/1.txt)

**Comment by philipianpearce** [comment]
@dbrody2004 - Please try with the attached changes to ConnectionHandler.cpp and see if that fixes the issue. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
Fixed it.  Thanks.

**Comment by Dalacor** [comment]
When was this issue fixed? The date of the fix says February 2018, but E2guardian 5.3.2 came out in March 2019 with this exact same error message? None of my clients running E2guardian 5.3.3 show this error message, but they are much smaller schools and are also running a new version of Slackware Kernel so I am not sure whether the size of the client running E2G 5.3.2 makes a difference?

I will be upgrading all of them to 5.3.4 when I have time but I am wondering if this will fix it for the one school experiencing this issue as they are much bigger than the other schools. Thanks

**Comment by Dalacor** [comment]
Ignore my previous post. I updated the client running E2guardian 5.3.2 to 5.3.3 and problem has gone away so I have answered my own question. In April I will be updating all clients to 5.3.4
