### ISSUE TITLE
V5.0.0: ConnectionHandler.cpp 'peercon' was not declared in this scope

### ISSUE THREAD

**Issue by Django-BOfH** [e2guardian/e2guardian#346]
I tried to build the new development-version 5 under CentOS 7.

The following error occurred:
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --prefix=/usr --enable-clamd=yes --with-proxyuser=e2guardian --with-proxygroup=e2guardian --sysconfdir=/etc --localstatedir=/var --enable-icap=yes --enable-commandline=yes --enable-email=yes --enable-ntlm=yes --enable-pcre=yes --enable-sslmitm=yes --enable-avastd=yes --enable-kavd=yes --enable-orig-ip --enable-avastd=yes
+ make
ConnectionHandler.cpp: In member function 'int ConnectionHandler::handleConnection(Socket&, String&, bool, Socket&, stat_rec*&)':
ConnectionHandler.cpp:867:53: error: 'peercon' was not declared in this scope
                             writeback_error(checkme,peercon,200,0,"400 Bad Request");
                                                     ^
make[2]: *** [e2guardian-ConnectionHandler.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by fredbcode** [comment]
Did you make an autogen.sh before configure ?

--enable-avastd=yes is duplicated

**Comment by Django-BOfH** [comment]
yes I dit it. the duplicated --enable-avastd have i deleted, thanx fot hat hint!

BUT, it is very strange.
If I try to build v5 ba hand, it compiles!
Example:
$ ./autogen.sh
$ ./configure
$ make

If I try the same with a spec-file and rpmbuild it fails. :/  In my spec-file I do it in the same way, as I build all the other packages:

`%prep
%setup -q

%build

./autogen.sh
autoreconf -fi

%configure \
   --prefix=/usr \
   --enable-clamd=yes \
   --with-proxyuser=e2guardian \
   --with-proxygroup=e2guardian \
   --sysconfdir=/etc \
   --localstatedir=/var \
   --enable-icap=yes \
   --enable-commandline=yes \
   --enable-email=yes \
   --enable-ntlm=yes \
   --enable-pcre=yes \
   --enable-sslmitm=yes \
   --enable-avastd=yes \
   --enable-kavd=yes \
   --enable-orig-ip \

make`

`$ rpmbuild -v -ba -sign /home/django/rpmbuild/SPECS/e2guardian-5.0.0.spec
+ umask 022
+ cd /home/django/rpmbuild/BUILD
+ cd /home/django/rpmbuild/BUILD
+ rm -rf e2guardian-5.0.0beta
+ /usr/bin/gzip -dc /home/django/rpmbuild/SOURCES/e2guardian-5.0.0beta.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd e2guardian-5.0.0beta
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
+ umask 022
+ cd /home/django/rpmbuild/BUILD
+ cd e2guardian-5.0.0beta
+ ./autogen.sh
+ cp README.md README
+ aclocal -I m4
+ autoheader
+ automake --add-missing --copy
configure.ac:115: installing './config.guess'
configure.ac:115: installing './config.sub'
+ autoconf
+ ./configure --prefix=/usr --enable-clamd=yes --with-proxyuser=e2guardian --with-proxygroup=e2guardian --sysconfdir=/etc --localstatedir=/var --enable-icap=yes --enable-commandline=yes --enable-email=yes --enable-ntlm=yes --enable-pcre=yes --enable-sslmitm=yes --enable-avastd=yes --enable-kavd=yes --enable-orig-ip
/home/django/rpmbuild/BUILD/e2guardian-5.0.0beta/missing: Unknown `--is-lightweight' option
Try `/home/django/rpmbuild/BUILD/e2guardian-5.0.0beta/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
+ make
ConnectionHandler.cpp: In member function 'int ConnectionHandler::handleConnection(Socket&, String&, bool, Socket&, stat_rec*&)':
ConnectionHandler.cpp:867:53: error: 'peercon' was not declared in this scope
                             writeback_error(checkme,peercon,200,0,"400 Bad Request");
                                                     ^
make[2]: *** [e2guardian-ConnectionHandler.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.6Tti9b (%build)
    Fehler-Status beim Beenden von /var/tmp/rpm-tmp.6Tti9b (%build)`

**Comment by fredbcode** [comment]
Seems there is something wrong with "missing" file and compilation options.
I guess there is something cached, please do a make clean or better distclean before make


Le 15 février 2018 17:08:36 GMT+01:00, Django <notifications@github.com> a écrit :
>yes I dit it. the duplicated --enable-avastd have i deleted, thanx fot
>hat hint!
>
>BUT, it is very strange.
>If I try to build v5 ba hand, it compiles!
>Example:
>$ ./autogen.sh
>$ ./configure
>$ make
>
>If I try the same with a spec-file and rpmbuild it fails. :/  In my
>spec-file I do it in the same way, as I build all the other packages:
>
>`%prep
>%setup -q
>
>%build
>
>./autogen.sh
>autoreconf -fi
>
>%configure \
>   --prefix=/usr \
>   --enable-clamd=yes \
>   --with-proxyuser=e2guardian \
>   --with-proxygroup=e2guardian \
>   --sysconfdir=/etc \
>   --localstatedir=/var \
>   --enable-icap=yes \
>   --enable-commandline=yes \
>   --enable-email=yes \
>   --enable-ntlm=yes \
>   --enable-pcre=yes \
>   --enable-sslmitm=yes \
>   --enable-avastd=yes \
>   --enable-kavd=yes \
>   --enable-orig-ip \
>
>make`
>
>`$ rpmbuild -v -ba -sign
>/home/django/rpmbuild/SPECS/e2guardian-5.0.0.spec
>+ umask 022
>+ cd /home/django/rpmbuild/BUILD
>+ cd /home/django/rpmbuild/BUILD
>+ rm -rf e2guardian-5.0.0beta
>+ /usr/bin/gzip -dc
>/home/django/rpmbuild/SOURCES/e2guardian-5.0.0beta.tar.gz
>+ /usr/bin/tar -xf -
>+ STATUS=0
>+ '[' 0 -ne 0 ']'
>+ cd e2guardian-5.0.0beta
>+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
>+ exit 0
>+ umask 022
>+ cd /home/django/rpmbuild/BUILD
>+ cd e2guardian-5.0.0beta
>+ ./autogen.sh
>+ cp README.md README
>+ aclocal -I m4
>+ autoheader
>+ automake --add-missing --copy
>configure.ac:115: installing './config.guess'
>configure.ac:115: installing './config.sub'
>+ autoconf
>+ ./configure --prefix=/usr --enable-clamd=yes
>--with-proxyuser=e2guardian --with-proxygroup=e2guardian
>--sysconfdir=/etc --localstatedir=/var --enable-icap=yes
>--enable-commandline=yes --enable-email=yes --enable-ntlm=yes
>--enable-pcre=yes --enable-sslmitm=yes --enable-avastd=yes
>--enable-kavd=yes --enable-orig-ip
>/home/django/rpmbuild/BUILD/e2guardian-5.0.0beta/missing: Unknown
>`--is-lightweight' option
>Try `/home/django/rpmbuild/BUILD/e2guardian-5.0.0beta/missing --help'
>for more information
>configure: WARNING: 'missing' script is too old or missing
>+ make
>ConnectionHandler.cpp: In member function 'int
>ConnectionHandler::handleConnection(Socket&, String&, bool, Socket&,
>stat_rec*&)':
>ConnectionHandler.cpp:867:53: error: 'peercon' was not declared in this
>scope
>              writeback_error(checkme,peercon,200,0,"400 Bad Request");
>                                                     ^
>make[2]: *** [e2guardian-ConnectionHandler.o] Error 1
>make[1]: *** [all-recursive] Error 1
>make: *** [all] Error 2
>Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.6Tti9b (%build)
>    Fehler-Status beim Beenden von /var/tmp/rpm-tmp.6Tti9b (%build)`
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/346#issuecomment-365975202

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
