### ISSUE TITLE
v5develop:503 proxy error

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#347]
Getting a 503 proxy error.  Below is the e2guardian log and squid.log.  There is a device connected to e2guardian that is trying to go to accounts.google.com/o/oauth2/token (thread hw4).  You can see that in e2guardian it gets  503 proxy error.  In squid you can see that e2guardian is trying to connect the first time with the statement - CONNECT accounts.google.com/o/oauth2/token:443 HTTP/1.1.  I believe the initial connection should be CONNECT accounts.google.com:443.

[e2guardian.txt](https://github.com/e2guardian/e2guardian/files/1732515/e2guardian.txt)

[squid.txt](https://github.com/e2guardian/e2guardian/files/1732516/squid.txt)

**Comment by philipianpearce** [comment]
From the trace the SNI sent by the device is accounts.google.com/o/oauth2/token.  SNI should only contain server name, but I will  change the code in order to cater for this.

Philip

**Comment by dbrody2004** [comment]
Thanks - looking forward to the code change.
