### ISSUE TITLE
Microsoft Bing - Enforce Safeseach

### ISSUE THREAD

**Issue by pjfraser82** [e2guardian/e2guardian#35]
Hi, 

Although no one probably uses Bing I have a small issue with it. I am trying to make sure that Bing Safesearch feature is enforced. 

e2g Seems to classify Bing as a Proxy site. If I run bing through the an exception list then it works but the URL Regex re-write does not take effect. If I use grey lists it seems to be the same. 

Why is Bing classed as a proxy site and is there any way I can have it accessible but still be process through the regex url re-writer? 

Thanks

**Comment by fredbcode** [comment]
Please use https://groups.google.com/forum/#!forum/e2guardian for any question
