### ISSUE TITLE
loglevel issue

### ISSUE THREAD

**Issue by PhilCode4U** [e2guardian/e2guardian#350]
Hello,

I found an issue with e2guardian -r

In fact, when we would change the loglevel in e2guardian.conf, the command "service e2guardian reload" didn't take it in consideration.
But with the command "service e2guardian restart" the new loglevel value is well read by e2guardian.

Eg

e2guardian.conf Before:

	loglevel = 0

e2guardian.conf After:

	loglevel = 3

with:

	service e2guardian reload

-> the new value of loglevel was ignored and e2guardian didn't log anything 

But with:

	service e2guardian restart

-> the new value of loglevel was taken into consideration and e2guardian log right

I think about 2 possible Fix:

1- Add explicitly comments, about the loglevel value change doesn't works with reload

OR

2- Take care about loglevel with reload (in part of code -> e2guardian -r)

**Comment by philipianpearce** [comment]
Please read the start of the example e2guardian.conf. file which makes this behavior clear.

# e2guardian config file for version @PACKAGE_VERSION@

#NOTE This file is only read at start-up.
