### ISSUE TITLE
v5develop cant build dnsauth plugin

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#352]
using freebsd11

trying to compile with dnsauth returns

--- authplugins/e2guardian-dnsauth.o ---
authplugins/dnsauth.cpp:266:24: error: cast from pointer to smaller type 'char' loses information
                p[j] = (char)NULL;
                       ^~~~~~~~~~
1 error generated.
*** [authplugins/e2guardian-dnsauth.o] Error code 1

make[4]: stopped in /usr/ports/www/e2guardian_5/work/e2guardian-5.0/src
--- authplugins/e2guardian-port.o ---
mv -f authplugins/.deps/e2guardian-port.Tpo authplugins/.deps/e2guardian-port.Po
--- authplugins/e2guardian-digest.o ---
mv -f authplugins/.deps/e2guardian-digest.Tpo authplugins/.deps/e2guardian-digest.Po
--- authplugins/e2guardian-header.o ---
authplugins/header.cpp:56:24: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if (fname.length() < 0)
        ~~~~~~~~~~~~~~ ^ ~
1 warning generated.
mv -f authplugins/.deps/e2guardian-header.Tpo authplugins/.deps/e2guardian-header.Po
1 error

make[4]: stopped in /usr/ports/www/e2guardian_5/work/e2guardian-5.0/src
*** [all-recursive] Error code 1

**Comment by fredbcode** [comment]
Ok, try now please

**Comment by marcelloc** [comment]
Thanks again.
