### ISSUE TITLE
Lack of padding in timestamps makes log parsing difficult

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#354]
I'm working on a logwatch filter for e2guardian but the log timestamp format is making it difficult.  The month, day, and hour are expected to be either 0 or space padded but they are not.   I'm not sure what else out there is parsing these logs but we may want to add an option to turn this on so as to not break existing setups.  Thoughts?

**Comment by fredbcode** [comment]
I'm not using timestamp format right now,  please can you post a sample here ?

Le 8 mars 2018 17:33:44 GMT+01:00, Orion Poplawski <notifications@github.com> a écrit :
>I'm working on a logwatch filter for e2guardian but the log timestamp
>format is making it difficult.  The month, day, and hour are expected
>to be either 0 or space padded but they are not.   I'm not sure what
>else out there is parsing these logs but we may want to add an option
>to turn this on so as to not break existing setups.  Thoughts?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/354

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by opoplawski** [comment]
So currently access log has:
```
2018.3.8 9:59:20
```
And I would like:
```
2018.03.08 09:59:20
```
Which I have done with this patch:
```
diff -up e2guardian-4.1.4/src/FatController.cpp.padtime e2guardian-4.1.4/src/FatController.cpp
--- e2guardian-4.1.4/src/FatController.cpp.padtime      2017-12-04 01:40:58.000000000 -0700
+++ e2guardian-4.1.4/src/FatController.cpp      2018-03-08 09:37:54.093306327 -0700
@@ -982,18 +982,25 @@ void log_listener(std::string log_locati
             tmnow = localtime(&tnow); // convert to local time (BST, etc)
             year = String(tmnow->tm_year + 1900);
             month = String(tmnow->tm_mon + 1);
+            if (month.length() == 1) {
+                month = "0" + month;
+            }
             day = String(tmnow->tm_mday);
+            if (day.length() == 1) {
+                day = "0" + day;
+            }
             hour = String(tmnow->tm_hour);
-            temp = String(tmnow->tm_min);
-            if (temp.length() == 1) {
-                temp = "0" + temp;
+            if (hour.length() == 1) {
+                hour = "0" + hour;
+            }
+            min = String(tmnow->tm_min);
+            if (min.length() == 1) {
+                min = "0" + min;
             }
-            min = temp;
-            temp = String(tmnow->tm_sec);
-            if (temp.length() == 1) {
-                temp = "0" + temp;
+            sec = String(tmnow->tm_sec);
+            if (sec.length() == 1) {
+                sec = "0" + sec;
             }
-            sec = temp;
             when = year + "." + month + "." + day + " " + hour + ":" + min + ":" + sec;
             // append timestamp if desired
             if (o.log_timestamp)
```
Might be better at this point to use something like strftime().

**Comment by fredbcode** [comment]
Please test the my latest push

**Comment by opoplawski** [comment]
The problem now is that the year has gone to 2 digits only, so we've gone from 2018.9.18 to 18.09.19.
