### ISSUE TITLE
v5develop - squid log format not logging ip address and register tcp_miss on access denied

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#359]
Squid logs does not include client ip and access denied page shows as tcp_miss.
scenario:
Version 5.0.1
transparente and non proxy  http and https
not interception traffic on group config but ssl inspect enabled.

![image](https://user-images.githubusercontent.com/926309/37318731-e84c1e16-264a-11e8-87f2-4c4ac979c21d.png)

with ssl interception enabled, same issue in transparent and normal mode

![image](https://user-images.githubusercontent.com/926309/37318830-4f356c9a-264b-11e8-9ff1-734deb942cfb.png)

**Comment by fredbcode** [comment]
Related with resolv IP client ?

**Comment by fredbcode** [comment]
I pushed some fixes in v4, I guess I missed v4, I will check

**Comment by fredbcode** [comment]
I mean, I missed v5 of course

**Comment by fredbcode** [comment]
Please test now

**Comment by marcelloc** [comment]
fixed on #360 

You guys are doing a really amazing proxy tool with e2guardian5!!!!

**Comment by domanuell** [comment]
Boa tarde Marcelo, estou assistindo a tua aula no sysquad,  acompanhei todos  os passos mais mesmo ela nao registra no Real Time: 

![image](https://user-images.githubusercontent.com/47576932/115562982-f5fdeb00-a2ae-11eb-834e-8329a8313e12.png)

estou a atualizar a versão 2.5

**Comment by domanuell** [comment]
não filtra nada

**Comment by marcelloc** [comment]
> não filtra nada

verifica na console se o processo do e2guardian está rodando.
Se estiver, pode ser um processo preso que está impedindo o reload quando você aplica alguma configuração. 
Se for este o caso, via console, execute um killall e2guardian e aguarde o watchdog do pacote subir outro processo.

**Comment by domanuell** [comment]
![image](https://user-images.githubusercontent.com/47576932/115661529-78c98900-a335-11eb-97dc-d31a872c4dcc.png)
![image](https://user-images.githubusercontent.com/47576932/115661779-e83f7880-a335-11eb-8912-0e40425b44fa.png)
![image](https://user-images.githubusercontent.com/47576932/115661838-fe4d3900-a335-11eb-8987-6f28b44e12b0.png)
![image](https://user-images.githubusercontent.com/47576932/115662016-44a29800-a336-11eb-9a45-14e03456fd54.png)
![image](https://user-images.githubusercontent.com/47576932/115662094-63089380-a336-11eb-931e-c94934908f21.png)
![image](https://user-images.githubusercontent.com/47576932/115662178-829fbc00-a336-11eb-9ef8-50f4c82940d2.png)
![image](https://user-images.githubusercontent.com/47576932/115662307-b2e75a80-a336-11eb-9559-b27696d648cf.png)


Mesmo fazendo o recomendado, infelizmente não funciona.

estou a sofrer meu amigo, ajuda-me...
