### ISSUE TITLE
v5develop - e2guardian denied logged as 200 ok

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#360]
![image](https://user-images.githubusercontent.com/926309/37319158-bb1b4726-264c-11e8-8731-b4f5948f21b8.png)

e2guardian5 is loging denied page with 200ok instead of 403

![image](https://user-images.githubusercontent.com/926309/37319356-8c5f500c-264d-11e8-8422-b9cb9a77cd52.png)

**Comment by fredbcode** [comment]
No 403 at all ? Never ?

**Comment by PhilCode4U** [comment]
It's a bug in v5 of E2guardian, not in v4

**Comment by fredbcode** [comment]
I will take a look, soon

**Comment by philipianpearce** [comment]
This is not a bug - the logs log what HTTP status code is sent back to the client. 

In the case of a deny page this has always been 200 OK. If you use log format 5 or 6 you will get two codes the http response code and the e2g code 5nn which will tell you it's denied. 

Sending a 403 would give misleading information to the browser, as it would indicate that the target server is refusing access, rather than the proxy. 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
This is unclear I think, dolog should log 403 and returns a web page (with 200)

I will check in v4, I can't now, but I'm pretty sure that I saw 403 lines before


Le 13 mars 2018 12:44:42 GMT+01:00, Philip Pearce <notifications@github.com> a écrit :
>This is not a bug - the logs log what HTTP status code is sent back to
>the client. 
>
>In the case of a deny page this has always been 200 OK. If you use log
>format 5 or 6 you will get two codes the http response code and the e2g
>code 5nn which will tell you it's denied. 
>
>Sending a 403 would give misleading information to the browser, as it
>would indicate that the target server is refusing access, rather than
>the proxy. 
>
>Regards 
>
>Philip 
>
>----- Original Message -----
>
>> From: "PhilCode4U" <notifications@github.com>
>> To: "e2guardian/e2guardian" <e2guardian@noreply.github.com>
>> Cc: "Subscribed" <subscribed@noreply.github.com>
>> Sent: Tuesday, 13 March, 2018 10:33:17 AM
>> Subject: Re: [e2guardian/e2guardian] v5develop - e2guardian denied
>> logged as 200 ok (#360)
>
>> It's a bug in v5 of E2guardian, not in v4
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub , or mute the thread
>> .
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/360#issuecomment-372637674

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by philipianpearce** [comment]
Yes, you are right! 

v4 does log a 403 on deny. 

I will have a look at this. 

Regards 

Philip 

----- Original Message -----

> From: "Fredb" <notifications@github.com>
> To: "e2guardian/e2guardian" <e2guardian@noreply.github.com>
> Cc: "Philip Pearce" <philip.pearce@e2bn.org>, "Comment"
> <comment@noreply.github.com>
> Sent: Tuesday, 13 March, 2018 11:53:04 AM
> Subject: Re: [e2guardian/e2guardian] v5develop - e2guardian denied
> logged as 200 ok (#360)

> This is unclear I think, dolog should log 403 and returns a web page
> (with 200)

> I will check in v4, I can't now, but I'm pretty sure that I saw 403
> lines before

> Le 13 mars 2018 12:44:42 GMT+01:00, Philip Pearce

**Comment by philipianpearce** [comment]
Please test and if OK close

**Comment by fredbcode** [comment]
Philip, FI I switched to logformat 6 by default 
https://github.com/e2guardian/e2guardian/commit/caa85f99b9e4df242631cdf1cfcf1baeb581b4d4

**Comment by marcelloc** [comment]
Looks perfect now.

![image](https://user-images.githubusercontent.com/926309/37350299-3a68e49c-26b7-11e8-9275-ec5d1ef82730.png)
