### ISSUE TITLE
Не работает https filtering

### ISSUE THREAD

**Issue by maslonax** [e2guardian/e2guardian#361]
Добрый день, установил squid, настроил его так что все имеют всегда доступ. Установил e2guardian по инструкции "установка на Ubuntu или Debian". Настроил ip и port, в bannedsitelist указал **, в exceptionsitelist и exceptionurllist указываю сайты, при проверке все работает. Потребовалось открывать часть сайта https, решил настроить по инструкии  : https://github.com/e2guardian/e2guardian/wiki/MITM---Filtering-HTTPS
в конфиге:
ssllegacylogic = off
onlymitmsslgrey = 'off'
Настроил lighttpd и WPAD. Компьютеры автоматически получают настройки прокси сервера.
Сертификаты установил на компьютере.
При проверке обратиться к разрешеной странице запрещеного сайта https в google chrome я вижу следующую ошибку: 

Не удается получить доступ к сайту
Веб-страница по адресу https://vk.com/cariera1, возможно, временно недоступна или постоянно перемещена по новому адресу.
ERR_TUNNEL_CONNECTION_FAILED

Буду очень благодарен если поможете с этим разобратся.

**Comment by Kenny690** [comment]
Какая версия e2? Неплохо было бы посмотреть конфиги.

**Comment by maslonax** [comment]
e2guardian -v
e2guardian 4.1.4

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CFLAGS=-g -O2 -g -Wall -O2' 'LDFLAGS=' 'CPPFLAGS=' 'CXXFLAGS=-g -O2 -g -Wall -O2'


[конфиг e2.zip](https://github.com/e2guardian/e2guardian/files/1818118/e2.zip)

**Comment by Kenny690** [comment]
У тебя стоит "enablessl = off". Попробуй переключить его и проверить.
Так же, пришли логи сквида и e2.

**Comment by maslonax** [comment]
Все работает, спасибо. Заодно нашел невнимательность в прописание пути к сертификатам перед etc не поставил / . и в одном пути сертификата был прописан ssl2.

**Comment by Kenny690** [comment]
Ну вот и отлично. Закрывай тему. :)

**Comment by fredbcode** [comment]
In english please, otherwise fell free to discuss in our Google group
Thanks
