### ISSUE TITLE
Interpreting dstats.log

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#362]
![image](https://user-images.githubusercontent.com/926309/37538774-725418ce-2930-11e8-9fb8-72297cc59e00.png)

It's a 950 computer network but doesn't matter how I increase max processes, in few minutes it gets on top.

**Comment by marcelloc** [comment]
Not sure if I found the right value for max connections on this network or running it in foreground to see some debug info helped but it's increasing and decreasing according to traffic.

![image](https://user-images.githubusercontent.com/926309/37544239-0b19a65c-2943-11e8-95f0-bfd6b02ef8cf.png)

**Comment by marcelloc** [comment]
It was a massive connections due a misconfigured wan port by sysadmin. It was really with that amount of connections...

**Comment by GabrielLonghi** [comment]
Olá Marcello! Estou com o mesmo problema, aba BUSY, fica sempre sobrando workers e do nada fica no máximo! Segue a foto para que me auxilie! Obrigadão! 
![WhatsApp Image 2019-12-05 at 22 02 49 (1)](https://user-images.githubusercontent.com/58576986/70286732-16f19900-17ab-11ea-9674-f31cee003a42.jpeg)
![WhatsApp Image 2019-12-05 at 22 02 49](https://user-images.githubusercontent.com/58576986/70286733-16f19900-17ab-11ea-8297-439d89469f61.jpeg)
