### ISSUE TITLE
4.1.4 segfault (NTLM auth)

### ISSUE THREAD

**Issue by VasiliyF** [e2guardian/e2guardian#363]
I'm using e2guardian 4.1.4 with MITM and NTLM auth. Today I have get many segfault:
Mar 20 10:30:49 school72 e2guardian[1469]: NTLM - step 2 was not part of an auth handshake! (Accept-Encoding: identity,gzip,deflate#015)
Mar 20 10:30:49 school72 e2guardian[1469]: Auth plugin returned error code: -1
Mar 20 10:33:01 school72 e2guardian[1469]: NTLM - step 2 was not part of an auth handshake! (http://detectportal.firefox.com/success.txt)
Mar 20 10:33:01 school72 e2guardian[1469]: Auth plugin returned error code: -1
Mar 20 10:33:21 school72 e2guardian[1469]: NTLM - step 2 was not part of an auth handshake! (Proxy-Authenticate: NTLM#015#012)
Mar 20 10:33:21 school72 e2guardian[1469]: Auth plugin returned error code: -1
Mar 20 10:34:56 school72 kernel: [3633890.561038] e2guardian[1989]: segfault at 31ff560 ip 00007f6a55a2504e sp 00007f6914e2c498 error 4 in libc-2.19.so[7f6a55993000+1a1000]
Mar 20 10:34:56 school72 e2guardian[1469]: NTLM - step 2 was not part of an auth handshake! (http://service.weather.microsoft.com/appex/DesktopTile/PreInstallLiveTile?lang=ru-RU&region=RU&a
ppid=C98EA5B0842DBB9405BBF071E1DA76512D21FE36&FORM=APXWEA)
Mar 20 10:34:56 school72 e2guardian[1469]: Auth plugin returned error code: -1
Mar 20 10:34:56 school72 e2guardian[1469]: NTLM - step 2 was not part of an auth handshake! (Server: squid/3.4.8#015#012)
Mar 20 10:34:56 school72 e2guardian[1469]: Auth plugin returned error code: -1
Mar 20 10:35:46 school72 named[628]: error (network unreachable) resolving '18.146.20.115.in-addr.arpa/PTR/IN': 2001:67c:e0::9#53
Mar 20 10:35:46 school72 named[628]: error (network unreachable) resolving '18.146.20.115.in-addr.arpa/PTR/IN': 2001:dc0:2001:0:4608::25#53
Mar 20 10:35:46 school72 named[628]: error (network unreachable) resolving '18.146.20.115.in-addr.arpa/PTR/IN': 2001:67c:1010:27::53#53
Mar 20 10:37:22 school72 systemd[1]: Starting E2guardian Web filtering...
Mar 20 10:37:22 school72 systemd[1]: Started E2guardian Web filtering.
Mar 20 10:37:22 school72 e2guardian[2936]: Started successfully.

**Comment by fredbcode** [comment]
Works well without NTLM and same configurations ?
Why do you have so many "Mar 20 10:35:46 school72 named[628]: error (network unreachable) resolving '18.146.20.115.in-addr.arpa/PTR/IN': 2001:67c:e0::9#53" ?

**Comment by VasiliyF** [comment]
After increasing ntlm helpers and rebooting , segfault no more appears.
