### ISSUE TITLE
SSL Site Rewriting - Youtube

### ISSUE THREAD

**Issue by forid786** [e2guardian/e2guardian#365]
Hi,

First of all I'd like to start out by saying that E2Guardian v5 is absolutely amazing. It's been scaling a lot better, and has worked out a lot of the kinks I've had in the past. However, I've started having one issue.

I use SSL Rewriting via Regex on E2Guardian to force Youtube Restricted for certain usergroups. Here's what I'm using below, it comes standard with E2Guardian.

# Enforce restricted mode in YouTube
#
"(^https://www.youtube.com)"->"https://restrict.youtube.com"
"(^https://m.youtube.com)"->"https://restrict.youtube.com"
"(^https://youtubei.googleapis.com)"->"https://restrict.youtube.com"
"(^https://youtube.googleapis.com)"->"https://restrict.youtube.com"
"(^https://www.youtube-nocookie.com)"->"https://restrict.youtube.com"
#

Since upgrading it seems to have stopped working. Youtube restricted is no longer being enforced, even though MITM and the rest are working fine. Does anyone else here use this feature of E2Guardian and does it work for you? 
It's quite an important feature for me as using the DNS method doesn't work well for me if I want to enforce Youtube restricted for certain groups while allowing others. I've been using this since 3.5.1 and it has seemed to work pretty well.  

EDIT:
e2guardian 5.1.0
OS: FreeBSD (pfSense)

Built with:  '--localstatedir=/var' '--with-logdir=/var/log' '--with-piddir=/var/run' '--with-zlib=/usr' '--enable-fancydm' '--disable-clamd' '--disable-commandline' '--enable-dnsauth' '--disable-email' '--disable-icap' '--disable-kavd' '--enable-ntlm' '--enable-sslmitm' '--enable-trickledm' '--prefix=/usr/local' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd11.1' 'build_alias=amd64-portbld-freebsd11.1' 'CXX=c++' 'CXXFLAGS=-O2 -pipe  -I/usr/local/include -D__SSLMITM -D__SSLCERT -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing  -DLIBICONV_PLUG -std=c++11' 'LDFLAGS= -lssl -lcrypto -fstack-protector' 'LIBS=' 'CPPFLAGS=-I/usr/local/include -DLIBICONV_PLUG' 'CC=cc' 'CFLAGS=-O2 -pipe  -I/usr/local/include -D__SSLMITM -D__SSLCERT -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing' 'CPP=cpp' 'PKG_CONFIG=pkgconf'

**Comment by forid786** [comment]
- Spoke to @marcelloc who is maintaining the pfSense package, seems like it could be due to the v5 configuration style and some work needs to be done there.

- Closing the issue for now until we can confirm where the problem lies.

**Comment by forid786** [comment]
This one is a strange one, it seems to work for m.youtube.com after some fiddling. But it doesn't matter what I do on the desktop, I cannot get it to work. 

As mentioned before MITM works perfectly fine and users are getting the cert from my internal CA.

**Comment by philipianpearce** [comment]
Hi, 

Yes, this may be partly a config issue, although if you are using the standard storyboard the sslreplace should work OK with or without MITM. 

To enforce Youtube restricted on with MITM the more flexible add header method can used. 

I have updated the example addheaderregexplist with some example regexp (v5.0 and v5develop) 

Regards 

Philip 

----- Original Message -----

**Comment by forid786** [comment]
I've just tried with both the header method and the site list method. Both didn't seem to work when trying to enforce Youtube restricted mode for the desktop.

Here's what I got now in a header under the replace option, enabled and assigned to groups. I'm not sure if I'm doing something wrong but I don't seem to be having much luck with this.

## to enable restricted YouTube 
"(^http://www\.youtube\.com/.*$)"->"YouTube-Restrict: Strict" 
"(^http://m\.youtube\.com/.*$)"->"YouTube-Restrict: Strict" 
"(^http://youtubei\.googleapis\.com/.*$)"->"YouTube-Restrict: Strict" 
"(^http://youtube\.googleapis\.com/.*$)"->"YouTube-Restrict: Strict" 
"(^http://www\.youtube-nocookie\.com/.*$)"->"YouTube-Restrict: Strict" 
"(^http://www\.youtube\.com$)"->"YouTube-Restrict: Strict" 
"(^http://m\.youtube\.com$)"->"YouTube-Restrict: Strict" 
"(^http://youtubei\.googleapis\.com$)"->"YouTube-Restrict: Strict" 
"(^http://youtube\.googleapis\.com$)"->"YouTube-Restrict: Strict" 
"(^http://www\.youtube-nocookie\.com$)"->"YouTube-Restrict: Strict"

**Comment by forid786** [comment]
SSL re-write is working fine on newer versions again!! - However, the header replacement isn't working. Maybe I have done something incorrect here?

**Comment by philipianpearce** [comment]
No nothing you are doing!     The addheader list was not defined in e2guardianf1.conf.in.

This is corrected in latest v5.1

**Comment by forid786** [comment]
Hi Philip,

Thanks for the fix. You are a legend!!

I'm still running an older V5 Develop, I'll ask @Marcelloc to update his repo as I'm running this on pfSense. 

I've not messed around with headers too much. So can the header be inserted without MITM?

**Comment by fredbcode** [comment]
> 
> 
> Hi Philip,
> 
> Thanks for the fix. You are a legend!!

I agree !

**Comment by forid786** [comment]
@fredbcode You're a legend too, I've just been snooping through your V5.1 commits!!

Keep up the amazing work!

**Comment by marcelloc** [comment]
It's working on 5.1 with Freebsd too.

Thanks for the really amazing work on e2guardian.

**Comment by marcelloc** [comment]
Is safe search engine under url filter with MITM working on 5.1?

**Comment by philipianpearce** [comment]
Glad that it is working now. 

"So can the header be inserted without MITM?" 

Depends on mode:- 

If with http site via transparent or explicit proxy or ICAP - yes. 

With https transparent - no - only with MITM. 

With https explicit proxy and squid - technically yes, but will not work as will be inserted into CONNECT request which will only get to squid not to the target site. So really, it will only work with MITM. 

Regards 

Philip 

----- Original Message -----

**Comment by forid786** [comment]
@marcelloc I still can't use the header method in order to force restricted mode, for now I am just relying on the SSL re-write method which works.

Is this because the configurations still need to be sorted out for 5.1 on your pfSense package?

**Comment by marcelloc** [comment]
Me too, I can't force google safe search for example. If it's just a config option, let me know the right conf options to check on pfSense gui package.

**Comment by Dalacor** [comment]
Should one be using the addheaderregexplist instead of the settings in sslsiteregexplist for Google Safe Search and Youtube Safe Mode? The settings appear to be in both files, but are slightly different.

On a separate note @forid786 do you use Youtube Strict as opposed to Moderate? Some years ago I tried strict but we found that far too many Youtube videos were being blocked that should not have been blocked? However, i think that Moderate is perhaps a bit too moderate!

**Comment by forid786** [comment]
@Dalacor Strict has become much better but still overblocks but the best way to filter at least in my scenario is assign all the kids YouTube strict and then have adults unfiltered. There's no perfect way to filter YouTube unless you use some kind of approval system.

**Comment by Dalacor** [comment]
Thank you for a very quick response. I see that you are online at the same time as me. I actually just asked you a question on two of your other topics - one about Google Search on your topic phraselists need an update and the other question was on your closed topic Categories not showing for Blacklists as I am hoping that you were able to solve that issue.

I have been having fun with the new version of E2guardian that I have installed very recently.

**Comment by forid786** [comment]
@Dalacor Yeah it's 7PM in the UK now, I guess you're from the US? Unfortunately with the phraselists I'm still using stock. Its not been too much of an issue for me at home. But in a actual school setting for example, I'd never recommend the stock phrase lists. They're just too outdated. And for most people it's  a little too time consuming to make their own list, as I mentioned I don't mind donating for decent phrase lists.

This is actually one of the reasons why Smoothwall blew me away, they're quite far ahead with these things. But I guess it's because they've poached some devs.

**Comment by Dalacor** [comment]
@forid786 No I am in the UK like you! Just working very late! I have spent the day on E2guardian today.

I am going to use the GoogleSearch terms in the phraselists whatever prhaselists E2guardian comes with to create a bannedsearchlist which will apply to all search engines. This will solve most of the issues I might have with Google Search. I am hoping to complete this particular job this weekend. If I can get the bannedsearchlist 100% effective this will make the biggest difference as people use Google to find websites therefore it makes sense to concentrate on filtering search results.

Yes I agree that the stock phraselists are too outdated and I don't have many of them active. However, I do use some of them as its better than nothing. I deal with primary schools and the main focus is preventing accidental access to inappropriate sites rather than preventing kids doing everything they can to get around the filters as it were!

But I will see if I can buy phraselists for all languages from somebody who is developing, preferably E2BN if they ever get around to creating a subscription system for this as I fully agree that the phraselists need a drastic overhaul.

**Comment by forid786** [comment]
@Dalacor Wow I didn't know you're in the UK, pretty cool. Today luckily I started work very early so I finished earlier. Although I've spent time building firewalls and IPS systems so not much on the E2G front.

Hit me up if you're interested in working together. I've never used E2BN before so can't vouch how much better it is compared to E2 Guardian. But I can say for Smoothwall once it's setup right it pretty much blocks all circumvention with the help of tight GPO's.

**Comment by Dalacor** [comment]
@forid786 I will be happy to pass on any improvements that I manage to make such as the bannedsearchlist which I am hoping to create this weekend. I think that this will help everyone a lot as this will make a huge difference to E2guardian if Google Search Results are better filtered.

Don't know how much help I will be to you though as I suspect that you are better with E2guardian than I am. I have only just in the last month managed to move to MITM etc. I have been on V3 for a long while.

If you do have two minutes if you like would you be able to see how your E2guardian fixed the Categories issue for banned sites as the only way that I could get the Categories to show will be to edit each domain file in each category of the blacklists. Which is problematic if you automatically update the blacklists which I do.

In addition, can you see if -HOST- on your template.html file actually shows your computer name. For some reason, E2guardian shows the computer name in the Access.log file but is blank on the template.html view when you hit a banned website. Don't know wy.

**Comment by Dalacor** [comment]
> @Dalacor Strict has become much better but still overblocks but the best way to filter at least in my scenario is assign all the kids YouTube strict and then have adults unfiltered. There's no perfect way to filter YouTube unless you use some kind of approval system.

I would recommend Strict for the Pupils and Moderate for the Staff. We have no issues with Moderate for the staff, so I would suggest that instead of unfiltered.

**Comment by forid786** [comment]
@Dalacor Let's just say I've become frustrated enough with moderate, it ends up giving me more problems than solutions. Even things you would possibly not want blocked, somehow end up blocked...

**Comment by Dalacor** [comment]
Update on this issue:

Using E2guardian 5.3.1 with MITM currently off as I don't want to setup certificates yet!

addheaderregexplist - does not work at all (This may need MITM?)
sslsiteregexplist - works flawlessly for Youtube in both transparent and explicit proxy mode
sslsiteregexplist - Google SafeSearch - #"https://www\.google\.[a-zA-Z0-9_.]*$)"->"https://forcesafesearch.google.com" - There is a typo in this file. It should have a (^ at the beginning of the line after the inverted commas. Changing this ensures that Google Safe Search works in both transparent and explicit proxy (don't know about MITM yet).

As a matter of interest, on my old system I have the syntax as: "(^https://www\.google\..*)"->"https://forcesafesearch.google.com." I wonder if we should use ..* or .{a-zA-Z0-9_.}*$ they both seem to do the same thing!

I will be opening up a new Issue to report typos in files.

**Comment by fredbcode** [comment]
I can close ?

**Comment by forid786** [comment]
This seems to be resolved on the newer versions of E2 Guardian, thank you for fixing it. I'll go ahead and close this off for you.

To anyone else reading, please be aware that Youtube may not "say" that it's in restricted mode but if you try to play a restricted video. You will not be able to and it will ask you to log into a GSuite account, whether you do login to one or not, it will keep displaying that message on restricted videos. At least this is the behaviour I have seen with the config @philipianpearce provided.

**Comment by forid786** [comment]
@Dalacor Just spotted your comment above as well. 

-Host- Works for me however I did have to setup my DHCP to register those host names. In terms of fixing categories, I did that by switching my Blacklist to a sightly better one - I use this: https://dsi.ut-capitole.fr/blacklists/index_en.php

If you still have problems, open a separate issue to discuss those. As this issue was meant to be relating to the SSL Site rewriting.

**Comment by Dalacor** [comment]
@forid786 

Host was because there was a bug in E2guardian which has been fixed. You did not see the issue because pfsense fixed that bug within the distro.
Thanks for the link to that blacklist. I will have a look at that. It does look very similar to big backlist from urlblacklist.

Yes, I will open up a separate issue on anything I need to do. Thanks
