### ISSUE TITLE
v5develop - SSL_ERROR_RX_RECORD_TOO_LONG response with  **s or *ips 

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#367]
SSL sites denied by **s and **ips story directive are receiving SSL_ERROR_RX_RECORD_TOO_LONG instead of connection refused while intercepting.

Intercepting and filtering ssl I get a blank page instead of denied error.

**Comment by fredbcode** [comment]
With or without SSLBump ? without blank is the usual behaviour

**Comment by marcelloc** [comment]
With SSLBump, I get a blank page. Without SSLBump but with SSL enabled, I get the RX_RECORD_TOO_LONG

**Comment by fredbcode** [comment]
We need a trace please (wireshark format)

**Comment by marcelloc** [comment]
dump with exception sites enabled and youtube.com not on exception list.

**ssl enabled but no sslbump**
[tcpdump_https_exception_enabled.dump.gz](https://github.com/e2guardian/e2guardian/files/1846807/tcpdump_https_exception_enabled.dump.gz)

**with sslbump**
[tcpdump_https_sslbump_exception_enabled.dump.gz](https://github.com/e2guardian/e2guardian/files/1846818/tcpdump_https_sslbump_exception_enabled.dump.gz)

**Comment by fredbcode** [comment]
Please try this
"if(connect) return true" in common.story file (at first place)

**Comment by marcelloc** [comment]
just saw this running e2guardian with -QN

**Comment by fredbcode** [comment]
if(true,,502) return setblock # = ** total blanket ??
Just remove "# = ** total blanket" in g_Liberado.story

**Comment by fredbcode** [comment]
As you can see here, StoryBoard error: Action not defined setblock # = ** total blanket at line 44" 
It seems your comment is read by e2guardian

**Comment by marcelloc** [comment]
Yes. My mistake. I misunderstood sample file and leaved the comment out there.

Thanks again for the fast response
