### ISSUE TITLE
v5develop - timed out/blank page with ** and **ip

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#368]
While using ** and **ip sites no listed on exception list does not receive a deny page. It keeps loading and finish with a blank page after 1 minute.

**Comment by fredbcode** [comment]
What do you have in logs ? Can you share a tcpdump trace

**Comment by marcelloc** [comment]
This is the dump for an http request.
Between the first request and the blank page, there are two or three requests to http://detectportal.firefox.com/success.txt made by mozilla firefox.

The complete connection looks like be the 192.168.25.10.63030 > pfSense.lab.local.8080

I'm have proxy configured on my browser.

[tcpdump_http_exception_enabled.dump.gz](https://github.com/e2guardian/e2guardian/files/1846790/tcpdump_http_exception_enabled.dump.gz)

**Comment by marcelloc** [comment]
My mistake. I misunderstood sample file and leaved the comment out there. #367 

Thanks again for the fast response
