### ISSUE TITLE
Segfault on some systems. 4.1.4

### ISSUE THREAD

**Issue by VasiliyF** [e2guardian/e2guardian#369]
I have problem whith segfault on some systems, modern systems, 64-bit.
My configuration: debian 8, CPU  Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz, 8 GB RAM, e2guardian 4.1.4, basic auth, MITM.
Several times a day, I get segafult:

`Mar 30 09:43:46 school57 kernel: [152473.521244] e2guardian[26267]: segfault at 1adc1d20 ip 0000000000428839 sp 00007fabd84a9cd0 error 4 in e2guardian[400000+e8000]`
`Mar 30 09:44:00 school57 systemd[1]: Starting E2guardian Web filtering...`
`Mar 30 09:44:00 school57 systemd[1]: Started E2guardian Web filtering.`
`Mar 30 09:44:00 school57 e2guardian[1849]: Started successfully.`
`Mar 30 09:44:00 school57 kernel: [152486.883210] e2guardian[1851]: segfault at 1ac64d20 ip 0000000000428839 sp 00007fb8bde8ccd0 error 4 in e2guardian[400000+e8000]`
`Mar 30 09:47:00 school57 systemd[1]: Starting E2guardian Web filtering...`
`Mar 30 09:47:00 school57 systemd[1]: Started E2guardian Web filtering.`
`Mar 30 09:47:00 school57 e2guardian[2997]: Started successfully.`
`Mar 30 09:47:00 school57 kernel: [152667.275443] e2guardian[2999]: segfault at 1a7cdd20 ip 0000000000428839 sp 00007ff7ed88ccd0 error 4 in e2guardian[400000+e8000]`

On another system (same software, same configuration), but CPU  Intel(R) Pentium(R) D CPU 3.40GHz, 4GB RAM e2guardian works fine.

**Comment by fredbcode** [comment]
Do you have the knowledge needed to recompile the binary ?
A test with this option should be very interesting  

 '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' '**CPPFLAGS=-mno-sse2** -frecord-gcc-switches -g3 -O0' '--with-dgdebug=off'

**Comment by VasiliyF** [comment]
I have recompiled binary with this flags:

`# e2guardian -v
e2guardian 4.1.4

`Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -frecord-gcc-switches -g3 -O0' '--with-dgdebug=off'
`
Today I got some segfault:
`Apr  2 08:53:04 school57 arpwatch: new station 10.100.100.186 94:e9:79:a9:17:c5 eth0`
`Apr  2 08:53:08 school57 kernel: [408381.292576] e2guardian[10188]: segfault at 1bb80d20 ip 0000000000428839 sp 00007fe5df78fcd0 error 4 in e2guardian[400000+e8000]`
`Apr  2 08:54:29 school57 kernel: [408461.823755] e2guardian[11312]: segfault at 1abc8d20 ip 0000000000428839 sp 00007ff865f34cd0 error 4 in e2guardian[400000+e8000]`
`Apr  2 08:55:09 school57 kernel: [408502.388954] e2guardian[12278]: segfault at 1c11bd20 ip 0000000000428839 sp 00007fa397f88cd0 error 4 in e2guardian[400000+e8000]`
`Apr  2 08:55:36 school57 kernel: [408529.294725] e2guardian[13200]: segfault at 1b03fd20 ip 0000000000428839 sp 00007fa6717f3cd0 error 4 in e2guardian[400000+e8000]`
`Apr  2 08:56:37 school57 kernel: [408589.491863] e2guardian[14228]: segfault at 1b9a3d20 ip 0000000000428839 sp 00007f1d64ff2cd0 error 4 in e2guardian[400000+e8000]`

May be add more more gcc options?

**Comment by fredbcode** [comment]
Ok thanks for your help
Now a coredump is needed for deeper investigation.

https://github.com/e2guardian/e2guardian/wiki/F.A.Q

**Comment by fredbcode** [comment]
And also do you have something more in syslog ? Can you make a try with 'develop' branche ?

**Comment by VasiliyF** [comment]
Syslog contain only segfaut message and start/stop message from systemd (e2g is started  with monit, when it fail).
Yesterday I disabled MITM, but this morning I have get segfault 3 times

`Apr  3 09:01:22 school57 kernel: [75433.559567] e2guardian[7210]: segfault at 1b2fad20 ip 000000000042883b sp 00007f073c4339b0 error 4 in e2guardian[400000+e8000]`
`Apr  3 09:01:37 school57 arpwatch: new station 10.100.100.174 00:24:1d:9f:fc:b8 eth0`
`Apr  3 09:01:39 school57 systemd[1]: Starting E2guardian Web filtering...`
`Apr  3 09:01:39 school57 systemd[1]: Started E2guardian Web filtering.`
`Apr  3 09:01:39 school57 e2guardian[13754]: Started successfully.`
`Apr  3 09:02:15 school57 kernel: [75485.992112] e2guardian[13953]: segfault at 1c223d20 ip 000000000042883b sp 00007f072ef589b0 error 4 in e2guardian[400000+e8000]`
`Apr  3 09:02:39 school57 systemd[1]: Starting E2guardian Web filtering...`
`Apr  3 09:02:39 school57 systemd[1]: Started E2guardian Web filtering.`
`Apr  3 09:02:39 school57 e2guardian[14801]: Started successfully.`
`Apr  3 09:03:23 school57 crontab[15996]: (root) LIST (root)`
`Apr  3 09:03:24 school57 puppet-agent[15818]: Applied catalog in 3.19 seconds`
`Apr  3 09:03:35 school57 kernel: [75566.563034] e2guardian[14939]: segfault at 1c38bd20 ip 000000000042883b sp 00007fb4177919b0 error 4 in e2guardian[400000+e8000]`
`Apr  3 09:03:39 school57 systemd[1]: Starting E2guardian Web filtering...`
`Apr  3 09:03:39 school57 systemd[1]: Started E2guardian Web filtering.`
`Apr  3 09:03:39 school57 e2guardian[16105]: Started successfully.`

I'm trying to take a coredump today.

**Comment by fredbcode** [comment]
Ok thanks, and please if you can https://github.com/e2guardian/e2guardian/tree/develop

```
git clone https://github.com/e2guardian/e2guardian.git
cd e2guardian
git checkout develop
git pull
./autogen.sh
./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -frecord-gcc-switches -g3 -O0' '--with-dgdebug=off'
make
```

**Comment by VasiliyF** [comment]
[Link to the coredumps](https://cloud.tgl.net.ru/index.php/s/mKAGxcukLj6EpMM/download)

**Comment by VasiliyF** [comment]
With the 4.1.4 develop i have get the same error. 
[coredumps 4.1.4.1](https://cloud.tgl.net.ru/index.php/s/rRIGq416cST9QDf)

**Comment by fredbcode** [comment]
Great, now the exact binary is needed for investigation
Please try this

```
gdb /usr/sbin/e2guardian /path/corefile
bt

(eguardian = binary who generated the core)
```

And copy/past the result here, for both core

**Comment by VasiliyF** [comment]
**4.1.4**
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/e2guardian'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000428839 in std::_Deque_iterator<ListContainer*, ListContainer*&, ListContainer**>::_M_set_node (this=0x7f7dc3d10d60, __new_node=0xf080da8)
    at /usr/include/c++/4.9/bits/stl_deque.h:241
241             _M_first = *__new_node;
(gdb) bt
#0  0x0000000000428839 in std::_Deque_iterator<ListContainer*, ListContainer*&, ListContainer**>::_M_set_node (this=0x7f7dc3d10d60, __new_node=0xf080da8)
    at /usr/include/c++/4.9/bits/stl_deque.h:241
#1  0x0000000000427f9f in std::_Deque_iterator<ListContainer*, ListContainer*&, ListContainer**>::operator+= (this=0x7f7dc3d10d60, __n=1953775904)
    at /usr/include/c++/4.9/bits/stl_deque.h:203
#2  0x0000000000426d50 in std::_Deque_iterator<ListContainer*, ListContainer*&, ListContainer**>::operator+ (this=0x6ea5d8 <o+2072>, __n=1953775904)
    at /usr/include/c++/4.9/bits/stl_deque.h:214
#3  0x000000000042582d in std::_Deque_iterator<ListContainer*, ListContainer*&, ListContainer**>::operator[] (this=0x6ea5d8 <o+2072>, __n=1953775904)
    at /usr/include/c++/4.9/bits/stl_deque.h:230
#4  0x0000000000424409 in std::deque<ListContainer*, std::allocator<ListContainer*> >::operator[] (this=0x6ea5c8 <o+2056>, __n=1953775904) at /usr/include/c++/4.9/bits/stl_deque.h:1250
#5  0x0000000000487ad3 in FOptionContainer::inSearchList (this=0x8e4490, words=..., list=1953775904, lastcategory=...) at FOptionContainer.cpp:1397
#6  0x000000000048824d in FOptionContainer::inBannedSearchOverideList (this=0x8e4490, words=...) at FOptionContainer.cpp:1524
#7  0x0000000000488183 in FOptionContainer::inBannedSearchList (this=0x8e4490, words=..., lc=...) at FOptionContainer.cpp:1502
#8  0x000000000041d3b8 in ConnectionHandler::requestChecks (this=0x7f7dc3d16c90, header=0x7f7dc3d12590, checkme=0x7f7dc3d12310, urld=0x7f7dc3d133d0, url=0x7f7dc3d133f0,
    clientip=0x7f7dc3d13390, clientuser=0x7f7dc3d16ca0, filtergroup=0, isbanneduser=@0x7f7dc3d1336f: false, isbannedip=@0x7f7dc3d1335f: false, room="") at ConnectionHandler.cpp:3666
#9  0x0000000000412a2c in ConnectionHandler::handleConnection (this=0x7f7dc3d16c90, peerconn=..., ip=..., ismitm=true, proxysock=..., dystat=@0x6e82e8: 0x6e9940 <dstat>)
    at ConnectionHandler.cpp:2061
#10 0x0000000000412197 in ConnectionHandler::handleConnection (this=0x7f7dc3d16c90, peerconn=..., ip=..., ismitm=false, proxysock=..., dystat=@0x6e82e8: 0x6e9940 <dstat>)
    at ConnectionHandler.cpp:1948
#11 0x000000000040c863 in ConnectionHandler::handlePeer (this=0x7f7dc3d16c90, peerconn=..., ip=..., dystat=@0x6e82e8: 0x6e9940 <dstat>) at ConnectionHandler.cpp:390
#12 0x000000000044c0c0 in handle_connections (tindex=781) at FatController.cpp:563
#13 0x000000000045c180 in std::_Bind_simple<void (*(int))(int)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x8c41b8) at /usr/include/c++/4.9/functional:1700
#14 0x000000000045bfff in std::_Bind_simple<void (*(int))(int)>::operator()() (this=0x8c41b8) at /usr/include/c++/4.9/functional:1688
#15 0x000000000045befa in std::thread::_Impl<std::_Bind_simple<void (*(int))(int)> >::_M_run() (this=0x8c41a0) at /usr/include/c++/4.9/thread:115
#16 0x00007f7fca43d970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#17 0x00007f7fcaf13064 in start_thread (arg=0x7f7dc3d17700) at pthread_create.c:309
#18 0x00007f7fc9bad62d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

**4.1.4 dev**
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/e2guardian'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000047e890 in operator+= (__n=<optimized out>, this=<synthetic pointer>) at /usr/include/c++/4.9/bits/stl_deque.h:204
204                 _M_cur = _M_first + (__offset - __node_offset
(gdb) bt
#0  0x000000000047e890 in operator+= (__n=<optimized out>, this=<synthetic pointer>) at /usr/include/c++/4.9/bits/stl_deque.h:204
#1  operator+ (__n=<optimized out>, this=<optimized out>) at /usr/include/c++/4.9/bits/stl_deque.h:214
#2  operator[] (__n=<optimized out>, this=<optimized out>) at /usr/include/c++/4.9/bits/stl_deque.h:230
#3  operator[] (__n=<optimized out>, this=<optimized out>) at /usr/include/c++/4.9/bits/stl_deque.h:1250
#4  FOptionContainer::inSearchList (this=this@entry=0x18a17c0, words=..., list=<optimized out>, lastcategory=...) at FOptionContainer.cpp:1397
#5  0x000000000047e8ee in FOptionContainer::inBannedSearchOverideList (this=this@entry=0x18a17c0, words=...) at FOptionContainer.cpp:1524
#6  0x000000000047e9ae in FOptionContainer::inBannedSearchList (this=0x18a17c0, words=..., lc=...) at FOptionContainer.cpp:1502
#7  0x000000000041613a in ConnectionHandler::requestChecks (this=this@entry=0x7f60c2ffcd60, header=header@entry=0x7f60c2ff9ba0, checkme=checkme@entry=0x7f60c2ff9920,
    urld=urld@entry=0x7f60c2ff91c0, url=url@entry=0x7f60c2ff91a0, clientip=clientip@entry=0x7f60c2ff9200, clientuser=0x7f60c2ffcd70, filtergroup=0, isbanneduser=@0x7f60c2ff9174: false,
    isbannedip=@0x7f60c2ff92b0: false, room="") at ConnectionHandler.cpp:3667
#8  0x00000000004206e2 in ConnectionHandler::handleConnection (this=this@entry=0x7f60c2ffcd60, peerconn=..., ip=..., ismitm=ismitm@entry=true, proxysock=...,
    dystat=@0x6d1e28: 0x6d3960 <dstat>) at ConnectionHandler.cpp:2065
#9  0x000000000041cfab in ConnectionHandler::handleConnection (this=this@entry=0x7f60c2ffcd60, peerconn=..., ip=..., ismitm=ismitm@entry=false, proxysock=...,
    dystat=@0x6d1e28: 0x6d3960 <dstat>) at ConnectionHandler.cpp:1947
#10 0x000000000042a93f in ConnectionHandler::handlePeer (this=this@entry=0x7f60c2ffcd60, peerconn=..., ip=..., dystat=@0x6d1e28: 0x6d3960 <dstat>) at ConnectionHandler.cpp:389
#11 0x000000000044ca0b in handle_connections (tindex=<optimized out>) at FatController.cpp:563
#12 0x00007f6121429970 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007f6121eff064 in start_thread (arg=0x7f60c2ffd700) at pthread_create.c:309
#14 0x00007f6120b9962d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb)

**Comment by VasiliyF** [comment]
I already did it.

> 204 _M_cur = _M_first + (__offset - __node_offset
***(gdb) bt***
#0 0x000000000047e890 in operator+= (__n=, this=) at /usr/include/c++/4.9/bits/stl_deque.h:204
#1 operator+ (__n=, this=) at /usr/include/c++/4.9/bits/stl_deque.h:214

Or not?

**Comment by fredbcode** [comment]
Oh, Yes sorry

**Comment by fredbcode** [comment]
Ok now please compil '--with-dgdebug=on' 

e2guardian >/tmp/debug 2>&1   

And after a crash send us debug file

Thank you for your help

**Comment by VasiliyF** [comment]
[Link to the log](https://cloud.tgl.net.ru/index.php/s/LGhuIzgoK5kLaEM/download)
[Link to the another log](https://cloud.tgl.net.ru/index.php/s/ZEea7Ti6LM4YtWe/download)

**Comment by VasiliyF** [comment]
Good morning!
I have uncommented the #bannedsearchoveridelist = '/etc/e2guardian/lists/bannedsearchoveridelist' (empty bannedsearchoveridelist was created before) in e2guardianf1.conf - no more segfault today.
I'll watch more..

**Comment by fredbcode** [comment]
Yes good point, in debug Search Overide list is involved very interesting
Can you post here your e2guardian.conf and e2guardianfx.conf

**Comment by fredbcode** [comment]
Vasily please try the develop branch (with and without bannedsearchoveridelist=)

**Comment by fredbcode** [comment]
Retry please, I pushed a change

**Comment by VasiliyF** [comment]
E2guardian (dev.) works without segfault now (without bannedsearchoveridelist). 
Thank you.

**Comment by fredbcode** [comment]
Ok great !

**Comment by fredbcode** [comment]
Vasiliy can you try my latest push please ?

**Comment by VasiliyF** [comment]
Ok, I'm trying now.
Seems good.

**Comment by fredbcode** [comment]
Ok, thank you for your help
