### ISSUE TITLE
logclienthostnames and usexforwardedfor not working

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#370]
Is that only my problem? I have e2guardian 5.0.2 and squid 4.0.24 and two problems with them.
First - e2guardian is not getting hostnames while squid does. Second - e2 is not sending client's ip to squid. I see ip address of a server instead.
Can you help me? I tried to solve this by muself, but have no success yet. 
Yesterday I was on 4.x and everything worked fine. I removed it with config before installing 5.0.2
[e2guardian.zip](https://github.com/e2guardian/e2guardian/files/1871570/e2guardian.zip)

**Comment by philipianpearce** [comment]
Is your set-up client -> e2g -> squid or something else? 


Do you mean e2g not logging client hostnames or what? 


In order for squid to see client IP you need to have forwardedfor = yes in e2guardian.conf. 
and squid must be configured to log x-forwarded-for IPs instead of squid client IP. 



Regards 

Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
Thanks for reporting this.

I have found bug with forwardedfor (not working ) - fixed in v5.0 and v5develop branches.

Also I had to add    'log_uses_indirect_client on' as well as follow_x_forwarded_for lines to the squid.conf in order to get forwarded IPs in squid.log.

**Comment by philipianpearce** [comment]
Closed and new issue opened for logclienthostnames issue

**Comment by Kenny690** [comment]
Something's wrong is going on. 
After I turned on forwardedfor I'm getting a lot of errors 

2018.4.6 14:02:36 10.20.25.244 10.20.25.244 https://jim46.mail.ru:443 *DENIED* Failed to nogotiate ssl connection to server CONNECT 0 0 SSL SITE 1 403 - - default - - - - 

If I'm turning off sslmitm I'm not getting https sites at all, but still e2guardian writes code 200 in the log, but actually site didn't open and squid has nothing from e2 in logs.

**Comment by philipianpearce** [comment]
Log shows you are getting a 403 from squid - i.e. squid is denying the request.

I've had this working with this config here - but have had to allow the forwarded IP range in squid for it to work.
