### ISSUE TITLE
V5: SSL Issue

### ISSUE THREAD

**Issue by nwaelti** [e2guardian/e2guardian#371]
Hi all,
I'm trying to re-install e2guardian from scratch in order to use SSL but this time I'm unsuccessful :(
I keep getting that in log: "hw[00]: Failed to get client's original destination IP: Protocol not available"
I'm in transparent HTTP and HTTPS. HTTP works fine...
Can someone please point me in the right direction?
Thanks and cheers,
Nick

**Comment by philipianpearce** [comment]
What operating platform are you using and which version of e2guardian (v5.0 or v5develop)?

**Comment by nwaelti** [comment]
I've tried with V5.0

**Comment by security-sense** [comment]
I have the same problem. I'm working in a clean suse enterprise server 12 SP2.

@nwaelti did you solve it? you said http works fine? when i use "just" squid works fine, i can go internet, but when i enable dansguardian i can't, no http or https.

**Comment by philipianpearce** [comment]
Have you switched ipforwarding in the kernel? Transparent filtering will not work without this on and the appropriate iptables redirects. 

This forum is for bug reporting. For help on set up issues etc please use the community forum on google groups https://groups.google.com/forum/#!forum/e2guardian 

Regards 

Philip 

----- Original Message -----

**Comment by nwaelti** [comment]
Transparent forwarding is done via Firewall NAT'ing so no iptables rules in question...

**Comment by forid786** [comment]
@nwaelti What platform are you on? And which ports are you natting and to where?

**Comment by nwaelti** [comment]
@forid786 I've an OPNSense box that's port forwarding outgoing request going out to 80 and 443 from some clients via a Debian 9.3 where e2Guardian is installed

**Comment by philipianpearce** [comment]
For transparent https to work e2guardian must be running on a server that acts as the network gateway.  

The traffic must not be NATed before e2guardian, as NATing makes it impossible for e2guardian to determine the original destination IP/port.

I am closing this issue, as it is a configuration problem and not an e2guardian bug.
