### ISSUE TITLE
v5develop: Segmantation fault with transparente ssl and dns_auth authplugin

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#374]
Segmentation fault with transparent ssl proxy + dnsauth + redirect_to_auth = "yes" for unauthenticated users.

tested authurl and prefix-auth with both http and https auth urls.

**Comment by marcelloc** [comment]
Do you need any debug info to help identifying this ssl redirect to url issue?

**Comment by marcelloc** [comment]
h.url() seems to be null with transparent ssl connection and causes segmentation fault on dnsauth plugin.

**HTTPHeader.cpp**
String HTTPHeader::getUrl(bool withport, bool isssl)
**answer(header.front().after(" "));** This causes segmentation fault with transparent ssl enabled and dns auth pluging with auth url redirect.

**Comment by philipianpearce** [comment]
Thanks for the report.  I will look at fixing the seg fault.

Note:  dnsauth + redirect_to_auth = "yes" + https  is generally broken in v4 and v5.  I am looking at putting in an option so that it will work using MITM for unauthenticated users.

**Comment by marcelloc** [comment]
If I force a url instead of testing if it has header info, it stop crashing but user receive cert error different from connection refused.

In other error functions mention that a 307 redirect with a small error message could show a deny error on Firefox /ie.

**Comment by philipianpearce** [comment]
Can you try with latest v5develop? 

"In other error functions mention that a 307 redirect with a small error message could show a deny error on Firefox /ie." - this no longer works in modern browsers. 

Thanks 

Philip 

----- Original Message -----

**Comment by marcelloc** [comment]
**result with latest code**

hw309:  -Not got persistent credentials for this connection - querying auth plugins
hw309:  -Querying next auth plugin...
hw309: IPPath is 192.168.25.102
hw309: IPPath is 192-168-25-102

 waiting connection on http_worker_Q
 waiting connection on http_worker_Q
 waiting connection on http_worker_Q

 waiting connection on http_worker_Q

 waiting connection on http_worker_Q









 waiting connection on http_worker_Q












 waiting connection on http_worker_Q

 waiting connection on http_worker_Q










 waiting connection on http_worker_Q


 waiting connection on http_worker_Q


hw1092:  waiting connection on http_worker_Q



 waiting connection on http_worker_Q
 waiting connection on http_worker_Q






 waiting connection on http_worker_Q

 waiting connection on http_worker_Q

 waiting connection on http_worker_Q




 waiting connection on http_worker_Q




hw255: DNS query returned error HOST_NOT_FOUND

hw309: DNS query returned error HOST_NOT_FOUND
**Segmentation fault**

**Comment by forid786** [comment]
`hw2390: inURLList (processed): www.privateinternetaccess.com/vpninfo/servers
hw2390: After StoryB checkrequest isexception 0 gomitm 0 mess_no 500
hw2390:  -Forwarding body to client : Upfailure is 0
hw2390:  -reporting level is 3
hw2390:  -Enabling filter bypass hash generation
hw2390: mime type: - Line: 217 Function: isContentType
hw2390: mimes result : false Line: 244 Function: isContentType
hw2390: Displaying TEMPLATE
hw2390: -HOST- placeholder encountered but hostname currently unknown; lookup forced.
Segmentation fault
`

I seem to be having a segmentation fault here too. Looks like it could be related.

**Comment by marcelloc** [comment]
I guess not related to dns auth but with #375

**Comment by philipianpearce** [comment]
Related to dns lookup but not to dns auth,  bug in HTMLTemplate login - now fixed

**Comment by marcelloc** [comment]
no crashes after update
