### ISSUE TITLE
e2guardian 4.1.4

### ISSUE THREAD

**Issue by dtomeysoto** [e2guardian/e2guardian#376]
Hola a todos, cómo podría configurar un grupo de usuarios que solo tiene acceso a algunos sitios hhtp y htpps.

He probado poner los sitios http y https en el archivo exceptionsitelist pero solo los sitios http son accesibles, no así los https.

Qué pudiera ser?

--------------------------------------------------------------------------------------------
Hello everyone, how could you configure a group of users that only have access to some hhtp and htpps sites.

I have tried to put the http and https sites in the exceptionsitelist file but only the http sites are accessible, not the https.

What could it be?

**Comment by fredbcode** [comment]
Github is for bug report, please ask question to Google group
