### ISSUE TITLE
Anydesk can't work with e2guardian ssl mode

### ISSUE THREAD

**Issue by lifeoverlinux** [e2guardian/e2guardian#379]
Hi everybody,

As may you know that when you use e2guardian service, you can't use Anydesk program in your network, anydesk gives you ssl error when it tries to connect to internet. 

So guys how I can solve this problem, I tried to allow domains, ip address of anydesk when anydesk tries to connect internet, but this was a bad idea :) Well, By default E2guardian service doesn't block anything at all. 

This means I don't need to allow something to Anydesk work) I guess when you use e2guardian with ssl filter feature, something broke with ssl between Anydesk ssl certs.

What you guys suggest or what should I do.

Thanks your help.

**Comment by fredbcode** [comment]
More information needed, do you have something (any error, warning message etc.) in log files??

**Comment by lifeoverlinux** [comment]
There is no error message or error in log files. That's why I can't solve the problem, if there was error or warning message then I would search and try to fix it.  :/

Also there is a accounting program in our network, it works with ssl. I couldn't connect to program when I use e2guardian with ssl, after I found ip address of program. I wrote the ip address to "destination bypass proxy" and I connected.

I guess, with e2guardian ssl proxy works perfect but some programs that work with ssl doesn't work.

**Comment by fredbcode** [comment]
It works with Squid only ?

**Comment by lifeoverlinux** [comment]
Yeah, without squid, it gives you error like "8080 in already use". After reboot your pfsense, it works but after 1 hour or maybe 1 day later, you get same error and not e2guardian working.

It works with squid stable.

**Comment by fredbcode** [comment]
I need a wireshark trace between PC and pfsense when anydesk works and when e2guardian blocks

**Comment by lifeoverlinux** [comment]
Actually sir, I did this so much, but I couldn't find anything why anydesk gives ssl error.

**Comment by fredbcode** [comment]
I mean a network trace with wireshark tool
Are you using SSLMITM ? In this case the pinning mode is often annoying

**Comment by fredbcode** [comment]
I mean a network trace with wireshark tool
Are you using SSLMITM ? In this case the pinning mode is often annoying

**Comment by lifeoverlinux** [comment]
**Are you using SSLMITM ?** No I don't use that, without this feature it blocks https domains.

**Comment by lifeoverlinux** [comment]
The problem right now is solved. I put the link, if you have kind of problems like that, the best way right now doing take ip address or domains and then put them into firewall group after that bypass the group on e2guardian.

https://forum.pfsense.org/index.php?topic=147466.0
