### ISSUE TITLE
E2Guardian SSL MITM does not work without CA installed

### ISSUE THREAD

**Issue by pfsenseRavegen** [e2guardian/e2guardian#381]
SSL Interception is enabled in E2Guardian (means Splice All isn't it? )  Therefore, no need to install CA certificate on client browsers.

However, error message such as "This site can’t provide a secure connection www.facebook.com sent an invalid response. Try running Windows Network Diagnostics. ERR_SSL_PROTOCOL_ERROR"  is shown.

When you select Filter ssl sites forging SSL certificates in group options, the ERR_SSL_PROTOCOL_ERROR is gone but is replaced with error messaage "Your connection is not private Attackers might be trying to steal your information from forum.pfsense.org (for example, passwords, messages, or credit cards). Learn more NET::ERR_CERT_AUTHORITY_INVALID"

The solution I found so far was to install the CA certificate on client browsers.  But this is not a solution because you cannot possibly install CA certificate to public users on the computer, laptops, devices, etc.

Please kindly fix the splice all if it does really work.

**Comment by philipianpearce** [comment]
To use SSL interception on any proxy filter you must install a CA on each client. 

If what you are asking for where possible, than the whole of the web would be insecure and no-one would trust https! 

The 'splice all' option in for example squid is the option for NOT doing SSL MITM interception. That is, just connect the client to the target server, without doing any inspection. This is the default behaviour of e2guardian when sslmitm is set to 'off'. With this mode filtering can only be done by site name, as it is impossible to examine the full url or the content of the https conversation. 

Regards 

Philip 

----- Original Message -----

**Comment by pfsenseRavegen** [comment]
that is very confusing as to why squid proxy in pfsense will put words such as:

The SSL/MITM mode determines how SSL interception is treated when 'SSL Man In the Middle Filtering' is enabled. Default: Splice Whitelist, Bump Otherwise.

Splice All: 
This configuration is suitable if you want to use the SquidGuard package for web filtering.
All destinations will be spliced. SquidGuard can do its job of denying or allowing destinations according its rules, as it does with HTTP.
You do not need to install the CA certificate configured below on clients.

**Comment by philipianpearce** [comment]
All explained clearly in https://openschoolsolutions.org/pfsense-web-filter-filter-https-squidguard/ 

Regards 

Philip 

----- Original Message -----

**Comment by forid786** [comment]
I believe the link that Philip provided above makes it clear, and I am pretty sure you were linked to the same place on the pfSense forums too. Take time to learn how the trust relationship works with CA certificates. 

However, here's the main difference between Splice All and MITM in a nutshell:

- Splice All does not require a CA certificate to be installed on the client device, however when using Splice All. The proxy can only see the domain that the client is connecting to, not the page. So for example if someone were to go to Google.com and search something inappropriate. The proxy would only see "www.Google.com" and allow it, and it will not see the end page (www.google.com/somebadpage).

- When using SSL MITM, the proxy is able to see the exact page that the user is visiting. However a CA certificate must be installed on the client's machine for this to work. The proxy essentially requests the page on the end user machine's behalf, then re-encrypts the traffic and sends it to the clients device. 

- SSL MITM has the added benefit of denying pages based on phrases found on them. This is one of the most powerful features of E2 Guardian as it doesn't solely rely on a black list to determine if a website is good or bad. So for example, if E2 Guardian is set to block porn related phrases, and a user goes to a website that isn't on the blacklist. E2 Guardian will detect it and block it before the user sees the content. 

This is just scratching the surface. With MITM you can do a lot of things to the point where you can even re-write the page on-the-fly as long as you have enough CPU resources.
