### ISSUE TITLE
v5develop fileextension and mime issues

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#382]
I'm a bit confused with logs while trying to configure extension/mime block and exception list.
Most video download works on any configuration, even with blockdownloads=on

and when some urls get looged by mime test, it says trusted but on the message it has a not on the white list.
Default story config files has the same messageno=750 for exception and banned mime types. 

Also getting TRANSLATION KEY 999 MISSING for
fileextlist = 'name=bannedextension,messageno=999

logs:
```
*TRUSTED* Blanket file download is active and this MIME type is not on the white list: text/css
*TRUSTED* Banned file extension: .txt
*DENIED* TRANSLATION KEY 999 MISSING .zip
*TRUSTED* Blanket file download is active and this MIME type is not on the white list: image/png
*TRUSTED* Blanket file download is active and this MIME type is not on the white list: text/css
http://testsite.ws/test.mkv *TRUSTED* Blanket file download is active and this MIME type is not on the white list: text/plain 
```

**Comment by marcelloc** [comment]
removing messageno= from exceptionextension  and exceptionmime
and
changing messageno on bannedextension to 900 and messageno to 800  started showing correct error messages on denied extensions but still getting this for mime on logs.

This example is an mkv video.
```
http://test.ws/video.mkv *TRUSTED* Banned MIME file type: text/plain GET 0 0 - 2 206 - 192.168.25.106 
and an mp4 video get no mime info
http://test.ws/video.mp4 - GET 15625 0 - 2 206 - 192.168.25.106 
```

tested with blockdownloads on and off @

**Comment by philipianpearce** [comment]
blockdownloads does not do anything in v5 - I have now removed this option from v5develop
Functionality replaced by modifying responsecheck storyboard function.

Can you confirm mime blocks are being now correctly shown as DENIED in log?

**Comment by marcelloc** [comment]
Update the code and config files but now I'm not seeing any mime type logs.
most banned extensions are being blocked 

this is an example of exe file that is not blocked 
18.05.24 12:53:24 admin 192.168.25.192 https://the.earth.li/~sgtatham/putty/0.70/w32/putty.exe - GET 774200 0 - 1 200 - 192.168.25.192 Default - - - - -

**Comment by marcelloc** [comment]
I've tried including this on group.story but it blocked a lot .com sites.
Non identified mimes seems to block site too.

```
function(checkrequest)
if(viruscheckset) checknoscantypes
if(urlin,exceptionfile) return true
if(mimein, exceptionmime) return true
if(extensionin, exceptionextension) return true
if(true,,750) return setblock
```

**Comment by marcelloc** [comment]
https://the.earth.li/~sgtatham/putty/0.70/w32/putty.exe  downloads fine with .exe extension blocked.

**Comment by philipianpearce** [comment]
You  need to redefine checkresponse not checkrequest for mime ext blocking

Regards

Philip

**Comment by marcelloc** [comment]
ok. Changing to checkresponse fixed sites .com being blocked but I'm still getting "non identified mime types" being blocked 
```

18.05.25 11:56:11 admin 192.168.25.192 https://static.xx.fbcdn.net/rsrc.php/v3/yc/r/XM1bgTzrj7-.js *DENIED* Blanket file download is active and this MIME type is not on the white list:  GET 0 0 - 1 403 - 192.168.25.192 Default - - - - -
18.05.25 11:56:22 admin 192.168.25.192 https://shavar.services.mozilla.com/downloads?client=navclient-auto-ffox&appver=60.0&pver=2.2 *DENIED* Blanket file download is active and this MIME type is not on the white list:  POST 0 0 - 1 403 - 192.168.25.192 Default - - - - -
18.05.25 11:57:03 admin 192.168.25.192 https://s3.glbimg.com/cdn/fonts/opensans/bold.ttf *DENIED* Blanket file download is active and this MIME type is not on the white list:  GET 0 0 - 1 403 - 192.168.25.192 Default - - - - -


```

**Comment by marcelloc** [comment]
On 5.1 looks really better with blanket blocker.

with normal extension block, I get *TRUSTED* Banned MIME file type: text/html.
I'll check if that story update I've pushed on 5.0 is present on 5.1

**Comment by DonusumBilgisayar** [comment]
Mercello
When will you upload the 5.1 update to PFSense for unofficial repo?
