### ISSUE TITLE
performance regression with 4.1.3 -> 4.1.5

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#396]
I updated e2guardion from 4.1.3 to 4.1.5 and immediately are users started complaining about slow internet access.  That's all I have for now.

**Comment by fredbcode** [comment]
Weird I'm seeing no difference here, do you have something in logs (syslog ?)

**Comment by fredbcode** [comment]
Or cpu/memory usage ?

**Comment by fredbcode** [comment]
Some news ? There is no other report about this

**Comment by forid786** [comment]
Switch over to v5 if you can, for me it's been much faster and way more stable. I have been running v5 for a while now and it's been great so far.

**Comment by fredbcode** [comment]
Ticket was closed (due to a lack of response) Please feel free to reopen this issue if the problem still occurs
