### ISSUE TITLE
v4.1.5 - filtergroupslist not being reloaded on -r or -g

### ISSUE THREAD

**Issue by fbarco** [e2guardian/e2guardian#397]
e2guardian V4.1.5 on EOLE/Amon 2.6.2 (Ubuntu 16.04).
When i modify the filter number of an ipgroup, -r or -g option doesn't reload it.
Only stop and start process works.

**Comment by fredbcode** [comment]
Works in V4.1.4 ?

**Comment by fbarco** [comment]
Yes, it is the same in V4.1.3 and 4.1.4.
I know why we have this problem. This is not a problem with -r or -g option.
We have several authplugin in our configuration :
`authplugin = '/etc/guardian/guardian0/authplugins/proxy-ntlm.conf'`
`authplugin = '/etc/guardian/guardian0/authplugins/proxy-basic.conf'`
`authplugin = '/etc/guardian/guardian0/common/ip.conf'`

With ntlm auth, the behavior is good.
The problem appears when we add an ipgroupslist : `10.1.2.50-10.1.2.100=filter3`
If a workstation is in this ipgrouplist and used the ntlm authentication, ip plugin is bypassed.

**Comment by fredbcode** [comment]
So it's expected, this is sequential
