### ISSUE TITLE
v5.1: HTTP Workers not released

### ISSUE THREAD

**Issue by WISPa-Chris** [e2guardian/e2guardian#406]
Our set up generally uses `httpworkers = 1400` although we amend this slightly to meet demand for different clients.

We're seeing a number of servers where the busy workers steadily increase over the course of a few hours and eventually cause connections to queue and hang. It seems that some workers aren't being released to be reused and consequently performance at those times is terrible.

Traffic usage obviously spikes and during the spikes we can see busy workers increase. However when that traffic subsides we aren't seeing much, if any, reduction in busy workers.

Is this expected behaviour?

Thanks

**Comment by fredbcode** [comment]
Can you post a dstats file please ? https://github.com/e2guardian/e2guardian/blob/v5.1/configs/e2guardian.conf.in#L110

**Comment by fredbcode** [comment]
Some news ?

**Comment by WISPa-Chris** [comment]
Sorry, Ive been away from desk for a few days. I'll try to grab a dstats and get it to you shortly.

**Comment by Anthony-76** [comment]
Hi,

It seems that I've got this problem.

I will make somes tests and come back quickly.

thanks
Best regards
Anthony

**Comment by fredbcode** [comment]
Do you have busy workers (connections are waiting in the queue in syslog's message) ?
Please try to increase the http_worker value, 1400 is not huge
