### ISSUE TITLE
3.0.4 crash on small foot print system with specific sites

### ISSUE THREAD

**Issue by 83GTIGuy** [e2guardian/e2guardian#41]
I have build 3.0.4 on a Banana Pi running Openwrt, with apache as the forward proxy.  This setup has worked well on the raspbery pi with the same openwrt custom build, but for some reason when visiting some sites e2guardian seems to crash on the Banana PI.   The Banana Pi is much faster and think I may see more resouce use due to its speed and double amount of ram. Since the device is a small foot print I don't have alot of tools on the system to debug whats going on.
I know for sure that if I visit http://www.timesunion.com e2guardian crashes.  I've increased logging but can't seem to see what the issue is.
Looking for some debug guidance.

**Comment by fredbcode** [comment]
Nothing new ?

**Comment by 83GTIGuy** [comment]
Please close this issue.  e2guardian was not the cause.  An issue in the netfilter code caused the crash.  Once the netfilter code was fixed - e2guardian performed just fine.

**Comment by fredbcode** [comment]
Ok thanks
