### ISSUE TITLE
v5.1: libssl error

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#410]
When running e2guardian v5.1 under ubuntu 16.04 in a docker container, ssl isn't working properly.  You can see below the error "https proxy request" from Error accepting ssl connection  (I added some debug code to display the error).  The is using libssl 1.0.2g and e2guardian's transparent proxy and no squid.

hw0:  popped connection from http_worker_Q
hw0: Compiling ,*[a-z|A-Z].*
hw0: ...with PCRE 
hw0:  -got peer connection - clientip is 192.168.3.64
hw0: bytes peeked 5
hw0: hello length is 2048 magic is CON isTLS is 0
hw0: hasSNI = 0 SNI is 172.17.0.3 Orig IP 172.17.0.3 Orig port 8443
hw0: decoding url Line: 1515 Function: decode
hw0: inIPList no match for 
hw0: After StoryA thttps-pre-authcheck0 mess_no 0
hw0:  -Not got persistent credentials for this connection - querying auth plugins
hw0:  -No auth plugins loaded; using defaults & feigning persistency
hw0:  -username: - -filtergroup: 0
hw0: After StoryB thttps-checkrequest 0 mess_no 0
hw0: Connecting to IPHost 172.17.0.3 port 443
hw0: Connecting to IPHost 172.17.0.3 port 443
hw0: Connecting to IPHost 172.17.0.3 port 443
hw0: Connecting to IPHost 172.17.0.3 port 443
hw0: Connecting to IPHost 172.17.0.3 port 443
hw0:  after connectUpstream nf 1 upfail 1
hw0: Going MITM ....
hw0:  Start goMITM nf 1 upfail 1
hw0:  -Intercepting HTTPS connection
hw0:  -Getting ssl certificate for client connection
hw0: Generating serial no for 172.17.0.3
hw0: Serial no is 5679E7DB57F827475033DFD3946C1F30
hw0: looking for cert /etc/e2guardian/generatedcerts//56/79/E7/DB57F827475033DFD3946C1F30
hw0: Certificate not found. Creating one
hw0: certificate create 0x7f56780025e0
hw0:  -Going SSL on the peer connection
hw0: Error accepting ssl connection 336027803https proxy request 5
hw0: ssl stopping
hw0: ssl stopping
hw0:  nf 1 upfail 1
hw0:  -SSL Interception failed Failed to negotiate ssl connection to client nf 1 upfail 1
hw0:  -Building raw log data string... hw0:  -...built
hw0:  -Shutting down ssl to proxy
hw0: ssl stopping
hw0:  -Shutting down ssl to client
hw0: ssl stopping
hw0: handle_peer returned: 0
log: received a log request0
SSL SITE
1
3
0
https://172.17.0.3
Failed to negotiate ssl connection to client

-
192.168.3.64
0
0
0
0
0
0
0
0
403
0
-
1531766961
101468

154
0

hw0:  in  handle connection
hw0:  waiting connection on http_worker_Q 
29 18.07.16 18:49:21 - 192.168.3.64 https://172.17.0.3 *NETERROR* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.3.64 no_name_group - - - - -
master: busychildren:0 worker Q size:0
master: busychildren:0 worker Q size:0

**Comment by fredbcode** [comment]
Can I see your docker file ?

**Comment by dbrody2004** [comment]
Getting a little closer here.

Found an unrelated bug - if neterrtemplate= doesn't exist, a segfault happens (it doesn't use the template.html by default).

I'm getting a different error now - NETERROR.  Here is a little more about the setup.  There is a front server running openvpn.  Openvpn has iptables rules to forward traffic to another server which has e2guardian.  http works fine, it's just https.  In the e2guardian debug trace I think it is using its own IP address as the destination.  I believe it has to do with SNI - the first server DNATs to a destination of the second server which is used in the SNI process e2guardian checks on.  If that's the case, not sure how e2guardian can do its SNI process check.

Openvpn IP - 172.17.0.2.  E2Guardian - 172.17.0.3 (listening on 8080 and 8443 for transparent https proxy).

openvpn iptables -
iptables -t nat -A PREROUTING -p tcp --dport 80 -i tun+ -j DNAT --to 172.17.0.3:8080
iptables -t nat -A PREROUTING -p tcp --dport 443 -i tun+ -j DNAT --to 172.17.0.3:8443
iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE

E2Guardian debug output
hw72:  popped connection from http_worker_Q
hw72: Compiling ,*[a-z|A-Z].*
hw72: ...with PCRE 
hw72:  -got peer connection - clientip is 172.17.0.2
hw72: bytes peeked 5
hw72: hello length is 2048 magic is  isTLS is 1
hw72: bytes peeked 175
hw72: hasSNI = 0 SNI is 172.17.0.3 Orig IP 172.17.0.3 Orig port 8443
hw72: decoding url Line: 1515 Function: decode
hw72: inIPList no match for 
hw72: After StoryA thttps-pre-authcheck0 mess_no 0
hw72:  -Not got persistent credentials for this connection - querying auth plugins
hw72:  -No auth plugins loaded; using defaults & feigning persistency
hw72:  -username: - -filtergroup: 0
hw72: After StoryB thttps-checkrequest 0 mess_no 0
-------------------why is e2guardian trying to connect to itself (172.17.0.3):443 ?
hw72: Connecting to IPHost 172.17.0.3 port 443
e2guardian[2506]: hw72:  retry 1 to connect to 172.17.0.3
hw72: Connecting to IPHost 172.17.0.3 port 443
e2guardian[2506]: hw72:  retry 2 to connect to 172.17.0.3
hw72: Connecting to IPHost 172.17.0.3 port 443
e2guardian[2506]: hw72:  retry 3 to connect to 172.17.0.3
hw72: Connecting to IPHost 172.17.0.3 port 443
e2guardian[2506]: hw72:  retry 4 to connect to 172.17.0.3
hw72: Connecting to IPHost 172.17.0.3 port 443
hw72:  after connectUpstream nf 1 upfail 1
hw72: Going MITM ....
hw72:  Start goMITM nf 1 upfail 1
hw72:  -Intercepting HTTPS connection
hw72:  -Getting ssl certificate for client connection
hw72: Generating serial no for 172.17.0.3
hw72: Serial no is 5679E7DB57F827475033DFD3946C1F30
hw72: looking for cert /etc/e2guardian/generatedcerts//56/79/E7/DB57F827475033DFD3946C1F30
hw72: Certificate not found. Creating one
hw72: certificate create 0x7fcab40024f0
hw72:  -Going SSL on the peer connection
hw72:  nf 1 upfail 1
hw72:  -SSL Interception failed  nf 1 upfail 1
hw72:  -Building raw log data string... hw72:  -...built
hw72:  -reporting level is 3
hw72: mime type: - Line: 217 Function: isContentType
hw72: mimes result : false Line: 244 Function: isContentType
hw72: mime type: - Line: 217 Function: isContentType
hw72: mimes result : false Line: 244 Function: isContentType
hw72: Displaying TEMPLATE
log: received a log request0

1
3
0
https://172.17.0.3


-
172.17.0.2
0
0
0
0
0
0
0
0
403
0
-
1531777503
916196




203
0

e2guardian[2506]: 18.07.16 21:45:03 - 172.17.0.2 https://172.17.0.3 *NETERROR* - - 0 0 - 1 403 - 172.17.0.2 no_name_group - - - - -
29 18.07.16 21:45:03 - 172.17.0.2 https://172.17.0.3 *NETERROR* - - 0 0 - 1 403 - 172.17.0.2 no_name_group - - - - -
hw72:  -Shutting down ssl to proxy
hw72: ssl stopping
hw72:  -Shutting down ssl to client
hw72: ssl stopping
hw72: this is a server connection
hw72: calling 1st ssl shutdown
hw72: need to call SSL shutdown again
hw72: SSL_SENT_SHUTDOWN IS SET
hw72: Discarding extra data from client
hw72: done
hw72: handle_peer returned: 0
hw72:  in  handle connection
hw72:  waiting connection on http_worker_Q 
master: busychildren:1 worker Q size:0
listen1_thttps: 2: got connection from accept
listen1_thttps: 2: pushed connection to http_worker_Q
hw81:  popped connection from http_worker_Q
hw81: Compiling ,*[a-z|A-Z].*
hw81: ...with PCRE 
hw81:  -got peer connection - clientip is 172.17.0.2
hw81: bytes peeked 5
hw81: hello length is 2048 magic is  isTLS is 1
hw81: bytes peeked 208
hw81: hasSNI = 0 SNI is 172.17.0.3 Orig IP 172.17.0.3 Orig port 8443
hw81: decoding url Line: 1515 Function: decode
hw81: inIPList no match for 
hw81: After StoryA thttps-pre-authcheck0 mess_no 0
hw81:  -Not got persistent credentials for this connection - querying auth plugins
hw81:  -No auth plugins loaded; using defaults & feigning persistency
hw81:  -username: - -filtergroup: 0
hw81: After StoryB thttps-checkrequest 0 mess_no 0
hw81: Connecting to IPHost 172.17.0.3 port 443
e2guardian[2506]: hw81:  retry 1 to connect to 172.17.0.3
hw81: Connecting to IPHost 172.17.0.3 port 443
e2guardian[2506]: hw81:  retry 2 to connect to 172.17.0.3
hw81: Connecting to IPHost 172.17.0.3 port 443
e2guardian[2506]: hw81:  retry 3 to connect to 172.17.0.3
hw81: Connecting to IPHost 172.17.0.3 port 443
e2guardian[2506]: hw81:  retry 4 to connect to 172.17.0.3
hw81: Connecting to IPHost 172.17.0.3 port 443
hw81:  after connectUpstream nf 1 upfail 1
hw81: Going MITM ....
hw81:  Start goMITM nf 1 upfail 1
hw81:  -Intercepting HTTPS connection
hw81:  -Getting ssl certificate for client connection
hw81: Generating serial no for 172.17.0.3
hw81: Serial no is 5679E7DB57F827475033DFD3946C1F30
hw81: looking for cert /etc/e2guardian/generatedcerts//56/79/E7/DB57F827475033DFD3946C1F30
hw81: Certificate not found. Creating one
hw81: certificate create 0x7fca400017e0
hw81:  -Going SSL on the peer connection
hw81:  nf 1 upfail 1
hw81:  -SSL Interception failed  nf 1 upfail 1
hw81:  -Building raw log data string... hw81:  -...built
log: received a log request0

1
3
0
https://172.17.0.3


-
172.17.0.2
0
0
0
0
0
0
0
0
403
0
-
1531777510
29911




203
0

e2guardian[2506]: 18.07.16 21:45:10 - 172.17.0.2 https://172.17.0.3 *NETERROR* - - 0 0 - 1 403 - 172.17.0.2 no_name_group - - - - -
29 18.07.16 21:45:10 - 172.17.0.2 https://172.17.0.3 *NETERROR* - - 0 0 - 1 403 - 172.17.0.2 no_name_group - - - - -

**Comment by fredbcode** [comment]
How e2guardian is compiled ? Can you post your DockerFile please ?

**Comment by fredbcode** [comment]
Please try the fix about neterrtemplate

**Comment by fredbcode** [comment]
FYI: This DockerFile runs with a recent OS (16.04 is deprecated for us) 
https://github.com/e2guardian/e2guardian/blob/v5.1/data/scripts/Dockerfile

**Comment by philipianpearce** [comment]
Transparent https will ONLY work correctly if the e2g server is made the network gateway. Then e2g will get the original destination IP. If you forward using NAT then it is not possible for it to work! 

If you need to load share then this should be possible using the 'direct' load sharing method, where just the destination MAC is changed and the IPs left unchanged. 

The NETERROR error is used whenever e2g is unable to negotiate a connection with the client or it cannot connect to the target server (e.g. site does not exist, no route to server, or certificate error in MITM). I.e. Whenever the site is unavailable but is NOT being DENIED to the user due to url or content. 

Regards 

Philip 

----- Original Message -----

**Comment by dbrody2004** [comment]
Got it working with some iptables and route table magic.
