### ISSUE TITLE
urlredirectregexplist doesn't work

### ISSUE THREAD

**Issue by Kenny690** [e2guardian/e2guardian#417]
Is there something I missing? I have these regexps in my urlredirectregexplist file

'.*yandex.ru\/search\/.*text=(.*)'->'http://search.skydns.ru/search/?query=\1&r=1'
'.*google.ru\/search?.*q=(.*)'->'http://search.skydns.ru/search/?query=\1&r=1'
'.*go.mail.ru/search?.*q=(.*)'->'http://search.skydns.ru/search/?query=\1&r=1'

They were working fine on v4, but on v5 it doesn't. Is there something in storyboard I have to change?
I have debian stretch, e2 v5.1

**Comment by philipianpearce** [comment]
It was a storyboard issue.

Can you try using common.story from latest in v5.1 branch?

**Comment by Kenny690** [comment]
I added if(fullurlin,redirect) return setredirect to the common.story and restarted e2guardian. Still no luck.
I have MITM turned on. In log I see this:
1532953211.652    798 room38.*.ru TCP_MISS/200 87918 GET https://yandex.ru/search/?lr=973&msid=1532953203.35761.22866.8571&text=test&suggest_reqid=759920912151611321432044818658783 - DEFAULT_PARENT/ -
I checked regexp here https://regex101.com/r/SmFKmx/2 and it worked in a past version.

UPD:

It's working. Problem is in description. There is apostrophes 
'regexp_pattern'->'url_to_redirect_to'
But it must be quotation marks
"regexp_pattern"->"url_to_redirect_to"

When I was trying to find a problem I tried to change quotation marks to apostrophes like it showed in the comments of the urlredirectregexplist file.

Thanks for help!
