### ISSUE TITLE
v5.1.1: missing config file and wrong path in e2guardianf1.conf.in

### ISSUE THREAD

**Issue by Alexander237** [e2guardian/e2guardian#421]
e2guardianf1.conf.in contains reference to:
`#ipsitelist = 'name=exceptionvirus,path=@DGCONFDIR@/lists/contentscanners/exceptionvirussiteiplist'`
but there is no such file in source directory configs/lists/contentscanners/

e2guardianf1.conf.in contains line 
`#fileextlist = 'name=exceptionvirus,path=@DGCONFDIR@/e2guardian/lists/contentscanners/exceptionvirusextensionlist'`
It should be corrected to 
`#fileextlist = 'name=exceptionvirus,path=@DGCONFDIR@/lists/contentscanners/exceptionvirusextensionlist'`

**Comment by fredbcode** [comment]
Fixed in 5.1.2
