### ISSUE TITLE
ssl connection to client

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#422]
Hi,

I use E2guardian 5.1. on Debian 9
On my client I use Chrome browser.

After somes times, I have the following error in my logs:

18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://fr.wikipedia.org/w/load.php?debug=false&lang=fr&modules=site.styles&only=styles&skin=vector - GET 0 0 - 1 304 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://www.ouest-france.fr *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://media.ouest-france.fr *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://www.ouest-france.fr *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://cdn.jokerly.com *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://fr.wikipedia.org *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://upload.wikimedia.org *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://fr.wikipedia.org *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://upload.wikimedia.org *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://upload.wikimedia.org *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://upload.wikimedia.org *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.10 16:42:19 192.168.170.25 192.168.170.25 https://upload.wikimedia.org *DENIED* Failed to negotiate ssl connection to client - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -

So, I wait about 1-2 minutes, I refresh the webpage and the ssl error disappear without do nothing.

On my Chrome browser, I have this error : "ERR_TIMED_OUT".

So, this problem can be avoid via E2guardian configurations?

Best regards
Anthony

**Comment by fredbcode** [comment]
Good taste of web sites :)

Do you have more informations in syslog ?

18.08.10 16:42 -> Must be exactly the same time in your browser, server 
and clients are both fully synchronized ?

**Comment by Anthony-76** [comment]
Server and computer are fullt synchronized.

In syslog:

Aug 10 16:52:27 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:52:32 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:52:37 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:52:42 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:52:47 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:52:52 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:52:57 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:53:02 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:53:07 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 19 connections are waiting in the queue.
Aug 10 16:53:12 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:17 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:22 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:27 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:32 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:37 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:42 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:47 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:52 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:53:57 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 20 connections are waiting in the queue.
Aug 10 16:54:02 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:07 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:12 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:17 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:22 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:27 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:32 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:37 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:42 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:47 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:52 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:57 sysun e2guardian[32258]: master: Warning: all 200 http_worker threads are busy and 21 connections are waiting in the queue.
Aug 10 16:54:59 sysun e2guardian[32258]: hw51: Failed to get client's original destination IP: Aucun fichier ou dossier de ce type
Aug 10 16:54:59 sysun e2guardian[32258]: hw51: Failed to get client's original destination IP: Aucun fichier ou dossier de ce type
Aug 10 16:54:59 sysun e2guardian[32258]: hw51: Failed to get client's original destination IP: Aucun fichier ou dossier de ce type
Aug 10 16:54:59 sysun e2guardian[32258]: hw51: Failed to get client's original destination IP: Aucun fichier ou dossier de ce type



Very strange. I have only one computer connected to E2guardian and All http_worker are busy.....

This problem seems to be the same that ticket #406 .


If necessary, I can make differents tests

**Comment by fredbcode** [comment]
200 http_worker is a very very low value

Please test with 1024 (with a decent hardware ?)

**Comment by Anthony-76** [comment]
Ok, I will increase http_worker

The hardware (for my test with 1 computer client) is ok 
2 CPU core i3 and 4GB of ram

I will give you a feedback.

**Comment by fredbcode** [comment]
Ho, I guess you can try with 2048 maybe 4096 (depends of the complexity of the rules) 
Tu es breton ?

**Comment by Anthony-76** [comment]
Ok, non, je suis normand, ton voisin ;)

**Comment by fredbcode** [comment]
Ok pas grave personne n'est parfait

**Comment by Anthony-76** [comment]
I increased httpworker to 1024 and it's ok.
No problem appears :)

**Comment by fredbcode** [comment]
Check time to time and upgrade if necessary
