### ISSUE TITLE
Certificate not valid

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#423]
Hi,

I use E2guardian 5.1.1 on Debian 9

I have the following error with some https website:

18.08.13 10:50:46 192.168.170.25 192.168.170.25 https://extranet.alphalink.fr *DENIED* Certificate supplied by server was not valid: unable to get local issuer certificate - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -
18.08.13 10:50:46 192.168.170.25 192.168.170.25 https://extranet.alphalink.fr *DENIED* Certificate supplied by server was not valid: unable to get local issuer certificate - 0 0 SSL SITE 1 403 - 192.168.170.25 Test - - - - -

I have no additionnal error in syslog

Is it possible to configure e2guardian in order to ignore this error?

If I bypass e2guardian, the website works fine

Best regards
Anthony

**Comment by fredbcode** [comment]
Are you using SSLMITM?

**Comment by Anthony-76** [comment]
Yes , I use it

**Comment by fredbcode** [comment]
So two possibilities

1 - Add the unknown CA certificate in you system -> https://framacloud.org/fr/echange-de-graines/ajouter-une-autorite-de-certification-a-debian.html

or

2 - Add this website to the exception lists

**Comment by Anthony-76** [comment]
thanks for your answer.

In exception lists, it's work.

So, if the webpage contains a virus is added in exception lists, the webpage will not be blocked by the antivirus scanner?

**Comment by philipianpearce** [comment]
If in exceptionsitelist https web site will not be MITM or scanned. 

A 3rd alternative is to add site to nocheckcertsitelist. In this case it can be content scanned. 

----- Original Message -----

**Comment by Anthony-76** [comment]
The 3rd alternative seems better for me. I will test this.
Thanks for your answser

**Comment by fredbcode** [comment]
Add the CA can be also useful for another websites.

**Comment by fredbcode** [comment]
@anthony please ask questions to the Google group, GitHub is for bug report
Thanks
