### ISSUE TITLE
Some more typos found by Debian's lintian tool

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#426]
I: e2guardian: spelling-error-in-binary usr/sbin/e2guardian sucessfully successfully
I: e2guardian: spelling-error-in-binary usr/sbin/e2guardian occured occurred
I: e2guardian: spelling-error-in-binary usr/sbin/e2guardian Ambigous Ambiguous

**Comment by fredbcode** [comment]
What does it mean exactly?

**Comment by sunweaver** [comment]
Search your code for sucessfully (with one c) and replace by the correctly spelled word.

Same for the other words (occurred has 2 "r"s and ambiguous has 2 "u"s).

**Comment by fredbcode** [comment]
Ah ! of course :)
