### ISSUE TITLE
max_upload_size not used in code and not implementable in story board?

### ISSUE THREAD

**Issue by bmuel** [e2guardian/e2guardian#430]
Hi all,
might be wrong, but Looking at the Code, maxuploadsize from filter Group files does not do anything anymore. Also, it does not seem to be possible to check post size using storyboards?

Feedback would be appreciated.

Best regards, Ben

**Comment by philipianpearce** [comment]
You are correct.    POST content checking has not yet been implemented in v5.   There is a comment in the code stating this and it is listed as a future development in notes/NEWIN_v5.    I have now added a comment to the sample e2guardianf1/conf in v5develop/v5.2 stating this.

This feature is likely to be available in v5.3.
