### ISSUE TITLE
E2Guardian works very slowly! :(

### ISSUE THREAD

**Issue by thejvmshid** [e2guardian/e2guardian#431]
Hi everybody! Please help me please, E2Guardian works very slowly!

Me E2Guardian conf file content:
languagedir = '/usr/share/e2guardian/languages'
language = 'ukenglish'
loglevel = 3 
logexceptionhits = 2
logfileformat = 6 
daemonuser = 'e2guardian'
daemongroup = 'e2guardian'
filterip = 
filterports = 48080
#transparenthttpsport = 8443
proxytimeout = 5
proxyip = aaaaaaaa
proxyip = bbbbbbbb
proxyip = ccccccccc
proxyport = 55039
proxyport = 55040
proxyport = 55041
connecttimeout = 5
proxyexchange = 61
pcontimeout = 55
usecustombannedimage = on
custombannedimagefile = '/usr/share/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/usr/share/e2guardian/blockedflash.swf'
filtergroups = 3
filtergroupslist = '/etc/e2guardian/lists/filtergroupslist'
iplist = 'name=bannedclient,messageno=100,logmessageno=103,path=/etc/e2guardian/lists/bannediplist'
iplist = 'name=exceptionclient,messageno=600,path=/etc/e2guardian/lists/exceptioniplist'
iplist = 'name=authexception,messageno=602,path=/etc/e2guardian/lists/authexceptioniplist'
sitelist = 'name=authexception,messageno=602,path=/etc/e2guardian/lists/authexceptionsitelist'
urllist = 'name=authexception,messageno=603,path=/etc/e2guardian/lists/authexceptionurllist'
authplugin = '/etc/e2guardian/authplugins/ip.conf'
showweightedfound = on
weightedphrasemode = 2
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
maxcontentfiltersize = 256
maxcontentramcachescansize = 2000
maxcontentfilecachescansize = 20000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10

maxchildren = 6000
minchildren = 64
minsparechildren = 15
preforkchildren = 20
maxsparechildren = 80
maxagechildren = 5000

downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
contentscannertimeout = 60
recheckreplacedurls = off
forwardedfor = off
usexforwardedfor = off
#xforwardedforfilterip = 
logconnectionhandlingerrors = on
httpworkers = 200
nodaemon = off
nologger = off
logadblocks = off
loguseragent = off
enablessl = off
preauthstoryboard = '/etc/e2guardian/preauth.story'
searchsitelistforip = on

/etc/security/limits.conf content 
e2guardian		soft	nofile		64000
e2guardian		hard	nofile		64000

Thansk in advance!

**Comment by fredbcode** [comment]
Version? OS? Something in syslog?

**Comment by thejvmshid** [comment]
E2Guardian 5.1.1
Debian 9 Stretch
The problems started after it was updated from version 4.4 to 5.1.1. Users began to complain about too slow Internet. I also noticed that after a long hanging, the leaf listener port simply falls off, but the processes in e2guardian in the operating system continue to function. Those. It turns out that the network mechanism stops working. In such cases, helps, restart the service.

**Comment by fredbcode** [comment]
And system logs?

**Comment by thejvmshid** [comment]
Aug 29 15:27:50 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200
Aug 29 15:27:52 srv-i43905gn e2guardian[3231]: hw65:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:27:55 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200
Aug 29 15:27:56 srv-i43905gn e2guardian[3231]: hw17:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:27:56 srv-i43905gn e2guardian[3231]: hw122:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:00 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200
Aug 29 15:28:02 srv-i43905gn e2guardian[3231]: hw128:  Unable to send return header to client Client Connection at 192.168.36.98 problem - errno: 32
Aug 29 15:28:04 srv-i43905gn e2guardian[3231]: hw172:  No header recd from client at 192.168.30.112 - errno: 0
Aug 29 15:28:04 srv-i43905gn e2guardian[3231]: hw94:  No header recd from client at 192.168.30.112 - errno: 0
Aug 29 15:28:05 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200
Aug 29 15:28:07 srv-i43905gn e2guardian[3231]: hw174:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:09 srv-i43905gn e2guardian[3231]: hw33:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:09 srv-i43905gn e2guardian[3231]: hw21:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:09 srv-i43905gn e2guardian[3231]: hw28:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:09 srv-i43905gn e2guardian[3231]: hw57:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:10 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200
Aug 29 15:28:13 srv-i43905gn e2guardian[3231]: hw70:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:13 srv-i43905gn e2guardian[3231]: hw50:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:14 srv-i43905gn e2guardian[3231]: hw180:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:14 srv-i43905gn e2guardian[3231]: hw20:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:15 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200
Aug 29 15:28:15 srv-i43905gn e2guardian[3231]: hw159:  No header recd from client at 192.168.36.98 - errno: 0
Aug 29 15:28:15 srv-i43905gn e2guardian[3231]: hw92:  No header recd from client at 192.168.36.98 - errno: 0
Aug 29 15:28:17 srv-i43905gn e2guardian[3231]: hw185:  Unable to send return header to client Client Connection at 192.168.30.96 problem - errno: 104
Aug 29 15:28:18 srv-i43905gn e2guardian[3231]: hw118:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:19 srv-i43905gn e2guardian[3231]: hw76:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:20 srv-i43905gn e2guardian[3231]: hw178:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:20 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200
Aug 29 15:28:21 srv-i43905gn e2guardian[3231]: hw5:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:25 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200
Aug 29 15:28:29 srv-i43905gn e2guardian[3231]: hw183:  No header recd from client at 192.168.30.112 - errno: 0
Aug 29 15:28:30 srv-i43905gn e2guardian[3231]: hw48:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 29 15:28:30 srv-i43905gn e2guardian[3231]: master: Warning system is full : max httpworkers: 200 Used: 200

**Comment by thejvmshid** [comment]
For example, if count of httpworkers specify as > 1000
Receive this error:
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error reading /etc/e2guardian/lists/exceptionurllist3. Check directory and file permissions. They should be 640 and 750: Нет такого файла или каталога
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error reading file /etc/e2guardian/lists/exceptionurllist3: Нет такого файла или каталога
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error reading file /etc/e2guardian/lists/exceptionurllist3: Нет такого файла или каталога
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error opening exception
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error reading file /etc/e2guardian/lists/exceptionextensionlist3: Нет такого файла или каталога
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error opening exceptionextension
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error opening exception
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Unable to read /etc/e2guardian/lists/exceptionurllist3
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error reading /etc/e2guardian/lists/exceptionextensionlist3. Check directory and file permissions. They should be 640 and 750: Нет такого файла или каталога
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error reading file /etc/e2guardian/lists/exceptionextensionlist3: Нет такого файла или каталога
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Error opening exceptionextension
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Unable to read /etc/e2guardian/lists/exceptionextensionlist3
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: SB warning: Undefined list exceptionextension used at line 44 of /etc/e2guardian/common.story
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: httpworkers option in e2guardian.conf has a value too high.
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]:  httpworkers option in e2guardian.conf has a value too high for current file id limit (1024)
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: httpworkers 1000 must not exceed 50% of 1017
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: in this configuration.
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Reduce httpworkers
Aug 29 15:33:55 srv-i43905gn e2guardian[3686]: Or increase the filedescriptors available with ulimit -n to at least=2007
Aug 29 15:33:55 srv-i43905gn systemd[1]: e2guardian.service: Control process exited, code=exited status=1
Aug 29 15:33:55 srv-i43905gn systemd[1]: e2guardian.service: Failed with result 'exit-code'.
Aug 29 15:33:55 srv-i43905gn systemd[1]: Failed to start E2guardian Web filtering.

But:

root@srv-i43905gn:/etc/e2guardian/lists# su - e2guardian
e2guardian@srv-i43905gn:~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63584
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
**open files                      (-n) 64000**
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63584
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Open files limits specified as 64000

**Comment by fredbcode** [comment]
Are you using my package? E2 is started with systemd?

Ulimit value is by user, so I guess this not the same for the user used by e2 than root

**Comment by thejvmshid** [comment]
I updated E2 from the Debian repository.
Yes, I use the system.
Tell me, please, how can I increase httpworkers? Thanks in advance.

**Comment by fredbcode** [comment]
Which version is ?

You can try to change the systemd file https://github.com/e2guardian/e2guardian/blob/v5.1/data/scripts/e2guardian.service.in

Or use our latest package (but perphaps you must change your configuration files)
https://github.com/e2guardian/e2guardian/releases/tag/v5.1.2

**Comment by thejvmshid** [comment]
fredbcode, thank you for your reply. After recreate systemd service file, without error takes great value httpworkers
