### ISSUE TITLE
MITM exception list not available?

### ISSUE THREAD

**Issue by Schroeffu** [e2guardian/e2guardian#433]
I am trying to disable MITM for all e-banking sites, so that these sites are displaying the right and original certification in users browser.
My idea is to use the banking domain list from https://dsi.ut-capitole.fr/blacklists/index_en.php > bank, and/or from other blacklists (and use as a whitelist)

I could not find anywhere a MITM exception list. How can i configure a list of domains which should not attacked with MITM?

**Comment by fredbcode** [comment]
Put the websites in an exception site list (exceptionsitelist) 

Google groups e2guardian is the right place for questions

Le 29 août 2018 10:54:56 GMT+01:00, Schroeffu <notifications@github.com> a écrit :
>I am trying to disable MITM for all e-banking sites, so that these
>sites are displaying the right and original certification in users
>browser.
>My idea is to use the banking domain list from
>https://dsi.ut-capitole.fr/blacklists/index_en.php > bank of from other
>blacklists (and use as a whitelist)
>
>I could not find anywhere a MITM exception list. How can i configure a
>list of domains which should not attacked with MITM?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/433

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Schroeffu** [comment]
Thanks. You're right, will do so next time. thanks again
