### ISSUE TITLE
 blank page with HTTPS filtering

### ISSUE THREAD

**Issue by thejvmshid** [e2guardian/e2guardian#434]
First, thanks for your product!
This happens:
Users, when visiting some sites, do not let **Forbidden** notice go out.
In the logs appears:
Aug 30 11:25:27 srv-i43905gn e2guardian[10765]: hw65:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 30 11:25:27 srv-i43905gn e2guardian[10765]: hw371:  No header recd from client at 192.168.30.225 - errno: 0
Aug 30 11:25:27 srv-i43905gn e2guardian[10765]: hw275:  No header recd from client at 192.168.30.225 - errno: 0
Aug 30 11:25:36 srv-i43905gn e2guardian[10765]: hw434:  No header recd from client at 192.168.37.241 - errno: 0
Aug 30 11:25:44 srv-i43905gn e2guardian[10765]: hw282:  Unable to send return header to client Client Connection at 192.168.30.96 problem - errno: 104
Aug 30 11:25:52 srv-i43905gn e2guardian[10765]: hw131:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 30 11:26:08 srv-i43905gn e2guardian[10765]: hw454:  No header recd from client at 192.168.37.36 - errno: 0
Aug 30 11:26:10 srv-i43905gn e2guardian[10765]: hw490:  No header recd from client at 192.168.30.119 - errno: 0
Aug 30 11:26:16 srv-i43905gn e2guardian[10765]: hw303:  Unable to send return header to client Client Connection at 192.168.30.96 problem - errno: 104
Aug 30 11:26:22 srv-i43905gn e2guardian[10765]: hw324:  Unable to send return header to client Client Connection at 192.168.30.96 problem - errno: 104
Aug 30 11:26:31 srv-i43905gn e2guardian[10765]: hw165:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104
Aug 30 11:26:32 srv-i43905gn e2guardian[10765]: hw411:  Unable to send return header to client Client Connection at 192.168.37.55 problem - errno: 104

**Comment by thejvmshid** [comment]
Are you have any ideas? Some sites do not open at all, issuing an error is forbidden.
E2Guardian.conf:
languagedir = '/usr/share/e2guardian/languages'
language = 'ukenglish'
loglevel = 3 
logexceptionhits = 2
logfileformat = 6 
daemonuser = 'e2guardian'
daemongroup = 'e2guardian'
filterip = 
filterports = 48080
proxytimeout = 5
proxyip = aaa
proxyip = bbb
proxyip = ccc
proxyport = 55039
proxyport = 55040
proxyport = 55041
connecttimeout = 5
proxyexchange = 61
pcontimeout = 55
usecustombannedimage = on
custombannedimagefile = '/usr/share/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/usr/share/e2guardian/blockedflash.swf'
filtergroups = 3
filtergroupslist = '/etc/e2guardian/lists/filtergroupslist'
iplist = 'name=bannedclient,messageno=100,logmessageno=103,path=/etc/e2guardian/lists/bannediplist'
iplist = 'name=exceptionclient,messageno=600,path=/etc/e2guardian/lists/exceptioniplist'
iplist = 'name=authexception,messageno=602,path=/etc/e2guardian/lists/authexceptioniplist'
sitelist = 'name=authexception,messageno=602,path=/etc/e2guardian/lists/authexceptionsitelist'
urllist = 'name=authexception,messageno=603,path=/etc/e2guardian/lists/authexceptionurllist'
authplugin = '/etc/e2guardian/authplugins/ip.conf'
showweightedfound = on
weightedphrasemode = 2
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
maxcontentfiltersize = 256
maxcontentramcachescansize = 2000
maxcontentfilecachescansize = 20000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
maxchildren = 6000
minchildren = 64
minsparechildren = 15
preforkchildren = 20
maxsparechildren = 80
maxagechildren = 5000
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
contentscannertimeout = 60
recheckreplacedurls = off
forwardedfor = off
usexforwardedfor = off
logconnectionhandlingerrors = on
httpworkers = 1000
nodaemon = off
nologger = off
logadblocks = off
loguseragent = off
enablessl = off
preauthstoryboard = '/etc/e2guardian/preauth.story'
searchsitelistforip = on

E2Guardianf1.conf:

groupname = 'no_name_group'
storyboard = '/etc/e2guardian/examplef1.story'
bannedphraselist = '/etc/e2guardian/lists/bannedphraselist'
weightedphraselist = '/etc/e2guardian/lists/weightedphraselist'
exceptionphraselist = '/etc/e2guardian/lists/exceptionphraselist'
sitelist = 'name=banned,messageno=500,path=/etc/e2guardian/lists/bannedsitelist'
ipsitelist = 'name=banned,messageno=510,path=/etc/e2guardian/lists/bannedsiteiplist'
urllist = 'name=banned,messageno=501,path=/etc/e2guardian/lists/bannedurllist'
regexpboollist = 'name=banned,messageno=503,path=/etc/e2guardian/lists/bannedregexpurllist'
regexpboollist = 'name=banneduseragent,messageno=522,path=/etc/e2guardian/lists/bannedregexpuseragentlist'
sitelist = 'name=bannedssl,messageno=520,path=/etc/e2guardian/lists/bannedsslsitelist'
ipsitelist = 'name=bannedssl,messageno=520,path=/etc/e2guardian/lists/bannedsslsiteiplist'
sitelist = 'name=grey,path=/etc/e2guardian/lists/greysitelist'
ipsitelist = 'name=grey,path=/etc/e2guardian/lists/greysiteiplist'
urllist = 'name=grey,path=/etc/e2guardian/lists/greyurllist'
sitelist = 'name=greyssl,path=/etc/e2guardian/lists/greysslsitelist'
ipsitelist = 'name=greyssl,path=/etc/e2guardian/lists/greysslsiteiplist'
sitelist = 'name=exception,messageno=602,path=/etc/e2guardian/lists/exceptionsitelist'
ipsitelist = 'name=exception,messageno=602,path=/etc/e2guardian/lists/exceptionsiteiplist'
urllist = 'name=exception,messageno=603,path=/etc/e2guardian/lists/exceptionurllist'
regexpboollist = 'name=exception,messageno=609,path=/etc/e2guardian/lists/exceptionregexpurllist'
regexpboollist = 'name=exceptionuseragent,messageno=610,path=/etc/e2guardian/lists/exceptionregexpuseragentlist'
sitelist = 'name=refererexception,messageno=620,path=/etc/e2guardian/lists/refererexceptionsitelist'
ipsitelist = 'name=refererexception,messageno=620,path=/etc/e2guardian/lists/refererexceptionsiteiplist'
urllist = 'name=refererexception,messageno=620,path=/etc/e2guardian/lists/refererexceptionurllist'
sitelist = 'name=embededreferer,path=/etc/e2guardian/lists/embededreferersitelist'
ipsitelist = 'name=embededreferer,path=/etc/e2guardian/lists/embededreferersiteiplist'
urllist = 'name=embededreferer,path=/etc/e2guardian/lists/embededrefererurllist'
regexpreplacelist = 'name=change,path=/etc/e2guardian/lists/urlregexplist'
regexpreplacelist = 'name=sslreplace,path=/etc/e2guardian/lists/sslsiteregexplist'
regexpreplacelist = 'name=redirect,path=/etc/e2guardian/lists/urlredirectregexplist'
contentregexplist = '/etc/e2guardian/lists/contentregexplist'
sitelist = 'name=localbanned,messageno=560,path=/etc/e2guardian/lists/localbannedsitelist'
searchlist = 'name=localbanned,messageno=581,path=/etc/e2guardian/lists/localbannedsearchlist'
sitelist = 'name=localgrey,path=/etc/e2guardian/lists/localgreysitelist'
sitelist = 'name=localgreyssl,path=/etc/e2guardian/lists/localgreysslsitelist'
sitelist = 'name=localexception,messageno=662,path=/etc/e2guardian/lists/localexceptionsitelist'
fileextlist = 'name=exceptionextension,path=/etc/e2guardian/lists/exceptionextensionlist'
mimelist = 'name=exceptionmime,path=/etc/e2guardian/lists/exceptionextensionlist'
fileextlist = 'name=bannedextension,messageno=900,path=/etc/e2guardian/lists/bannedextensionlist'
mimelist = 'name=bannedmime,messageno=800,path=/etc/e2guardian/lists/bannedmimetypelist'
sitelist = 'name=exceptionfile,path=/etc/e2guardian/lists/exceptionfilesitelist'
ipsitelist = 'name=exceptionfile,path=/etc/e2guardian/lists/exceptionfilesiteiplist'
urllist = 'name=exceptionfile,path=/etc/e2guardian/lists/exceptionfileurllist'
maxuploadsize = -1
regexpreplacelist = 'name=headermods,path=/etc/e2guardian/lists/headerregexplist'
regexpboollist = 'name=bannedheader,path=/etc/e2guardian/lists/bannedregexpheaderlist'
regexpboollist = 'name=exceptionheader,path=/etc/e2guardian/lists/exceptionregexpheaderlist'
regexpreplacelist = 'name=addheader,path=/etc/e2guardian/lists/addheaderregexplist'
naughtynesslimit = 50
 
regexpreplacelist = 'name=searchterms,path=/etc/e2guardian/lists/searchregexplist'
searchlist = 'name=banned,path=/etc/e2guardian/lists/bannedsearchlist'
searchlist = 'name=override,path=/etc/e2guardian/lists/bannedsearchoveridelist'
categorydisplaythreshold = 0
embeddedurlweight = 0
bypass = 0
bypasskey = ''
sitelist = 'name=bannedbypass,messageno=500,path=/etc/e2guardian/lists/bannedsitelistwithbypass'
infectionbypass = 0
infectionbypasskey = ''
infectionbypasserrorsonly = on
disablecontentscan = off  
disablecontentscanerror = off
contentscanexceptions = off
deepurlanalysis = off
reportinglevel = 3
usesmtp = off   #NOT YET TESTED
mailfrom = ''
avadmin = ''
contentadmin = ''
avsubject = 'e2guardian virus block'
contentsubject = 'e2guardian violation'
notifyav = off
notifycontent = off
thresholdbyuser = off
violations = 0
threshold = 0
sslmitm = off
mitmcheckcert = on
sitelist = 'name=nocheckcert,path=/etc/e2guardian/lists/nocheckcertsitelist'
ipsitelist = 'name=nocheckcert,path=/etc/e2guardian/lists/nocheckcertsiteiplist'

I use E2Guardian version 5.1.1
Thanks everybody in advance.

**Comment by fredbcode** [comment]
You mean you have a blank page ? if the website works in SSL mode there is no issue at all, a banned webpage is showed only in HTTP mode.
This is not a limitation about e2guardian but a protocol restriction.

There are two ugly "tricks" to show a message in configuration file (take a look), but the best way is to use SSLMITM

**Comment by thejvmshid** [comment]
For earlier I apologize. The most interesting, these sites work on http. if you go without the E2guardian filter, the sites open, there are no problems.
![aaa](https://user-images.githubusercontent.com/35526267/45144720-5a400f00-b1d8-11e8-8957-6b56f2806d9c.jpg)


Thank in advance for replies.

**Comment by thejvmshid** [comment]
Of course I'm sorry, but including SSLMITM did not solve the problem, unfortunately.

chunk of e2guardianf2.conf:

sslmitm = on
cacertificatepath = '/usr/local/etc/e2guardian/my_rootCA.crt'
caprivatekeypath = '/usr/local/etc/e2guardian/private_root.pem'
certprivatekeypath = '/usr/local/etc/e2guardian/private_cert.pem'
generatedcertpath = '/usr/local/etc/e2guardian/generatedcerts'
mitmcheckcert = on
sslcertcheck = on

thanks in advance.

**Comment by fredbcode** [comment]
Are you sure SSLMITM is enable ? Which certificate are you seeing in google ?

**Comment by fredbcode** [comment]
https://github.com/e2guardian/e2guardian/blob/v5.1/configs/e2guardianf1.conf.in#L489
