### ISSUE TITLE
compile error 5.2

### ISSUE THREAD

**Issue by zulusbg** [e2guardian/e2guardian#436]
Hello im tyring to compile support for avast and kaspersky
but im getting this error 
ontentscanners/kavdscan.cpp
contentscanners/kavdscan.cpp: In function ‘CSPlugin* kavdcreate(ConfigVar&)’:
contentscanners/kavdscan.cpp:57:39: error: invalid new-expression of abstract class type ‘kavdinstance’
     return new kavdinstance(definition);
                                       ^
contentscanners/kavdscan.cpp:35:7: note:   because the following virtual functions are pure within ‘kavdinstance’:
 class kavdinstance : public CSPlugin
       ^~~~~~~~~~~~
In file included from contentscanners/kavdscan.cpp:16:0:
contentscanners/../ContentScanner.hpp:81:17: note:      virtual int CSPlugin::scanFile(HTTPHeader*, HTTPHeader*, const char*, FOptionContainer*&, const char*, const char*, NaughtyFilter*, const String*, const String*)
     virtual int scanFile(HTTPHeader *requestheader, HTTPHeader *docheader, const char *user, FOptionContainer* &foc , const char *ip,
                 ^~~~~~~~
Makefile:1239: recipe for target 'contentscanners/e2guardian-kavdscan.o' failed
make[2]: *** [contentscanners/e2guardian-kavdscan.o] Error 1
make[2]: Leaving directory '/root/e2guardian/src'
Makefile:400: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/e2guardian'
Makefile:341: recipe for target 'all' failed
make: *** [all] Error 2

configure settings are 
./configure '--prefix=/usr''--enable-avastd=yes' '--enable-kavd=yes'  '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--enable-dnsauth=yes' '--enable-sslmitm'

**Comment by fredbcode** [comment]
Fixed in V5.2 and develop branch

But with a recent kav version this option is now useless , only icap is 
needed now
