### ISSUE TITLE
[Feature Request] Block SSL VPN's on port 443

### ISSUE THREAD

**Issue by forid786** [e2guardian/e2guardian#443]
Hi guys,

As the title says. I'm looking to block SSL VPN's or VPN's that work on port 443 by tunneling traffic that looks legitimate. This is due to the fact that more and more VPN's and extensions are leveraging the fact that IT administrators cannot block port 443, thus allowing users to circumvent and bypass content filtering policies.

My question is, with MITM can E2 Guardian detect and block these VPN's? I've seen some paid solutions like Smoothwall do this by default but I can only guess that the proxy is blocking anything it cannot decrypt.

Thanks in advance!

**Comment by fredbcode** [comment]
There is no difference between HTTP Tunnel and an usual SSL website so without MITM we can only stop the domain or perhaps in some case User-Agent. I didn't test but yes perhaps just MITM breaks the VPN.
If you test I'm interested by your results

**Comment by DonusumBilgisayar** [comment]
I was able to test my little bit
With mitm, the VPNs are stopping. (I installed the certificate to the clients)
If there is no mitm I run pfense with lan net to pfsense pass (with required ports 80,443,53,8080,8081).
it is still useful to look at the domain names of some VPNs from the logs and to block them.
perhaps it may work if the proxy list is created in the domain list acl.
there are too many domains and ip addresses. shalla list is very inadequate.
Another solution is snort to openappid or pfblocker.

**Comment by forid786** [comment]
MITM breaks VPN's (by blocking domains) but many still get through. One example is using Ultra Surf chrome extension. It uses port 443 to punch through the firewall / E2 Guardian.

Could E2 Guardian identify and block VPN traffic specifically going over these ports and user agents that are fishy? 

Rest of the VPN's that use unusual ports can be locked down quite easily through firewall rules.

**Comment by DonusumBilgisayar** [comment]
some strange chome vpn extensions use very little domain name
for example I blocked with the domain names for ultrasurf
ultrasurf can not connect

heftinesscongresscandy.info
fetalhydrantembroider.info
dimmedfosterwaggle.info

**Comment by forid786** [comment]
Ultra Surf directly connects via IP as far as I'm aware, not sure if that's changed. But the point is there's a lot of VPN's like psiphon that can bypass filtering policies.

And it makes sense for E2 Guardian to implement some methods to block or prevent that. Even if MITM is required.

This might even need to wait until E2 Guardian adds support for ports other than 80/443 for transparent proxy.

**Comment by philipianpearce** [comment]
Currently - using MITM with transparent https or proxy https - ssl connections will be blocked by default if they are not using sni and http protocol  or the SSL can not negotiate using the e2g cert, unless the site or IP is made an exception.
It is fairly simple to add multi-port support for transparent https, should be in 5.3.   Ports other than 80 for http may be later (as this is based on older code). In a later version it may be possible to do some auto-detection on the protocol running.

**Comment by forid786** [comment]
@philipianpearce Have you come across this issue yourself in the past? (Though E2BN customers?)

**Comment by Anthony-76** [comment]
Hi,

It seems that I have the same issue with lot of applications such as vsphere client for example...
With mitm I can't connect to my server via vsphere client.

In this case, is there a way to configure E2guardian in order that allow flows if these flows are not http request?

**Comment by philipianpearce** [comment]
@Anthony-76 

No, detecting non-http sites is generally not possible in transparent https (MITM). The reason is that e2g (or any proxy for that matter) can not tell whether http is being used until after it has done MITM. Non-http apps will not use the system certificates and use their own embedded certs so they reject the e2g server certificate, so e2g never gets to see what protocol is the app is trying to use. 

Apps may or may not use TLS (as used in https) over port 443. 

If they do not use TLS then e2g can detect this, and you can allow it through without MITM by using the storyboard line 'ifnot(tls) setexception'. 

If the app uses TLS (most do) then it may or may not send an SNI as part of the TLS Hello packet. 

If it does send an SNI (Server Name Indication), then it can be allowed by making the site name trusted (exceptionsitelist). 

If SNI is missing then the only info e2g has is the destination IP address. In this case it can allowed by making the IP or IP range trusted (exceptionsiteiplist). 

Philip 

----- Original Message -----

**Comment by forid786** [comment]
@Anthony-76 I run E2 Guardian on pfSense and to avoid the issue you're having. I just exclude the source or destination IP and let it completely bypass E2 Guardian.

**Comment by Anthony-76** [comment]
Hi Philip,

I understand the difficulty/impossibility to avoid this problem.
mitm is mandotary to analyse packet flow.

I tried this last week to make something with iptables and ndpi module but it's failed....

Thanks for your clear explainations.

Anthony

**Comment by Anthony-76** [comment]
@forid786 , I think to do that too. 
Thanks for your tips
