### ISSUE TITLE
https Youtube block in ACL but still can access 

### ISSUE THREAD

**Issue by kenpachizaraki13** [e2guardian/e2guardian#444]
Currently im using pfsense + e2guardian with blacklist.
Youtube is block on the settings but google chrome can still access the site.
But when using incognito mode, https youtube is block.
check the logs also and it was verified blocked.

Is this a google chrome cache?
If so, is there a way to block it?

See image.
![capture](https://user-images.githubusercontent.com/43229864/45468818-42790580-b759-11e8-8484-b5fb852d54f7.PNG)

**Comment by fredbcode** [comment]
Please ask question to the google group (github is for bug report)

There is only one way to debug this, take a look at your logs (squid, 
e2) and see which domains is accessed by chrome and block them.

Block youtube.com is not enough

**Comment by fredbcode** [comment]
I mean what do you have in your logs when youtube is accessed ?

**Comment by DonusumBilgisayar** [comment]
The necessary comments were made in the PFSense forum on this topic.
you can turn off the configuration error.

**Comment by fredbcode** [comment]
@DonusumBilgisayar for the record can you copy/paste the answer here? Please

**Comment by DonusumBilgisayar** [comment]
https://forum.netgate.com/topic/113757/unofficial-e2guardian-package-for-pfsense/916

susamlicubuk about 14 hours ago 
@kenpachizaraki
try blocking the domains below

youtube.com
googlevideo.com
ytimg.com

**Comment by fredbcode** [comment]
Thanks

Le 14 septembre 2018 19:46:45 GMT+02:00, "d.ali.yilmaz" <notifications@github.com> a écrit :
>https://forum.netgate.com/topic/113757/unofficial-e2guardian-package-for-pfsense/916
>
>susamlicubuk about 14 hours ago 
>@kenpachizaraki
>try blocking the domains below
>
>youtube.com
>googlevideo.com
>ytimg.com
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/444#issuecomment-421434131

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
