### ISSUE TITLE
V5.1 included storyboard file error

### ISSUE THREAD

**Issue by Johnny7813** [e2guardian/e2guardian#446]
storyboard file can't be found because the the file name is made lowercase.
Since linux file names are case sensitive the file can't be found any more.
The problem is in file StoryBoard.cpp around line 100. The code is:
``
line = linebuffer.c_str();
        line.removeWhiteSpace();
        if (caseinsensitive)
           line.toLower();
        // handle included list files
        if (line.startsWith("."))  {
            temp = line.after(".include<").before(">");
            if (temp.length() > 0) {
``
this makes the .include statement lower case. But also the file name.

I suggest changing the code to:
`line = linebuffer.c_str();
        line.removeWhiteSpace();
        /*if (caseinsensitive)
           line.toLower();*/
        // handle included list files
        if (line.startsWith(".")) {
            temp = line.after(".Include<").before(">");
            if (temp.length() > 0) {
                if (!readFile(temp.toCharArray(), *LMeta, false)) {
                    listfile.close();
                    return false;
                } else {
                    continue;
                }
            } else {
                continue;
            }
        }
        if (caseinsensitive)
            line.toLower();`

hope this helps,

Johnny

**Comment by philipianpearce** [comment]
Fixed in v5.2 and v5develop.

Work round in v5.1 is only to use lower-case storyboard file names.
