### ISSUE TITLE
Issue in e2guardian 5.1.2 (MIME Type issue, Virus file blocking issue, squid logging issue)

### ISSUE THREAD

**Issue by surjitiit** [e2guardian/e2guardian#450]
I moved from e2guardian 4.02 to e2guardian 5.1.2
following issue i found in e2guardian 5.1.2

1. Not blocking virus text file.
2. MIME type x-ms-wmv not working.
3. When Enabling Blanket block then we are not getting blocked site (by e2guardian5) details in squid access.log file.

**Comment by fredbcode** [comment]
Works well here , which AV ? configuration ? Some messages in logs ?

**Comment by surjitiit** [comment]
> Works well here , which AV ? configuration ? Some messages in logs ?

Issue no 1

I have tested to download **eicar.com.txt** file from [](http://www.eicar.org/85-0-Download.html) . why it is downloading. but when i try to download **eicar.com**  file it is blocked successfully.

I dont know why it is not blocking to download **eicar.com.txt** file. 
In privious e2guarding 4.02 it is working file.

**Comment by Anthony-76** [comment]
@surjitiit : Can you check in exceptionvirusextensionlist . Mybe the .txt is truted.

**Comment by Anthony-76** [comment]
and for mimetype (issue 2): exceptionmimetypelist

**Comment by fredbcode** [comment]
Fixed ?

**Comment by surjitiit** [comment]
yes issue was fixed...thanks
