### ISSUE TITLE
e2guardian -r not working or not reloading conf files

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#452]
Hi,

In E2guardian v4:

when I add a domain (for example domain.com) in exceptionsitelist, then I type e2guardian -r command in order to reload the e2guardian configuration. It works
My client can access to domain.com and in e2guardian log, the domain.com is "TRUSTED" without lost web (http or https) connection.

In E2guardian v5.1.2:

When I do the same method than above, my domain is always blacklisted.
The e2guardian -r command doesn't work
I must do e2guardian -Q to reload my configuration. 
The problem is that web connection to my client is dropped during the excecution on e2guardian -Q

**Comment by fredbcode** [comment]
Hi Anthony 
Please can you give it a try and check with the latest pre-release 5.2.1 ?

**Comment by Anthony-76** [comment]
Hi,

I just try now. It seem better.
I will make other tests tomorrow when I will be in office.

**Comment by Anthony-76** [comment]
Hi,

This morning, I put accounts.google.com in exceptionsitelist
I make e2guardian -r.
Then, I tried to go to the accounts.google.com (put in exceptionsitelist) and I have an E2guardian blacklist message.

So, I have to e2guardian -Q 
Then I can access to accounts.google.com

Sometimes, e2guardian -r works sometime not

**Comment by fredbcode** [comment]
In SSL mode the browser/website session still open, if you close your 
browser and reopen it you should see the website

Can you confirm you are not already connected before ?

Also accounts.google.com is right denied in logs? (not an another domain 
related)

**Comment by Anthony-76** [comment]
You are right.
When I close the browser and reopen it, it's ok. I can access to the website

**Comment by fredbcode** [comment]
Ok, so I close it's a normal behaviour
