### ISSUE TITLE
v5.2.1: ICAP with F-Secure broken, any site blocked

### ISSUE THREAD

**Issue by Schroeffu** [e2guardian/e2guardian#457]
Since v5.2.1 (before 5.2.0) the ICAP content scanner is not working anymore with F-Secure Internet Gateway (FSIGK). The following error message appears on any site, everything is blocked now:

**ICAP returned unrecognised response code.** 

With Pre-Release 5.2.0 the ICAP scanner was working with FSIGK but the execption handling was not embedded i think. It felt like any exception from icap FSIGK means, virus found, blocked, that was ok because only sites with virus were blocked (with a non-sense error message: "Ein Virus oder unerlaubter Inhalt wurde gefunden. Unknown). But now, any website is blocked by contentscanner icap with the the error message above.

The support of FSIGK was discussed here: https://groups.google.com/d/topic/e2guardian/CRQ4KJF5L18/discussion

My icapscan.conf:

```
plugname = 'icapscan'
icapurl = 'icap://localhost:1344/respond'

```

**Comment by fredbcode** [comment]
Hi,

Switched to branch 'v5.1-icapc'
Your branch is up to date with 'origin/v5.1-icapc'.
root@ubuntu-bionic:~/e2guardian# src/e2guardian -N

1538552333.955        -    127.0.0.1    127.0.0.1 http://numsys.eu    
GET    403    34081    text/html    - -203    -    0    *SCANNED* 
*DENIED* ICAP returned unrecognised response code.    0    Content 
scanning    no_mame_group    1

The previous version still works for you ?

**Comment by fredbcode** [comment]
Perhaps ?

tail -f /opt/f-secure/fsigk/log/fsicapd/fsicapd.log
2018-10-03 07:36:49 fsicapd/src/license.c:83[8] license: No valid license
2018-10-03 07:37:20 fsicapd/src/license.c:83[8] license: No valid license
2018-10-03 07:38:32 fsicapd/src/license.c:83[8] license: No valid license

**Comment by Schroeffu** [comment]
Hi Fred,

I have a license active, there is a check binary also which gives me:

/opt/f-secure/fsigk# ./license_check
License OK: Valid License(for corporation)

Yes, previous version 5.2.0 is still working. I deleted 5.2.1 and installed 5.2.0 again, working again.

With the old 5.2.0 where ICAP with FSIGK is working, the output while virus is found in /opt/f-secure/fsigk/log/fsicapd/fsicapd.log is 
`2018-10-04 09:27:17 fsicapd/src/server.c:1254[7] [26669:1] ICAP header parsing failed: network I/O error 104 (Connection reset by peer)` (virus source https://schroeffu.ch/eicar.com.txt with MITM). It was not extracting the virus-name from the response header from ICAP, but that ok for now, it was blocking viruses found by FSIGK.

What has changed with 5.2.1?

**Comment by fredbcode** [comment]
Hi,

Weird, no nothing to the icap client part

https://github.com/e2guardian/e2guardian/commits/v5.2/src/contentscanners/icapscan.cpp

But something as icap server (but should be not related ...)

https://github.com/e2guardian/e2guardian/commit/2456c46d055a0c001baee03042870c38fca90c30#diff-25d902c24283ab8cfbac54dfa101ad31

Can I have a testing licence (do you have a commercial contact ?) or an 
access to your machine ?

Thank

**Comment by Schroeffu** [comment]
Hmm thats confusing. I think for reproducing i should setup a proxy without the ubuntu binary but the compiled sourcecode. makes it easier for me to test between versions without your help compiling it for ubuntu 18.04.

Unfortunately our servers I setup are all in the company network, I can't give you access to them. The license we use is commercial, can't give you this too sorry. Our license was from a local distributor. 

But I sent an eMail to an employee from F-Secure to ask where Open Source projects can ask for testing licenses. Will inform you when I get an answer.

**Comment by Schroeffu** [comment]
@fredbcode  i think it was really an issue with the license, or similar with f-secure. we should close this issue, sorry!

i have 4 proxies in pre-production, just rollbacked today the last 3 too. result: 2/4 are working, 2/4 aren't, but they are build identically with ansible..... so I was terribly confused... I re-run "make install" in the f-secure installer path, on all 4 proxies, without ansible (ansible skips this task if installed already), now all 4 of them are working as expected again.

maybe the recompilation did something required to run properly.... I am still confused, but now it is working with 5.2.1 too. sorry again.

**Comment by fredbcode** [comment]
No problem, keep us in touch it will be interesting to see what happens here

**Comment by fredbcode** [comment]
Some news ?

**Comment by Schroeffu** [comment]
@fredbcode about a license for you for testing? a german contact from F-Secure said usually just get a (new) trial here: https://www.f-secure.com/fr_FR/web/business_fr/internet-gatekeeper but they are asking internal if there is another way (for open source projects).

about the issue itself, its still working after re-install f-secure with make install. cannot reproduce that. for me, we still can close the issue.

**Comment by fredbcode** [comment]
Ok thank you, they can contact me directly at numsys - @ - free.fr

**Comment by Schroeffu** [comment]
by the way: usually security companies are calling all possible customers at the end of trial time. asking if you are happy etc. this is another chance to explain the situation to get a real license for the open source project, isn't it?

**Comment by fredbcode** [comment]
Yep ! and now they can adds a beautiful sticker "E2guardian approved !"

**Comment by Schroeffu** [comment]
Absolutely ;-) when the license problem is resolved, maybe you have the fun to improve it, adding the name of found virus (catch from the icap response header) in the e2guardian denied page would be cool : - )

**Comment by fredbcode** [comment]
Of course yes, but right I'm not really motivate to remove and reinstall a product each time a test is needed ...
For information, it also works well with kav4proxy from Kaspersky
