### ISSUE TITLE
Reload e2guardian not reload ipgroups after changing ip address from filter group to other filter group

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#458]
Hi,

I use E2guardian 5.2.1 on Debian 9

I change my IP address from filter 1 to filter2 in /etc/e2guardian/lists/authplugins/ipgroups.
Then I do e2guardian -r. When I see on access.log, my IP @ is on the same filer (filter1 not filter2)

I saw in the past the issue #158. The same issue of mine

I do e2guardian -g and the result is the same than e2guardian -r.

In order to take in consideration my conf, I need to restart E2guardian

So, E2guardian is able to reload change in filtergroupslist file without restart E2guardian? 
If not, is it possible to add this function on the next E2guardian release or it's impossible?

Anthony

**Comment by philipianpearce** [comment]
I have looked at the code and this is a bug - currently all authplugins configuration are only loaded at start-up.  This has been the case since v4.0.  The gentle restart (-g) option has never reloaded auth-plugins and previous to v5 only reloaded lists.

v5 introduced fn.conf, lists from e2guardian.conf and storyboard re-reading on -g/-r, but reload of authplugs configuration was missed!

It is possible to add this function and it will be fixed in the next release (v5.3).

Note the -g and -r options have exactly the same function since v4.0.  Both have been retained for backward compatibility with control scripts etc.

**Comment by Anthony-76** [comment]
Hi @philipianpearce ,

Thanks for your answer.

If you want, I can make some tests for your pre-release.

Anthony

**Comment by philipianpearce** [comment]
Fixed in v5.4.dev??  Please test - note changes to auth plug-in list defines and plug-in .conf files and pre-auth.story storyboard

**Comment by Anthony-76** [comment]
I will try as soon as possible (maybe the next week)

**Comment by Anthony-76** [comment]
I just test with the last 5.4-dev.

Like in release 5.3, I must restart e2guardian in order to change IP addresse from group to other group.

The e2guardian -r or service e2gaurdian reload don't reload my modification

**Comment by philipianpearce** [comment]
Hi @anthony-76, 

It works ok in my tests here (in proxy mode). 

Can you confirm that you have the ipmaplist defined in e2guardian.conf and that you are using the revised sample pre-auth.story? 

Also, can you provide more details:- what platform? transparent or proxy mode? 

----- Original Message -----

**Comment by Anthony-76** [comment]
Hi @philipianpearce 

Yes, excatly. I use ipmaplist and pre-auth.story

However, I use non transparent proxy (without other parent proxy like Squid). Maybe is the cause of my issue?

So E2Guardian 5.4-dev in installed on Debian10 with the following "./configure"

e2guardian 5.4.0

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'

Thank you

Anthony

**Comment by philipianpearce** [comment]
@Anthony-76 

Is this now fixed for you, can I close?

**Comment by Anthony-76** [comment]
Hi @philipianpearce 

Sorry for the delay.
Currently I have no free time to test.
In my last comment, it was not fixed.

I will try to test as soon as possible.
