### ISSUE TITLE
[Feature Request] - Question : Quic or 0-RTT protocol how to analyze

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#459]
Hi,

I post my question here, Maybe it's not the good place

I assisted today to a conference about QUIC protocol.
Currently, QUIC is mainly use with Youtube

Facebook work on the same type of protocol

It seems in the near future this protocol will be use for lot of webpages

Maybe I'm wrong, the mitm (ssl inspection) will be impossible with QUIC protocol because this procotol is more and too secure than tls and It's impossible to analyze the flow content.

In this case, how E2guardian or other webfilter will scan flow and dat in this protocol in order to block virus or access to the website?

If the flow analyze is impossible, any webfilter solution will be over?

Anthony

**Comment by mveplus** [comment]
Hi @Anthony-76 , 
[QUIC](http://www.chromium.org/quic) is very similar to TCP+TLS+HTTP/2 implemented on UDP. 
Google’s version of QUIC (often called [gQUIC](https://docs.google.com/document/d/1gY9-YNDNAB1eip-RTPbqphgySwSNSDHLq9D5Bty4FSU/edit)) does roll its own crypto, but that is currently being standardised by IETF (commonly known as [iQUIC](https://datatracker.ietf.org/wg/quic/about/) for now) which basically uses TLSv1.3. Eventually, iQUIC will replace gQUIC just like HTTP/2 replaces SPDY [Barry's comment](https://ma.ttias.be/googles-quic-protocol-moving-web-tcp-udp/). 
Before we can start talking for QUIC inspection, the first request naturally should be [HTTP/2](https://github.com/http2/http2-spec/wiki/Implementations). Then once iQUIC and TLSv1.3 are finalized by [IETF](https://quicwg.org),  may present options to add QUIC in the mix as well. But for now, QUIC open-source [tools](https://github.com/quicwg/base-drafts/wiki/Tools) and libraries are [ few](https://github.com/quicwg/base-drafts/wiki/Implementations).  
Let's assume HTTP/2 is implemented in e2guardian, and open source [tools](https://github.com/quicwg/base-drafts/wiki/Tools) for [QUIC/TLSv1.3](https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/PT2y_Ol2eOk) emerge that will allow implementing [a QUIC client](https://github.com/devsisters/libquic) into e2guardian, then the following senario may become possible:

Web-server - 443/UDP/QUIC <HTTP/2 - multiplexed streams>------> e2guardian { acting as QUIC client dissecting to HTTP/2 } e2guardian 443/TCP/TLS streams <-----HTTP/2------>  Client browser

[HTTP/2 & QUIC teaching good protocols to do bad things](https://www.blackhat.com/docs/us-16/materials/us-16-Pearce-HTTP2-&-QUIC-Teaching-Good-Protocols-To-Do-Bad-Things.pdf)
Sources&Credits follow the links

Cheers,

**Comment by fredbcode** [comment]
Hi,
I don't know if there is something about with Squid, but in this case icap mode is a short term solution.
Let the proxy (squid, bluecoat, etc) doing the job and check the result with icap

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Anthony-76** [comment]
Hi @mveplus and @fredbcode ,

Thanks for yours explainations. Yours differents sources are interresting.

I red others articles about that. Currently, others security vendors can't analyze this protocol.
I think and hope than in the future new solutions and technologies will appear to permit an inspection for the security.

@fredbcode, maybe I'm wrong and I'm not an expert about proxy, but if the tls1.3/http2 inspection is not possible, how proxies can do the job via ICAP support?

**Comment by fredbcode** [comment]
tls1.3/http2 inspection is not possible now, but when a new technologies will appears e2guardian will be able to inspect requests from this.
Without ICAP it well not be able at all.

With ICAP e2guardian is not a proxy anymore, the "new proxy" is configured to decrypt the requests, identify the users, connect to internet, etc and the results are sent to E2 in parallel  

For example, today ICAP is the only way to integrate your proxy in AD (kerberos mode) and still use E2 as web filter. Why ? because E2 in proxy mode can't "decrypt" username from a web request because the security is too strong when we use proxy chaining (with Squid and others) and there is no identification plug-in in stand-alone proxy mode for now.

Of course it's not a full answer to TLS1.3, but good to know I think

**Comment by Anthony-76** [comment]
Ok,

Thank you for these explainations
