### ISSUE TITLE
*NETERROR* Unable to connect to upstream proxy (network error)

### ISSUE THREAD

**Issue by LucayanBuchelt** [e2guardian/e2guardian#460]
> *NETERROR* Unable to connect to upstream proxy (network error)

this error is appearing in "Real Time".
![error](https://user-images.githubusercontent.com/42984203/46742789-21cf9d00-cc7e-11e8-9c77-dad573e8abc7.png)

**Comment by fredbcode** [comment]
It's a configuration issue, e2guardian can contact your proxy
