### ISSUE TITLE
SB warning: Undefined list addheader used at line

### ISSUE THREAD

**Issue by LucayanBuchelt** [e2guardian/e2guardian#461]
error returned when i start e2guardian by console.
does anyone know what this is?
tks.

full error:

> [2.4.3-RELEASE][root@fw.lab.local]/root: e2guardian
> SB warning: Undefined list addheader used at line 32 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 33 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 73 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 74 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 139 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 146 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 32 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 33 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 73 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 74 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 139 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 146 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 32 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 33 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 73 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 74 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 139 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 146 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 32 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 33 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 73 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 74 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 139 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 146 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 32 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 33 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 73 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 74 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 139 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 146 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 32 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 33 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 73 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 74 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 139 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 146 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list addheader used at line 73 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list override used at line 74 of /usr/local/etc/e2guardian/common.story
> SB warning: Undefined list exceptionuseragent used at line 139 of /usr/local/etc/e2guardian/common.story
>

**Comment by fredbcode** [comment]
Which version ? Config files from ?

**Comment by LucayanBuchelt** [comment]
> Which version ? Config files from ?

pfsense: 2.4.3-RELEASE-p1 (amd64) 
e2guardian5  version: 0.5.0.4_2

**Comment by fredbcode** [comment]
Please contact the package maintener, or ask to our mailing list. 
GitHub is for bug report and this is a configuration issue something is missing here.
