### ISSUE TITLE
Firefox issues with latest version of E2guardian

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#462]
I have setup the latest version of E2guardian 5.1 along with MITM.

I have discovered three things

1. With or without MITM (and/or using the accesdenied/cgi-bin workaround, Firefox will not show the Access Denied Page. With the same settings in E2guardian 3.4.0.3 I could get the Access Denied Page - when not using MITM or SSL. Access Denied Page coming up in MITM as desired in IE.

2. Firefox will not use the E2guardian certificates that I have setup. Works flawlessly in IE

3. I have also noticed in this version of E2guardian, if you put in say www.jigsaw24.com or any http address (when not using MITM or SSL enabled), the page won't load in Firefox as it seems to have problems converting from http to https if website is using https. Yet this worked in E2guardian 3.4.03 without MITM or SSL enabled in E2guardian.

Is there any solution to these issues or does E2guardian now only support Chrome and IE

**Comment by fredbcode** [comment]
You mean 5.2.2 ?

Le 19 octobre 2018 18:08:40 GMT+02:00, Dalacor <notifications@github.com> a écrit :
>I have setup the latest version of E2guardian 5.1 along with MITM.
>
>I have discovered three things
>
>1. With or without MITM (and/or using the accesdenied/cgi-bin
>workaround, Firefox will not show the Access Denied Page. With the same
>settings in E2guardian 3.4.0.3 I could get the Access Denied Page -
>when not using MITM or SSL. Access Denied Page coming up in MITM as
>desired in IE.
>
>2. Firefox will not use the E2guardian certificates that I have setup.
>Works flawlessly in IE
>
>3. I have also noticed in this version of E2guardian, if you put in say
>www.jigsaw24.com or any http address (when not using MITM or SSL
>enabled), the page won't load in Firefox as it seems to have problems
>converting from http to https if website is using https. Yet this
>worked in E2guardian 3.4.03 without MITM or SSL enabled in E2guardian.
>
>Is there any solution to these issues or does E2guardian now only
>support Chrome and IE
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/462

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Dalacor** [comment]
No installed e2guardian over a week ago. Did not realise that a new version was coming out. I will install the new version.

I may close this question as points 1 and 3 are fixed if using mitm in Firefox. As everyone will be using mitm there is no value in fixing things so that Firefox works when not using mitm.

I have discovered that I need to install certificate in authorities in Firefox. Then mitm works.

So if you want to close this issue as Firefox now works in mitm this fixing all three issues.

I presume you need to install certificate in certificates in windows for ie and in authorities for Firefox. I will have a look at documentation for certificates for ipads.

Thanks
