### ISSUE TITLE
Transparent HTTPS Proxying and MITM causes E2guardian to crash

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#463]
I have read up on the Internet and it seems that quite a few people have this issue where E2guardian works flawlessly when not using Transparent HTTPS and not using MITM or more specifically when SSL is not enabled in E2guardian.

If you enable SSL, transparent https proxy or MITM or any combination E2guardian will work for a while - anything between a few minutes to up to an hour before E2guardian crashes. There seems to be no consistency in the time it takes before it crashes.

Have the developers identified the underlying cause of this crashing. I am using openssl-1.0.2h if that is relevant?

**Comment by fredbcode** [comment]
Which version and OS, libssl1.0 is pretty old now

**Comment by Dalacor** [comment]
E2guardian 5.1 which I installed about 2 weeks ago. Slackware 14 and above mentioned openssl. I presume that it is the openssl version that is the issue. However I
 thought that e2guardian 4 had been updated to not crash e2guardian if there was some issue with ssl or mitm. Thanks

**Comment by fredbcode** [comment]
Can you try the latest 5.2.2 and check if there is a way to compile with libssl1.2-dev ?

**Comment by fredbcode** [comment]
Sorry libssl1.1 (Dev library)

**Comment by Dalacor** [comment]
I will see if I have time this weekend. Thank you. I have the debugger running so will check what that says when e2guardian crashes. Have a good weekend

**Comment by Dalacor** [comment]
E2guardian crashed, but nothing in the debugger file. As I will be upgrading to the 5.2.2 version and upgrading openssl I am not too worried, but you might want to file a bug that E2guardian still crashes if there is some issue with presumably openssl as I would imagine that whatever the issue present in E2guardian 5.1 is likely to be present in 5.2.2. Thanks

**Comment by philipianpearce** [comment]
I believe this may have something to do with the build platform.  We have lots of customer systems using transparent http/https with MITM and we are not seeing this as a general issue.   Our build platform is CentOS6.    

What we have seen on some (very few) customer sites is that some apps (such as whatsapp) will not work with transparent https, behave very badly by failing to connect and then retrying many times a second causing effectively a DOS attack on e2g.   This also happens with transparent https without MITM. This can be mitigated by using iptables to rate limit the number of connections from a single device (i.e. source IP). Or by blocking the destination addresses using iptables.  Or by banning users from using these rouge apps. Or by whitelisting in e2g the app sites/IPs if you want to allow them through.

**Comment by Dalacor** [comment]
I have only been using the new version of E2guardian on a test proxy server. So the only person going through that proxy was me. I just used my laptop and one computer to test the proxy server. But you have given me an idea to check whether clamav or squid blacklist may be causing the problem as I have set these to download automatically. This might explain why even when no websites are accessed E2guardian crashes.

I will try Fredb's suggestion first as I think that upgrading the openssl may fix a lot of problems. I still have not got around to doing this yet.

**Comment by Dalacor** [comment]
Upgrading to latest Openssl and or upgrading to latest E2guardian seems to have fixed this issue. Thank you.

**Comment by cbroque** [comment]
I'm having the same issue on Oracle Linux 7.6, it's running the latest packages.

These are my ssl rpms:
openssl-devel-1.0.2k-16.0.1.el7.x86_64
openssl-1.0.2k-16.0.1.el7.x86_64
openssl-libs-1.0.2k-16.0.1.el7.x86_64

**Comment by cbroque** [comment]
I was able to fix it, has something to do with permissions, e2guardian is running as clamscan user, I changed the e2guardian directory (recursively) ownership to this user and it worked, I think the issue was releted with the generatedcerts dir,

**Comment by Dalacor** [comment]
Why don't you use openssl 1.1 - versions 1.0 are getting a bit old now and this was the main cause of the problem for me. So it's likekly that you will still experience issues.

**Comment by cbroque** [comment]
That version is not available on the vendor repos, I'm running the latest published version for this distribution. But again that was not the issue.
