### ISSUE TITLE
v5.2: mitmcertcheck does not seem to validate wildcard certificates correctly

### ISSUE THREAD

**Issue by bmuel** [e2guardian/e2guardian#465]
Hi all,
after a bit of testing and reviewing the Code, I may have found a Scenario where mitmcertcheck does not validate Wildcard certificates correctly.

The Scenario is: hostname: https://wrong.host.badssl.com/, certificate is CN and SAN *.badssl.com. 
It seems that Wildcard certificates should not cover more than one Level of subdomains (https://en.wikipedia.org/wiki/Wildcard_certificate). The Major Browsers are recognizing this Scenario as invalid, but e2g loads it without complaint.

After taking a peek at the Code, I think that e2g is only checking if the hostname Ends with the Wildcard Domain, but does not check if hostname contains further subdomains.

Best regards,

Ben

**Comment by philipianpearce** [comment]
@bmuel     Hi could you re-test with latest version  (v5.2 or v5develop)?

**Comment by bmuel** [comment]
Hi. Will do that in the next few days. Need to setup a test environment first.

 

Von: Philip Pearce <notifications@github.com> 
Gesendet: Montag, 5. November 2018 16:19
An: e2guardian/e2guardian <e2guardian@noreply.github.com>
Cc: bmuel <b.mueller@kbmnet.de>; Mention <mention@noreply.github.com>
Betreff: Re: [e2guardian/e2guardian] v5.2: mitmcertcheck does not seem to validate wildcard certificates correctly (#465)

 

@bmuel <https://github.com/bmuel>  Hi could you re-test with latest version (v5.2 or v5develop)?

**Comment by bmuel** [comment]
@philipianpearce 

Hi Philip,
recognition seems to work perfectly. But the message seems to have a placeholder problem. 
I tried attaching a screenshot, but couldn't. The message is as follows:

> SSL SITE Server%27s SSL certificate does not match… 

Best,

Ben
