### ISSUE TITLE
function(checkrequest) setblock

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#467]
Tried adding the following to the checkrequest storyboard but doesn't seem to block anything.  The idea here is that at specific times a script adds this to the storyboard to block all internet access.  Not sure if the common storyboard is the proper place to do this either.  The script also changes the template to indicate internet access blocked and does a e2guardian -r reload.

function(checkrequest)
return setblock
....

tried also

function(checkrequest)
setblock
.....

**Comment by philipianpearce** [comment]
Your command line syntax is wrong. See https://github.com/e2guardian/e2guardian/blob/v5.2/notes/V5_Storyboard.pdf 

Correct syntax is if(true) return setblock. 

The best file to change is site.story. Functions in common.story can be overwritten in site.story or fn.story. 

Add:- 

function(checkrequest) 
if(true) return setblock 

to site.story 

Regards 
Philip 

----- Original Message -----
