### ISSUE TITLE
incorrect error message

### ISSUE THREAD

**Issue by nerijus** [e2guardian/e2guardian#47]
Config problem; check allowed values for maxsparechildren
Error parsing the e2guardian.conf file or other e2guardian configuration files

But actually it was minchildren = 120 which was incorrect; setting it back to 64 made e2guardian to start. BTW, it would be nice to provide max values for maxchildren, minchildren, minsparechildren, etc in comments of e2guardian.conf.

**Comment by fredbcode** [comment]
Upgraded in dev branch

**Comment by fredbcode** [comment]
Fixed in 3.5.0
