### ISSUE TITLE
v5.2 ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by ghost** [e2guardian/e2guardian#470]
I'm seeing an issue with the latest 5.2.2 build and the following resource - http://www.altoservice.co.uk/content/Login.php

When submitting the form (blank with no details is fine) connections through e2guardian receive no response at all, with Chrome showing an ERR_EMPTY_RESPONSE error page. Direct connections to the internet will receive response containing an invalid user page. 

Please let me know if there is any further information I can provide to help debug this.

**Comment by fredbcode** [comment]
Yes more informations are needed, are you using SSLMITM ? Do you have something in logs (squid, e2, syslog) ?

**Comment by ghost** [comment]
Yes, running SSLMITM. Logs show altoservice.co.uk is allowed when the page is loaded and then absolutely nothing once the form is submitted.

**Comment by Anthony-76** [comment]
Hi 

I have the same error.
I use E2guardian 5.2.2 on Debian 9 with SSLMITM.

But, this Website works only on http not https.

With Chrome, I have the following message (Message returned by Chrome)

Cette page ne fonctionne pas www.altoservice.co.uk n'a envoyé aucune donnée.
ERR_EMPTY_RESPONSE


With Firefox, I have no error message.
The webpage stay on login.php even if I put bad login/password

In E2guardian logs I have only that:

2018.11.09 23:18:30 10.100.200.16 10.100.200.16 http://www.altoservice.co.uk/content/Login.php - POST 0 0 - 3 100 - 


I put the domain to whitelist and the result is the same.

They are no more information in /var/log/syslog, message logs.......


Without pass through E2guardian, the website works

**Comment by philipianpearce** [comment]
Issue is to do with 100 Continue mis-handling.   Raised as bug #480

**Comment by philipianpearce** [comment]
Bug #480 fixed also fixes this issue.
