### ISSUE TITLE
Preserve old DansGuardian SVN repository from SourceForge

### ISSUE THREAD

**Issue by matjon** [e2guardian/e2guardian#472]
Hello,
When e2guardian was started, no history from the DansGuardian repository on SourceForge ( https://sourceforge.net/p/dansguardian/code/HEAD/tree/ ) was imported. Instead, all files were just copied and checked in in the first commit ( https://github.com/e2guardian/e2guardian/commit/b8056eb74e839386ae6dd836ff662f9b787d94f1 ). To protect the old DansGuardian history from disappearing (just like it happened with the http://dansguardian.org web site), I would propose to import it into a separate GitHub project, perhaps https://github.com/e2guardian/e2guardian_old .

This could be made like this:

    git svn clone --stdlayout --preserve-empty-dirs https://svn.code.sf.net/p/dansguardian/code/trunk dansguardian-old 
    git remote add github https://github.com/e2guardian/e2guardian_old.git
    git push --tags --all github HEAD

The `git svn clone` command could be refined with the `--authors-file` switch which would reference a file with mappings from SVN usernames to real names and e-mails. For more, see: https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git .

Additionally, bugs and feature requests from SourceForge could be imported too (to the e2guardian_old repository). There are several tools to do that, for example:

- https://github.com/cmungall/gosf2github

- https://github.com/ttencate/sf2github

but they seem to require administrator access to the SourceForge repository to export project data. Possibly previous maintainer of DansGuardian (Aecio F. Neto) could be asked for it.

**Comment by fredbcode** [comment]
Hello,

Yes good idea, for a historical point of view

Maybe I had an administrator account on SF, Ido not remember exactly

About username and changes I wrote the detailed changes in Changelog 
file, I guess it's enough now

Bug and feature request seems to me useless now

Regards

Fred



Le 12/11/2018 à 12:34, Mateusz Jończyk a écrit :

**Comment by philipianpearce** [comment]
OK,  dansguardian repository archived as dansguardian-old for reference.
