### ISSUE TITLE
Computer Name issue

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#475]
Latest version E2guardian 5.2.2 with MITM etc. I am not using Squid. I am using E2guardian for proxy.

Access.log file shows Computer Names of source computer, but the template.html shows blank for -HOST-

Not sure if this is a bug or some strange configuration problem on my part but given that the Access.log file shows the computer name, I assume its a bug?

Thank you.

**Comment by forid786** [comment]
On my setup I had to setup DNS to register host names to fix this for example, this is on FreeBSD (pfSense). What platform are you running this on and have you tried enabling a similar feature?

**Comment by Dalacor** [comment]
Windows Server 2016 is set as the DNS Server and I have enable ptr records. The access logs for E2guardian are showing the computer name, so not sure why the template is not! Oh well, I will have to play with that. Maybe its some issue with Slackware, but its probably some configuration issue with E2guardian I suspect.

**Comment by forid786** [comment]
@Dalacor Have you enabled DNS auth at all? For me it pretty much started working after registering the DNS entries.

But if the access logs actually show computer names then it most likely would be a config issue, have a play around and let us know if you manage to get this up and running

**Comment by Dalacor** [comment]
No I have not enabled DNS auth, but I am not authenticating via DNS. I am using Port authentication. Unless enabling DNS auth enables the varialbe -host- to work, but that doesn't make sense because the access logs would also have no computer name.

Ya, I will have to spend Saturday looking around to see if I can find the cause of the issue as it must be some kind of configuration issue somehwere.

Thanks

**Comment by forid786** [comment]
@Dalacor The reason I suggested DNS auth is because I've seen some strange behaviour with E2 Guardian here and there on platforms that the devs haven't tested it on themselves.

Sure, good luck with it! But still on the hunt for those phrase lists, Philip was going to update them :c

**Comment by Dalacor** [comment]
I can try Pfsense as well and see if its an E2guardian configuration issue or something else. I will have to leave that till Saturday or Sunday. But as I understand it, I don't think that DNS auth is the solution as I am not using DNS for authentication. But I will read up on it anyway. Thanks @forid786

**Comment by forid786** [comment]
I just asked you to try it because I've had this issue on pfSense before and enabling it fixed it. However in later E2 Guardian builds it seems to have been fixed properly. So now even without that enabled it looks fine. But yeah like I mentioned when you use E2 Guardian on platforms that the devs haven't tested it on. Sometimes you have to expect slightly weird or unexpected behaviour.

**Comment by Dalacor** [comment]
I had the bright idea of testing computername on the old e2guardian computer but on the same network as the new e2guardian computer. I am getting the computername on the template.html file so I can rule out the network itself as in the Windows Server, router etc. I just have to copy the e2guardian.conf and e2guardianf1.conf files from the old e2guardian to the new e2guardian system and see what works.

I will get myself a cup of coffee and see if I can get this issue cracked before I go to bed. Thanks

**Comment by Dalacor** [comment]
@fredbcode  I would like to file this as a bug.

I took a hard drive and freshly installed Slackware and both E2guardian 5.2.2 as well as E2guardian 3.4.03 and Squid for the old version of E2guardian obviously.

The only changes that I made in both e2guardian.conf files is to enable logclienthostnames = on and I copied my template.html file which includes the -HOST- variable to the UKenglish folder. On the old E2guardian I get the computer name showing on the template as well as in access.log file, the new E2guardian does not show the name on the access denied page that comes up, but does show the computer name in access.log file.

I tried changing the logging settings in the new version to match the logging settings of the old version in the conf files. With no difference.

I tried compling with the DNS auth option, with no change. I am not sure what if anything I need to enable in the conf files. But I don't believe that this has anything to do with the issue.

I even tried getting E2guardian 5.2.2 to go through the same squid proxy server that I setup E2guardian 3.4.0.3 and still no joy and I noticed that the access denied doesn't even go through the squid proxy anway with the new version of E2g.

I agree with @forid786 that the issue is one of two things. His system has something compiled that Slackeware doesn't that the new version of E2guardian needs - I suspect the difference is that the old version relied on Squid to get all the information (which is no longer the case with the new E2G) or the second cause is that I have missed something in my conf files that could be causing the problem.

But seeing as I installed both versions of E2guardian on a completely and brand new distro install and only edited the e2guardian.conf file to enable logclienthostnames and copy my template file across yet the result is different depending on which version of E2g I am running. I compiled both e2g with the same options. This to me looks like a bug not a configuration issue.

Thank you

**Comment by Dalacor** [comment]
Version 4.0.1 works.

It would seem that the problem with this started with version 5.1 when E2g moved to optional proxy and storyboard logic. My guess is E2g moving to optional proxy is causing this problem for Slackware not the storyboard logic, but I can't say for sure.

So I am satisfied its some kind of bug. Thank you.

**Comment by philipianpearce** [comment]
v5 has completely new logic code and there is a bug in this.  Not do do with optional proxy or storyboard, but due to the moving of a set of variables from handleContainer class into NaughtyFilter class.

Will fix.

**Comment by philipianpearce** [comment]
Fix applied to v5.2.

Please test to now confirm now OK.

**Comment by Dalacor** [comment]
Hi Philip,

I have edited the three files in the src folder and recompiled E2guardian. I can confirm that this has fixed the issue on the limited testing that I did. I just tested two websites that I added to the bannedsitelist file. But I presume that this will apply to content, phraselists etc. I will let you know if I see any issues with this as I will be working on E2guardian quite a bit in the next 8 weeks.

I presume that I need to download the zip file where it says clone or download to receive the very latest changes. I download the source tarball file but this was the 5.2.2 release without any further commits. So I ended up editing the src files.

Thank you for fixing this issue so quickly. I was expecting it to be a big job to find the cause because it seems to work fine for forid786 so it sounded like some platform issue. Thank you!

**Comment by forid786** [comment]
@Dalacor My experience will be different to other platforms because the Dev for pfSense spots and fixes bugs here and there himself. Sometimes it's probably not obvious that it's an E2 Guardian issue so it may not make it upstream.

**Comment by Dalacor** [comment]
@forid786 Fair point.  I have been meaning to look at pfSense but never got around to it. Slackware on the whole I have been very pleased with. Rock solid stable, easy to setup and easy to configure so never really needed to look at anything else.

**Comment by forid786** [comment]
@Dalacor Yeah I run E2 Guardian on pfSense because pfSense is an absolutely amazing platform. Based on FreeBSD it's really stable and has a great networking stack, and has a lot of enterprise firewall features. The only thing missing was a decent filtering addon for it. I used squid and squid guard but they don't work well with HTTPS anymore and rely too much on black lists.

**Comment by philipianpearce** [comment]
> Hi Philip,
> 
> I have edited the three files in the src folder and recompiled E2guardian. I can confirm that this has fixed the issue on the limited testing that I did. I just tested two websites that I added to the bannedsitelist file. But I presume that this will apply to content, phraselists etc. I will let you know if I see any issues with this as I will be working on E2guardian quite a bit in the next 8 weeks.
> 
> I presume that I need to download the zip file where it says clone or download to receive the very latest changes. I download the source tarball file but this was the 5.2.2 release without any further commits. So I ended up editing the src files.
> 
> Thank you for fixing this issue so quickly. I was expecting it to be a big job to find the cause because it seems to work fine for forid786 so it sounded like some platform issue. Thank you!

No problem.      

Since v4 we try and write code to support both Linux and freebsd.  There are some differences in the system calls available and some calls are thread-safe in Linux but not in freebsd.  Where there are any issues in the freebsd porting these have always, as far as I am aware have reported to us, and we have adjusted the code to use calls that will work correctly in both Linux and freebsd.

Regards Philip
