### ISSUE TITLE
v. 5.2: Repeated "Proxy authentication error" (key 110) 

### ISSUE THREAD

**Issue by resoli** [e2guardian/e2guardian#481]
I've just compiled latest v5.2 from git, because of #464. I noted using firefox 63.0.3 there are repeated failed GET requests to firefox detect connection url (which does not requires auth in my configuration):

from e2g access.log:
`2018.11.28 15:10:50 - 192.168.11.18 http://detectportal.firefox.com/success.txt *DENIED* Proxy authentication error GET 0 0 - 1 403 - 192.168.11.18 GruppoStandard - - - - -`

from squid access.log:
`Wed Nov 28 15:10:47 2018.819      7 192.168.11.18 TCP_MISS/200 485 GET http://detectportal.firefox.com/success.txt - HIER_DIRECT/88.221.145.81 text/plain`

I think this is a regression introduced in "ConnectionHandler.cpp" to fix #464.

**Comment by philipianpearce** [comment]
Would you try adding 'detectportal.firefox.com' to your authexceptionsitelist and see if that fixes the issue?

This list should contain all sites that are needed to be accessed. e.g. update sites,etc without authentication.

Philip

**Comment by resoli** [comment]
Tried, but the response is 403 anyway:

`2018.11.28 16:11:08 - 192.168.11.18 http://detectportal.firefox.com/success.txt *DENIED* Exception site match.detectportal.firefox.com GET 0 0 - 1 403 - 192.168.11.18 GruppoStandard - - -`

I tried to add firefox.com to the exceptionsitelist of both `GruppoFacebook` and `GruppoStandard` filtergroups and it worked:
`2018.11.28 16:33:45 resolir 192.168.11.18 http://detectportal.firefox.com/success.txt *TRUSTED* Exception site match.detectportal.firefox.com GET 8 0 - 4 200 - 192.168.11.18 GruppoFacebook - - - - -`

Strangely, both sites are in a squid whitelist for excluding them from authentication.

**Comment by resoli** [comment]
I will review my configuration, expect some update tomorrow ...

**Comment by resoli** [comment]
> I tried to add firefox.com to the exceptionsitelist of both `GruppoFacebook` and `GruppoStandard` filtergroups and it worked:
> `2018.11.28 16:33:45 resolir 192.168.11.18 http://detectportal.firefox.com/success.txt *TRUSTED* Exception site match.detectportal.firefox.com GET 8 0 - 4 200 - 192.168.11.18 GruppoFacebook - - - - -`
> 
> Strangely, both sites are in a squid whitelist for excluding them from authentication.

I found that this workaround succeeds only if the squid white list is in an acl mentioned *after* another acl which triggers authentication. Which, of course, makes the white list meaningless.

**Comment by philipianpearce** [comment]
2018.11.28 16:11:08 - 192.168.11.18 http://detectportal.firefox.com/success.txt *DENIED* Exception site match.detectportal.firefox.com GET 0 0 - 1 403 - 192.168.11.18 GruppoStandard - - -

Above log message indicates a bug in code.  It is denying an exception.  Now fixed in v5.2 branch.

**Comment by philipianpearce** [comment]
@resoli   I have fixed bug that surfaced while looking at this, but I'm not clear as to why you want to NOT auth detectportal.firefox.com.   The whole point of this firefox call is log the user into the proxy at browser start-up. Is this not better than having a proxy log-in appear apparently at random to the user?

**Comment by resoli** [comment]
@philipianpearce yes, but our current internal policy is to consent access to a static sites whitelist to everybody, even non-authenticated clients. We use ntlm auth, so for most users there is no login prompt in any case. 

Anyway, the main problem was that accesses to http://detectportal.firefox.com/success.txt were repeatedly refused as if auth was failing, which was not the case, given that no auth was required at all by upstream squid proxy (which in fact responded with an HTTP 200).

**Comment by resoli** [comment]
Thanks for the quick fix, will try and report.

**Comment by resoli** [comment]
Ok, recompiled latest git. Now putting a site in preauth exception list works, but the strange behaviour:

> Anyway, the main problem was that accesses to http://detectportal.firefox.com/success.txt were repeatedly refused as if auth was failing, which was not the case, given that no auth was required at all by upstream squid proxy (which in fact responded with an HTTP 200).

Still remains; as a workaroundt i put in authexceptionsitelist  an .Include  for every squid whitelist

**Comment by resoli** [comment]
Another quirk: when a site is in `authexceptionsitelist`, as of default `preauth.story`, e2g fetches content directly:

> if(returnset) setgodirect

If I comment out this line, e2g passes the request to the parent proxy, but 

> forwardedfor = on

setting in `e2guardian.conf`

is not honored, the parent proxy does not see the original src ip.

**Comment by philipianpearce** [comment]
The standard - if(returnset) setgodirect in preauth.story is to avoid having to set up complex auth exceptions in squid. 

I will look at the forwardedfor issue. 

Philip 

----- Original Message -----

**Comment by resoli** [comment]
> The standard - if(returnset) setgodirect in preauth.story is to avoid having to set up complex auth exceptions in squid.

Yes, and it definetely makes sense. 

In our current setup, anyway, direct fetch by e2g seems to have some issues (nginx default pages appearing at first request, and regular content after shift-reload), and we would like to pass requests thru squid in any case.

> I will look at the forwardedfor issue.

Many thanks.

**Comment by resoli** [comment]
> In our current setup, anyway, direct fetch by e2g seems to have some issues (nginx default pages appearing at first request, and regular content after shift-reload), and we would like to pass requests thru squid in any case.

I've created a separated issue for this: #485

**Comment by resoli** [comment]
I've checked, and the `forwardedfor` issue is stil actual even after recent fixes.

**Comment by fredbcode** [comment]
@resoli Hi, did you check recently ?

**Comment by fredbcode** [comment]
Closed for now, if the issue persists then reopen the ticket
