### ISSUE TITLE
Storyboard file caseinsensitive

### ISSUE THREAD

**Issue by dbrody2004** [e2guardian/e2guardian#482]
Due to the caseinsensitive flag in Storyboard.cpp, the following include breaks reading a storyboard file.  Note the include has capitals but trying to read this filename in lower case in linux breaks.

Reading storyboard file /etc/e2guardian/09F96E0FC57F4C7A861278273547B849/examplef1.story
Readline .Include</etc/e2guardian/09F96E0FC57F4C7A861278273547B849/common.story>
Reading storyboard file /etc/e2guardian/09f96e0fc57f4c7a861278273547b849/common.story

**Comment by philipianpearce** [comment]
OK will fix.

**Comment by philipianpearce** [comment]
As you testing with the latest v5.2?

Bug was previously reported #446 and fixed before v5.2 was released.

**Comment by dbrody2004** [comment]
Thanks, that was the it.
