### ISSUE TITLE
How to use/compile this application?

### ISSUE THREAD

**Issue by dev0zero** [e2guardian/e2guardian#483]
Hi, can confirm can i use it on macOs?

Is there binary files for MacOS. any depending applications? 

How to compile ?

any manual???

**Comment by philipianpearce** [comment]
V5 should compile on MacOS as it is based on bsd unix. I'm not aware of any pre-built MacOS packages for v5. 

Details of how to compile are in the INSTALL file as is normal with open source packages. Read README and INSTALL and the files they reference. 

Please note that the github issues is for bug and new feature notifications only. If you need further help please join and post to the e2guardian Google group. 

See https://github.com/e2guardian/e2guardian/issues/21. 

Regards 
Philip 

----- Original Message -----
