### ISSUE TITLE
[Feature request] logphraselist 

### ISSUE THREAD

**Issue by ghost** [e2guardian/e2guardian#484]
At the moment we've got a lovely set of phraselists - bannedphraselist, weightedphraselist and exceptionphraselist.

How hard would it be to add in a fourth "logphraselist" that simply logged an occurrence of a word on this list? This would allow many of us to set up basic monitoring on a keyword level.  Based on my very limited understanding, the new storyboarding logic might make something like this easier?

**Comment by philipianpearce** [comment]
Unfortunately, the phraselists are still the same logic as before and internally the three lists are combined into one list, so to add a new phrase list with a different function requires a fair bit of code changing. This is unlike the site/url/regexp lists where a new list and the logic to be applied can now be added without any code change. At the moment we do not have any plans to extend storyboarding to content checking. It may be possible to add optional phaselists via the content scanning plugin feature which may be able in the future to do this. 

You may be able to achieve the effect you need by making the naughtynesslimit very low and using stealth mode (reportinglevel = -1)??? But that would mean that everything is allowed. 

Regards 
Philip 

----- Original Message -----

**Comment by ghost** [comment]
Hi Philip,

OK this makes sense. Thanks for the insight & advice. I'll mark this as closed for now but feel free to contact me if something like this ever does make it into the development plan and needs testing.
