### ISSUE TITLE
v5.2 git - Incorrect HTTP content returned for some sites

### ISSUE THREAD

**Issue by resoli** [e2guardian/e2guardian#485]
We are experiencing strange issues when contacting some http sites the first time in a browser session.

We took  `tcpdump` traces for:

- http://www.ladige.it
- http://www.trentorunningfestival.it

both sites are in `authexceptionsitelist`

[ladige-119.dump.gz](https://github.com/e2guardian/e2guardian/files/2656794/ladige-119.dump.gz)
[running-119.dump.gz](https://github.com/e2guardian/e2guardian/files/2656793/running-119.dump.gz)

In both cases, e2g returns as content:

```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Note that  **no concurrent request** is made to fetch content upstream (we checked multiple times).

Correct content is returned (with ffox browser) after shift-reload.

**Comment by resoli** [comment]
> Note that **no concurrent request** is made to fetch content upstream (we checked multiple times).
> 
> Correct content is returned (with ffox browser) after shift-reload.

Un update: I discovered that the content **is** fetched upstream, but from an (apparently) unrelated  ip:

```
13:13:03.816140 IP 192.168.10.202.56058 > 54.194.23.175.80: Flags [P.], seq 16:416, ack 1, win 849, options [nop,nop,TS val 17419488 ecr 4853754], length 400: HTTP
	0x0000:  4500 01c4 5e94 4000 4006 c0bc c0a8 0aca  E...^.@.@.......
	0x0010:  36c2 17af dafa 0050 7972 0df1 648a 50ed  6......Pyr..d.P.
	0x0020:  8018 0351 1b9a 0000 0101 080a 0109 cce0  ...Q............
	0x0030:  004a 0ffa 486f 7374 3a20 7777 772e 6c61  .J..Host:.www.la
	0x0040:  6469 6765 2e69 740d 0a55 7365 722d 4167  dige.it..User-Ag
	0x0050:  656e 743a 204d 6f7a 696c 6c61 2f35 2e30  ent:.Mozilla/5.0
	0x0060:  2028 5769 6e64 6f77 7320 4e54 2036 2e31  .(Windows.NT.6.1
	0x0070:  3b20 574f 5736 343b 2072 763a 3532 2e30  ;.WOW64;.rv:52.0
	0x0080:  2920 4765 636b 6f2f 3230 3130 3031 3031  ).Gecko/20100101
	0x0090:  2046 6972 6566 6f78 2f35 322e 300d 0a41  .Firefox/52.0..A
```
The correct resolution for `http://www.ladige.it` is `195.78.202.60`:
```
# host www.ladige.it
www.ladige.it is an alias for www3.ladige.it.
www3.ladige.it has address 195.78.202.60
```
It seems that e2g is wrongly resolving that address; I checked multiple times, but when the problem arises no dns query is made on the net, and I tested various resolution mechanisms: 

- systemd-resolvd (default)
- dnsmasq
- plain resolv.conf

even putting the resolution of `www.ladige.it` in `/etc/hosts` does not change that GET to `54.194.23.175` ...

**Comment by resoli** [comment]
I've found that `54.194.23.175` is one of the IPs of `trento.comunitatrentina.it` whose alias `www.comune.trento.it` was accessed immediately before `www.ladige.it`  in the same browser session.

**Comment by philipianpearce** [comment]
Thanks for reporting this in detail.    I think this is may be related to fix for #481.
I have added some checks which should fix this.   Please can you test with lastest v5.2?

Regards
Philip

**Comment by resoli** [comment]
Will try and report.

Thanks,
rob

**Comment by resoli** [comment]
This issue seems fixed now. Closing.
