### ISSUE TITLE
v5.2.2: Set bypass cookie with 302 bypass redirection

### ISSUE THREAD

**Issue by sonertari** [e2guardian/e2guardian#486]
Since checkme.isexception is set after isBypassURL() succeeds in checkByPass(), the code never executes the 302 bypass redirection in handleConnection(). Note that the denied page is displayed, and the URL bypass hash is correctly processed if the user clicks the bypass link, but since the bypass cookie is not set, the page does not load properly, for example the favicon request for the page is still denied, along with any other content requests with the same url domain.

Firstly, am I missing something? If not, I have applied the following patches to fix this issue:

	diff --git a/src/NaughtyFilter.hpp b/src/NaughtyFilter.hpp
	index d1a51dc..5f102e0 100644
	--- a/src/NaughtyFilter.hpp
	+++ b/src/NaughtyFilter.hpp
	@@ -70,6 +70,7 @@
		 bool wasclean = false;
		 bool cachehit = false;
		 bool isbypass = false;
	+    bool setbypasscookie = false;
		 bool iscookiebypass = false;
		 bool isvirusbypass = false;
		 bool isscanbypass = false;

	diff --git a/src/ConnectionHandler.cpp b/src/ConnectionHandler.cpp
	index 57066ba..1809c82 100644
	--- a/src/ConnectionHandler.cpp
	+++ b/src/ConnectionHandler.cpp
	@@ -937,10 +958,12 @@
	 
		         if (checkme.isdirect) header.setDirect();
	 
	-            if (checkme.isbypass && !(checkme.isexception || checkme.iscookiebypass || checkme.isvirusbypass)) {
	+            if (checkme.isbypass && (checkme.setbypasscookie || !(checkme.isexception || checkme.iscookiebypass || checkme.isvirusbypass))) {
	 #ifdef DGDEBUG
		             std::cout << thread_id << "Setting GBYPASS cookie; bypasstimestamp = " << checkme.bypasstimestamp << __func__ << std::endl;
	 #endif
	+                checkme.setbypasscookie = false;
	+
		             String ud(checkme.urldomain);
		             if (ud.startsWith("www.")) {
		                 ud = ud.after("www.");
	@@ -1730,7 +1753,7 @@
		                         eheader = "HTTP/1.1 200 \r\n";
		                     }
		                     if (headersent < 2) {
	-                            eheader += "Content-type: text/html\n\n";
	+                            eheader += "Content-type: text/html\r\n\r\n";
		                     }
		                     // if the header has been sent then likely displaying the
		                     // template will break the download, however as this is
	@@ -2805,6 +2828,7 @@
		         header.chopBypass(checkme.logurl, checkme.isvirusbypass);
		         if (checkme.bypasstimestamp > 1) { // not expired
		             checkme.isbypass = true;
	+                checkme.setbypasscookie = true;
		             checkme.isexception = true;
		             // checkme: need a TR string for virus bypass
		             checkme.exceptionreason = o.language_list.getTranslation(606);

What I basically do is to introduce a new setbypasscookie flag to force the 302 redirection, but only if isBypassURL() succeeds and the hash did not time out. I could unset the isexception flag instead as a quick fix, but I don't know if it would affect other parts of the code. Plus, I have tried to keep the original logic, amap, as in my modifications to the if condition above.

I am not sure if this is the right way of fixing this issue, so I am not submitting a pull request (also, there is another checkByPass() call for ICAP anyway). But this fix is working for me so far. Any comments welcome.

**Comment by fredbcode** [comment]
Hi Thank you for the report I'm using Bypass myself without know issue, can you post a step by step way to reproduce ?
Bypass is set form a specific url no more or less, maybe this is related with your issue ?

**Comment by sonertari** [comment]
Hi @fredbcode, to reproduce the issue, I just try to go to a denied web site while following the access logs. For example, I:

1. Try to view slashdot.org on a web browser (make sure slashdot.org is among blacklisted urls, such as the News Domains list)
2. Get the denied page with a bypass link, and see the denied request for slashdot.org among the logs
3. Click the bypass link on the denied page, and see that slashdot.org is now TRUSTED, so the page starts loading
4. But continue following the logs to see that the favicon request for slashdot is denied (along with other images on the page)

The full slashdot page may or may not load in your case, depending on whether you have previously visited the web site or not (I guess the web browser may fetch those missing images from its own cache).

Aside from those steps above, when I look at the code, I see that the 302 redirection is not supposed to work, as I explained in my first post (and I have inserted multiple debug lines to make sure that the 302 code is not executed). But after I apply the patches I have given there, everything seems fine, e.g. the favicon and other image requests are TRUSTED too (and my debug logs show me that the 302 redirection code sets the cookie now, and sets it only once).

Btw, I have tried to do the same with v4.1.5, it works fine without a similar patch, e.g. the favicon request is never denied after bypass (because v4.1.5 sets the cookie correctly).

So, do you see that the favicon request is denied, after you click the bypass link on the denied page?

**Comment by philipianpearce** [comment]
@sonertari - Many thanks for reporting this - yes there was a bug, but only in the normal code path (i.e. not in ICAP mode where the code is ok).    It just needed the !checkme.isexception check removing to fix, so no need for the extra checkme flag.  Fixed in latest v5.2 branch.

**Comment by sonertari** [comment]
@philipianpearce, great, thank you too.
