### ISSUE TITLE
ERR_RESPONSE_HEADERS_TRUNCATED on google chrome.

### ISSUE THREAD

**Issue by nunompad** [e2guardian/e2guardian#49]
Hi there, 

IF I enable a ssldeniedrewrite = on the I get an error from google chrome: 

Error code: ERR_RESPONSE_HEADERS_TRUNCATED. 

Is this normal? I tried with chrome 39 and 41. 

Can you check this link: 

https://groups.google.com/forum/m/#!topic/jasig-cas-user/TWaFzCEVTyk

**Comment by fredbcode** [comment]
https://groups.google.com/forum/#!topic/e2guardian/7VStsDSNvnY
Please tell me if it works

**Comment by nunompad** [comment]
it is a https website

**Comment by fredbcode** [comment]
About local website are you using an exclusion in your browser - about local websites should not use the proxy -

Tested this morning with Chrome 39 and IE 11 works fine (except SSL warning message of course)

sslaccessdeniedaddress = 'https://yahoo.fr'
ssldeniedrewrite = on

**Comment by fredbcode** [comment]
| About local website are you using an exclusion in your browser - about local websites should not use the proxy -

In this case you should see the local request in your proxy log (certainly with a 503 code)

**Comment by nunompad** [comment]
I there you can close the issue this was like you say a problem that the browser were redirected to  a site that could not be opened.

**Comment by fredbcode** [comment]
Ok thanks
