### ISSUE TITLE
RFE: Support HTTPS connections to proxy

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#491]
It appears that recent versions of CURL and other browsers can accept an "HTTPS" proxy where the connection to the proxy is encrypted via SSL.  As near as I can tell, e2guardian does not appear to support this at the moment.

**Comment by opoplawski** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file

**Comment by philipianpearce** [comment]
No this is not currently supported directly.  However, if required, e2g can be enabled to do this by using stunnel - see https://www.chromium.org/developers/design-documents/secure-web-proxy.    

A native implementation may be required when we start looking at http2 support in v6.

**Comment by opoplawski** [comment]
Thanks for the stunnel suggestion - I've got that working for the moment.  But yes, a native implementation would still be preferable in the long run.

**Comment by philipianpearce** [comment]
Secure proxy has now been added to v5.5.dev,

**Comment by philipianpearce** [comment]
Feature released in v5.5 Stable
