### ISSUE TITLE
Failure using ICAP MODE and SQUID.

### ISSUE THREAD

**Issue by matheuscucoloto** [e2guardian/e2guardian#494]
Hi, everybody.

My config is FreeBSD 11.2 + Squid 4.4 + E2guardian 5.2.2 with last version of github.

Squid use NTLM and work with E2guardia via ICAP.

Sometimes or everytime (traffic depend) squid write in log this information:

kid1 | optional ICAP service is suspended: icap: //127.0.0.1: 1344 / response [down, susp, fail11]

I checked all sysctl of freebsd that would be influencing in socket, but i did not get success.

It is possible to check in https://pastebin.com/ZDR8cTgx that is debug e2guardian log with debug level ICAP that has some info about this error:

hw743: 1547560899 ICAP debug : hw743: ICAP/1.0 400 Bad request : ICAP/1.0 400 Bad request
   
hw727: 1547560899 ICAP debug : hw727:  ICAP Error: ICAP/1.0 418 Bad composition - X-ICAP-E2G header not present

In squid.conf i have it:

icap_enable on
icap_service service_req reqmod_precache bypass=1 icap://127.0.0.1:1344/request
icap_service service_resp respmod_precache bypass=1 icap://127.0.0.1:1344/response
icap_service_revival_delay 30
adaptation_access service_req allow all
adaptation_access service_resp allow all
icap_send_client_ip on
icap_send_client_username on
icap_persistent_connections on
adaptation_masterx_shared_names X-ICAP-E2G
icap_log /var/log/squid/icap2.log

I dont use sslmitm!

**Comment by fredbcode** [comment]
Can you make a test with a more recent version , please ?

**Comment by philipianpearce** [comment]
Stale
