### ISSUE TITLE
[5.2.2] - Auto Switch to MITM to deliver block page 

### ISSUE THREAD

**Issue by forid786** [e2guardian/e2guardian#495]
Hi,

The group option "Auto Switch to MITM to deliver block page" doesn't seem to be working. From my understanding, if a end device has the CA cert installed, however you're not inspecting everything. If that device attempts to visit a blocked HTTPS site, then E2 Guardian should MITM the connection and deliver the block page through HTTPS. 

In some of my networks this is desirable, where you don't want to waste resources by MITM everything but want to deliver a user friendly page, when someone attempts to go on a blocked site.

```
e2guardian -v
e2guardian 5.2.2

Built with:  '--localstatedir=/var' '--with-logdir=/var/log' '--with-piddir=/var/run' '--with-zlib=/usr' '--enable-fancydm' '--disable-clamd' '--disable-commandline' '--enable-dnsauth' '--disable-email' '--enable-icap' '--disable-kavd' '--enable-ntlm' '--enable-sslmitm' '--enable-trickledm' '--prefix=/usr/local' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd11.2' 'build_alias=amd64-portbld-freebsd11.2' 'CXX=c++' 'CXXFLAGS=-O2 -pipe  -I/usr/local/include -D__SSLMITM -D__SSLCERT -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing   -DLIBICONV_PLUG -std=c++11 ' 'LDFLAGS= -lssl -lcrypto -Wl,-rpath,/usr/local/lib -fstack-protector ' 'LIBS=' 'CPPFLAGS=-I/usr/local/include -DLIBICONV_PLUG' 'CC=cc' 'CFLAGS=-O2 -pipe  -I/usr/local/include -D__SSLMITM -D__SSLCERT -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing ' 'CPP=cpp' 'PKG_CONFIG=pkgconf'
```

Platform: pfSense 2.4.4-p2 - Based on FreeBSD 11.2 

Regards,
Forid

**Comment by fredbcode** [comment]
"Auto Switch to MITM to deliver block page" what this ?

**Comment by forid786** [comment]
It's a group setting @fredbcode 

Screenshot in the pfSense GUI: https://i.imgur.com/5maURQz.png

**Comment by fredbcode** [comment]
Seems not related to e2guardian (not directly) but with the pfsense packaging 
There is no gui and no specific group setting by default 
Please contact the pfsense community or our google group, github is only used for bug report

**Comment by fredbcode** [comment]
I guess you are speaking about this configuration: 
https://github.com/marcelloc/Unofficial-pfSense-packages/tree/master/pkg-e2guardian5

**Comment by forid786** [comment]
Yes, I am referring to @marcelloc 's package. I assumed that "Auto Switch to MITM" was a E2 Guardian feature. I'll try reporting the issue directly to @marcelloc 

It seems like a pretty cool feature to have in certain situations.
