### ISSUE TITLE
E2guardian GUI

### ISSUE THREAD

**Issue by sghazagh** [e2guardian/e2guardian#496]
Not sure if it's right place to ask, but couldn't find answer anywhere in the web.

Is there any GUI for E2guardian?

If yes how can we install it?
Is it webbase , mean can we run it through web address port, or it is a desktop based, mean need desktop interface like XFCE, LXDE ,... to be able to use it?!

Any help will be appreciated....

**Comment by Kenny690** [comment]
There was a webmin module for Dansguardian, but it's not working anymore with e2guardian. I thought about writing a new one but I'm experienceless and timeless. :(

**Comment by sghazagh** [comment]
What a bout this one, does it still apply to update it and get it working with e2guardian?

[See HERE](http://mindwatering.com/SupportRef.nsf/webpg/AC0573670600ADC6852580A0007914C6)

**Comment by Kenny690** [comment]
I think it could be updatable, but for me it's easier to write a new one than to rewrite someone's sources. Maybe somebody who has a lot of free time and want to help project will help us with that. But I'm not struggling with "nano" and "e2guardian -r", so I'm not in a hurry. :D

**Comment by fredbcode** [comment]
Please ask question to the google group, github purpose is only about bug report
