### ISSUE TITLE
No messageno for bannedheader / exceptionheader

### ISSUE THREAD

**Issue by moosty-moo** [e2guardian/e2guardian#503]
Hi,
I'm using the current v5develop.
It seems that there is no messageno for bannedheader or exceptionheader
So, you just get "*TRUSTED* TRANSLATION KEY 0 MISSING"

**Comment by fredbcode** [comment]
Can you try now with the latest default configuration file ?

**Comment by moosty-moo** [comment]
Hi Fred,

Yes, that's working fine now. 
Many Thanks.
