### ISSUE TITLE
User-Agent banned/exceptionuseragent not working

### ISSUE THREAD

**Issue by moosty-moo** [e2guardian/e2guardian#504]
Hi,

I'm using the current v5develop tree.
The banned/exceptionuseragent lists don't seem to work.
Have added  "zilla" and many combinations.
No regex patterns seem to match, even just "dot star"

The useragent string reported in the logs is
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

However, bannedheader and exceptionheader, do work with "User-Agent: .*zilla"

**Comment by fredbcode** [comment]
Are you sure about your configuration ? There is no difference between 
exceptionuseragent and exceptionheader

**Comment by fredbcode** [comment]
```
grep -r headerin *
configs/common.story:if(useragentin, exceptionuseragent) return setexception
configs/common.story:if(useragentin, exceptionuseragent) return setexception
configs/e2guardianf1.conf.in:regexpboollist = 'name=exceptionuseragent,messageno=610,path=@DGCONFDIR@/lists/exceptionregexpuseragentlist'

grep -r exceptionheader *
configs/common.story:if(headerin, exceptionheader) return setexception
configs/common.story:if(headerin, exceptionheader) return setexception
configs/e2guardianf1.conf.in:regexpboollist = 'name=exceptionheader,messageno=524,path=@DGCONFDIR@/lists/exceptionregexpheaderlist'
```
The path is not the same but the function still "regexpboollist"

**Comment by moosty-moo** [comment]
Hi,
The configs look ok, I think:

fgrep -r exceptionuseragent *
common.story:if(useragentin, exceptionuseragent) return setexception
common.story:if(useragentin, exceptionuseragent) return setexception
e2guardianf3.conf:regexpboollist = 'name=exceptionuseragent,messageno=610,path=/var/local/e2guardian/exceptionregexpuseragentlistf3'

fgrep -r exceptionheader *
common.story:if(headerin, exceptionheader) return setexception
common.story:if(headerin, exceptionheader) return setexception
e2guardianf3.conf:regexpboollist = 'name=exceptionheader,messageno=610,path=/var/local/e2guardian/exceptionregexpheaderlistf3'

**Comment by fredbcode** [comment]
Do you have exactly the same content in both files?

Le 22 février 2019 12:44:30 GMT+01:00, moosty-moo <notifications@github.com> a écrit :
>Hi,
>The configs look ok, I think:
>
>fgrep -r exceptionuseragent *
>common.story:if(useragentin, exceptionuseragent) return setexception
>common.story:if(useragentin, exceptionuseragent) return setexception
>e2guardianf3.conf:regexpboollist =
>'name=exceptionuseragent,messageno=610,path=/var/local/e2guardian/exceptionregexpuseragentlistf3'
>
>fgrep -r exceptionheader *
>common.story:if(headerin, exceptionheader) return setexception
>common.story:if(headerin, exceptionheader) return setexception
>e2guardianf3.conf:regexpboollist =
>'name=exceptionheader,messageno=610,path=/var/local/e2guardian/exceptionregexpheaderlistf3'
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/504#issuecomment-466369963

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by moosty-moo** [comment]
Hi,

EXCEPTION USERAGENT config:
--------------------------------
/var/local/e2guardian/exceptionregexpuseragentlistf3  ( has just .*zilla )
( I also tried with the same regex as for the exceptionheader below)

e2guardianf3.conf:regexpboollist = 'name=exceptionuseragent,messageno=610,path=/var/local/e2guardian/exceptionregexpuseragentlistf3'

1550838200.128  devel   192.168.0.71    192.168.0.71    192.168.0.71    https://www.gnu.org/software/libc/manual/html_node/Linux.html   GET     200     7035    -       Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0   -       214     -       0       *SCANNED* -     0       -       Desktop 3

EXCEPTION HEADER config
---------------------------
/var/local/e2guardian/exceptionregexpheaderlistf3 ( has just User-Agent: .*zilla )

e2guardianf3.conf:regexpboollist = 'name=exceptionheader,messageno=524,path=/var/local/e2guardian/exceptionregexpheaderlistf3'

1550837747.719  devel   192.168.0.71    192.168.0.71    192.168.0.71    https://github.com:443  CONNECT 0       68564   -       Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0   -       2708    -       524     *TRUSTED* Allowed Regular Expression HTTP header: User-Agent: .*zilla       0       -       Desktop 3

**Comment by fredbcode** [comment]
Can you make a test with a recent version, please ?

**Comment by moosty-moo** [comment]
Hi,
I just compiled the current 5.3.dev branch.
I tried bannedregexpuseragentlist  and exceptionregexpuseragentlist and they are now both working.
That's brilliant Fred.
Many thanks.

**Comment by moosty-moo** [comment]
I'll close this now.
