### ISSUE TITLE
Statshumanreadable only works for dstats.log

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#506]
E2guardian 5.3.1 e2guardian.conf file. There is a setting Statshumanreadable  = off.

Changing this to on changes the time display in dstats.log. However it has no effect on access.log.

I am looking into whether I want to use Linux time (to ensure that reporting works properly based on daylight saving) or whether I want to use humanreadable. So I may not end up using this setting. But I thought that I would report that it does not work for access.log

Do you recommend using Linux time format?

**Comment by philipianpearce** [comment]
statshumanreadable only affects the dstats.log format.

If you want human readable date/time in log file you can use a logfileformat that supports this.  (e.g. 1, 2 or 4.

I would recommend using Linux time format. It is much easier for reporting programs to parse, makes combining logs from multiple systems in an array easy (just numeric sort on first field).

A script, such as the attached can be used for human reading (also works with gzip logs).
[show_log.pdf](https://github.com/e2guardian/e2guardian/files/2927553/show_log.pdf)

**Comment by Dalacor** [comment]
Oh I see. Then I would just recommend that the e2guardian.conf file be updated to state that the human readable is only for dstats.log as I assumed it was for both logs.

I agree, I think that using Linux time is better so I will be sticking to using Linux Time. Thanks
