### ISSUE TITLE
greysitelist and greysslsitelist not working

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#507]
Don't know if this is a bug or I am doing something really stupid.

If I put say google.co.uk and google.com in exceptionsitelist the website is unblocked. If I put these domains in either/both greysitelist and greysslsitelist the website remains blocked as a result of being blocked in one of the banned site blacklist categories. I have tried non https websites as well with same result.

I cannot get e2guardian to greylist a domain so that it whitelists the domain but still has content scanning. It would seem that the greylists don't work.

**Comment by Dalacor** [comment]
Update:

greysitelist only works in mitm mode. greysslsitelist does not work in either mode although I realise greysslsitelist is not meant to work in mitm mode! I will be implementing mitm long term anyway and I suspect that most people will be using mitm, so probably not a major issue.

But I would classify this as a bug as grey sites does not  whitelisting does not work in non mitm mode.

**Comment by philipianpearce** [comment]
greysitelist works with http sites and will also work with https sites which have been mitm.    

Setting grey flag means content-check the request.    This is the reason greysitelist is not implemented with https sites in non-mitm mode as it is not possible to content-check them but only to deny or allow them.  I.e.  grey lists should not be used to white-list.  (this used to happen in dg and some very early e2g versions, but was removed as we regarded it as a bug).

If you want to override a banned https site in non-mitm mode, then you need to put it in an exceptionsitelist, explicitly allowing the site.

**Comment by Dalacor** [comment]
I am confused: You say that you should not use grey lists to white-list. I thought the whole point of grey lists was to whitelist a website whilst still enabling content checking? Have I misunderstood this? Putting it in exceptionsitelist turns of content checking as well.

greysitelist does not work for http websites in non mitm mode! I tested this with a couple of websites.

I understand that you cannot content check https sites in non-mitm mode, which is why I checked plain http websites as well.

As I am going to be using MITM permanently I am not worried about the issue. Buf if you are saying that greysitelist should work for http websites in non MITM, it did not work for me in 5.3.1. But I can double check that.

**Comment by philipianpearce** [comment]
The point of grey lists is to force content-check on sites that may
otherwise be blocked in blocklists. My understanding of white-list
 is to trust the site/url, to make it an exception and not to
 content-check. In a storyboard setting the grey flag enables
 content-checking.

 https sites with no MITM can not be content-checked and so it is
 impossible to make them 'grey' - either they are allowed (TRUSTED)
or not. For these sites the only effect in storyboard of setting the
 'grey' flag is would be to unset any block or exception flag
 previously set allowing the action taken to fall through to the
default setting for unlisted SSL sites.

> greysitelist does not work for http websites in non mitm mode! I
> tested this with a couple of websites

http sites should be handled the same whether MITM is on or off. But
 I will test this and get back to you.

**Comment by philipianpearce** [comment]
I have tested greysitelist with the latest v5develop and can confirm that is works as it should using the standard storyboard.

For example, if I put pip55test.com in bannedsitelist and www.pip55test.com in greysitelist, pip55test.com is blocked and www.pip55test.com is allowed. 

I will also check with 5.3 when I am able.

**Comment by Dalacor** [comment]
Not had time to test this yet. But will do so when I have time.
