### ISSUE TITLE
Slow speed on specific websites using explicit proxy

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#510]
Websites that use CDN or pull a lot of information from another website seem to load very slowly in E2guardian when browser is set to explicit proxy. In transparent mode the websites load fast!

I have ruled out blacklists, dns and browser issues. I am currently using E2guardian 5.3.1 in default config - no certificates or MITM etc. This problem is also present in E2g 3.x so not a new issue with latest version.

These are two websites that I can reliably see the difference in explicit and transparent mode but basically any website that uses CDN seems to be a bit slower than without e2guardian.

https://meta.discourse.org/
manager.io

They are using discourse and cloudfront.net - most times they load (slowly), but occasionally I will get a blank page especially on manager.io.

**Comment by Dalacor** [comment]
Even websites like github seem to take longer the first time loading using explicit proxy than without e2guardian or using transparent proxy. It seems to hang for a few seconds on loading github assets.

Makes no difference in mitm mode or not.

Most websites are fast, just specific websites where I can reproduce the slow speeds.

**Comment by Anthony-76** [comment]
Hi,

What dns servers do you use?

**Comment by Dalacor** [comment]
I use my router's Dns which then uses my ISP's DNS. However, I cannot see how this is a dns issue as the same three websites work fine when not using E2guardian or when using Transparent E2guardian. I only see a difference when using explicit proxy - using the same dns configuration!

Thanks

**Comment by Anthony-76** [comment]
It seems that your problem is like the issue #508

**Comment by Dalacor** [comment]
No his issue is with NAT - transparent proxying. Mine's the other way around. In transparent mode, E2guardian is really fast. Also my problem is with very specific websites, not all websites in general. My understanding is the difference between transparent and explicit is there is no content filtering in transparent and I think its the contenting filtering logic that may be the issue here. I can reproduce the same issue in E2g ver 3.x so its not a new problem alas.

**Comment by Anthony-76** [comment]
Ok, and this problem appears with all browser (Firefox, Edge, Chrome, Safari) or just one of them?

**Comment by Dalacor** [comment]
I tested Firefox (my usual browser) and IE. Same result. Also tested different computers and different networks.

**Comment by KDGundermann** [comment]
When using the developer tools in Firefox you can go into network analysis. Could you share us the data of the first request with/without the problem.

**Comment by Dalacor** [comment]
I am about to roll out 5.3.4 and MITM very soon. I will check and see if this is still an issue. I have a feeling that the lack of MITM may be more to do with it.

**Comment by philipianpearce** [comment]
Stale
