### ISSUE TITLE
Valve steam friends network connecting.... ssl_mitm

### ISSUE THREAD

**Issue by livello** [e2guardian/e2guardian#511]
I set up mitm_ssl. Valve Steam does not work, gives wrong ssl cert error.
1) is there a way to add root cert to valve steam?
2) I added valve's domains and valve's ips to /etc/e2guardian/lists/exceptionsiteiplist and
/etc/e2guardian/lists/exceptionsitelist
[site_ip_lists.zip](https://github.com/e2guardian/e2guardian/files/2921818/site_ip_lists.zip)
Steam works but friends network trying to connect.
![default](https://user-images.githubusercontent.com/15374538/53678295-39abca00-3cce-11e9-9273-5efe615d6112.png)
Is there a way to make valve steam work by adding right exceptions?

3) The only way to make valve steam work with e2guardian is to use execution group like this:
addgroup steam
in /etc/before/rules
-A OUTPUT -p tcp -m tcp --dport 80 -m owner --gid-owner steam -j ACCEPT
-A OUTPUT -p tcp -m tcp --dport 443 -m owner --gid-owner steam -j ACCEPT
and run steam with
sudo -g steam steam
I made a lot of efforts with setgid bit, but it seems steam has too complicated launch script for me and I had no luck with something like this:
chown :steam ~/.steam -R
chmod g+s ~/.steam -R

I made a script that counts and limits time my cousin playing and using computer. So if I give him sudoer ability he will soon find the way to pass around that gaming control service.

**Comment by livello** [comment]
I found a workaround. I use iptables-save iptables-restore
When steam is running, e2guardian is bypassing with iptables-restore and when steam is not running e2guardian works as usual.

**Comment by Anthony-76** [comment]
Did you tried to put domains in nocheckcertsitelist file?

**Comment by philipianpearce** [comment]
Closed - Please see #21
