### ISSUE TITLE
Typos in files in E2g 5.3.1

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#512]
**In sslsiteregexplist**

#"https://www\.google\.[a-zA-Z0-9_.]*$)"->"https://forcesafesearch.google.com"
should be
#"(^https://www\.google\.[a-zA-Z0-9_.]*$)"->"https://forcesafesearch.google.com"

It is missing the (^ at the beginning. On an older E2guardian setup I actually have the following syntax

"(^https://www\.google\..*)"->"https://forcesafesearch.google.com."
the difference between ..* instead of .{a-zA-Z0-9_.}*$ - not sure which way is better? What do you recommend.

**In portgroups.conf file in /lists/authplugins**

#8080 = filter0
#8081 = filter1

should be

#8080 = filter1 (not filter0 as e2guardian starts with an error)
#8081 = filter2

Thank you

**Comment by Dalacor** [comment]
Have you fixed the typo in the sslsiteregexplist file. I see that you have updated the portsgroup file thank you.

**Comment by fredbcode** [comment]
Hi, what do you mean about sslsiteregexplist?

**Comment by Dalacor** [comment]
See my very first post. There is a typo in the sslsiteregexplist file as well. It is missing the (^ at the beginning for forcesafesearch.

**Comment by fredbcode** [comment]
Sorry I missed that, I will fix

**Comment by Dalacor** [comment]
ok thank you

**Comment by fredbcode** [comment]
Fixed

**Comment by Dalacor** [comment]
see my comment on the typo fix as you have put in the " twice.

**Comment by fredbcode** [comment]
Yes right, fixed
