### ISSUE TITLE
Missing dependency in 5.3.1 debian

### ISSUE THREAD

**Issue by gbouthenot** [e2guardian/e2guardian#513]
I am building a container using docker with this Dockerfile:

```
FROM debian:stretch

COPY e2debian_V5.3.1_20190221.deb /root/e2guardian.deb
RUN dpkg -i /root/e2guardian.deb
RUN apt-get update && apt-get install -f -y --no-install-recommends

CMD ["/usr/sbin/e2guardian", "-N"]
EXPOSE 8080  
```
But when starting a new container, I have this issue:
```
e2guardian: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Simple solution:
```
apt-get install libssl1.1
```
and now it starts normally.

I think e2guardian should depend on libssl1.1 instead of libssl1.0.2

Thank you !

**Comment by fredbcode** [comment]
Yes already fixed :) https://github.com/fredbcode/scripts/commit/a47861586a008229b234ad87eb000e22a8f97182#diff-521049f7aa275a87f2b4dc111c554209
The next package will be ok
