### ISSUE TITLE
https sites does not appear on access.log

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#52]
Seem to be since dansguardian code but logs only shows http traffic. All https are sent do squid but not logged on e2guardian access.log

Using version 3.0.4 

Built with:  '--localstatedir=/var' '--with-logdir=/var/log' '--with-piddir=/var/run' '--enable-fancydm' '--enable-clamd=yes' '--enable-icap' '--enable-ntlm' '--enable-dnsauth' '--with-filedescriptors=8192' '--prefix=/usr/local' '--mandir=/usr/local/man' '--infodir=/usr/local/info/' '--build=amd64-portbld-freebsd10.1' 'build_alias=amd64-portbld-freebsd10.1' 'CXX=c++' 'CXXFLAGS=-O2 -pipe -I/usr/local/include -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing  -DLIBICONV_PLUG' 'LDFLAGS= -fstack-protector' 'LIBS=' 'CPPFLAGS=-I/usr/local/include -DLIBICONV_PLUG' 'CC=cc' 'CFLAGS=-O2 -pipe  -I/usr/local/include -DLIBICONV_PLUG -fstack-protector -fno-strict-aliasing' 'CPP=cpp' 'PKG_CONFIG=pkgconf'

**Comment by fredbcode** [comment]
What do you mean exactly, you are speaking about loglevel = 3 ? Or exception ?

**Comment by marcelloc** [comment]
loglevel = 3 

If I enter an invalid https url like https://www, it logs but normal https access does not shows in logs or only (i guess) when connection is closed

**Comment by fredbcode** [comment]
> loglevel = 3
>
> If I enter an invalid https url like https://www, it logs but normal 
> https access does not shows in logs or only (i guess) when connection 
> is closed
>
> —
>

This should be the case, E2guardian waits the return code from Squid (same as Squid from website)
Each "GET" in CONNECT request will be in log only after the end of connection.

3.0.4 works fine for me

2015.1.25 16:37:42 fred 88.174.120.52 https://www.google.fr:443  CONNECT 73419 0  2 200 -  groupe2   - -



But I should wait a little time

**Comment by fredbcode** [comment]
I can close ?

**Comment by marcelloc** [comment]
sure.

2015-01-29 15:07 GMT-02:00 Fredb <notifications@github.com>:

**Comment by fredbcode** [comment]
Ok thanks

**Comment by shyamkhakhar9** [comment]
Facing the same issue in squid , https sites are displayed in access log after 5 minutes or after closing connection. Can it be possible to get log on every request?

**Comment by fredbcode** [comment]
Obviously there is the same issue with squid (and any other proxy) we can only log the result at the end of the session 

> Can it be possible to get log on every request?

No because e2 can't see the encrypted requests, if you want to logs each GET and POST you must use SSLMITM mode
