### ISSUE TITLE
Which overrides which banned or exception

### ISSUE THREAD

**Issue by prascher** [e2guardian/e2guardian#524]
I was just wondering whether bannedsitelist or exceptionsitelist, I started wondering because I had to unban facebook but would like to time based ban facebook as well.

**Comment by prascher** [comment]
sorry I realized I forgot to say the version I am running which is 4.1.5 on Ubuntu 18.04

**Comment by philipianpearce** [comment]
lists are checked in the following order:-
exception
grey
banned

This issue-tracker is for bugs and enhancement requests only.   For support please join and use the e2guardian community google group. See #21
