### ISSUE TITLE
aarch64 pfsense support

### ISSUE THREAD

**Issue by barucomx** [e2guardian/e2guardian#525]
Is there any plan to provide compiled version for aarch64 (netgate appliances) of e2guardian???

If I can compile it, how I can do it? (and if it works) how do I provide those files to you???

**Comment by sveip** [comment]
@barucomx, did you investigate any further on compiling the sources yourself?

**Comment by barucomx** [comment]
Yes I did, following the marcelloc guidance, and I got it working, the aarch64 files I published here **[https://github.com/barucomx/e2guardian-aarch64](https://github.com/barucomx/e2guardian-aarch64)**  ^_^
