### ISSUE TITLE
v5 - memory leak when complied with openssl v1.1 

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#527]
Memory leaking when complied with openssl v1.1 - only affects MITM

**Comment by Anthony-76** [comment]
I think this fix will correct my memory issue :)

I will try this tomorrow

**Comment by Dalacor** [comment]
@Anthony-76 I am still seeing the memory leak on E2G 5.2.2. I have compiled MITM, however I have not turned MITM on yet as I wanted to run E2g in for a couple of months before putting certificates in. I don't know if that makes a difference.

**Comment by philipianpearce** [comment]
The memory leak fixed in the latest v5.3 branch - only happened when complied with openssl v1.1 and when MITM and mitmcheckcerts = on. So I do not think this is related to your issue. 

----- Original Message -----

**Comment by Dalacor** [comment]
That is basically what I meant. I think there are several memory leaks in the ver 5 branch.

I have some E2G v3.x boxes with an uptime running for over a year and they only use around 1gb. Whereas E2g5.x is already after a week using more memory than this. It starts off around 400mb and every day climbs up.

**Comment by Anthony-76** [comment]
Of my part, I use MITM with E2G.

So, I upgraded the E2guardian with the last branch. My issue (memory leak) is still here.

Currently, I have a script via crontab that check memory usage. If memory usage is very too high, I excecute the follwing command "e2guardian -Q". 
Then, the memory usage is "noral"
