### ISSUE TITLE
Wrong user in DENIED log (identity can be usurped - but only in deny situation -)

### ISSUE THREAD

**Issue by GnunuX** [e2guardian/e2guardian#53]
In this example www.sex.com is a forbidden website. I set this website as homepage in firefox.

Local user is "gnunux" in windows 7 not integrated in any domain. When I start firefox, squid force authentification, firefox send local NTLM token but e2guardian denied access to this site.

The problem is local user in my computer is set as user in log:

Feb  2 16:50:09 internet e2guardian[2885]: "2015.2.2 16:50:09","gnunux","10.3.2.50","http://www.sex.com","*DENIED* Site interdit: sex.com","GET","0","0","","1","403","-","","","","","-","-",""
Feb  2 16:50:10 internet e2guardian[2885]: "2015.2.2 16:50:10","gnunux","10.3.2.50","http://www.sex.com/favicon.ico","*DENIED* Site interdit: sex.com","GET","0","0","","1","403","-","","","","","-","-",""

Second example, homepage is set to an allowed website (perdu.com). When firefox start, i'm logging in squid with domain user "admin".
Just after, I tried to access to sex.com.

Has you can see, one the first acces to sex.com is associate to "admin" user. Others are associated to my local user "gnunux":

Feb  2 16:58:22 internet e2guardian[2885]: "2015.2.2 16:58:22","admin","10.3.2.50","http://www.perdu.com","","GET","204","0","","1","200","text/html","","","","","-","-",""
Feb  2 16:58:37 internet e2guardian[2885]: "2015.2.2 16:58:37","admin","10.3.2.50","http://sex.com","*DENIED* Site interdit: sex.com","GET","0","0","","1","403","-","","","","","-","-",""
Feb  2 16:58:37 internet e2guardian[2885]: "2015.2.2 16:58:37","gnunux","10.3.2.50","http://sex.com/favicon.ico","*DENIED* Site interdit: sex.com","GET","0","0","","1","403","-","","","","","-","-",""
Feb  2 16:58:37 internet e2guardian[2885]: "2015.2.2 16:58:37","gnunux","10.3.2.50","http://sex.com/favicon.ico","*DENIED* Site interdit: sex.com","GET","0","0","","1","403","-","","","","","-","-",""
Feb  2 16:58:42 internet e2guardian[2885]: "2015.2.2 16:58:42","gnunux","10.3.2.50","http://sex.com","*DENIED* Site interdit: sex.com","GET","0","0","","1","403","-","","","","","-","-",""

Here is a PCAP file (rename with png extension) for first example:
https://cloud.githubusercontent.com/assets/150240/6003615/44c2480e-aafd-11e4-8955-62a05ba828bd.png

**Comment by fredbcode** [comment]
From your trace, the first request with user account contain User Name Gnunux from host win7admin1 with Firefox 31
There is nothing unusual here, all the requests show the same identification from browser.
Do you have the same thing in squid's logs ? 

Please can you make a try with Squid directly ?

**Comment by GnunuX** [comment]
Il squid log, i don't have any user (because I'm not authentificated):

Feb  4 16:59:39 internet (squid): 1423065579.045      1 10.3.2.50 TCP_DENIED/407 3896 GET http://www.sex.com/ - NONE/- text/html

Here is PCAP file without e2guardian and with sex.com as homepage: https://cloud.githubusercontent.com/assets/150240/6043866/bc46baac-ac8f-11e4-8de9-34303123cb21.png

**Comment by fredbcode** [comment]
Same thing, the user Gnunux is present in FF header
As I say I'm not a NTLM expert but in this case E2guardian report the right value. 
Take a look lines 20 and 22

Squid returns: 
407 Not authenticate and Proxy-Authenticate: NTLM needed 

FF answers with:
Domain name: WIN7ADMIN1
User name: GNUNUX 

Maybe there is something wrong with FF or your old Squid version ?
E2Guardian just sniff the HTTP response headers and read the values

**Comment by fredbcode** [comment]
Do you have more informations, now ?

**Comment by GnunuX** [comment]
For example, I've E2G in port 3128 and E2G is configured to be connected to Squid which is correctly configured.
Everything works well (user must be authentificated with NTLM protocol, forbidden website, ...).

fakeuser is not an available user and sex.com is a forbidden website.

When a launch this script:
> #!/usr/bin/env python
> import telnetlib
> 
> host = "192.168.10.2"
> port = '3128'
> 
> ntlm1 = """GET http://sex.com/ HTTP/1.1
> User-Agent: Wget/1.13.4 (linux-gnu)
> Accept: */*
> Host: sex.com
> Connection: Close
> Proxy-Connection: keep-alive
> Proxy-Authorization: NTLM TlRMTVNTUAABAAAABrIAAAoACgAoAAAACAAIACAAAABJTlRFUk5FVE1PTkRPTUFJTkU=
> Content-Length: 0
> 
> """
> 
> ntlm2 = """GET http://sex.com/ HTTP/1.1
> User-Agent: Wget/1.13.4 (linux-gnu)
> Accept: */*
> Host: sex.com
> Connection: Close
> Proxy-Connection: keep-alive
> Proxy-Authorization: NTLM TlRMTVNTUAADAAAAGAAYAFoAAAAAAAAAcgAAAAoACgBAAAAACAAIAEoAAAAIAAgAUgAAAAAAAAByAAAAgoJBAE1PTkRPTUFJTkVGQUtFVVNFUklOVEVSTkVUoXtxqkLJqbEJQtgU2NDT4bNQ33NOJM0a
> 
> """
> 
> tn = telnetlib.Telnet(host, port)
> 
> tn.write(ntlm1)
> print tn.read_until('&lt;/body&gt;&lt;/html&gt;')
> tn.write(ntlm2)

Here is e2guardian log:

> May 24 11:00:45 internet e2guardian[390]: "2015.5.24 11:00:45","fakeuser","192.168.10.2","http://sex.com","*DENIED* Site interdit: sex.com","GET","0","0","","1","403","-","","","","","-","-",""

Has you can see, username is set to "fakeuser" which is not a valid user. If a set a valid user but without valid password, we can see the spoofed user in log.

**Comment by fredbcode** [comment]
I do not understand right

**Comment by GnunuX** [comment]
"fakeuser" is suppose to be the authentificated user with NTLM protocol. The problem is that E2G didn't valid password if domain is forbidden. So we can spoof user name in log.

**Comment by fredbcode** [comment]
Ok, wrong user pushed with a domain forbidden = Wrong user spoofed in deny log (and only in deny Log), right ?

**Comment by fredbcode** [comment]
Hum, so I guess you are using only one group (e2guardianf1.conf) ?

**Comment by GnunuX** [comment]
> Ok, wrong user pushed with a domain forbidden = fake user spoofed in deny log (and only in deny Log), right ?

Right.

> Hum, so I guess you are using only one group (e2guardianf1.conf) ?

Here is my configuration (tar.gz rename to png): https://cloud.githubusercontent.com/assets/150240/7801392/300f0c9c-0324-11e5-8195-3c69aa044101.png

In our architecture, e2guardian reuse dansguardian filename.

**Comment by fredbcode** [comment]
I reproduce something similar here, if I put a false user in the identification pop-pup E2guardian log the value but in my case with tag group1 in log . 
Unknown users default is filter group 1, so there is nothing wrong here

 -  The browser try to connect to a website with a user, but the user is unknown, so it's pushed to group1 - 

To avoid this my group1 is a garbage with no authorization at all. 

You should add a value like groupname = ''group1" and deny all for the first group. 
All users with an identification problem, like user with good login/password but not in the groups file, or "fake" users will be blocked by E2 with tag group1  (ou "utlisateur sans groupe" as you wish ...)

However still a problem, when I'm using an existing name (with a wrong password of course) and a denied website E2 log the wrong value with the user's group, rather annoying ...

This behaviour seems old, but it needs a fix, maybe we should take care about 407 from Squid or something similar, I mean if 407 = e2 with no log 

PS Without relation you have no greysslsitelist or bannedsslistelist and with 3.0.4 you can have problem with HTTPS domains filtering

**Comment by fredbcode** [comment]
It's a complex problem, as you can see only Squid knows the truth :)

The first request is always the same, Squid reclaims an account - 407 Proxy Authentication Required -

Squid just after the first GET

**AUTH: basic + digest**
 
HTTP/1.1 407 Proxy Authentication Required
Server: squid/3.4.13
Mime-Version: 1.0
Date: Wed, 24 Jun 2015 14:22:06 GMT
Content-Type: text/html
Content-Length: 2358
X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
Proxy-Authenticate: Digest realm="TEST Digest", nonce="Dr2KVZAndgoMdNcv", qop="auth", stale=false
Proxy-Authenticate: Basic realm="TEST Basic"
X-Cache: MISS from proxytest
Via: 1.1 proxytest (squid/3.4.13)
Connection: close

My browser 

**Good user:**

GET /4/Firefox/38.0.5/20150525141253/WINNT_x86-msvc/fr/release/Windows_NT%206.1/default/default/ HTTP/1.1
Host: snippets.cdn.mozilla.net
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Origin: null
Connection: keep-alive
Proxy-Authorization: Digest username="itsme", realm="TEST", nonce="Dr2KVZAndgoMdNcv", uri="snippets.cdn.mozilla.net:443", response="691721f837b8290173a1490de18df841", qop=auth, nc=00000001, cnonce="a077537b84347bee"

**False user:**

https://ddddd.com/

GET / HTTP/1.1
Host: ddddd.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Connection: keep-alive
Proxy-Authorization: Digest username="not_me", realm="TEST", nonce="mLyKVfiDuQr2Vqx/", uri="ddddd.com:443", response="456918596eae776c2ce9927a014a6c92", qop=auth, nc=00000001, cnonce="505715c6a89368dc"

Doh ! No difference

E2Guardian intercepts the answers from browser to Squid, in this case the wrong user "not_me" exist in my groups file, so E2 log the request with a false user, there is no bug here.

If "not_me" is non-existent it will logged with group1 tag (default group)
Fortunately, the fake user can't pass the identification control     

Honestly like this I don't see any solution, there is always a first answer from browser and we can't control his header. 
Maybe something with a cookie ...
If needed I can add a tag for users without group ? Or an option to block without logging in E2 (just a trace in Squid) ?

**Comment by fredbcode** [comment]
For a strong identification report, ICAP is a solution now

**Comment by fieldsplan** [comment]
In an era where environmental consciousness is paramount, [Prestige Lavender Fields](https://www.prestigelavenderfield.net.in/) stands as a shining example of a residential project committed to green initiatives and sustainability. Nestled in the heart of Bangalore, this innovative development is not only about luxury living but also about embracing a responsible and eco-friendly lifestyle.

**Comment by danialredy** [comment]
The outdoor sports facilities at [Prestige Park Ridge](https://www.prestigeparkridge.net.in/) extend beyond the traditional, with an expansive jogging track that winds through the lush green surroundings. Residents can enjoy their morning or evening runs in a serene environment, embracing both physical activity and the tranquility of nature.
