### ISSUE TITLE
Descriptions in comments for sslsiteregexplist and urlregexplist could be more clear

### ISSUE THREAD

**Issue by justinrdonnelly** [e2guardian/e2guardian#530]
The comments in sslsiteregexplist and urlregexplist are not as clear as they could be.  This leads to some users misunderstanding their purpose and using them incorrectly.  I propose adding the following text.

sslsiteregexplist:
This applies to the site only (not full URL) for HTTPS sites (regardless of SSL MITM configuration).

urlregexplist:
This applies to the full URL for HTTP sites, and if configured for SSL MITM, also HTTPS sites.

**Comment by philipianpearce** [comment]
Thanks for this.    I have made the changes in the v5.3.dev branch, so these will be incorporated into next v5.3 release.
