### ISSUE TITLE
When i am switching from V-5.2.2 to V-5.3.1 #sslaccessdeniedaddress and #ssldeniedrewrite not found. why?

### ISSUE THREAD

**Issue by surjitiit** [e2guardian/e2guardian#535]
**I did not found following configuration in e2guardianf1.conf file. is this a bug or this feature is removes from latest Vs.**

sslaccessdeniedaddress is the address of your web server to which the static page
e2guardian reporting was copied.

With ssldeniedrewrite 'off' it works only with firefox 
With ssldeniedrewrite 'on' there are several limitations, SSL warning, basic page, etc, eg this webserver can't be listed as an
exception in your browser's proxy configuration.
Keep in mind, this is only a trick to avoid blank page, the best way still to use SSLMITM   
 
**sslaccessdeniedaddress = 'http://YOURSERVER.YOURDOMAIN/denyssl.htm'****

Break SSL protocol and redirect to another HTTPS website for denied page (sslaccessdeniedaddress url)

**ssldeniedrewrite = 'on'**

**Comment by fredbcode** [comment]
5.3.2 is the latest not 5.3.1

**Comment by surjitiit** [comment]
this feature is also not available in V-5.3.2. why?

**Comment by fredbcode** [comment]
sslaccessdeniedaddress was an ugly "trick", but it doesn't works now with the latest Firefox version.
So I removed the code, now SSLMITM is the only way to have a page

**Comment by surjitiit** [comment]
> sslaccessdeniedaddress was an ugly "trick", but it doesn't works now with the latest Firefox version.
> So I removed the code, now SSLMITM is the only way to have a page

Ok thanks for your reply...

**Comment by fredbcode** [comment]
The expected behaviour, not with e2 but with all proxies, is a browser error (blank page or internal message error)

with SSLMITM the page can be switched by another
