### ISSUE TITLE
e2guardian: spelling-error-in-manpage usr/share/man/man8/e2guardian.8.gz implimentations implementations

### ISSUE THREAD

**Issue by sunweaver** [e2guardian/e2guardian#543]
I: e2guardian: spelling-error-in-manpage usr/share/man/man8/e2guardian.8.gz implimentations implementations
N: 
N:    Lintian found a spelling error in the manpage. Lintian has a list of
N:    common misspellings that it looks for. It does not have a dictionary
N:    like a spelling checker does.
N:    
N:    If the string containing the spelling error is translated with the help
N:    of gettext (with the help of po4a, for example) or a similar tool,
N:    please fix the error in the translations as well as the English text to
N:    avoid making the translations fuzzy. With gettext, for example, this
N:    means you should also fix the spelling mistake in the corresponding
N:    msgids in the *.po files.
N:    
N:    Severity: minor, Certainty: possible
N:    
N:    Check: manpages, Type: binary

Please search&replace for implimentations / by implementations in the e2guardian man page. Thanks.

**Comment by fredbcode** [comment]
Fixed in 5.4.dev
