### ISSUE TITLE
v5.3.3 freebsd - transparent SSL proxy creates a lot of 127.0.0.1 entries on log

### ISSUE THREAD

**Issue by marcelloc** [e2guardian/e2guardian#545]
Hi, I could get a closer way to force this error related on #394 
If I try to access any site by its IP using HTTPS, I get the forward issue to 127.0.0.1 while in transparent mode with or without inteception
The ip address on the screen is not a pfsense GUI, but the resulting page is my https 127.0.0.1 web host where e2guardian is running

![image](https://user-images.githubusercontent.com/926309/62638806-9b72fe80-b914-11e9-81ce-521073ea9bb1.png)

**Comment by marcelloc** [comment]
This is a screenshot of forwading rules to make sure there is no fwd rule mistakes

 
![image](https://user-images.githubusercontent.com/926309/62639604-3e784800-b916-11e9-861b-d9b9fc492f87.png)

**Comment by philipianpearce** [comment]
Hi,

The problem seems to be that the rdr NATs the packet to 127.0.0.1 so e2g only has 127.0.0.1 as the destination ip.   This is not a problem where the client sends an SNI in the TLS request as e2g will use the SNI as the address to connect to (either host name or ip).  But if SNI is absent then all e2g has is the ip header destination address which has been nated to 127.0.0.1.   Most browsers will send an SNI, but many apps do not.

Can you try using divert-to instead of rdr-to in your ruleset as suggested for squid? According to the ps firewall documentation this should allow e2g to pick up the original destination IP (and port).

I'm not familiar with open/freebsd firewalling so I am just working from what I can find on the web.

**Comment by marcelloc** [comment]
on squid code, Intercept.cc file has these calls

#if PF_TRANSPARENT
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <sys/fcntl.h>
#include <net/if.h>
#include <netinet/in.h>
#if HAVE_NET_PF_PFVAR_H
#include <net/pf/pfvar.h>
#endif /* HAVE_NET_PF_PFVAR_H */
#if HAVE_NET_PFVAR_H
#include <net/pfvar.h>
#endif /* HAVE_NET_PFVAR_H */
#endif /* PF_TRANSPARENT required headers */

These can be useful on e2guardian code? If so, how can I include this.

I've already included same config args that squid package has, but I need some help to find how to include it on e2guardian code.( --with-nat-devpf and --enable-pf-transparent)

**Comment by marcelloc** [comment]
> Hi,
> 
> The problem seems to be that the rdr NATs the packet to 127.0.0.1 so e2g only has 127.0.0.1 as the destination ip. This is not a problem where the client sends an SNI in the TLS request as e2g will use the SNI as the address to connect to (either host name or ip). But if SNI is absent then all e2g has is the ip header destination address which has been nated to 127.0.0.1. Most browsers will send an SNI, but many apps do not.
> 

https fqdn sites are redirected fine to e2guardian but https ip addresses  get this redirect issue.

> Can you try using divert-to instead of rdr-to in your ruleset as suggested for squid? According to the ps firewall documentation this should allow e2g to pick up the original destination IP (and port).
> 
I'll try to find a way to create a rule this way on pfSense, but I'm not sure divert is enabled on it.

**Comment by philipianpearce** [comment]
In ConnectionHandler.cpp. 

The relevant code is at line 3342 (current v5.4.dev) 
{ // get original IP destination & port 

sockaddr_in origaddr; 
socklen_t origaddrlen ( sizeof (sockaddr_in)); 
if ( 
# ifdef SOL_IP // linux 
# define SO_ORIGINAL_DST 80 
getsockopt (peerconn. getFD (), SOL_IP, SO_ORIGINAL_DST, &origaddr, &origaddrlen ) < 0 
# else // BSD 
getsockname (peerconn. getFD (), ( struct sockaddr *)&origaddr, &origaddrlen) < 0 
# endif 
) { 
syslog (LOG_ERR, " %sFailed to get client's original destination IP: %s " , thread_id. c_str (), strerror (errno)); 
return - 1 ; 
} else { 
char res[INET_ADDRSTRLEN]; 
checkme. orig_ip = inet_ntop (AF_INET,&origaddr. sin_addr ,res, sizeof (res)); 
checkme. orig_port = ntohs (origaddr. sin_port ); 
} 
} 

Regards 
Philip 
----- Original Message -----
