### ISSUE TITLE
[RASP] e2guardian not starting.  Main process exited, code=killed, status=6/ABRT

### ISSUE THREAD

**Issue by nielssiebert** [e2guardian/e2guardian#547]
H,
I have I raspberry 4 with 4gb ram. Everything is up to date. e2guardian does not start without any real error message. I activated debug level in e2guardian.conf but it remains empty after restart. This is when I type `sudo service e2guardian status`:
```
● e2guardian.service - E2guardian Web filtering
   Loaded: loaded (/lib/systemd/system/e2guardian.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sat 2019-08-24 14:20:40 CEST; 9s ago
     Docs: http://e2guardian.org/
  Process: 31967 ExecStart=/usr/sbin/e2guardian (code=exited, status=0/SUCCESS)
 Main PID: 31968 (code=killed, signal=ABRT)

Aug 24 14:20:40 raspberrypi systemd[1]: Starting E2guardian Web filtering...
Aug 24 14:20:40 raspberrypi systemd[1]: Started E2guardian Web filtering.
Aug 24 14:20:40 raspberrypi systemd[1]: e2guardian.service: Main process exited, code=killed, status=6/ABRT
Aug 24 14:20:40 raspberrypi systemd[1]: e2guardian.service: Failed with result 'signal'.
```
Either in is syslog and any other logs, I can't find any information, that does explain this issue…
Can anybody help?
Thanks and Best Regards, Niels

**Comment by nielssiebert** [comment]
This are my build-options:
````
sudo /usr/sbin/e2guardian -v
e2guardian 5.3.1

Built with:  '--build=arm-linux-gnueabihf' '--includedir=${prefix}/include' '--disable-silent-rules' '--libdir=${prefix}/lib/arm-linux-gnueabihf' '--runstatedir=/run' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-sslmitm=yes' '--enable-pcre=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'build_alias=arm-linux-gnueabihf' 'CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/e2guardian-0dKyHz/e2guardian-5.3.1=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fdebug-prefix-map=/build/e2guardian-0dKyHz/e2guardian-5.3.1=. -fstack-protector-strong -Wformat -Werror=format-security'
````

**Comment by nielssiebert** [comment]
Another additional information
````
sudo /usr/sbin/e2guardian -N
terminate called after throwing an instance of 'std::system_error'
  what():  Die Ressource ist zur Zeit nicht verfügbar
Abgebrochen
````
This is german and means kind of like
````
sudo /usr/sbin/e2guardian -N
terminate called after throwing an instance of 'std::system_error'
  what():  Die Ressource ist zur Zeit nicht verfügbar -> The recource is currently unavailabe
Abgebrochen -> Cancelled or terminated

````

**Comment by fredbcode** [comment]
Pi4 , Debian buster ? Are you using a package, a compiled version?
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by nielssiebert** [comment]
Yes Pi4 Debian buster.
I installed e2guardian via
````
sudo apt-get install e2guardian
````

**Comment by nielssiebert** [comment]
Just another additional information:
````
sudo su e2guardian
$
$ ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        8192
coredump(blocks)     0
memory(kbytes)       unlimited
locked memory(kbytes) 65536
process              29184
nofiles              1024
vmemory(kbytes)      unlimited
locks                unlimited
rtprio               2
$
````
Maybe this is an issue? As in squid it is looking like:
````
sudo su -l proxy -s /bin/bash

proxy@raspberrypi:~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 29184
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 2
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 29184
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
proxy@raspberrypi:~$ exit

````

**Comment by fredbcode** [comment]
There is something obviously wrong about pi4 (or Debian Buster) unfortunately I don't have this hardware on-hand for testing

**Comment by fredbcode** [comment]
About PI3 I made specific packages I don't know if the system package works well

**Comment by nielssiebert** [comment]
So are there specific files you would suggest that they could corrupted in case of my hardware and eventually should be changed? So as my profession is application development, maybe I can get it working.

**Comment by fredbcode** [comment]
I guess the binary is not well compiled, you can try this to recompile 

Download and unzip the source code (here in directory "e2guardian")

 apt install --no-install-recommends --no-install-suggests -y curl unzip base-files automake base-passwd bash coreutils dash debianutils diffutils dpkg e2fsprogs findutils grep gzip hostname ncurses-base libevent-pthreads-* libevent-dev ncurses-bin perl-base sed login sysvinit-utils tar bsdutils mount util-linux libc6-dev libc-dev gcc g++ make dpkg-dev autotools-dev debhelper dh-autoreconf dpatch libclamav-dev libpcre3-dev zlib1g-dev pkg-config libssl-dev libssl1.1 git ca-certificates lsb-release gcc-arm-linux-gnueabi g++-arm-linux-gnueabi

 !! Unfortunately the name of some packages could be changed now ... !! 

cd e2guardian
./autogen.sh
./configure --host=arm --prefix=/usr --enable-clamd=yes --with-proxyuser=e2guardian --with-proxygroup=e2guardian --sysconfdir=/etc --localstatedir=/var --enable-icap=yes --enable-commandline=yes --enable-email=yes --enable-ntlm=yes --enable-pcre=yes --enable-sslmitm=yes
make
cp src/e2guardian /usr/sbin

**Comment by mitodeboa** [comment]
I have the same problem in raspberry pi both installing package and compiling.
First I tried to compile 5.2.2 and after a while I tried to compile 5.3.3 and finally I tried to install package 5.3.3 from testing repo. Always same result status=6/ABRT

I tried to compile and configure in x86 with enable-sslmitm successfully

**Comment by fredbcode** [comment]
Compiled on pi4 or cross compilation ?
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by mitodeboa** [comment]
Compiled on Raspberrypi 4.14.79

**Comment by fredbcode** [comment]
The output of /usr/sbin/e2guardian -N ?
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
Which hardware ? Pi3+, pi4 ?
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by nielssiebert** [comment]
pi@raspberrypi:~ $ /usr/sbin/e2guardian -N
Unable to setgid()

**Comment by mitodeboa** [comment]
Excuse me, hardware is Pi Zero W. 
The output of /usr/sbin/e2guardian -N is:
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted

**Comment by nielssiebert** [comment]
Hm after I tried your suggestions @fredbcode I'm getting following issue:
````
● e2guardian.service - LSB: e2guardian configuration
   Loaded: loaded (/etc/init.d/e2guardian; generated)
   Active: failed (Result: protocol) since Sat 2019-08-31 12:46:36 CEST; 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 8939 ExecStart=/etc/init.d/e2guardian start (code=exited, status=0/SUCCESS)

Aug 31 12:46:36 raspberrypi systemd[1]: Starting LSB: e2guardian configuration...
Aug 31 12:46:36 raspberrypi systemd[1]: e2guardian.service: Can't open PID file /run/e2guardian.pid (yet?) after start: No such file or directory
Aug 31 12:46:36 raspberrypi systemd[1]: e2guardian.service: Failed with result 'protocol'.
Aug 31 12:46:36 raspberrypi systemd[1]: Failed to start LSB: e2guardian configuration.

````

**Comment by nielssiebert** [comment]
Ou the cp command didn't work or I forgot it as there was no e2guardian file und /usr/sbin/
Good message is. Something is happening now:
````
pi@raspberrypi:/etc/e2guardian/e2guardian-5.3 $ sudo service e2guardian restart
Job for e2guardian.service failed because the control process exited with error code.
See "systemctl status e2guardian.service" and "journalctl -xe" for details.
pi@raspberrypi:/etc/e2guardian/e2guardian-5.3 $ sudo systemctl status e2guardian.service
● e2guardian.service - LSB: e2guardian configuration
   Loaded: loaded (/etc/init.d/e2guardian; generated)
   Active: failed (Result: exit-code) since Sat 2019-08-31 12:54:56 CEST; 14s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9408 ExecStart=/etc/init.d/e2guardian start (code=exited, status=1/FAILURE)

Aug 31 12:54:56 raspberrypi e2guardian[9413]: Error reading custom image file.
Aug 31 12:54:56 raspberrypi e2guardian[9408]: Error opening messages file (does it exist?): /usr/share/e2guardian/languages/ukenglish/messages
Aug 31 12:54:56 raspberrypi e2guardian[9408]: Error parsing the e2guardian.conf file or other e2guardian configuration files
Aug 31 12:54:56 raspberrypi e2guardian[9413]: Error opening messages file (does it exist?):
Aug 31 12:54:56 raspberrypi e2guardian[9413]: /usr/share/e2guardian/languages/ukenglish/messages
Aug 31 12:54:56 raspberrypi e2guardian[9413]: Error parsing the e2guardian.conf file or other e2guardian configuration files
Aug 31 12:54:56 raspberrypi e2guardian[9408]:  failed!
Aug 31 12:54:56 raspberrypi systemd[1]: e2guardian.service: Control process exited, code=exited, status=1/FAILURE
Aug 31 12:54:56 raspberrypi systemd[1]: e2guardian.service: Failed with result 'exit-code'.
Aug 31 12:54:56 raspberrypi systemd[1]: Failed to start LSB: e2guardian configuration.
````
I'll try to figure this out. 



edit:
````
pi@raspberrypi:/etc/e2guardian/e2guardian-5.3 $ ls /usr/share | grep e2guardian
pi@raspberrypi:/etc/e2guardian/e2guardian-5.3 $
````
no file here, where could I get it from?


edit:
some probs fixed now:
````
pi@raspberrypi:/etc/e2guardian/e2guardian-5.3 $ sudo mkdir /usr/share/e2guardian
pi@raspberrypi:/etc/e2guardian/e2guardian-5.3/data $ sudo cp transparent1x1.gif /usr/share/e2guardian/transparent1x1.gif
pi@raspberrypi:/etc/e2guardian/e2guardian-5.3/data $ sudo cp blockedflash.swf /usr/share/e2guardian/blockedflash.swf
pi@raspberrypi:/etc/e2guardian/e2guardian-5.3/data $ sudo cp -dr languages /usr/share/e2guardian/languages
````

edit :-/
now again:

````
sudo /usr/sbin/e2guardian -N 
terminate called after throwing an instance of 'std::system_error'
  what(): Resource temporarily unavailable
Aborted
````

**Comment by nielssiebert** [comment]
I setted up an pi3b+ with new raspbian/Debian buster: Same problem:
````
Aug 31 14:04:29 raspberrypi systemd[1]: e2guardian.service: Failed with result '
lines 1-11/11 (END)
● e2guardian.service - E2guardian Web filtering
   Loaded: loaded (/lib/systemd/system/e2guardian.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Sat 2019-08-31 14:04:29 BST; 6s ago
     Docs: http://e2guardian.org/
  Process: 8759 ExecStart=/usr/sbin/e2guardian (code=exited, status=0/SUCCESS)
 Main PID: 8760 (code=killed, signal=ABRT)

Aug 31 14:04:29 raspberrypi systemd[1]: Starting E2guardian Web filtering...
Aug 31 14:04:29 raspberrypi systemd[1]: Started E2guardian Web filtering.
Aug 31 14:04:29 raspberrypi systemd[1]: e2guardian.service: Main process exited, code=killed, status=6/ABRT
Aug 31 14:04:29 raspberrypi systemd[1]: e2guardian.service: Failed with result 'signal'.
pi@raspberrypi:~ $ sudo /usr/sbin/e2guardian -N
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted

````

**Comment by fredbcode** [comment]
Something is broken, with buster maybe it's just the package or something more deeper ...

But a compilation and e2guardian -N as root  should works, I must try ...

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by nielssiebert** [comment]
ok, I got it working on my pi4 when setting it up with ubuntu bionic server.

**Comment by nielssiebert** [comment]
````
$e2guardian -version
e2guardian 5.3.3

Built with:  '--build=aarch64-linux-gnu' '--includedir=/include' '--disable-silent-rules' '--libdir=/lib/aarch64-linux-gnu' '--libexecdir=/lib/aarch64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--prefix=/usr' '--enable-clamav=yes' '--enable-sslmitm=yes' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=/share/man' '--infodir=/share/info' 'build_alias=aarch64-linux-gnu'
````
This is console output of my pi4 with ubuntu. Ubuntu is anyway not running properly on raspberry pi4, as any apt command is running into an error. It does work, but I would not recommend to use it actual.
To install ubuntu I followed following instructions:
https://jamesachambers.com/raspberry-pi-ubuntu-server-18-04-2-installation-guide/

**Comment by ctariel** [comment]
I have the same problem : Raspberry PI 4, raspian Buster, e2guardian version from repository (5.3.1).
I am willing to help, and as I live near Rennes, maybe I can lend my Raspberry for 1 week or 2... Just ask !

**Comment by schallee** [comment]
It looks like I tacked this down. I'm running on a odroid xu4 which is also debian armhf.

```
strace -f e2guardian -N:
...
2732  mmap2(NULL, 8392704, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0 <unfinished ...>
3106  <... set_robust_list resumed> )   = 0
2732  <... mmap2 resumed> )             = -1 ENOMEM (Cannot allocate memory)
```
I haven 't looked at the compile but this looks like some sort of guard page between allocations (PROT_NONE). From mmap(2):

```
       ENOMEM (since Linux 4.7) The process's RLIMIT_DATA limit, described  in
              getrlimit(2), would have been exceeded.
```
Which implies something most likely to do with the MAP_STACK option. Amusingly the documentation for MAP_STACK states:

```
       MAP_STACK (since Linux 2.6.27)
              Allocate  the  mapping  at  an address suitable for a process or
              thread stack.  This flag is currently a no-op, but  is  used  in
              the glibc threading implementation so that if some architectures
              require special treatment for  stack  allocations,  support  can
              later be transparently implemented for glibc.
```

Long story short, it appears that this is no longer a "no-op" or, even if it is a no-op, something is still checking the resource limit.

```
ulimit -s unlimited
```

And it runs without issues with -N. 

```
cp /lib/systemd/system/e2guardian.service /etc/systemd/system
vi /etc/systemd/system/e2guardian.service
```
add:

```
LimitSTACK=infinity
```

to the "[Service]" section.

```
systemctl daemon-reload
service e2guardian start
```

and you should be in business. 

This is all sorta weird though. armhf and the xu4 are 32bit. If I set the LimitSTACK to 3G it fails as previously. If I set it to 4G it succeeds. For 32bits that is as close to infinity as it gets. Its also about as useful as trying to pull a double wide mobile home through a one lane tunnel. If anyone figures this out I'd be curious to know what is going on. Enough though for me for one evening,

**Comment by fredbcode** [comment]
> I have the same problem : Raspberry PI 4, raspian Buster, e2guardian version from repository (5.3.1).
> I am willing to help, and as I live near Rennes, maybe I can lend my Raspberry for 1 week or 2... Just ask !

Sorry for the delay ...
Hum why not maybe, I have a real problem for make packages automatically with rasp ...
Can you share a ssh access with me ? If yes send me access (PM)

**Comment by fredbcode** [comment]
Please make a try with: http://numsys.eu/e2guardian/raspbian/e2guardian_5.3.3_debian_raspberry_buster_package.deb

**Comment by fredbcode** [comment]
Someone for testing this package ? 
http://nostromo.traceroot.fr/v5.4.dev/e2debian_buster_V5.4.1_20200228.deb

It's a new automatic build, package for pi will be made automatically at each new version (if it works ...)

**Comment by benfortuna** [comment]
I managed to get it working by reducing httpworkers to 200.

Edit file /etc/e2guardian/e2guardian.conf, change as follows:

`httpworkers = 200` (the default is 500 I think)

Save and start e2guardian. This is with a Pi3b.

**Comment by kurtnordstrom** [comment]
> I managed to get it working by reducing httpworkers to 200.
> 
> Edit file /etc/e2guardian/e2guardian.conf, change as follows:
> 
> `httpworkers = 200` (the default is 500 I think)
> 
> Save and start e2guardian. This is with a Pi3b.

This was the magic solution for my Raspberry Pi.  I wish I'd found this earlier!

**Comment by fredbcode** [comment]
> This was the magic solution for my Raspberry Pi. I wish I'd found this earlier!

That should not be happening with the latest package

**Comment by fredbcode** [comment]
https://e2guardian.numsys.eu you should make a try with v5.4 branch 

The "trick" to update beyond 200 is in systemd https://github.com/e2guardian/e2guardian/blob/v5.4/data/scripts/e2guardian.service.in

**Comment by LegalDreadPirateRobert** [comment]
Am still having this issue, am trying to setup e2guardian && Squid for web filtering . 

i installed both earlier today and both installed fine but while testing it was'nt filtering any of the web urls i had entered so i had to uninstall it now when i try to install it back i get this error `Error opening ${prefix}/etc/e2guardian/e2guardian.conf`

**Comment by fredbcode** [comment]
Installed how ?

Le 05/11/2021 à 13:40, Emhonfubhegbe Osayi Bishop a écrit :

**Comment by fredbcode** [comment]
Quicky tested 

```
apt remove e2guardian --purge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  e2guardian*
0 upgraded, 0 newly installed, 1 to remove and 3 not upgraded.
After this operation, 4194 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 107935 files and directories currently installed.)
Removing e2guardian (5.4.4) ...
(Reading database ... 107540 files and directories currently installed.)
Purging configuration files for e2guardian (5.4.4) ...
Processing triggers for systemd (245.4-4ubuntu3.13) ...
Files have not changed, Decompression not needed

root@demeter:/tmp# dpkg -i e2debian-arm64_bullseye_V5.4.4_20211028.deb 
Selecting previously unselected package e2guardian.
(Reading database ... 107401 files and directories currently installed.)
Preparing to unpack e2debian-arm64_bullseye_V5.4.4_20211028.deb ...
Unpacking e2guardian (5.4.4) ...
Setting up e2guardian (5.4.4) ...
Adding system user `e2guardian' (UID 118) ...
Adding new group `e2guardian' (GID 124) ...
Adding new user `e2guardian' (UID 118) with group `e2guardian' ...
Creating home directory `/var/log/e2guardian' ...

Synchronizing state of e2guardian.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable e2guardian

Processing triggers for systemd (245.4-4ubuntu3.13) ...
root@demeter:/tmp# 
root@demeter:/tmp# pidof e2guardian
792533
root@demeter:/tmp#
```
