### ISSUE TITLE
Denied page template vs CGI discrepancy

### ISSUE THREAD

**Issue by HadiJadallah** [e2guardian/e2guardian#549]
Hello,

I have a E2G 5.3.3 on pfsense 2.4.4 up and running correctly with SSL MITM and filtering / blocking.
1- Accessing a blocked/denied site, the DeniedAccess (CGI) page is displayed correctly but the URL is inaccurate when a secure site is requested by browser/user
Example: 
http**S**://hide.me/en/proxy (secure) will be blocked yet the AccessDenied report page will display the DENIED URL as http://hide.me/en/proxy (none secure). 
This also applies to the Acknowledge link to bypass and allow temp access.
Not sure if this affects websites not configured for auto-redirect from http to https if link is changed. See point 2.
Using the HTML template, the DENIEDURL is displayed correctly and so is the Acknowledge link.

2- I was testing banning a site that is currently down on http but up on https. This site has no auto-redirect from http to https.
E2G will timeout and report a connection issue/error before checking if the site is banned.
Not sure if this correct behavior, but I imagine it should not try to connect if the site is banned.

I thought this might be worth reporting.

Thanks.

**Comment by surjitiit** [comment]
Regarding point 1- May be you added "http://hide.me" instead of "hide.me"  in banned sites list.

**Comment by HadiJadallah** [comment]
@surjitiit Actually I did not add any thing. This is default blacklist. I just selected the categories I want to ban. 
If you use the HTMLTemplate provided by e2g then switch to CGI scripts, you can see the difference. No need to change anything else.
When I dug deeper, the html template is populated directly from e2g code while the CGI use URL parameters to pass the variables i.e. DENIED URL, HOST, USER DETAILS, HASH...etc.

Thank you

**Comment by philipianpearce** [comment]
1. Thanks for reporting this - I think it is now fixed in v5.3.dev and v5.4.dev.

2. This is the correct behavior. Although the site may be in a block list, this may overridden by a exception or grey url at the same site, so MITM is done even on blocked sites, so that the url requested can be seen.   At present the MITM to the target and the client is done at the same time,  this may be changed in a future release.

**Comment by HadiJadallah** [comment]
Thanks Philip
Will test once a 5.3.4 release is available

Cheers.

**Comment by fredbcode** [comment]
@HadiJadallah Can you confirm ?

**Comment by HadiJadallah** [comment]
Am away from the setup for the next few days.
Once back I should be able to compile the pfSense version and test it.

Hope thats ok.

**Comment by HadiJadallah** [comment]
Hi

Seems to be fixed.
Confirmed URL displays correctly.

Thank you @philipianpearce and @fredbcode
