### ISSUE TITLE
Failed to read PID from file /run/e2guardian.pid: Invalid argument

### ISSUE THREAD

**Issue by tachtler** [e2guardian/e2guardian#55]
Hi,

when I start the e2guardian, following error message occurs on /var/log/messages

Feb 23 16:55:32 server systemd: Starting E2guardian Web filtering...
Feb 23 16:55:32 server systemd: Failed to read PID from file /run/e2guardian.pid: Invalid argument
Feb 23 16:55:32 server systemd: Started E2guardian Web filtering.
Feb 23 16:55:34 server e2guardian[19944]: Started sucessfully.

Following list the directory:

/run
-rw-r--r-- 1 root       e2guardian  6 Feb 23 16:55 /run/e2guardian.pid
/run/e2guardian:
total 0

Please, is this a bug, or did I something wrong?

The e2guardian was compiled without settings at: --with-piddir!

Thank you!
Klaus

**Comment by nerijus** [comment]
Could it be a selinux issue?

**Comment by tachtler** [comment]
Sorry, no:

getenforce said
Disabled

**Comment by fredbcode** [comment]
A problem with systemd ?

In /lib/systemd/system/e2guardian.service
PIDFile=/run/e2guardian.pid

But: e2guardian creates pidfile as /var/run/e2guardian.pid

Or something like that

**Comment by tachtler** [comment]
I don't think so, because it will start and the PID dile has thw right pid.

With other programs under systemd it's /run/squid.pid too and wirh the  dansguardian 2.10.x it's also /run/dansguardian.pid but the last, i will check tomorrow.

I think under SysV-Init /var/run is the right place, but under System

**Comment by tachtler** [comment]
Sorry... type on my mobile phone...

Why are in the error message "Invalid argument"?

**Comment by fredbcode** [comment]
I don't know this is a systemd message
All I can say is this message is usually a config error "Failed to read 
PID from file xxxx: Invalid argument"  (checked with google)

Do you have something in e2guardian.conf pidfilename = ?

**Comment by Django-BOfH** [comment]
Pardon, but you should use the last version (e2guardian-3.1.2-2.el7.centos.x86_64) from here: http://repo.mailserver.guru/7/os/x86_64/repoview/e2guardian.html
This version works without your error. ;)

**Comment by tachtler** [comment]
Thank you Django,

the error was gone! 

@fredbcode - you're right, it was a systemd problem!

Solution was in
 - /usr/lib/systemd/system/e2guardian.service

**NOT** to have any configuration for the PID file!

Thank you all!
Klaus.
