### ISSUE TITLE
Youtube filtering does not work for Chrome in transparent mode

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#550]
Firefox, Edge and Internet Explorer all seem to have Youtube filtered even in transparent mode. However for some reason Chrome is only filtered when the proxy server is explicitly set.

The file that I have edited is the sslsiteregexplist file.

I have tested on several different client networks, freshly installed Google Chromes, cleared the caches etc and for some reason Chrome does not seem to be filtering Google Safe Search and Youtube Safe Mode unless you have the DNS entries set on the DNS servers or Chrome has the proxy server explicitly set. But IE, Firefox and Microsoft Edge all seem to support Youtube Filtering even in transparent mode.

This is for networks that are currently not using MITM. I started using MITM but had problems with the server crashing so I have disabled MITM until I have time to research that issue. I mention this because I know most people are probably using MITM.

**Comment by surjitiit** [comment]
I'm also facing same problem. Google and Youtube safe searching.
I am using sslsiteregexplist file to enable disable google and youtube safe searching.

It is working fine for MITM but for that i have updates urlregexplist and addheaderregexplist files.

also i want to know if some one have idea about urlregexplist and addheaderregexplist files. When we use these files?

**Comment by philipianpearce** [comment]
Are you sure that the Chrome google/youtube traffic is going via e2g (i.e. port 443 tcp). Are they logged in the e2g access.log?  

I understand that Chrome will try and get to google sites via QUIC over UDP.  So try blocking these port(s) at the firewall so that chrome falls back to http(s).

**Comment by Dalacor** [comment]
Oh I see what the problem is now. My firewall is redirecting tcp 443 traffic, but not udp 443 traffic! This is why Chrome is bypassing the firewall. I was not aware that Chrome is using QUIC now.

I don't use Chrome for my clients as I install Firefox on all client computers. So what I have done for the moment is set the DNS entries on the windows servers for google and youtube safe mode and this has fixed the issue.

Chrome is obviously going through e2guardian for most websites as I tested other websites.

I will have to investigate if I should redirect udp 443 traffic to e2guardian so that Chrome cannot bypass E2guardian in transparent mode, but I am not sure if that will break functionality with other things that use udp port 443.

Thank you for providing the solution!
