### ISSUE TITLE
Ubuntu post-installation script bug

### ISSUE THREAD

**Issue by rvbglas** [e2guardian/e2guardian#551]
Post-installation script /var/lib/dpkg/info/e2guardian.postinst fails - invalid find command (exec instead of -exec key):

/var/lib/dpkg/info/e2guardian.postinst, lines 30-31

Now:
find /etc/e2guardian -type d exec chmod 750 {} \+
find /etc/e2guardian -type f exec chmod 640 {} \+

Should be:
find /etc/e2guardian -type d -exec chmod 750 {} \+
find /etc/e2guardian -type f -exec chmod 640 {} \+

**Comment by fredbcode** [comment]
Thanks, fixed
