### ISSUE TITLE
max value of httpworkers? down the service

### ISSUE THREAD

**Issue by surjitiit** [e2guardian/e2guardian#553]
I have set httpworkers=45000. it is causing to down e2guardian service. i do not no why? is there any limitaion to set httpworkers value?

**Comment by Anthony-76** [comment]
httpworkers = 45000 its a very very high value...

Maybe you have a memory issue.
you should see syslog and/or messages logs files.

**Comment by Dalacor** [comment]
45 000 httpworkers. What size network are you serving? The entire country lol !.

Check your dstats file to see how many httpworkers you really need. I am currently using 1500 for a network that has around 100 computers, although not all in simultaneous use.

You are either running out of memory or you are running out of file descriptors as Linux has a hard and soft File descriptor Limit which you will need to increase accordingly. But you have way too many httpworkers. Set if for 1000 httpworkers and check your dstats file and increase accordingly.

**Comment by surjitiit** [comment]
thanks your reply..
