### ISSUE TITLE
v5.3 segfault when visting sites without an SSL cert with accessdeniedaddress block page

### ISSUE THREAD

**Issue by ghost** [e2guardian/e2guardian#556]
Hi all,

I'm seeing a segfault when trying to access https versions of websites that don't have an SSL cert. This is only occurring when I have an accessdeniedaddress value set in the filter group config file.

Version: 5.3
OS: Centos 7
SSLMITM on

To reproduce set reporting level to 2 and set accessdeniedaddress to https://github.com and visit https://neverssl.com through the filter.

**Comment by ghost** [comment]
Further testing on this issue, it appears any SSL error will cause the segfault.

So with accessdeniedaddress set - any example of a bad certificate from https://badssl.com will cause e2g to stop. 

Also, turning mitmcheckcert off in group config or adding the site to the nocertchecklist results in normal behaviour, no segfault.

**Comment by ghost** [comment]
Further further testing, and it segfaults after the line `Displaying TEMPLATE`, but of course with reporting level 2 there is no template to show, so could the expected and lack of template be the cause?

Below is debug output taken while the segfault occurs if that helps:

```hw7: Start of request header:in
hw7: header:in before getLine - timeout:55000 Line: 1828 Function: in
hw7: firstime: header:in after getLine  Line: 1832 Function: in
hw7: header:size =  5
hw7: first line =  CONNECT expired.badssl.com:443 HTTP/1.1
 Line: 973 Function: checkheaderser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
 Line: 973 Function: checkheaderroxy-Connection: keep-alive
 Line: 973 Function: checkheaderonnection: keep-alive
 Line: 973 Function: checkheaderost: expired.badssl.com:443
hw7: CheckHeader: HTTP/1.1 detected Line: 982 Function: checkheader
hw7: zero contentlength on request due to not POST/PUT 
hw7: CheckHeader: CONNECT request detected Line: 1036 Function: checkheader
hw7: CheckHeader flags before normalisation: AP=1 PPC=1 1.1=1 connectionclose=0 CL=0 Line: 1043 Function: checkheader
hw7: CheckHeader flags after normalisation: AP=1 WP=1 Line: 1066 Function: checkheader
hw7: from header url:https://expired.badssl.com Line: 1218 Function: getUrl
 Line: 541 Function: setURL changed from: CONNECT expired.badssl.com:443 HTTP/1.1
 Line: 549 Function: setURLadssl.com:443 HTTP/1.1
 Line: 554 Function: setURLchanged from: Host: expired.badssl.com:443
 Line: 563 Function: setURLsl.com
hw7: isProxyRequest is 1
hw7:  firsttime =1ismitm =0 clientuser = group = 0
hw7: Compiling ,*[a-z|A-Z].*
hw7: ...with PCRE 
hw7: from header url:https://expired.badssl.com Line: 1218 Function: getUrl
hw7: decoding url Line: 1389 Function: decode
hw7: from header url:https://expired.badssl.com Line: 1218 Function: getUrl
hw7: 177778Start URL https://expired.badssl.comis_ssl=1ismitm=0
After StoryA pre-authcheck0 mess_no 0
hw7: isProxyRequest is 1 only_ip_auth is 0 needs proxy for auth plugin is 0
hw7:  -Not got persistent credentials for this connection - querying auth plugins
hw7:  -Querying next auth plugin...
hw7:  -Auth plugin found username 8080 (), now determining group
hw7: Matched port 8080 to port list
hw7: Auth plugin found username & group; not querying remaining plugins
hw7:  -Identity found; caching username & group
Auth plugin is for a connection-based auth method - keeping credentials for entire connection
hw7:  -username: 8080
hw7:  -filtergroup: 2
hw7:  -About to check for bypass...
hw7: Found cookie: Line: 1292 Function: getCookie
hw7: No bypass cookie Line: 1320 Function: isBypassCookie
hw7:  -Finished bypass checks.
hw7: inIPList no match for expired.badssl.com
hw7: inIPList no match for badssl.com
hw7: inIPList no match for .com
hw7: After StoryB checkrequest isexception 0 gomitm 1 mess_no 0
hw7: May_be_loop = 0  port 443
hw7: Connecting to IP 104.154.89.105 port 443
hw7: Got connection upfailure is 0
hw7:   got past line 990 rfo 
Going MITM ....
hw7:  Start goMITM nf 0 upfail 0
hw7:  -Intercepting HTTPS connection
hw7:  -Getting ssl certificate for client connection
hw7: Generating serial no for expired.badssl.com
hw7: Serial no is DA2BAA14D1AAD902ACE4922425066FC3
hw7: looking for cert /var/e2guardian/generated_ssl/DA/2B/AA/14D1AAD902ACE4922425066FC3
hw7: Certificate found
hw7:  -Going SSL on the peer connection
hw7:  nf 0 upfail 0
hw7:  -Going SSL on upstream connection 
hw7:  nf 0 upfail 0
hw7:  -Checking certificate
hw7:  -checking SSL certificate is valid
hw7:  nf 1 upfail 0
hw7:  -SSL Interception failed Certificate supplied by server was not valid nf 1 upfail 0
hw7:  -Building raw log data string... hw7:  -...built
hw7:  -reporting level is 2
hw7:  -Enabling filter bypass hash generation
hw7:  - filter bypass hash generation virushah 0log: received a log request0
SSL SITE
1
0
0
https://expired.badssl.com
Certificate supplied by server was not valid: certificate has expired
CONNECT
8080
10.220.220.58
443
0
0
0
0
0
0
2
403
0
-
1570631435
694519

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0


150
0

 dohash 1 filterhash 1
hw7: mime type: - Line: 218 Function: isContentType
hw7: mimes result : false Line: 245 Function: 29 1570631436.027         8080    10.220.220.58   10.220.220.58   https://expired.badssl.com:443CONNECT  403     0       -       Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0  -       334     -       150   *DENIED* Certificate supplied by server was not valid: certificate has expired   0       SSL SITE        testgroup       3
isContentType
hw7: mime type: - Line: 218 Function: isContentType
hw7: mimes result : false Line: 245 Function: isContentType
hw7:  -generate Bypass hashedurl data 10.220.220.58 https://expired.badssl.com 8080 1570631736 result GBYPASS=0F6FD45C605DE93A5B2C038C96A0C3951570631736
hw7: Displaying TEMPLATE
```

**Comment by fredbcode** [comment]
Can you make a test with branch v5.4.dev, please ?

**Comment by ghost** [comment]
@fredbcode I've just tested this under the same conditions and it's now working as expected without any segfaults. Thanks for the fix!

**Comment by fredbcode** [comment]
@TedSeabed Thank you very much !
I pushed another way to fix this bug (without less consequences) 

You can make a try, please ? With a debug mode if you can 

Thank for your help

**Comment by ghost** [comment]
Morning @fredbcode, still working great after a pull on the v5.4dev branch. Debug output below

```hw27: header:size =  5
hw27: first line =  CONNECT expired.badssl.com:443 HTTP/1.1
hw27: Header value from client: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firef Line: 973 Function: checkheader
 Line: 973 Function: checkheaderProxy-Connection: keep-alive
 Line: 973 Function: checkheaderConnection: keep-alive
 Line: 973 Function: checkheaderHost: expired.badssl.com:443
hw27: CheckHeader: HTTP/1.1 detected Line: 982 Function: checkheader
hw27: zero contentlength on request due to not POST/PUT 
hw27: CheckHeader: CONNECT request detected Line: 1036 Function: checkheader
hw27: CheckHeader flags before normalisation: AP=1 PPC=1 1.1=1 connectionclose=0 CL=0 Line: 1043 Function: checkheader
hw27: CheckHeader flags after normalisation: AP=1 WP=1 Line: 1066 Function: checkheader
hw27: from header url:https://expired.badssl.com Line: 1218 Function: getUrl
 Line: 541 Function: setURL) changed from: CONNECT expired.badssl.com:443 HTTP/1.1
 Line: 549 Function: setURLbadssl.com:443 HTTP/1.1
 Line: 554 Function: setURL changed from: Host: expired.badssl.com:443
 Line: 563 Function: setURLssl.com
hw27: isProxyRequest is 1
hw27:  firsttime =1ismitm =0 clientuser = group = 0
hw27: Compiling ,*[a-z|A-Z].*
hw27: ...with PCRE 
hw27: from header url:https://expired.badssl.com Line: 1218 Function: getUrl
hw27: decoding url Line: 1389 Function: decode
hw27: from header url:https://expired.badssl.com Line: 1218 Function: getUrl
hw27: 209029Start URL https://expired.badssl.comis_ssl=1ismitm=0
After StoryA pre-authcheck0 mess_no 0
hw27: isProxyRequest is 1 only_ip_auth is 0 needs proxy for auth plugin is 0
hw27:  -Not got persistent credentials for this connection - querying auth plugins
hw27:  -Querying next auth plugin...
hw27:  -Auth plugin found username 8081 (), now determining group
hw27: Auth plugin found username & group; not querying remaining plugins
hw27:  -Identity found; caching username & group
Auth plugin is for a connection-based auth method - keeping credentials for entire connection
hw27:  -username: 8081
hw27:  -filtergroup: 2
hw27:  -About to check for bypass...
hw27: Found cookie: Line: 1292 Function: getCookie
hw27: No bypass cookie Line: 1320 Function: isBypassCookie
hw27:  -Finished bypass checks.
hw27: inIPList no match for expired.badssl.com
hw27: inIPList no match for badssl.com
hw27: inIPList no match for .com
hw27: After StoryB checkrequest isexception 0 gomitm 1 mess_no 0
hw27: May_be_loop = 0  port 443
hw27: Connecting to IP 104.154.89.105 port 443 after dns lookup
hw27: Got connection upfailure is 0
hw27:   got past line 990 rfo 
Going MITM ....
hw27:  Start goMITM nf 0 upfail 0
hw27:  -Intercepting HTTPS connection
hw27:  -Getting ssl certificate for client connection
hw27: Generating serial no for expired.badssl.com
hw27: Serial no is DA2BAA14D1AAD902ACE4922425066FC3
hw27: looking for cert /var/e2guardian/generated_ssl/DA/2B/AA/14D1AAD902ACE4922425066FC3
hw27: Certificate not found. Creating one
hw27: certificate create 0x7f69940038a0
hw27:  -Going SSL on the peer connection
hw27:  nf 0 upfail 0
hw27:  -Going SSL on upstream connection 
hw27:  nf 0 upfail 0
hw27:  -Checking certificate
hw27:  -checking SSL certificate is valid
hw27:  nf 1 upfail 0
hw27:  -SSL Interception failed Certificate supplied by server was not valid nf 1 upfail 0
hw27:  -Building raw log data string... hw27:  -...built
hw27:  -Shutting down ssl to proxy
log: received a log request0
SSL SITE
1
0
0
https://expired.badssl.com
Certificate supplied by server was not valid: certificate has expired
CONNECT
8081
10.220.219.61
443
0
0
0
0
0
0
2
403
0
-
1583490728
178287

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0


150
0
8081:PS:port:pdef


31 1583490728.534               8081    10.220.219.61   10.220.219.61   https://expired.badssl.com:443  CONNECT 4030       -       Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0  -       356     - 150      *DENIED* Certificate supplied by server was not valid: certificate has expired  0       SSL SITE        staff      3
hw27:  -Shutting down ssl to client
hw27:  -Attempting graceful connection close Line: 1411 Function: handleConnection
hw27: handle_peer returned: 0
hw27:  in  handle connection
hw27:  waiting connection on http_worker_Q 
listen2_proxy: 1: got connection from accept
listen2_proxy: 1: pushed connection to http_worker_Q
hw28:  popped connection from http_worker_Q
hw28:  -got peer connection```

**Comment by fredbcode** [comment]
Thanks 

Le 6 mars 2020 11:43:34 GMT+01:00, TedSeabed <notifications@github.com> a écrit :
>Morning @fredbcode, still working great after a pull on the v5.4dev
>branch. Debug output below
>
>```hw27: header:size =  5
>hw27: first line =  CONNECT expired.badssl.com:443 HTTP/1.1
>hw27: Header value from client: User-Agent: Mozilla/5.0 (Windows NT
>10.0; Win64; x64; rv:73.0) Gecko/20100101 Firef Line: 973 Function:
>checkheader
> Line: 973 Function: checkheaderProxy-Connection: keep-alive
> Line: 973 Function: checkheaderConnection: keep-alive
> Line: 973 Function: checkheaderHost: expired.badssl.com:443
>hw27: CheckHeader: HTTP/1.1 detected Line: 982 Function: checkheader
>hw27: zero contentlength on request due to not POST/PUT 
>hw27: CheckHeader: CONNECT request detected Line: 1036 Function:
>checkheader
>hw27: CheckHeader flags before normalisation: AP=1 PPC=1 1.1=1
>connectionclose=0 CL=0 Line: 1043 Function: checkheader
>hw27: CheckHeader flags after normalisation: AP=1 WP=1 Line: 1066
>Function: checkheader
>hw27: from header url:https://expired.badssl.com Line: 1218 Function:
>getUrl
>Line: 541 Function: setURL) changed from: CONNECT
>expired.badssl.com:443 HTTP/1.1
> Line: 549 Function: setURLbadssl.com:443 HTTP/1.1
> Line: 554 Function: setURL changed from: Host: expired.badssl.com:443
> Line: 563 Function: setURLssl.com
>hw27: isProxyRequest is 1
>hw27:  firsttime =1ismitm =0 clientuser = group = 0
>hw27: Compiling ,*[a-z|A-Z].*
>hw27: ...with PCRE 
>hw27: from header url:https://expired.badssl.com Line: 1218 Function:
>getUrl
>hw27: decoding url Line: 1389 Function: decode
>hw27: from header url:https://expired.badssl.com Line: 1218 Function:
>getUrl
>hw27: 209029Start URL https://expired.badssl.comis_ssl=1ismitm=0
>After StoryA pre-authcheck0 mess_no 0
>hw27: isProxyRequest is 1 only_ip_auth is 0 needs proxy for auth plugin
>is 0
>hw27:  -Not got persistent credentials for this connection - querying
>auth plugins
>hw27:  -Querying next auth plugin...
>hw27:  -Auth plugin found username 8081 (), now determining group
>hw27: Auth plugin found username & group; not querying remaining
>plugins
>hw27:  -Identity found; caching username & group
>Auth plugin is for a connection-based auth method - keeping credentials
>for entire connection
>hw27:  -username: 8081
>hw27:  -filtergroup: 2
>hw27:  -About to check for bypass...
>hw27: Found cookie: Line: 1292 Function: getCookie
>hw27: No bypass cookie Line: 1320 Function: isBypassCookie
>hw27:  -Finished bypass checks.
>hw27: inIPList no match for expired.badssl.com
>hw27: inIPList no match for badssl.com
>hw27: inIPList no match for .com
>hw27: After StoryB checkrequest isexception 0 gomitm 1 mess_no 0
>hw27: May_be_loop = 0  port 443
>hw27: Connecting to IP 104.154.89.105 port 443 after dns lookup
>hw27: Got connection upfailure is 0
>hw27:   got past line 990 rfo 
>Going MITM ....
>hw27:  Start goMITM nf 0 upfail 0
>hw27:  -Intercepting HTTPS connection
>hw27:  -Getting ssl certificate for client connection
>hw27: Generating serial no for expired.badssl.com
>hw27: Serial no is DA2BAA14D1AAD902ACE4922425066FC3
>hw27: looking for cert
>/var/e2guardian/generated_ssl/DA/2B/AA/14D1AAD902ACE4922425066FC3
>hw27: Certificate not found. Creating one
>hw27: certificate create 0x7f69940038a0
>hw27:  -Going SSL on the peer connection
>hw27:  nf 0 upfail 0
>hw27:  -Going SSL on upstream connection 
>hw27:  nf 0 upfail 0
>hw27:  -Checking certificate
>hw27:  -checking SSL certificate is valid
>hw27:  nf 1 upfail 0
>hw27:  -SSL Interception failed Certificate supplied by server was not
>valid nf 1 upfail 0
>hw27:  -Building raw log data string... hw27:  -...built
>hw27:  -Shutting down ssl to proxy
>log: received a log request0
>SSL SITE
>1
>0
>0
>https://expired.badssl.com
>Certificate supplied by server was not valid: certificate has expired
>CONNECT
>8081
>10.220.219.61
>443
>0
>0
>0
>0
>0
>0
>2
>403
>0
>-
>1583490728
>178287
>
>Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101
>Firefox/73.0
>
>
>150
>0
>8081:PS:port:pdef
>
>
>31 1583490728.534               8081    10.220.219.61   10.220.219.61  
>https://expired.badssl.com:443  CONNECT 4030       -       Mozilla/5.0
>(Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0  -  
>356     - 150      *DENIED* Certificate supplied by server was not
>valid: certificate has expired  0       SSL SITE        staff      3
>hw27:  -Shutting down ssl to client
>hw27:  -Attempting graceful connection close Line: 1411 Function:
>handleConnection
>hw27: handle_peer returned: 0
>hw27:  in  handle connection
>hw27:  waiting connection on http_worker_Q 
>listen2_proxy: 1: got connection from accept
>listen2_proxy: 1: pushed connection to http_worker_Q
>hw28:  popped connection from http_worker_Q
>hw28:  -got peer connection```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/556#issuecomment-595711059

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
