### ISSUE TITLE
V5.3 - getting warning when starting e2guardian service

### ISSUE THREAD

**Issue by surjitiit** [e2guardian/e2guardian#557]
**When start e2guardian services i am getting following warning on console. But e2guardian is Started successfully. Is any one have idea why there warning coming and how to resolve it?**
### 
SB warning: Undefined list /etc/e2guardian/examplef1.story list localbanned used at line 99 of /etc/e2guardian/common.story
SB warning: Undefined list /etc/e2guardian/examplef1.story list localexception used at line 105 of /etc/e2guardian/common.story
SB warning: Undefined list /etc/e2guardian/examplef1.story list localgreyssl used at line 106 of /etc/e2guardian/common.story
SB warning: Undefined list /etc/e2guardian/examplef1.story list localbanned used at line 107 of /etc/e2guardian/common.story
SB warning: Undefined list /etc/e2guardian/examplef1.story list localgrey used at line 121 of /etc/e2guardian/common.story
SB warning: Undefined list /etc/e2guardian/examplef1.story list localbanned used at line 126 of /etc/e2guardian/common.story
SB warning: Undefined list /etc/e2guardian/examplef1.story list localexception used at line 131 of /etc/e2guardian/common.story
SB warning: Undefined list /etc/e2guardian/examplef1.story list localexception used at line 165 of /etc/e2guardian/common.story

**Comment by fredbcode** [comment]
Which version ? installed how ?

**Comment by fredbcode** [comment]
lack of information
