### ISSUE TITLE
v5.3 OpenBSD does not support sigtimedwait()

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#559]
Google group comments relates.   

sigwait() is not direct subsitute for sigtimedwait().

OpenBSD compatible code requires use of timer_settime() called to achieve same effect as sigtimedwait().  Revised code tested OK under Linux.

Needs testing with OpenBSD.

I have posted a temporary branch  v5.3.dev.bsd with this change.   Please test and see if this works OK with OpenBSD and FreeBSD.   Note that you will need to add -lrt to the link parameters for this to link.

**Comment by jaywax** [comment]
Hi Philip,
Here's the output of make compilation on OpenBSD 6.5 :

> FatController.cpp: In function 'int fc_controlit()':
> FatController.cpp:1609:5: error: 'timer_create' was not declared in this scope
>      timer_create(CLOCK_REALTIME,NULL, &timerid);
>      ^~~~~~~~~~~~
> FatController.cpp:1609:5: note: suggested alternative: 'timerclear'
>      timer_create(CLOCK_REALTIME,NULL, &timerid);
>      ^~~~~~~~~~~~
>      timerclear
> FatController.cpp:1714:9: error: 'timer_settime' was not declared in this scope
>          timer_settime(timerid ,0 , &timeout, NULL);
>          ^~~~~~~~~~~~~
> FatController.cpp:1714:9: note: suggested alternative: 'clock_settime'
>          timer_settime(timerid ,0 , &timeout, NULL);
>          ^~~~~~~~~~~~~
>          clock_settime
> *** Error 1 in target 'e2guardian-FatController.o'
> mv -f .deps/e2guardian-SysV.Tpo .deps/e2guardian-SysV.Po
> mv -f .deps/e2guardian-NaughtyFilter.Tpo .deps/e2guardian-NaughtyFilter.Po
> mv -f .deps/e2guardian-ICAPHeader.Tpo .deps/e2guardian-ICAPHeader.Po
> mv -f .deps/e2guardian-HTTPHeader.Tpo .deps/e2guardian-HTTPHeader.Po
> mv -f .deps/e2guardian-ListMeta.Tpo .deps/e2guardian-ListMeta.Po
> mv -f .deps/e2guardian-ListContainer.Tpo .deps/e2guardian-ListContainer.Po
> mv -f .deps/e2guardian-ConnectionHandler.Tpo .deps/e2guardian-ConnectionHandler.Po
> *** Error 1 in src (Makefile:918 'e2guardian-FatController.o')
> *** Error 1 in . (Makefile:424 'all-recursive')
> *** Error 2 in /usr/local/src/e2guardian (Makefile:340 'all')

**Comment by philipianpearce** [comment]
Thanks,  Can you try the latest v5.3.dev.bsd I have posted - It uses a older timer call which according to OpenBSD man pages is supported.   Can you see if it complies OK?

And if it does then enable dstats and then check that the interval stats are being recorded. (In linux this code complies OK, but timer does not appear to work! So no interval stats.)

Thanks
Philip

**Comment by jaywax** [comment]
The compilation succeeded, and i'm trying to figure out how to replace dstats with something under openbsd (maybe systat, i don't know...). I don't really understand which stats you're talking about... sorry.
Thanks.

**Comment by philipianpearce** [comment]
Hi Jay, 

Dstats are sar-like stats produced by e2g (very useful for tuning). 

They are configured in e2guardian.conf:- 

uncomment 

#dstatslocation = .... 

and 

#dstatinterval = 300 

change dstatinterval to 10 

This should then put a sar-like line in the dstatslocation file every 10 seconds. 

If it does then the timer needed with sigwait() is working. If it does not it is not working correctly. 

Philip 

----- Original Message -----

**Comment by jaywax** [comment]
Hello Philip,
Thanks for the explanation !
It works !
> tail -f dstats.log 
time		httpw	busy	httpwQ	logQ	conx	conx/s	reqs	reqs/s	maxfd	LCcnt
1571833881	500	0	0	0	0	0	0	0	0	1
1571833891	500	0	0	0	0	0	0	0	0	1
1571833901	500	0	0	0	0	0	0	0	0	1
1571833911	500	0	0	0	0	0	0	0	0	1
1571833921	500	0	0	0	0	0	0	0	0	1
1571833931	500	0	0	0	0	0	0	0	0	1
1571833941	500	0	0	0	0	0	0	0	0	1
1571833951	500	0	0	0	0	0	0	0	0	1
``
>

**Comment by philipianpearce** [comment]
Great! I will now re-write with pre-compliler directives. 

Philip 

----- Original Message -----

**Comment by jaywax** [comment]
Thanks for your work.

**Comment by philipianpearce** [comment]
Hi Jay,

Could you try with the latest v5.3.dev.bsd I have posted?   This includes pre-processing directives, so should work on both openbsd and other types of OS.

Thanks
Philip

**Comment by jaywax** [comment]
Hi Philip,
Here's the error i've got when i try to compile : 

> 

FatController.cpp: In function 'int fc_controlit()':
FatController.cpp:1613:5: error: 'OpenBSD' was not declared in this scope
     OpenBSD does not support posix sig_timed_wait, so have to use timer and SIGALRM
     ^~~~~~~
FatController.cpp:1616:5: error: 'timeout' was not declared in this scope
     timeout.it_interval.tv_sec = 0;
     ^~~~~~~
FatController.cpp:1616:5: note: suggested alternative: 'timeoff'
     timeout.it_interval.tv_sec = 0;
     ^~~~~~~
     timeoff

Thanks !

**Comment by philipianpearce** [comment]
Hi Jay, 

Sorry made a syntax error. 

Can you re-try with latest? 

Thanks 
Philip 

----- Original Message -----

**Comment by jaywax** [comment]
Hi Philip,

Works like a charm :)
Thanks

**Comment by philipianpearce** [comment]
Great, I have now merged the fix into v5.3.dev and v5.4.dev branches.

**Comment by rafalj4** [comment]
The same issue occured on MacOS 10.13. Version 5.3.4 is affected.
Below output from make

FatController.cpp:1751:14: error: use of undeclared identifier 'sigtimedwait'
        rc = sigtimedwait(&signal_set, NULL, &timeout);
             ^
1 error generated.
