### ISSUE TITLE
DEVELOPMENT-Branch, ssl_mitm doesn't work...

### ISSUE THREAD

**Issue by tachtler** [e2guardian/e2guardian#56]
Hi, 

hope this is o.k. when I open a issue for the development branch, but we've tried the latest stable AND we're tried the latest development-branch.

With the latest **stable**, we have to configure the whole certificate things, like described in the notes/ssl_mitm, to get e2guardian to start, without any other personal configuration - AND IT WORKS!

With the **development-branch**, we don't have to configure the ssl_mitm things to get e2guardian, 
without any other personal configuration to start - BUT IT DOESN'T WORK!

We always set /etc/e2guardian/e2gaurdianf1.conf --> ssl_mitm = on

Could it be, that there is a problem with the development-branch and ssl_mitm?

Thank you!
Klaus.

**Comment by fredbcode** [comment]
Hi,

Maybe there is a bug now ...
Can you be more explicit, what's wrong exactly ?

I tried recently the dev branch without any issues, as far as I can remember I wrote some new informations in https://github.com/e2guardian/e2guardian/blob/develop/notes/ssl_mitm (Develop file)

**Comment by fredbcode** [comment]
Discussion here https://groups.google.com/forum/#!topic/e2guardian/0FIFHkZlGmo

**Comment by fredbcode** [comment]
| With the development-branch , we don't have to configure the ssl_mitm things to get e2guardian, 
| without any other personal configuration to start 

I don't understand right ? A special configuration is also needed.

**Comment by tachtler** [comment]
Hi,

let me explain how we have been testing, because we want use it in the nearest future under CentOS-7.

We (Django and I) had a rpm with 3.1.2 **stable** installed, **enabled** ssl_mitm like you described at
https://github.com/e2guardian/e2guardian/blob/develop/notes/ssl_mitm

After that (Django) build a rpm with 3.x.x **development-branch** and we tried this with **saved configuration files from the previous 3.1.2 stable** installation.

So we figured out, that ssl_mitm was working with the stabled but not with the development-branch.

**SOLUTION** is, when **sslseparatelist = off (default)** ssl_mitm will be not considered, when we set
- ssl_mitm = on
- sslseparatelist = on

it work's - **BUT if you only set ssl_mitm = on, it doesn't work !**

Thank you, your reaction time on issues are great!
Klaus.

**Comment by fredbcode** [comment]
Ah ok sorry, it's my fault

This new option sslseparatelist is needed for users (like me) who are using the same list for SSL or not.

With sslseparatelist = off - (default) each list is loaded one time, there is no difference between HTTP or HTTPS, like with DansGuardian before  
With sslseparatelist = on  - two separates lists are needed, HTTP and HTTPS. Without your lists should be loaded twice, the same in SSL and no SSL, not good for horsepower ... 

Of course MITM needs dedicated lists, so "sslseparatelist = on" is needed, I added a comment in note.

So it's not an issue but a change in behaviour to consider more use.

**Comment by tachtler** [comment]
Hi,

maybe, both configuration parameter (ssl_mitm **and** sslseparatelist ) should stay one after the other inside the config file...?

Thank you for committing e2guardian, we loved dansguardian, but it's still dead I think?
Klaus.

**Comment by fredbcode** [comment]
You are right I pushed a change. 
Now there is a message when there is ssl_mitm without sslseparatelist

**Comment by tachtler** [comment]
Hi,

sorry, but it doesn't work with the development-branch! - We tested the
- ssl_mitm = on
- sslseparatelist = on

with the 3.1.2 **stable** ! - under the **development-branch** it's still **not** working, sorry for the testing mistake!

Klaus.

**Comment by tachtler** [comment]
Hi,

on the 3.1.2 **stable** set the
- ssl_mitm

is enough to enable ssl_mitm! Setting sslseparatelist = on is not necessary to use MITM.

Thank you for your **patience**!
Klaus.

**Comment by fredbcode** [comment]
I'm trying now without problem, what's wrong exactly ?

e2guardian 3.3.0

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-trickledm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' 'CXXFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-z,relro' 'CPPFLAGS=-D_FORTIFY_SOURCE=2' 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' '--enable-pcre=yes' '--with-filedescriptors=1024' '--enable-sslmitm=yes'

e2guardian.conf:

cacertificatepath = '/home/fred/my_rootCA.crt'
caprivatekeypath = '/home/fred/private_root.pem'
certprivatekeypath = '/home/fred/private_cert.pem'
sslcertificatepath = '/etc/ssl/certs/'
generatedcertpath = '/tmp'



e2guardianf3.conf:

groupmode = 1 
groupname = 'grouptest'
sslseparatelists = on
sslmitm = on
bannedsitelist = '/etc/e2guardian/lists/bannedsitelistgroupetest'
greysitelist = '/etc/e2guardian/lists/greysitelistgroupetest'
greysslsitelist = '/etc/e2guardian/lists/greysslsitelistgroupetest'
bannedsslsitelist = '/etc/e2guardian/lists/bannedsslsitelist'
exceptionsitelist = '/etc/e2guardian/lists/exceptionsitelist'
bannedurllist = '/etc/e2guardian/lists/bannedurllistgroupetest'
greyurllist = '/etc/e2guardian/lists/greyurllist'
exceptionurllist = '/etc/e2guardian/lists/exceptionurllist'
exceptionregexpurllist = '/etc/e2guardian/lists/exceptionregexpurllistgroupetest'
bannedregexpurllist = '/etc/e2guardian/lists/bannedregexpurllist'
picsfile = '/etc/e2guardian/lists/pics'
contentregexplist = '/etc/e2guardian/lists/contentregexplist'
urlregexplist = '/etc/e2guardian/lists/urlregexplist'
localbannedsitelist = '/etc/e2guardian/lists/localbannedsitelist'
localgreysitelist = '/etc/e2guardian/lists/localgreysitelist'
localexceptionsitelist = '/etc/e2guardian/lists/localexceptionsitelist'
localbannedurllist = '/etc/e2guardian/lists/localbannedurllist'
localgreyurllist = '/etc/e2guardian/lists/localgreyurllist'
localexceptionurllist = '/etc/e2guardian/lists/localexceptionurllist'
localbannedsslsitelist = '/etc/e2guardian/lists/localbannedsslsitelist'
localgreysslsitelist = '/etc/e2guardian/lists/localgreysslsitelist'
localbannedsearchlist = '/etc/e2guardian/lists/localbannedsearchlist'
bannedregexwithblanketblock = on
maxuploadsize = -1
blockdownloads = off
exceptionextensionlist = '/etc/e2guardian/lists/exceptionextensionlist'
exceptionmimetypelist = '/etc/e2guardian/lists/exceptionmimetypelist'
bannedextensionlist = '/etc/e2guardian/lists/bannedextensionlist'
bannedmimetypelist = '/etc/e2guardian/lists/bannedmimetypelist'
exceptionfilesitelist = '/etc/e2guardian/lists/exceptionfilesitelist'
exceptionfileurllist = '/etc/e2guardian/lists/exceptionfileurllist'
headerregexplist = '/etc/e2guardian/lists/headerregexplist'
bannedregexpheaderlist = '/etc/e2guardian/lists/bannedregexpheaderlistgroupetest'
htmltemplate = 'test.htm'
sslaccessdeniedaddress = 'http://10.1.1.1/denied_https.php'
ssldeniedrewrite = off
nonstandarddelimiter = off
disablecontentscan = off
deepurlanalysis = off
reportinglevel = 3
usesmtp = off
mailfrom = ''
avadmin = ''
contentadmin = ''
avsubject = 'e2guardian virus block'
contentsubject = 'e2guardian violation'
notifyav = off
notifycontent = off
thresholdbyuser = off
violations = 0
threshold = 0

**Comment by nerijus** [comment]
Why do you call 3.1.2 as stable? it is interim development release. Stable is 3.0.4.

**Comment by fredbcode** [comment]
Which browser ? There is some problem with FF https://groups.google.com/forum/#!topic/e2guardian/0FIFHkZlGmo

**Comment by tachtler** [comment]
Hi,

sorry, but I thought the master is the latest stable, my fault!

Yes we use Firefox ESR 31.4.0 under Linux (CentOS-7), but with 3.1.2 **master**, MITM are working correct.

**/etc/e2guardian/e2guardian.conf**:

----- start -----
# egrep -v '(^#|^$)' /etc/e2guardian/e2guardian.conf
languagedir = '/usr/share/e2guardian/languages'
language = 'ukenglish'
loglevel = 2
logexceptionhits = 2
logfileformat = 1
maxuploadsize = -1
filterip =
filterports = 8080
proxyip = 127.0.0.1
proxyport = 3128
proxytimeout = 20
proxyexchange = 20
pcontimeout = 55
originalip = off
accessdeniedaddress = 'http://YOURSERVER.YOURDOMAIN/cgi-bin/e2guardian.pl'
usecustombannedimage = on
custombannedimagefile = '/usr/share/e2guardian/transparent1x1.gif'
usecustombannedflash = on
custombannedflashfile = '/usr/share/e2guardian/blockedflash.swf'
filtergroups = 1
filtergroupslist = '/etc/e2guardian/lists/filtergroupslist'
bannediplist = '/etc/e2guardian/lists/bannediplist'
exceptioniplist = '/etc/e2guardian/lists/exceptioniplist'
perroomdirectory = '/etc/e2guardian/lists/bannedrooms/'
showweightedfound = on
weightedphrasemode = 2
urlcachenumber = 1000
urlcacheage = 900
scancleancache = on
phrasefiltermode = 2
preservecase = 0
hexdecodecontent = off
forcequicksearch = off
reverseaddresslookups = off
reverseclientiplookups = off
logclienthostnames = off
createlistcachefiles = on
prefercachedlists = off
maxcontentfiltersize = 256
maxcontentramcachescansize = 2000
maxcontentfilecachescansize = 20000
filecachedir = '/tmp'
deletedownloadedtempfiles = on
initialtrickledelay = 20
trickledelay = 10
downloadmanager = '/etc/e2guardian/downloadmanagers/fancy.conf'
downloadmanager = '/etc/e2guardian/downloadmanagers/default.conf'
contentscannertimeout = 60
contentscanexceptions = off
recheckreplacedurls = off
forwardedfor = off
usexforwardedfor = off
logconnectionhandlingerrors = on
logchildprocesshandling = off
maxchildren = 180
minchildren = 20
minsparechildren = 16
preforkchildren = 10
maxsparechildren = 32
maxagechildren = 500
maxips = 0
ipcfilename = '/tmp/.dguardianipc'
urlipcfilename = '/tmp/.dguardianurlipc'
ipipcfilename = '/tmp/.dguardianipipc'
nodaemon = off
nologger = off
logadblocks = off
loguseragent = off
softrestart = off
mailer = '/usr/sbin/sendmail -t'
sslcertificatepath = '/etc/pki/tls'
cacertificatepath = '/etc/pki/e2guardian/certs/my_rootCA.crt'
caprivatekeypath = '/etc/pki/e2guardian/private/private_root.pem'
certprivatekeypath = '/etc/pki/e2guardian/private/private_cert.pem'
generatedcertpath = '/tmp/generatedcerts'
generatedlinkpath = '/tmp/generatedlinks'
----- end -----

/etc/e2guardian/e2guardian.conf:

----- start -----
# egrep -v '(^#|^$)' /etc/e2guardian/e2guardianf1.conf
groupmode = 1
groupname = ''
bannedphraselist = '/etc/e2guardian/lists/bannedphraselist'
weightedphraselist = '/etc/e2guardian/lists/weightedphraselist'
exceptionphraselist = '/etc/e2guardian/lists/exceptionphraselist'
bannedsitelist = '/etc/e2guardian/lists/bannedsitelist'
greysitelist = '/etc/e2guardian/lists/greysitelist'
bannedsslsitelist = '/etc/e2guardian/lists/bannedsslsitelist'
greysslsitelist = '/etc/e2guardian/lists/greysslsitelist'
exceptionsitelist = '/etc/e2guardian/lists/exceptionsitelist'
bannedurllist = '/etc/e2guardian/lists/bannedurllist'
greyurllist = '/etc/e2guardian/lists/greyurllist'
exceptionurllist = '/etc/e2guardian/lists/exceptionurllist'
exceptionregexpurllist = '/etc/e2guardian/lists/exceptionregexpurllist'
bannedregexpurllist = '/etc/e2guardian/lists/bannedregexpurllist'
picsfile = '/etc/e2guardian/lists/pics'
contentregexplist = '/etc/e2guardian/lists/contentregexplist'
urlregexplist = '/etc/e2guardian/lists/urlregexplist'
refererexceptionsitelist = '/etc/e2guardian/lists/refererexceptionsitelist'
refererexceptionurllist = '/etc/e2guardian/lists/refererexceptionurllist'
embededreferersitelist = '/etc/e2guardian/lists/embededreferersitelist'
embededrefererurllist = '/etc/e2guardian/lists/embededrefererurllist'
urlredirectregexplist = '/etc/e2guardian/lists/urlredirectregexplist'
!! Not compiled !! authexceptionsitelist = '/etc/e2guardian/lists/authexceptionsitelist'
!! Not compiled !! authexceptionurllist = '/etc/e2guardian/lists/authexceptionurllist'
blockdownloads = off
exceptionextensionlist = '/etc/e2guardian/lists/exceptionextensionlist'
exceptionmimetypelist = '/etc/e2guardian/lists/exceptionmimetypelist'
bannedextensionlist = '/etc/e2guardian/lists/bannedextensionlist'
bannedmimetypelist = '/etc/e2guardian/lists/bannedmimetypelist'
exceptionfilesitelist = '/etc/e2guardian/lists/exceptionfilesitelist'
exceptionfileurllist = '/etc/e2guardian/lists/exceptionfileurllist'
maxuploadsize = -1
headerregexplist = '/etc/e2guardian/lists/headerregexplist'
bannedregexpheaderlist = '/etc/e2guardian/lists/bannedregexpheaderlist'
addheaderregexplist = '/etc/e2guardian/lists/addheaderregexplist'
naughtynesslimit = 50
 
categorydisplaythreshold = 0
embeddedurlweight = 0
enablepics = off
bypass = 0
bypasskey = ''
infectionbypass = 0
infectionbypasskey = ''
infectionbypasserrorsonly = on
disablecontentscan = off
deepurlanalysis = off
reportinglevel = 3
usesmtp = off
mailfrom = ''
avadmin = ''
contentadmin = ''
avsubject = 'e2guardian virus block'
contentsubject = 'e2guardian violation'
notifyav = off
notifycontent = off
thresholdbyuser = off
violations = 0
threshold = 0
sslcertcheck = off
sslmitm = on
onlymitmsslgrey = off
----- end -----

(Django) will now build the development-branch with the same configuration settings as you described before, at this issue... we will document the tests here...

Thank you
Klaus.

**Comment by fredbcode** [comment]
But what happen ? Error message ? Access denied ?

**Comment by tachtler** [comment]
Hi,

wait... still building the rpm... we will see...

;-)
Klaus.

**Comment by fredbcode** [comment]
Also can you make a try with IE ?

**Comment by fredbcode** [comment]
I mean what happen when you have the problem - it doesn't works - is not enough explicit

**Comment by tachtler** [comment]
Hi,

sorry, we can't test with IE, because it's a separate network with no Windows inside.

When we use 3.1.2 **master** - we had a entry in /var/log/e2guardian/access.log with https://... and the MITM-Certificate was shown in Firefox.

When we use **development-branch**, **no** entry is in /var/log/e2guardian/access.log and the **real** SSL-Certificate will shown in Firefox.

So, no error or something else in logs or on the Firefox display will shown!

Hope this help a little bit more, sorry for the small error description before!
Klaus.

**Comment by tachtler** [comment]
Hi,

last test, before new package was build with the **development-branch** - With Konqueror-Browser, same
issue, sorry.

I will report as soon as possible if the new rpm with your build-options was finished and I could try this...

Klaus.

**Comment by fredbcode** [comment]
| When we use development-branch, no entry is in /var/log/e2guardian/access.log and the real SSL-Certificate will shown in Firefox.

In my case there is nothing in log (seems normal with authorized access...) but when I checked the certificate MITM-Certificate was shown

**Comment by tachtler** [comment]
Hi,

we tested actually with only Proxy settings in the Browser, now authentication against LDAP, NTLM ... was used...

So package is in the last build steps...

Klaus.

**Comment by Django-BOfH** [comment]
how Klaus told me, I've build it with development-sources and following options:
--build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --prefix=/usr --enable-clamd=yes --with-proxyuser=e2guardian --with-proxygroup=e2guardian --sysconfdir=/etc --localstatedir=/var --enable-icap=yes --enable-commandline=yes --enable-email=yes --enable-ntlm=yes --enable-trickledm=yes --enable-pcre=yes --with-filedescriptors=4096 --enable-sslmitm=yes

**Comment by tachtler** [comment]
Hi, 

first of all, we found a error in the configuration file **/etc/e2guardian/e2guardianf1.conf**:
- sslmitm = off

should be
- ssl_mitm = off

Found as error while startup process is running at /var/log/messages.

Test will continue...
Klaus.

**Comment by fredbcode** [comment]
No, the option is sslmitm = off/on
ssl_mitm is unknown (So not checked)

**Comment by fredbcode** [comment]
For reduce --with-filedescriptors=4096 under 1024 Change In FD_SETSIZE is needed for this 
Take a look here https://github.com/e2guardian/e2guardian/blob/develop/INSTALL ( --with-filedescriptors=NUMBER =

**Comment by Django-BOfH** [comment]
O.K: here are our configure options:
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --prefix=/usr --enable-clamd=yes --with-proxyuser=e2guardian --with-proxygroup=e2guardian --sysconfdir=/etc --localstatedir=/var --enable-icap=yes --enable-commandline=yes --enable-email=yes --enable-ntlm=yes --enable-trickledm=yes --enable-pcre=yes --with-filedescriptors=1024 --enable-sslmitm=yes --enable-avastd=yes --enable-kavd=yes --enable-fancydm=yes --enable-orig-ip

After that I've seen this hint:
/home/django/rpmbuild/BUILD/e2guardian-3.3.0/missing: Unknown `--is-lightweight' option

I don't know wether this is a problem or not?

**Comment by tachtler** [comment]
Hi,

you're right, BUT:

**/etc/e2guardian/e2guardianf1.conf**

'# Enable separate ssl lists greysslsitelist and bannedsslsitelist
'# 
'# Note that the logic for handling SSL is changed. In DG when either blanket block (or SSL blanket block) 
'# was active then an SSL site would not be blocked if site name matched either exceptionsitelist or greysitelist. 
'# In e2guardian with blanket block (or SSL blanket block) active an SSL site will only be allowed if it matches 
'# exceptionsitelist or greysslsitelist. This ensures that only trusted sites can be accessed via SSL. 
'# The greysslsitelist is used in order to allow a site to drop through so that it's domain can be mangled via urlregexplist, 
'# e.g. To use the Google mechanism for prevention of https Google search, or to allow an SSL site whilst blocking the corresponding http: site.
'# Default off (DG logic) 
'# Tachtler
'# default: # sslseparatelist = on
sslseparatelist = on

**Is a **s** missing at sslseparatelist**s** = on ?!?**

Feb 24 14:39:55 fw046 e2guardian[3062]: sslmitm requires sslseparatelists
Feb 24 14:39:55 fw046 e2guardian[3062]: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
Feb 24 14:39:55 fw046 e2guardian[3062]: Error reading filter group conf file(s).
Feb 24 14:39:55 fw046 e2guardian[3062]: Error parsing the e2guardian.conf file or other e2guardian configuration files
Feb 24 14:39:55 fw046 e2guardian: sslmitm requires sslseparatelists
Feb 24 14:39:55 fw046 e2guardian: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
Feb 24 14:39:55 fw046 e2guardian: Error reading filter group conf file(s).
Feb 24 14:39:55 fw046 e2guardian: Error parsing the e2guardian.conf file or other e2guardian configuration files
Feb 24 14:39:55 fw046 systemd: e2guardian.service: control process exited, code=exited status=1
Feb 24 14:39:55 fw046 systemd: Failed to start E2guardian Web filtering.
Feb 24 14:39:55 fw046 systemd: Unit e2guardian.service entered failed state.

With sslseparatelist**s** = on

Now e2guaridan starts with:
Feb 24 14:41:16 fw046 systemd: Starting E2guardian Web filtering...
Feb 24 14:41:16 fw046 e2guardian: test
Feb 24 14:41:16 fw046 systemd: Started E2guardian Web filtering.
Feb 24 14:41:18 fw046 e2guardian[3080]: Started sucessfully.

**BUT no MITM was done!**

**/var/log/messages**
 - no error

**/var/log/e2guardian/access.log**
- (HTTP access)
- 2015.2.24 14:47:17 - 127.0.0.1 http://domain.tld/pub  GET 354 0  1 301 -     - - 
- 2015.2.24 14:47:17 - 127.0.0.1 http://domain.tld/pub/  GET 3532 0  1 200 text/html     - -
- (HTTPS access)
- no entry

Browser settings:
Manual proxy configuration:
- HTTP Proxy: 127.0.0.1 8080
- SSL Proxy: 127.0.0.1 8080
(Firefox is running for testing on same Server as e2guardian and squid!)

Can we sent you some debugging?

It looks like MITM-Settings will be totally ignored?

Thank you
Klaus.

**Comment by danfresneda** [comment]
Hi, I'm not sure if this is the cause of your issue but it's one of the problems I encountered when trying to get sslmitm to work. This is referring to the develop branch.

On line 337 of FOptionContainer.cpp there is a bug (I believe):

    if (findoptionS("onlymitmsslgrey") == "on") 
        only_mitm_ssl_grey = true;

This variable, only_mitm_ssl_grey only gets initialized if the option is ON. Otherwise it's garbage and usually ends up evaluating as true. This causes a problem in ConnectionHandler.cpp, line 1524:

    if (o.fg[filtergroup]->only_mitm_ssl_grey && !checkme.isSSLGrey) ismitmcandidate = false;

Since only_mitm_ssl_grey ends up evaluating as true, ismitmcandidate gets set to false and the connection isn't intercepted.

**Comment by tachtler** [comment]
Hi danfresneda,

we set:
'#SSL man in the middle
'# Forge ssl certificates for all non-exception sites, decrypt the data then re encrypt it
'# using a different private key. Used to filter ssl sites
'# Tachtler 
'# default: sslmitm = off
sslmitm = on

'#Limit SSL MITM to sites in greysslsitelist(s)
'# ignored if  sslmitm is off
'# SSL sites not matching greysslsitelist will be treat as if sslmitm is off.
'# Tachtler
'# default: onlymitmsslgrey = off
onlymitmsslgrey = on

**YES - MITM was done, but our https://domain.tld site must be in**
- /etc/e2guardian/lists/greysslsitelist

Thank you for your post!
Klaus.

**Comment by fredbcode** [comment]
@dansfresneda, Bug fixed (and pushed) now, thank for your return

@tachtler There is a bug about log and SSL I'm looking ...

**Comment by danfresneda** [comment]
I see that you tried to fix it fredbcode. However, I think the braces are still off in that particular section of FOptionContainer.cpp
```c++
		if (findoptionS("sslmitm") == "on") {
			ssl_mitm = true;
			mitm_magic = findoptionS("mitmkey");
			if (mitm_magic.length() < 9) {
				std::string s(16u, ' ');
				for (int i = 0; i < 16; i++) {
					s[i] = (rand() % 26) + 'A';
				}
				mitm_magic = s;
			if (findoptionS("onlymitmsslgrey") == "on") 
				only_mitm_ssl_grey = true;
			} else {	
				only_mitm_ssl_grey = false;
			}
```
There's no brace before or after 

    if (findoptionS("onlymitmsslgrey") == "on") 

So only_mitm_ssl_grey is set to false if mitmkey is set correctly.

**Comment by tachtler** [comment]
Hi,

thank you all, you are so great and fast in reply!! - **GREAT!**

Klaus.

**Comment by fredbcode** [comment]
dansfresneda, yes I forgot something sorry. "great and fast in reply!! - GREAT!" -> Great I don't known, too fast sure ...

@tachler please retry with the latest commit, this should fixes bug (worst random bug ...)

**Comment by tachtler** [comment]
Hi,

yes we will try.. Django ist downloading and will start soon the rpm build process..

Thank you so much!
Klaus.

**Comment by fredbcode** [comment]
Don't forget this version still in dev, Philip needs more time to finish SSLMITM and bugs like this can be presents.

**Comment by tachtler** [comment]
Hi,

we will try this first at our development environment with a few users, so don't be afraid, we known it's DEV!

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi, 

so latest development-branch was build as rpm and installed, **BUT sorry it doesn't work**!

**/etc/e2guardian/e2guardianf1.conf**:
'#SSL man in the middle
'# Forge ssl certificates for all non-exception sites, decrypt the data then re encrypt it
'# using a different private key. Used to filter ssl sites
'# Tachtler 
'# default: sslmitm = off
sslmitm = on

'#Limit SSL MITM to sites in greysslsitelist(s)
'# ignored if  sslmitm is off
'# SSL sites not matching greysslsitelist will be treat as if sslmitm is off.
onlymitmsslgrey = off

**No MITM** was done!

**ONLY with - onlymitmsslgrey = on  - and the site listed in following list, than it will work!**
- /etc/e2guardian/lists/greysslsitelist

**/var/log/e2guardian/access.log**
2015.2.24 15:54:51 - 127.0.0.1 https://domain.tld:443 *DENIED* Certificate supplied by server was not valid: unable to get local issuer certificate CONNECT 0 0 SSL Site 1 200 -     - - 
2015.2.24 15:54:56 - 127.0.0.1 https://domain.tld:443 *DENIED* Certificate supplied by server was not valid: unable to get local issuer certificate CONNECT 0 0 SSL Site 1 200 -     - - 
2015.2.24 15:55:01 - 127.0.0.1 https://domain.tld:443 *DENIED* Certificate supplied by server was not valid: unable to get local issuer certificate CONNECT 0 0 SSL Site 1 200 -     - -

(The certificate is not equal to the CN (Apache VHOST) - the DENIED is correct!)

Thank you!
Klaus.

**Comment by fredbcode** [comment]
You said it works with 3.1.2 ? 

"Provided MITM is restricted to Google sites by using the onlymitmsslgrey option"
http://e2guardian.org/cms/index.php/news/10-e2guardian-interim-development-release-v3-1-2

I will try to understand ...

**Comment by fredbcode** [comment]
Ok I pushed some modifications, now the values are initialised at start and the brace is fixed
Quickly tested with https://linuxfr.org/ and IE:

sslseparatelists = on
sslmitm = on
sslcertcheck = off
onlymitmsslgrey = off

I checked that the website is not in a list (totally unknown from e2 point of view)

Result: The website appears in log and in my browser with my "false" certificate
Same result with https://www.123-reg.co.uk

PS: With FF 35 I have some troubles but maybe there is something wrong with my browser ...

**Comment by Django-BOfH** [comment]
O.K. I've build a new rpm, you'll find it here: 
http://repo.mailserver.guru/7/testing/x86_64/repoview/e2guardian.html

direct link: 
http://repo.mailserver.guru/7/testing/x86_64/Packages/e2guardian-3.3.0-3.el7.centos.x86_64.rpm

@tachtler GO GO GO!!! ;)

**Comment by tachtler** [comment]
Hi,

o.k. - tomorror - we'll see, if we can do it tomorror afternoon?

Thank you for the heavy work on it!
Klaus.

**Comment by tachtler** [comment]
So, back in business!

We tried the latest **development-branch** version,

#it works !!

Tested with: Konqueror 4.10.5 (CentOS -7)
Tested with: Firefox ESR 31.4.0 (CentOS -7)

Our configuration files, with **only the changes we made**:

**/etc/e2guardian/e2guardian.conf**
originalip = off
sslcertificatepath = '/etc/pki/tls'
cacertificatepath = '/etc/pki/e2guardian/certs/my_rootCA.crt'
caprivatekeypath = '/etc/pki/e2guardian/private/private_root.pem'
certprivatekeypath = '/etc/pki/e2guardian/private/private_cert.pem'
generatedcertpath = '/tmp/generatedcerts'
generatedlinkpath = '/tmp/generatedlinks

**/etc/e2guardian/e2gaurdianf2.conf**
sslseparatelists = on
sslmitm = on

Thank you for your great work!
Klaus.

**Comment by fredbcode** [comment]
Ok great, no issue with FF ?

A tittle advice about: 

generatedcertpath = '/tmp/generatedcerts'
generatedlinkpath = '/tmp/generatedlinks

In production you should use another path to avoid certificate regeneration (after reboot)

**Comment by tachtler** [comment]
Hi,

yes, no issue with Firefox! But it's a Linux ESR Version, maybe in future I will test with Firefox and IE under Windows too.

Yes, 

generatedcertpath = '/tmp/generatedcerts'
generatedlinkpath = '/tmp/generatedlinks

only for testing purpose.

We thought about to place it under /var/cache? Which path did you prefer **and** is there a **automatic delete mechanism**, to keep an eye on the used space for the certificate stored with MITM?

Thank you,
Klaus.

**Comment by fredbcode** [comment]
Yes /var/cache seems good, I don't know about delete mechanism you can post a question at Philip (He wrote the SSLMITM code) in forum.

Ok I close the bug, now we should discuss in forum. 

Thanks for your tests
