### ISSUE TITLE
Add Server Name to Block Page

### ISSUE THREAD

**Issue by dkwiebe** [e2guardian/e2guardian#560]
I'd be glad to sponsor this enhancement.  We'd like to be able to access a server name variable in the block templates.  That will help us track where unblock requests are coming from.

**Comment by fredbcode** [comment]
Good idea, yes
I will take a look

**Comment by fredbcode** [comment]
Ok new option added in v5.4.dev

servername in e2guardian.conf or hostane is used
In block page you can now add -SERVERNAME- tag
