### ISSUE TITLE
dstats.log topando HTTPWQ

### ISSUE THREAD

**Issue by GabrielLonghi** [e2guardian/e2guardian#563]
Boa tarde, estou com o seguinte problema! Quando conecta mais de 450~500 usuários no e2guardian ele começa a topar a aba BUSY, independente de quantos workers eu coloco ele chega ao topo!! Vi que o @marcelloc já passou por algo parecido nesta publicação (https://github.com/e2guardian/e2guardian/issues/362) Muito obrigado a todos pela atenção! 
![WhatsApp Image 2019-12-05 at 22 02 49 (1)](https://user-images.githubusercontent.com/58576986/70339452-9f188280-182d-11ea-8707-94348bc2e24f.jpeg)
![WhatsApp Image 2019-12-05 at 22 02 49](https://user-images.githubusercontent.com/58576986/70339453-9f188280-182d-11ea-81a9-73bd60a4f41f.jpeg)

**Comment by fredbcode** [comment]
In English language please

**Comment by GabrielLonghi** [comment]
Good afternoon. I'm having the following problem here: when I try to connect more than 450~500 users in the e2guardian it starts growing to the top the tab "BUSY". Doesn't matter how many workers I put on it, it still get to the top!! I noticed that @marcelloc already pass thought something like that in this publication https://github.com/e2guardian/e2guardian/issues/362 Thanks very much  for your attention!
