### ISSUE TITLE
在pfsense 上使用无法登陆钉钉

### ISSUE THREAD

**Issue by YuJunping** [e2guardian/e2guardian#564]
在pfsense 上开启e2guardian proxy，钉钉客户端提示网络异常，有人知道怎么解决么

**Comment by mveplus** [comment]
您好 @YuJunping 获得一般支持 [googlegroups](https://groups.google.com/forum/#!forum/e2guardian )。不好意思，这看 #21，这里使开发者问题。

**Comment by fredbcode** [comment]
English language please
