### ISSUE TITLE
Segfault when no write permission on generated certs directory

### ISSUE THREAD

**Issue by justinrdonnelly** [e2guardian/e2guardian#565]
Hi,
When running in MITM mode, E2Guardian will segfault when the e2guardian user does not have write permission to the generated certs directory.  An initial request will hang indefinitely, and a second request results in a segfault.  Clearly, incorrect permissions is a user error.  The [wiki](https://github.com/e2guardian/e2guardian/wiki/MITM---Filtering-HTTPS) states the "directory must be writable by the e2guardian user".  But it seems that this user error could be handled better.  I have reproduced this on v3.4.0.3-2  from the Ubuntu 18.04 repo, v5.3.3-1 from the Ubuntu 19.10 repo, and v5.2 (I got other errors running v5.3) built from source on Ubuntu 18.04.  This issue is made more likely when a user is running E2Guardian in a docker container due to differences between file ownership on the host and in the container.  Below is a simple test case to reproduce the issue.

1. Install E2Guardian, but do not start (if started automatically, stop).
2. Configure MITM.
```
# enable MITM
sed -i "s/^sslmitm.*$/sslmitm = on/" /etc/e2guardian/e2guardianf1.conf &&
sed -i "s/^enablessl.*$/enablessl = on/" /etc/e2guardian/e2guardian.conf &&

# uncomment cert paths
sed -i "s/^#cacertificatepath/cacertificatepath/;s/#caprivatekeypath/caprivatekeypath/;s/#certprivatekeypath/certprivatekeypath/;s/#generatedcertpath/generatedcertpath/" /etc/e2guardian/e2guardian.conf &&

# workaround openssl issue? https://github.com/openssl/openssl/issues/7754
sed -i "s/^RANDFILE\s*=\s*\\\$ENV/#RANDFILE = \$ENV/" /etc/ssl/openssl.cnf &&

# generate certs
cert_dir="/home/e2/e2install/" &&
mkdir --parents "${cert_dir}generatedcerts" &&
openssl genrsa 4096 > "${cert_dir}ca.key" &&
openssl req -subj "/C=US" -new -x509 -days 3650 -key "${cert_dir}ca.key" -out "${cert_dir}ca.pem" &&
openssl genrsa 4096 > "${cert_dir}cert.key" &&
chown --recursive e2guardian:e2guardian /home/e2 &&

echo "configuration updated"
```
3. Start E2Guardian.
4. Confirm correct behavior with correct configuration.
`https_proxy=http://localhost:8080 wget --no-check-certificate https://google.com`
5. Remove the generated certificates.
`rm -rf /home/e2/e2install/generatedcerts/*`
6. Remove write permission on the generated certs directory.
`chmod 000 /home/e2/e2install/generatedcerts/`
7. Attempt to view https site.
`https_proxy=http://localhost:8080 wget --no-check-certificate https://google.com`
8. The request hangs.  Kill that request and try again.
`https_proxy=http://localhost:8080 wget --no-check-certificate https://google.com`
9. E2Guardian segfaults.

Expected result: An error is logged and the block page is returned on all requests.
Actual result: For the first request an error is logged, and the request hangs.  For the second request E2Guardian segfaults.

Relevant lines from syslog:
```
Dec 20 20:07:37 ubuntu1804 e2guardian[2398]: hw0: error creating certificate sub-directory: /home/e2/e2install/generatedcerts//BD/D0/EB/
Dec 20 20:07:49 ubuntu1804 kernel: [  170.844291] e2guardian[2401]: segfault at 230 ip 000055b665f2d6b5 sp 00007f11b48f48d0 error 4 in e2guardian[55b665ec9000+fb000]
```

**Comment by fredbcode** [comment]
Hum, you change the permissions after starting (steep 3), it's very complex to take care at such behaviour for each file used by e2, step 5 is also not a good practice with e2guardian running 

You confirm that there no segfault with step 6 before starting ?

**Comment by justinrdonnelly** [comment]
There may be some confusion around the test case.  Maybe I should have broken it into two tests.  I wanted to show correct behavior first, then incorrect (or maybe just undesired) behavior.  E2Guardian will segfault even if the permissions are changed prior to starting.  A simplified test case is below.

1. Install E2Guardian, but do not start (if started automatically, stop).
2. Configure MITM.
```
# enable MITM
sed -i "s/^sslmitm.*$/sslmitm = on/" /etc/e2guardian/e2guardianf1.conf &&
sed -i "s/^enablessl.*$/enablessl = on/" /etc/e2guardian/e2guardian.conf &&

# uncomment cert paths
sed -i "s/^#cacertificatepath/cacertificatepath/;s/#caprivatekeypath/caprivatekeypath/;s/#certprivatekeypath/certprivatekeypath/;s/#generatedcertpath/generatedcertpath/" /etc/e2guardian/e2guardian.conf &&

# workaround openssl issue? https://github.com/openssl/openssl/issues/7754
sed -i "s/^RANDFILE\s*=\s*\\\$ENV/#RANDFILE = \$ENV/" /etc/ssl/openssl.cnf &&

# generate certs
cert_dir="/home/e2/e2install/" &&
mkdir --parents "${cert_dir}generatedcerts" &&
openssl genrsa 4096 > "${cert_dir}ca.key" &&
openssl req -subj "/C=US" -new -x509 -days 3650 -key "${cert_dir}ca.key" -out "${cert_dir}ca.pem" &&
openssl genrsa 4096 > "${cert_dir}cert.key" &&
chown --recursive e2guardian:e2guardian /home/e2 &&

echo "configuration updated"
```
3. Remove write permission on the generated certs directory.
`chmod 000 /home/e2/e2install/generatedcerts/`
4. Start E2Guardian.
5. Attempt to view https site.
`https_proxy=http://localhost:8080 wget --no-check-certificate https://google.com`
6. The request hangs.  Kill that request and try again.
`https_proxy=http://localhost:8080 wget --no-check-certificate https://google.com`
7. E2Guardian segfaults.

**Comment by fredbcode** [comment]
Please make a try with 5.3.dev ,18.04 package here https://gitlab.com/fredbcode/e2guardian/tree/packages

**Comment by justinrdonnelly** [comment]
This seems to work.  I downloaded and installed [e2ubuntu_bionic_V5.3.3_20200107.deb](https://gitlab.com/fredbcode/e2guardian/blob/packages/v5.3.dev/e2ubuntu_bionic_V5.3.3_20200107.deb).  When I ran the test I got the following results:
1. The page was successfully returned.
2. I see the following in syslog:
```
Jan  8 09:48:42 ubuntu1804 e2guardian[3383]: hw2: error creating certificate sub-directory: /home/e2/e2install/generatedcerts//BD/D0/EB/
Jan  8 09:48:42 ubuntu1804 e2guardian[3383]: Couldn't save certificate to on disk cache
Jan  8 09:48:42 ubuntu1804 e2guardian[3383]: hw0: error creating certificate sub-directory: /home/e2/e2install/generatedcerts//E7/68/28/
Jan  8 09:48:42 ubuntu1804 e2guardian[3383]: Couldn't save certificate to on disk cache
```
I confirmed that E2Guardian is still filtering content.  So it appears that the cert is generated and used, but not saved to disk cache.  This is probably the best way to handle this case.  Thanks so much for fixing this!
