### ISSUE TITLE
Strange behavior of https filtering between Debian 9 and Debian 10

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#568]
Hi,

Since I use E2guardian 5.3.3 on Debian 10, I have lot of SSL errors like this:

Failed to nogotiate ssl connection to server - 0 0 SSL SITE 2 403

I put mitmcheckcert = off in e2guardianfx.conf, but the problem is still here.

This problem appears with these websites for example:
https://www.wcc0.orange-business.com/
https://vmrest.viamichelin.com/

On Debian 9 with same config files, the problem is not present.

So, is there a workaround to avoid this problem or is it a problem with openssl?

Thank you
Anthony

**Comment by Anthony-76** [comment]
In addition to my last message, I just installed the e2debian_buster_V_20200107.deb package and the problem is still here.

**Comment by fredbcode** [comment]
Which directory exactly ? https://gitlab.com/fredbcode/e2guardian/tree/packages/

Can you try with the v5.3.dev branch, please ?

**Comment by Anthony-76** [comment]
HI @fredbcode 

I tried this:

https://gitlab.com/fredbcode/e2guardian/tree/packages/v5.3.dev

the following package :


e2debian_buster_V_20200107.deb | Commit debian v5.3.dev Package | 19 hours ago
-- | -- | --

Do you want really that I try with the v5.3.dev branch? 

Moreover, this issue appears since DEbain 10. With Debian 9 there is no problem with the websites in my example.

Thank you
Anthony

**Comment by fredbcode** [comment]
No it's already what you did, this package is auto generated from this 
branch

**Comment by Anthony-76** [comment]
If you want I can deploy 2 VM (If you want to test and take a traces)?
one with Debian 9 and the other one with Debian10?

**Comment by fredbcode** [comment]
Tested with exactly the same e2guardian version on both ?
Why you think this is related to os and not e2 ?

Le 8 janvier 2020 17:15:17 GMT+01:00, Anthony-76 <notifications@github.com> a écrit :
>If you want I can deploy 2 VM (If you want to test and take a traces)?
>one with Debian 9 and the other one with Debian10?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/568#issuecomment-572142302

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Anthony-76** [comment]
So it's the same E2guardian release: 5.3.3 with the following configure:

e2guardian 5.3.3

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'


I use the same config files.

The only change is the Debain release and packages such as libssl etc...

**Comment by Anthony-76** [comment]
Maybe is a start answer: 
I found something in openssl configuration


**On Debian 9**

curl -v https://www.wcc0.orange-business.com
* Rebuilt URL to: https://www.wcc0.orange-business.com/
*   Trying 80.12.17.139...
* TCP_NODELAY set
* Connected to www.wcc0.orange-business.com (80.12.17.139) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=FR; L=Paris; O=Orange; OU=Orange France; CN=www.wcc0.orange-business.com
*  start date: Apr 23 00:00:00 2019 GMT
*  expire date: Jun 11 12:00:00 2020 GMT
*  subjectAltName: host "www.wcc0.orange-business.com" matched cert's "www.wcc0.orange-business.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: www.wcc0.orange-business.com
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 302 D▒plac▒ Temporairement
< Date: Wed, 08 Jan 2020 19:53:06 GMT
< Set-Cookie: JSESSIONID=AC8EE64B47E5116CEBE23F09421E6859; Path=/; Secure
< Location: https://www.wcc0.orange-business.com/jamc
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
<
* Curl_http_done: called premature == 0
* Connection #0 to host www.wcc0.orange-business.com left intact




**On Debian 10**

 curl -v https://www.wcc0.orange-business.com
* Expire in 0 ms for 6 (transfer 0x55b431ec6f50)
[...........]
* Expire in 5 ms for 1 (transfer 0x55b431ec6f50)
*   Trying 80.12.17.139...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55b431ec6f50)
* Connected to www.wcc0.orange-business.com (80.12.17.139) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
* Closing connection 0
**curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small**


This result is related to this bug in Debian

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788

After remove the CipherString = DEFAULT@SECLEVEL=2 in openssl.conf


Maybe this workaround will be helpfull for others people.

I don't know if it's possible to do something on E2guardian in the future release in order to passthrough https flow if E2guardian detect ssl error?


Anthony

**Comment by fredbcode** [comment]
Yes good idea, there is something like this in squid.
Thank you for the report

Ps: Are you working for OBS (France ?)

Le 8 janvier 2020 21:03:52 GMT+01:00, Anthony-76 <notifications@github.com> a écrit :
>Maybe is a start answer: >
>I found something in openssl configuration>
>>
>>
>**On Debian 9**>
>>
>curl -v https://www.wcc0.orange-business.com>
>* Rebuilt URL to: https://www.wcc0.orange-business.com/>
>*   Trying 80.12.17.139...>
>* TCP_NODELAY set>
>* Connected to www.wcc0.orange-business.com (80.12.17.139) port 443
>(#0)>
>* ALPN, offering h2>
>* ALPN, offering http/1.1>
>* Cipher selection:
>ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH>
>* successfully set certificate verify locations:>
>*   CAfile: /etc/ssl/certs/ca-certificates.crt>
>  CApath: /etc/ssl/certs>
>* TLSv1.2 (OUT), TLS header, Certificate Status (22):>
>* TLSv1.2 (OUT), TLS handshake, Client hello (1):>
>* TLSv1.2 (IN), TLS handshake, Server hello (2):>
>* TLSv1.2 (IN), TLS handshake, Certificate (11):>
>* TLSv1.2 (IN), TLS handshake, Server key exchange (12):>
>* TLSv1.2 (IN), TLS handshake, Server finished (14):>
>* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):>
>* TLSv1.2 (OUT), TLS change cipher, Client hello (1):>
>* TLSv1.2 (OUT), TLS handshake, Finished (20):>
>* TLSv1.2 (IN), TLS change cipher, Client hello (1):>
>* TLSv1.2 (IN), TLS handshake, Finished (20):>
>* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384>
>* ALPN, server did not agree to a protocol>
>* Server certificate:>
>*  subject: C=FR; L=Paris; O=Orange; OU=Orange France;
>CN=www.wcc0.orange-business.com>
>*  start date: Apr 23 00:00:00 2019 GMT>
>*  expire date: Jun 11 12:00:00 2020 GMT>
>*  subjectAltName: host "www.wcc0.orange-business.com" matched cert's
>"www.wcc0.orange-business.com">
>*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA>
>*  SSL certificate verify ok.>
>> GET / HTTP/1.1>
>> Host: www.wcc0.orange-business.com>
>> User-Agent: curl/7.52.1>
>> Accept: */*>
>>>
>< HTTP/1.1 302 D▒plac▒ Temporairement>
>< Date: Wed, 08 Jan 2020 19:53:06 GMT>
>< Set-Cookie: JSESSIONID=AC8EE64B47E5116CEBE23F09421E6859; Path=/;
>Secure>
>< Location: https://www.wcc0.orange-business.com/jamc>
>< Content-Type: text/html; charset=UTF-8>
>< Content-Length: 0>
><>
>* Curl_http_done: called premature == 0>
>* Connection #0 to host www.wcc0.orange-business.com left intact>
>>
>>
>>
>>
>**On Debian 10**>
>>
> curl -v https://www.wcc0.orange-business.com>
>* Expire in 0 ms for 6 (transfer 0x55b431ec6f50)>
>[...........]>
>* Expire in 5 ms for 1 (transfer 0x55b431ec6f50)>
>*   Trying 80.12.17.139...>
>* TCP_NODELAY set>
>* Expire in 200 ms for 4 (transfer 0x55b431ec6f50)>
>* Connected to www.wcc0.orange-business.com (80.12.17.139) port 443
>(#0)>
>* ALPN, offering h2>
>* ALPN, offering http/1.1>
>* successfully set certificate verify locations:>
>*   CAfile: none>
>  CApath: /etc/ssl/certs>
>* TLSv1.3 (OUT), TLS handshake, Client hello (1):>
>* TLSv1.3 (IN), TLS handshake, Server hello (2):>
>* TLSv1.2 (IN), TLS handshake, Certificate (11):>
>* TLSv1.2 (IN), TLS handshake, Server key exchange (12):>
>* TLSv1.2 (OUT), TLS alert, handshake failure (552):>
>* error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small>
>* Closing connection 0>
>**curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too
>small**>
>>
>>
>This result is related to this bug in Debian>
>>
>https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788>
>>
>After remove the CipherString = DEFAULT@SECLEVEL=2 in openssl.conf>
>>
>>
>Maybe this workaround will be helpfull for others people.>
>>
>I don't know if it's possible to make something on E2guardin in the
>future release in order to passthrough https flow if E2guardian detect
>ssl error?>
>>
>>
>Anthony>
>>
>>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/e2guardian/e2guardian/issues/568#issuecomment-572233613

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=www.wcc0.orange%2dbusiness.com&latest

Yes, weak DH key exchange

Le 8 janvier 2020 21:03:52 GMT+01:00, Anthony-76 <notifications@github.com> a écrit :
>Maybe is a start answer: >
>I found something in openssl configuration>
>>
>>
>**On Debian 9**>
>>
>curl -v https://www.wcc0.orange-business.com>
>* Rebuilt URL to: https://www.wcc0.orange-business.com/>
>*   Trying 80.12.17.139...>
>* TCP_NODELAY set>
>* Connected to www.wcc0.orange-business.com (80.12.17.139) port 443
>(#0)>
>* ALPN, offering h2>
>* ALPN, offering http/1.1>
>* Cipher selection:
>ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH>
>* successfully set certificate verify locations:>
>*   CAfile: /etc/ssl/certs/ca-certificates.crt>
>  CApath: /etc/ssl/certs>
>* TLSv1.2 (OUT), TLS header, Certificate Status (22):>
>* TLSv1.2 (OUT), TLS handshake, Client hello (1):>
>* TLSv1.2 (IN), TLS handshake, Server hello (2):>
>* TLSv1.2 (IN), TLS handshake, Certificate (11):>
>* TLSv1.2 (IN), TLS handshake, Server key exchange (12):>
>* TLSv1.2 (IN), TLS handshake, Server finished (14):>
>* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):>
>* TLSv1.2 (OUT), TLS change cipher, Client hello (1):>
>* TLSv1.2 (OUT), TLS handshake, Finished (20):>
>* TLSv1.2 (IN), TLS change cipher, Client hello (1):>
>* TLSv1.2 (IN), TLS handshake, Finished (20):>
>* SSL connection using TLSv1.2 / DHE-RSA-AES256-GCM-SHA384>
>* ALPN, server did not agree to a protocol>
>* Server certificate:>
>*  subject: C=FR; L=Paris; O=Orange; OU=Orange France;
>CN=www.wcc0.orange-business.com>
>*  start date: Apr 23 00:00:00 2019 GMT>
>*  expire date: Jun 11 12:00:00 2020 GMT>
>*  subjectAltName: host "www.wcc0.orange-business.com" matched cert's
>"www.wcc0.orange-business.com">
>*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA>
>*  SSL certificate verify ok.>
>> GET / HTTP/1.1>
>> Host: www.wcc0.orange-business.com>
>> User-Agent: curl/7.52.1>
>> Accept: */*>
>>>
>< HTTP/1.1 302 D▒plac▒ Temporairement>
>< Date: Wed, 08 Jan 2020 19:53:06 GMT>
>< Set-Cookie: JSESSIONID=AC8EE64B47E5116CEBE23F09421E6859; Path=/;
>Secure>
>< Location: https://www.wcc0.orange-business.com/jamc>
>< Content-Type: text/html; charset=UTF-8>
>< Content-Length: 0>
><>
>* Curl_http_done: called premature == 0>
>* Connection #0 to host www.wcc0.orange-business.com left intact>
>>
>>
>>
>>
>**On Debian 10**>
>>
> curl -v https://www.wcc0.orange-business.com>
>* Expire in 0 ms for 6 (transfer 0x55b431ec6f50)>
>[...........]>
>* Expire in 5 ms for 1 (transfer 0x55b431ec6f50)>
>*   Trying 80.12.17.139...>
>* TCP_NODELAY set>
>* Expire in 200 ms for 4 (transfer 0x55b431ec6f50)>
>* Connected to www.wcc0.orange-business.com (80.12.17.139) port 443
>(#0)>
>* ALPN, offering h2>
>* ALPN, offering http/1.1>
>* successfully set certificate verify locations:>
>*   CAfile: none>
>  CApath: /etc/ssl/certs>
>* TLSv1.3 (OUT), TLS handshake, Client hello (1):>
>* TLSv1.3 (IN), TLS handshake, Server hello (2):>
>* TLSv1.2 (IN), TLS handshake, Certificate (11):>
>* TLSv1.2 (IN), TLS handshake, Server key exchange (12):>
>* TLSv1.2 (OUT), TLS alert, handshake failure (552):>
>* error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small>
>* Closing connection 0>
>**curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too
>small**>
>>
>>
>This result is related to this bug in Debian>
>>
>https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907788>
>>
>After remove the CipherString = DEFAULT@SECLEVEL=2 in openssl.conf>
>>
>>
>Maybe this workaround will be helpfull for others people.>
>>
>I don't know if it's possible to make something on E2guardin in the
>future release in order to passthrough https flow if E2guardian detect
>ssl error?>
>>
>>
>Anthony>
>>
>>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/e2guardian/e2guardian/issues/568#issuecomment-572233613

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Anthony-76** [comment]
No I don't work at OBS.
I work in France in a litle and dynamic company in Normandy.... I know, i'm not "Breton" :)

**Comment by Anthony-76** [comment]
Just for information, since I remove the CipherString = DEFAULT@SECLEVEL=2 in openssl.conf **AND** I add also in  [system_default_sect] section
**tls-cipher "DEFAULT:@SECLEVEL=1"**


I have no ssl error.
Now, eveything works fine

**Comment by philipianpearce** [comment]
The above reference from commit 41ca9d6 to issue #568 is wrong it should refer to issue #566 and not to this issue.
