### ISSUE TITLE
e2guardian alone - forwardedfor

### ISSUE THREAD

**Issue by Open-wan** [e2guardian/e2guardian#582]
Hello,

I use e2guardian 5.3.4 in explicit mode (without squid) on a debian buster.

Client IP --> explicit proxy e2guardian --> firewall for log and sso auth or captive portal --> internet

I would like to keep the client's IP address on my firewall.
Is it possible without squid? 
Not working via forwardedfor option.

Thank you.

**Comment by philipianpearce** [comment]
The forwardedfor option is only useful if you are using an upstream web proxy (such as squid) which can analyse the data for you. 

It can not be done at the IP level as the source ip and the return IP address has to be the e2g system. 

Some proxy systems (e.g. squid) when in transparent proxy mode can preserve the source IP of the client, but can only do this when run on the same host as the gateway. e2g does not currently natively support this mode (which could only ever work with transparent filtering on the same system as the firewall). 

I'm not quite sure from your post as to what you are trying to achieve, but I would suggest a config such as the following may work - 

Client IP(with explicit proxy) --> firewall for log and sso auth or captive portal (but no NAT) --> e2g in DMZ > NAT --> internet. 

If you are using captive portal then client has to go there first to get access to the network. 

Of course all these (except for client) could be on just one system. 

Philip 

----- Original Message -----

**Comment by Open-wan** [comment]
Thank you Philip.
I tried this, works fine.
Slowness during ramp-ups (several hundred users - CPU / RAM / IO ok).
httpworker at 7500 with explicit proxy (no clamAV or SSL decrypt).
need to test different settings.

Best regards
