### ISSUE TITLE
Failed to start e2guardian service

### ISSUE THREAD

**Issue by hbtechnologia** [e2guardian/e2guardian#583]
CentOS 7
Linux  3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

****Followed(Installation From Source):****
 https://github.com/e2guardian/e2guardian/wiki/Installation-From-Source

but stuck at 

**Get it running**
At this point you have a working binary, but without a few more touches it won't actually start. Per settings above, e2g has been configured to run as the user e2guardian. If the user is absent on your system e2g won't start. How to create a new user is beyond the scope of this doc, but be sure to do so or change the config options above and recompile.

I have added user e2guardian using 
# useradd e2guardian 
but its still  not working...

**Comment by hbtechnologia** [comment]
Support will be highly appreciated.

**Comment by hbtechnologia** [comment]
[root@squidanalyzer e2guardian]# systemctl  start e2guardian
Failed to start e2guardian.service: Unit not found.

**Comment by fredbcode** [comment]
What do you have in syslog or message ?

Le 14 février 2020 20:12:49 GMT+01:00, HB Technologia <notifications@github.com> a écrit :
>[root@squidanalyzer e2guardian]# systemctl  start e2guardian
>Failed to start e2guardian.service: Unit not found.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/583#issuecomment-586429026

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by hbtechnologia** [comment]
Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error reading /etc/e2guardian/lists/domainsnobypass. Check directory and file permissions. They should be 640 and 750: No such file or direct
Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error reading file /etc/e2guardian/lists/domainsnobypass: No such file or directory
Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error opening bannedbypass
Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error reading file /etc/e2guardian/lists/domainsnobypass: No such file or directory
Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error opening bannedbypass
Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Unable to read /etc/e2guardian/lists/domainsnobypass
Feb 20 16:48:21 localhost.localdomain polkitd[698]: Unregistered Authentication Agent for unix-process:9632:1954143 (system bus name :1.58, object path /org/freedesktop/PolicyKit1/AuthenticationAge
Feb 20 16:48:21 localhost.localdomain systemd[1]: Started E2guardian Web filtering.

**Comment by fredbcode** [comment]
Ok, so just add the missing files

And change permissions

chown -rf e2guardian /etc/e2guardian

Le 20 février 2020 22:49:01 GMT+01:00, HB Technologia <notifications@github.com> a écrit :
>Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error reading
>/etc/e2guardian/lists/domainsnobypass. Check directory and file
>permissions. They should be 640 and 750: No such file or direct
>Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error reading
>file /etc/e2guardian/lists/domainsnobypass: No such file or directory
>Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error opening
>bannedbypass
>Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error reading
>file /etc/e2guardian/lists/domainsnobypass: No such file or directory
>Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Error opening
>bannedbypass
>Feb 20 16:48:21 localhost.localdomain e2guardian[9638]: Unable to read
>/etc/e2guardian/lists/domainsnobypass
>Feb 20 16:48:21 localhost.localdomain polkitd[698]: Unregistered
>Authentication Agent for unix-process:9632:1954143 (system bus name
>:1.58, object path /org/freedesktop/PolicyKit1/AuthenticationAge
>Feb 20 16:48:21 localhost.localdomain systemd[1]: Started E2guardian
>Web filtering.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/583#issuecomment-589336023

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by hbtechnologia** [comment]
I have commented the line in e2guardian.conf because it is not needed yet and it worked.
but  i have  a issue banned phrases are not working..

i have pasted these strings in file  : /etc/e2guardian/lists/bannedphraselist

e.g: 
<Ticket>,<Quality>,<Tenders>,<Welcome>

**Comment by hbtechnologia** [comment]
can  you share complete guide link or any file for filtering content and other ?

**Comment by fredbcode** [comment]
With https, sslmitm is needed.
I guess there is no bug here (GitHub tickets is only for bugs), please ask questions to the Google groups

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by hbtechnologia** [comment]
Thanks
