### ISSUE TITLE
Trouble With Bypass Using MITM - Verson 5.3.4

### ISSUE THREAD

**Issue by wiltdu** [e2guardian/e2guardian#585]
Hoping somebody can offer a little help or guidance.  As the subject line says I can't seem to get the bypass to work w/ version 5.3.4, I have MITM enabled.

I was using it with an older version of 5 and my pi died and I setup a new pi with it on with 5.3.4 and it doesn't seem to work as before.

Built with:  '--prefix=' '--enable-sslmitm=yes' '--enable-icap=yes' '--enable-orig-ip' '--enable-pcre=yes' '--with-proxygroup=e2guardian' '--with-proxyuser=e2guardian'

Normally I have e2guardianf1.conf configured thusly:

bypass=300
bypasskey='MyMagicKey'
bypassversion = 1
cgibypass = 'off'

and I would set the template.html  to send the "acknowledge" click to a php page that would allow them to select a duration and type a password.  If the password matches the correct bypasskey then they are allowed to proceed and I'd calculate the hash like this:

$unixtimekey = time() + $duration;
$hash = strtoupper(md5($url . $magic . $ip . $unixtimekey));
$hash .= $unixtimekey;

That quit working on this version.  I tried many things including the following change after reading the cgibypass notes including amidst them the following:

bypassversion = 2
cgibypass = 'on'
accessdeniedaddress = 'http://192.168.1.10/nonsession/test.php'

Wth this modification e2guardian wouldn't even redirect to that new page to play with it, it still just brought up the template.html page  so I gave up that approach.

So I tried just setting the default that should enable the default acknowledge button:

bypass=300
bypasskey=''
bypassversion = 1
cgibypass = 'off'

Used the original  template.html with bypass instead of my modified one and that default acknowledge button also won't work either.  The URL clearly show a GBYPASS hash in it, but still loads just the denied page.

Any help would be appreciated, thanks.

**Comment by bmuel** [comment]
I can confirm that issue and did some debugging. There seem to be 2 issues. One in redirect and one in hashing.
Attached is a version of ConnectionHandler.cpp with which I could get bypass working reliably again
[ConnectionHandler.txt](https://github.com/e2guardian/e2guardian/files/4345292/ConnectionHandler.txt)

**Comment by wiltdu** [comment]
Thank you for taking a look at that.  I did try copying the ConnectionHandler.txt to ConnectionHandler.cpp and recompiled with that.  Afterward it still didn't work I'm afraid.  I even just set it to the following and used the default -GBYPASS- acknowledge link in the template and had no success:

bypass=300
bypasskey=''
bypassversion = 1
cgibypass = 'off'

I'm just trying https://www.proxysite.com/ to test the bypass.   This is with version 5.3.4, does that match with your testing?

**Comment by bmuel** [comment]
Hi wiltdu. Thanks for your feedback. At my end, the ConnectionHandler.txt version works with the following parameters:

bypass = 300
bypassversion = 2
cgibypass = 'off'
bypasskey = ''

and the default acknowlege link on the default pag

**Comment by wiltdu** [comment]
Yup, works with bypassversion=2, but doesn't work with my own hash generation like it used to.  I used to calculate the hash with:
$unixtimekey = time() + $duration;
$hash = strtoupper(md5($url . $magic . $ip . $unixtimekey));

is there a new format I'd have to use, something like the following maybe?
$hash = strtoupper(md5($url . $ip . $user. $magic . $unixtimekey));

Thanks for the help:)

**Comment by philipianpearce** [comment]
See https://github.com/e2guardian/e2guardian/blob/v5.3/notes/cgi_bypass for how to generate the new v2 hash. 
----- Original Message -----

**Comment by bmuel** [comment]
@philipianpearce: I think there is still something wrong in bypass v5.3.4 and later. Could you do a diff on ConnectionHandler.cpp and my ConnectionHandler.txt at the top? Maybe there is something useful for feature versions

**Comment by philipianpearce** [comment]
@bmuel  Thanks for your fixes - I have incorporated in v5.3.dev and v5.4.dev
