### ISSUE TITLE
Access log: date-time not shown for log format=5 or 6

### ISSUE THREAD

**Issue by rdpmc** [e2guardian/e2guardian#596]
Access log: date-time not shown for log format=5 or 6.

 builtline = 'utime' ... Instead of 'when' in FatController.cpp

**Comment by fredbcode** [comment]
In this format timestamp is used, do you have a blank field ?

**Comment by philipianpearce** [comment]
Log formats 5, 6, 7 and 8 use unix timestamp for ease of sorting and report handling.

This is by design and not a bug.

See new wiki page for more details of fields [Access-Log-File-Format](https://github.com/e2guardian/e2guardian/wiki/Access-Log-File-Format)
