### ISSUE TITLE
v5.4 raspbian will not start

### ISSUE THREAD

**Issue by trimm54** [e2guardian/e2guardian#601]
New to this somewhat.  I have a Raspberry Pi 4.  Trying to install e2guardian using the 5.4 pre-release (
e2raspbian_buster_v5.4_20200427.deb). The version shows 5.3.3 though...?

e2guardian does not start, fails.  I have not changed any lists or config files.  Versions and status shown below.  Does not run on reboot or manual start/stop.  Any suggestions?

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@raspberrypi:/home/pi# 

||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  e2guardian     5.3.3        armhf        Web content filtering

pi@raspberrypi:~/Downloads $ systemctl status e2guardian.service
● e2guardian.service - E2guardian Web filtering
   Loaded: loaded (/lib/systemd/system/e2guardian.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-05-05 18:01:52 EDT; 1min 43s ago

May 05 18:01:52 raspberrypi e2guardian[1904]: SB warning: Defined list urllist:refererexception is not referenced in the storyboard /etc/e2guardian/examplef1.story
May 05 18:01:52 raspberrypi e2guardian[1904]: Required storyboard entry function 'checklogging' is missing
May 05 18:01:52 raspberrypi e2guardian[1904]: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
May 05 18:01:52 raspberrypi e2guardian[1904]: Error in reading filter group files
May 05 18:01:52 raspberrypi e2guardian[1904]: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
May 05 18:01:52 raspberrypi e2guardian[1904]: Error reading filter group conf file(s).
May 05 18:01:52 raspberrypi e2guardian[1904]: Error reading filter group conf file(s).
May 05 18:01:52 raspberrypi systemd[1]: e2guardian.service: Control process exited, code=exited, status=1/FAILURE
May 05 18:01:52 raspberrypi systemd[1]: e2guardian.service: Failed with result 'exit-code'.
May 05 18:01:52 raspberrypi systemd[1]: Failed to start E2guardian Web filtering.

**Comment by fredbcode** [comment]
Please try apt remove e2guardian --purge

And 

Install this package: https://e2guardian.numsys.eu/v5.4.dev/e2raspbian_buster_v5.4.dev_20200507.deb

**Comment by trimm54** [comment]
Trying to download now but site link fails.  Is the site down?

**Comment by trimm54** [comment]
Just downloaded.  Thx.

**Comment by trimm54** [comment]
After installing and updating dependencies, same issue.  Any other information I can get you?

pi@raspberrypi:~/Downloads $ sudo apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libevent-core-2.1-6 libevent-pthreads-2.1-6
The following NEW packages will be installed:
  libevent-core-2.1-6 libevent-pthreads-2.1-6
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/165 kB of archives.
After this operation, 345 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package libevent-core-2.1-6:armhf.
(Reading database ... 158941 files and directories currently installed.)
Preparing to unpack .../libevent-core-2.1-6_2.1.8-stable-4_armhf.deb ...
Unpacking libevent-core-2.1-6:armhf (2.1.8-stable-4) ...
Selecting previously unselected package libevent-pthreads-2.1-6:armhf.
Preparing to unpack .../libevent-pthreads-2.1-6_2.1.8-stable-4_armhf.deb ...
Unpacking libevent-pthreads-2.1-6:armhf (2.1.8-stable-4) ...
Setting up libevent-core-2.1-6:armhf (2.1.8-stable-4) ...
Setting up libevent-pthreads-2.1-6:armhf (2.1.8-stable-4) ...
Setting up e2guardian (5.3.3) ...
Adding system user `e2guardian' (UID 111) ...
Adding new group `e2guardian' (GID 115) ...
Adding new user `e2guardian' (UID 111) with group `e2guardian' ...
Creating home directory `/var/log/e2guardian' ...

Job for e2guardian.service failed because the control process exited with error code.
See "systemctl status e2guardian.service" and "journalctl -xe" for details.
invoke-rc.d: initscript e2guardian, action "restart" failed.
● e2guardian.service - E2guardian Web filtering
   Loaded: loaded (/lib/systemd/system/e2guardian.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-05-07 07:59:16 EDT; 24ms ago
  Process: 1874 ExecStart=/usr/sbin/e2guardian (code=exited, status=1/FAILURE)

May 07 07:59:16 raspberrypi e2guardian[1874]: SB warning: Defined list urllist:refererexception is not referenced in the storyboard /etc/e2guardian/examplef1.story
May 07 07:59:16 raspberrypi e2guardian[1874]: Required storyboard entry function 'checklogging' is missing
May 07 07:59:16 raspberrypi e2guardian[1874]: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
May 07 07:59:16 raspberrypi e2guardian[1874]: Error in reading filter group files
May 07 07:59:16 raspberrypi e2guardian[1874]: Error reading filter group conf file(s).
May 07 07:59:16 raspberrypi e2guardian[1874]: Error opening filter group config: /etc/e2guardian/e2guardianf1.conf
May 07 07:59:16 raspberrypi e2guardian[1874]: Error reading filter group conf file(s).
May 07 07:59:16 raspberrypi systemd[1]: e2guardian.service: Control process exited, code=exited, status=1/FAILURE
May 07 07:59:16 raspberrypi systemd[1]: e2guardian.service: Failed with result 'exit-code'.
May 07 07:59:16 raspberrypi systemd[1]: Failed to start E2guardian Web filtering.
WARNING: Starting e2guardian failed. Please check your configuration.
Synchronizing state of e2guardian.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable e2guardian
Job for e2guardian.service failed because the control process exited with error code.
See "systemctl status e2guardian.service" and "journalctl -xe" for details.
WARNING: Starting e2guardian failed. Please check your configuration.
Processing triggers for libc-bin (2.28-10+rpi1) ...
Processing triggers for systemd (241-7~deb10u3+rpi1) ...

**Comment by fredbcode** [comment]
Please try (generated): https://e2guardian.numsys.eu/v5.4.dev/e2raspbian_buster_v5.4.dev_20200507.deb

**Comment by trimm54** [comment]
Success!  Thank you fredb!

**Comment by trimm54** [comment]
Package was successful.  

● e2guardian.service - E2guardian Web filtering
   Loaded: loaded (/lib/systemd/system/e2guardian.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Thu 2020-05-07 10:21:44 EDT; 6s ago

May 07 10:21:44 raspberrypi systemd[1]: Starting E2guardian Web filtering...
May 07 10:21:44 raspberrypi e2guardian[1859]: SB warning: Undefined list /etc/e2guardian/examplef1.story list nolog used at line 285 of /etc/e2guardian/common.story
May 07 10:21:44 raspberrypi systemd[1]: Started E2guardian Web filtering.
May 07 10:21:44 raspberrypi systemd[1]: e2guardian.service: Succeeded.
