### ISSUE TITLE
Blanket Block mode: exception lists should not override banned lists

### ISSUE THREAD

**Issue by ghost** [e2guardian/e2guardian#604]
When in **Blanket Block** mode, _exception_ lists should not be able to override _banned_ lists.

Say I want to allow _all_ of a domain, _except_ a subdomain, or a url within that domain.

It's not currently possible to do it. For example:

I put _google.com_ in _exceptionsitelist_. How can I block a url within that domain, say _google.com/search_?

Is not this a limitation in e2guardian? And does not it make the banned lists redundant in Blanket Block mode?

**Comment by KDGundermann** [comment]
mmh, and what should we do, if we want to BLOCK all of the domain and only allow google.com/search ?

**Comment by philipianpearce** [comment]
@elyoas 

Banned lists are (and always have been) redundant in blanket block mode - 
Blanket block means block everything (or *) that is NOT in exception or grey lists.

Putting any site in the site exception list means that, it is an EXCEPTION to url filtering and content inspection, and it will NOT be MITM or interfered with in any way.

It should be possible to do what you want using exceptionregexpurllist. You just need to work out a regexp which matches google.com urls except google.com/search.

**Comment by philipianpearce** [comment]
@KDGundermann 

That is a lot easier, as block is done last.   Add google.com/search to exceptionurllist (or to greyurllist if you want search terms and result content-checked) and add add google.com to blockedsitelist.

**Comment by philipianpearce** [comment]
@elyoas 

Due to the way https sites have to be processed, it is simply not possible to 'fix' this in the way you suggest.

With https a decision has to be made on whether to let the site through and whether to MITM (in order t do url and content inspection) when all the info e2guardian has the site name.   So it is impossible to block a url within a domain and allow the domain as an exception.
