### ISSUE TITLE
FD_SETSIZE change needed for Linux

### ISSUE THREAD

**Issue by fredbcode** [e2guardian/e2guardian#61]
Actually to increase maxchildren beyond the usual value a change in system file still needed 
- Increase FD_SETSIZE -

The point is in FatController.cpp (at least a point ...), the result is related to FD_SETSIZE beyond the return is -1

if (socketpair(AF_UNIX, SOCK_STREAM, 0, sv) < 0)

**Comment by philipianpearce** [comment]
Fixed in V4.0
