### ISSUE TITLE
v5.4 add listdir configuration in e2guardianfn.conf files to allow use of relative list paths

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#610]
v5.4 add 'change list pwd' configuration in e2guardianfn.conf files to allow use of relative list paths.   This is to simplify customization and upgrading of e2g. Likely to be implemented using a generic '.define' directive (similar to #define in C++).

Move example list files used by e2guardianf1.conf into a lists/f1.example subdirectory and re-organise sample configs to use .Include<....>

**Comment by KDGundermann** [comment]
Why another configuration option and not just .Include<> relative to the current file (e.g. Same directory) ? I‘ve done this for conf files with only 7 lines added today.

**Comment by philipianpearce** [comment]
HI Klaus, 

Happy to add this auto relative path that you suggest. 

Would you send me a patch just for that bit? 

But it does not address the use cases that I am looking at which is to do with list files. 

These are the bulk of the cases where it is needed in order to improve ease of configuration and the reduction in duplication in similar configs in e2guardianfn.conf. So the .Pwd feature is designed for templating both conf and master listfiles, which are not likely to be in the current .conf file path. For example, with your relative path patch added:- 

In config /etc/e2g/e2guardianf1.conf:- 

.Pwd</etc/e2g/lists/f1/> # specific to fg1 

.Include<./lists_template.conf> # expands to /etc/e2g/./lists_template.conf 

In lists_template.conf:- 

sitelist = 'name=block, path=__PWD__blocksitelist' 

#path expands to /etc/e2g/lists/f1/blocksitelist 

This will enable the simplification of the e2guardianf1.conf files so that they are easy to configure with just the 
config directives that vary between filtergroups configured in the top level file together with relevant .Includes of templates etc. for the bulk. 

This is why in the code the variable is called list_pwd not just pwd. 

I will add examples and notes on this over the next few days. 

Regards 

Philip 

----- Original Message -----

**Comment by KDGundermann** [comment]
Hi Philip,
give me 1-2 days and I will prepare some suggestions. But first I would try to conclude the work on Logger.

Regards,
Klaus

**Comment by philipianpearce** [comment]
Hi Klaus, 

It's OK, I don't now need a relative path patch as I have coded for it for all .Include cases (.conf, lists and storys) and will push this to v5.4.dev later today. 

On reflection the .Pwd<> directive is a bit confusing so I will be changing it to .Define __PWD__<> t make it clear what it does which is similar to C #define. Thanks for highlighting this. 

Thanks, 
Philip 

----- Original Message -----

**Comment by philipianpearce** [comment]
Variable name changed from PWD to LISTDIR as this better reflects it's purpose.

**Comment by philipianpearce** [comment]
Implemented in v5.4.dev and v5.5.dev
