### ISSUE TITLE
Opinion: Make e2guardian easier to configure

### ISSUE THREAD

**Issue by KDGundermann** [e2guardian/e2guardian#615]
When using e2guardian for the first time, you have to read (and understand) a lot of config files:
- e2guardian.conf and e2guardianf1.conf with 1.300+ lines
- preauth.story, common.story, site.story, f1.story with about 450 lines

That would be fine if you are a pro and would like to configure every detail of the software,
but as a beginner I would like to have it as easy as possible, install the software and start,
lets say with an empty config file (e.g. all lines commented out) and then only add minimial
config to change it to your needs.

So I will try to tell you my userstory and then propose some steps to make the configuration easier:

As a User, I would like to
- install the software
- with an empty config file
- and block every access to any site
- and the only allow access to on specific site 
- and as this site displays images hosted on cloudfront.net
  allow access to .png files on cloudfront.net

Step 1 : Install software 
- easy, either use your OS package manager or follow the instructions in the INSTALL document.

Step 2 : start with an empty config
- e2guardian complains about a missing value for 'proxytimeout' (eeh, I'm not using a proxy, only e2guardian, why should I use a proxytimeout ?)
- e2guardian complains about a missing value for 'pcontimeout' (WTF ?!?)

to be continued...

**Comment by KDGundermann** [comment]
Proposal for Step2:
use sensible defaults in the software, document them in the config files but let them commented out.
So every non-commented line is a config option changed by the user on purpose.

**Comment by KDGundermann** [comment]
Step 3 : block every site

for blocking a site I have to understand how the algorithm of e2guardian works.  (yes I know its buried in the *.story files, but thats way to complex for e beginner to understand)
I have also looked on the old dansguardian sites, but couldn't find a high level explanation (please correct me if there is one !)

If I would write an explanation of the algorithm, I would write:

There are three concepts:
- Phases
- Classifications
- Lists

**1. Phases**
before a client can get any data from a webserver there are several phases e2guardian is running through.
The most commonly used are:
- Check-Authentication: is the client allowed to use e2guardian?
- Check-Request: is the request of the client is allowed to be forwarded to the server
- Check-Response: is the answer of the server is allowed to return to the client
- Check-Content: is the content of the answer is allowed to return to the client (e.g. virus free)
- Check-Logging: should this request send to the logging system
( there could be some more. e.g. Check-MITM , and Check-Direct,.. )

**2. Classification**
every Request/Response/Content is classified to be either:
- Whitelisted (exception)
- Greylisted ( further checks has to be done ), may add "Naughty" points
- Blacklisted (banned)

**3. Lists**
for determining the Classification, there are several lists which could be used : 
- (DNS) Sitelist : DNS Names of Clients/Servers
- (IP) Sitelist: IP Adresses of Client Servers
- URL's : Complete URLS of requests
- Times: Allowed/Blocked timslots
- RegExp (Header) : regular Expressions working on the header information of a request/response
- RegExp (Content) : regular Expressions working on the content of a request/response 
- Fileextensions
- Mimetypes
- Phrases : Words searched in the content of a resonse
- Search : Matching on the search expressions used in web search sites

**Algorithm:**
So a simple (pseudo) code for the algorithm would be:
```
For every Phase in (Authentication, ,Request, Response, Content, Logging)  
    For every List in (DNS, IP, URL, .... ) {  
      If it is in an exception List -> Set Exception  
      If it is in a grey list -> Add Naughty Points and proceed with next list  
      If it is in a banned list -> Set Banned  
    }  
    if ( IsException or Naughty Points <= Threshhold )  
      Execute Action of this phase and proceed to next phase  
    else if ( IsBanned or Naughty Points > Threshhold )
      Block this Request and send an error message to the client  
  }  
```

So back to my User story, for blocking every request to ever site, I know I have to look at the request phase for a banned list for DNS or IP Sites. So maybe there is a directory structure `./check-requests/banned/dns-sites.list`
So I would like to add '*' to the `dns-sites.list` file to block all requests..

**Comment by KDGundermann** [comment]
Step 4 : allow access to on specific site

that's now an easy one, 
add e.g. e2guardian.org to `./check-requests/exception/dns-sites.list`

**Comment by KDGundermann** [comment]
Step 5 : allow access to .png files on cloudfront.net

ok, that's now two conditions: 
add 'cloudfront.net' to `./check-requests/grey/dns-sites.list` (so it will continue to check more conditions..) 
and '.png' to `./check-requests/exception/file-extensions.list`

**Comment by KDGundermann** [comment]
Oh, my boss wants to access all banking websites and the sales department should be allowed to access all .com and .org websites (but with virus scanning and phrase checking filter of course)

Step 6 : add additional groups
there is an option 'filtergroups' in e2guardian.conf, I change it to '3' and restart e2guardian.
Previously there was a folder named "group1" which I use before. Now e2guardian created 2 new folders "group2" and "group3" with a predefined subfolder structure.
To give it a better name for logs, I rename it to "group2-CEO" and "group3-Sales" ( or maybe I drop a file "groupname" in this folder with a content of "CEO" or "Sales")
As we have now more groups we have to determine which client belongs to which group by authenticate the client.
Our CEO uses a PC with name "Boss-PC". So I write the DNS Name "boss-pc.intern.mycompany.org" ( or maybe only "boss-pc") in the `./group2/authenticate/dns.list`file.
The Sales department has all its PCs in then 192.168.90.0/24 subnet so I add this to the file `./group3/authenticate/ip.list`

Step 6: allow the Boss to access his banking URLs
we are matching against the URL of the request, so we add some entries to the file `./group2-CEO/requests/exception/url.list` e.g. "www.banking.com/online-banking/"

Step 7 : allow Sales to access .com and .org sites
Easy: just add to `./group3-Sales/request/exception/dns-sites.list`

Step 8: content check the responses
We will use the files `./group3-Sales/content/banned/phrases.list` or `./group3-Sales/content/grey/phrases.list`
As e2guardian deliviers some predefined lists (or we may download some lists from the internet( we will include this lists in our definitions.
E.g the file `./group3-Sales/content/banned/phrases.list` will have:
```
.include<$base/lists/phraselists/nudism/*>
.include<$base/lists/phraselists/violence/*>
```
to completly block sites with this phrases.

While the file `./group3-Sales/content/grey/phrases.list`will have all phrase lists (except travel related):
```
!naughtynesslimit = 50
.include<$base/lists/phraselists/*>
.exclude<$base/lists/phraselists/travel/*>
```
but only will block when the naughtynesslimit of 50 is reached

**Comment by philipianpearce** [comment]
> Proposal for Step2:
> use sensible defaults in the software, document them in the config files but let them commented out.
> So every non-commented line is a config option changed by the user on purpose.

There are only a few items that do not already conform to this. There are some very few exceptions where 0 is used as a value and we do not want this to be the default so these will have to remain for the moment.   And others that need a default added - can be done largely in v5.4

**Comment by langfield** [comment]
It is very surprising to me that this issue was closed. As a new user with a fair amount of networking experience, it is still a mystery to me how I would accomplish this workflow beyond Step 3:

> As a User, I would like to
> 
> * install the software
> * with an empty config file
> * and block every access to any site
> * and the only allow access to on specific site
> * and as this site displays images hosted on cloudfront.net
>   allow access to .png files on cloudfront.net

I would love to hear an explanation of how a new user is supposed to figure out how to actually **create** an exception via storyboarding as hinted at below in `exceptionsitelist`:
```
# NOTE: From v5 Blanket exceptions are now implemented using Storyboarding
```

This makes it sound like this file is completely ignored in v5, and I still can't figure out if that's the case. As a naive user, I want to (1) block some sites, and (2) allow some sites. What on earth is *storyboarding* and how am I supposed to know how that plays in to the most basic use case for this tool? If you search for "storyboarding" in the repo, there are 0 results in the Wiki.
