### ISSUE TITLE
V5.4 IP authentication issue in ICAP mode

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#616]
I can confirm this bug as well.  Tried putting my machine into a specific filter group and it always came up as the default group.  I downgraded to 5.3.4 and it is working as expected again.

_Originally posted by @ccoager in https://github.com/e2guardian/e2guardian/issues/599#issuecomment-655223263_

**Comment by philipianpearce** [comment]
https://github.com/e2guardian/e2guardian/issues/599#issuecomment-657596922

**Comment by philipianpearce** [comment]
https://github.com/e2guardian/e2guardian/issues/599#issuecomment-657917607

**Comment by philipianpearce** [comment]
@ccoager    Thanks, your config looks fine.    I have done a visual check of the code (compared to v5.3) and have not been able to see the problem.   

I don't have an icap test rig, so would you run a test with  storyboardtrace = on and send me the result?  

Thanks,
Philip

**Comment by ccoager** [comment]
@philipianpearce Here is the log you requested.
[616.zip](https://github.com/e2guardian/e2guardian/files/4921224/616.zip)

**Comment by philipianpearce** [comment]
@ccoager OK, that is useful, but does not contain the storyboard trace, which should be in syslog.

**Comment by ccoager** [comment]
"Output goes to syslog (or stderr in debug mode)" - This is either a bug or the documentation is wrong.  I was using stderr but the storyboard trace didn't get logged.  I had to run syslog to capture this.  Try this.
[616-2.zip](https://github.com/e2guardian/e2guardian/files/4929119/616-2.zip)

**Comment by philipianpearce** [comment]
@ccoager Thanks,  With the SB trace I think I have found the problem.  Please try latest v5.4.dev and let me know if it is now OK.  If not please send another trace.

"Output goes to syslog (or stderr in debug mode)" - This is either a bug or the documentation is wrong.   

The documentation was correct when this was written (prior to the introduction of the the 'new' debug config entries) as it refers to compiling with the debug option on.   But is now very confusing!!

I'm in the process of re-organizing and correcting the e2guardian.conf.in and am making this comment and the limited extent of the debug options in e2guardian.conf clearer!  I should have this pushed to v5.4.dev next week.

**Comment by fredbcode** [comment]
Hi Philip,

FI: I'm seeing that the ci/cd test is broken.

https://gitlab.com/fredbcode/e2guardian/-/pipelines

So there is no package for testing purpose now


Le 16 juillet 2020 18:00:03 GMT+02:00, Philip Pearce <notifications@github.com> a écrit :
>@ccoager Thanks,  With the SB trace I think I have found the problem. 
>Please try latest v5.4.dev and let me know if it is now OK.  If not
>please send another trace.
>
>"Output goes to syslog (or stderr in debug mode)" - This is either a
>bug or the documentation is wrong.   
>
>The documentation was correct when this was written (prior to the
>introduction of the the 'new' debug config entries) as it refers to
>compiling with the debug option on.   But is now very confusing!!
>
>I'm in the process of re-organizing and correcting the
>e2guardian.conf.in and am making this comment and the limited extent of
>the debug options in e2guardian.conf clearer!  I should have this
>pushed to v5.4.dev next week.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/e2guardian/e2guardian/issues/616#issuecomment-659507649

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by philipianpearce** [comment]
Fred, 

Thanks for letting me know. I will fix. 

Philip 
----- Original Message -----

> From: "Fredb" <notifications@github.com>
> To: "e2guardian/e2guardian" <e2guardian@noreply.github.com>
> Cc: "Philip Pearce" <philip.pearce@e2bn.org>, "Assign"
> <assign@noreply.github.com>
> Sent: Thursday, 16 July, 2020 7:04:46 PM
> Subject: Re: [e2guardian/e2guardian] V5.4 IP authentication issue in
> ICAP mode (#616)

> Hi Philip,

> FI: I'm seeing that the ci/cd test is broken for now.

> https://gitlab.com/fredbcode/e2guardian/-/pipelines

> So there is no package for testing purpose now

> Le 16 juillet 2020 18:00:03 GMT+02:00, Philip Pearce

**Comment by fredbcode** [comment]
Ok, there is a package for ubuntu & debian for branch "v5.4.dev" now

**Comment by philipianpearce** [comment]
@ccoager Hi, can you confirm that the fix works for you?

Can I close the issue?

**Comment by ccoager** [comment]
@philipianpearce  This is still not working with the e2ubuntu_focal_V5.4.2_20200721.deb build.
[616-3.zip](https://github.com/e2guardian/e2guardian/files/4974838/616-3.zip)

**Comment by philipianpearce** [comment]
@ccoager Hi, can you confirm that the fix works for you with latest v5.4.2?

Can I close the issue?
