### ISSUE TITLE
FD_SETSIZE and filedescriptors >1024 on FreeBSD

### ISSUE THREAD

**Issue by Alexander237** [e2guardian/e2guardian#62]
Hello.

If I compile e2guardian on FreeBSD with filedescriptors >1024, then e2guardian fails to start with error:

 Compiled with --with-filedescriptors too high
You should upgrade your FD_SETSIZE=1024
E2guardian compiled with with-filedescriptors=8192
Or reduce --with-filedescriptors=8192 under 1024

Alexander

**Comment by nerijus** [comment]
I saved a developer comment in e2guardian.conf near "maxchildren" setting
(btw, this info should probably be added to e2guardian.conf):

You can change this value here (Linux) e.g #define __FD_SETSIZE 8192
- /usr/include/bits/typesizes.h
- /usr/include/linux/posix_types.h
Before compiling/building also set ulimit:
ulimit -n 8192 (This line should be also set in the E2Guardian startup script)
And finaly add configure --with-filedescriptors=8192
Now you can set maxchildren + preforkchildren to 8188 Max (8192 - 7 (reserved by E2)

**Comment by fredbcode** [comment]
This is not a config option, but a compilation option (./configure)

@Alexander237 Do you know the way to increase FD in FreeBSD ? If yes we can add some words in the next release documentation https://github.com/e2guardian/e2guardian/blob/develop/INSTALL

**Comment by Alexander237** [comment]
To see:
% sysctl -a | grep maxfiles 

To change on the fly (till reboot): 
# sysctl -w kern.maxfiles=xxxxx 
# sysctl -w kern.maxfilesperproc=xxxxx

To set permanently (keep settings after reboot) values should be set in /etc/sysctl.conf

Default values for FreeBSD 10.1 are
kern.maxfiles: 261376
kern.maxfilesperproc: 235233

**Comment by fredbcode** [comment]
It's not exactly the same thing 
With linux and some libraries you need to edit a couple system include files to increase the FD_SETSIZE limit (in binary binary compilation)

**Comment by Alexander237** [comment]
@fredbcode I'm not an expert in programming, however I hope reference below might be usefull:
_http://www.freebsd.org/cgi/man.cgi?query=select
     The default size of FD_SETSIZE is currently 1024.	In order to accommo-
     date programs which might potentially use a larger	number of open files
     with select(), it is possible to increase this size by having the program
     define FD_SETSIZE before the inclusion of any header which	includes
     <sys/types.h>.

**Comment by Alexander237** [comment]
The solution for FreeBSD is to raise FD_SETSIZE in /usr/include/sys/select.h before preceding with e2guardian compilation (successfully tested today). I believe issue can be closed and appreciate if this note will be included in next release of documentation.

**Comment by fredbcode** [comment]
Ok done thanks

**Comment by cnighswonger** [comment]
The solution for CentOS is to raise FD_SETSIZE in /usr/include/bits/typesizes.h before proceeding with e2guardian compilation (successfully tested today). This note should be included in next release of documentation.

**Comment by fredbcode** [comment]
There is some words here https://github.com/e2guardian/e2guardian/blob/master/INSTALL (--with-filedescriptors)

**Comment by cnighswonger** [comment]
I can't tell you how many times I read over that and completely missed the reference to typesizes.h!

Thanks for all of your help!
