### ISSUE TITLE
Need automatic certificate regeneration, specify certificate lifetime

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#624]
I'm starting to look at the ramifications of Apple changing Safari to not accept SSL certificates with an expiration date greater than 398 days.  To start with I'm manually setting (and updating) generatedcertstart to be the current time and generatedcertend to be that + 398 days.  But it probably would be easier to be able to specify the cert lifetime rather than having that be hard-coded to 10 years and to be able to have e2guardian use "now" for the start time.

The next issue will be regenerating expired certificates.  I think we'll want e2g to check the expiration date and regenerate if needed.

**Comment by opoplawski** [comment]
Actually, after thinking about this some more, I don't think this will be an issue for a while longer.  Apple at the moment will only enforce for certificates issued (presumably "start time") after Sep 1, 2020.  So the default start time of 2014 should make it okay.  But this still should be addressed at some point.

**Comment by philipianpearce** [comment]
> I'm starting to look at the ramifications of Apple changing Safari to not accept SSL certificates with an expiration date greater than 398 days. To start with I'm manually setting (and updating) generatedcertstart to be the current time and generatedcertend to be that + 398 days. But it probably would be easier to be able to specify the cert lifetime rather than having that be hard-coded to 10 years and to be able to have e2guardian use "now" for the start time.

Using 'now' as start date would be problem for large systems using arrays of e2g as clients would get different certs for the same site and will object.  

A better option may be to set start_date to 1st January 00:01 of current year and lifetime to +390 days and use the start date as part of the hash to create the serial no.  This would automatically make sure that the up-to-date cert is used.  I will look at implementing this in v5.5.
> 
> The next issue will be regenerating expired certificates. I think we'll want e2g to check the expiration date and regenerate if needed.

With the suggestion above this is not required.   

It just needs the generatedcerts directory to be cleared to remove stale entries, and conserve disk space and inodes.

I would suggest this is done at least weekly.

**Comment by philipianpearce** [comment]
I have opened a separate issue to progress this #631 and so will close this one.

**Comment by opoplawski** [comment]
Is clearing out old generatedcerts items something that should be done regularly now?  I'm not exactly sure what the impact of that is.  Should this be mentioned in a readme anywhere?

**Comment by philipianpearce** [comment]
I would recommend that it is cleared weekly at a quiet time (e.g. 3am on Sunday) to conserve disk space and inodes.  Providing the start date has not changed - the cache will be re-populated quickly with all the commonly used certificates all of which will be identical to the previous ones.

**Comment by seem8** [comment]
WOW! I was struggling today for an hour because of this. All my certs in /installation/dir/etc/e2guardian/private/generatedcerts expired one month ago. All I had to do was:
- empty generatedcerts directory,
- bump generatedcertstart line in /installation/dir/etc/e2guardian/e2guardian.conf to NOW minus 1000 seconds,
- restart e2guardian.

I strongly suggest against 3am, because of daylight savings happens between 2am and 3am.

This whole mitm is pretty awesome even with this quirk. See You in 10 years minus 1000 seconds!
