### ISSUE TITLE
v5.4.2r pre2 Segfaults continuosly with commandline scan enabled

### ISSUE THREAD

**Issue by xes** [e2guardian/e2guardian#626]
e2guardian 5.4.2r pre2 build on centos8  ~100 users, MITM enabled
Enabling commandline scan, pointing to a simple script like:

--------------------------------------------------------------
#!/bin/sh
echo "$1" >> /tmp/scan.log
fileinfo=`file "$1"`
echo "$fileinfo" >> /tmp/scan.log
if echo "$fileinfo" | grep -i pdf > /dev/null
then
      cp $1 /tmp/pdf_archive/
fi
exit 0
-------------------------------------------------------------
RESULT: e2guardian segfaults continuosly every 2/5 minutes:

 e2guardian[471780]: segfault at 0 ip 00007f97593201ff sp 00007f95e07ea7d0 error 4 in libc-2.28.so[7f97592af000+1b9000]

Disabling commandline scan, e2guardian becomes stable again.

**Comment by philipianpearce** [comment]
@xes Did you have comandlinescan working in any previous e2g version?  If so which version?

**Comment by xes** [comment]
No, this is the first time i'm trying to enable commandlinescan to check pdf and office documents containing malicious code.

**Comment by philipianpearce** [comment]
This plugin uses 'fork()' which does not work well in a large multi-threaded program like e2g.    (Can cause unpredictable crashes).
On a small scale system (home user) it may work ok, but not recommended for larger scale systems.  (The more active threads, the more likely a crash is).

This the reason why we do not currently support the email option as this also uses fork().

I have added a warning comment in e2guardian.conf for this.

A future version will fix this by forking before the threads are started or having a small 'forker' non-threaded helper program which will fork on behalf of e2g.

**Comment by xes** [comment]
Since latest attacks make great use of pdf injected with code, it would be very important to find a way to discover them with "non-standard" engines.

A few examples: 
https://resources.infosecinstitute.com/analyzing-malicious-pdf/
http://blog.didierstevens.com/programs/pdf-tools/
https://sourceforge.net/p/pjscan/home/Home/

In the last months I have discovered a lot examples of pdf with javascript inside. I need a way to stop them.

Can this be managed creating a different kind of script?

Is there any temporary trick to keep e2guardian stable with commandline scan active while waiting for the 'forker' version that you described?
