### ISSUE TITLE
v5.4.dev Build error : cannot stat 'authexceptionsiteiplist': No such file or directory

### ISSUE THREAD

**Issue by KDGundermann** [e2guardian/e2guardian#629]
`
/bin/bash /e2guardian/install-sh -d /etc/e2guardian/lists/common && \
	for l in authexceptionsiteiplist authexceptioniplist authexceptionsitelist authexceptionurllist bannedclientlist bannediplist browserregexplist embededreferersiteiplist embededreferersitelist embededrefererurllist exceptionclientlist exceptioniplist nologextensionlist nologregexpurllist nologsiteiplist nologsitelist nologurllist nomitmsiteiplist nomitmsitelist searchregexplist searchexceptionregexplist README ; do \
	echo "/usr/bin/install -c -m 644 $l /etc/e2guardian/lists/common/$l"; \
	/usr/bin/install -c -m 644 $l /etc/e2guardian/lists/common/$l; \
done

/usr/bin/install -c -m 644 authexceptionsiteiplist /etc/e2guardian/lists/common/authexceptionsiteiplist
/usr/bin/install: cannot stat 'authexceptionsiteiplist': No such file or directory

/usr/bin/install -c -m 644 authexceptioniplist /etc/e2guardian/lists/common/authexceptioniplist
/usr/bin/install -c -m 644 authexceptionsitelist /etc/e2guardian/lists/common/authexceptionsitelist
/usr/bin/install -c -m 644 authexceptionurllist /etc/e2guardian/lists/common/authexceptionurllist
/usr/bin/install -c -m 644 bannedclientlist /etc/e2guardian/lists/common/bannedclientlist
/usr/bin/install -c -m 644 bannediplist /etc/e2guardian/lists/common/bannediplist
/usr/bin/install -c -m 644 browserregexplist /etc/e2guardian/lists/common/browserregexplist
/usr/bin/install -c -m 644 embededreferersiteiplist /etc/e2guardian/lists/common/embededreferersiteiplist
/usr/bin/install -c -m 644 embededreferersitelist /etc/e2guardian/lists/common/embededreferersitelist
/usr/bin/install -c -m 644 embededrefererurllist /etc/e2guardian/lists/common/embededrefererurllist
/usr/bin/install -c -m 644 exceptionclientlist /etc/e2guardian/lists/common/exceptionclientlist
/usr/bin/install -c -m 644 exceptioniplist /etc/e2guardian/lists/common/exceptioniplist
/usr/bin/install -c -m 644 nologextensionlist /etc/e2guardian/lists/common/nologextensionlist
/usr/bin/install -c -m 644 nologregexpurllist /etc/e2guardian/lists/common/nologregexpurllist
/usr/bin/install -c -m 644 nologsiteiplist /etc/e2guardian/lists/common/nologsiteiplist
/usr/bin/install -c -m 644 nologsitelist /etc/e2guardian/lists/common/nologsitelist
/usr/bin/install -c -m 644 nologurllist /etc/e2guardian/lists/common/nologurllist
/usr/bin/install -c -m 644 nomitmsiteiplist /etc/e2guardian/lists/common/nomitmsiteiplist
/usr/bin/install -c -m 644 nomitmsitelist /etc/e2guardian/lists/common/nomitmsitelist
/usr/bin/install -c -m 644 searchregexplist /etc/e2guardian/lists/common/searchregexplist
/usr/bin/install -c -m 644 searchexceptionregexplist /etc/e2guardian/lists/common/searchexceptionregexplist

/usr/bin/install -c -m 644 README /etc/e2guardian/lists/common/README
/usr/bin/install: cannot stat 'README': No such file or directory
`

I think authexceptionsiteiplist  could be remove?
Should I create a pull request 
What about the README file ?

**Comment by philipianpearce** [comment]
Should be fixed in last push of v5.4.dev
README file was missing from the git bundle.

Thanks for the info.

**Comment by KDGundermann** [comment]
Build OK !
