### ISSUE TITLE
v5.4.2r Raspbian dies soon after starting with no obvious warnings

### ISSUE THREAD

**Issue by sebtombs** [e2guardian/e2guardian#630]
Raspberry Pi 3b+ running Raspbian Buster with latest updates. No GUI - command line interface only.

Configured as a wireless AP per the Raspberry Pi foundation instructions. Working as a wireless AP (clients access Internet via it as expected).

Downloaded https://e2guardian.numsys.eu/v5.4/e2raspbian_buster_V5.4.2r_20200812.deb using wget and installed using dpkg -i.

Originally missing libevent_pthread and libtommath1 dependencies but resolved these.

e2guardian service status says it is inactive. Starting manually with
```
sudo e2guardian &
```
 it terminates within a few seconds. e2guardian -q says there is no e2guardian process.
Aside: Status lines say it is version 5.3.3 but I'm presuming that's just that it hasn't been changed for production yet.

no processes with e2guardian in the name in the process list.

Proxy does not work
netstat shows no listener on port 8080

/var/log/e2guardian contains access.log created when originally installed. No content.

Is there anything else I can look at please to help work out why it is dying?

**Comment by fredbcode** [comment]
What happen without & ?

Did you try with another version from e2guardian.traceroot.fr ?
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by sebtombs** [comment]
Hi. Without the & nothing is reported to the command line. Otherwise the behaviour is the same.

I'm getting no DNS response for e2guardian.traceroot.fr

This isn't urgent for me so please don't let it mess up your Sunday evening!

**Comment by fredbcode** [comment]
Sorry e2guardian.numsys.eu of course

Can you try with e2guardian -N please
Do you have something in syslog ?

**Comment by fredbcode** [comment]
And also e2guardian --help just for testing purpose

**Comment by fredbcode** [comment]
And try this

https://e2guardian.numsys.eu/v5.4.dev/e2raspbian_buster_V5.4.3_20200902.deb

**Comment by sebtombs** [comment]
sudo e2guardian -N yields
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted

I can't see anything relevant in the system logs.

--help works OK.

I'll try 5.4.3 from the dev folder now.

**Comment by sebtombs** [comment]
sudo dpkg -r e2guardian
sudo dpkg -i e2raspbian_buster_V5.4.3_20200902.deb

same result from -N

**Comment by sebtombs** [comment]
Just wondered whether the resource issue is down to ownership.

Given the files are owned by an e2guardian user, I'm presuming that the service runs as that user.

I've therefore tried 
```
sudo su e2guardian
e2guardian -N
```
instead.

This gives me 
```
master: Error creating/opening pid file /var/run/e2guardian.pid
```

However, that's an ownership problem with the PID file. If I chown e2guardian:e2guardian the PID file first, I'm back to the resource error.

So, it looks like we're fine running it as root, and in either case it gets past line 1468 of FatController.cpp then gets a resource problem. There's 600M of free RAM, and ulimit returns "unlimited" so I'm puzzled as to what resource is unavailable.

Unless I'm missing something, we don't get as far as line 1719 of FatController.cpp as one of 1720 or 1722 should write to the syslog and that doesn't happen.

**Comment by fredbcode** [comment]
Weird, can you retry with 5.4.dev ?

But with rm -r /etc/e2guardian and also /var/run/e2guardian after uninstalling

And just start with systems

Thanks
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by sebtombs** [comment]
That doesn't quite work - dpkg decides not to recreate the configuration files when I reinstall so the service errors out on install because it can't find e2guardian.conf.

However, dpkg -P does seem to remove them and tells dpkg to recreate them when installed again.

After doing so, service still says "inactive" and same result from -N if I stop the service first.

**Comment by fredbcode** [comment]
Can you open a temporary ssh access please ?

numsys - @ - free - . - fr

Thanks

**Comment by sebtombs** [comment]
I can't do that at the moment unfortunately as the Pi is behind a firewall which doesn't give access from the Internet.

There's something strange going on with task processes I think.
If I run
```
sudo e2guardian -N; ps -agux
```
the process number given for ps is always 251 larger than that stored in /var/run/e2guardian.pid

8 of these are potentially due to sudo (repeated sudo ps -agux increment process number by 9)

Doesn't that suggest e2guardian is creating more processes than we expect? We should have 3 + number of http workers + number of server sockets shouldn't we?

Given that I can't give you SSH access at present, for which I apologise, is my best next step to build the 5.4.dev code on the Pi with debug turned on?

**Comment by fredbcode** [comment]
No one process

Maybe you have a process already running ? From a previous test ?


If you have a process, eguardian runs


I dontt understand why e2guardian -N with the latest 5.4.dev is broken


Just after a reboot do you have something running ? |e2guardian -N; ps 
-agux|

**Comment by sebtombs** [comment]
Sorry, I wasn't clear there. What I mean is the pid for ps itself is 251 larger than the one stored in the e2guardian pid file. There is never an e2guardian process visible in ps - I think it must die before ps gets to run.

```
sudo e2guardian -N; ps -agux
cat /var/run/e2guardian.pid
```
yields a PID for ps which is 251 more than the one in e2guardian.pid. 
ps itself runs as the pi user, not root

If I do
```
ps -agux
ps -agux
```
PID for ps increments by 1

Whereas if I do
```
sudo ps -agux
sudo ps -agux
```
PID for ps increments by 9

Doesn't {thread}.detach spawn a new process for the detached thread?

I've proved that it runs beyond the XXX AAAARGH! comment at line 1477 by deliberately specifying an invalid IP address in the config file. This correctly reports an error to the console and syslog.

**Comment by sebtombs** [comment]
I've used -v to get the options that were used to build e2raspbian_buster_V5.4.3_20200902.deb and am building from v5.4.dev source now with those options and --with-e2debug

Hopefully this will allow me to see where it aborts

**Comment by sebtombs** [comment]
Build seems to have worked :)

```
sudo /home/pi/e2guardian/src/e2guardian -N >& errlog
```

yields loads of debug information:

```
{lots of stuff}

master: Master thread created threads
log: log listener started
master: sig handlers done

{lots of hw{x} messages}

hw223: in  handle connection
hw223: waiting connection on http_worker_Q
what(): Resource temporarily unavailable
Aborted
```
The number after hw when it dies is not consistent - was 226 on the second attempt and 185 on the next. On one attempt, a "waiting connection" message appeared between the "what" and "Aborted" on the console.

**Comment by sebtombs** [comment]
Progress!

The debug suggested it wasn't getting past the loop which creates the http workers, so I looked for code setting o.http_workers.

This yielded the httpworkers option, so I added
```
httpworkers=20
```
to the config file. It is no longer generating an exception, and netstat shows 8080 is being listened to.

So, the question is, what is making it normally decide to create too many workers on my Pi, and is this somehow unique to me or going to affect others?

**Comment by sebtombs** [comment]
After a reboot, the service is now also working correctly with the httpworkers=20 in the config file

Aside:

I've learned something new about Linux here. If a process with PID x creates N additional threads, the next process to be created gets a PID of x + 1 + N. That's why the PID for ps was so much bigger, even though e2guardian does not create new processes for the threads. This is apparent from running ps -eLf with the working config.

**Comment by sebtombs** [comment]
OK. Looks like this may be an issue introduced in v5.4

Looking at the history of OptionContainer.cpp, it looks like the default for httpworkers was 100 but as part of the 5.4 work to remove the warning the default was changed to 500.  I can confirm that it works for me with httpworkers=100 in the config file. Maybe 500 works OK in normal Debian and Ubuntu but wasn't tested on a Pi, or was tested on a Pi4 with more memory?

On t'web there seem to be some (contested) suggestions that there is a per user limit on threads which depends on the amount of virtual memory and the default thread stack size. The workers are under the e2guardian user so would be subject to this I believe.

Perhaps Philip would be willing to comment on the change of default from 100 to 500 please? It may be the right thing to do and we just need instructions to users with less memory to set httpworkers to something smaller via the config.

**Comment by fredbcode** [comment]
Maybe it's just a package issue ...

The systemd config was specifically adapted for this issue ...

Can you post your systemd file please ?

e2guardian.service
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
I mean e2guardian -N should raise a limit
But "systemctl start e2guardian" not

**Comment by sebtombs** [comment]
Understood.

/lib/systemd/system/e2guardian.service:
```
[Unit]
Description=E2guardian Web filtering
After=network.target

[Service]
TasksMax=infinity
LimitNOFILE=65535
Type=forking
IgnoreSIGPIPE=no
GuessMainPID=no
ExecStart=/usr/sbin/e2guardian
ExecReload=/usr/sbin/e2guardian -r
UMask=027

[Install]
WantedBy=multi-user.target
```

**Comment by fredbcode** [comment]
And it works with more than 500 ?
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by sebtombs** [comment]
I've only tried 100 in the config so far, as that was the old default. I'm presuming "TasksMax" is supposed to allow more than the usual max number of threads. Will try different values in the config and restart the service each time.

**Comment by fredbcode** [comment]
Ok thanks

Maybe there is no more issue with this package and good ip entry ?
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by sebtombs** [comment]
200 works but 300 and 500 don't. It looks like TasksMax=Infinity is not working for some reason.

**Comment by sebtombs** [comment]
Hmm. This is all a bit strange.
```
sudo systemctl show -p TasksMax e2guardian
```
yields infinity, so it is being picked up correctly. From other parameters, it looks like infinity may be the default anyway. I'm going to try 20000 (the max allowed when parsing the config file).

**Comment by sebtombs** [comment]
TasksMax doesn't seem to change the thread limit. With TasksMax=20000, httpworkers=200 in the config works but httpworkers=300 does not.

**Comment by sebtombs** [comment]
Unless, of course, the resource we run out of when having more workers is not threads but something else ....

**Comment by sebtombs** [comment]
.. which is actually supported by what status is saying. With httpworkers=200 in the config file and TasksMax=20000
```
sudo systemctl status e2guardian
```
reports
```
Tasks: 203 (limit 20000)
```

With TasksMax removed from the .service file, the limit on my Pi is 2065.

**Comment by fredbcode** [comment]
Maybe I should add an ulimit option right before the compilation ?

https://github.com/e2guardian/e2guardian/blob/v5.4.dev/gitlabci/raspbianbuster.yml


Can you try this, ulimit -s unlimited , compilation, and try to run in the same shell (or at least a shell with ulimit -s unlimited and this binary)

**Comment by sebtombs** [comment]
Another option seems to be StackLIMITSoft in the .service file. If I add 
```
StackLIMIT=infinity:infinity
```
 then it works for httpworkers=300, 400 and 500, and the default of it not being in the config. 
StackLIMIT itself appears to be infinity by default but StackLIMITSoft is not.

**Comment by fredbcode** [comment]
Great ! I will add this 
I keep you in touch this week

The latest package still with 5.3.3 tag ?

Thanks

**Comment by sebtombs** [comment]
I think the 5.3.3 was only visible in 5.42r - can't see it now in the 5.4.3 dev; so that's already resolved.

Thanks to you too :)

**Comment by fredbcode** [comment]
Gitlab-ci is now updated, can you try the latest v5.4.dev package, please ?

**Comment by sebtombs** [comment]
Sorry - entirely my fault this. Typo in my post above which means the updated service file doesn't parse properly.

Should be 
```
LimitSTACK=infinity:infinity
```

My apologies.

I have spotted a 5.3.3 being displayed in the latest package though - appears when running dpkg -i

**Comment by fredbcode** [comment]
Ok new package will be generated, you can follow the process here

https://gitlab.com/fredbcode/e2guardian/-/pipelines

**Comment by sebtombs** [comment]
Many thanks.

I have confirmed that the new dev package fixes the issue (but still says 5.3.3 in dpkg).

**Comment by fredbcode** [comment]
> I have confirmed that the new dev package fixes the issue (but still 
> says 5.3.3 in dpkg).
>
I pushed a change, Fixed now ?

**Comment by sebtombs** [comment]
Yes thanks - now says 5.4.3

**Comment by fredbcode** [comment]
New gitlab pushed on 5.4.dev, 5.5.dev,  5.4

@sebtombs Many thanks for your help
