### ISSUE TITLE
v5.4 bannedtimelist possibly not working - generates error message on first reload but not subsequent ones

### ISSUE THREAD

**Issue by sebtombs** [e2guardian/e2guardian#632]
I believe bannedtimelist is a new group feature in v5.4.

If I uncomment the example configuration and reload the service then I get "Time Tag End Hour over bounds." in syslog. This seems to be the case whatever change I make to the time ranges.

However, if I reload again without changing the file, I don't get the warning (I suspect it only reloads the file if it has changed).

The error message is the same as that which I get if I put two #time directives in bannedsitelist, so could it be that bannedtimelist is actually only allowing one entry despite the example?

**Comment by philipianpearce** [comment]
The issue appears to be with the example(s) given - 24 is not a valid hour - it should read 23 59 instead of 24 0

I will correct this and add a note that the numbers are 0 based.

**Comment by sebtombs** [comment]
Thanks

It also appears that the double spaces used in the example to get the columns to line up cause issues - the second line was causing me to get the same error message when I changed the ending time to 15 30, but what seemed to be happening was that the 30 was being parsed as a day number due to a double space earlier in the line. Making all white-space a single space seems to have fixed it (in that I no longer get the error) but I need to wait until later in the day to confirm it has been read correctly.

**Comment by philipianpearce** [comment]
I have put a fix for this in v5.4.dev - double spaces are now treated as a single space.
