### ISSUE TITLE
v5.3 Squid + e2 icap mode and username

### ISSUE THREAD

**Issue by puppetmaster** [e2guardian/e2guardian#644]
We have a "moderation" mode filter to warn user is about to enter a filtered site but provides a link to bypass and consult anyway.
The thing is, this mode won't work any more with version 5.3.

To do so, we ave a filtering policy and we affect it by user, by adding lines to a filtergroupslist, like 
```
john=filter2
```
With this version the user is never redirected to the "moderation" template with the bypass but always blocked. 
The information page provided by e2 provides 2 informations, the username and the IP addr. In our case the username is allways empty.

I think in icap mode the username is never used by e2guardian.

My squid is configured to send the IP and the username.

**Comment by fredbcode** [comment]
I personally tested this case with success (without NTLM), how did you manage HTTPS websites in moderation list before ?
