### ISSUE TITLE
Big filtergroupslist crashes e2guardian - 5.4.dev

### ISSUE THREAD

**Issue by shrimpgo** [e2guardian/e2guardian#646]
Hi, folks!

I've testing `5.4.dev` version, trying to use with new configuration mode. Everything is working well since then, except filtergroupslist. By inserting a few users into list, works fine, but when I insert a lot of users into it, gives me *Segmentation fault* (both reload or restart action). My list has 1077 lines (or users) and I thought that bug was related with some not human-readable character, but I noticed that filtergroupslist had a limit: 16 users set. Above this, it crashes.

I didn't test another version yet.

Thanks

**Comment by philipianpearce** [comment]
I have posted a possible fix to latest v5.4.dev.

Please try and let me know if it fixes the problem.

Philip

**Comment by shrimpgo** [comment]
Sorry, Philip, but it didn't work... Same result *Segmentation fault*.

**Comment by philipianpearce** [comment]
OK, just to check:- 

When does it crash on start-up/restart or on first request? 

Crashes when filtergroupslist has more than 16 entries? 

What auth plugin are you using? 

I will try on my test rig and see if I can replicate. 

Philip 
----- Original Message -----

**Comment by philipianpearce** [comment]
I have replicated and have fixed the problem in latest v5.4.dev, which was due to error in sort operator definitions.

Many thanks for reporting this issue.

Regards
Philip

**Comment by shrimpgo** [comment]
@philipianpearce I've tested the latest version v5.4.dev and now it works like a charm. Thanks for the fix and sorry for took so long to test again.
