### ISSUE TITLE
How can I block all traffic to a filtered group?

### ISSUE THREAD

**Issue by yuriang85** [e2guardian/e2guardian#647]
I need to block all traffic to a filtered group of users. for example.
In dansguardian using bannedurllist and bannedsitelist with '**' or '** s'.
Please someone who can help me.

**Comment by philipianpearce** [comment]
See  https://github.com/e2guardian/e2guardian/blob/v5.4/configs/examplef1.story.in

Also #21

**Comment by papoteur-mga** [comment]
> See https://github.com/e2guardian/e2guardian/blob/v5.4.dev/configs/examplef1.story.in
> 
> Also #21

Both links are broken.

**Comment by philipianpearce** [comment]
> > See https://github.com/e2guardian/e2guardian/blob/v5.4.dev/configs/examplef1.story.in
> > Also #21
> 
> Both links are broken.

Thanks for letting us know.

The first link is now out of date as it referred to the version current at the time of posting.

See  https://github.com/e2guardian/e2guardian/blob/v5.5/configs/examplef1.story.in for current information.

The #21 is not broken.
