### ISSUE TITLE
e2guardian / squid / auth bypass

### ISSUE THREAD

**Issue by alb-coder** [e2guardian/e2guardian#651]
Hi,

I'm using e2guardian in front of squid + NTLM Auth. Works fine so far.

When I make certain websites accessible without user/pass (acl in squid)
e2 denies access without showing a username in the error page. Logfile
shows "*DENIED* Proxy authentication error".

Versions: e2guardian 5.3.4 and squid 4.13

**Comment by philipianpearce** [comment]
This is just one of the problems with NTLM auth with e2g in front of squid.  

Suggest you use squid in front of e2g with latest version v5.4.  See https://github.com/e2guardian/e2guardian/issues/638#issuecomment-720418584
