### ISSUE TITLE
Add httpS and redirect all http to httpS

### ISSUE THREAD

**Issue by Neustradamus** [e2guardian/e2guardian#655]
The website is not secure:
- http://e2guardian.org/
- http://www.e2guardian.org/

Can you add:
- https://e2guardian.org/

And add all automatic page redirections:
- http://e2guardian.org/ -> https://e2guardian.org/
- http://www.e2guardian.org/ -> https://e2guardian.org/
- https://www.e2guardian.org/ -> https://e2guardian.org/

Note: https://dropwww.com/

**Comment by philipianpearce** [comment]
Thanks for this - I'll ask the support team who look after the hosting of our sites to look at this.

This is not a e2g development issue. So closed.

**Comment by Neustradamus** [comment]
Dear @e2guardian team, @philipianpearce,

I wish you a Happy New Year 2025!

Can you reopen this ticket, it has not been solved.

Thanks in advance.
