### ISSUE TITLE
refererexceptionsitelist - not working in 5.4.2r

### ISSUE THREAD

**Issue by mcgrete** [e2guardian/e2guardian#656]
Hi.

I am using e2g v5.4.2r (e2ubuntu_focal_V5.4.2r_20201023.deb), Lbuntu 20.04; I have made only minor edits of default storyboards & lists, using default group.

I have found an earlier issue that is identical to my issue, which apparently was resolved: #493.  Unfortunately, I can not demonstrate success with 5.4.2r.  I examined the default (new after install) common.story file and it has the recommended insertion of code proposed as an interim fix without needing to re-compile the source. The issue is now marked as fixed.

I have successfully used a timed blanket block with exceptions, using a blanket block for SSL with exceptions, and using simultaneously a timed blanket block and a blanket block for SSL with exceptions.  I have been unsuccessful in implementing the refererexceptionsitelist while implementing either isolated or simultaneously blocking types.

If I add whatismyreferer.com to the exceptionsitelist, I can confirm that the referer site from the link to www.whatismyreferer.com in #493 is indeed "https://github.com/".  So, the sites that I am using should meet requirements for testing functionality of referers.

Perhaps it is me making some yet to be identified error/typo, or maybe there is a typo/bug introduced in development somewhere between 5.3dev and 5.4dev? Forgive if it turns out to be me...

All lists are stored in subdirectory /etc/e2guardian/example.group

**examplef1.story**
```
# To use timed blanket block 
# define times in blankettimelist,
# uncomment the list definition for 'blankettimes' in e2guardianfn.conf,
# and uncomment the next line 
if(timein,blankettimes) return setblock

# To create blanket block for SSL 
# uncomment next line and one condition line.
function(sslcheckblanketblock)
if(true,,506) return setblock  # = **s total blanket
#if(siteisip,,507) return setblock  # = **ips ip blanket
```

**e2guardianf1.conf**
```
# NEW in v5.4 bannedtimelist - times when no access is allowed
# To activate a storyboard change is required - see examplef1.story
timelist = 'name=bannedtimes,messageno=122,path=__LISTDIR__/bannedtimelist'

# NEW in v5.4 blankettimelist - times when blanket block is applied
# To activate a storyboard change is required - see examplef1.story
timelist = 'name=blankettimes,messageno=122,path=__LISTDIR__/blankettimelist'

# refererexception lists are used to make a request an exception based on the
# Referer header.

sitelist = 'name=refererexception,messageno=620,path=__LISTDIR__/refererexceptionsitelist'
ipsitelist = 'name=refererexception,messageno=620,path=__LISTDIR__/refererexceptionsiteiplist'
urllist = 'name=refererexception,messageno=620,path=__LISTDIR__/refererexceptionurllist'
```

**blankettimelist**
```
# block AM
00 00 12 00 0123456
```

**bannedtimelist**
```
# block before 7am Mon-Sun
00 00 07 00 0123456

#block from 8pm to midnight Mon-Sun
20 00 23 59 0123456
```

**exceptionsitelist**
```
wikipedia.org
en.wikipedia.org
github.com

```

**refererexceptionsitelist**
```
# Exception referer sites
# sites which are refered to by these sites will be made exceptions
github.com
google.com
youtube.com
```

If I omitted some information or file content that you require, please point out and I will attempt to provide.

Thanks

**Comment by philipianpearce** [comment]
Are you using MITM for https sites?

Refererexception  can only work on https sites if MITM is used, as the RefererL header is an html header and thus is sent encrypted and not readable by e2g unless MITM is deployed.

**Comment by mcgrete** [comment]
Thanks Phil; got your instructions on another response to a similar post.
