### ISSUE TITLE
v5.3 MacOS 10.13 does not support sigtimedwait() 

### ISSUE THREAD

**Issue by rafalj4** [e2guardian/e2guardian#662]
The same issue like #559 occured on MacOS 10.13. Version 5.3 and  5.3.4 e2guardian is affected.
Below output from make

FatController.cpp:1751:14: error: use of undeclared identifier 'sigtimedwait'
rc = sigtimedwait(&signal_set, NULL, &timeout);
^
1 error generated.

**Comment by rafalj4** [comment]
Some information about sigtimedwait - https://www.gnu.org/software/gnulib/manual/html_node/sigtimedwait.html

**Comment by philipianpearce** [comment]
Yes, I'm aware of the info on sigtimedwait.    

I am only able to support Linux, and others support the FreeBSD version used in pfsense.   And the design aim in the development of v5 was support Linux and FreeBSD.   If anyone who is expert in MacOS development wishes to port e2g that would be great, and we would then incorporate conditional code as required. 

Ok, then can you have a look at the code, there is a preprocessor directive which caters for OpenBSD which may also work on MacOS.   If you are able to do a port to MacOS that would be great - it you can get it working with directives, then let me know the changes and I will incorporate them into the main code.

Failing that, I would recommend that use a linux port as non-linux ports do not yet have the full functionality in areas such as transparent filtering.  Using a VM system (like Multipass (ubuntu)) works great on Mac.   (I do all my development on VMs on my Mac.)

**Comment by rafalj4** [comment]
I am not a developer so I wan't be able to fix this by myself. I did simlple copy/replace of code for OpenBSD fix but with no success. Errors was generated

FatController.cpp:1750:17: error: no member named 'it_value' in 'timespec'
        timeout.it_value.tv_sec = 5;
        ~~~~~~~ ^
FatController.cpp:1751:9: error: no matching function for call to 'setitimer'
        setitimer(ITIMER_REAL, &timeout, NULL);
        ^~~~~~~~~
/usr/include/sys/time.h:201:5: note: candidate function not viable: no known conversion from 'struct timespec *' to 'const struct itimerval *' for 2nd
      argument
int     setitimer(int, const struct itimerval * __restrict,
        ^
FatController.cpp:1767:25: error: no member named 'it_value' in 'timespec'
                timeout.it_value.tv_sec = 0;
                ~~~~~~~ ^
FatController.cpp:1769:17: error: no matching function for call to 'setitimer'
                setitimer(ITIMER_REAL, &timeout, NULL);
                ^~~~~~~~~
/usr/include/sys/time.h:201:5: note: candidate function not viable: no known conversion from 'struct timespec *' to 'const struct itimerval *' for 2nd
      argument
int     setitimer(int, const struct itimerval * __restrict,

As I understand e2guardian is not building on MacOS so this section should dissapeare from INSTALL document of e2guardian.

**Comment by philipianpearce** [comment]
I will review the INSTALL document.   Thanks for reporting this!
