### ISSUE TITLE
Unable to build latest version on openwrt mips

### ISSUE THREAD

**Issue by kisisten** [e2guardian/e2guardian#663]
Hi guys, I'm unable to run configure on openwrt, please see attached config.log.
Thanks.
[config.log](https://github.com/e2guardian/e2guardian/files/5914266/config.log)

**Comment by KDGundermann** [comment]
the last message I see is:

 
    configure:5852: checking for gzdopen in -lz
    configure:5877: g++ -o conftest -g -O2   conftest.cpp -lz  -lz  >&5
    /tmp/ccCeoKEh.o: In function `main':
    /home/lamer/e2guardian-5.3/conftest.cpp:56: undefined reference to `gzdopen' 
    ....
    configure:5892: error: no zlib!

**Comment by kisisten** [comment]
On Tuesday, February 2, 2021 10:00:11 PM PST Klaus wrote:
> the last message I see is:
> 
>  
>     configure:5852: checking for gzdopen in -lz
>     configure:5877: g++ -o conftest -g -O2   conftest.cpp -lz  -lz  >&5
>     /tmp/ccCeoKEh.o: In function `main':
>     /home/lamer/e2guardian-5.3/conftest.cpp:56: undefined reference to `gzdopen' 
>     ....
>     configure:5892: error: no zlib! 
> 
> 
> 
Hi Klaus, I do have zlib packages installed:


zlib - 1.2.11-3 
zlib-dev - 1.2.11-3
autogen finishes successfully.
Am I missing some other parameters?

Thanks.

**Comment by kisisten** [comment]
On Tuesday, February 2, 2021 10:00:11 PM PST Klaus wrote:
> the last message I see is:
> 
>  
>     configure:5852: checking for gzdopen in -lz
>     configure:5877: g++ -o conftest -g -O2   conftest.cpp -lz  -lz  >&5
>     /tmp/ccCeoKEh.o: In function `main':
>     /home/lamer/e2guardian-5.3/conftest.cpp:56: undefined reference to `gzdopen' 
>     ....
>     configure:5892: error: no zlib! 
> 
> 
> 
This seems to be the way zlib is used static vs dynamic.
I was able to move a bit forward by adding "--enable-static-zlib=yes" to the configure command.
This issue can be closed.
Thank you.
