### ISSUE TITLE
Several errors but still running

### ISSUE THREAD

**Issue by brunolorente** [e2guardian/e2guardian#665]
Hi, 

First of all, I'm a newbie on e2guardian, I used to use dansguardian.

I've already installed and running e2guardian + Squid setup but several (and painful) messages are droped into syslog or journalctl on every e2guardian restart, here the journalctl -fu trace:

`feb 24 14:57:34 srv01 e2guardian[134226]: master: Stopping
feb 24 14:57:34 srv01 systemd[1]: Stopping E2guardian Web filtering...
feb 24 14:57:36 srv01 systemd[1]: e2guardian.service: Succeeded.
feb 24 14:57:36 srv01 systemd[1]: Stopped E2guardian Web filtering.
feb 24 14:57:40 srv01 systemd[1]: Starting E2guardian Web filtering...
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading '/etc/e2guardian/lists/exceptioniplist. Check directory and file permissions. They should be 640 and 750: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file '/etc/e2guardian/lists/exceptioniplist: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening exceptionclient
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/preauth.story list exceptionclient used at line 3 of /etc/e2guardian/preauth.story
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/preauth.story list exceptionclient used at line 10 of /etc/e2guardian/preauth.story
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file '/etc/e2guardian/lists/exceptioniplist: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening exceptionclient
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read '/etc/e2guardian/lists/exceptioniplist
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading . Check directory and file permissions. They should be 640 and 750: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading . Check directory and file permissions. They should be 640 and 750: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list headermods used at line 32 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list headermods used at line 73 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list bannedheader used at line 165 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading . Check directory and file permissions. They should be 640 and 750: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading . Check directory and file permissions. They should be 640 and 750: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list headermods used at line 32 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list headermods used at line 73 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list bannedheader used at line 165 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Required Listname  is not defined
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading . Check directory and file permissions. They should be 640 and 750: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading . Check directory and file permissions. They should be 640 and 750: No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error reading file : No such file or directory
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Error opening
feb 24 14:57:40 srv01 e2guardian[141954]: Unable to read
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list headermods used at line 32 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list headermods used at line 73 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 e2guardian[141954]: SB warning: Undefined list /etc/e2guardian/examplef1.story list bannedheader used at line 165 of /etc/e2guardian/common.story
feb 24 14:57:40 srv01 systemd[1]: Started E2guardian Web filtering.
feb 24 14:57:40 srv01 e2guardian[141955]: Started successfully.
`

I guess you'll need some config files in order to check them, but right now I prefer to wait untill your answer in order to avoid useless spam.

2 issues, I setup que right permisions, I swear, but the errror related with permissions still happens... about the Storyboard errors, I can't understand what is going on, I didn't edit the default files.

Thanks in advance!

**Comment by brunolorente** [comment]
ii  e2guardian     5.3.4-1      amd64        Web content filtering (Dansguardian fork)

**Comment by brunolorente** [comment]
ii  squid          4.10-1ubuntu1.2 amd64        Full featured Web Proxy cache (HTTP proxy)

**Comment by KDGundermann** [comment]
Hi Bruno,

e2guardian v5 has some "Config" files, which references to some "List" files, which do not exists on your system. e.g.:

`Error reading file '/etc/e2guardian/lists/exceptioniplist: No such file or directory `

You may either create an empty list file or remove the entry from the configfile e2guardian.conf/e2guardianf?.conf

**Comment by brunolorente** [comment]
Hi @KDGundermann, thanks for your fast reply.

These files already exists on my system, because of this i'm confused with those errors. Below, all the files under the /ect/e2guardian/lists/:

`root@srv0:/etc/e2guardian/lists# ls -lha
total 384K
drwxr-x---  6 e2guardian root 4,0K feb 25 10:00 .
drwxr-x---  8 e2guardian root 4,0K feb 25 10:00 ..
-rwxr-x---  1 e2guardian root  734 feb 15  2020 addheaderregexplist
-rwxr-x---  1 e2guardian root  166 feb 15  2020 authexceptioniplist
-rwxr-x---  1 e2guardian root  166 feb 15  2020 authexceptionsiteiplist
-rwxr-x---  1 e2guardian root   40 feb 15  2020 authexceptionsitelist
-rwxr-x---  1 e2guardian root   40 feb 15  2020 authexceptionurllist
drwxr-x---  2 e2guardian root 4,0K feb 25 10:00 authplugins
-rwxr-x---  1 e2guardian root  133 feb 15  2020 bannedclientlist
-rwxr-x---  1 e2guardian root 4,9K feb 15  2020 bannedextensionlist
-rwxr-x---  1 e2guardian root  227 feb 15  2020 bannediplist
-rwxr-x---  1 e2guardian root  284 feb 15  2020 bannedmimetypelist
-rw-r--r--  1 root       root 1,3K feb 25 10:00 bannedphraselist
-rwxr-x---  1 e2guardian root  321 feb 15  2020 bannedregexpheaderlist
-rw-r--r--  1 root       root 5,4K feb 25 10:00 bannedregexpurllist
-rwxr-x---  1 e2guardian root  292 feb 15  2020 bannedregexpuseragentlist
drwxr-x---  2 e2guardian root 4,0K dic 30 20:22 bannedrooms
-rwxr-x---  1 e2guardian root  236 feb 15  2020 bannedsearchlist
-rwxr-x---  1 e2guardian root    0 feb 15  2020 bannedsearchoveridelist
-rwxr-x---  1 e2guardian root  210 feb 15  2020 bannedsiteiplist
-rwxr-x---  1 e2guardian root 4,4K feb 15  2020 bannedsitelist
-rw-r--r--  1 root       root  220 feb 25 10:00 bannedsitelist3
-rwxr-x---  1 e2guardian root  482 feb 15  2020 bannedsslsiteiplist
-rwxr-x---  1 e2guardian root  450 feb 15  2020 bannedsslsitelist
-rwxr-x---  1 e2guardian root 2,6K feb 15  2020 bannedurllist
-rwxr-x---  1 e2guardian root 4,9K feb 15  2020 contentregexplist
drwxr-x---  2 e2guardian root 4,0K dic 30 20:22 contentscanners
-rwxr-x---  1 e2guardian root 3,1K feb 15  2020 domainsnobypass
-rwxr-x---  1 e2guardian root  223 feb 15  2020 embededreferersiteiplist
-rwxr-x---  1 e2guardian root   94 feb 15  2020 embededreferersitelist
-rwxr-x---  1 e2guardian root  200 feb 15  2020 embededrefererurllist
-rwxr-x---  1 e2guardian root  408 feb 15  2020 exceptionclientlist
-rwxr-x---  1 e2guardian root  480 feb 15  2020 exceptionextensionlist
-rwxr-x---  1 e2guardian root  421 feb 15  2020 exceptionfilesiteiplist
-rwxr-x---  1 e2guardian root  912 feb 15  2020 exceptionfilesitelist
-rwxr-x---  1 e2guardian root  834 feb 15  2020 exceptionfileurllist
-rwxr-x---  1 e2guardian root  578 feb 15  2020 exceptioniplist
-rwxr-x---  1 e2guardian root  653 feb 15  2020 exceptionmimetypelist
-rw-r--r--  1 root       root  535 feb 25 10:00 exceptionphraselist
-rwxr-x---  1 e2guardian root  322 feb 15  2020 exceptionregexpheaderlist
-rwxr-x---  1 e2guardian root  335 feb 15  2020 exceptionregexpurllist
-rwxr-x---  1 e2guardian root  305 feb 15  2020 exceptionregexpuseragentlist
-rwxr-x---  1 e2guardian root  154 feb 15  2020 exceptionsiteiplist
-rwxr-x---  1 e2guardian root  703 feb 15  2020 exceptionsitelist
-rw-r--r--  1 root       root  738 feb 25 10:00 exceptionsitelist3
-rwxr-x---  1 e2guardian root  361 feb 15  2020 exceptionurllist
-rw-r--r--  1 root       root  381 feb 25 10:00 exceptionurllist3
-rwxr-x---  1 e2guardian root  357 feb 15  2020 exceptionvirusextensionlist
-rwxr-x---  1 e2guardian root  232 feb 15  2020 exceptionvirussiteiplist
-rw-r--r--  1 root       root  196 feb 25 10:00 filtergroupslist
-rwxr-x---  1 e2guardian root  444 feb 15  2020 greysiteiplist
-rwxr-x---  1 e2guardian root 1,9K feb 15  2020 greysitelist
-rwxr-x---  1 e2guardian root  155 feb 15  2020 greysslsiteiplist
-rwxr-x---  1 e2guardian root  132 feb 15  2020 greysslsitelist
-rwxr-x---  1 e2guardian root  900 feb 15  2020 greyurllist
-rwxr-x---  1 e2guardian root  520 feb 15  2020 headerregexplist
-rwxr-x---  1 e2guardian root  221 feb 15  2020 ipnobypass
-rwxr-x---  1 e2guardian root  553 feb 15  2020 localbannedsearchlist
-rwxr-x---  1 e2guardian root  159 feb 15  2020 localbannedsiteiplist
-rwxr-x---  1 e2guardian root  291 feb 15  2020 localbannedsitelist
-rwxr-x---  1 e2guardian root  272 feb 15  2020 localbannedsslsiteiplist
-rwxr-x---  1 e2guardian root  222 feb 15  2020 localbannedsslsitelist
-rwxr-x---  1 e2guardian root   27 feb 15  2020 localbannedurllist
-rwxr-x---  1 e2guardian root  161 feb 15  2020 localexceptionsiteiplist
-rwxr-x---  1 e2guardian root   31 feb 15  2020 localexceptionsitelist
-rwxr-x---  1 e2guardian root   30 feb 15  2020 localexceptionurllist
-rwxr-x---  1 e2guardian root  157 feb 15  2020 localgreysiteiplist
-rwxr-x---  1 e2guardian root   28 feb 15  2020 localgreysitelist
-rwxr-x---  1 e2guardian root  161 feb 15  2020 localgreysslsiteiplist
-rwxr-x---  1 e2guardian root  362 feb 15  2020 localgreysslsitelist
-rwxr-x---  1 e2guardian root   25 feb 15  2020 localgreyurllist
-rwxr-x---  1 e2guardian root  621 feb 15  2020 logregexpurllist
-rwxr-x---  1 e2guardian root  725 feb 15  2020 logsiteiplist
-rwxr-x---  1 e2guardian root  594 feb 15  2020 logsitelist
-rwxr-x---  1 e2guardian root  589 feb 15  2020 logurllist
-rwxr-x---  1 e2guardian root 1,9K feb 15  2020 newbannedphraselist
-rwxr-x---  1 e2guardian root  560 feb 15  2020 newexceptionphraselist
-rwxr-x---  1 e2guardian root 6,7K feb 15  2020 newweightedphraselist
-rwxr-x---  1 e2guardian root  478 feb 15  2020 nocheckcertsiteiplist
-rwxr-x---  1 e2guardian root  387 feb 15  2020 nocheckcertsitelist
drwxr-x--- 53 e2guardian root 4,0K dic 30 20:22 phraselists
-rw-r--r--  1 root       root 2,9K feb 25 10:00 pics
-rwxr-x---  1 e2guardian root  225 feb 15  2020 refererexceptionsiteiplist
-rwxr-x---  1 e2guardian root   95 feb 15  2020 refererexceptionsitelist
-rwxr-x---  1 e2guardian root   71 feb 15  2020 refererexceptionurllist
-rwxr-x---  1 e2guardian root 1,6K feb 15  2020 searchregexplist
-rwxr-x---  1 e2guardian root 1,3K feb 15  2020 sslsiteregexplist
-rwxr-x---  1 e2guardian root 2,2K feb 15  2020 urlnobypass
-rwxr-x---  1 e2guardian root   81 feb 15  2020 urlredirectregexplist
-rwxr-x---  1 e2guardian root 3,0K feb 15  2020 urlregexplist
-rwxr-x---  1 e2guardian root 6,6K feb 15  2020 weightedphraselist
`

I tried different combinations of owners and permissions but it's still dropping errors.

**Comment by KDGundermann** [comment]
have you checked as which user the e2guardian process is running?

**Comment by fredbcode** [comment]
You can also test with our "official" packages

https://e2guardian.numsys.eu

**Comment by fredbcode** [comment]
Or

Check your user and group in your configuration files https://github.com/e2guardian/e2guardian/blob/v5.3/configs/e2guardian.conf.in#L611

chown -R e2user:e2group /etc/e2guardian 

find /etc/e2guardian -type d -exec chmod 750 {} \+
find /etc/e2guardian -type f -exec chmod 640 {} \+

**Comment by brunolorente** [comment]
The service is running with e2guardian user, so:
`chown e2guardian:e2guardian /etc/e2guardian
find /etc/e2guardian -type d -exec chmod 750 {} +
find /etc/e2guardian -type f -exec chmod 640 {} +`

Still happenning the same issues, on the other hand installing https://e2guardian.numsys.eu/v5.4/e2ubuntu_focal_V5.4.2r_20201023.deb preserving the old config seems to be the same behavior.

For the daemonuser  and daemongroup I proved with quotes and without quotes, the same...

The "custom" config file  used with "ii e2guardian 5.3.4-1 amd64 Web content filtering (Dansguardian fork)" (from ubuntu repo) looks like https://pastebin.com/KkxPepQ4

**Comment by fredbcode** [comment]
Did you try with the package config files (e2ubuntu_focal_V5.4.2r_20201023.deb) ? With /etc/e2guardian directory removed first ?

**Comment by Josephat90** [comment]
Good day, Mr. Fred
Is it mandatory to run e2guardian with squid or can  I run e2guardian without squid?

**Comment by KDGundermann** [comment]
@Josephat90 you can run e2guardian without squid

**Comment by fredbcode** [comment]
> Good day, Mr. Fred
> Is it mandatory to run e2guardian with squid or can I run e2guardian without squid?

Hi, Yes you can but with some limitation like identification,  please ask your question on https://groups.google.com/forum/#!forum/e2guardian

**Comment by brunolorente** [comment]
Hi again @KDGundermann @fredbcode, still the same problem. Did you see some mess in https://pastebin.com/KkxPepQ4?
hmmm could be squid being the source problem?

**Comment by fredbcode** [comment]
Did you see my answer about install without previous config files ?

Remove /etc/e2guardian and try latest 5.4 package

**Comment by brunolorente** [comment]
Thais issue can be closed

**Comment by FlookyBS** [comment]
Hi, this error happens on Alpine Linux. Did all steps, nothing.

**Comment by FlookyBS** [comment]
![image](https://github.com/e2guardian/e2guardian/assets/69437909/2693b64f-034d-420e-832c-717e9d92b334)
![image](https://github.com/e2guardian/e2guardian/assets/69437909/a35927e5-2509-42a0-b0a4-ce6b34c665d4)
