### ISSUE TITLE
Is it possible to test headers for banned words

### ISSUE THREAD

**Issue by rickprice** [e2guardian/e2guardian#671]
I'm having an issue with YouTube where its passing its query via the Referer Header, I would like to take the query value from the header, and add it to what is being tested for illegal words...

I am okay with writing a Regex to accomplish this, but how would I go about doing that?

Referer: https://www.youtube.com/results?search_query=zombie

**Comment by ghost** [comment]
Put this line in _urlregexplist_ list:

"zombie"->"spring"

**Comment by rickprice** [comment]
Appreciated :)

**Comment by philipianpearce** [comment]
This relates to #623

**Comment by philipianpearce** [comment]
Stale
