### ISSUE TITLE
 exceptionfile test in wrong place? ( 5.4.3r) 

### ISSUE THREAD

**Issue by moosty-moo** [e2guardian/e2guardian#677]
I can't get the exceptionfile ( exception for file extensions per site ) to work in version 5.4.3r

In function "checkrequest" the line:
ifnot(greyset) returnif bannedcheck
always blocks a file exension even if the site domain is in the "exceptionfile"

It looks like the exceptionfile check is in the "checkresponse" function when it should be tested in checkrequest
if(urlin,exceptionfile) return false

EDIT: Please see my reply below where I've changed bannedcheck instead.

I've altered the exceptioncheck function to include the exceptionfile test and all now works.

function(exceptioncheck)
if(urlin, exception) return setexception
if(refererin,refererexception) return setexception
if(urlin,exceptionfile) return setexception  <----------- added line 
if(headerin, exceptionheader) return setexception
if(useragentin, exceptionuseragent) return setexception
ifnot(urlin,embededreferer) return false
if(embeddedin,refererexception) return setexception

Does that make sense?

**Comment by moosty-moo** [comment]
Just had another look. Instead of what I did above. How's about just modifying bannedcheck?
I'm probably doing this all wrong, but it seems to work.

function(bannedcheck)
if(true) returnif checkblanketblock
if(urlin, banned) return setblock
if(true) fileexception  <-----  is there a file exception?
ifnot(returnset) returnif fileban  < -----  if not, then check for banned file extensions.
#if(urlin,bannedextension) return setblock <--- removed
if(useragentin, banneduseragent) return setblock
if(headerin, bannedheader) return setblock

function(fileexception) <--- new function
if(urlin,exceptionfile) return true

function(fileban) <---- new function
if(urlin,bannedextension) return setblock

**Comment by philipianpearce** [comment]
Hi, 

Yes, you are along the right lines. I would code it as follows (to reduce the number of functions and lines): 

function(bannedcheck) 
if(true) returnif checkblanketblock 
if(urlin, banned) return setblock 
ifnot(urlin,exceptionfile) returnif fileban <--- if not in exceptionfile check fileban 
#if(urlin,bannedextension) return setblock <--- removed 
if(useragentin, banneduseragent) return setblock 
if(headerin, bannedheader) return setblock 

function(fileban) <---- new function 
if(urlin,bannedextension) return setblock 

I will change the distributed common.story to this for the next v5.4 release. 

Thanks for bring this to our attention. 

Note that the reason the main extension/mime checks are in responsecheck is that much better information is available then from the manifest including the actual mime type and the actual filename that would be written to disk. Increasing url are missing the file extension as much content is dynamically served. 

Regards 
Philip 
----- Original Message -----
