### ISSUE TITLE
SQUID+ICAP protocol error / timeout/no response: out_res_body_flag was not reseted.

### ISSUE THREAD

**Issue by rdpmc** [e2guardian/e2guardian#679]
I have the  problem with e2g 5.5.0 and squid 4.13 (sslbump + interception), both on the same machine.

After a few minutes from starting browsing the internet Squid slows down and finally there is a message 
------------------------------------------
    ICAP protocol error.
    The system returned: [No Error]
     This means that some aspect of the ICAP communication failed.

I've found that flags out_res/req_body_flag are not cleared (reseted to false) in reset() method in ICAPHeader.cpp.
So this sometimes randomly produce such  strange behaviour: Encapsulated header can be wrong in some cases in such way:

In ICAP response: Encapsulated: req_hdr:0, res_body=1234, but res_body is set errorneously due-to out_res_body_flag is true and not cleaded in reset(). 

In such case squid thinks that response body present in the response for ICAP-Reqmod, but only HTTP-headers are in response packet. 
Correct Encapsulated must be : Encapsulated: req_hdr:0,nul_body=1234. 

I considered case when no modifications are made to HTTP-request .

**Comment by philipianpearce** [comment]
Thanks for reporting this.   I have made code changes to ensure the flags are now both initialized and reset to false in v5.5.dev.    Can you check if this is now ok?
I will also look at v5.4 as I expect the bug was also present in that version.

**Comment by maxxer** [comment]
Is there any chance to test using deb packages? I ran into the same yesterday...

**Comment by philipianpearce** [comment]
See https://e2guardian.numsys.eu/v5.4/e2debian_buster_V5.4.4_20210421.deb 

----- Original Message -----

**Comment by fredbcode** [comment]
There are also packages for Ubuntu, raspberry (raspbian) and docker images (docker hub).
Links in our GitHub releases page


-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by philipianpearce** [comment]
Community group mail indicate this issue is fixed in v5.4.4
