### ISSUE TITLE
*DENIED* Failed to negotiate ssl connection to client

### ISSUE THREAD

**Issue by ageekhere** [e2guardian/e2guardian#680]
I am getting a lot of *DENIED* Failed to negotiate ssl connection to client

Is there a way to resolve/manage this?

**Comment by ageekhere** [comment]
Turning off negotiate ssl selected in group defaults seems to help now

**Comment by philipianpearce** [comment]
These are often caused by apps who are not using the stored root CA. (or where the root CA has not been installed on browser)

If you are using v5.3 then upgrading to v5.4 will reduce the number of these messages.

**Comment by nkowshik** [comment]
> Turning off negotiate ssl selected in group defaults seems to help now

How do I do that please?

**Comment by ageekhere** [comment]
> > Turning off negotiate ssl selected in group defaults seems to help now
> 
> How do I do that please?

Look for negotiate ssl in group defaults of e2guardian
