### ISSUE TITLE
Feature: observability

### ISSUE THREAD

**Issue by chifu1234** [e2guardian/e2guardian#697]
Currently e2g has no observability. There are no metric which can be gathered. I think there are two options to resolve this issue:
- Implement a Prometheus exporter
- implement a socket
What do you think?

**Comment by KDGundermann** [comment]
in v5.5 there is a new logger and you can send the log entries e.g. to GrayLog and then create metrics there..

**Comment by philipianpearce** [comment]
Key metrics (requests, connections and capacity etc) are periodically written to the dstat.log or to syslog (output similar to sar format). This can be read by standard log-monitoring tools (or by scripting) for system monitoring purposes.  

No plans at the moment to implement a special socket (like squid) as e2g stats are much simpler.
