### ISSUE TITLE
Downloading large file stops after 1,25G

### ISSUE THREAD

**Issue by sysadmin0129** [e2guardian/e2guardian#698]
e2guardian 5.3.4, Ubuntu server 20.04.2 LTS

Every time i try downloading Centos iso file from http://mirror.etf.bg.ac.rs/centos/8.4.2105/isos/x86_64/CentOS-8.4.2105-x86_64-dvd1.iso it stops after 1,25GB with "Failed" message from the browser (Firefox, Chrome).

- etf.bg.ac.rs is added to the exceptionsitelist
- i have no AV scanning enabled, "contentscanner" options are not set in e2guardian.conf and "disablecontentscan = on" is set in e2guardianf1.conf. I have no other filter group.
- e2guardian uses squid v 4.10 as upstream proxy, and i was able to download Centos iso file using squid directly
- i have no mitm setup is e2guardian

I was able to download other large files withouth problem, but i am affraid that this problem could potentially affect users as i cant test every large file they try to download and i dont know why this Centos iso is blocked. 

Log files does not show anything useful to my understanding. "/var/log/e2guardian/access.log" list mirror.etf.bg.ac.rs as TRUSTED. 

Any help is highly appreciated. :)

**Comment by philipianpearce** [comment]
Sorry for missing your post - issue fixed as part of resolving issue #730
