### ISSUE TITLE
v5.4: allows dh-1024 and has no way to tweak allowed ciphersuites

### ISSUE THREAD

**Issue by patrakov** [e2guardian/e2guardian#708]
Same system as in #707 (standalone transparent proxy with SSL MITM enabled) also allows connections to a test site with a weak crypto (https://dh1024.badssl.com/), that browsers would normally block. That site uses an ephemeral Diffie-Hellman key exchange over a 1024-bit group.

Not sure if this can be counted as a bug in e2guardian or just bad defaults in OpenSSL: curl on Arch Linux (without the e2guardian MITM) opens this site, too. Perhaps let's take it as a feature request to be able to fine-tune acceptable SSL parameters on both sides of the connection through the configuration file?

**Comment by patrakov** [comment]
Modern Firefox also doesn't open https://dh2048.badssl.com/ while e2guardian allows it.

Also e2guardian opens https://dh-small-subgroup.badssl.com/ , https://dh-composite.badssl.com/ , https://tls-v1-0.badssl.com:1010/ , https://tls-v1-1.badssl.com:1011/ , but again, curl can get them, too.

**Comment by philipianpearce** [comment]
Changing ciphersuites is fully supported  by modifying the main openssl.conf file or by creating a specific openssl format config file for e2guardian.   See options useopensslconf and opensslconffile in e2guardian.conf.   This avoids re-implementing the openssl config syntax within e2g.

It would be useful to add an example openssl config file that implements the latest recommended settings to the distribution if you would like to write one.  What do you think?

**Comment by patrakov** [comment]
Yes, an example of an openssl cnf file that allows the same cryptographic primitives and protocols as modern browsers would be great.
