### ISSUE TITLE
problems installing E2Guardian-3.1.2 released December 2014

### ISSUE THREAD

**Issue by rmdtech** [e2guardian/e2guardian#71]
Let me explain why I want to upgrade as perhaps another version would be better suited for me as this version is a development version and perhaps I should be looking at the stable version

I want to accomplish the following:
1. Use port authentication (which is supported in E2Guardian).  I am still using the Dansguardian version created by FredB
2. We have issues with any https website that is blocked showing the error message "proxy server is refusing connections" instead of the error message that website abc is blocked.  I am hoping that the e2Guardian upgrade will fix whatever the problem is here.
3.  I want to filter Google traffic which we can no longer do as all google searches are now https.  I think I need to install this version and enable sslmitm at ./configure time.

I downloaded the file, extracted it and saw that there was no configure file.  According to a google search I need to run autoreconf to create the configure file.  I did this, but it comes up with the following errors:

aclocal.m4:17 warning this file was generated for autoconf 2.67.  You have another version
(I have version 2.69)
configure.ac:177 error possibly undefined macro AC_FINALISED_VAR
if this token and others are legitimate please use m4_pattern_allow
imlib.m4:9 warning.  Underquoted defintion of AM_PATH_IMLIB
IMLIB.M4:9 run info'(automake)Extending aclocal'

Naturally this results in a corrupted configure file as the autoreconf exits with failed status 1.  When I run ./configure --prefix=/usr/local/e2guardian --with-filedescriptors=8196 --enable-clamd=yes it does some configuring and then exits with error.  I will add the enable-sslmitm=yes on if this is required for google searches to work properly now.

Is there some reason why there is no longer a configure file as I never had any problems installing using ./configure make make install and make clean commands.  But now I have to use autoreconf which is not working.

my pkg-config is installed so I am not sure whether there is a problem with the configure.ac file?  But nobody else is having problems installing the program, so it must be something to do with my os.  I am using Slackware.

Thank you for any feedback!

**Comment by fredbcode** [comment]
Hi,

Le 29/05/2015 21:03, rmdtech a écrit :
>
> Let me explain why I want to upgrade as perhaps another version would 
> be better suited for me as this version is a development version and 
> perhaps I should be looking at the stable version
>
> I want to accomplish the following:
> 1. Use port authentication (which is supported in E2Guardian). I am 
> still using the Dansguardian version created by FredB
> 2. We have issues with any https website that is blocked showing the 
> error message "proxy server is refusing connections" instead of the 
> error message that website abc is blocked. I am hoping that the 
> e2Guardian upgrade will fix whatever the problem is here.
>

Yes you can, please take a look here 
https://groups.google.com/forum/#!topic/e2guardian/M2LhXerJ568

> 3. I want to filter Google traffic which we can no longer do as all 
> google searches are now https. I think I need to install this version 
> and enable sslmitm at ./configure time.
>

Only with the dev branch, but don't worry a new release is coming

> I downloaded the file, extracted it and saw that there was no 
> configure file. According to a google search I need to run autoreconf 
> to create the configure file. I did this, but it comes up with the 
> following errors:
>
>

There is a little change now, make ./autogen.sh before
https://github.com/e2guardian/e2guardian/blob/develop/INSTALL ./autogen.sh

FredB

**Comment by rmdtech** [comment]
Thank you very much for your help.  I am sorry that I took so long to respond but this weekend is the first chance I have had to install the e2guardian upgrade.  I followed your suggestion of using ./autogen.sh and this addressed my installation issue.

I have not used enable-sslmitm=yes in the ./configure option for e2guardian because I discovered that e2guardian would not start.

This topic gave me the answer - https://groups.google.com/forum/#!topic/e2guardian/wJXLvpJsMZY

I understand that this issue will be fixed in the next release that comes out.

I will open up a new topic when I have time and cover some issues that I am having with the default settings such as when blocking facebook, the browser just says proxy server is refusing connections because facebook is an https site.  I am sure that I just need to change a setting somewhere for blocked https websites to show the access denied html page.

I have a couple of other issues like that, so when I have time I will open up a new topic as this topic has been answered and I don't want to take the thread offtopic.

**Comment by fredbcode** [comment]
Ok thanks for your report

About HTTPS access denied page https://groups.google.com/forum/#!topic/e2guardian/M2LhXerJ568

**Comment by rmdtech** [comment]
I have already looked at that HTTPS access denied topic.  This is not relevant to my issue.  They are using the access denied cgi webserver setup.  I am using the template file within e2guardian.  My problem is the template file is not being displayed at all.  I just get a proxy is refusing connections page.  Their issue was that they were not getting the correct information sent to their php/cgi page.

I think that I need to enable some settings in the conf file.  I have only changed a couple of settings, just to get filtering to work.  so the next step will be fixing this issue.  but I will open a new topic up for it.

**Comment by fredbcode** [comment]
Sorry but for SSL you can't 
sslaccessdeniedaddress is needed because E2 can't replace a SSL website by a template file
SSL website is protected, without SSLMITM we can't change anything 

sslaccessdeniedaddress is a trick, a redirection to another website

**Comment by rmdtech** [comment]
Thank you for explaining that I need to use ssaccessdeniedaddress instead of the template for SSL Websites.  Did not know that.  Could you update the e2guardian.conf file notes to highlight that the template file will only work with http websites as most people who were using filtering systems for years will have been using the template file which has effectively been obsolete by the introduction of https for virtually all websites.

Also could you update the install documentation of the downloads to reflect that you need to run ./autogen.sh as those instructions are not in the install documentation.  At least ways not in the version that I downloaded.  Thank you.

I will attempt to complete the filtering installing and configuration this weekend.  I have been very busy this week and last week sorting out some networking issues unrelated to the e2guardian so have not spent any time on e2guardian in the last few days.
