### ISSUE TITLE
[bug] reportinglevel

### ISSUE THREAD

**Issue by chifu1234** [e2guardian/e2guardian#710]
Hi Guys,
It seems like that the option `reportinglevel` is completely ignored. I use e2g `5.4.3`. It always sends a `302`  to `http://internal.test.e2guardian.org` when blocked. Both e2guardian.conf and e2guardianf0.conf are ignored.
Regards, Kevin

**Comment by chifu1234** [comment]
not sure but it might be related  to https://github.com/e2guardian/e2guardian/blob/3ce57b50c9754bca39fabd1eaa1b69f0bbe223f9/src/FOptionContainer.cpp#L470

**Comment by chifu1234** [comment]
Ok not sure if I read the code correct ;)

But I fall in that if (because I've setet it to 3) https://github.com/e2guardian/e2guardian/blob/7c865f2e04f4e69694b77594664f6feb284156e4/src/ConnectionHandler.cpp#L1885
And then next I fall in (because its a connect request) https://github.com/e2guardian/e2guardian/blob/7c865f2e04f4e69694b77594664f6feb284156e4/src/ConnectionHandler.cpp#L1896
And then e2g builds the response with 302 and with a harcoded location https://github.com/e2guardian/e2guardian/blob/7c865f2e04f4e69694b77594664f6feb284156e4/src/ConnectionHandler.cpp#L1904
Is this behaviour as intended?

**Comment by philipianpearce** [comment]
Yes, it did allow a more tidy user presentation in non-MITM mode at one time in some browsers.  However, now most browsers will no longer allow it and throw an error, so this redirection code has been removed in versions after v5.4.

As 99.9% of all sites are now https, reportinglevel will only be effective for the user when using MITM. 

In fact e2guardian can now only be effective and user-friendly when used in MITM mode (or in ICAP mode with squid-bump - a more complex set up).  

Without MITM  e2guardian can only block or allow based on site names and browsers give a 'network' error when e2g blocks a site.

Philip

**Comment by chifu1234** [comment]
i see thanks ;)
