### ISSUE TITLE
maxheaderline limit

### ISSUE THREAD

**Issue by Anthony-76** [e2guardian/e2guardian#713]
Hi, 

I use an E2guardian release 5.3 (I know it's not the last release)

I have issues on somes Websites (like Linkedin for example)

The webpages are very slow or sometimes all webpages are not fully loaded because these websites are a loooooot oooffffff..... headers lines.

I increase the maxheaderlines to 2000 in e2guardian.conf and now the webpages work fully and fully loaded

I change the value in OptionContainer.cpp:
if (!realitycheck(max_header_lines, 10, **2050**, "maxheaderlines")) 

If you can allow the range value between of maxheaderlines from10 to 2000 in the e2guardian.conf file, it will be good.
Maybe this tips can help you (or not) in the new E2guardian release

Best regards
Anthony

**Comment by philipianpearce** [comment]
Very sorry for delay in picking this up.   Thanks very much for suggestion.
Have increased upper limit in latest v5.4 and v5.5.dev to 2500.

Sorry it missed v5.4.4r but will be in v5.4.5r (to be released shortly)
