### ISSUE TITLE
5.5 ignores proxyip

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#716]
Testing out 5.5 in our ssl MITM configuration, but it appears to connect directly to sites rather than use our squid proxy as set in proxyip.

**Comment by philipianpearce** [comment]
diag - bug in revised OptionContainer structure

**Comment by philipianpearce** [comment]
Many thanks for reporting this bug.
Fixed in latest v5.5.dev
Can you please test and report if now OK

**Comment by opoplawski** [comment]
That looks better, thanks!
