### ISSUE TITLE
e2g appears unable to process data some some URLs

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#717]
We are downloading data from https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/, in particular dated directories like https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20211228/00/atmos/.  Access to the latter URL fails when going through e2g (5.4.3 or 5.5-dev), but works fine directly or via squid.  Headers are returned but no data.

[log.txt](https://github.com/e2guardian/e2guardian/files/7786515/log.txt)

**Comment by philipianpearce** [comment]
This site is generating a huge chunk greater than the size of an int with an abnormally large chunk size field (14 chars), so required changing definitions to long int in order to work.     This is unusual, as it is bad practice for a site to generate such large chunks as this slows down browser rendering a lot when going direct making the site seem dead.

Fix in progress for v5.5.dev. 
Work round for v5.4.3 is to make the site an exception.

**Comment by opoplawski** [comment]
Thank you very much for the analysis - I banged my head against this for much of yesterday.  However, for 5.4..3 adding "ncep.noaa.gov" to exceptionsitelist did not appear to help.

**Comment by philipianpearce** [comment]
This site is very, very slow especially where there is lots of entries in a directory. 

It is likely that it is exceeding the timeout set in e2guardian.conf. Try increasing proxytimeout and proxyexchange to 120 or more. 

----- Original Message -----

**Comment by opoplawski** [comment]
Yeah, that may have been it.  Seems to be working now.  Thanks.

**Comment by Kenny690** [comment]
I have the same issue with dns-shop.ru. I have white screen and nothing in logs. If I go directly, I can access it. 
And I have another issue, and, IDK, maybe it's connected. I have some websites that I can't access via proxy. E2guardian throwing "Access Denied" with error "Failed to negotiate ssl connection to server". I can access the website directly. 
I have MITM turned on. Websites are, for example, facebook.com, rg.ru, cm.mgid.com

**Comment by philipianpearce** [comment]
Kenny690 issue with 'Failed to negotiate ssl connection to server' is different likely due to out-of-date cert store on system e2g is hosted on.
