### ISSUE TITLE
Change in log format with 5.5

### ISSUE THREAD

**Issue by opoplawski** [e2guardian/e2guardian#718]
Testing out 5.5 branch and using logfileformat 4.  Out is different.  Previously there was a "-" in the initial field but that is no empty.  Can that be reverted to be a "-"?  It's confusing my logwatch parsing.  Thanks.

**Comment by opoplawski** [comment]
I'm also seeing some entries without a "action" (like `*SCANNED*`):
```
https://push.services.mozilla.com               GET     0       0               1       101 
```
What is happening there?

**Comment by philipianpearce** [comment]
Use 'dashforblank = on' option in e2guardian.conf 

This is missing from the examples, I will add it as an example. 

Regards 
Philip 

----- Original Message -----

**Comment by opoplawski** [comment]
Thanks, that works.  Looks like it used to be on by default but not anymore?

**Comment by philipianpearce** [comment]
Is now on by default in v5.5.dev
