### ISSUE TITLE
banned searchlist can be bypassed by changing capitalization

### ISSUE THREAD

**Issue by programmerPhysicist** [e2guardian/e2guardian#720]
When I add the word 'cats' to bannedsearchlist, if I do a search for 'Cats' it won't block it. If I search for 'cats' (uncapitalized), it blocks it. If I then add 'Cats' (capitalized), to bannedsearchlist and restart e2guardian, it _still_ won't block it.

**Comment by programmerPhysicist** [comment]
Furthermore, it appears to not block search terms that are capitalized.

**Comment by philipianpearce** [comment]
Fixed in v5.4 and v5.5.dev branches

Thanks for raising this bug!

Philip
