### ISSUE TITLE
Is it possible to use aliases instead of ip's?

### ISSUE THREAD

**Issue by andersonsc10** [e2guardian/e2guardian#721]
Hello, I have some groups and acl's configured in the e2g, and I would like to reuse ips that I have registered in aliases, I would like to know if in the ip's tab of the e2g instead of putting the ips "192.168.xx" I could put an alias "list_mang" for example?

Att

**Comment by philipianpearce** [comment]
e2g does not support aliases, so I'm not sure what you mean by 'registered in aliases'.  Can you provide an example of what you mean?

However, if you a talking about within the lists, .Include lists can often be used to avoid retyping lists of ip.

For example, you could have a list called    mang_ip_list and then include this within other master lists as required. 

Also please see #21 re use of e2g issues.

**Comment by andersonsc10** [comment]
Hello, I'll try to give an example with images, I don't know if it's
supported here on github but I'll try the same, below there's a print of
the pfsense menu, where I have lists of ip's:
[image: image.png]
[image: image.png]
in this list of ips (aliases) above I have my manager list, among others,
what I would like is to reuse these lists in the following e2g menu:
[image: image.png]
that way I would centralize the ips only in one place.

ps: I don't speak English, I'm using google translator.


Em ter., 1 de mar. de 2022 às 06:30, Philip Pearce ***@***.***>
escreveu:

**Comment by philipianpearce** [comment]
This is not an e2g issue.

Best to ask this at the pfsense support site.

**Comment by andersonsc10** [comment]
Ok thanks, I asked here because in other parts of pfsense aliases work,
except in e2guardian, but I will try to inform myself better.

Att.

Em sex., 11 de mar. de 2022 às 07:42, Philip Pearce <
***@***.***> escreveu:
