### ISSUE TITLE
Is possible to build arm image for arm/v7 processor

### ISSUE THREAD

**Issue by rekcah78** [e2guardian/e2guardian#722]
Hi,

I need that for running e2guardian in raspberry pi,
the latest arm image only support arm64/v8 processor.

Christophe

**Comment by fredbcode** [comment]
Sorry I'm using only an armv8 (p3/p4) infra for compilation, you can migrate to 64 bits OS or compil e2guardian source code 
Look at my ci dockerfile for this 
https://github.com/e2guardian/e2guardian/blob/v5.4/gitlabci/docker-ci/Dockerfile
