### ISSUE TITLE
Are there any plans to release a new version soon please?

### ISSUE THREAD

**Issue by ghost** [e2guardian/e2guardian#723]
Please excuse me..

**Comment by philipianpearce** [comment]
Yes,  a new v5.4 version will be released within the next two weeks and the first v5.5 stable release in about a month.

**Comment by ghost** [comment]
@philipianpearce It seems like you forgot to issue a new tag:
https://github.com/e2guardian/e2guardian/tags

**Comment by philipianpearce** [comment]
@lyos Nothing forgotten. Due to having covid19 and leave the release has been delayed - I hope now to complete the release later this week. 

Philip 

----- Original Message -----
