### ISSUE TITLE
Log Referer

### ISSUE THREAD

**Issue by xes** [e2guardian/e2guardian#726]
While trying to filter some phishing pages, i would like to log the referer url with latest e2guardian 5.4 with MITM enabled.

Is it possible?

**Comment by philipianpearce** [comment]
It will be possible from v5.6

**Comment by philipianpearce** [comment]
The new log format definition files in v5.6 allow the logging of any header.  See https://github.com/e2guardian/e2guardian/blob/v5.6.dev/notes/LogFormatFiles
