### ISSUE TITLE
Installation /etc/clamd.d/e2guardian.conf

### ISSUE THREAD

**Issue by tachtler** [e2guardian/e2guardian#73]
Hi, 

when installing e2guardian, there will be a dependency to ClamAV and the following configuration file will be generated: vim /etc/clamd.d/e2guardian.conf

Inside the configuration file, parameters will set to dansguardion, not to e2guardian:

PidFile /var/run/dansguardian/clamd.pid
User dansguardian
LocalSocket /var/run/dansguardian/clamd.sock

This should be:

PidFile /var/run/e2guardian/clamd.pid
User e2guardian
LocalSocket /var/run/e2guardian/clamd.sock

Is that right?

Thank you!
Klaus.

**Comment by fredbcode** [comment]
http://wiki.contribs.org/Dansguardian#ClamAV_support 
E2guardian must be compiled with --enable-clamd=yes

Please post your questions https://groups.google.com/forum/#!forum/e2guardian
