### ISSUE TITLE
E2guardian 5.5.1pre trickle download manager Bug

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#732]
Upon installing this version of E2guardian, I needed to rem out references to Trickle Download Manager in both common.story and E2guardianf1.conf otherwise E2guardian does not start as result of errors looking for Trickle Download Manager. As this version of E2guardian is a pre release, you are probably are aware of it. But I thought I would mention it, in case you were not aware.

Could the documentation be updated regarding download managers. I can't find any information on what the difference is between Default, Trickle and Fancy Download Managers. I have always used Default, but more because I have no idea what the benefit (if any) is for using the other two. Second I think (but it is unclear) whether Download Managers are only applicable when using an anti virus scanner like ClamAV. In other words if you don't use ClamAV are download managers relevant? The only aspect of downloads that I filter is filetypes and mimetypes - so we can block exe's and other filetypes that users do not need to be able to download. But I don't think that the functionality of download managers is relevant here as I presume that R2guardian checks the filetype before downloading the file?

I reviewed ClamAv and I feel that ClamAV is not as effective as it used to be as malware detection has moved away from virus signatures into heuristics and endpoint detection and response (EDR). So it would be worthwhile reviewing whether it still makes sense to support anti virus scanning of websites and downloads in E2guardian. The landscape has changed so much that I don't think traditional virus signature scanning is relevant anymore. So I am relying on our anti virus and malware solution installed on endpoints. Just something to consider for future E2guardian releases.

**Comment by philipianpearce** [comment]
The term 'download manager' is a bit misleading as the default download manager is also used for inbuilt  content checking.   Previous versions of v5 have only supported the default download manager and I have never (in  previous versions) used anything else on systems we support.  But there have been a number of requests for trickle and fancy to be re-instated.  In v5.5 I have re-written the DataManager to improve memory handling etc, and re-instated trickle.  Fancy is not complete.

The trickle and fancy managers are only relevant when talking to a browser.  (Fancy needs user interaction).  Now, so much inter action is with javascript, I'm not sure that they are they likely to be effective, and so any further work on these is currently low priority.  

There is potential for new download managers to cope with more specific content (like inline search result filtering for Google etc) if someone has the time to develop these.

I tend to agree with you re ClamAv,  I have tested it in the past and it worked well,  but we do not use it and recommend to our customers that they use a endpoint solution.   However,  I'm aware that many e2g users do use it, so it is still there for the moment.

**Comment by philipianpearce** [comment]
Just uploaded to v5.5 with config references to trickle and fancy commented out.

**Comment by Dalacor** [comment]
There is no harm in keeping Clamav coding within E2guardian. But I would not recommend further development for Clam AV. I think the technology Clamav is based on is not relevant anymore. Restricting filetypes and mimetypes is a far more effective tool and is less likely to cause issues with websites.

I will stick with default download manager then. as I have no need for trickle or fancy.

I will close this topic as you have fixed the error messages in the config files.
