### ISSUE TITLE
Geolocation and TLD Allowed Cyber Protection

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#733]
Dansguardian was originally developed to filter internet traffic more from the point of view of blocking not suitable for work websites.

While this is still a very important and very relevant part of the program's core functionality that E2guardian has further developed, I feel it would be worthwhile to review the use of E2guardian (in conjunction with a firewall like IPTables) to build a comprehensive Cyber Security and Malware Protection System. Malware, Cyber Hacking, Breaches etc is a huge problem nowadays and I believe that E2guardian can be leveraged in conjunction with firewalls to further protect the networks. So the focus of E2guardian should twofold - blocking not suitable for work websites but also Cyber Security and Malware Protection.

**Country Blocking** - One could block countries for two (or more reasons). One to block connections to countries that are known malware hotspots. So for example, you could receive an email with a malicious link that then tries to download a dodgy file from a website hosted in a country where malware is prevalent. A country block would defeat this attack. Two, you could block all Non English countries preventing users that speak another language in addition to English from bypassing E2guardian content filter - which is mostly based on English phraselists - other than the actual blacklists obviously.

**Top Level Domains** - There has a huge increase in dodgy top level domains, most of which host spam, malware etc. From a Cyber Security point of view restricting E2guardian to a limited list of legit TLD's is a very effective way of blocking connections to unsafe websites.

I could implement country blocking in three ways - E2guardian, IPTables or Draytek Router. Draytek router is the simplest, but I will need to test whether E2guardian would then accurately log the website being blocked based on Country Block by Draytek Router. Iptables and Maxmind could certainly do it - but then again we have the same problem of what does E2guardian show in the logs when a user or malware tries to access a blocked country? Hence, the reason I would be keen to implement Maxmind with E2guardian.

I need to investigate, but as far as I am aware only E2guardian supports blocking Top Level Domains. Iptables only deals with IP addresses and I don't think Draytek routers support blocking top level domains. But I am still investigating that.

However there are several problems with implementing Maxmind and TLD with E2guardian.

1. E2guardian has no Geolocation or TLD Rules to show that the page was blocked because of country ABC or TLD. In addition, because E2guardian has no logging functionality for Geolocations it's impossible to create an allowed list of countries as currently we have no information on what countries host the websites currently being viewed. Iptables doesn't log websites, only IP Addresses.

2. While I was looking at TLD, I realised something about E2guardian which makes Allowed Lists difficult to use. Let's say I want to allow only .com ; .co.uk and .net domains for TLD domains and block every other top level domain. Let's say I only want UK, US and Canada as the list of countries where users can view websites.

In E2guardian, I can only find a bannedsitelist file where I can block a top level domain - #You can include
#.tld so for example you can match .gov for example

There seems to be no way to rather block all top level domains by default with an allowed list for a few top level domains. I have long since gone down the route of blocking everything by default and creating an allowed list for a lot of things. It is much more practical to allow a few countries and TLD's rather than to operate a blacklist. There are new TLD's coming out every day. Blacklisting used to be the way IT security worked, but a whitelist is a lot more effective for security and should be used where it is practical such as TLD and Countries. Obviously not practical to maintain a whitelist of allowed websites, so a blacklist is more relevant for that.

Even if I could create a whitelist of allowed countries and top level domains - there is a second issue with E2guardian. The way E2guardian works is when you allow a website, this overides anything in a blacklist. So for example whitelisting a TLD such as .com will allow pornhub.com - which is obviously not what we want. So E2guardian TLD and Geolocation Whitelists would need to operate differently from exception lists which generally override anything in a blacklist. E2guardian currently works on blocked or exceptions basis, whereas a layered approach to filtering needs to apply here to whitelist say .com, yet still block pornhub.com

Maxmind is used by a lot of systems like Mail Servers, Routers etc. All E2guardian would require is the ability to log Geolocation and to continue to apply blacklists, phraselists filtering after Geolocation is approved. E2guardian already records websites, so adding functionality to filter based on TLD is already largely builtin to E2guardian. It just requires a field to log it and as with Geolocation to allow TLD's and still apply further filtering.

For the time being I will implement Geolocation using Draytek Router and see if I can apply top level domain filtering at Draytek level, however, I think the future direction of E2guardian should be to achieve two aims - NSFW filtering and Cyber Security Protection as most of the functionality for NSFW filtering is very much applicable to Cyber Security Protection. We have already gone down the direction of E2guardian providing the logging and filtering of blocked websites where the blacklists are managed by the Draytek Router. So Maxmind and Geolocation filtering is just the next logical step.

I will update this lengthy post once I have reviewed how E2guardian logs websites blocked based on Draytek Country Block.

**Comment by philipianpearce** [comment]
This is a very interesting post.    I'll pick up on most of the points at a later date, but just want to comment on the idea of 'allowed TLDs'  that would be effectively a reverse logic list.

It is possible to do this without any change to the binary (in both v5.4 and v5.5) by modifying the blanket block storyboard functions.    After defining a 'sitelist' with allowed TLD, say tagged as 'allowedtld' you can then add logic to the blanket block like  'ifnot(sitein,allowedtld,888) return setblock'  I'll look at adding this as an example for the next pre-release of v5.5 (as no new binary features needed for it).

Geolocation - most of the building blocks to do this are already in e2g - e.g. ipmaplist which could map ip to country. But would need extra data field(s) for logging and for testing if country is in allowed list.

**Comment by Dalacor** [comment]
I am very pleased that you like the idea. I think TLD and Geolocation is the logical evolution of E2guardian as Internet Filtering is increasingly becoming more about Cyber Security than NSFW concerns. And you have just confirmed that most of the functionality is already in place for both features. So that is fantastic. When I have time, I will see if I can get the TLD Allowed list to work (as you suggested) as it will be the simplest to implement and probably the most effective for both NSFW and Cyber Security.

A note about Geolocation. I tried to implement an allowed list of countries using the Draytek Router. It worked well for the vast majority of websites, but I encountered issues with several websites. I believe that the problem may be with CDN like Cloudflare etc not liking it - regardless of what countries I allow - I just couldn't get these particular websites to work.

Geolocation filtering works brilliantly in email. Since I implemented both Geolocation and TLD Allowed lists, we no longer get any dodgy spammy emails from Ukraine etc. But Content Delivery Networks systems like Cloudflare may actually make Geolocation filtering for websites impossible. However, it may still be practical for blocking the majority of websites as most websites probably don't use CDN I guess? Something to think about.

**Comment by Dalacor** [comment]
I have done the work on TLD. Here is the coding required to block all TLD's by default and explicitly allow specific TLD's. I have also created the necessary coding to allow all TLD's by default and only block a few. Most users will probably only want to block a few TLD's rather than have to explicitly allow TLD's as it is more work to have a blanket block in place obviously.

I tested a blanket TLD block and allowed only the following domains: .com, .uk, .net, .org and .io. I am pleased to report it works really well. 99% of the websites we use fit into these TLD's. So very practical.

Only issue that I have encountered is that error message 888 says *DENIED* TRANSLATION KEY 888 MISSING
It would also be useful to have a TLD field to make it easier to see what TLD's are actually in use before doing a blanket block.

**E2guardianf1.conf**

`### Top Level Domains
###

# Uncomment the line below if you want to ONLY allow top level domains in these lists
# You will also need to uncomment the checkblanketblock and SSLcheckblanket block functions in examplefn.story to enable this

sitelist = 'name=exceptiontld,messageno=888,path=__LISTDIR__/exceptiontldlist'

# Uncomment the line below if you want to BLOCK top level domains in these lists
# You will also need to uncomment the Block Top Level Domains section in examplefn.story to enable this

#sitelist = 'name=bannedtld,messageno=888,path=__LISTDIR__/bannedtldlist'`

**Examplef1.story**

`# To create blanket block for http (and MITM https)
# uncomment next line and one condition line.
function(checkblanketblock)
ifnot(sitein,exceptiontld,888) return setblock # only allows TLD's explicitly set

# To create blanket block for SSL 
# uncomment next line and one condition line.
function(sslcheckblanketblock)
ifnot(sitein,exceptiontld,888) return setblock # only allows TLD's explicitly set

# To Block Top Level Domains listed. Uncomment line below
#if(sitein, bannedtld) return setblock # Block TLD's listed`

**Comment by philipianpearce** [comment]
Have updated v5.5 to do this.  Also added new message 752 for use by these functions/lists.

Note I have used allowedtldlist rather than exceptiontld.  Exceptions
generally override everything but this list is used in blanketblock and
so will be overridden by exception site urls etc.

**Comment by Dalacor** [comment]
The reason I went with the name exceptiontld is because this is what you have for filetypes and mimetype exceptions. You have named them exceptionextension and exceptionmime - so I used the same naming format for consistency. But I agree with your point that exceptions generally override exceptions.

I will test this when I have time. Thanks

**Comment by Dalacor** [comment]
**Top Level Domain Feedback:**

I would like to provide feedback on the new TLD Filtering functionality. I am still using E2guardian 5.5.2 so am still seeing the message - TRANSLATION KEY 888 MISSING. I will be updating E2guardian on the test machine very soon to report back on the issues with configure.ac to see if the fix you have applied works on my systems. Once I have updated E2guardian, I will confirm if the error message for TLD is fixed as well. I want to get rid of that translation Key message.

Using just .com, io, .net, .org and .uk in a live environment, I have found that I have only had to exempt around 20 websites that were blocked by top level domain blanket block. Some I have actually left as blocked as I felt that we were better off blocking them. So I have found using the new allowedtldlist functionality to work very well in a live environment with virtually no issues. I feel the system is much more secure from a Cyber Security point of view as malware frequently connect to dodgy tld and countries known for malware hotspots. So a resounding success for TLD. Thank you.

Only addition, that I might suggest is allowing the .ms Top Level domain as well or go down the route that I have gone and add aka.ms to the exceptionsitelist as this domain is used extensively by Microsoft as a url shortener! I prefer to exempt the website rather than add .ms as an allowed top level domain.

The allowed TLD List is suitable for English users. For other countries, I have no doubt users would need to have different TLD.

**Geolocation Filtering:**

The single biggest problem with Geolocation filtering (apart from the CDN issue) is that logging in Draytek was just not practical. I managed to get Geolocation Filtering to work in Iptables, so was finally able to work out what countries were actually being connected to by CDN Systems such as Cloudflare. I am pleased to report that in reality, you could have less than 20 countries allowed that works with Content Delivery Networks.

So it is actually feasible to use Geolocation to restrict what countries can be connected to. From a Cyber Security point of view as well as language content filtering, this is a great addition.

The problem with using Iptables for Geolocation is twofold.

1. I don't always know what website is being connected to - if they are using CDN as iptables only logs IP addresses not website addresses. It is usually a Microsoft or Google site, but unclear as to what Google/Microsoft service is being connected to.

2. A bigger problem is that for the vast majority of websites (that don't use CDN), I probably only need to allow 2 or 3 countries as most websites seem to come from a very small number of countries. But I have to allow another dozen or so countries for websites using Cloudflare etc to work. It would be far better to allow microsoft.com and google.com to be exempt from geolocation filtering and reduce the actual number of countries allowed to less than 5 countries!

So I would like to confirm that Geolocation filtering is actually quite viable (even with CDN such as Cloudflare). I have tested it in a live environment and found that the vast majority of websites are based in 3 countries. There is just a requirement to be able to exempt certain websites from Geolocation filtering for CDN management reasons and then we have a fairly Cyber Secure system in terms of blocking malware etc.

Iptables uses the following to achieve Geolocation:

1. xtables-addons - https://inai.de/files/xtables-addons
3. Download DB-IP and build database within xtables-addons

Would it be possible for E2guardian to use xtables-addons in the same way the Linux Firewall uses the addons so Geolocation filtering can be achieved by E2guardian rather than using Iptables. It's not practical to have to work with IP Addresses in iptables to exempt websites from Geolocation because of CDN. In addition, I am using the xtables-addons to block logins outside our country to our external servers! So I see no reason to re-invent the wheel for E2guardian. Xtables already provides the functionality - E2guardian just needs to use xtables as a filter list.

Depending on the distro, you may require other dependencies to install xtables-addons.

**Comment by philipianpearce** [comment]
Sorry for the delay in replying! I have been on leave and am still catching up!

Thanks for the detailed feedback.    It's good that the .tld logic is working well.

Geolocation:   

I've had a look at the DB-IP download formats and the .csv version could be formatted into e2g iplist or ipmaplist easily with sed or other tools, which would allow the IP covering the countries required to be loaded into e2g.    This will avoid having to integrate the DB-IP library into e2g.   (In the latest version v5.5.3 I have altered the search code for IP ranges so that it will be able to cope with a large list.)

By having the geo lists in e2g, it means that trusted (exception) and content-check (grey) can be allowed on any IP and the geo lists to be deployed in the same way as the .tld.

What is needed to make this work is a method to test the destination IP after DNS look-up.   As the DNS look-up is normally done after the request checks, I may need to add an extra storyboard 'entry hook' to the e2g code as well as adding a ipdestinationin state to the storyboarding.   (This may also be useful for deployments where a restricted DNS is used as it should then be possible to replace any RDNS block page with an e2g one).    

I will look at this once v5.5.3 is settled in the first v5.6.   

I will close this issue now and opened a new one #775 for this development.
