### ISSUE TITLE
configure script uses -V option that no longer exists for gcc

### ISSUE THREAD

**Issue by programmerPhysicist** [e2guardian/e2guardian#734]
When I try to run the configure script before building, using the following command:
`./configure '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--enable-pcre=yes' '--enable-sslmitm=yes' 'CPPFLAGS=-mno-sse2 -g -O2'`
I get the following error: 
`configure: error: C++ compiler cannot create executables`
If I then go look at config.log, I see this:
```
configure:3174: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3185: $? = 1
configure:3174: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'; did you mean '--versio
n'?
```
According to [this superuser.com](https://superuser.com/questions/846768/gcc-unrecognized-command-line-options-v-and-qversion-with-autoconf) post, gcc hasn't had those options for some time. 

This is for e2guardian version 5.4.5r, on Raspbian Buster.

**Comment by philipianpearce** [comment]
This is strange, the configure.ac which configure is generated from uses the g++ -version parameter,  the -V option is nowhere to be found!

Have you run sh autogen.sh which regenerates the configure script before running ./configure as per the INSTALL notes?

**Comment by programmerPhysicist** [comment]
It has been awhile. I tried again today (but with version 5.5), and same issue, as above. I did indeed run sh autogen.sh before running ./configure.

**Comment by programmerPhysicist** [comment]
Removing `'CPPFLAGS=-mno-sse2 -g -O2'` from the given command seems to make the -V error go away, no idea why.

**Comment by philipianpearce** [comment]
Closing as stale
