### ISSUE TITLE
MITM mode: guardian should honor TLS-specifications and send to client FULL chain of certificates

### ISSUE THREAD

**Issue by MrdUkk** [e2guardian/e2guardian#736]
currently e2guardian send to client ONLY certificate for requested site. it's very wrong because according to standart it SHOULD send full chain or clients can't build chain of trust.

_"If the server is authenticated, its certificate message must provide a valid certificate chain leading to an acceptable certificate authority."_

See:  https://www.rfc-editor.org/rfc/rfc5246#appendix-F.1.1

for example Squid proxy server in MITM mode was done this correctly (send full trust chain to clients)

**Comment by philipianpearce** [comment]
For security reasons e2g does not allow the use of derived certificates in order to generate a 'spoofed' certificate in MITM.   A self-signed root CA has to be generated and loaded on all clients so there is always 'client consent' to the MITM.

As this is the case the 'full chain' in MITM can only consist of a single certificate and so e2guardian does conform to rfc5246.

For connections that are not MITM e2g transparently passes the full certificate chain as sent by the target host.  This is the same as in squid, as it can only pass through the host cert chain when the logic decides not to deploy decrypt/encrypt interception.

**Comment by MrdUkk** [comment]
What are these security reasons? Can you write it here?
To process MITM e2guardian already required PKI certificates from corresponding PKI authority. Those chain of certificates ARE PUBLIC keys that will lead to root trusted CA. What are security concerns here you mentioned ?
'spoofed' certificates are generated by e2guardian already for TARGET sites visited through proxy. but with spoofed cert - you should send to clients full chain of certificates (hes public part). Please look PKI certification chain building documentation and standarts.
Why Squid and others doing MITM properly and you don't? PLease provide examples confirming your point of view.
Didn't you don't understand how certificate chains are building or so?
Please answer question: HOW e2guarian comply with appendix F.1.1 of standard?
"If the server is authenticated,
   its certificate message must provide a valid certificate chain
   leading to an acceptable certificate authority"

**Comment by philipianpearce** [comment]
You are starting from a wrong assumption:
"To process MITM e2guardian already required PKI certificates from corresponding PKI authority. Those chain of certificates ARE PUBLIC keys that will lead to root trusted CA."   

This is NOT the case.  If it were, it would allow e2g to intercept and examine https traffic, without  permission of the client.    And it would make the use of TLS useless, any HTTPS could be intercepted
by anyone with an intermediate certificate and would destroy all trust in the security of the https protocol.

E2guardian REQUIRES the use of a self-signed rootCA - please read the documentation at https://github.com/e2guardian/e2guardian/wiki/MITM---Filtering-HTTPS

Re Standard:
"If the server is authenticated,
its certificate message must provide a valid certificate chain
leading to an acceptable certificate authority"
This refers to target hosts and not to proxies which would normally simply pass on the cert received from the target host.    In MITM mode e2g provides a certificate which leads to a generated  rootCA, which the user has already loaded and approved for use as a certificate authority.   So e2g DOES provide a certificate 'leading to an acceptable certificate authority' as the rootCA has been made acceptable by the client.

Squid does allow the use of intermediate certs, but only recommends it with a self-signed rootCA - see squid documentation.   However, this poses the risk of squid being used for non-authorised MITM by using an upstream public rootCA, which is a security risk and so we are not providing this option in e2g.
