### ISSUE TITLE
Youtube not working in E2guardian-5.5.1pre

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#738]
Youtube won't load in the latest version of E2guardian with MITM enabled. No error message - it just won't load. The only way I can get it to work is to put the site into exceptionsiteslist. The option nocheckcertsitelist has no effect on the issue. I have no problems with Youtube in the stable release of E2guardian. I don't even need to except Youtube certificate in the stable version for the website to load.

I have tested both the latest version and stable version of E2guardian using a fresh install.

**Comment by Dalacor** [comment]
I forgot to add that another website that also has problems is - https://www.imdb.com/list/ls074297314/. Website loads perfectly in stable version of E2guardian, but for some reason will not load images in E2G-5.5.1pre.

An unrelated issue, but one that I have also noticed during all my testing is that E2guardian seems to be a bit sluggish loading some pages in both stable and latest version of E2guardian. It may or may not have something to do with errors that I am seeing in the log like this one:

https://content-signature-2.cdn.mozilla.net:443	*DENIED* Failed to negotiate ssl connection to client

I am seeing this message with random sites, all showing :443 on the end of the url. Sometimes the website shows this and other times, there is no error message for that site. Not sure why these urls ending in :443 are being denied randomly and not 100% certain if this is causing the sluggishness on some websites. But the websites that seem to be experiencing most of the speed issues are almost always showing url:443 and *Denied, so I assume that there is a connection. I have ruled out extensions, mimetypes, content filter block, blacklists and none of these have anything to do with the issue.

I am guessing it's something to do with MITM certificates not liking something about urls ending in :443 - it may be that they use http, not https? I have noticed that http websites won't load because E2guardian tries to load it as https and it fails because there is no certificate. Perhaps this is the cause of the :443 issue?

I see that there is a topic on this - https://groups.google.com/g/e2guardian/c/fKdtZasoQJ8. Is this still the recommended method of addressing this issue? I am not sure how many websites are having this issue, but it seems to be more than just a couple. What I will do when I have time, is go back to a clean install of E2G5.5.1pre and load all the websites up and save the log file. Then reboot and reload all the websites and see what websites are persistently causing this error and which ones only seem to cause the error the first time the certificate is created. It just seems like quite a few websites are affected by this error message. I am not so much worried about the error message, but the performance issues - especially Google, Youtube and a couple of websites we use a lot. There is a noticeable drop in performance on those sites.

I will try the suggestions in the linked topic - editing these files authexceptioniplist and nomitmsiteiplist and see if this fixes the performance issues for Google Search and Youtube as well as fixing Youtube not working at all in E2G5.5.1pre version.

**Comment by Dalacor** [comment]
Adding Youtube to nomitmsitelist gets Youtube working in E2G-5.5.1pre. However this is not required in previous versions of E2G. So definitely something broken in latest version of E2G.

Upon further testing of Google and Youtube, I think the underlying cause of any performance issues is with the actual websites (probably loading a lot of scripts and elements). This is exacerbated when using E2G and MITM. Bing for example is unaffected and is quite snappy. But Google search, there is a definite lag after pressing enter after search term when in MITM mode.

Another website that I found to be really slow when using E2guardian (MITM is irrelevant) is this site - https://www.ashbrookschool.co.uk/

If you load this website on a browser that does not go through E2G - the website loads normally. If you are using ublock origin, the website works nearly as fast whether you are using E2G or not. But you disable Ublock origin and the website is really slow to load.

I think the fault is with the website having lots of elements to load and some elements on the website point to dead links or scripts. The website basically hangs for a few seconds the first time you load it if using E2guardian. I think E2guardian is hanging on dead links or something? So this is a good website to use to test how E2guardian handles problem websites like Youtube.

**Comment by philipianpearce** [comment]
Are you using the latest in the v5.5 branch?    

It is possible that this is related to bug #730 which was fixed after v5.5.1pre release.

(On my test rig using latest v5.5 - youtube works fine and there is no discernible difference in loading speed between using e2g or not, even though e2g does not support the h2 protocol which a browser talking direct to google sites will use).

**Comment by Dalacor** [comment]
I am using v5.5.1pre release and 5.4.5r as my testing versions. Didn't realise that anything had been released after 5.5.1pre. I will download the latest E2G and test. I have looked at the linked bug and that would explain the problems with imdb as well. I will update when I have upgraded and tested.

**Comment by Dalacor** [comment]
I have installed the very latest version. Youtube is working as in the IMDB website. So has definitely been fixed. Can't comment on speed as working away from home atm and Internet speed is not the best where I am currently. So will close this topic as the reported issue has been solved.
