### ISSUE TITLE
Search Terms Field not showing in E2g-5.5.1pre log file

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#741]
Google and Bing Search terms not showing in search term field in E2G-5.5.1pre. Not an issue in earlier versions of E2guardian. The config files are the same obviously. Makes no difference using safe mode search or not.

It looks to me like not all the fields are displaying in E2G5.5.1pre log file, and the order of some fields is slightly from stable version of E2G.

**Comment by philipianpearce** [comment]
Please would you post a sample of the log file with this problem?

(I am unable to replicate here with my test set up).

logfileformat is 7 or 8??
and usedashforblank setting?

**Comment by Dalacor** [comment]
I will upgrade to the most recent version of E2guardian as I am on 5.5.1pre. This may have already been fixed in the very latest patch. I am on the version where Youtube will not load, which you said has now been patched. I will test on latest patch and see if the problem is still present.

**Comment by Dalacor** [comment]
I have now updated to the very latest version. Still seeing the same issue. But I realise it is not limited to just search terms. Proxy server details are also missing etc. I think it has more to do with the new logging functionality in E2g 5.5 than anything else. I have read the documentation on the new logging system and it is not clear if 5.5 requires one to set search terms and proxy etc anywhere or if I am looking in the wrong file? I am looking in e2guardian/var/log.e2guardian and reading that file as I always have.

**This is what the log looks like in E2guardian 5.4 version**

`1660312879.093		-	192.168.0.12	192.168.0.12	https://www.google.co.uk/search?q=dragons&source=hp&ei=cF32YuSYJ8K68gKc3qWACg&iflsig=AJiK0e8AAAAAYvZrgEuD4qr6InIJwesCN1Mhkf9bN_3t&ved=0ahUKEwjkkKDau8H5AhVCnVwKHRxvCaAQ4dUDCAg&uact=5&oq=dragons&gs_lcp=Cgdnd3Mtd2l6EAMyCwgAEIAEELEDEIMBMgsIABCABBCxAxCDATIICC4QgAQQsQMyCwguEIAEELEDEIMBMggILhCABBCxAzIICAAQgAQQyQMyBQgAEJIDMgUIABCSAzILCAAQgAQQsQMQgwEyBQgAEIAEOg4ILhCABBCxAxDHARDRAzoICC4QsQMQgwE6FAguEIAEELEDEIMBEMcBENEDENQCOggIABCxAxCDAToICC4QgAQQ1AI6CAgAEIAEELEDUAZYrgZgoQhoAHAAeACAAecFiAHdDJIBBzQtMi4wLjGYAQCgAQE&sclient=gws-wiz	GET	200	620799	text/html	-	-	1819	-	0	-	-295	-	group1	1	dragons	8080:PM::def`

**However in 5.5 it looks like this:**

`2022.08.12 14:54:42  192.168.0.12 
https://www.google.co.uk/search?q=macros&source=hp&ei=21v2YujfMYzngAbZ_rX4DA&iflsig=AJiK0e8AAAAAYvZp68_Bj_cW0idXbIuTHobpKRSsVldv&ved=0ahUKEwiouZuZusH5AhWMM8AKHVl_Dc8Q4dUDCAg&uact=5&oq=macros&gs_lcp=Cgdnd3Mtd2l6EAMyCwguEIAEELEDENQCMhEILhCABBCxAxDHARDRAxDUAjIFCAAQgAQyCAgAEIAEELEDMggIABCABBCxAzIICAAQgAQQsQMyCAgAEIAEELEDMgUIABCABDIFCAAQgAQyCAgAEIAEELEDOg4IABCPARDqAhCMAxDlAjoLCAAQgAQQsQMQgwE6EQguEIAEELEDEIMBEMcBENEDOgsILhCABBCxAxCDAToOCC4QgAQQsQMQxwEQ0QM6FAguEIAEELEDEIMBEMcBENEDENQCOgsILhCABBDHARDRAzoICC4QsQMQgwE6CAgAELEDEIMBUOgLWMUQYPkVaABwAHgBgAGiCIgBrBuSAQ0yLTEuMC4yLjIuMC4xmAEAoAEBsAEK&sclient=gws-wiz  GET 158428 -217  1 200 text/html 192.168.0.12 group1   - - `

Both systems were setup as defaults with just MITM turned on. The log fields are different order and the new version is not showing proxy server port 8080 or search term in search field. It is however showing the date and time which is a nice improvement over the Linux time format.

**Comment by philipianpearce** [comment]
The new logging/debug system has not changed the format of the access.log. I.e. There is no change to logging formats in v5.5. 

However, the way defaults are set has been change and there is a bug in the default setting for logfileformat it should be 8 and is being set to 1. See #743. Now fixed in v5.5 and v5.6.dev. 

Thanks for reporting. 

To fix without using latest v5.5 set logfileformat = 8 in e2guardian.conf. 

Philip

**Comment by Dalacor** [comment]
Just tested this now. My config was already at default 8, so didn't explicitly enable it as I thought it would use 8. Now enabled it explicitly.

The search terms and proxy server settings etc are all showing as expected. The time is now showing in Linux time format instead of 24 hour time. I presume that this is necessary to get around issues with time zones etc? It's just really handy to be able to see the actual time in the logs, without having to convert it into a format humans can read.

Happy to close this issue as problem has been fixed.
