### ISSUE TITLE
e2guardian.service fails to start post edit

### ISSUE THREAD

**Issue by fleamour** [e2guardian/e2guardian#744]
```
> systemctl status e2guardian.service
× e2guardian.service - E2guardian Web filtering
     Loaded: loaded (/usr/lib/systemd/system/e2guardian.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Thu 2022-09-01 10:43:19 BST; 6s ago
    Process: 3191 ExecStart=/usr/sbin/e2guardian (code=exited, status=1/FAILURE)
        CPU: 70ms
```

When applying edits to bannedsiteslist & saving via nano e2guardian will fail to start with above error. Reverting to stock lets e2guardian start:

```
● e2guardian.service - E2guardian Web filtering
     Loaded: loaded (/usr/lib/systemd/system/e2guardian.service; enabled; preset: disabled)
     Active: active (running) since Thu 2022-09-01 10:45:10 BST; 9s ago
    Process: 3882 ExecStart=/usr/sbin/e2guardian (code=exited, status=0/SUCCESS)
      Tasks: 203 (limit: 4915)
        CPU: 97ms
     CGroup: /system.slice/e2guardian.service
             └─3887 /usr/sbin/e2guardian

```

**Comment by philipianpearce** [comment]
Likely that the file permissions are being changed in the edit - file must be owned by the e2guardian user. 

For more details on reason for failure look in the system log (syslog often called messages in /var/log).

**Comment by fleamour** [comment]
I will chown recursively after nano edit. 

EDIT: Did not work unless need to chown as root? When nano edit back to previous # then it all works again, bit useless if cannot edit config file. It's journalctl on openSUSE Tumbleweed, but nothing telling.

**Comment by fleamour** [comment]
Likely a config issue. I only discovered Wiki by blindly stabbing around github. Not intuitive for new users, but sure glad it there, now.
