### ISSUE TITLE
e2guardian confuses *.com urls and .com file extensions

### ISSUE THREAD

**Issue by programmerPhysicist** [e2guardian/e2guardian#754]
e2guardian seems to confuse *.com url's with the banned file extension *.com. Below is only one example from my logs:

`1672293977.879		-	192.168.1.4	192.168.1.4	https://docs.google.com/sharing/init?id=1xNm5_97MczDTh1gnObZ8Hl7anw8t82EVycMk0Pc4O1A&resourcekey=%5B%221xNm5_97MczDTh1gnObZ8Hl7anw8t82EVycMk0Pc4O1A%22%2Cnull%5D&themeColor=1&foreignService=ritz&gaiaService=wise&shareService=ritz&subapp=10&popupWindowsEnabled=true&shareUiType=default&hl=en&authuser=0&rand=1672293977633&origin=https%3A%2F%2Fdocs.google.com	GET	403	0	-	-	-	6	-	900	*DENIED* hw261: Banned file extension: .com	0	-	group1	1	-	8080:PM::def`

To reproduce, simply add .com to the the banned extensions. Go to, for example, https://www.sitejabber.com/search?q=google.com and it should be blocked. Any number of other websites which also have website names in a query string, should also probably work, provided they aren't in an exception list.

**Comment by philipianpearce** [comment]
This behavior (of checking the url for an extension) was requested by the community as not all sites send a tag with the filename and extension when serving a file.   However, we should be removing the cgi part (?xxxx....) of the url before doing this check.   I have raised bug issue #756 and will fix in v5.5.

**Comment by philipianpearce** [comment]
Thanks for reporting this.  Now fixed in v5.5 branch.
