### ISSUE TITLE
urlregexplist, urlredirectregexplist, searchregexplist and icap client mode

### ISSUE THREAD

**Issue by phtagn** [e2guardian/e2guardian#755]
Hi,

I'm having issues with urlregexplist, urlredirectregexplist an searchregexplist in icap client mode. In my set up Squid handles MITM and e2g is running in Icap client mode on port 1345. Both REQMOD and RESPMOD are enabled and they both work. On Squid's side I can see the requests being made in the logs and I can see that they are correctly received by e2g in the debug logs.

However, whatever I put in those two lists has absolutely no effect. Even something as simple as putting:
"zombie" -> "spring" in urlregexplist does not change anything. I tested it on google, bing and duckduckgo.

In site.story, I have enabled
```
function(icapsquidbump)
if(true) return true
```

I"ve looked at the google group and the issues presented here, but I cannot find a way to make it work. Please could you point me in the right direction ?

Thanks,

Jonathan

**Comment by philipianpearce** [comment]
Are you testing with v5.5 or an earlier version?  (v5.5 has much better debug features and is near stable release).

**Comment by phtagn** [comment]
~~V5.3 at the moment, which is the package available on Debian stable. Do you by any chance have a .deb available with 5.5 or would I need to compile it from source ?~~
I've found the deb packages, apologies for the dumb question. I just love the new release, thank you so much. I think I have everything I need with the new debug system to find out what's wrong. Again, thank you very much.
