### ISSUE TITLE
Segmentation fault - Corrupted TEMPLATE returns

### ISSUE THREAD

**Issue by moosty-moo** [e2guardian/e2guardian#759]
Hi,

I'm getting random seg faults with version 5.4.3r.
The same happened with version 5.3.

e2guardian[14728]: Corrupted TEMPLATE returns: https://northeurope1-mediap.svc.ms
kernel: [4833446.927146] e2guardian[16907]: segfault at 7f3588823350 ip 00000000004a71ff sp 00007f30aa078fb0 error 4 in e2guardian[407000+e2000]

It appears to happen several times a day with different URL's listed.

Any ideas?

Regards, Chris.

**Comment by moosty-moo** [comment]
It must come from the fact that html.size() is zero and the sz = html.size() - 1 makes a negative sz. This gives a -1 index to an array, hence the seg fault. :(

The code is:
`
void HTMLTemplate::display_hb(String &ebody, String *url, std::string &reason, std::string &logreason, std::string &categories,
                          std::string *user, std::string *ip, std::string *host, int filtergroup, String grpname, String &hashed , String &localip, String &extflags) {
 #ifdef E2DEBUG
     std::cerr << thread_id << "Displaying TEMPLATE" << std::endl;
 #endif
     String line;
     bool newline;
     **unsigned int sz = html.size() - 1**; // the last line can have no thingy. erm... carriage return?
`
The line is:
`unsigned int sz = html.size() - 1; // the last line can have no thingy. erm... carriage return?`
So, "html" size is zero and sz is made to be -1
It then falls through to

`ebody += html[sz].toCharArray();
`

which creates the segfault. 
Shouldn't the `unsigned int sz = html.size() - 1; ` test for a zero size first?

Also, why would there be nothing in "html" ?

**Comment by moosty-moo** [comment]
How's about changing 
`unsigned int sz = html.size() - 1; // the last line can have no thingy. erm... carriage return?`
TO
 unsigned int sz = 0;
 if (html.size() >0) sz = html.size() - 1; // the last line can have no thingy. erm... carriage return?

**Comment by philipianpearce** [comment]
Thanks for investigation and reporting this.

html.size() of 0 indicates an empty (or corrupt) template file. So check that your template files are readable and that they end with a line with a single space in it properly terminated with a newline.    

There is however a bug here which I will look at as this should result in an error being reported on reading the template file and should not result in a segfault when it is being used.   Also the code seems to assume that template file ends with a blank line which is dangerous!

**Comment by philipianpearce** [comment]
I was unable to replicate segfault on my dev platform and so am not sure whether if was the 
`unsigned int sz = html.size() - 1;`  or the          ` if (html[i + 1][0] != '-') {` which was causing the segfault.

However, I have amended the logic to ensure neither expression will now segfault and also that  empty template are reported on start-up.

Only fixed in latest stable branch (v5.5) at present.

**Comment by philipianpearce** [comment]
Work round for  previous  versions  (v5.3, v5.4).

Ensure all template files have a final line which consists of just a single space character followed by a new line character.
