### ISSUE TITLE
E2G v5.5.3 : dockermode

### ISSUE THREAD

**Issue by KDGundermann** [e2guardian/e2guardian#761]
when enabling the dockermode all output is directed to stdout/stderr  in [Logger.cpp](https://github.com/e2guardian/e2guardian/blob/ca3e2070497ad77d93c424cbc0ad67886b6c3732/src/Logger.cpp#L390)

But this gets overwritten by [this](https://github.com/e2guardian/e2guardian/blob/ca3e2070497ad77d93c424cbc0ad67886b6c3732/src/OptionContainer.cpp#L523)

```
    String temp = cr.findoptionS("set_accesslog");
    if (!temp.empty()) {
        if (!loggerConf.configure(LoggerSource::accesslog, temp))
            return false;
    } else {
            log.log_location = cr.findoptionS("loglocation");
            if (log.log_location.empty()) {
                log.log_location = __LOGLOCATION;
                log.log_location += "/access.log";
            }
            if (!e2logger.setLogOutput(LoggerSource::accesslog, LoggerDestination::file, log.log_location))
                return false;
    }

```

Which reads: 
if there is NO set_accesslog in the config then send the log to __LOGLOCATION/access.log which is a little bit surprising

**Comment by KDGundermann** [comment]
Suggestion:
A: Only enable the access log if there is an explicit `set_accesslog` in the config (the same as with set_requestlog)
B: Start the configuration with a default for enabled access log and loglocation which may later be overwritten by `dockermode = on`

**Comment by KDGundermann** [comment]
some more inconsistence in OptionContainer:
- using `set_responselog` will also enable `log.log_responses = true`
- using `set_storytrace` will NOT enable `logger.SB_trace` but you have to use an additional `storyboardtrace = true` in the config

**Comment by philipianpearce** [comment]
@KDGundermann   Thanks very much for the input.   See my more specific comments in the pull request
