### ISSUE TITLE
 e2guardian 5.3.4 SB warning: Undefined list

### ISSUE THREAD

**Issue by vincentmli** [e2guardian/e2guardian#764]
Hi,

I installed e2guardian 5.3.4 on  Ubuntu 20.04, and copied the e2guardian 4.1.2 configurations  from Ubuntu 16.04, fixed some missing configurations and the e2guardian started ok, but I get many SB warning like below:

```
Feb 28 12:19:47 srv-bk-gw e2guardian[2082]: SB warning: Undefined list /etc/e2guardian/examplef1.story list searchterms used at line 23 of /etc/e2guardian/common.story
Feb 28 12:19:47 srv-bk-gw e2guardian[2082]: SB warning: Undefined list /etc/e2guardian/examplef1.story list change used at line 29 of /etc/e2guardian/common.story
Feb 28 12:19:47 srv-bk-gw e2guardian[2082]: SB warning: Undefined list /etc/e2guardian/examplef1.story list headermods used at line 31 of /etc/e2guardian/common.story
Feb 28 12:19:47 srv-bk-gw e2guardian[2082]: SB warning: Undefined list /etc/e2guardian/examplef1.story list addheader used at line 32 of /etc/e2guardian/common.story
Feb 28 12:19:47 srv-bk-gw e2guardian[2082]: SB warning: Undefined list /etc/e2guardian/examplef1.story list override used at line 33 of /etc/e2guardian/common.story
Feb 28 12:19:47 srv-bk-gw e2guardian[2082]: SB warning: Undefined list /etc/e2guardian/examplef1.story list banned used at line 35 of /etc/e2guardian/common.story
Feb 28 12:19:47 srv-bk-gw e2guardian[2082]: SB warning: Undefined list /etc/e2guardian/examplef1.story list redirect used at line 36 of /etc/e2guardian/common.story
```

I think it is 5.3.4  e2guardian filter group configuration files `e2guardianf*. conf` requires 
`storyboard` to be configured for each filtergroup, since I have 5 filter groups, so I configured `storyboard = '/etc/e2guardian/examplef1.story` for each filter group like:

```
$ sudo grep 'storyboard' e2guardianf*.conf
e2guardianf1.conf:storyboard = '/etc/e2guardian/examplef1.story' 
e2guardianf2.conf:storyboard = '/etc/e2guardian/examplef1.story'
e2guardianf3.conf:storyboard = '/etc/e2guardian/examplef1.story'
e2guardianf4.conf:storyboard = '/etc/e2guardian/examplef1.story'
e2guardianf5.conf:storyboard = '/etc/e2guardian/examplef1.story'
```
and I did not make any changes to the `/etc/e2guardian/examplef1.story` since I am not familiar to the example1.story, will it be ok I can ignore the SB warning?

```
$ sudo cat examplef1.story 
.Include</etc/e2guardian/common.story>
.Include</etc/e2guardian/site.story>

# Add any altered functions for this filtergroup here
# They will overwrite library or site level definitions

# To allow unfiltered access to this group 
# uncomment next 4 lines
#function(checkrequest)
#if(true) return setexception
#function(thttps-checkrequest)
#if(true) return setexception

# To block all access to this group 
# uncomment next 4 lines
#function(checkrequest)
#if(true,,105) return setblock
#function(sslexceptioncheck)
#function(localsslcheckrequest)

# Note: Blanket blocks are checked after exceptions
# and can be used to make a 'walled garden' filtergroup

# To create blanket block for http 
# uncomment next line and one condition line.
#function(checkblanketblock)
#if(true,,502) return setblock  # = ** total blanket
#if(siteisip,,505) return setblock  # = *ip ip blanket

# To create blanket block for SSL 
# uncomment next line and one condition line.
#function(sslcheckblanketblock)
#if(true,,506) return setblock  # = **s total blanket
#if(siteisip,,507) return setblock  # = **ips ip blanket

# To limit MITM to sslgreylist
# replaces onlymitmsslgrey e2guardianf1.conf option
# uncomment the next 2 lines
#function(sslcheckmitm)
#if(true) return sslcheckmitmgreyonly


# SNI checking - overrides default action when no SNI or TSL is present on a 
#    THTTPS connection
# To allow (tunnell) non-tls and/or non-sni connections uncomment the next 3 lines
#function(checksni)
#ifnot(tls,,511) return setexception  # change to setblock to block only non-tls
#ifnot(hassniset,,512) return setexception
```

**Comment by KDGundermann** [comment]
Hi Vincent,

have you read [Upgrading_to_V5](https://github.com/e2guardian/e2guardian/blob/v5.5/notes/Upgrading_to_V5) ??

Yes, V5 comes with some storybook files and examplef1.story is the one which could be used in your different groups.
common.story has several functions which are looking for some list files, if the list file does not exist you will get the warning.

You have three options:
1. ignore the warnings (yes they are annoying)
2. create empty list files (tedious)
3. comment the lines in common.story (not recommended)

**Comment by vincentmli** [comment]
it is good to hear the warning can be ignored, I will keep that in mind. Before I read your note, I  resort to manually compile 4.1.5 and install on Ubuntu 20.04 :)

**Comment by philipianpearce** [comment]
Getting lots of these messages indicates that the lists are not being defined correctly in e2guardian.conf and e2guardianf1.conf and that your lists are not being read in.  The format for list definition this has changed in v5.

Have you followed the steps in [https://github.com/e2guardian/e2guardian/blob/v5.5/notes/Upgrading_to_V5.4? ](https://github.com/e2guardian/e2guardian/blob/v5.5/notes/Upgrading_to_V5)

As suggested, it is better to install v5.4 with the default set of configuration files and then edit these to reflect the settings you want.     The format and names of the top list files have not changed and so it is safe to copy your v4 lists over the v5 ones (but these will be in a different directory to v4).

The default .conf files have been reorganized with lots of helpful comments. Also look at the README files in the default list directories.

Note v5.3 is no longer supported - use v5.4 or v5.5.

**Comment by philipianpearce** [comment]
No response so closed
