### ISSUE TITLE
Installation/build issues (Arch Linux)

### ISSUE THREAD

**Issue by lukasjenks** [e2guardian/e2guardian#767]
Whether trying to install `e2guardian` from the [AUR](https://aur.archlinux.org/packages/e2guardian), cloning/building the package manually, or cloning from the [AUR](https://aur.archlinux.org/packages/e2guardian) and installing with the `makepkg -si` build process, it seems that me and several people who have commented on the [AUR](https://aur.archlinux.org/packages/e2guardian) page since at least December 2022 are not able to install this tool, due to an error in the build process triggered by an `m4` process:

```
==> Starting build()...
+ cp README.md README
+ aclocal -I m4
configure.ac:12: error: AM_INIT_AUTOMAKE expanded multiple times
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:9: the top level
/usr/share/aclocal-1.16/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:12: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: autom4te failed with exit status: 1
==> ERROR: A failure occurred in build().
    Aborting...
```

I just wanted to open this issue for visibility into this issue and to see if it could be something code related that could be addressed since it seems to be present regardless of configuration.

**Comment by mhdna** [comment]
@lukasjenks It has nothing to do with e2g itself.
The AUR package hasn't been updated in quite a long time.

I've just updated the PKGBUILD for it, and you should be able to install it just fine.
