### ISSUE TITLE
Feature Request exempt IP Addresses from logging

### ISSUE THREAD

**Issue by Dalacor** [e2guardian/e2guardian#769]
E2guardian gives the ability to exempt computers from being filtered, but those computers connections are still logged. It would be useful to completely exempt some devices from E2guardian so they are not logged nor filtered. Currently E2guardian only supports exempting websites and IP Addresses being connected to from being logged, but not the Source IP Address.

**Comment by philipianpearce** [comment]
Try this:

edit preauth.story:

Replace  if(clientin,exceptionclient) return setexception
with   if(clientin,exceptionclient) return multisetexceptionnolog

and add new function:

function(multisetexceptionnolog)
if(true) setnolog
if(true) return setexception

**Comment by philipianpearce** [comment]
@Dalacor Did this work? Can I close?

**Comment by Dalacor** [comment]
At the moment, I have not gone time to work on E2guardian as I am busy with other urgent projects. I will close this for the time being and re-open if necessary. Thank you
