### ISSUE TITLE
SSL MITM (development branch) Version 3.3.2

### ISSUE THREAD

**Issue by tachtler** [e2guardian/e2guardian#77]
Hi,

I'm testing with e2guardian and SSL MITM.

I have a special problem: When I start e2guardian and clear the file space of generated certificates (/var/lib/ssl_e2guardian) and I enter following url at the Firefox 38.0.1 ESR Browser under CentOS-7, everything is fine - the EICAR-Virus was detected:  https://secure.eicar.org/eicar.com.txt

When I enter after that https://www.google.de - The browser said 
"secure connection could not established."

It's always, when I type in a direct https:// url after I opened a few other HTTPS-Connections.

After stopping e2guardian, clearing the certificates file space (/var/lib/ssl_e2guardian) and restart e2guardian, https://www.google.de works. 

I can see some error output in /var/log/messages:
```bash
e2guardian[5333]: error creating certificate sub-directory
```

See the list of the certificates file space (/var/lib/ssl_e2guardian), not all have the same permissions:
```bash
# ls -la /var/lib/ssl_e2guardian
total 0
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:59 0A
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:59 0E
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:59 20
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:58 29
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:58 53
d--x--xrwx 2 e2guardian e2guardian  6 Jun 30 13:59 57
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 14:04 6C
d--x--xrwx 2 e2guardian e2guardian  6 Jun 30 14:04 7A
d--x--xrwx 2 e2guardian e2guardian  6 Jun 30 14:04 84
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:59 9B
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:59 A5
d--x--xrwx 2 e2guardian e2guardian  6 Jun 30 13:59 C3
```

Can I sent you some files or "on-the-fly" generated certificates or something else. to help to find out what is the problem?

Thank you.
Klaus.

**Comment by tachtler** [comment]
Hi,

I can reproduce the problem by doing following steps:

1. Browser open URL https://...whatelse
2. Browser said "secure connection could not established."
3. ```chmod -R 777 /var/lib/ssl_e2guardian```
4. Browser open URL https://...whatelse
5. Browser said "secure connection could not established."
6. ```chmod -R 777 /var/lib/ssl_e2guardian```
7. Browser open URL https://...whatelse
8. Browser said "secure connection could not established."
9. ```chmod -R 777 /var/lib/ssl_e2guardian```

Example for: ```/var/lib/ssl_e2guardian```
```
0A
0A/13
0A/13/7B
0A/13/7B/375CC3881A70E186CE2172C8D1
```

After doing that, the certificate could be created and the site could be shown!

Hope this helps?
Klaus.

**Comment by databeille** [comment]
As a dirty fix, I would write certs on a FAT32 partition as it does not deal with rights management.
Sorry, I can't help for making the program sets rights properly :/

**Comment by tachtler** [comment]
Hi,

I use e2guardian on a Linux server, so fat32 is not the partition type i would like to prefer under linux.

But the folder one step over that does NOT have the rights like that:
´´´# ls -la /var/lib | grep ssl_e2guardian
drwxr-xr-x  12 e2guardian e2guardian   96 Jun 30 14:39 ssl_e2guardian
´´´

**Comment by databeille** [comment]
I understand, I uses Linux too :)
As I said, it is a quick and dirty fix to help you in your trouble. You can use a virtual drive to do so.

I do not see any place where rights are properly set by e2guardian, seems done on a fly without worrying, but c++ is not my cup of tea.

**Comment by tachtler** [comment]
Hi,

so, there MUST be a place inside e2guardian where the rights of the folders are set, because the folder has following rights
```
# ls -la /var/lib | grep ssl_e2guardian
drwxr-xr-x  12 e2guardian e2guardian   96 Jun 30 14:39 ssl_e2guardian
```
So normally, when you create a new file or directory, they would like have following rights:
```
-rw-r--r-- 1 root       root        0 Jun 30 15:54 test
drwxr-xr-x 2 root       root        6 Jun 30 15:54 testfolder
```
BUT the folders and subfolders created by e2guardian while creating certificates via SSL MITM "on-the-fly" have following right, normally:
```
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:35 0A
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:35 0E
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:35 20
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:41 31
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:39 4B
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:38 53
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:38 57
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:38 84
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:35 9B
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:35 A5
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 15:35 C3
```

So, I think - or I'm totally wrong - there MUST be a code for setting the rights, while creating the certificates (and folders) "on-the-fly".

Thank you!
Klaus.

**Comment by nerijus** [comment]
(You can use ls -ld /var/lib/ssl_e2guardian instead of ls -la /var/lib | grep ssl_e2guardian)
e2guardian runs as e2guardian user, so it creates directories owned by e2guardian user, not root.

**Comment by tachtler** [comment]
Hi,

thank you i know, I create the example file ```test``` and ```testfolder``` as user ```root`` only for example to say - creating a directory with mask 777 - must be a program part of e2guardian.

Sorry, when I posted some thing incomprehensible.

Klaus.

**Comment by databeille** [comment]
In fact, it is ok if files and directories have chmod 0007. I agree with nerijus.
It would be better to understand why some other programs need other rights.
Isn't openSSL bundled into e2guardian ? what about the http responder ?

**Comment by tachtler** [comment]
Hi,

how does e2guaridan create the folders and subfolders? I'm not a c++ programmer, but maybe someone who wrote that code or who understands the code and knows where it is, could keep an eye on it and checks, whats going on there?

Thank you for the help!
Klaus.

**Comment by tachtler** [comment]
Hi,

by the way - squid with ssl_bump creates some files(for example) under
```
/var/lib/ssl_db/certs/
-rw-r----- 1 squid squid 3197 Jun 12 16:22 057EAA1695735435509787A575F8F65CD6A7D8C5.pem
```
with special permissions too.

Klaus.

**Comment by tachtler** [comment]
Hi,

I've seen some errors too in /var/log/messages (journal), the error occurs often directly after a fault by creating teh "on-the-fly" certificates:
```
Jun 30 16:13:20 server50 e2guardian[7300]: error creating certificate sub-directory
Jun 30 16:13:21 server50 e2guardian[8226]: error creating certificate sub-directory
Jun 30 16:14:03 server50 e2guardian[7218]: error creating certificate sub-directory
Jun 30 16:14:11 server50 kernel: e2guardian[8171]: segfault at 94220 ip 00007f171825aebc sp 00007ffc7ad41900 error 4 in libcrypto.so.1.0.1e[7f1718179000+1bd0
00]
```
Klaus.

**Comment by tachtler** [comment]
<h3>*** PROBLEM SUMMARY POST, PLEASE HELP, THANK YOU! ***</h3>

Hi,

I'm testing with e2guardian and SSL MITM (man-in-the-middle).

I have a special problem: When I start e2guardian with cleared folder space where the generated certificate files are stored --> <b>```/var/lib/ssl_e2guardian```</b>, sometimes the creation of a directory (folder) especially a sub folder, was done with <b>FALSE PERMISSIONS</b>, see following:
```
# ls -la /var/lib/ssl_e2guardian
total 0
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:59 0A (normal)
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 13:58 53 (normal)
d--x--xrwx 2 e2guardian e2guardian  6 Jun 30 13:59 57 (FALSE)
drwxrwxrwx 3 e2guardian e2guardian 15 Jun 30 14:04 6C (normal)
d--x--xrwx 2 e2guardian e2guardian  6 Jun 30 14:04 7A (FALSE)
d--x--xrwx 2 e2guardian e2guardian  6 Jun 30 14:04 84 (FALSE)
```
The problem is, at the folders marked with <b>(FALSE)</b>, a creation of a sub folder or certificate file, was <b>NOT</b> possible, <b>or will NOT be done by other reasons</b>?

<b>When I correct the permissions manually, while e2guardian is running, like this:</b>

1.a. Browser open URL https://...whatelse
1.b. Browser said "secure connection could not established."
1.c. <b>```chmod -R 777 /var/lib/ssl_e2guardian```</b>

2.a. Browser open URL https://...whatelse
2.b. Browser said "secure connection could not established."
2.c. <b>```chmod -R 777 /var/lib/ssl_e2guardian```</b>

3.a. Browser open URL https://...whatelse
<b>3.b. Encrypted site will be shown!</b>

...after that, the sub folders and the certificate could be created perfectly.

See, for example a structure for the sub folders at <b>```/var/lib/ssl_e2guardian:```</b>
```
0A
0A/13
0A/13/7B
0A/13/7B/375CC3881A70E186CE2172C8D1
```
I can see following error messages in the <b>```/var/log/messages```</b> (journal) too:
```
Jun 30 16:13:21 server50 e2guardian[8226]: error creating certificate sub-directory
Jun 30 16:14:03 server50 e2guardian[7218]: error creating certificate sub-directory
Jun 30 16:14:11 server50 kernel: e2guardian[8171]: segfault at 94220 ip 00007f171825aebc
sp 00007ffc7ad41900 error 4 in libcrypto.so.1.0.1e[7f1718179000+1bd000]
```
<h4>Please, HELP!</h4>


Thank you!
Klaus.

**Comment by philipianpearce** [comment]
Klaus, 

What platform are you running on? 

Regards 

Philip Pearce 

----- Original Message -----

**Comment by tachtler** [comment]
Hi Philip,

I'm running on: CentOS Linux release 7.1.1503 (Core) (64-bit) virtual machine under KVM.

Klaus.

**Comment by fredbcode** [comment]
Possible fix #78

**Comment by fredbcode** [comment]
Ok fixed now (dev branch)

**Comment by fredbcode** [comment]
Fixed 3.2.0

**Comment by moderichEd** [comment]
Hi!
First of all, great tool!!
Unfortunately I'm getting the same error message in v5.5.3 :-(.
/var/lib/ssl_e2guardian has permissions drwxr-xr-x with e2guardian/e2guardian, permission in it's subfolders are all drwx------.
I guess that's the reason why it's running quite unstable; quite often connection to "the internet" works fine; but after some time it's starting to be unstable (my family starts to get annoyed ;-)).
Fur further information just ask; I'll try to help as good as possible!
Thanks a lot!!

**Comment by philipianpearce** [comment]
Hi, 

Glad you like e2guardian! 

This may be a similar problem, but is it not the same problem as #77 in v3.3.2! (e2g has had two major rewrites since that version). 

Check that the file system used for the store certs has sufficient inodes (A file system can run out of inodes, before it runs out of space as each file uses at least one inode. The effect is the same as running out of space - i.e. unable to create file or directory). 

Use df -i to check if this is happening. 

If you are running out of inodes then you will need to re-install on file system that has more inodes or create a new filesystem (or partition with more inodes and mount this on /var/lib/ssl_e2guardian. 

Regards 
Philip

**Comment by moderichEd** [comment]
Ok, df -i returns me a usage of <10%, so this shouldn't be an issue I guess...
Besides of this, e2guardian does it's job, but the error message still pops up in systemctl status...?

**Comment by philipianpearce** [comment]
If you are getting this message regularly, it indicates some issue with the underlying platform rather than e2g itself. It will still work as the cert for a host will be re-generated and used if one is not found in the stored certs. Having the certs cached on disk means that cpu time is saved by re-using the saved cert. 

What platform are you running on? (OS, memory, RAM etc).

**Comment by moderichEd** [comment]
Hi!
E2Guardian is running on a Raspberry 3 (ARMv7 processor with 1GB RAM;
running with Raspbian 9).
Thanks!
Greetings,
Matthias

BTW: I did a lot of things to get it running, so I'll try to write a kind
of documentation or whatever since I'm quite sure that I've forgotten why I
did certain things :-). Would you mind to review this; maybe this would
help other users in future?
Anyway; this will take some time since children are quite time consuming
;-)...

Am Mi., 16. Aug. 2023 um 13:23 Uhr schrieb Philip Pearce <
***@***.***>:

> If you are getting this message regularly, it indicates some issue with
> the underlying platform rather than e2g itself. It will still work as the
> cert for a host will be re-generated and used if one is not found in the
> stored certs. Having the certs cached on disk means that cpu time is saved
> by re-using the saved cert.
>
> What platform are you running on? (OS, memory, RAM etc).
>
