### ISSUE TITLE
error: There is some problem with ‘uint32_t’ is defined in header ‘<cstdint>’; makepgk.

### ISSUE THREAD

**Issue by Arjow** [e2guardian/e2guardian#771]
failed to makepgk in archlinux. 
See here the log. 
There is some problem with ‘uint32_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’
In the includes from the ListContainer.hpp file.

[PKGBUILD_log.txt](https://github.com/e2guardian/e2guardian/files/11431341/PKGBUILD_log.txt)

**Comment by philipianpearce** [comment]
Fixed by @Arjow in pull request #772.   Many thanks!
