### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [e2guardian/e2guardian#774]

**Comment by philipianpearce** [comment]
e2guardian uses standard system calls to perform DNS resolution. These do not have an option for the specification of DNS resolver targets. 

Basically, DNS is a system-wide setting and not determined by an application. 

How are you determining your groups (i.e. which auth plugin are you using)?

**Comment by philipianpearce** [comment]
If you use transparent mode you can put the appropriate DNS resolver on your client devices and then switch off e2g looking up DNS with the useoriginalip set to on in e2guardian.conf.
