### ISSUE TITLE
Facing issue with some domains in e2guardian transparent filtering

### ISSUE THREAD

**Issue by SanketJaiswal24** [e2guardian/e2guardian#776]
I have setup e2guardian as a transparent proxy and I've also redirected my traffic to e2guardian HTTP and HTTPS ports using the below iptables rules.

 iptables -t nat -A PREROUTING -s 0.0.0.0/0 -p tcp --dport 443 -j REDIRECT --to-port 8443
 iptables -t nat -A PREROUTING -s 0.0.0.0/0 -p tcp --dport 80 -j REDIRECT --to-port 8080
  
And the above configuration works fine for domains like .google.com, github.com, and all other domains but I have some secure handful of domains that are not working and also not passthrough via e2guardian transparent proxy, showing me an error 

**curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled**

I have also tried to exclude them via the below configuration but still it shows me an error.

sslexclude {
       re.pay.com
}

**Comment by philipianpearce** [comment]
This appears to be an issue with OpenSSL v3. See https://stackoverflow.com/questions/75763525/curl-35-error0a000152ssl-routinesunsafe-legacy-renegotiation-disabled on how to fix this. 

Do this sites work OK when viewed from a browser (transparently proxied via e2g)? Do they work if the browser has the proxy set for e2g?

**Comment by SanketJaiswal24** [comment]
Yes Resolved Thanks
