### ISSUE TITLE
v5.5 MacOS 13.1 not supported

### ISSUE THREAD

**Issue by adrian-mih** [e2guardian/e2guardian#781]
tried installing on MacOS 13.1 e2guardian v5.5 and encountered

`FatController.cpp:1627:14: error: use of undeclared identifier 'sigtimedwait'`

it was previously reported [here](https://github.com/e2guardian/e2guardian/issues/662) and the docs mentioned no support for macos in v5.3 and v5.4 in [INSTALL](https://github.com/e2guardian/e2guardian/blob/v5.4/INSTALL#L202)

are the docs out of sync and it's still not supported or is it supported and I'm missing something during build?

**Comment by philipianpearce** [comment]
Yes, somehow the v5.5 INSTALL file had reverted to the pre-v5.3 version.

Now corrected in v5.5.

It remains true that we have no one in the community supporting a MACOS port.   

The suggestions in #662 are still valid.  i.e. to run on MACOS use a VM service (this will work in Intel MAC but may not on latest Apple chips).

Regards
Philip
