### ISSUE TITLE
Bypass URL in HTMLTemplate.cpp may lead to XSS

### ISSUE THREAD

**Issue by ozetta** [e2guardian/e2guardian#782]
Code with issues:
https://github.com/e2guardian/e2guardian/blob/v3.4/src/HTMLTemplate.cpp#L172-L182

Unlike the `-URL-` placeholder that will go through a `makeURLSafe` function, the `-BYPASS-` placeholder did not encode quotes or angle brackets, which may lead to XSS. Despite `"`, `<` and `>` are typically encoded in modern browsers, `'` remains not encoded in the URL. Therefore, if the template contains something like this:

```
<a href='-BYPASS-'>I acknowledge to access the website at my own risk</a>
```

A crafted URL that triggers the filter warning page could result in universal XSS:
```
http://example.com/Variants/AVTest'onfocus='eval(window.name)'name='z'z='#z
```

The resulting template page will look like this:
```
<a href='http://example.com/Variants/AVTest'onfocus='eval(window.name)'name='z'z='#z'>I acknowledge to access the website at my own risk</a>
```

**Comment by philipianpearce** [comment]
Fixed in all supported versions (v5.4, v5.5 and v5.6.dev).

@ozetta Thanks for spotting this.    But I'm puzzled as to why you are checking a version (v3.4) that is very old and no longer supported.

**Comment by ozetta** [comment]
Thanks for the quick fix, and I guess I somehow selected the wrong version tag (which was the oldest one) after I searched the related file in github when I was preparing the description.
I have tested on version v5.4, v5.5 and v5.6.dev and the bug is fixed.

**Comment by ozetta** [comment]
Thanks for the quick fix, and I guess I somehow selected the wrong version tag (which was the oldest one) after I searched the related file in github when I was preparing the description.
I have tested on version v5.4, v5.5 and v5.6.dev and the bug is fixed.
