### ISSUE TITLE
v. 5.4.7r not updating access.log

### ISSUE THREAD

**Issue by ghost** [e2guardian/e2guardian#789]
Prior to v. 5.4.7r I used to create the logs like so:

```
sudo rm /usr/local/var/log/e2guardian/access.log
sudo rm /usr/local/var/log/e2guardian/dstats.log
sudo rm /usr/local/var/log/e2guardian/request.log
sudo touch /usr/local/var/log/e2guardian/access.log
sudo touch /usr/local/var/log/e2guardian/dstats.log
sudo touch /usr/local/var/log/e2guardian/request.log
sudo chown -R nobody:nobody /usr/local/var/log/e2guardian/access.log
sudo chown -R nobody:nobody /usr/local/var/log/e2guardian/dstats.log
sudo chown -R nobody:nobody /usr/local/var/log/e2guardian/request.log
sudo chmod 755 /usr/local/var/log/e2guardian/*
```

And e2guardian could modify the log files just fine. I had the above commands as part of a script which I successfully installed on many machines.

But since I updated to v. 5.4.7r and after running the above commands, e2guardian stopped updating those logs.

Has anything changed in this version please?

**Comment by philipianpearce** [comment]
What version were you using before? 

Also note that the effect you describe would occur on any version, if e2g is running when you execute the script, as e2g will continue to write to the removed file until it is stopped and restarted (or in v5.5 the log rotate option is called). 

Philip

**Comment by ghost** [comment]
Thank you for your reply.

I was on the version immediately before it (v. 5.4.6). I am aware that a restarting of the service is required. I even frequently restart my computer.

Here is how the files look like:
```
-rwxr-xr-x 1 nobody nobody  517 Oct 13 15:22 access.log
-rwxr-xr-x 1 nobody nobody 9031 Oct 17 14:39 dstats.log
-rwxr-xr-x 1 nobody nobody  346 Oct 13 15:22 request.log
```

The setting files are exactly the same as the ones in v4.5.7. I simply upgrade, and logging stops working.

**Comment by ghost** [comment]
**UPDATE:**

1. Oh, the commands above do work. The issue is something else. I have been using iptables to enforce e2guardian like so:
```
sudo iptables -A INPUT -j ACCEPT -s 127.0.0.1 -p tcp --dport 8080
sudo iptables -I OUTPUT -p tcp -m owner ! --uid-owner 65534 -m multiport --dports http,https -j REJECT
sudo iptables-save -f /etc/iptables/iptables.rules
```

I just discovered that for some reason these changes aren't being kept upon a restart (ubuntu 20.04). I'm not sure if this is related to e2guardian. I'm still investigating. This is a serious security flaw for me.

2. My old version was v. 5.4.5, not 5.4.6.

**Comment by ghost** [comment]
Oops.. My mistake.. It turns out the saving command was wrong. It should be:
```
sudo iptables-save | sudo tee /etc/iptables/rules.v4
```
I will close it now. Thanks for your consideration.
