### ISSUE TITLE
is exist this file authexceptionsiteiplist ? 

### ISSUE THREAD

**Issue by szrce** [e2guardian/e2guardian#790]
hi when source build e2guardian i have get error this file is exist ? [authexceptionsiteiplist](https://github.com/e2guardian/e2guardian/blob/fcd3b16d2b6a925b49d816f6623cf35fa05d63fb/configs/lists/common/Makefile.am#L7C10-L7C33) , [exceptionclientlist](https://github.com/e2guardian/e2guardian/blob/9f78424d795482586067f231e52ca217a06ef812/configs/lists/example.group/Makefile.am#L38)

/work/stage/usr/local/etc/e2guardian/lists/common/authexceptionsiteiplist
install: authexceptionsiteiplist: No such file or directory

install: exceptionclientlist: No such file or directory
*** Error code 71

**Comment by philipianpearce** [comment]
Hi, which version are you building?

**Comment by szrce** [comment]
from here https://github.com/e2guardian/e2guardian/releases/tag/v5.5.4r @philipianpearce

**Comment by philipianpearce** [comment]
Thanks for reporting this issue.   Fixed in latest v5.5 branch.

**Comment by szrce** [comment]
thankyou, did you forget others?

https://github.com/e2guardian/e2guardian/blob/9f78424d795482586067f231e52ca217a06ef812/configs/lists/example.group/Makefile.am#L38

**Comment by philipianpearce** [comment]
Sorry, I missed that, now fixed.
