### ISSUE TITLE
ab test very slow, requests per second?

### ISSUE THREAD

**Issue by szrce** [e2guardian/e2guardian#802]
hi @philipianpearce  i hope u well,

i did build bellow version everything is good, but if i send request with  ab test, requests per second very slow if site nonblock however if site is block better than before ouput.

 **installed on pf machine hardware option bellow.**
- vmware pfsense 2.7.1 freebsd 14.current
- 4gb
- 1proc
by the way same result appliance device 

e2guardian 5.5.4r
Built with:  '--with-logdir=/var/log' '--with-piddir=/var/run' '--disable-avastd' '--enable-clamd' '--with-debug_high=off' '--with-debug_low=off' '--enable-dnsauth=on' '--disable-icap' '--disable-kavd' '--enable-sslmitm' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--disable-silent-rules' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd14.0' 'build_alias=amd64-portbld-freebsd14.0' 'CXX=c++' 'CXXFLAGS=-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing   -std=c++11 ' 'LDFLAGS=  -fstack-protector-strong ' 'LIBS=' 'CPPFLAGS=' 'CC=cc' 'CFLAGS=-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing ' 'CPP=cpp' 'PKG_CONFIG=pkgconf' 'PKG_CONFIG_LIBDIR=/root/pfSense/FreeBSD-ports/www/e2guardian/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig'

<b> if site is block </b>

```
rooke@debian:~$ ab -k -c 350 -n 2000 http://www.testa.com/ 
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.testa.com (be patient)
Completed 200 requests
Completed 400 requests
Completed 600 requests
Completed 800 requests
Completed 1000 requests
Completed 1200 requests
Completed 1400 requests
Completed 1600 requests
Completed 1800 requests
Completed 2000 requests
Finished 2000 requests


Server Software:        
Server Hostname:        www.testa.com
Server Port:            80

Document Path:          /
Document Length:        50134 bytes

Concurrency Level:      350
Time taken for tests:   2.038 seconds
Complete requests:      2000
Failed requests:        0
Keep-Alive requests:    0
Total transferred:      100352000 bytes
HTML transferred:       100268000 bytes
Requests per second:    981.59 [#/sec] (mean)  #this here
Time per request:       356.565 [ms] (mean)
Time per request:       1.019 [ms] (mean, across all concurrent requests)
Transfer rate:          48097.78 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    3   5.2      0      19
Processing:    11  324 152.2    289    1069
Waiting:        0  291  91.1    288     683
Total:         29  326 151.4    290    1070

Percentage of the requests served within a certain time (ms)
  50%    290
  66%    341
  75%    357
  80%    373
  90%    541
  95%    553
  98%    920
  99%    937
 100%   1070 (longest request)
```

<b> if site is unblock </b>

```
rooke@debian:~$ ab -k -c 350 -n 2000 http://www.testa.com/index.php
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking www.testa.com (be patient)
Completed 200 requests
Completed 400 requests
Completed 600 requests
Completed 800 requests
Completed 1000 requests
Completed 1200 requests
Completed 1400 requests
Completed 1600 requests
Completed 1800 requests
Completed 2000 requests
Finished 2000 requests


Server Software:        
Server Hostname:        www.testa.com
Server Port:            80

Document Path:          /index.php
Document Length:        49646 bytes

Concurrency Level:      350
Time taken for tests:   51.646 seconds
Complete requests:      2000
Failed requests:        631
   (Connect: 0, Receive: 0, Length: 631, Exceptions: 0)
Non-2xx responses:      631
Keep-Alive requests:    631
Total transferred:      68315040 bytes
HTML transferred:       68128803 bytes
Requests per second:    38.73 [#/sec] (mean)   #this here
Time per request:       9038.037 [ms] (mean)
Time per request:       25.823 [ms] (mean, across all concurrent requests)
Transfer rate:          1291.76 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    4   8.4      0      31
Processing:    64 7185 4616.4  10289   10600
Waiting:       64 7173 4608.3  10272   10598
Total:         81 7189 4619.3  10293   10600

Percentage of the requests served within a certain time (ms)
  50%  10293
  66%  10343
  75%  10370
  80%  10392
  90%  10452
  95%  10517
  98%  10560
  99%  10571
 100%  10600 (longest request)


```

**Comment by philipianpearce** [comment]
Hi, I've on;y just picked this up as I have been leave following an operation on 1st March.

What do the e2guarding access logs say?  Have you tuned e2guardian for such a test?
The defaults settings are for up to 4 users use ( < 100 req per sec), so tests like this will overload the default system.

Have you enabled the dstats log?   This will give you the information you need to tune e2guardian and see whether you have sufficient httpsworkers configured.    

Also, check processor and memory usage.

The smallest platform for production usage (for up to 200 users) would be 4 processors and 8G memory.

Also, what network speed do you have between testing and e2g target and to the target site on the internet?

For comparison have you tried the ab directly to the test site?

How did you configure e2g to block and allow the site?

**Comment by szrce** [comment]
thank you @philippearce,

how we can change, 4 users and how we tune 350 users or how we calculate 350 users max  req per sec , have you any hint?

also dstat output like bellow,


```
time		        httpw	busy	httpwQ	logQ	conx	conx/s	 reqs	reqs/s	maxfd	LCcnt
2024-04-19 13:37	2048	0	0	0	117	0	700	 2	18	 1
2024-04-18 17:38	1024	1	0	0	28	0	1017	 3	25	 1
2024-04-18 17:43	1024	2	0	0	6	0	6	 0	25	 1
2024-04-18 17:48	1024	3	0	0	5	0	5	 0	25	 1
2024-04-18 17:53	1024	3	0	0	4	0	4	 0	25	 1
2024-04-18 18:01	2048	5	0	0	3150	10	6019	 20	720	 1
2024-04-18 18:06	2048	2	0	0	2415	7	7769	 25	994	 1
```

**Comment by philipianpearce** [comment]
When testing it is a good idea to set dstatinterval to a short period say 10 secs - you will be able see what is happening better then as you will have a 10sec average figures and 10 sec snapshot of busy workers. 

Looking at your trace. If you divide maxfd by 2 = 497 gives you the maximum number of httpworkers used in any instant so for this load httpworkers = 800 would be fine. 

How much resources you need depends on how the users are using the net and how many sites are allowed through without content-filtering, but looking at one of our production systems with 1G internet feed and around average 350 users, the maxiumum reqs/s over 300 second average we see is around 200 req/s and peak at 3,000 busy workers. Some request responses may be in less than 10 ms, others many thousands of seconds. I would recommend at least 8 cores and 16G ram for this, you can then tune it once in production by looking at dstats and at system usage of processors and memory. 

Regards 
Philip

**Comment by szrce** [comment]
thank you for  u information, yesterday i did  check again with some settings, 

when you change bellow settings
## reportinglevel = 3 
to 
## reportinglevel = 2 or redirect 

so mean if e2g return html template the test output will be very slow 350 users to 200 per sec, but when you redirect some php page or just denied settings output very high 350 users 3k per sec.

do you have any idea, is it bug somewhere?

**Comment by philipianpearce** [comment]
With reportinglevel 3 (a page has to be generated from the template - very little time) and a full page with standard template is > 50k bytes of formatted html including an image is returned to the browser. 

So ~LAN bandwidth used = 50k bytes x 200 x 8 = plus TCP/IP overhead = >100Mbits/s 

With other settings or redirect the number of bytes returned will be much smaller (less than 1k). 

So ~LAN bandwidth used = 1k bytes x 3,000 x 8 = plus TCP/IP overhead = >30 Mbits/s 

When load testing, you are testing the hardware, network path and well as the software. 

So no, it is not a bug - it is more likely a bottle-neck in the network or in the host system network handling. 

Why are you load testing for blocking? In a working system block pages are not delivered very often, as users tend to avoid sites that have been blocked to them.

**Comment by szrce** [comment]
Actually we wanted to know how to calculate system requirements for RAM and CPU in order to handle different levels of user requests per second, such as 350, 500, and 1000 users, Sometimes e2guardian( version 5.3.1) giving kernel dumps average 300 users we cant reach devices, until reboot , all of issues that why 

We had thought that if we improve the system options, maybe we won't get dumps, sorry we couldn't think about other issues like internet speeds.

but you answered all questions, if i get another problem or getting kernel dumps this version  i will  share.

thank you for everything.

**Comment by philipianpearce** [comment]
@szrce v5.3.1 is now 5 years old and the final v5.3 release v5.3.5 4 years old, so no longer supported.
There a number of bug fixes since then that relate to intermittent crashes.  Most of these as related to apps that miss-use the http protocol (for example see a recent one with whatsapp which exposed a bug when bad headers are sent. #794).
Obviously, the greater the number and diversity of users, then the greater the chance of one of these apps being used and a crash happening.  So this may not be a capacity issue.    
If a hardware set-up works generally OK with v5.3 then it should be fine with v5.5.   At least, that is our experience on a linux platform.

**Comment by szrce** [comment]
yeap sure, i will check newer versions  thank you all informations.
