### ISSUE TITLE
openssl dependency / sslmitm

### ISSUE THREAD

**Issue by prlw1** [e2guardian/e2guardian#806]
e.g., `src/CertificateAuthority.cpp` uses openssl, and it is built unconditionally given that it is listed in `e2guardian_SOURCES`.

`configure.ac` will only look for openssl if `--enable-sslmitm` or `--disable-sslmitm` are used:
```
AC_MSG_CHECKING(for SSL MITM support)
AC_ARG_ENABLE(
sslmitm,
[AS_HELP_STRING([--enable-sslmitm@<:@=yes@:>@],[Enable support for the SSL MITM ])],
[
        AC_MSG_RESULT(yes)
        sslmitm=true
        SSLMITMSUPPORT=""
        AC_DEFINE([__SSLMITM],[],[Define to enable SSL MITM ])
        PKG_CHECK_MODULES([OPENSSL],[ openssl >= 1.0.1])
        CXXFLAGS="${CXXFLAGS} ${OPENSSL_CFLAGS}"
        LIBS="${LIBS} ${OPENSSL_LIBS}"
],
[
        AC_MSG_RESULT(no)
        sslmitm=false
        SSLMITMSUPPORT="!! Not compiled !! "
]
)
AM_CONDITIONAL(__SSLMITM, test "x$sslmitm" = "xtrue")
AC_SUBST(SSLMITMSUPPORT)
```
i.e., `./configure && make` will fail as openssl won't be searched for, and, among others `CertificateAuthority.cpp` will be compiled.

(BTW, `__SSLMITM` and `SSLMITMSUPPORT` are not used anywhere.)

The simplest fix would be to g/c the `sslmitm` option, and run `PKG_CHECK_MODULES([OPENSSL],[ openssl >= 1.0.1])` in `configure.ac` unconditionally.

The alternative is to fix the `AC_ARG_ENABLE` call to not search for openssl in the `--disable-sslmitm` case, as it was before e94c0b4bab6646eaeb1ca8e11c1004c1007f4b31, and then make use of `__SLMITM` in the `Makefile.am` files, having worked out the set of source files which use openssl.

**Comment by philipianpearce** [comment]
OK - I have removed --enable-sslmitm configure option and have configure check for openssl library, and add ssl library and include paths by default.
