### ISSUE TITLE
`std::memset`

### ISSUE THREAD

**Issue by prlw1** [e2guardian/e2guardian#808]
Essentially, we `#include <cstring>` and then use `memset` rather than `std::memset` and there isn't a `using namespace std`.

Admittedly I haven't been able to reproduce the `not in scope` error someone else reported to me, but given that we are using std11, I think the above makes sense.

**Comment by philipianpearce** [comment]
I agree, I will change code in v5.6.dev to std::memset.

**Comment by philipianpearce** [comment]
@prlw1  also did you get my comment on #597?
