### ISSUE TITLE
v5.5.5r - doesn't compile under OpenBSD

### ISSUE THREAD

**Issue by drtmk** [e2guardian/e2guardian#814]
2 issues:
In Socket.cpp you're using a function `SSL_has_pending()` that doesn't exist in LibreSSL.
In FatController.cpp line 1620, the compiler is expecting another ) at the end of the line: `DEBUG_debug("signal:", String(rc);`

**Comment by philipianpearce** [comment]
@drtmk   I have added conditional so that it will compile with LibreSSL and corrected DEBUG call in v5.5 branch. Please test and see if now OK.

**Comment by fredbcode** [comment]
Hi Philip

There is something wrong, at least with debian 

https://gitlab.com/fredbcode/e2guardian/-/jobs/6949182621

**Comment by philipianpearce** [comment]
Hi Fred, 

Thanks for the alert. 

Due to a typo in configure.ac. Correction posted in v5.5. 

Regards 
Philip

**Comment by drtmk** [comment]
Now it does compile successfully.
But src/Makefile contains `sysconfdir = ${prefix}/etc` insted of `sysconfdir = /etc` and that ends up in an executable file.


```
Error reading ${prefix}/etc/e2guardian/e2guardian.conf
Error parsing the e2guardian.conf file or other e2guardian configuration files
```
It was working fine in v5.5.5r

**Comment by philipianpearce** [comment]
I've had a look at this:- {prefix} is a built-in of the automake tools and so I cannot find a way to adjust automake behavior by modifying configure.ac. 

If you add a --sysconfdir option to the configure options this fixes the problem and prefix is defined in Makefile correctly as '/usr/local' 

Has anybody got any experience of automake that might explain this?
