### ISSUE TITLE
log_thread doesn't block signals

### ISSUE THREAD

**Issue by drtmk** [e2guardian/e2guardian#815]
The main thread blocks signals after the log_thread has been created. Because the log_thread does not handle signals, there is a chance that when the process receives a signal, instead of going to the main thread, it will go to the log_thread and the process will be terminated unexpectedly.

And this is what is happening. For OpenBSD you're using SIGALRM to interate the main loop every 5 seconds. Sometimes, the signal goes to the log_thread and the process is terminated. Other signals like SIGUSR1, SIGHUP might also end up in the wrong thread killing the process even under Linux.

The solution is to invoke `pthreads_sigmask` before creating log_thread.

**Comment by philipianpearce** [comment]
@drtmk - Thanks for this report, logic rearranged as you suggest.
