### ISSUE TITLE
v5.6 - permanent error in syslog log: Internal error - storage for field code 0 not defined

### ISSUE THREAD

**Issue by Luc-G-67** [e2guardian/e2guardian#821]
when client workstations browse the internet I constantly get this error in syslog. log: Internal error - storage for field code 0 not defined

I searched everywhere, I can't see where this error comes from.

access log is logformat3.  otherwise everything else works fine. no error.

at each line in access.log  (I replaced the website name with *)

1719234110.488 63440 128.3.3.212 - 4806 - https://******.com - - -
 i have this line 
log: Internal error - storage for field code 0 not defined
in syslog
thank you for your help

**Comment by philipianpearce** [comment]
Thanks for reporting this bug - The error was being generated whenever a Blank log field type is used - fixed in latest v5.6 branch

**Comment by Luc-G-67** [comment]
thank you very much it works with version 5.6.1
I had version 5.6.0
