### ISSUE TITLE
any plans for supporting TLS proxy chaining (secure proxy chain) ?

### ISSUE THREAD

**Issue by MrdUkk** [e2guardian/e2guardian#825]
title says all,
currently i see in source code  only plain-text is supported (configuration file vars proxyport & proxyip)

**Comment by philipianpearce** [comment]
I have no plans to implement upstream TLS proxy, as e2guardian is focused on web filtering and is now normally deployed without any upstream proxy. 

However, if anyone in the e2g community would like to code this feature it should not be too difficult. 

Although, the simplest way to get this effect would be to deploy a proxy that does support this feature on the same system as e2g an then use local ip address and port in e2g. This would be secure as it would just be local traffic within the system. 

Philip
