### ISSUE TITLE
 ConnectionHandler::get_TLS_SNI in bug

### ISSUE THREAD

**Issue by szrce** [e2guardian/e2guardian#831]
@philipianpearce  hi, i hope u weel, when client connect "t.co/oQBC0k5ocj" e2g not processing sni extract functions cause set it length < 8 break; 

![get_tls_sni_screenshots](https://github.com/user-attachments/assets/c4d53bcb-1ed1-4f95-99ca-1f0bb8a3c819)

https://github.com/e2guardian/e2guardian/blob/15be4494770e3b5749005be696a6177c8848e7c9/src/ConnectionHandler.cpp#L3430

![get_tls_sni_debugfrom_e2g](https://github.com/user-attachments/assets/3ff23f83-9f52-4625-aaff-6ba5b1355ed9)

**Comment by philipianpearce** [comment]
Check should be < 7 not < 8.  (Min length domain path is 4 bytes + 1 byte host type + 2 bytes length so minimum record length is 7).

Fixed in branch v5.5.
