### ISSUE TITLE
e2guardian as ICAP server

### ISSUE THREAD

**Issue by m8522s** [e2guardian/e2guardian#836]
Hi team,

I try to use **e2guardian** as ICAP server with content filtering for Squid, but run into issues.
Squid and E2g run on different machines. Squid invokes the E2guardian via ICAP with these configuration lines:

```
icap_enable on
icap_service_failure_limit -1
icap_default_options_ttl 60
adaptation_send_client_ip on
adaptation_send_username off
icap_client_username_encode off
icap_client_username_header X-Username
icap_preview_enable on
icap_preview_size 1024
icap_service response_mod respmod_precache icap://10.5.1.83/response
icap_service request_mod reqmod_precache icap://10.5.1.83/request
```
The IPv4 address 10.5.1.83 is the address of the e2guardian host.

The relevant configuration on the e2g host is:
```
icapport = 1344
icapreqmodurl = 'request'
icapresmodurl = 'response'
```

The e2g service starts without issues. However, the first ICAP query fails and the client receive the default `ICAP protocol error` message. The e2g process logs the debug message:
```
1732049442 hw7:  ICAP -persisting (count 1) Client IP: 10.5.1.1 handleICAPConnection():ConnectionHandler.cpp:3402
1732049442 hw7: Start of request ICAPheader:in in():ICAPHeader.cpp:486
1732049442 hw7: ICAPheader:in before getLine - timeout: 120000 in():ICAPHeader.cpp:505
1732049442 hw7: firstime: ICAPheader:in after getLine  in():ICAPHeader.cpp:508
1732049442 hw7: firstime: ICAPheader:in after getLine: rc: -1 truncated: 0 in():ICAPHeader.cpp:513
1732049442 hw7:  -ICAP Persistent connection closed handleICAPConnection():ConnectionHandler.cpp:3419
1732049442 hw7: ICAP -Attempting graceful connection close handleICAPConnection():ConnectionHandler.cpp:3542
```

Is this an error or some configuration missing? There is little information available in the Wiki, so I have to ask here.

Thanks for some insight.

**Comment by philipianpearce** [comment]
See https://github.com/e2guardian/e2guardian/blob/v5.5/notes/icap on using e2g icap with squid
And there also some background information at https://github.com/e2guardian/e2guardian/blob/v5.5/notes/ICAP_server_notes_for_implimenting_ICAP_client

**Comment by m8522s** [comment]
Thanks. I implemented the recommended configuration. However, `squid` (version 6.10) is not too happy and reports:
```
2024/11/20 21:33:35 kid1| essential ICAP service is down after an options fetch failure: icap://10.5.1.83/request [down,!opt]
    current master transaction: master54
```
Is this a configuration issue?

**Comment by m8522s** [comment]
This is a configuration issue, but on the Squid side. It is mandatory to put the port number in the `icap_service` line. I need to change my configuration from above to:
```
icap_service response_mod respmod_precache icap://10.5.1.83:1344/response
icap_service request_mod reqmod_precache icap://10.5.1.83:1344/request
```
Now Squid and e2guardian talk nicely via ICAP.
