### ISSUE TITLE
kqueue support

### ISSUE THREAD

**Issue by Alexander237** [e2guardian/e2guardian#88]
It would be nice to have kqueue support in e2guardian. This will dramatically increase performance on FreeBSD.

**Comment by philipianpearce** [comment]
We plan for the next version to replace poll/epoll with a threads based logic which should really increase performance for all platforms as well as simplifying the code.
Both Fred and I use the Linux platform, but if someone in the FreeBSD community can add kqueue support to the current version, and/or is able to help with the new version that would be great!

**Comment by prlw1** [comment]
Your plans for threads based logic sound good - how is it going? (If it is going well, then there is no point spending time on kqueue?)

**Comment by philipianpearce** [comment]
First V4 released with threads support - so kqueue support no longer needed
