### ISSUE TITLE
SSL SHA-1 Certificate

### ISSUE THREAD

**Issue by aaronsinclair** [e2guardian/e2guardian#89]
Hi. Thank you for your work and great software.. I have installed and configured e2guardian successfully and have been enjoying the benefits of this software for my family.  As part of this I am filtering SSL requests, however it appears that e2guardian is generating SHA-1 certificates - which causes an issue for Chrome browsers
![capture](https://cloud.githubusercontent.com/assets/15620481/10897096/2788d64c-8223-11e5-9ecd-316b6e78754b.PNG)

Checking the generated certificates shows SHA-1

 sudo openssl x509 -in 0A/13/7B/375CC3881A70E186CE2172C8D1 -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0a:13:7b:37:5c:c3:88:1a:70:e1:86:ce:21:72:c8:d1
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=NZ, ST=Some-State, O=CFS
        Validity
            Not Before: Dec  6 13:35:51 2014 GMT
            Not After : Dec  5 13:35:51 2024 GMT
        Subject: CN=www.google.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a8:65:b1:55:c0:bf:cd:49:9a:af:84:74:ea:27:
                    14:fe:db:7f:4d:8a:21:db:6c:94:8d:ce:1f:d8:be:
                    6a:bd:87:70:1b:7f:dd:8e:39:e3:4c:b6:0c:9a:58:
                    97:a9:dc:70:e3:b4:d8:04:66:f1:6b:d1:a4:a4:5a:
                    85:9b:b0:23:a1:67:c8:d2:32:ba:1f:72:d9:1d:56:
                    8e:38:b6:d1:71:6a:fb:16:bd:32:af:b7:c6:0b:3c:
                    39:f6:4e:3c:d0:22:99:65:a3:06:5e:ea:d2:0c:27:
                    70:e9:93:8a:1d:60:3b:7b:2e:f0:da:22:f0:0c:09:
                    ce:bd:17:38:41:11:17:24:7d:64:bd:a4:76:90:71:
                    5f:fe:93:64:2f:0e:03:28:9f:80:f3:e7:56:eb:de:
                    b1:cb:a3:0b:03:27:e5:84:c5:dc:96:b0:8b:d3:9f:
                    ab:54:4a:73:92:11:fd:35:89:48:6c:82:e6:6c:d5:
                    71:38:a0:3f:31:69:72:ec:f4:8c:cb:2c:97:44:80:
                    eb:7c:d9:a8:53:47:ba:c1:e2:5d:5a:75:2c:60:71:
                    45:df:fb:89:14:79:dc:2f:bc:07:dd:7a:05:f5:99:
                    9e:da:3c:3a:ba:f5:96:ed:a5:88:e2:d7:d7:8d:05:
                    d9:2c:69:b6:37:54:ea:10:22:a0:72:9c:97:6d:50:
                    26:7f
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha1WithRSAEncryption
         76:46:e9:35:a1:e4:c2:28:1e:b9:85:77:29:71:df:3d:21:a9:
         2a:f0:5a:32:e5:68:b1:44:bf:c2:ae:4f:7f:f5:5c:d4:2e:46:
         12:c1:3c:9d:ac:a2:91:3e:9c:a4:55:ae:c9:9e:31:0d:33:8a:
         09:6a:d2:f5:4a:d1:6d:bc:c6:a4:a0:97:eb:05:fc:65:b9:bb:
         8b:ac:3b:95:54:d3:61:41:16:c0:b9:40:2d:b0:c2:b8:f7:df:
         90:6d:e9:23:4c:e6:f3:32:bd:a9:08:92:e4:e5:3b:23:a3:3e:
         cb:93:74:71:73:31:95:b3:ab:e9:01:c4:81:ad:0f:d7:73:d9:
         c3:e3:49:83:78:6d:c2:6c:7f:d7:c1:d2:72:52:6d:43:73:49:
         4d:0c:a6:7a:b5:3c:20:9e:e8:b0:f4:e2:34:7c:17:e2:e4:85:
         7b:80:e1:3c:87:45:77:02:c2:d7:cc:5f:43:f9:5a:67:44:23:
         f2:bf:c2:c3:ff:75:0f:03:4f:5d:94:fb:71:c7:6b:b5:fd:14:
         c7:2e:ca:75:03:29:e7:a9:47:06:7c:db:25:92:8b:9d:e6:8c:
         84:6f:83:bf:0e:10:a9:c3:c6:0b:88:f8:0e:57:d7:15:c8:41:
         c8:fd:7b:18:fa:fa:d5:37:cd:81:1a:39:0f:26:71:66:99:d7:
         9b:82:cf:d5

I have ensured that my ROOT CA's are SHA-2 signed and confirm that there is no issue in IE / Edge

I wish to ensure that my users don't become complacent in accepting certificate errors and wonder if this is an easy fix in updating CertificateAuthority.cpp to sign using EVP_sha256

**Comment by aaronsinclair** [comment]
HI. 
I modified line 325 of /src/CertificateAuthority.cpp 

 if (!X509_sign(newCert, _caPrivKey, EVP_sha1())) {
        X509_free(newCert);
        return NULL;
    }


 if (!X509_sign(newCert, _caPrivKey, EVP_sha256())) {
        X509_free(newCert);
        return NULL;
    }

recompiled and it appears to be working (Im wondering how much other stuff i've broken in doing this).. 


Checking the SSL Certs now shows SHA256

#sudo openssl x509 -in 0A/13/7B/375CC3881A70E186CE2172C8D1 -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0a:13:7b:37:5c:c3:88:1a:70:e1:86:ce:21:72:c8:d1
    Signature Algorithm: **sha256WithRSAEncryption**
        Issuer: C=NZ, ST=Some-State, O=CFS
        Validity
            Not Before: Dec  6 13:35:51 2014 GMT
            Not After : Dec  5 13:35:51 2024 GMT
        Subject: CN=www.google.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a8:65:b1:55:c0:bf:cd:49:9a:af:84:74:ea:27:
                    14:fe:db:7f:4d:8a:21:db:6c:94:8d:ce:1f:d8:be:
                    6a:bd:87:70:1b:7f:dd:8e:39:e3:4c:b6:0c:9a:58:
                    97:a9:dc:70:e3:b4:d8:04:66:f1:6b:d1:a4:a4:5a:
                    85:9b:b0:23:a1:67:c8:d2:32:ba:1f:72:d9:1d:56:
                    8e:38:b6:d1:71:6a:fb:16:bd:32:af:b7:c6:0b:3c:
                    39:f6:4e:3c:d0:22:99:65:a3:06:5e:ea:d2:0c:27:
                    70:e9:93:8a:1d:60:3b:7b:2e:f0:da:22:f0:0c:09:
                    ce:bd:17:38:41:11:17:24:7d:64:bd:a4:76:90:71:
                    5f:fe:93:64:2f:0e:03:28:9f:80:f3:e7:56:eb:de:
                    b1:cb:a3:0b:03:27:e5:84:c5:dc:96:b0:8b:d3:9f:
                    ab:54:4a:73:92:11:fd:35:89:48:6c:82:e6:6c:d5:
                    71:38:a0:3f:31:69:72:ec:f4:8c:cb:2c:97:44:80:
                    eb:7c:d9:a8:53:47:ba:c1:e2:5d:5a:75:2c:60:71:
                    45:df:fb:89:14:79:dc:2f:bc:07:dd:7a:05:f5:99:
                    9e:da:3c:3a:ba:f5:96:ed:a5:88:e2:d7:d7:8d:05:
                    d9:2c:69:b6:37:54:ea:10:22:a0:72:9c:97:6d:50:
                    26:7f
                Exponent: 65537 (0x10001)
    Signature Algorithm: **sha256WithRSAEncryption**
         9b:e1:ad:cc:06:14:39:b5:a6:4c:df:b4:a1:6c:f3:53:6b:12:
         b8:91:f3:50:99:7b:c9:f0:c9:bd:cf:b9:22:ec:60:8b:4d:94:
         92:39:c8:8f:fe:4f:f3:65:8e:9c:99:2d:51:73:8e:95:e8:c1:
         e7:57:45:2b:97:32:0c:10:c3:10:9a:13:a3:4f:58:f7:11:42:
         95:9c:ff:76:70:d6:02:9d:4f:4c:4c:83:c9:0e:11:43:eb:1e:
         53:d2:de:31:a9:df:a6:bc:67:97:ce:c1:5e:5b:ee:aa:35:5b:
         d5:87:e6:82:cd:1a:c1:9e:69:16:31:6f:41:3b:19:60:b1:7c:
         44:0e:4f:ff:14:a2:23:90:20:2d:07:de:e5:d2:db:f1:56:0c:
         2b:de:54:6c:6d:2a:dc:b8:d0:0c:78:41:61:0f:11:54:22:85:
         7d:52:c5:89:d5:d2:7e:db:a2:08:e7:d7:01:00:a9:0b:11:3c:
         9f:e6:48:6d:44:3b:ba:9a:5d:f7:25:ae:26:c3:8b:16:5d:3f:
         30:d4:3c:e8:0c:1c:7f:f2:82:b4:f9:19:96:26:43:69:d4:3a:
         93:4f:b3:82:39:03:8a:48:9e:62:ed:1b:85:28:d0:dc:5a:7e:
         b6:c3:16:d2:a5:04:d8:0d:9a:05:d8:9c:b6:26:b6:94:b8:97:
         c1:c0:ea:29
![capture1](https://cloud.githubusercontent.com/assets/15620481/10897943/accfc9da-822a-11e5-9834-05936b1f7eff.PNG)

**Comment by fredbcode** [comment]
Thanks, yes SHA1 is depreciated now 
Microsoft will also breaks support in 2016
And the end of support is scheduled at 31 December 2016 (for all browsers)

"Your connection to www.google.co.nz is encrypted using an obsolete cipher suite" still present  because that RSA is used as the key exchange mechanism. 
Instead, we should use DHE_RSA or ECDHE_RSA.

To remove the 'obsolete' requirement, we'll need to get 'modern' cryptography which is defined as:

    TLS 1.2 or QUIC (protocol)
    AES_128_GCM or CHACHA20_POLY1305 (cipher)
    DHE_RSA or ECDHE_RSA or ECDHE_ECDSA (key exchange).

**Comment by fredbcode** [comment]
Ok thank, committed to the develop branch
Philip feel free to reverse if you you thing there is something wrong

**Comment by philipianpearce** [comment]
Looks good.
