### ISSUE TITLE
Content type or encoding consistent DENIED citing Norwegian or Japanese visiting a few sites-

### ISSUE THREAD

**Issue by 83GTIGuy** [e2guardian/e2guardian#90]
Visiting newegg.com and selecting sales items will bring up the following.  Bring up Amazon.com or yahoo.com does this sometimes too.
2015.11.8 2:03:58 - 192.168.40.114 http://www.newegg.com *DENIED* Banned combination phrase found.150 : 230 (��+��+��+��+��+��+��) GET 63810 230 adult (Japanese) 1 403 text/html     - - 

Based on the filter it seems to indicate adult Japanese content, but its an English site.  It seems that the characters displayed are utf-8 encoded?  I can't seem to find them in the content of the site.  Is this a content conversion error or content type error? Advice on fixing this filtering error?

**Comment by fredbcode** [comment]
Le 08/11/2015 03:39, 83GTIGuy a écrit :
>
> Visiting newegg.com and selecting sales items will bring up the 
> following. Bring up Amazon.com or yahoo.com does this sometimes too.
> 2015.11.8 2:03:58 - 192.168.40.114 http://www.newegg.com /DENIED/ 
> Banned combination phrase found.150 : 230 (��+��+��+��+��+��+��) GET 
> 63810 230 adult (Japanese) 1 403 text/html - -
>
> Based on the filter it seems to indicate adult Japanese content, but 
> its an English site. It seems that the characters displayed are utf-8 
> encoded? I can't seem to find them in the content of the site. Is this 
> a content conversion error or content type error? Advice on fixing 
> this filtering error?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/e2guardian/e2guardian/issues/90>.
>


Yes there is something wrong, can you show your bannedphraselist file ?*
*

**Comment by fredbcode** [comment]
Le 08/11/2015 03:39, 83GTIGuy a écrit :
>
> Visiting newegg.com and selecting sales items will bring up the 
> following. Bring up Amazon.com or yahoo.com does this sometimes too.
> 2015.11.8 2:03:58 - 192.168.40.114 http://www.newegg.com /DENIED/ 
> Banned combination phrase found.150 : 230 (��+��+��+��+��+��+��) GET 
> 63810 230 adult (Japanese) 1 403 text/html - -
>
> Based on the filter it seems to indicate adult Japanese content, but 
> its an English site. It seems that the characters displayed are utf-8 
> encoded? I can't seem to find them in the content of the site. Is this 
> a content conversion error or content type error? Advice on fixing 
> this filtering error?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/e2guardian/e2guardian/issues/90>.
>

And  weightedphraselist

**Comment by 83GTIGuy** [comment]
bannedphraselist:
.Include</etc/e2guardian/lists/phraselists/safelabel/banned>
.Include</etc/e2guardian/lists/phraselists/pornography/banned>

weightedphraselist:

#Good Phrases (to allow medical, education, news and other good sites)
.Include</etc/e2guardian/lists/phraselists/goodphrases/weighted_general>
.Include</etc/e2guardian/lists/phraselists/goodphrases/weighted_news>
.Include</etc/e2guardian/lists/phraselists/goodphrases/weighted_general_danish>
.Include</etc/e2guardian/lists/phraselists/goodphrases/weighted_general_dutch>
.Include</etc/e2guardian/lists/phraselists/goodphrases/weighted_general_malay>
.Include</etc/e2guardian/lists/phraselists/goodphrases/weighted_general_polish>
.Include</etc/e2guardian/lists/phraselists/goodphrases/weighted_general_portuguese>
.Include</etc/e2guardian/lists/phraselists/goodphrases/weighted_general_swedish>

#Pornography
.Include</etc/e2guardian/lists/phraselists/pornography/weighted>
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_chinese> #ALPHA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_danish> #ALPHA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_dutch> #BETA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_french>
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_german>
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_italian>
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_japanese> #ALPHA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_malay> #BETA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_norwegian> #BETA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_polish>
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_portuguese>
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_russian> #BETA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_russian_utf8> #BETA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_spanish> #ALPHA#
.Include</etc/e2guardian/lists/phraselists/pornography/weighted_swedish>
.Include</etc/e2guardian/lists/phraselists/nudism/weighted>

#Bad Words - swearing
.Include</etc/e2guardian/lists/phraselists/badwords/weighted_dutch> 
.Include</etc/e2guardian/lists/phraselists/badwords/weighted_french>
.Include</etc/e2guardian/lists/phraselists/badwords/weighted_german> #ALPHA#
.Include</etc/e2guardian/lists/phraselists/badwords/weighted_portuguese> #ALPHA#
.Include</etc/e2guardian/lists/phraselists/badwords/weighted_spanish> #ALPHA#

#Drugs
#.Include</etc/e2guardian/lists/phraselists/drugadvocacy/weighted>
#.Include</etc/e2guardian/lists/phraselists/illegaldrugs/weighted>
#.Include</etc/e2guardian/lists/phraselists/illegaldrugs/weighted_portuguese>
#.Include</etc/e2guardian/lists/phraselists/legaldrugs/weighted>

#Violence and intolerance
#.Include</etc/e2guardian/lists/phraselists/intolerance/weighted>
#.Include</etc/e2guardian/lists/phraselists/intolerance/weighted_portuguese>
#.Include</etc/e2guardian/lists/phraselists/gore/weighted>
#.Include</etc/e2guardian/lists/phraselists/gore/weighted_portuguese>
#.Include</etc/e2guardian/lists/phraselists/violence/weighted>
#.Include</etc/e2guardian/lists/phraselists/violence/weighted_portuguese>
#.Include</etc/e2guardian/lists/phraselists/weapons/weighted>
#.Include</etc/e2guardian/lists/phraselists/weapons/weighted_portuguese>

#Chat
#.Include</etc/e2guardian/lists/phraselists/chat/weighted>
#.Include</etc/e2guardian/lists/phraselists/chat/weighted_italian>

#Webmail
#.Include</etc/e2guardian/lists/phraselists/webmail/weighted>
#Note that if you enable the webmail weighted list you should also disable 
#the "exception_email" list in the exceptionphraselist file.

#Forums
#.Include</etc/e2guardian/lists/phraselists/forums/weighted> #BETA#

#Gambling
#.Include</etc/e2guardian/lists/phraselists/gambling/weighted>
#.Include</etc/e2guardian/lists/phraselists/gambling/weighted_portuguese>

#Productivity
#.Include</etc/e2guardian/lists/phraselists/games/weighted> #ALPHA#
#.Include</etc/e2guardian/lists/phraselists/news/weighted> #ALPHA#
#.Include</etc/e2guardian/lists/phraselists/personals/weighted>
#.Include</etc/e2guardian/lists/phraselists/personals/weighted_portuguese>
#.Include</etc/e2guardian/lists/phraselists/sport/weighted> #ALPHA#
#.Include</etc/e2guardian/lists/phraselists/travel/weighted>
#.Include</etc/e2guardian/lists/phraselists/music/weighted>

#System Management and Security
#.Include</etc/e2guardian/lists/phraselists/domainsforsale/weighted>
#.Include</etc/e2guardian/lists/phraselists/idtheft/weighted>
.Include</etc/e2guardian/lists/phraselists/malware/weighted> #BETA#
.Include</etc/e2guardian/lists/phraselists/proxies/weighted>
#.Include</etc/e2guardian/lists/phraselists/translation/weighted>
#.Include</etc/e2guardian/lists/phraselists/upstreamfilter/weighted>
.Include</etc/e2guardian/lists/phraselists/warezhacking/weighted>
#.Include</etc/e2guardian/lists/phraselists/peer2peer/weighted>

**Comment by fredbcode** [comment]
Ok please, add a comment # before BETA or ALPHA lines there is something wrong 
Do you have the complete url ?  
It's http://www.newegg.com/xxxx/xxxx or just http://www.newegg.com

**Comment by 83GTIGuy** [comment]
Commented out the weighted_japanese and weighted_norwegian lines and I no longer get the denied message.

some times I would get the error on the home page http://www.newegg.com and sometimes specifically http://www.newegg.com/Gaming/Store  
Here is the log for that specific denied message.
2015.11.8 16:17:06 - 192.168.40.114 http://www.newegg.com/Gaming/Store *DENIED* Banned combination phrase found.150 : 235 (��+��+��+��+��+��) GET 66803 235 Pornography (Japanese) 1 403 text/html     - -

**Comment by fredbcode** [comment]
OK I will make a try, thanks 
BETA and ALPHA are now disabled by default
