### ISSUE TITLE
httpS surf is broken when IP is assigned a filter group and ntlm-auth is enabled (Chrome, Opéra, IE,  ! not Firefox !)

### ISSUE THREAD

**Issue by ai99** [e2guardian/e2guardian#91]
Squid NTLM auth is enabled using a Samba3 domain controller.
e2guardian has 7 filter groups enabled.
A client's IP is assigned to "filter2".
Chrome, Opéra and IE cannot surf on https anymore :
* Chrome : ERR_PROXY_AUTH_UNSUPPORTED
* Opéra : "This web page is not available"
* IE : _white page_

Firefox works correctly, no problem.

**Comment by fredbcode** [comment]
More informations please 
Are you using SSLMITM ? There is something particular in E2's logs ?
No problem with X-Forwarde-For ? 

About squid there is a specific (NTLM ident) exclusion for the users from filter2 ? This an important point E2  doesn't makes any identification, just reads the result from Squid

**Comment by ai99** [comment]
Your "X-Forwarde-For" question made me test by changing :
```
    authplugin = '/etc/guardian/guardian0/common/ip.conf'
    authplugin = '/etc/guardian/guardian0/authplugins/proxy-ntlm.conf'
    authplugin = '/etc/guardian/guardian0/authplugins/proxy-basic.conf'
```
by :
```
    authplugin = '/etc/guardian/guardian0/authplugins/proxy-ntlm.conf'
    authplugin = '/etc/guardian/guardian0/authplugins/proxy-basic.conf'
    authplugin = '/etc/guardian/guardian0/common/ip.conf'
```

It looks like this has solve my problem. I can define ipgroups and use authentication and surf on http and https sites.

**Comment by fredbcode** [comment]
Ok thanks
