### ISSUE TITLE
/etc/e2guardian/lists/searchregexplist

### ISSUE THREAD

**Issue by aaronsinclair** [e2guardian/e2guardian#93]
Suggest adding comments to /etc/e2guardian/lists/searchregexplist in regard to mitm search regex.. 

Regardless of connection protocol, the match string is always http://
eg.. https://www.google.com is always and only matched in regex as http://google.com.

Im assuming that this may change in the future, so to cover our bases we should do regex that covers both protocol options.. eg;

#YOUTUBE
"^http[s]?://[0-9a-z]+.youtube\.[a-z]+[-/%.0-9a-z]*\?search_query=([^&]*)\&.*"->"\1"
"^http[s]?://[0-9a-z]+.youtube\.[a-z]+[-/%.0-9a-z]*\?search_query=([^&]*)"->"\1"
"^http[s]?://[0-9a-z]+\.google\.[a-z]+[-/%.?_&=#0-9a-z]*[&\?]?q=([^&]*)\&.*"->"\1"

#GOOGLE
"^http[s]?://[0-9a-z]+\.google\.[a-z]+[-/%.?_=#0-9a-z]*&q=([^&]*)"->"\1"
"^http[s]?://[0-9a-z]+\.google\.[a-z]+[-/%.?_&=#0-9a-z]*&q=([^&]*)\&.*"->"\1"

#BING
"^http[s]?://[0-9a-z]+\.bing\.[a-z]+[-/%.?_&=#0-9a-z]*?q=([^&]*)\&.*"->"\1"

  # BING SUGGESTIONS
"^http[s]?://[0-9a-z]+\.bing\.[a-z]+[-/%.?_&=#0-9a-z]*&qry=([^&]*).*"->"\1"
"^http[s]?://[0-9a-z]+\.bing\.[-/%.?_&=#0-9a-zA-Z]*&qry=([^&]*).*"->"\1"

#TWITTER
"^http[s]?://[0-9a-z]*[\.]?twitter\.[-/%.?_&=#0-9a-zA-Z]*[&?]q=([^&]*).*"->"\1"
"^http[s]?://[0-9a-z]*[\.]?twitter\.[-/%.?_&=#0-9a-zA-Z]*&query=([^&]*).*"->"\1"

#YAHOO

"^http[s]?://[0-9a-z]*\.[0-9a-z]*\.yahoo.[0-9a-z]*/.*p=([a-z0-9%-._~]*)"->"\1"

**Comment by philipianpearce** [comment]
Comments amended in develop branch - will incorporate into next release
