### ISSUE TITLE
Filtering additional mime types such as application/json, application/javascript etc

### ISSUE THREAD

**Issue by aaronsinclair** [e2guardian/e2guardian#94]
Hi. 
A lot of content is delivered via application/json, application/xml etc mime types and it appears that e2guardian does not apply any inspection (weighting, regex) to this content. 

I tested this by creating a file on a remote server and changing header types. 

MIME: text/javascript (Filter Success)
http://www.somedomain.com/json.php  GET     403     36      text/javascript -       -       137     -       0       *DENIED* Banned combination phrase found.50 : 70 ( boob+ sex + tit +boobs+naked)     70      Pornography     StrictFilterMode        1

MIME: text/plain (Filter Success)
http://www.somedomain.com/json.php  GET     403     36      text/plain      -       -       384     -       0       *DENIED* Banned combination phrase found.50 : 70 ( boob+ sex + tit +boobs+naked)     70      Pornography     StrictFilterMode        1

MIME: application/json (NO Filtering)
http://www.somedomain.com/json.php  GET     200     36      application/json        -       -       146     -       0               0               StrictFilterMode     1

MIME: application/javascript  (NO Filtering)
http://www.somedomain.com/json.php  GET     200     36      application/javascript  -       -       82      -       0               0               StrictFilterMode     1

Both application/json && application/javascript are not filtered -- Is there a mechanism by which I can specify mime types to filter?  

This issue is quite evident in the following examples... 
http://www.youtube.com/results?search_query=sexy+mo&spf=navigate       GET     200     25474   application/json
http://twitter.com/i/search/typeahead.json?count=10&filters=true&q=good+sex&result_type=topics%2Cusers&src=SEARCH_BOX GET     200     1295    application/json     -       -       363     -       0               0               StrictFilterMode 

Many thanks for your assistance.

**Comment by aaronsinclair** [comment]
In reviewing this I have found an older solution from 2011 posted for DG by Andy Balholm (see: https://groups.yahoo.com/neo/groups/dansguardian/conversations/topics/24973).  I have applied the changes outlined in the above URL and recompiled as of 7 days ago.  Content filtering is enabled on mime types as defined in the configuration file change below.

Note configuration change to /etc/e2guardian.conf does not include quotes anywhere otherwise it is not recognised...
textmimetypes = application/json,application/javascript,application/x-javascript

[dgPatchDetails.txt](https://github.com/e2guardian/e2guardian/files/42446/dgPatchDetails.txt)

**Comment by fredbcode** [comment]
I will post something similar this week 
Thank

**Comment by fredbcode** [comment]
Ok pushed some changes in dev branch 
textmimetypes = "application/json,application/javascript,application/x-javascript"
And weightedphrasemode are moved in e2guardianfx.conf

**Comment by aaronsinclair** [comment]
Hi Fred. I've tested this on the dev branch and there is a slight issue with the quotations in the configuration directive.. 

Configuration 
```
textmimetypes = "application/xhtml,application/xml,application/json,application/javascript,application/x-javascript"
```
The inner 3 mime types are filtered (xml,json & javascript) but the outer two mime types are passed (xhtml and x-javascript).

I tested this by buffering each side with 
```
textmimetypes = "application/ntop,application/xhtml,application/xml,application/json,application/javascript,application/x-javascript,application/bust"
```
This allowed had the behaviour of allowing xhtml, xml, json, javascript and x-javascript, but NOT mime type ntop and bust..

This got me thnking about the format of the directive -  I tried 
``` textmimetypes = application/xhtml,application/xml,application/json,application/javascript,application/x-javascript
``` (minus quotes) and all mime types were filtered...

**Comment by fredbcode** [comment]
Ok thanks, 
I think fixed now I also reduced CPU usage with high load and textmimetypes

The syntax
textmimetypes = "application/ntop,application/xhtml,application/xml,application/json,application/javascript,application/x-javascript,application/bust"
Was wrong, it should be
textmimetypes = 'application/ntop,application/xhtml,application/xml,application/json,application/javascript,application/x-javascript,application/bust'

**Comment by fredbcode** [comment]
Good for you ? I can close now ?

**Comment by aaronsinclair** [comment]
Thanks fred, go ahead and close issue.

**Comment by fredbcode** [comment]
Thank again for your help, Philip made some optimizations
