### ISSUE TITLE
Certificate issues 

### ISSUE THREAD

**Issue by philipianpearce** [e2guardian/e2guardian#96]
I'm now running e2g from the develop branch, my openSSL version is 1.0.1f 6 Jan 2014.

The domain www.familyfirst.org.nz opens fine but coursera still doesn't.

UPDATE: Noticed something different, coursera.org keeps loading forever, and when I return to the page after 5-7 minutes I find just the site logo has loaded and the rest of the page keeps taking forever to load. So I guess some progress has been made, since I'm not getting that redirect error anymore.

**Comment by philipianpearce** [comment]
This appears to be due to cert check failure in openssl for xxxxx.cloudfront.net - see http://stackoverflow.com/questions/27804710/python-urllib2-ssl-error for more info.

Looks as if need to upgrade to openssl 1.0.2 for a proper fix.

Meantime you could add cloudfront.net to your nocheckcertsitelist as a work round.

**Comment by philipianpearce** [comment]
Fix uploaded to develop.

Note:  This needs support for X509_V_FLAG_TRUSTED_FIRST in openssl.  Appeared in v1.0.2, but feature may be back ported in your distribution to v1.0.1.  (Supported in Centos6 with latest v1.0.1e).

E2g will compile with warning if X509_V_FLAG_TRUSTED_FIRST is not supported by openssl version, and some sites will get odd cert failures (e.g. xxx.cloudfront.net)

**Comment by aaronsinclair** [comment]
Thanks Philipianpearce -- No support for X509_V_FLAG_TRUSTED_FIRST in Ubuntu/Debian jessie openssl  1.0.1k-3+deb8u1    Just updating to 1.0.2d and will post feedback on this..

**Comment by aaronsinclair** [comment]
tested without any success... :-(
Env. Unbuntu jessie
```
openssl 1.0.2d-0ubuntu1  (sourced from https://launchpad.net/ubuntu/+source/openssl/1.0.2d-0ubuntu1)
 ca-certificates  20150426ubuntu1    (sourced from https://launchpad.net/ubuntu/xenial/+source/ca-certificates)
Latest e2g Develop branch
```

** Tested Sites https://cart.rackspace.com & https://www.coursera.org **

Coursera had many 302 redirects which ended badly.. 
```debug file: http://223.27.30.52/debug/coursea.debug.gz```
cart.rackspace.com didn't play nicely and did the same 302 redirect loop.
```debug file: http://223.27.30.52/debug/rackspace.debug.gz```

Any ideas are warmly welcomed... 

![ssl2](https://cloud.githubusercontent.com/assets/15620481/11498626/5f0d0584-9885-11e5-9f7b-21f0015e93ab.PNG)
![ssl3](https://cloud.githubusercontent.com/assets/15620481/11498635/6bf8ba54-9885-11e5-97d4-8e20eab70231.PNG)

**Comment by philipianpearce** [comment]
Looks like there are two issues - 
1. rackspace looping
2. cloudfront giving blank pages

Both appear to failing on openssl calls.

Would you check the following:-

  Do you have the updated openssl libaries on your server running e2g?

  Cloudfront is erroring because openssl is unable to negotiate connection with client - I've seen this before when I've changed generated certs and still had browser open from previous session.  Have you shut down browser completely before testing on the new settings?  You should be able to pick this up from the e2g access.log.   If this does not work try clearing the server certs for rackspace in the browser and restarting browser.

I have picked up one possible coding error from the debug log 'SSL_read() returned error 5' which I will look into, but this is not the cause of most of the issues.

Try using the cert bundle from http://curl.haxx.se/ca/cacert.pem and see if that improves things.

**Comment by aaronsinclair** [comment]
Yes, I had done the following before generating debug logs. 
1. Stopped e2g
2. Cleared generated Certificates.
3. Closed browser
4. started e2g then retested.

After testing with the new ca-certificates(20150426ubuntu1 ) I downloaded cert bundle from https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt

```
cd /usr/local/share/ca-certificates
wget https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt
update-ca-certificates
update-ca-certificates --fresh
```

I have now tried downloading http://curl.haxx.se/ca/cacert.pem and directly copying to to ca-certificates.crt
```
cp /etc/ssl/certs/ca-certificates.crt /root/ca-certificates.crt-orig
wget http://curl.haxx.se/ca/cacert.pem
cat cacert.pem > /etc/ssl/certs/ca-certificates.crt
```

Still no joy.... 

Question: does https://cart.rackspace.com work for you?

Libraries
```
 dpkg -l|grep ssl
ii  libcrypt-ssleay-perl           0.58-1+b2                  armhf        OpenSSL support for LWP
ii  libgnutls-openssl27:armhf      3.3.8-6+deb8u3             armhf        GNU TLS library - OpenSSL wrapper
ii  libio-socket-ssl-perl          2.002-2+deb8u1             all          Perl module implementing object oriented interface to SSL sockets
ii  libnet-smtp-ssl-perl           1.01-3                     all          Perl module providing SSL support to Net::SMTP
ii  libnet-ssleay-perl             1.65-1+b1                  armhf        Perl module for Secure Sockets Layer (SSL)
ii  libssl-dev:armhf               1.0.2d-0ubuntu1            armhf        Secure Sockets Layer toolkit - development files
ii  libssl-doc                     1.0.2d-0ubuntu1            all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:armhf              1.0.2d-0ubuntu1            armhf        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.0-dbg:armhf          1.0.2d-0ubuntu1            armhf        Secure Sockets Layer toolkit - debug information
ii  openssl                        1.0.2d-0ubuntu1            armhf        Secure Sockets Layer toolkit - cryptographic utility
```

**Comment by aaronsinclair** [comment]
*Meantime you could add cloudfront.net to your nocheckcertsitelist as a work round*
Adding sites to nocheckcertsitelist has no effect.

**Comment by philipianpearce** [comment]
I have investigated the rackspace issues and posted a fix.   The problems (at least on my system) was that sites with names longer than 64 bytes where being used.  As we use the domain name as the CN for the certificate the openssl cert generation was failing (with SEGV) as the max CN size is 64 bytes.  I have now modified the code so that sites with names longer than 64 generate a wildcard CN based on the
first domain path which is less than 62 bytes long with '*.' prepended to the front.   So,
752f77aa107738c25d93-f083e9a6295a3f0714fa019ffdca65c3.ssl.cf1.rackcdn.com
will have a cert with a CN of *.ssl.cf1.rackcdn.com.   This will also have the side effect of reducing the number of certificates needed of be generated and stored.
Hope this resolves the issue for you.

regards
Philip

**Comment by philipianpearce** [comment]
A new option for e2guardian.conf 'logsslerrors' has been posted to develop branch.  Defaults to 'off'.
When turned on gives detailed SSL errors in syslog.  Provides better clues as to why some sites are failing to connect.

**Comment by aaronsinclair** [comment]
Fantastic.. Will test today and get back to you.. Will certainly help with the 1056 SSL errors logged yesterday.. 

![graph](https://cloud.githubusercontent.com/assets/15620481/11665511/aad38d04-9e4c-11e5-8a82-b246479e4a0d.PNG)

![badssl](https://cloud.githubusercontent.com/assets/15620481/11665603/26ee6440-9e4d-11e5-99c1-b4f9e14c1702.PNG)

**Comment by fredbcode** [comment]
Fixed ?

**Comment by fredbcode** [comment]
aaronsinclair can you confirm that the fix works for you ?
For my information what is the name of you graphic tool ? https://cloud.githubusercontent.com/assets/15620481/11665603/26ee6440-9e4d-11e5-99c1-b4f9e14c1702.PNG

**Comment by aaronsinclair** [comment]
Hi Fred. 

 

Great thanks very much…  The graphic tool is an interface I built on top of e2g. 

The grid is from  <https://editor.datatables.net/> https://editor.datatables.net/ 

 

The network device is an Odroid, replaces DHCP on your network and becomes the gateway device. Also scans for other non dhcp devices and creates a “network device list” 

 



 

You can apply access time restrictions to each device. 

 



 

Apply filters for specific APPS

 



 

And of course report on network activity, good sites, bad sites, blocked searches etc… 

 

 

 

Aaron Sinclair 

Ruel Foundation - Give a Smile

 <http://www.giveasmile.co.nz/> 

Website:  <http://www.giveasmile.org> www.giveasmile.org   |  Email:  <mailto:aaron@sinclairs.co.nz> aaron@sinclairs.co.nz  |   Mob: +64 21 338 099

**Comment by fredbcode** [comment]
Nice result, it should be useful to write a few words about this
