### ISSUE TITLE
Allow access (to iPhone / Andriod apps) through header User-Agent

### ISSUE THREAD

**Issue by aaronsinclair** [e2guardian/e2guardian#97]
Hi. 
I'm working on allowing certain iphone apps open (unfiltered) access through e2guardian. 

As I see it, the issue is that a number of iPhone Apps don't or can't access the installed CA cert, so certs generated by e2g are rejected and the App doesn't work.  

One way I've circumvented this is to whitelist each of the domains that the App uses - however this is a bit of an unknown as they app may use many and varied domains over time.

Perhaps another solution would be to use the header _User-Agent_ string as a whitelist which would then negate the need to keep track of many whitelist domains

I had a look at a couple of apps to see if there was enough uniqueness to facilitate this.. 

> User-Agent: OzForex/2.16.0.0 CFNetwork/758.1.6 Darwin/15.0.0
> User-Agent: OzForex/2.16.0.0 (iPhone; iOS 9.1; Scale/2.00)
> User-Agent: Microsoft Office OneNote 2014
> User-Agent: trademe/3.0.41 (iPhone; iOS 9.1; Scale/2.00)

There is already the bannedregexpheaderlist - would it be a difficult or tedious addition to have an exceptionregexheaderlist ?

Would anyone else use/need this?

Thoughts???

**Comment by fredbcode** [comment]
>     User-Agent: OzForex/2.16.0.0 CFNetwork/758.1.6 Darwin/15.0.0
>     User-Agent: OzForex/2.16.0.0 (iPhone; iOS 9.1; Scale/2.00)
>     User-Agent: Microsoft Office OneNote 2014
>     User-Agent: trademe/3.0.41 (iPhone; iOS 9.1; Scale/2.00)
>
> There is already the bannedregexpheaderlist - would it be a difficult 
> or tedious addition to have an exceptionregexheaderlist ?
>

I guess not, but it should be really insecure
You can easily change the user agent ...

>

**Comment by fredbcode** [comment]
A list of User-Agent with SSLMITM disabled ?

**Comment by philipianpearce** [comment]
I agree with Fred's comments. 

But I think it may be useful to have an exceptionuseragentlist so that these can tunnel through on https. Not too difficult to implement with suitable health warnings. I will add it to the wish list for the next major version. 

Note: This may work where the app is using the explicit proxy settings for https. 

It can not work with any future transparent https, as e2g will have no idea what the user agent is! 

Regards 

Philip 

----- Original Message -----

**Comment by fredbcode** [comment]
Hi,
I'm working on a new auth plugin based on header value
It seems work good now

Eg: I added Mozilla/5.0 (Windows NT 6.1; rv:47.0) Gecko/20100101 Firefox/47.0=filter3 
to the my groups file

And added, header = 'user-agent', in the new proxy-header.conf 
Now all users with Firefox/47 **and** w7 are automatically added to group3
The users with another user-agent are added to group1 (banned group here) so it's also a, very simple, kind of identification

This is not related with any authentication from Squid so you can make combination ...
But as I said before this is insecure

**Comment by aaronsinclair** [comment]
This is awesome. Will test shortly.  Many thanks for your work on this!!

Kind regards

Aaron Sinclair

Mob: (64) 021 338 099
Ph: (64) 7577 1948

**Comment by fredbcode** [comment]
Thanks, the code is in the dev branch now

**Comment by brnmckllr** [comment]
@aaronsinclair How did you "whitelist" the domains you are having problems with? We are struggling getting the App store functioning. Whitelisting apple domains isn't an issue for us for the protection we are trying to provide.

**Comment by aaronsinclair** [comment]
I'm assuming you mean iTunes on a workstation accessing App Store, not mobile app?? From memory there is an issue with iTunes proxy settings. Check your workstation error logs. 

Kind regards

Aaron Sinclair

Mob: (64) 021 338 099
Ph: (64) 7577 1948

**Comment by fredbcode** [comment]
Fixed in 3.5.0
