### ISSUE TITLE
Search Term Blocking does not work

### ISSUE THREAD

**Issue by lupusrex** [e2guardian/e2guardian#98]
Dear all,

I have tried to enable search term blocking in the current develop branch (as of 13.12.2015) without any success. It worked fine in the master branch. I tried Google searches with Firefox and the following settings were enabled in e2guardianf1.conf:

weightedphrasemode = 1
naughtynesslimit = 50
searchregexplist = '/etc/e2guardian/lists/searchregexplist'
searchtermlimit = 10

I used the same regular expression settings in searchregexplist for the master and develop branches.

**Comment by philipianpearce** [comment]
I have pushed some further changes. Would you try again? 

Regards 

Philip 

----- Original Message -----

**Comment by lupusrex** [comment]
Dear Philip,

Thank you for your quick response. I have tried again.

Please note that I am using search term block method 2 without defining any further lists (except regexpressionlist).

Therefore e2guardian should fall back to the filtering methods for web content. I do not observe that e2guardian applies phraselists/googlesearches/banned - which I would like to use to protect my three children.

Some information about the build:
./configure --prefix=/usr --enable-clamd=yes --with-proxyuser=e2guardian --with-proxygroup=e2guardian --sysconfdir=/etc --localstatedir=/var --enable-icap=yes --enable-commandline=yes --enable-email=yes --enable-ntlm=yes --enable-trickledm=yes --mandir=/share/man --infodir=/share/info --enable-sslmitm=yes --enable-pcre=yes --with-filedescriptors=1024  && make -j2

I get a blocked site if i use i.e. the word “sex” because of a "banned combination phrase” 

2015.12.14 14:32:32 wolfgang 192.168.240.33 https://www.google.de/search?q=sex&ie=utf-8&oe=utf-8&gws_rd=cr&ei=78RuVqibOMbdaPbpgrgC *DENIED* Banned combination phrase found.50 : 200 ((-gun, control)+(foto, sex)+

I do not get a blocked site due to search term block: I tested in Firefox with a word manually entered to phraselists/googlesearches/banned (such as “marius") still does not work.

2015.12.14 15:12:45 wolfgang 192.168.240.33 https://www.google.de/search?q=marius  GET 227821 0  4 200 text/html  Wolfgang  0=marius; - - 
2015.12.14 15:12:47 wolfgang 192.168.240.33 https://www.google.de/gen_204?atyp=i&ct=&cad=&vet=10ahUKEwi0uN-ixNvJAhVGTBQKHYHSD4sQ-CcIHw..s&ei=XM5uVrSaMsaYUYGlv9gI&zx=1450102366766  GET 0 0  4 204 text/html  Wolfgang   - - 

I adapted the searchregexprlist to include "^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*search\?q=([^&]*).*"->”\1”
I checked it against the request URL using regexpr.com … Do you have any ideas ?
If you need some further information please let me know.

Cheers,
Wolfgang

**Comment by philipianpearce** [comment]
----- Original Message -----

> From: "lupusrex" <notifications@github.com>
> To: "e2guardian/e2guardian" <e2guardian@noreply.github.com>
> Cc: "Philip Pearce" <philip.pearce@e2bn.org>
> Sent: Monday, 14 December, 2015 2:20:17 PM
> Subject: Re: [e2guardian] Search Term Blocking does not work (#98)

> I do not observe that e2guardian applies
> phraselists/googlesearches/banned - which I would like to use to
> protect my three children.

This phrase list has not worked for a number of years. It used to work on the returned content, but 
since Google started to use javascript to return data it does not work. We should now take it out of the distribution, although it is sometimes useful for reference. 

The search term filtering has replaced this. Also, the phrase list would only work with google. The newer search term filtering will work with any defined search engine. 

> I get a blocked site if i use i.e. the word “sex” because of a
> "banned combination phrase”

> 2015.12.14 14:32:32 wolfgang 192.168.240.33
> https://www.google.de/search?q=sex&ie=utf-8&oe=utf-8&gws_rd=cr&ei=78RuVqibOMbdaPbpgrgC
> *DENIED* Banned combination phrase found.50 : 200 ((-gun,
> control)+(foto, sex)+

> I do not get a blocked site due to search term block: I tested in
> Firefox with a word manually entered to
> phraselists/googlesearches/banned (such as “marius") still does not
> work.

> 2015.12.14 15:12:45 wolfgang 192.168.240.33
> https://www.google.de/search?q=marius GET 227821 0 4 200 text/html
> Wolfgang 0=marius; - -
> 2015.12.14 15:12:47 wolfgang 192.168.240.33
> https://www.google.de/gen_204?atyp=i&ct=&cad=&vet=10ahUKEwi0uN-ixNvJAhVGTBQKHYHSD4sQ-CcIHw..s&ei=XM5uVrSaMsaYUYGlv9gI&zx=1450102366766
> GET 0 0 4 204 text/html Wolfgang - -

> I adapted the searchregexprlist to include
> "^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*search\?q=([^&]*).*"->”\1”
> I checked it against the request URL using regexpr.com … Do you have
> any ideas ?

Yes, there seems to be something different happening on the www.google.de site than www.google.com. I got it to work OK by having the following in searchregexplist:- 

"^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*\?q=([^&]*)\&.*"->"\1" 
"^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*\?q=([^&]*)"->"\1" 
"^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*/.*\&q=([^&]*).*"->"\1" 
"^http://[0-9a-z]+\.google\.[a-z]+[-/%.0-9a-z]*/.*\&q=([^&]*)"->"\1" 

Regards 
Philip
